### ISSUE TITLE
The text is deleted when press Enter

### ISSUE THREAD

**Issue by MBudkin** [laurent22/joplin#10002]
### Operating system

Windows

### Joplin version

2.13.15

### Desktop version info

Joplin 2.13.15 (prod, win32)

### Current behaviour

I added a picture in Joplin.

If there is text after the picture, the cursor is after the picture and after the picture I press Enter to retreat - everything is fine.
But! If I change the size of the picture, then text and a cursor appear after the picture - when I press Enter, the TEXT AFTER THE PICTURE IS DELETED.
The video is attached in a zip archive.

[2024-02-26 00-42-02.zip](https://github.com/laurent22/joplin/files/14397946/2024-02-26.00-42-02.zip)

**Comment by roman-r-m** [comment]
I can replicate this consistently. Whenever this happens I also see this error in dev tools
```
tinymce.min.js:9 Uncaught DOMException: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.
    at file:///tmp/.mount_JoplinKc969g/resources/app.asar/vendor/lib/tinymce/tinymce.min.js:9:94159
    at h (file:///tmp/.mount_JoplinKc969g/resources/app.asar/vendor/lib/tinymce/tinymce.min.js:9:89040)
    at Object.insertAfter (file:///tmp/.mount_JoplinKc969g/resources/app.asar/vendor/lib/tinymce/tinymce.min.js:9:94077)
    at fC (file:///tmp/.mount_JoplinKc969g/resources/app.asar/vendor/lib/tinymce/tinymce.min.js:9:305635)
    at file:///tmp/.mount_JoplinKc969g/resources/app.asar/vendor/lib/tinymce/tinymce.min.js:9:309230
    at Object.fold (file:///tmp/.mount_JoplinKc969g/resources/app.asar/vendor/lib/tinymce/tinymce.min.js:9:25048)
    at DC (file:///tmp/.mount_JoplinKc969g/resources/app.asar/vendor/lib/tinymce/tinymce.min.js:9:309194)
    at file:///tmp/.mount_JoplinKc969g/resources/app.asar/vendor/lib/tinymce/tinymce.min.js:9:312651
    at Object.ignore (file:///tmp/.mount_JoplinKc969g/resources/app.asar/vendor/lib/tinymce/tinymce.min.js:9:212895)
    at Object.ignore (file:///tmp/.mount_JoplinKc969g/resources/app.asar/vendor/lib/tinymce/tinymce.min.js:9:270416)
    at Object.transact (file:///tmp/.mount_JoplinKc969g/resources/app.asar/vendor/lib/tinymce/tinymce.min.js:9:212826)
    at Object.transact (file:///tmp/.mount_JoplinKc969g/resources/app.asar/vendor/lib/tinymce/tinymce.min.js:9:270340)
    at Tx.<anonymous> (file:///tmp/.mount_JoplinKc969g/resources/app.asar/vendor/lib/tinymce/tinymce.min.js:9:312575)
    at ux.fire (file:///tmp/.mount_JoplinKc969g/resources/app.asar/vendor/lib/tinymce/tinymce.min.js:9:358366)
    at Tx.fire (file:///tmp/.mount_JoplinKc969g/resources/app.asar/vendor/lib/tinymce/tinymce.min.js:9:361730)
    at lx (file:///tmp/.mount_JoplinKc969g/resources/app.asar/vendor/lib/tinymce/tinymce.min.js:9:360504)
    at Object.e (file:///tmp/.mount_JoplinKc969g/resources/app.asar/vendor/lib/tinymce/tinymce.min.js:9:360956)
    at ci.executeHandlers (file:///tmp/.mount_JoplinKc969g/resources/app.asar/vendor/lib/tinymce/tinymce.min.js:9:59612)
    at HTMLBodyElement.o (file:///tmp/.mount_JoplinKc969g/resources/app.asar/vendor/lib/tinymce/tinymce.min.js:9:56746)
```

**Comment by VartikaB** [comment]
This error typically occurs when attempting to append a DOM element as a child to its own parent element, which is not allowed in HTML.

**Comment by RafaR13** [comment]
Hi, i've come across this issue and would like to try and solve it

**Comment by laurent22** [comment]
I suspect this is a bug in TinyMCE which might be difficult to fix
