### ISSUE TITLE
 Error: Unable to resolve module ../lib/rnInjectedJs/noteBodyViewerBundle.bundle

### ISSUE THREAD

**Issue by minh-dai** [laurent22/joplin#10139]
### Operating system

iOS and Android

### Joplin version

last version

### Current behaviour

1: clone project
2: yarn install
3: cd ios folder (in app-mobile folder)
4: pod install
5: use Xcode run

### Expected behaviour

open the app.

### Logs

error: Error: Unable to resolve module ../lib/rnInjectedJs/noteBodyViewerBundle.bundle from /Users/minhdai/Desktop/ElectronProject/joplin/packages/app-mobile/utils/shim-init-react.js: 

None of these files exist:
  * lib/rnInjectedJs/noteBodyViewerBundle.bundle(.native|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * lib/rnInjectedJs/noteBodyViewerBundle.bundle/index(.native|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  20 | 	svgEditorBundle: require('../lib/rnInjectedJs/svgEditorBundle.bundle'),
  21 | 	pluginBackgroundPage: require('../lib/rnInjectedJs/pluginBackgroundPage.bundle'),
> 22 | 	noteBodyViewerBundle: require('../lib/rnInjectedJs/noteBodyViewerBundle.bundle'),
     | 	                               ^
  23 | };
  24 |
  25 | function shimInit() {
    at ModuleResolver.resolveDependency (/Users/minhdai/Desktop/ElectronProject/joplin/packages/app-mobile/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:137:15)
    at DependencyGraph.resolveDependency (/Users/minhdai/Desktop/ElectronProject/joplin/packages/app-mobile/node_modules/metro/src/node-haste/DependencyGraph.js:260:43)
    at Object.resolve (/Users/minhdai/Desktop/ElectronProject/joplin/packages/app-mobile/node_modules/metro/src/lib/transformHelpers.js:177:21)
    at Graph._resolveDependencies (/Users/minhdai/Desktop/ElectronProject/joplin/packages/app-mobile/node_modules/metro/src/DeltaBundler/Graph.js:432:35)
    at Graph._processModule (/Users/minhdai/Desktop/ElectronProject/joplin/packages/app-mobile/node_modules/metro/src/DeltaBundler/Graph.js:218:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Graph._addDependency (/Users/minhdai/Desktop/ElectronProject/joplin/packages/app-mobile/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
    at async Promise.all (index 33)
    at async Graph._processModule (/Users/minhdai/Desktop/ElectronProject/joplin/packages/app-mobile/node_modules/metro/src/DeltaBundler/Graph.js:263:5)
    at async Graph._addDependency (/Users/minhdai/Desktop/ElectronProject/joplin/packages/app-mobile/node_modules/metro/src/DeltaBundler/Graph.js:314:20)

**Comment by minh-dai** [comment]
![Screenshot 2024-03-16 at 14 47 57](https://github.com/laurent22/joplin/assets/24986640/9ca85e21-cf7e-4d06-bfb7-173980925821)
i checked the code and something wrong in this line.

**Comment by personalizedrefrigerator** [comment]
See https://github.com/laurent22/joplin/pull/10132
