### ISSUE TITLE
Sync fails with "Trust anchor for certification path not found" on Android when using Joplin Server

### ISSUE THREAD

**Issue by mu88** [laurent22/joplin#10144]
### Operating system

Android

### Joplin version

2.14.9

### Current behaviour

When syncing my data from my own Joplin Server on a new Android tablet for the very first time, the sync fails with `Trust anchor for certification path not found.`

Since Joplin Server is running on my Raspberry Pi 4 and I'm using my own PKI, I've enabled _Ignore TLS certificate errors_ and _Check synchronization configuration_ succeeds.

Please note that it works on several other devices (Android phones, Android tablets, Windows 10, Windows 11).

### Expected behaviour

No error should occur on sync.

### Logs

```
03-17T17:48:30: RevisionService: "maintenance: Done in 32909ms"
03-17T17:48:29: RevisionService: "collectRevisions: Created revisions for 0 notes"
03-17T17:48:29: RevisionService: "maintenance: Done in 168ms"
03-17T17:48:29: RevisionService: "maintenance: Service is enabled"
03-17T17:48:29: RevisionService: "maintenance: Starting..."
03-17T17:47:57: RevisionService: "maintenance: Service is enabled"
03-17T17:47:57: RevisionService: "maintenance: Starting..."
03-17T17:47:01: RevisionService: "maintenance: Done in 111ms"
03-17T17:47:01: RevisionService: "collectRevisions: Created revisions for 0 notes"
03-17T17:47:01: RevisionService: "maintenance: Service is enabled"
03-17T17:47:01: RevisionService: "maintenance: Starting..."
03-17T17:46:26: "ResourceService::deleteOrphanResources:", "[]"
03-17T17:46:26: RevisionService: "maintenance: Done in 43727ms"
03-17T17:46:26: "ResourceService::indexNoteResources: Completed"
03-17T17:46:26: RevisionService: "collectRevisions: Created revisions for 0 notes"
03-17T17:46:26: RevisionService: "maintenance: Done in 95ms"
03-17T17:46:26: RevisionService: "maintenance: Service is enabled"
03-17T17:46:26: RevisionService: "maintenance: Starting..."
03-17T17:45:42: "ResourceService::indexNoteResources: Start"
03-17T17:45:42: RevisionService: "maintenance: Starting..."
03-17T17:45:42: RevisionService: "maintenance: Service is enabled"
03-17T17:45:33: root: "root.biometrics: biometricsDone", "true"
03-17T17:45:33: root: "root.biometrics: biometricsEnabled", "false"
03-17T17:45:33: root: "root.biometrics: shouldShowMainContent", "true"
03-17T17:45:33: root: "root.biometrics: this.state.sensorInfo", "{"enabled":false,"sensorsHaveChanged":false,"supportedSensors":""}"
03-17T17:45:30: root: "root.biometrics: biometricsDone", "true"
03-17T17:45:30: root: "root.biometrics: biometricsEnabled", "false"
03-17T17:45:30: root: "root.biometrics: shouldShowMainContent", "true"
03-17T17:45:30: root: "root.biometrics: this.state.sensorInfo", "{"enabled":false,"sensorsHaveChanged":false,"supportedSensors":""}"
03-17T17:45:30: "DecryptionWorker: completed decryption."
03-17T17:45:30: "DecryptionWorker: starting decryption..."
03-17T17:45:29: "Updating all notifications..."
03-17T17:45:29: "Garbage collecting alarms..."
03-17T17:45:29: root: "root.biometrics: biometricsDone", "true"
03-17T17:45:29: root: "root.biometrics: biometricsEnabled", "false"
03-17T17:45:29: root: "root.biometrics: shouldShowMainContent", "true"
03-17T17:45:29: root: "root.biometrics: this.state.sensorInfo", "{"enabled":false,"sensorsHaveChanged":false,"supportedSensors":""}"
03-17T17:45:29: checkDisabledSyncItemsNotification: "No errors: Hiding notification"
03-17T17:45:29: Synchronizer: "Total folders: 0"
03-17T17:45:29: Synchronizer: "Total notes: 0"
03-17T17:45:29: Synchronizer: "Total resources: 3"
03-17T17:45:29: Synchronizer: "There was some errors:"
03-17T17:45:29: Synchronizer: "Error: uploadBlob: PUT https://myRaspi/joplinServer/api/items/root:/.resource/02f71a40c51e4e409b43f02cb409e99b:/content: Error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
Error: uploadBlob: PUT https://myRaspi/joplinServer/api/items/root:/.resource/02f71a40c51e4e409b43f02cb409e99b:/content: Error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
    at ?anon_0_ (address at index.android.bundle:1:3898788)
    at throw (native)
    at asyncGeneratorStep (address at index.android.bundle:1:550721)
    at _throw (address at index.android.bundle:1:551038)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (address at index.android.bundle:1:219452)
    at _callTimer (address at index.android.bundle:1:218401)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:218565)
    at callReactNativeMicrotasks (address at index.android.bundle:1:220529)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:121846)
    at anonymous (address at index.android.bundle:1:120939)
    at __guard (address at index.android.bundle:1:121687)
    at flushedQueue (address at index.android.bundle:1:120850)
    at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:120793)"
03-17T17:45:28: Synchronizer: "Operations completed: "
03-17T17:45:28: Synchronizer: "createRemote: 1"
03-17T17:45:28: Synchronizer: "Sync: finished: Synchronisation finished [1710693903718]"
03-17T17:45:28: ShareService: "Refreshed shares:", "{"items":[{"id":"sxePR8E6O3deDlsjttsSKk","type":3,"folder_id":"16e0c71b89dd4dcebc4501cc87389fbb","owner_id":"d9xWgHnakvnlFia89YNRJQ","master_key_id":"5b6331ff6057473c8907c514f6ed73b4","user":{"id":"d9xWgHnakvnlFia89YNRJQ"}},{"id":"uVrCxrxKwiqXJV2FUDljJ8","type":3,"folder_id":"e2f4dac2da9d4913858924f86788232e","owner_id":"d9xWgHnakvnlFia89YNRJQ","master_key_id":"0c234340c4a14229bd42007bf8b8ae73","user":{"id":"d9xWgHnakvnlFia89YNRJQ"}},{"id":"8UTOzJLR9Mgo2eznrLeQMo","type":3,"folder_id":"0a2598fdf2a74134b6e9395b4dfa0f8f","owner_id":"FIdcGTq2lCZ1W1PWdb4HTV","master_key_id":"2cd474624bee49ac837fd1b2a9816921","user":{"id":"FIdcGTq2lCZ1W1PWdb4HTV"}},{"id":"mvgooj5APQW0vXlYrJAOtM","type":3,"folder_id":"d018beb62d804c5db591e71e9885a5cd","owner_id":"8zqgWFIh9myTEFQ97t0XZH","master_key_id":"64009b8d6e824cb48f81204c0cdcffcd","user":{"id":"8zqgWFIh9myTEFQ97t0XZH"}}],"has_more":false}"
03-17T17:45:28: ShareService: "Refresh share invitations:", "[{"id":"ho4fOFdFetAOYcLuQOf21e","status":1,"master_key":{"checksum":"","encryption_method":6,"content":"{\"ppkId\":\"3mqgPUdDgh5nP0skVf5spV\",\"ciphertext\":\"cwoYBC2kysD5ZqR2CoyJA26aQtFfdJk8JJvBJ85emVRPnFbNZ/3hHUM56gOVLtrGmeGwCSf+OkSwM7z1Y8yFW0+Bow3L8j4KyVXkCsuCMdyUC6/TSqIKWcPrJRhZmQrpCvuhLaa/M0jBULo3QidbMXjB3gCnLeAY1ZKtk+gJsJhbgYXIGxTDJpHLtRgH5KkfY1N4mDZAADCIErdEjPFzEAHcEIW+ECNlu45hfVOPl4nK2urMw2t2Tmj+8Jz2G6bQh36xKGk2AP1/ITOZBLdWy+swXKzEwNZ0CSDqICCqH7UdumOSiM9GL5qJfl7tWG7MdvHxMDvGZWSP1DFlj+ZaepWzEMBGs+uac90IJrd/uvvD957DQ5CwuhyPriaZpQm+uSBwrSAQTQVdRAflXpS+9lCPeevKv1aFUXmomMGGCvPPDJuPyEJcV5Hoyn+gG7GBOfVW6qYFxKVrXslHQxY3rAcs1vg+HGJ/eFeScfrdQVBlUVnsj2YHWkKU6az062Y+8Ps5hcLqlLexBkN/oN7+dwmob6LyIrrMIpeTFwJnQMEIuOystEiFgb9yU5TO03MlRlE15IjCMSABK1Lm7GXzgAsr3Z9H5bunLJMRCdZGrdzBuUfp1x3qzg5R8VnJ+QwVWaUHlNvs9qKfqoMt+ZD2jiaUhj29fQmtWA2SfqgyY5+NQ679cg6Ygf+qlNwuKHeUBoXVefKkWNQmn4JkvrNRSLQeAFYyWNAjqv1HTUbirwKls37IpJlsr3W7yV3lvFl6qa0dDugirM7jNh5P+SeBs0DQuzabE3I3xZgypfb80qJJuNZEENOJtcPbSKs1Mno1PlCEC+SQIZEp7mE4Q39htt9z8j9gnrNd2uP7edJ/OHm3yHsXbr7TmWJ/WHCqgssIrcjphsQaYszz0ut7cRTpH7jCCAWGEC3FbigvoxdJ8mUhxxGxU1gO08+Lvmn0K0kPppu7xlUrodUmnZGAn1sAdVPiE9/iw25hZBmMXNJZnnM/GFrWwyntlpu0WGIMT3WL\"}","created_time":1689084038056,"updated_time":1689084038056,"source_application":"net.cozic.joplin-desktop","hasBeenUsed":false,"id":"2cd474624bee49ac837fd1b2a9816921"},"share":{"id":"8UTOzJLR9Mgo2eznrLeQMo","folder_id":"0a2598fdf2a74134b6e9395b4dfa0f8f","user":{"full_name":"Together","email":"together@myRaspi"}}},{"id":"XwgppskwOcI4nbTOjilIWX","status":1,"master_key":{"checksum":"","encryption_method":6,"content":"{\"ppkId\":\"3mqgPUdDgh5nP0skVf5spV\",\"ciphertext\":\"iXX1ihncCXpSHdllBOfqRdTM9w5DmnMeWJGXbASiXNLAFg8CsTV7wbcMEplqjX9TxFz9YFZp03BSTMOM8eZcCn/SXQFR2wb9MFx4Mtb8Qf0wX01ae77F2wQh1I/+sBUXdAOeoslqFWYY0Ch4A2yxzbRHgX7QYOxfHuKZU01JM4VQrsffYASGcxolw3busTDtIL+I/OOlDPgWW5fnVyUM5yWEScQr4fl4TApH9yL5O2B9/nlE75Mto2NHJuYrp7K6ianix/m4lu/OHMzwrh7xkYxsBTBOE8Hetq6FOBRtvCAXoez1od2MLSbmP5p7zq/y2fTwWBHCsCt3ROFdgt6OxirohQymRAlr1kBR99zelBo9MzpUmZdExB7uGm9iBWr7rEYlJYGQfgxjVn0etkjwWECTfphKrCaJzSS9iNdg1rPxP/GW63UXdSd4s5BBWfGLnxLeBSolnhxAyuCg3rzfMSLiax5f9TBXtx5FIJ98ze1p9azw03W8E0VLU44aR0gcZUBAPs+nxjj3KHLkUERlp+fAEFnVmkDrmU9tIjOQJt8a13q1auerg4Skxg1lKHRABkRXupBovMtbmHZ9IRw/jaFby4wJ2wZxqys4Nar94aXNck2Cq1BlQD2jU2Ox14p1Sc7qLcQf9Rgx1VQAoqpAI/zXSICwUDHa/2Kry1R3ca2MEW9ACoH7smQxUxvQJCifONcmDiXP1vvH2sSMjeC1gQAuR7kYGULcLdHSLbhKUM8hbdSYRJvG7UmWs8/9M8FAQ2Eqe9dUx88+knzNvWPFXRbOrdzAC1FIlSwcQlDhsBwpj08/40YSH0OjFTB9cmAId9VDRtd8fxfa3zYIngQeaJALakYF26ZVF/VMJIb4qOtODGFUXfFUXKZQOV9li70n4PliTkVOnpQmqAFKkGj50gUWeJ8pfd8amEoSoiATbnqnkH5tHuOcE36dMFWmsWfr/xYbVzapgb5auViPEwfcOCbWfK5Dr4k7D5bPJlzLEAiDJCTVJcgpczkzAXRqrta3\"}","created_time":1705835919945,"updated_time":1705835919945,"source_application":"net.cozic.joplin-desktop","hasBeenUsed":false,"id":"64009b8d6e824cb48f81204c0cdcffcd"},"share":{"id":"mvgooj5APQW0vXlYrJAOtM","folder_id":"d018beb62d804c5db591e71e9885a5cd","user":{"full_name":"Mirko IT","email":"mirko_it@myRaspi"}}}]"
03-17T17:45:28: Synchronizer: "Error: uploadBlob: PUT https://myRaspi/joplinServer/api/items/root:/.resource/02f71a40c51e4e409b43f02cb409e99b:/content: Error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
Error: uploadBlob: PUT https://myRaspi/joplinServer/api/items/root:/.resource/02f71a40c51e4e409b43f02cb409e99b:/content: Error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
    at ?anon_0_ (address at index.android.bundle:1:3898788)
    at throw (native)
    at asyncGeneratorStep (address at index.android.bundle:1:550721)
    at _throw (address at index.android.bundle:1:551038)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (address at index.android.bundle:1:219452)
    at _callTimer (address at index.android.bundle:1:218401)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:218565)
    at callReactNativeMicrotasks (address at index.android.bundle:1:220529)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:121846)
    at anonymous (address at index.android.bundle:1:120939)
    at __guard (address at index.android.bundle:1:121687)
    at flushedQueue (address at index.android.bundle:1:120850)
    at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:120793)"
03-17T17:45:27: JoplinServerApi: "curl -v -X PUT -H "Content-Type: application/octet-stream" -H "X-API-AUTH: ******" -H "X-API-MIN-VERSION: 2.6.0" -H "Content-Length: 8563" 'https://myRaspi/joplinServer/api/items/root:/.resource/02f71a40c51e4e409b43f02cb409e99b:/content'"
03-17T17:45:27: JoplinServerApi: "Code:", "undefined"
03-17T17:45:27: JoplinServerApi: "Error: uploadBlob: PUT https://myRaspi/joplinServer/api/items/root:/.resource/02f71a40c51e4e409b43f02cb409e99b:/content: Error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
Error: uploadBlob: PUT https://myRaspi/joplinServer/api/items/root:/.resource/02f71a40c51e4e409b43f02cb409e99b:/content: Error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
    at ?anon_0_ (address at index.android.bundle:1:3898788)
    at throw (native)
    at asyncGeneratorStep (address at index.android.bundle:1:550721)
    at _throw (address at index.android.bundle:1:551038)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (address at index.android.bundle:1:219452)
    at _callTimer (address at index.android.bundle:1:218401)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:218565)
    at callReactNativeMicrotasks (address at index.android.bundle:1:220529)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:121846)
    at anonymous (address at index.android.bundle:1:120939)
    at __guard (address at index.android.bundle:1:121687)
    at flushedQueue (address at index.android.bundle:1:120850)
    at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:120793)"
03-17T17:45:27: root: "root.biometrics: biometricsEnabled", "false"
03-17T17:45:27: root: "root.biometrics: shouldShowMainContent", "true"
03-17T17:45:27: root: "root.biometrics: this.state.sensorInfo", "{"enabled":false,"sensorsHaveChanged":false,"supportedSensors":""}"
03-17T17:45:27: root: "root.biometrics: biometricsDone", "true"
03-17T17:45:26: root: "root.biometrics: biometricsDone", "true"
03-17T17:45:26: root: "root.biometrics: biometricsEnabled", "false"
03-17T17:45:26: root: "root.biometrics: shouldShowMainContent", "true"
03-17T17:45:26: root: "root.biometrics: this.state.sensorInfo", "{"enabled":false,"sensorsHaveChanged":false,"supportedSensors":""}"
```

**Comment by mu88** [comment]
Do you have any idea what might be the problem, @laurent22?

**Comment by zff233** [comment]
I came across the same problem, on Android client, when I chose "Ignore TLS Certificate Error", but still showed certificate error in the following sync, changing to Http connection doesn 't cause this problem. Hope this problem can be solved in the subsequent update.

**Comment by mu88** [comment]
This is still an issue and needs help from @laurent22

**Comment by mu88** [comment]
This is still an issue and needs help

**Comment by mu88** [comment]
This is still an issue and needs help

**Comment by theopoon** [comment]
This is still an issue, cannot sync self host Joplin server from Android (confirm it works on iOS / Web / Win / Mac)

**Comment by mu88** [comment]
same here

**Comment by mu88** [comment]
this is still an issue

**Comment by mu88** [comment]
this is still an issue

**Comment by UsualNormie** [comment]
Same for me. 
I just set up my self hosted setup, and it works great with desktop apps (i.e. Windows 11, Ubuntu Desktop) - but fails on android mobile sync when using `Joplin Server (Beta)` as a sync destination. 
`Ignore TLS certificate errors` is already enabled.

Device is a Samsung Galaxy S20 Plus running Android 13 if that helps.
Device is on a seperate VLAN, but can definitely access the server's port. 

*Edit:* App retrieved from Google Play Store

**Comment by mu88** [comment]
this is still an issue

**Comment by ngulden** [comment]
I have the same issue. My error message is `Error: uploadBlob: PUT <address to resource>:/contentError: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`

I use joplin-server 2.14.2 for arm64 with self signed certificates managed by step-ca. On Android it's Joplin Mobile 3.2.7 on Android 14. The app synchronization ignores TLS certificate errors.

I'd like to have an option to provide the custom CA certificate for certificate validation.

**Comment by ngulden** [comment]
I could manage to add my custom CA certificate to my Android device. The error then disappears.

With Android 14, use the following steps:
1. Copy your CA certificate to your phone.
2. Open the settings and search for `certificate management app` or similar. I translate, because my Android is in German.
3. At *Install from device storage* select the option *CA certificate*
4. Confirm the *Install anyway* warning.
5. Select your custom CA certificate from your device.
6. Reopen your Joplin app and test your encrypted synchronization with your self-hosted Joplin Server.
7. You can even deactivate the option to ignore TLS certificate errors in your Joplin app.

**Comment by mu88** [comment]
@ngulden: unfortunately, that doesn't work for me. Even with my custom root CA installed on the tablet, the sync fails.

**Comment by mu88** [comment]
this is still an issue

**Comment by mu88** [comment]
this is still an issue

**Comment by mahyarmirrashed** [comment]
Still an issue.

**Comment by theopoon** [comment]
I have been trying to get this problem solve, and the following solve for my case.

My config has joplin setup in a docker with http, and a reverse proxy with SSL cert by Let's Encypt on a NGINX serving https, client set to connect via reverse proxy https address.

The problem from Android client with "Trust anchor for certification path not found" is resolved by changing my setup of SSL key on NGINX config to use fullchain.pem (which is a key file including the CA CERT instead of just cert.pem)

I suspect the same logic should also resolve issues for others going for direct https instead of NGINX setup, and this also resolve my issue with other similar setup services with Android clients over https connection.

REF: https://www.tsunderechen.io/2020/04/nginx-ssl-certificate-fullchain-vs-cert/

**Comment by mahyarmirrashed** [comment]
Yep, I just ended up enabling LetsEncrypt with the cert-manager.io operator, and used DNS01 for the solver with a web hook into my registrar since my deployment of Joplin is locked behind my Tailscale network.

**Comment by UsualNormie** [comment]
I did the same thing as @mahyarmirrashed , but that only solves the issue by providing a trusted certificate - so there will never be a TLS cert error to ignore. IMO this issue still persists, as "Ignore TLS certificate errors" will still throw errors for people using self-signed certificates.

**Comment by ajay10000** [comment]
I can confirm this is still an issue with Joplin on Android 16.  

My work-around was similar to the iPhone solution I found, using Caddy as reverse proxy for Joplin (both in Docker) and installing the Caddy root certificate on the phone.  (See [above post](https://github.com/laurent22/joplin/issues/10144#issuecomment-2605684443) from @ngulden)

**Comment by sarsey-walker** [comment]
This problems persists till today. 
Funny enough, if i disable "Ignore TLS certificate errors" There is no error, but the sync do not works.
[mobile-log.log](https://github.com/user-attachments/files/28592751/mobile-log.log)

**Comment by meglio** [comment]
Hello everyone. Guys... I installed Joplin with my own sync server at Synology since I'm moving away from iPhone, and the first thing I encounter is that I simply cannot use Joplin on my phone. This is not some UI inconvenience, but rather a complete deal breaker - I simply cannot start using the app. Should not it be high priority and critical? With it being open from 2024, should I expect it to not be fixed any time soon? Note, I imported my root certificate used for self-signed certificate into the OS, but it did not help.
