### ISSUE TITLE
Android: Unable to decrypt shared notebooks

### ISSUE THREAD

**Issue by ltsjoe** [laurent22/joplin#10339]
### Operating system

Android

### Joplin version

2.14.9

### Desktop version info

Linux Flatpak: 2.14.20 (Prod, Linux)
Windows: 2.14.20 (prod, win32)
Mac OS X: 2.14.20 (prod, darwin)

### Current behaviour

1. Configure accounts A and B on Joplin-Server
2. Configure E2EE on users A's and B's Joplin Desktop clients
3. Connect Joplin Desktop clients for users A and B to Joplin-Server
4. Connect Android client for user A to Joplin-Server and configure E2EE from data received from Joplin-Server on Android client
5. Create Shared Notebook on account A with Joplin Desktop
6. Share Notebook with account B via Joplin Desktop
7. Shared Notebook is decrypted on all Joplin Desktop clients but not the Android client

Question: Could there be an issue with the Android client pulling the public key for user B from the Joplin-Server?

![image](https://github.com/laurent22/joplin/assets/18501940/358c9bcb-dfd9-46a2-97db-efa2b845d001)
![image](https://github.com/laurent22/joplin/assets/18501940/41e0991a-eb07-489b-add4-7c4931eb9ea3)
![image](https://github.com/laurent22/joplin/assets/18501940/77af9ee6-b6ec-495d-860b-f238bf10b8a9)

### Expected behaviour

Joplin Android to decrypt shared Notebook

### Logs

04-20T12:32:54: Synchronizer: "There was some errors:"
04-20T12:32:54: Synchronizer: "Error: Could not encrypt item 2f8c669398894a869baca5cccfdb3ca7: Master key is not loaded: aa0b7c40ae784886bdf6293a00d73ecf
Error: Master key is not loaded: aa0b7c40ae784886bdf6293a00d73ecf
    at loadedMasterKey (address at index.android.bundle:1:1359126)
    at ?anon_0_ (address at index.android.bundle:1:1362896)
    at next (native)
    at anonymous (address at index.android.bundle:1:1357111)
    at tryCallTwo (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (address at index.android.bundle:1:1356938)
    at encryptAbstract_ (address at index.android.bundle:1:1362756)
    at ?anon_0_ (address at index.android.bundle:1:1364733)
    at next (native)
    at anonymous (address at index.android.bundle:1:1357111)
    at tryCallTwo (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (address at index.android.bundle:1:1356938)
    at encryptString (address at index.android.bundle:1:1364670)
    at ?anon_0_ (address at index.android.bundle:1:2611646)
    at next (native)
    at fulfilled (address at index.android.bundle:1:2603361)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (address at index.android.bundle:1:219452)
    at _callTimer (address at index.android.bundle:1:218401)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:218565)
    at callReactNativeMicrotasks (address at index.android.bundle:1:220540)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:121846)
    at anonymous (address at index.android.bundle:1:120939)
    at __guard (address at index.android.bundle:1:121687)
    at flushedQueue (address at index.android.bundle:1:120850)
    at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:120793)"
04-20T12:32:53: Synchronizer: "Error: Could not encrypt item 2f8c669398894a869baca5cccfdb3ca7: Master key is not loaded: aa0b7c40ae784886bdf6293a00d73ecf
Error: Master key is not loaded: aa0b7c40ae784886bdf6293a00d73ecf
    at loadedMasterKey (address at index.android.bundle:1:1359126)
    at ?anon_0_ (address at index.android.bundle:1:1362896)
    at next (native)
    at anonymous (address at index.android.bundle:1:1357111)
    at tryCallTwo (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (address at index.android.bundle:1:1356938)
    at encryptAbstract_ (address at index.android.bundle:1:1362756)
    at ?anon_0_ (address at index.android.bundle:1:1364733)
    at next (native)
    at anonymous (address at index.android.bundle:1:1357111)
    at tryCallTwo (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (address at index.android.bundle:1:1356938)
    at encryptString (address at index.android.bundle:1:1364670)
    at ?anon_0_ (address at index.android.bundle:1:2611646)
    at next (native)
    at fulfilled (address at index.android.bundle:1:2603361)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (address at index.android.bundle:1:219452)
    at _callTimer (address at index.android.bundle:1:218401)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:218565)
    at callReactNativeMicrotasks (address at index.android.bundle:1:220540)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:121846)
    at anonymous (address at index.android.bundle:1:120939)
    at __guard (address at index.android.bundle:1:121687)
    at flushedQueue (address at index.android.bundle:1:120850)
    at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:120793)"
04-20T12:29:46: Synchronizer: "There was some errors:"
04-20T12:29:46: Synchronizer: "Error: Could not encrypt item 96b83c3982ae4f0ca08de279d3f1ab44: Master key is not loaded: 2873635aa8c14290b889d0c0d473edce
Error: Master key is not loaded: 2873635aa8c14290b889d0c0d473edce
    at loadedMasterKey (address at index.android.bundle:1:1359126)
    at ?anon_0_ (address at index.android.bundle:1:1362896)
    at next (native)
    at anonymous (address at index.android.bundle:1:1357111)
    at tryCallTwo (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (address at index.android.bundle:1:1356938)
    at encryptAbstract_ (address at index.android.bundle:1:1362756)
    at ?anon_0_ (address at index.android.bundle:1:1364733)
    at next (native)
    at anonymous (address at index.android.bundle:1:1357111)
    at tryCallTwo (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (address at index.android.bundle:1:1356938)
    at encryptString (address at index.android.bundle:1:1364670)
    at ?anon_0_ (address at index.android.bundle:1:2611646)
    at next (native)
    at fulfilled (address at index.android.bundle:1:2603361)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (address at index.android.bundle:1:219452)
    at _callTimer (address at index.android.bundle:1:218401)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:218565)
    at callReactNativeMicrotasks (address at index.android.bundle:1:220540)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:121846)
    at anonymous (address at index.android.bundle:1:120939)
    at __guard (address at index.android.bundle:1:121687)
    at flushedQueue (address at index.android.bundle:1:120850)
    at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:120793)"
04-20T12:29:46: Synchronizer: "Error: Could not encrypt item 96b83c3982ae4f0ca08de279d3f1ab44: Master key is not loaded: 2873635aa8c14290b889d0c0d473edce
Error: Master key is not loaded: 2873635aa8c14290b889d0c0d473edce
    at loadedMasterKey (address at index.android.bundle:1:1359126)
    at ?anon_0_ (address at index.android.bundle:1:1362896)
    at next (native)
    at anonymous (address at index.android.bundle:1:1357111)
    at tryCallTwo (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (address at index.android.bundle:1:1356938)
    at encryptAbstract_ (address at index.android.bundle:1:1362756)
    at ?anon_0_ (address at index.android.bundle:1:1364733)
    at next (native)
    at anonymous (address at index.android.bundle:1:1357111)
    at tryCallTwo (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (address at index.android.bundle:1:1356938)
    at encryptString (address at index.android.bundle:1:1364670)
    at ?anon_0_ (address at index.android.bundle:1:2611646)
    at next (native)
    at fulfilled (address at index.android.bundle:1:2603361)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (address at index.android.bundle:1:219452)
    at _callTimer (address at index.android.bundle:1:218401)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:218565)
    at callReactNativeMicrotasks (address at index.android.bundle:1:220540)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:121846)
    at anonymous (address at index.android.bundle:1:120939)
    at __guard (address at index.android.bundle:1:121687)
    at flushedQueue (address at index.android.bundle:1:120850)
    at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:120793)"

**Comment by ltsjoe** [comment]
Oddly enough, this issue seemed to sort itself out? I was able to decrypt the shared notebook on my Android phone.

**Comment by ltsjoe** [comment]
Oddly enough, this issue seemed to sort itself out? I was able to decrypt the shared notebook on my Android phone.
