### ISSUE TITLE
Clicking on "New notebook" crashes the application

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#10590]
### Operating system

macOS

### Joplin version

3.0.9

### Current behaviour

May have been a one-off since I can't replicate it anymore.

- Right-click on a notebook
- Select "New notebook".

=> The application crashes with the below error:

* * *

## Message

window.EmojiButton is not a constructor

## Version info

Joplin for Desktop

Copyright © 2016-2024 Laurent Cozic
Joplin 3.0.7 (prod, darwin)

ID client :
Version de Synchro : 3
Version du profil : 47
Trousseau supporté : Oui

Révision : 8330833

Backup: 1.4.1
Rich Markdown: 0.15.0
Table Formatter Plugin: 1.2.1
Plugins
[
    {
        "id": "io.github.jackgruber.backup",
        "name": "Backup",
        "enabled": true,
        "version": "1.4.1"
    },
    {
        "id": "plugin.calebjohn.rich-markdown",
        "name": "Rich Markdown",
        "enabled": true,
        "version": "0.15.0"
    },
    {
        "id": "net.rmusin.joplin-table-formatter",
        "name": "Table Formatter Plugin",
        "enabled": true,
        "version": "1.2.1"
    }
]

## Stack trace

TypeError: window.EmojiButton is not a constructor
    at /Applications/Joplin.app/Contents/Resources/app.asar/gui/EditFolderDialog/IconSelector.js:54:19
    at commitHookEffectListMount (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23150:26)
    at commitPassiveMountOnFiber (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24926:13)
    at commitPassiveMountEffects_complete (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24891:9)
    at commitPassiveMountEffects_begin (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24878:7)
    at commitPassiveMountEffects (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24866:3)
    at flushPassiveEffectsImpl (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:27039:3)
    at flushPassiveEffects (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:26984:14)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:26769:9
    at workLoop (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/scheduler/cjs/scheduler.development.js:266:34)

## Component stack

    at IconSelector (/Applications/Joplin.app/Contents/Resources/app.asar/gui/EditFolderDialog/IconSelector.js:20:84)
    at div
    at div
    at div
    at div
    at div
    at div
    at div
    at I (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/styled-components/dist/styled-components.cjs.js:1:19269)
    at div
    at I (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/styled-components/dist/styled-components.cjs.js:1:19269)
    at Dialog (/Applications/Joplin.app/Contents/Resources/app.asar/gui/Dialog.js:33:70)
    at default_1 (/Applications/Joplin.app/Contents/Resources/app.asar/gui/EditFolderDialog/Dialog.js:29:64)
    at exports.ThemeProvider (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/styled-components/dist/styled-components.cjs.js:1:25001)
    at ae (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/styled-components/dist/styled-components.cjs.js:1:13440)
    at RootComponent (/Applications/Joplin.app/Contents/Resources/app.asar/gui/Root.js:104:1)
    at ConnectFunction (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-redux/lib/components/connect.js:246:74)
    at ErrorBoundary (/Applications/Joplin.app/Contents/Resources/app.asar/gui/ErrorBoundary.js:21:9)
    at Provider (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-redux/lib/components/Provider.js:19:3)

**Comment by X1Vi** [comment]
I was not able to reproduce this error

**Comment by laurent22** [comment]
I think what happens is that I use Joplin on two different macOS accounts, and upgraded it on one of them. So the other one was still working with a weird hybrid version that was part 3.0.7, part 3.0.9. So closing for now because that's probably not something we should worry about

**Comment by X1Vi** [comment]
alright thanks for updating
