### ISSUE TITLE
Error message "Error: ENOTSUP: operation not supported on socket" being displayed on the UI

### ISSUE THREAD

**Issue by luixxiul** [laurent22/joplin#10693]
### Operating system

Linux

### Joplin version

3.0.13

### Desktop version info

Joplin 3.0.13 (prod, linux)

Client ID: 9c3199ec203e4f018c9bff8ffe4b5288
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: 599cf5b

Backup: 1.4.1

### Current behaviour

1. Update Joplin to 3.0.13
2. Open it
3. Notes are displayed but the error message below is displayed on the UI (left-bottom, where the sync status is shown) <del>Notes are not displayed due to the error below:</del>
````
/tmp/user/1000/.mount_JoplingSWFwW/resources/app.asar/node_modules/@joplin/utils/dist/Logger.js:270 00:33:57: Synchronizer: Error: Error: Error: ENOTSUP: operation not supported on socket, read. Path: /media/sf_Syncthing/Notes/info.json. Path: /media/sf_Syncthing/Notes/info.json
    at FileApiDriverLocal.fsErrorToJsError_ (/tmp/user/1000/.mount_JoplingSWFwW/resources/app.asar/node_modules/@joplin/lib/file-api-driver-local.js:31:24)
    at FileApiDriverLocal.<anonymous> (/tmp/user/1000/.mount_JoplingSWFwW/resources/app.asar/node_modules/@joplin/lib/file-api-driver-local.js:130:28)
    at Generator.throw (<anonymous>)
    at rejected (/tmp/user/1000/.mount_JoplingSWFwW/resources/app.asar/node_modules/@joplin/lib/file-api-driver-local.js:6:65)
````

### Expected behaviour

The error should not happen and the notes should be displayed

**Comment by luixxiul** [comment]
After updating to the latest version, the notes and notebooks started to be displayed, but ` Error: Error: Error: ENOTSUP: operation not supported on socket, read. Path: /media/sf_Syncthing/Notes/info.json. Path: /media/sf_Syncthing/Notes/info.json` keeps to be displayed on the UI (left-bottom, where the sync status is rendered).

**Comment by luixxiul** [comment]
This does not seem to have been fixed yet.

**Comment by luixxiul** [comment]
This does not seem to have been fixed yet.
