### ISSUE TITLE
"Uncaught TypeError: Cannot set properties of null (setting 'width')" after starting Joplin

### ISSUE THREAD

**Issue by Perkolator** [laurent22/joplin#10742]
### Operating system

Linux

### Joplin version

3.0.13

### Desktop version info

Joplin 3.0.13 (prod, linux)

Client ID: f3416ea1eb8b45f9b787217c1fefc343
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: 599cf5b

Running Linux Mint 20.3 Cinnamon

### Current behaviour

1. Start Joplin (appimage).

= The dev tools console reports an error:

```
MainScreen.tsx:347 Uncaught TypeError: Cannot set properties of null (setting 'width')
    at MainScreen.tsx:347:15
    at Immer.produce (/tmp/.mount_Joplinw40N1X/resources/app.asar/node_modules/immer/dist/immer.cjs.development.js:775:16)
    at MainScreenComponent.updateRootLayoutSize (MainScreen.tsx:345:32)
    at MainScreenComponent.window_resize (MainScreen.tsx:282:8)
(anonymous) @ MainScreen.tsx:347
produce @ /tmp/.mount_Joplinw40N1X/resources/app.asar/node_modules/immer/dist/immer.cjs.development.js:775
updateRootLayoutSize @ MainScreen.tsx:345
window_resize @ MainScreen.tsx:282
Show 1 more frame
Show less
```

### Expected behaviour

No errors in console.

**Comment by Harshinireddy05** [comment]
Hey @personalizedrefrigerator I would like to work on this issue.

**Comment by personalizedrefrigerator** [comment]
> Hey @personalizedrefrigerator I would like to work on this issue.


That would be great (this has been a bug for a while)! For additional context, this seems to happen when the developer tools start with Joplin **and** the developer tools are docked to the main window.

**Note**: We generally don't assign issues.
