### ISSUE TITLE
Sync via WebDAV stopped working since 3.1.1 on Android

### ISSUE THREAD

**Issue by kolinger** [laurent22/joplin#10848]
### Operating system

Android

### Joplin version

3.1.1

### Current behaviour

Sync via WebDAV ends with error every time since I updated from 3.0.9 to 3.1.1. I didn't have any sync issues before and the desktop Joplin synces via the same WebDAV server/credentials just fine. I can connect to the WebDAV server via other app just fine from the same Android device.

The check of WebDAV credentials in the settings also reports the same error "Not implemented: httpAgent" as the sync. 

### Expected behaviour

The sync should work with valid WebDAV config?

### Logs

```
08-09T13:55:32: RevisionService: maintenance: Done in 96922ms
08-09T13:55:31: RevisionService: collectRevisions: Created revisions for 0 notes
08-09T13:55:31: RevisionService: maintenance: Done in 14ms
08-09T13:55:31: RevisionService: maintenance: Starting...
08-09T13:55:31: RevisionService: maintenance: Service is enabled
08-09T13:53:55: RevisionService: maintenance: Starting...
08-09T13:53:55: RevisionService: maintenance: Service is enabled
08-09T13:53:33: DecryptionWorker: completed decryption.
08-09T13:53:33: DecryptionWorker: starting decryption...
08-09T13:53:31: root: root.biometrics: biometricsDone <true>
08-09T13:53:31: root: root.biometrics: biometricsEnabled <false>
08-09T13:53:31: root: root.biometrics: shouldShowMainContent <true>
08-09T13:53:31: root: root.biometrics: this.state.sensorInfo {"enabled":false,"sensorsHaveChanged":false,"supportedSensors":""}
08-09T13:53:31: checkDisabledSyncItemsNotification: No errors: Hiding notification
08-09T13:53:31: Synchronizer: Total folders: 3
08-09T13:53:31: Synchronizer: Total notes: 704
08-09T13:53:31: Synchronizer: Total resources: 21
08-09T13:53:31: Synchronizer: There was some errors:
08-09T13:53:31: Synchronizer: Error: Not implemented: httpAgent
Error: Not implemented: httpAgent
    at httpAgent (address at index.android.bundle:1:840518)
    at ?anon_0_ (address at index.android.bundle:1:3069435)
    at next (native)
    at asyncGeneratorStep (address at index.android.bundle:1:3018966)
    at _next (address at index.android.bundle:1:3019221)
    at anonymous (address at index.android.bundle:1:3019173)
    at tryCallTwo (address at InternalBytecode.js:1:1222)
    at doResolve (address at InternalBytecode.js:1:2541)
    at Promise (address at InternalBytecode.js:1:1318)
    at anonymous (address at index.android.bundle:1:3019094)
    at apply (native)
    at exec (address at index.android.bundle:1:3068762)
    at ?anon_0_ (address at index.android.bundle:1:3150227)
    at next (native)
    at asyncGeneratorStep (address at index.android.bundle:1:3018966)
    at _next (address at index.android.bundle:1:3019221)
    at anonymous (address at index.android.bundle:1:3019173)
    at tryCallTwo (address at InternalBytecode.js:1:1222)
    at doResolve (address at InternalBytecode.js:1:2541)
    at Promise (address at InternalBytecode.js:1:1318)
    at anonymous (address at index.android.bundle:1:3019094)
    at apply (native)
    at get (address at index.android.bundle:1:3150120)
    at anonymous (address at index.android.bundle:1:3012020)
    at ?anon_0_ (address at index.android.bundle:1:3005670)
    at next (native)
    at fulfilled (address at index.android.bundle:1:3007816)
    at tryCallOne (address at InternalBytecode.js:1:1180)
    at anonymous (address at InternalBytecode.js:1:1874)
    at apply (native)
    at anonymous (address at index.android.bundle:1:289123)
    at _callTimer (address at index.android.bundle:1:288074)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:288218)
    at callReactNativeMicrotasks (address at index.android.bundle:1:290197)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:150858)
    at anonymous (address at index.android.bundle:1:149942)
    at __guard (address at index.android.bundle:1:150696)
    at flushedQueue (address at index.android.bundle:1:149853)
    at callFunctionReturnFlushedQueue (address at index.android.bundle:1:149709)
```

**Comment by bsavant** [comment]
Same issue on iOS with 13.1.1
