### ISSUE TITLE
Blank screen on share, subsequent shares not saved

### ISSUE THREAD

**Issue by Terrance** [laurent22/joplin#10850]
### Operating system

Android

### Joplin version

3.0.7

### Desktop version info

Not desktop, but the Android debug info for reference:

```
Joplin 3.0.7 (prod, android)

Client ID: d8e98c66054049f0b59e6d8c0db590b2
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Joplin Calendar: 1.2.0
Outline: 1.5.13

Android API level: 33
WebView version: 127.0.6533.66
WebView package: com.google.android.webview
FTS enabled: 1
Hermes enabled: 1
```

### Current behaviour

* Initial share of text content to Joplin led to a blank screen with just the grey top bar, no title/body fields.
* Leaving Joplin and sharing again showed the note editor with the shared content, but back navigation (from nav bar or system gestures) had no effect, leaving you stuck in the editor.
* Swiping the app away from recents and sharing again produces the same state.
* After force-closing the app, shares and regular app usage work again, but any notes from content shared during the initial and subsequent shares here were not persisted.

### Expected behaviour

Incoming shared content to be recognised and persisted consistently.

### Logs

📎 [syncReport-1723220079287-snip.txt](https://github.com/user-attachments/files/16565765/syncReport-1723220079287-snip.txt)

Possible exception of interest:

```
08-09T17:11:55,20,"AsyncActionQueue: Unhandled error: TypeError: right operand of 'in' is not an object
TypeError: right operand of 'in' is not an object
    at diffObjectsFields (address at index.android.bundle:1:1716431)
    at ?anon_0_ (address at index.android.bundle:1:5990985)
    at next (native)
    at fulfilled (address at index.android.bundle:1:5989858)
    at tryCallOne (address at InternalBytecode.js:1:1180)
    at anonymous (address at InternalBytecode.js:1:1874)
    at apply (native)
    at anonymous (address at index.android.bundle:1:286591)
    at _callTimer (address at index.android.bundle:1:285542)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:285686)
    at callReactNativeMicrotasks (address at index.android.bundle:1:287676)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:148328)
    at anonymous (address at index.android.bundle:1:147412)
    at __guard (address at index.android.bundle:1:148166)
    at flushedQueue (address at index.android.bundle:1:147323)
    at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:147266)"
```

Note that this log contains a number of sync errors due to not being on my local network -- I don't believe this to be relevant as I've also seen this issue at home with sync available.

This failure mode has so far only happened a couple of times since 3.0, and does not seem to be readily reproducible.

**Comment by pedromj** [comment]
I have seen this behavior for some time. I thought it was related to my particular settings. I see it is more general now.
