### ISSUE TITLE
Joplin on Android: Update to 3.1.1 breaks nextcloud sync

### ISSUE THREAD

**Issue by SwallowYourDreams** [laurent22/joplin#10872]
### Operating system

Android

### Joplin version

3.1.1

### Current behaviour

Updating to 3.1.1 breaks nextcloud sync for me. Sync times out with the error message "Not implemented: http agent". Reverting to 3.0.9 restores sync capability.

### Expected behaviour

Sync works.

### Logs

08-13T21:20:49: Synchronizer: There was some errors:
08-13T21:20:49: Synchronizer: Error: Not implemented: httpAgent
Error: Not implemented: httpAgent
    at httpAgent (address at index.android.bundle:1:839519)
    at ?anon_0_ (address at index.android.bundle:1:3067376)
    at next (native)
    at asyncGeneratorStep (address at index.android.bundle:1:3016907)
    at _next (address at index.android.bundle:1:3017162)
    at anonymous (address at index.android.bundle:1:3017114)
    at tryCallTwo (address at InternalBytecode.js:1:1222)
    at doResolve (address at InternalBytecode.js:1:2541)
    at Promise (address at InternalBytecode.js:1:1318)
    at anonymous (address at index.android.bundle:1:3017035)
    at apply (native)
    at exec (address at index.android.bundle:1:3066703)
    at ?anon_0_ (address at index.android.bundle:1:3148170)
    at next (native)
    at asyncGeneratorStep (address at index.android.bundle:1:3016907)
    at _next (address at index.android.bundle:1:3017162)
    at anonymous (address at index.android.bundle:1:3017114)
    at tryCallTwo (address at InternalBytecode.js:1:1222)
    at doResolve (address at InternalBytecode.js:1:2541)
    at Promise (address at InternalBytecode.js:1:1318)
    at anonymous (address at index.android.bundle:1:3017035)
    at apply (native)
    at get (address at index.android.bundle:1:3148063)
    at anonymous (address at index.android.bundle:1:3009961)
    at ?anon_0_ (address at index.android.bundle:1:3003611)
    at next (native)
    at fulfilled (address at index.android.bundle:1:3005757)
    at tryCallOne (address at InternalBytecode.js:1:1180)
    at anonymous (address at InternalBytecode.js:1:1874)
    at apply (native)
    at anonymous (address at index.android.bundle:1:288143)
    at _callTimer (address at index.android.bundle:1:287094)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:287238)
    at callReactNativeMicrotasks (address at index.android.bundle:1:289217)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:149878)
    at anonymous (address at index.android.bundle:1:148962)
    at __guard (address at index.android.bundle:1:149716)
    at flushedQueue (address at index.android.bundle:1:148873)
    at callFunctionReturnFlushedQueue (address at index.android.bundle:1:148729)

**Comment by personalizedrefrigerator** [comment]
> 3.1.1

This may be fixed in [Android v3.1.2](https://discourse.joplinapp.org/t/android-pre-release-v3-1-is-now-available-updated-10-08-2024/39551/2) (see https://github.com/laurent22/joplin/commit/f58d29a6a647bc072e602161f8e6b03a92725534)

**Comment by SwallowYourDreams** [comment]
I'll make sure to try it. Staying on 3.0.9 for now.

**Comment by bananabob** [comment]
I am getting this as well using 3.1.1 through Fastmail WebDAV

**Comment by personalizedrefrigerator** [comment]
> I am getting this as well using 3.1.1 through Fastmail WebDAV


If Joplin was installed from F-Droid, this forum post may be relevant:

https://discourse.joplinapp.org/t/joplin-android-error-not-implemented-httpagent/39554/5

In summary, F-Droid seems to be publishing a slightly-outdated pre-release version of Joplin.

**Comment by bananabob** [comment]
3.1.2 got installed overnight and is working. I am going to leave it at that, and hope that F-Droid gets in sync at some stage.
