### ISSUE TITLE
TypeError: Cannot read property 'substring' of undefined - when trying to build

### ISSUE THREAD

**Issue by shankargopal** [laurent22/joplin#1091]
### Operating system
- Linux

### Application

- Desktop

### Details

When trying to build on a 32 bit Debian Linux system (`Linux debian 4.15.0-2-686-pae #1 SMP Debian 4.15.11-1 (2018-03-20) i686 GNU/Linux`), following the build instructions, I get this:

```
$ sudo npm install -g node-gyp && npm install && yarn dist
/usr/local/bin/node-gyp -> /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js
+ node-gyp@3.8.0
added 97 packages from 67 contributors in 48.382s

> Joplin@1.0.119 postinstall /home/user/Software/joplin/ElectronClient/app
> node compile-jsx.js && node compile-package-info.js && node ../../Tools/copycss.js --copy-fonts && install-app-deps

  • please use as subcommand: electron-builder install-app-deps
  • electron-builder version=20.14.7
  • loaded configuration file=package.json ("build" field)
  • rebuilding native production dependencies platform=linux arch=ia32
Error: /usr/bin/node exited with code 1
Error output:
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.4/electron-v1.8-linux-ia32.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.0.4 and electron@1.8.7 (electron-v1.8 ABI, glibc) (falling back to source compile with node-gyp) 
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack TypeError: Cannot read property 'substring' of undefined
gyp ERR! stack     at Unpack.isValid [as filter] (/usr/share/node-gyp/lib/install.js:156:30)
gyp ERR! stack     at Unpack.[consumeHeader] (/usr/lib/nodejs/tar/lib/parse.js:134:48)
gyp ERR! stack     at Unpack.[consumeChunkSub] (/usr/lib/nodejs/tar/lib/parse.js:385:30)
gyp ERR! stack     at Unpack.[consumeChunk] (/usr/lib/nodejs/tar/lib/parse.js:362:30)
gyp ERR! stack     at Unpack.write (/usr/lib/nodejs/tar/lib/parse.js:309:25)
gyp ERR! stack     at Gunzip.ondata (_stream_readable.js:639:20)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Gunzip.emit (events.js:211:7)
gyp ERR! stack     at addChunk (_stream_readable.js:263:12)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:250:11)
gyp ERR! System Linux 4.15.0-2-686-pae
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "configure" "--fallback-to-build" "--module=/home/user/Software/joplin/ElectronClient/app/node_modules/sqlite3/lib/binding/electron-v1.8-linux-ia32/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/user/Software/joplin/ElectronClient/app/node_modules/sqlite3/lib/binding/electron-v1.8-linux-ia32" "--napi_version=1" "--node_abi_napi=napi"
gyp ERR! cwd /home/user/Software/joplin/ElectronClient/app/node_modules/sqlite3
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/bin/node-gyp configure --fallback-to-build --module=/home/user/Software/joplin/ElectronClient/app/node_modules/sqlite3/lib/binding/electron-v1.8-linux-ia32/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/user/Software/joplin/ElectronClient/app/node_modules/sqlite3/lib/binding/electron-v1.8-linux-ia32 --napi_version=1 --node_abi_napi=napi' (7)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/user/Software/joplin/ElectronClient/app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.15.0-2-686-pae
node-pre-gyp ERR! command "/usr/bin/node" "/home/user/Software/joplin/ElectronClient/app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/user/Software/joplin/ElectronClient/app/node_modules/sqlite3
node-pre-gyp ERR! node -v v8.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@4.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-01-01T18_07_57_477Z-debug.log

    at ChildProcess.childProcess.once.code (/home/user/Software/joplin/ElectronClient/app/node_modules/builder-util/src/util.ts:252:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
From previous event:
    at rebuild (/home/user/Software/joplin/ElectronClient/app/node_modules/electron-builder-lib/out/util/yarn.js:234:18)
    at /home/user/Software/joplin/ElectronClient/app/node_modules/electron-builder-lib/src/util/yarn.ts:20:11
From previous event:
    at installOrRebuild (/home/user/Software/joplin/ElectronClient/app/node_modules/electron-builder-lib/out/util/yarn.js:68:17)
    at /home/user/Software/joplin/ElectronClient/app/node_modules/electron-builder/src/cli/install-app-deps.ts:57:20
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at installAppDeps (/home/user/Software/joplin/ElectronClient/app/node_modules/electron-builder/out/cli/install-app-deps.js:174:17)
    at main (/home/user/Software/joplin/ElectronClient/app/node_modules/electron-builder/src/cli/install-app-deps.ts:66:2)
    at Object.<anonymous> (/home/user/Software/joplin/ElectronClient/app/node_modules/electron-builder/out/cli/install-app-deps.js:187:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Joplin@1.0.119 postinstall: `node compile-jsx.js && node compile-package-info.js && node ../../Tools/copycss.js --copy-fonts && install-app-deps`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Joplin@1.0.119 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-01-01T18_07_57_621Z-debug.log
```

Any idea what I'm doing wrong? Trying to manually build the desktop client as there's no 32 bit pre-built binary.

**Comment by laurent22** [comment]
Looks like an error building sqlite. Maybe they can help with this if you ask on their repo

**Comment by laurent22** [comment]
Closing as this is not an issue with Joplin, but feel free to add more comments if you find a solution.

**Comment by shankargopal** [comment]
Thank you for your reply and for all your work, Laurent. Upgrading npm resolved this issue.

**Comment by xland** [comment]
Have you solved this issue?
@shankargopal
