### ISSUE TITLE
Android: The application crashes before synchronization is complete via WebDAV

### ISSUE THREAD

**Issue by DASenkiv** [laurent22/joplin#10937]
### Operating system

Android

### Joplin version

3.1.2 (Android 14), 3.0.8 (Android 12)

### Current behaviour

1. Open app
2. The WebDAV sync is started
3. 46/50 elements synced
4. The app closed without error modal
5. Repeat

### Expected behaviour

The application works correctly, without crashes

### Logs

2024-08-28 01:22:42.232 24762-24799 AndroidRuntime
net.cozic.joplin                     
  FATAL EXCEPTION: mqt_native_modules
                                                                                                    Process: net.cozic.joplin, PID: 24762
                                                                                                    java.lang.RuntimeException: Could not invoke FileReaderModule.readAsText
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:381)
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:146)
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:233)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:146) 
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232) 
                                                                                                    	at android.os.Looper.loop(Looper.java:317) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:233) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012) 
                                                                                                    Caused by: java.lang.OutOfMemoryError: Failed to allocate a 65732016 byte allocation with 46932496 free bytes and 44MB until OOM, target footprint 268435456, growth limit 268435456
                                                                                                    	at java.lang.StringFactory.newStringFromUtf8Bytes(Native Method)
                                                                                                    	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:94)
                                                                                                    	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:79)
                                                                                                    	at com.facebook.react.modules.blob.FileReaderModule.readAsText(FileReaderModule.java:55)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) 
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:146) 
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232) 
                                                                                                    	at android.os.Looper.loop(Looper.java:317) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:233) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)

**Comment by personalizedrefrigerator** [comment]
I'm highlighting part of the log message:
> Caused by: java.lang.OutOfMemoryError: Failed to allocate a 65732016 byte allocation with 46932496 free bytes and 44MB until OOM, target footprint 268435456, growth limit 268435456

For context, 65732016 bytes is about 65 MB.

**Comment by DASenkiv** [comment]
up
