### ISSUE TITLE
Searching crashes the terminal app

### ISSUE THREAD

**Issue by shankargopal** [laurent22/joplin#1096]
### Operating system

- Linux

### Application

- Terminal

When trying to do a search in the Terminal app, the app crashes as soon as I press enter on the search command, and an error is displayed in the terminal:

<pre>
Unhandled promise rejection Promise {
  <rejected> TypeError: Cannot read property 'selectAll' of null
    at SearchEngine.search (/home/user/.joplin-bin/lib/node_modules/joplin/lib/services/SearchEngine.js:212:31)
    at Function.notesForQuery (/home/user/.joplin-bin/lib/node_modules/joplin/lib/services/SearchEngineUtils.js:7:49)
    at Application.refreshNotes (/home/user/.joplin-bin/lib/node_modules/joplin/lib/BaseApplication.js:223:37)
    at Application.generalMiddleware (/home/user/.joplin-bin/lib/node_modules/joplin/lib/BaseApplication.js:313:15)
    at Object.dispatch (/home/user/.joplin-bin/lib/node_modules/joplin/lib/BaseApplication.js:268:16)
    at Command.cmd.setDispatcher [as dispatcher_] (/home/user/.joplin-bin/lib/node_modules/joplin/app.js:133:25)
    at Command.dispatch (/home/user/.joplin-bin/lib/node_modules/joplin/base-command.js:64:15)
    at Command.action (/home/user/.joplin-bin/lib/node_modules/joplin/command-search.js:48:8)
    at Application.execCommand (/home/user/.joplin-bin/lib/node_modules/joplin/app.js:303:30)
    at AppGui.processPromptCommand (/home/user/.joplin-bin/lib/node_modules/joplin/app-gui.js:520:21) } reason: TypeError: Cannot read property 'selectAll' of null
    at SearchEngine.search (/home/user/.joplin-bin/lib/node_modules/joplin/lib/services/SearchEngine.js:212:31)
    at Function.notesForQuery (/home/user/.joplin-bin/lib/node_modules/joplin/lib/services/SearchEngineUtils.js:7:49)
    at Application.refreshNotes (/home/user/.joplin-bin/lib/node_modules/joplin/lib/BaseApplication.js:223:37)
    at Application.generalMiddleware (/home/user/.joplin-bin/lib/node_modules/joplin/lib/BaseApplication.js:313:15)
    at Object.dispatch (/home/user/.joplin-bin/lib/node_modules/joplin/lib/BaseApplication.js:268:16)
    at Command.cmd.setDispatcher [as dispatcher_] (/home/user/.joplin-bin/lib/node_modules/joplin/app.js:133:25)
    at Command.dispatch (/home/user/.joplin-bin/lib/node_modules/joplin/base-command.js:64:15)
    at Command.action (/home/user/.joplin-bin/lib/node_modules/joplin/command-search.js:48:8)
    at Application.execCommand (/home/user/.joplin-bin/lib/node_modules/joplin/app.js:303:30)
    at AppGui.processPromptCommand (/home/user/.joplin-bin/lib/node_modules/joplin/app-gui.js:520:21)
</pre>

**Comment by shankargopal** [comment]
This problem happens even if I delete `~/.config/joplin` and then start from scratch, with only one note (that I added via the terminal app).

**Comment by laurent22** [comment]
Search in CLI app is currently broken and shouldn't have been released. A fix should be available at some point.
