### ISSUE TITLE
Fatal error when clicking on something(?) in the title bar 

### ISSUE THREAD

**Issue by bbreak** [laurent22/joplin#10979]
### Operating system

macOS

### Joplin version

3.0.15

### Desktop version info

Joplin 3.0.15 (prod, darwin)

Client ID: de4c7d007b8c4785b6cb3e5519421990
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: 598677b

Backup: 1.4.1

### Current behaviour

I'm not entirely sure what I clicked on, but suddenly the whole Joplin window filled with this error output:

```
Error
Joplin encountered a fatal error and could not continue.

To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

If the error persists you may try to [restart in safe mode](https://github.com/laurent22/joplin/issues/new?assignees=&labels=bug&projects=&template=BUG_REPORT.yml#), which will temporarily disable all plugins.

Message
window.EmojiButton is not a constructor

Version info
Joplin for Desktop

Copyright © 2016-2024 Laurent Cozic
Joplin 3.0.13 (prod, darwin)

Client ID: de4c7d007b8c4785b6cb3e5519421990
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: 599cf5b

Backup: 1.4.1
Plugins
[
    {
        "id": "io.github.jackgruber.backup",
        "name": "Backup",
        "enabled": true,
        "version": "1.4.1"
    }
]
Stack trace
TypeError: window.EmojiButton is not a constructor
    at /Applications/Joplin.app/Contents/Resources/app.asar/gui/EditFolderDialog/IconSelector.js:54:19
    at commitHookEffectListMount (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23150:26)
    at commitPassiveMountOnFiber (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24926:13)
    at commitPassiveMountEffects_complete (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24891:9)
    at commitPassiveMountEffects_begin (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24878:7)
    at commitPassiveMountEffects (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24866:3)
    at flushPassiveEffectsImpl (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:27039:3)
    at flushPassiveEffects (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:26984:14)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:26769:9
    at workLoop (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/scheduler/cjs/scheduler.development.js:266:34)
Component stack

    at IconSelector (/Applications/Joplin.app/Contents/Resources/app.asar/gui/EditFolderDialog/IconSelector.js:20:84)
    at div
    at div
    at div
    at div
    at div
    at div
    at div
    at I (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/styled-components/dist/styled-components.cjs.js:1:19269)
    at div
    at I (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/styled-components/dist/styled-components.cjs.js:1:19269)
    at Dialog (/Applications/Joplin.app/Contents/Resources/app.asar/gui/Dialog.js:33:70)
    at default_1 (/Applications/Joplin.app/Contents/Resources/app.asar/gui/EditFolderDialog/Dialog.js:29:64)
    at exports.ThemeProvider (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/styled-components/dist/styled-components.cjs.js:1:25001)
    at ae (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/styled-components/dist/styled-components.cjs.js:1:13440)
    at RootComponent (/Applications/Joplin.app/Contents/Resources/app.asar/gui/Root.js:104:1)
    at ConnectFunction (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-redux/lib/components/connect.js:246:74)
    at ErrorBoundary (/Applications/Joplin.app/Contents/Resources/app.asar/gui/ErrorBoundary.js:21:9)
    at Provider (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-redux/lib/components/Provider.js:19:3)
```

### Expected behaviour

Clicking on normal window UI controls should not produce a fatal error.

p.s. Thanks for the continued work on this great tool!

**Comment by personalizedrefrigerator** [comment]
Thank you for reporting this!


I'm linking to an issue that seems related: https://github.com/laurent22/joplin/issues/10590

**Comment by laurent22** [comment]
So I have this issue now and then because I use two accounts on macOS. And if I upgrade the app on one account, then switch to the other profile and use the app (which was already open), it's going to crash in that way. Is that also your situation @bbreak by any chance?

**Comment by bbreak** [comment]
Sorry, just saw this. I’m honestly not sure what triggered the issue for me. I wish I had more detail to offer. On Oct 4, 2024, at 11:03 AM, github-actions[bot] ***@***.***> wrote:﻿
Hey there, it looks like there has been no activity on this issue recently. Has the issue been fixed, or does it still require the community's attention? If you require support or are requesting an enhancement or feature then please create a topic on the Joplin forum. This issue may be closed if no further activity occurs. You may comment on the issue and I will leave it open. Thank you for your contributions.

**Comment by bbreak** [comment]
It may be worth noting that I store my sync folder on Google Drive.
