### ISSUE TITLE
Joplin fails to start because of an error in dependency

### ISSUE THREAD

**Issue by mschaaf** [laurent22/joplin#1104]
A dependency of a dependency is broken. Changes in the latest version of xregexp break the joplin startup. See issue https://github.com/slevithan/xregexp/issues/262

Joplin fails to start with the following error:

```
{ Error: Cannot find module '@babel/runtime/core-js/object/create'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/mschaaf/.nvm/versions/node/v10.15.0/lib/node_modules/joplin/node_modules/xregexp/lib/xregexp.js:10:38)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3) code: 'MODULE_NOT_FOUND' }
```

Maybe pinning the dependencies to working ones will it in the future.

I could fix it by installing manually in the Joplin installation directory the following babel module versions:
```
npm install babel-runtime@7.0.0-beta.53
npm install babel-core@7.0.0-beta.53
```

**Comment by renestalder** [comment]
I have the same problem, but with another dependency:

```
➜  ~ joplin
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '/usr/local/Cellar/joplin/1.0.139/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v64-darwin-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/Cellar/joplin/1.0.139/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```
