### ISSUE TITLE
Error screen shown while navigating the sidebar with the arrow keys

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#11190]
### Operating system

Linux

### Joplin version

3.1.17

### Desktop version info

Joplin for Desktop

Copyright © 2016-2024 Laurent Cozic
Joplin 3.1.17 (prod, linux)

Client ID: e4129541ac704c74bd240b36e450e556
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: 3ea403d

Backup: 1.4.2
Diff view: 0.1.1
Extra Markdown viewer settings: 0.4.0
Freehand Drawing: 2.11.0

### Current behaviour

While quickly navigating the sidebar with the arrow keys, Joplin 3.1.17 experienced an uncaught error:

```
Error
Joplin encountered a fatal error and could not continue.

To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

If the error persists you may try to [restart in safe mode](https://github.com/laurent22/joplin/issues/new?assignees=&labels=bug&projects=&template=BUG_REPORT.yml#), which will temporarily disable all plugins.

Message
Runtime is not registered for command textBold

Version info
Joplin for Desktop

Copyright © 2016-2024 Laurent Cozic
Joplin 3.1.17 (prod, linux)

Client ID: e4129541ac704c74bd240b36e450e556
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: 3ea403d

Backup: 1.4.2
Diff view: 0.1.1
Extra Markdown viewer settings: 0.4.0
Freehand Drawing: 2.11.0
Plugins
[
    {
        "id": "io.github.jackgruber.backup",
        "name": "Backup",
        "enabled": true,
        "version": "1.4.2"
    },
    {
        "id": "io.github.personalizedrefrigerator.diff-view",
        "name": "Diff view",
        "enabled": true,
        "version": "0.1.1"
    },
    {
        "id": "io.github.personalizedrefrigerator.note-viewer-settings",
        "name": "Extra Markdown viewer settings",
        "enabled": false,
        "version": "0.4.0"
    }
]
Stack trace
Error: Runtime is not registered for command textBold
    at CommandService.commandByName (/tmp/.mount_JoplindCt9Zy/resources/app.asar/node_modules/@joplin/lib/services/CommandService.js:93:19)
    at ToolbarButtonUtils.commandToToolbarButton (/tmp/.mount_JoplindCt9Zy/resources/app.asar/node_modules/@joplin/lib/services/commands/ToolbarButtonUtils.js:32:38)
    at ToolbarButtonUtils.commandsToToolbarButtons (/tmp/.mount_JoplindCt9Zy/resources/app.asar/node_modules/@joplin/lib/services/commands/ToolbarButtonUtils.js:61:30)
    at Function.mapStateToProps [as mapToProps] (/tmp/.mount_JoplindCt9Zy/resources/app.asar/gui/NoteEditor/NoteBody/CodeMirror/Toolbar.js:50:48)
    at mapToPropsProxy (/tmp/.mount_JoplindCt9Zy/resources/app.asar/node_modules/react-redux/lib/connect/wrapMapToProps.js:59:92)
    at handleNewState (/tmp/.mount_JoplindCt9Zy/resources/app.asar/node_modules/react-redux/lib/connect/selectorFactory.js:52:28)
    at handleSubsequentCalls (/tmp/.mount_JoplindCt9Zy/resources/app.asar/node_modules/react-redux/lib/connect/selectorFactory.js:66:30)
    at pureFinalPropsSelector (/tmp/.mount_JoplindCt9Zy/resources/app.asar/node_modules/react-redux/lib/connect/selectorFactory.js:71:32)
    at checkForUpdates (/tmp/.mount_JoplindCt9Zy/resources/app.asar/node_modules/react-redux/lib/components/connect.js:109:23)
    at subscribeUpdates (/tmp/.mount_JoplindCt9Zy/resources/app.asar/node_modules/react-redux/lib/components/connect.js:143:3)
Component stack

    at ConnectFunction (/tmp/.mount_JoplindCt9Zy/resources/app.asar/node_modules/react-redux/lib/components/connect.js:246:74)
    at div
    at div
    at ErrorBoundary (/tmp/.mount_JoplindCt9Zy/resources/app.asar/gui/ErrorBoundary.js:21:9)
    at CodeMirror (/tmp/.mount_JoplindCt9Zy/resources/app.asar/gui/NoteEditor/NoteBody/CodeMirror/v6/CodeMirror.js:52:44)
    at div
    at div
```

To reproduce (but not reliably):
1. Create a new profile
2. Create two notebooks:
   - `_Test`
   - `Empty`
3. Create a single note in `_Test`
4. Focus `Trash`
5. Hold the <kbd>ArrowUp</kbd> key until "NOTEBOOKS" header has focus.
6. Hold the <kbd>ArrowDown</kbd> key until the "TAGS" header has focus.
7. Repeat steps 5-6 until a crash occurs.

### Expected behaviour

Joplin should not crash due to an unregistered command runtime while navigating with the keyboard.

**Comment by personalizedrefrigerator** [comment]
This seems to have been fixed by https://github.com/laurent22/joplin/commit/98fce34fe91d6bf09890250105562b8727cf0c7f#diff-6dc0163cbb9240a94b1630b018c9fbf44b749e36a30907a8a5e79926f38d99c6L60, which removed the `commandByName` call in the above stack trace.
