### ISSUE TITLE
can not import jex file

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#1127]
### Operating system

- Linux

### Application

- Desktop
- Terminal

### Description

when importing with 

```
joplin import --profile ~/.config/joplin-desktop /path/to/foobar.jex MyFolder
```
it replies "MyFolder does not exist"
so if I do 
```
joplin import --profile ~/.config/joplin-desktop /path/to/foobar.jex
```
it says "importing notes...." but I can't find foobar anywhere when I use the search bar. :/

**Comment by laurent22** [comment]
App-specific flags should go after the executable name, so it should be:

    joplin --profile ~/.config/joplin-desktop import /path/to/foobar.jex MyFolder

**Comment by foxmask** [comment]
Ok.

**Comment by foxmask** [comment]
in that order that gives
```
/home/foxmask/.joplin-bin/bin/joplin --profile /home/foxmask/.config/joplin-desktop import /home/foxmask/Dropbox/Applications/Joplin/letterbox/moz.jex Tech
Fatal error:
Error: Unknown profile version. Most likely this is an old version of Joplin, while the profile was created by a newer version. Please upgrade Joplin at https://joplin.cozic.net and try again.
    at JoplinDatabase.upgradeDatabase (/home/foxmask/.joplin-bin/lib/node_modules/joplin/lib/joplin-database.js:211:38)
    at JoplinDatabase.initialize (/home/foxmask/.joplin-bin/lib/node_modules/joplin/lib/joplin-database.js:378:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
