### ISSUE TITLE
Cannot access Joplin

### ISSUE THREAD

**Issue by LucaSolari66** [laurent22/joplin#11386]
### Operating system

macOS

### Joplin version

Joplin-3.1.24-arm64

### Desktop version info

Joplin-3.1.24-arm64

### Current behaviour

I have tried multiple times to erase and reload the applicaiton, but I still get this message when attempting at starting it

An error occurred: Fatal error:

Error: SQLITE_CORRUPT: database disk image is malformed: DELETE FROM deleted_items

### Logs

An error occurred: Fatal error:

Error: SQLITE_CORRUPT: database disk image is malformed: DELETE FROM deleted_items

Error: Error: SQLITE_CORRUPT: database disk image is malformed: DELETE FROM deleted_items
at DatabaseDriverNode.sqliteErrorToJsError (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/database-driver-node.js:23:18)
at JoplinDatabase.sqliteErrorToJsError (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/database.js:27:30)
at JoplinDatabase.tryCall (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/database.js:130:32)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async JoplinDatabase.transactionExecBatch (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/database.js:184:17)
at async clearLocalDataForRedownload (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/tools.js:38:5)
at async default_1 (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/utils/handleSyncStartupOperation.js:15:9)
at async Application.start (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/BaseApplication.js:660:9)
at async Application.start (/Applications/Joplin.app/Contents/Resources/app.asar/app.js:360:16)
at async main (file:///Applications/Joplin.app/Contents/Resources/app.asar/main-html.js:140:22)

**Comment by mrjo118** [comment]
Looks like the sqlite database for your profile has become corrupt, which is rare, but could happen for any number of reasons.

Do you have a sync target setup? If you have, then first make a backup of the Joplin profile directory (not sure where it is on Mac, you will have to look into it), then delete the original. When you open Joplin afterwards, it will create a fresh profile and you can set it up to sync your notes again.

**Comment by LucaSolari66** [comment]
thank you for taking the time to answer. I really appreciate this gift.
So if I understand well (cross checking) I need to cancel the profile directory on my computer and subsequentely setup again.



Luca Solari
Founder & Chief Future Officer
Mail  ***@***.***
Mobile +393482629561

www.orgtech.it
Contact me https://calendar.app.google/u2eyHTdcCN5tbu9X7




Il 28 nov 2024, 20:47 +0100, mrjo118 ***@***.***> ha scritto:

**Comment by LucaSolari66** [comment]
It worked. Thank you so much!!!



Luca Solari
Founder & Chief Future Officer
Mail  ***@***.***
Mobile +393482629561

www.orgtech.it
Contact me https://calendar.app.google/u2eyHTdcCN5tbu9X7




Il 28 nov 2024, 20:47 +0100, mrjo118 ***@***.***> ha scritto:
