### ISSUE TITLE
Position 389 is out of range for changeset of length 377

### ISSUE THREAD

**Issue by Tzion0** [laurent22/joplin#11391]
### Operating system

Windows

### Joplin version

Joplin 3.1.24 (prod, win32)

## Version info
```
Joplin for Desktop

Copyright © 2016-2024 Laurent Cozic
Joplin 3.1.24 (prod, win32)

Client ID: a677bb480a6646199a9685e1a79f9cd2
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: d581264

Backup: 1.4.2
LanguageTool integration: 0.1.0
Persistent Editor Layout: 2.2.0
Quick Links: 1.3.2
Tags Generator: 1.0.0
```

### Current behaviour

# Error
Joplin encountered a fatal error and could not continue.

To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

If the error persists you may try to [restart in safe mode](https://github.com/laurent22/joplin/issues/new?assignees=&labels=bug&projects=&template=BUG_REPORT.yml#), which will temporarily disable all plugins.

## Message
Position 389 is out of range for changeset of length 377

## Version info
```
Joplin for Desktop

Copyright © 2016-2024 Laurent Cozic
Joplin 3.1.24 (prod, win32)

Client ID: a677bb480a6646199a9685e1a79f9cd2
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: d581264

Backup: 1.4.2
LanguageTool integration: 0.1.0
Persistent Editor Layout: 2.2.0
Quick Links: 1.3.2
Tags Generator: 1.0.0
```

## Plugins
```
[
    {
        "id": "joplin.plugin.benji.persistentLayout",
        "name": "Persistent Editor Layout",
        "enabled": true,
        "version": "2.2.0"
    },
    {
        "id": "joplin.plugin.forcewake.tags-generator",
        "name": "Tags Generator",
        "enabled": true,
        "version": "1.0.0"
    },
    {
        "id": "com.whatever.quick-links",
        "name": "Quick Links",
        "enabled": true,
        "version": "1.3.2"
    },
    {
        "id": "io.github.jackgruber.backup",
        "name": "Backup",
        "enabled": true,
        "version": "1.4.2"
    },
    {
        "id": "com.asdibiase.joplin-languagetool",
        "name": "LanguageTool integration",
        "enabled": true,
        "version": "0.1.0"
    }
]
```
## Stack trace
```
RangeError: Position 389 is out of range for changeset of length 377
    at ChangeSet.mapPos (C:\Users\tengz\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\editor\node_modules\@codemirror\state\dist\index.cjs:819:19)
    at Chunk.map (C:\Users\tengz\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\editor\node_modules\@codemirror\state\dist\index.cjs:3148:35)
    at RangeSet.map (C:\Users\tengz\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\editor\node_modules\@codemirror\state\dist\index.cjs:3284:45)
    at Decorator.updateEffectDecorations (C:\Users\tengz\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\editor\CodeMirror\CodeMirror5Emulation\Decorator.js:116:39)
    at StateField.update [as updateF] (C:\Users\tengz\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\editor\CodeMirror\CodeMirror5Emulation\Decorator.js:86:54)
    at Object.update (C:\Users\tengz\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\editor\node_modules\@codemirror\state\dist\index.cjs:1828:34)
    at EditorState.computeSlot (C:\Users\tengz\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\editor\node_modules\@codemirror\state\dist\index.cjs:2665:88)
    at ensureAddr (C:\Users\tengz\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\editor\node_modules\@codemirror\state\dist\index.cjs:2064:25)
    at new EditorState (C:\Users\tengz\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\editor\node_modules\@codemirror\state\dist\index.cjs:2601:13)
    at EditorState.applyTransaction (C:\Users\tengz\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\editor\node_modules\@codemirror\state\dist\index.cjs:2665:9)
 ```
 
## Component stack
```
    at CodeMirror (C:\Users\tengz\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteEditor\NoteBody\CodeMirror\v6\CodeMirror.js:43:44)
    at div
    at div
    at div
    at NoteEditor (C:\Users\tengz\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteEditor\NoteEditor.js:61:68)
    at ConnectFunction (C:\Users\tengz\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-redux\lib\components\connect.js:246:74)
    at div
    at I (C:\Users\tengz\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19269)
    at div
    at div
    at ResizableLayout (C:\Users\tengz\AppData\Local\Programs\Joplin\resources\app.asar\gui\ResizableLayout\ResizableLayout.js:54:45)
    at div
    at MainScreenComponent (C:\Users\tengz\AppData\Local\Programs\Joplin\resources\app.asar\gui\MainScreen\MainScreen.js:69:9)
    at ConnectFunction (C:\Users\tengz\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-redux\lib\components\connect.js:246:74)
    at div
    at NavigatorComponent (C:\Users\tengz\AppData\Local\Programs\Joplin\resources\app.asar\gui\Navigator.js:7:1)
    at ConnectFunction (C:\Users\tengz\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-redux\lib\components\connect.js:246:74)
    at exports.ThemeProvider (C:\Users\tengz\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:25001)
    at ae (C:\Users\tengz\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:13440)
    at RootComponent (C:\Users\tengz\AppData\Local\Programs\Joplin\resources\app.asar\gui\Root.js:93:1)
    at ConnectFunction (C:\Users\tengz\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-redux\lib\components\connect.js:246:74)
    at ErrorBoundary (C:\Users\tengz\AppData\Local\Programs\Joplin\resources\app.asar\gui\ErrorBoundary.js:12:9)
    at Provider (C:\Users\tengz\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-redux\lib\components\Provider.js:19:3)
    ```

**Comment by personalizedrefrigerator** [comment]
>     at Decorator.updateEffectDecorations (C:\Users\tengz\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\editor\CodeMirror\CodeMirror5Emulation\Decorator.js:116:39)
>    at StateField.update [as updateF] (C:\Users\tengz\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\editor\CodeMirror\CodeMirror5Emulation\Decorator.js:86:54)

The error seems to be coming from the plugin compatibility layer. As such, this error is most likely related to a plugin designed for an older version of Joplin's Markdown editor. If this error has happened multiple times, I suggest either:
1. Enabling the legacy Markdown editor (Settings > General > Advanced > Enable the legacy Markdown editor), or
2. Disabling individual Markdown editor plugins (e.g. Language Tool Integration).

**Comment by Vineet1101** [comment]
Is this issue still there , I would like to work on it
