### ISSUE TITLE
Sync: SQL query error

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#11519]
### Operating system

Linux

### Joplin version

3.1.24

### Desktop version info

Joplin 3.1.24 (prod, linux)

Client ID: 5639202a4c1d47da85ed851c07779a4f
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: d581264

Backup: 1.4.2

### Current behaviour

A user is [reporting errors during sync](https://discourse.joplinapp.org/t/sync-error-on-linux-database-query-issue/42478?u=personalizedrefriger) related to an SQL query. From the forum,
<blockquote>

```
Synchronizer: Error: On query
SELECT items.`id`,items.`parent_id`,items.`title`,items.`body`,items.`created_time`,items.`updated_time`,items.`is_conflict`,items.`latitude`,items.`longitude`,items.`altitude`,items.`author`,items.`source_url`,items.`is_todo`,items.`todo_due`,items.`todo_completed`,items.`source`,items.`source_application`,items.`application_data`,items.`order`,items.`user_created_time`,items.`user_updated_time`,items.`encryption_cipher_text`,items.`encryption_applied`,items.`markup_language`,items.`is_shared`,items.`share_id`,items.`conflict_original_id`,items.`master_key_id`,items.`user_data`,items.`deleted_time`
				FROM `notes` items
				WHERE id NOT IN (
					SELECT item_id FROM sync_items WHERE sync_target = 9
				)
				AND is_conflict = 0 AND encryption_applied = 0
				ORDER BY items.updated_time DESC
				LIMIT 100
			: 
    at DatabaseDriverNode.sqliteErrorToJsError (/tmp/.mount_JoplinKY…river-node.js:23:18)
    at JoplinDatabase.sqliteErrorToJsError (/tmp/.mount_JoplinKY…b/database.js:27:30)
    at JoplinDatabase.tryCall (/tmp/.mount_JoplinKY…/database.js:130:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Note.modelSelectAll (/tmp/.mount_JoplinKY…BaseModel.js:325:28)
    at async BaseItem.itemsThatNeedSync (/tmp/.mount_JoplinKY…/BaseItem.js:611:37)
    at async Synchronizer.start (/tmp/.mount_JoplinKY…chronizer.js:521:36)
    at async Timeout.timeoutCallback [as _onTimeout] (/tmp/.mount_JoplinKY…/registry.js:125:52)
```

</blockquote>

### Expected behaviour

Joplin should sync without errors.

**Comment by personalizedrefrigerator** [comment]
The issue was caused by a corrupt SQLite database (see the forum post).
