### ISSUE TITLE
Default plugins build failed in CI

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#11543]
### Operating system

macOS

### Joplin version

CI

### Current behaviour

The default plugin build failed in CI for `io.github.jackgruber.backup`.

<details><summary>Logs</summary>

````
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: [17:21:10] Starting 'copyDefaultPluginsAssets'...
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: Copying 7zip for platform darwin and architecture x64
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: [17:21:11] Finished 'copyDefaultPluginsAssets' after 19 ms
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: [17:21:11] Starting 'buildDefaultPlugins'...
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:  Building plugin io.github.jackgruber.backup at /var/folders/9f/9p4dh6hs5yddrk7drxq8rc_80000gn/T/default-plugin-buildvEcBD2 
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:  Cloning from repository https://github.com/JackGruber/joplin-plugin-backup.git 
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: > git clone -- https://github.com/JackGruber/joplin-plugin-backup.git /Users/runner/work/joplin/joplin/packages/default-plugins/plugin-sources/io.github.jackgruber.backup
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: Cloning into '/Users/runner/work/joplin/joplin/packages/default-plugins/plugin-sources/io.github.jackgruber.backup'...
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:  Switching to commit 5ba57c18ac0f24f20832f012e015a080b138f0c4 
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: > git switch master
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: Already on 'master'
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: Your branch is up to date with 'origin/master'.
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: > git checkout 5ba57c18ac0f24f20832f012e015a080b138f0c4
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: HEAD is now at 5ba57c1 Merge branch 'develop'
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: > git rev-parse --verify HEAD^{commit}
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: 5ba57c18ac0f24f20832f012e015a080b138f0c4
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:  Copying repository files... 
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:  Initializing repository. 
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: > git init . -b main
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: Initialized empty Git repository in /private/var/folders/9f/9p4dh6hs5yddrk7drxq8rc_80000gn/T/default-plugin-buildvEcBD2/.git/
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:  Running before-patch hook. 
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:  Applying patch. 
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: > git apply /Users/runner/work/joplin/joplin/packages/default-plugins/plugin-patches/io.github.jackgruber.backup.diff
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:  Installing dependencies. 
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: > npm install
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm WARN deprecated har-validator@5.1.5: this library is no longer supported
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR! code EEXIST
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR! syscall open
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR! path /Users/runner/.npm/_cacache/tmp/d81f5434
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR! errno -17
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR! EEXIST: file already exists, open '/Users/runner/.npm/_cacache/tmp/d81f5434'
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR! File exists: /Users/runner/.npm/_cacache/tmp/d81f5434
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR! Remove the existing file and try again, or run npm
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR! with --force to overwrite files recklessly.
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: 
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR! A complete log of this run can be found in:
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR!     /Users/runner/.npm/_logs/2024-12-19T17_21_12_873Z-debug-0.log
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: Error: Command failed with exit code 239: npm install
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm WARN deprecated har-validator@5.1.5: this library is no longer supported
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR! code EEXIST
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR! syscall open
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR! path /Users/runner/.npm/_cacache/tmp/d81f5434
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR! errno -17
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR! EEXIST: file already exists, open '/Users/runner/.npm/_cacache/tmp/d81f5434'
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR! File exists: /Users/runner/.npm/_cacache/tmp/d81f5434
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR! Remove the existing file and try again, or run npm
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR! with --force to overwrite files recklessly.
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: 
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR! A complete log of this run can be found in:
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR!     /Users/runner/.npm/_logs/2024-12-19T17_21_12_873Z-debug-0.log
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:     at makeError (/Users/runner/work/joplin/joplin/packages/utils/node_modules/execa/lib/error.js:60:11)
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:     at handlePromise (/Users/runner/work/joplin/joplin/packages/utils/node_modules/execa/index.js:118:26)
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:     at async exports.default (/Users/runner/work/joplin/joplin/packages/utils/execCommand.ts:45:17)
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:     at async buildDefaultPlugins (/Users/runner/work/joplin/joplin/packages/default-plugins/buildDefaultPlugins.ts:89:4)
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:     at async fn (/Users/runner/work/joplin/joplin/packages/app-desktop/gulpfile.ts:39:4) {
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:   shortMessage: 'Command failed with exit code 239: npm install',
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:   command: 'npm install',
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:   escapedCommand: 'npm install',
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:   exitCode: 239,
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:   signal: undefined,
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:   signalDescription: undefined,
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:   stdout: '',
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:   stderr: 'npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated\n' +
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:     'npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated\n' +
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:     'npm WARN deprecated har-validator@5.1.5: this library is no longer supported\n' +
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:     'npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.\n' +
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:     'npm ERR! code EEXIST\n' +
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:     'npm ERR! syscall open\n' +
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:     'npm ERR! path /Users/runner/.npm/_cacache/tmp/d81f5434\n' +
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:     'npm ERR! errno -17\n' +
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:     "npm ERR! EEXIST: file already exists, open '/Users/runner/.npm/_cacache/tmp/d81f5434'\n" +
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:     'npm ERR! File exists: /Users/runner/.npm/_cacache/tmp/d81f5434\n' +
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:     'npm ERR! Remove the existing file and try again, or run npm\n' +
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:     'npm ERR! with --force to overwrite files recklessly.\n' +
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:     '\n' +
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:     'npm ERR! A complete log of this run can be found in:\n' +
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:     'npm ERR!     /Users/runner/.npm/_logs/2024-12-19T17_21_12_873Z-debug-0.log',
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:   failed: true,
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:   timedOut: false,
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:   isCanceled: false,
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:   killed: false
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: }
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: Input is not from a TTY -- not waiting for input.
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: Build directory /var/folders/9f/9p4dh6hs5yddrk7drxq8rc_80000gn/T/default-plugin-buildvEcBD2
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:  Removed build directory 
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: [17:21:27] 'buildDefaultPlugins' errored after 17 s
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: [17:21:27] Error: Command failed with exit code 239: npm install
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm WARN deprecated har-validator@5.1.5: this library is no longer supported
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR! code EEXIST
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR! syscall open
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR! path /Users/runner/.npm/_cacache/tmp/d81f5434
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR! errno -17
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR! EEXIST: file already exists, open '/Users/runner/.npm/_cacache/tmp/d81f5434'
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR! File exists: /Users/runner/.npm/_cacache/tmp/d81f5434
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR! Remove the existing file and try again, or run npm
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR! with --force to overwrite files recklessly.
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: 
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR! A complete log of this run can be found in:
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: npm ERR!     /Users/runner/.npm/_logs/2024-12-19T17_21_12_873Z-debug-0.log
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:     at makeError (/Users/runner/work/joplin/joplin/packages/utils/node_modules/execa/lib/error.js:60:11)
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:     at handlePromise (/Users/runner/work/joplin/joplin/packages/utils/node_modules/execa/index.js:118:26)
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:     at async exports.default (/Users/runner/work/joplin/joplin/packages/utils/execCommand.ts:45:17)
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:     at async buildDefaultPlugins (/Users/runner/work/joplin/joplin/packages/default-plugins/buildDefaultPlugins.ts:89:4)
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]:     at async fn (/Users/runner/work/joplin/joplin/packages/app-desktop/gulpfile.ts:39:4)
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: [17:21:27] 'build' errored after 18 s
  ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: Process exited (exit code 1), completed in 23s 179ms
````

</details>

**Comment by personalizedrefrigerator** [comment]
I'm closing this issue temporarily &mdash; I plan to re-open it if the failure occurs again.
