### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by beamzer** [laurent22/joplin#1154]
### Operating system
- macOS (10.14.2)
### Application
- Terminal => joplin 1.0.120 (prod)

I installed joplin through brew a while ago. Made one notebook and one note in joplin.
Today i installed the Joplin desktop application. When i started that, i expected to see
the note i allready created in the terminal application, but it was not there.
I switched the desktop application to file sync. I did the same with the terminal application,
but that went a bit iffy. After i changed the config sync.target to 2
that option vanished as i just typed :config.
So i did an exit and started her back up again, but now the application crashed after a few seconds
with the error below. 
With debugging on, the logging doesn't show any warnings or errors, last log line is
"Preparing scheduled sync"
I upgraded joplin to the last version with brew, but that doesn't make any difference.

Unhandled promise rejection Promise {
  <rejected> Error: Invalid id: 0
      at Function.classById (/usr/local/Cellar/joplin/1.0.120/libexec/lib/node_modules/joplin/lib/SyncTargetRegistry.js:5:20)
      at Object.reg.syncTarget (/usr/local/Cellar/joplin/1.0.120/libexec/lib/node_modules/joplin/lib/registry.js:42:45)
      at Timeout.timeoutCallback [as _onTimeout] (/usr/local/Cellar/joplin/1.0.120/libexec/lib/node_modules/joplin/lib/registry.js:78:18)
      at listOnTimeout (timers.js:324:15)
      at processTimers (timers.js:268:5) } reason: Error: Invalid id: 0
    at Function.classById (/usr/local/Cellar/joplin/1.0.120/libexec/lib/node_modules/joplin/lib/SyncTargetRegistry.js:5:20)
    at Object.reg.syncTarget (/usr/local/Cellar/joplin/1.0.120/libexec/lib/node_modules/joplin/lib/registry.js:42:45)
    at Timeout.timeoutCallback [as _onTimeout] (/usr/local/Cellar/joplin/1.0.120/libexec/lib/node_modules/joplin/lib/registry.js:78:18)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)

**Comment by jatcwang** [comment]
### Operating system
 * Arch Linux

### Application
    * Terminal => joplin 1.0.120 (prod)

Can confirm I'm getting the same problem - desktop and CLI notes are completely separate. This is a fresh install. I don't see any exceptions running the CLI though

**Comment by laurent22** [comment]
They are indeed separate applications, and can only use the same data via sync.

Try again setting it up in CLI:

joplin config sync.target 2
joplin config sync.2.path /path/to/sync/with

**Comment by beamzer** [comment]
thanks, that fixed it.
Would it be possible to have the desktop and the terminal application point to the same database.sqlite and share the same notes etc?

**Comment by laurent22** [comment]
>  Would it be possible to have the desktop and the terminal application point to the same database.sqlite and share the same notes etc?

That's not supported since, for example, if two apps write to the same note at the same time, some of the changes will be lost. Sync between apps is supported via sync.
