### ISSUE TITLE
Error opening Joplin desktop

### ISSUE THREAD

**Issue by jbriales** [laurent22/joplin#1190]
### Operating system

- Linux

### Application

- Desktop

# Issue
I'm trying to open the desktop app but I get the error below.
I tried removing ~/.joplin, ~/.config/joplin-desktop and ~/.config/Joplin,
then installing again, but I still get the error. Any ideas?

# Error message
```
Fatal error:

Unknown profile version. Most likely this is an old version of Joplin, while the profile was created by a newer version. Please upgrade Joplin at https://joplin.cozic.net and try again.

Error: Unknown profile version. Most likely this is an old version of Joplin, while the profile was created by a newer version. Please upgrade Joplin at https://joplin.cozic.net and try again.
    at JoplinDatabase.upgradeDatabase (/tmp/.mount_JoplinjZfuwz/app/resources/app/lib/joplin-database.js:211:38)
    at JoplinDatabase.initialize (/tmp/.mount_JoplinjZfuwz/app/resources/app/lib/joplin-database.js:378:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by laurent22** [comment]
Need more info (what did you install, from where, what version, did you update the app, etc.). But for support, please use the forum.
