### ISSUE TITLE
Help with the build process

### ISSUE THREAD

**Issue by TobiasDev** [laurent22/joplin#1203]
I'm trying to follow this build process: https://github.com/laurent22/joplin/blob/master/BUILD.md

But I keep getting this error, and I'm not sure what I'm doing wrong (I'm new to react and I haven't used NPM or Yarn before)

```
> Joplin@1.0.126 postinstall /home/tobias/Projects/joplin/ElectronClient/app
> node compile.js && node compile-package-info.js && node ../../Tools/copycss.js --copy-fonts && install-app-deps

internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/tobias/Projects/joplin/Tools/copycss.js:1:74)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Joplin@1.0.126 postinstall: `node compile.js && node compile-package-info.js && node ../../Tools/copycss.js --copy-fonts && install-app-deps`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Joplin@1.0.126 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tobias/.npm/_logs/2019-02-10T18_10_09_542Z-debug.log
```

**Comment by josegarciaclm95** [comment]
Hi @TobiasDev 
I had that same problem some days ago, and what fixed it for me was doing `npm install` in the `Tools` folder.

```
cd Tools
npm install
```

I was following the [build for windows](https://github.com/laurent22/joplin/blob/master/readme/building_win32_tips.md) readme and it didn't have anything about building Tools.

Doing that fixed that error.

**Comment by TobiasDev** [comment]
That fixed it
