### ISSUE TITLE
Sync stalling at 35748/88750 total items

### ISSUE THREAD

**Issue by xthursdayx** [laurent22/joplin#1423]
### Operating system

- macOS

### Application

- Desktop

Sorry to be back again so soon with another issue...

While trying to finish syncing my notes I began getting an error and the synchronization has stalled at 35,748/88,750 items. I opened the debugging console but didn't see any errors there, however, this is the error from my log.txt:

```
Code: 423
Error: PUT 5f5d1ea0198547e2bd7c8f45e9535c7d.md: "Joplin/5f5d1ea0198547e2bd7c8f45e9535c7d.md" is locked (Exception OCA\DAV\Connector\Sabre\Exception\FileLocked) (423): <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>OCA\DAV\Connector\Sabre\Exception\FileLocked</s:exception>
  <s:message>"Joplin/5f5d1ea0198547e2bd7c8f45e9535c7d.md" is locked</s:message>
</d:error>

    at newError (/Applications/Joplin.app/Contents/Resources/app/lib/WebDavApi.js:349:11)
    at WebDavApi.exec (/Applications/Joplin.app/Contents/Resources/app/lib/WebDavApi.js:375:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)"
2019-04-15 11:39:19: "Sync: finished: Synchronisation finished [1555342715555]"
2019-04-15 11:39:19: "Reducer action", "SYNC_REPORT_UPDATE"
2019-04-15 11:39:19: "Operations completed: "
2019-04-15 11:39:19: "createRemote: 1"
2019-04-15 11:39:19: "Total folders: 78"
2019-04-15 11:39:19: "Total notes: 15330"
2019-04-15 11:39:19: "Total resources: 65906"
2019-04-15 11:39:19: "There was some errors:"
2019-04-15 11:39:19: "Error: PUT 5f5d1ea0198547e2bd7c8f45e9535c7d.md: "Joplin/5f5d1ea0198547e2bd7c8f45e9535c7d.md" is locked (Exception OCA\DAV\Connector\Sabre\Exception\FileLocked) (423): <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>OCA\DAV\Connector\Sabre\Exception\FileLocked</s:exception>
  <s:message>"Joplin/5f5d1ea0198547e2bd7c8f45e9535c7d.md" is locked</s:message>
</d:error>
```

I've tried searching Joplin and my computer for "5f5d1ea0198547e2bd7c8f45e9535c7d" but haven't found this file.

**Comment by laurent22** [comment]
This is an issue with Nextcloud - you might need to setup something like Redis to manage file locking. See the Nextcloud forum for a lot of info about file locking issues.

**Comment by xthursdayx** [comment]
Ah, okay. I'll look into that. Thanks.
