### ISSUE TITLE
Sync not working following (re)install

### ISSUE THREAD

**Issue by martinpengellyphillips** [laurent22/joplin#143]
### Operating system

- [x] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

### Application

- [x] Desktop
- [x] Mobile
- [ ] Terminal

---

Uninstalled the entire application, including deauthorising the application and removing all folders on OneDrive along with `~/.config/joplin-desktop`. I then did a fresh install, enabled the new encryption feature and subsequently setup OneDrive sync.

Now, when I click `Synchronise` in the application nothing happens. 

Looking in `log.txt` I see 

```
...
2018-01-08 13:36:20: "Profile directory: C:\Users\martinpp/.config/joplin-desktop"
2018-01-08 13:36:20: "Trying to load 1 master keys..."
2018-01-08 13:36:20: "Loaded master keys: 1"
2018-01-08 13:36:20: "Trying to load 1 master keys..."
2018-01-08 13:36:20: "Loaded master keys: 1"
2018-01-08 13:36:20: "Scheduling sync operation..."
2018-01-08 13:36:21: "DecryptionWorker: starting decryption..."
2018-01-08 13:36:21: "DecryptionWorker: completed decryption."
2018-01-08 13:36:23: "Preparing scheduled sync"
2018-01-08 13:36:23: "Saving updated OneDrive auth."
2018-01-08 13:36:25: "Could not run background sync:"
2018-01-08 13:36:25: "SyntaxError: Unexpected token o in JSON at position 1
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at timeoutCallback (C:\Users\martinpp\AppData\Local\Programs\Joplin\resources\app.asar\lib\registry.js:83:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)"
```

The database `.config/joplin-desktop/database.sqlite` has `NULL` as the value of `sync.3.context`.
  
 Possibly related to #142

**Comment by martinpengellyphillips** [comment]
I manually deleted `sync.3.context` row from the database and now the sync is working.

**Comment by martinpengellyphillips** [comment]
However, I am now encountering a similar option when setting up the mobile app on Android.

Not sure how to manually fix that one.

**Comment by maxcb97** [comment]
I'm having a similar problem. Same solution on Windows, however the logs for the Android version are also complainging about the encrytption, even though I have already put in the password. See attached (cropped) logs
[syncReport-1515420326707.txt](https://github.com/laurent22/joplin/files/1611784/syncReport-1515420326707.txt)

**Comment by laurent22** [comment]
This should now be fixed in Android. Please could you update and give it another try to see if you're still seeing this error?

**Comment by martinpengellyphillips** [comment]
Updated and works perfectly now - thanks!
