### ISSUE TITLE
internal/modules/cjs/loader.js:583 traceback right after installation

### ISSUE THREAD

**Issue by AloisMahdal** [laurent22/joplin#1456]
### Operating system

Fedora 29

### Application

- Desktop or CLI?

I just enabled `taw/joplin` COPR and installed `joplin` package, ran `joplin` and I get this traceback:

    internal/modules/cjs/loader.js:583
        throw err;
        ^

    Error: Cannot find module 'app-module-path'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
        at Function.Module._load (internal/modules/cjs/loader.js:507:25)
        at Module.require (internal/modules/cjs/loader.js:637:17)
        at require (internal/modules/cjs/helpers.js:22:18)
        at Object.<anonymous> (/usr/share/joplin/cli/main.js:7:1)
        at Module._compile (internal/modules/cjs/loader.js:689:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
        at Module.load (internal/modules/cjs/loader.js:599:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
        at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by AloisMahdal** [comment]
I just found out about Joplin from this article: https://fedoramagazine.org/4-cool-new-projects-to-try-in-copr-for-april-2019/

(It's linked on COPR page so lot of Fedora hackers will see it.)

**Comment by laurent22** [comment]
Only the installation method mentioned on the home page (via npm) is officially supported here. For other methods, you'll need to contact the person who manages the package.

You might also want to try the Arch Linux method (not sure if it works on Fedora) as it's been around for a while and should be more reliable.

**Comment by AloisMahdal** [comment]
Sorry I don't have time right now to investigate; I'm only willing to install via rpm, preferably COPR.  I understand if you're not maintaning it, tough luck for me.

Should the article be changed, though? This way lot of people who read it and want to try out Joplin might get frustrated right installation, which could create (undeserved!) bad feelings about Joplin.

**Comment by laurent22** [comment]
Unfortunately I didn't write this article nor even knew about this method of installing Joplin, so there's not much I can do about it. If possible, you might want to comment on that article that the method they suggest is not reliable.

**Comment by AloisMahdal** [comment]
I think I can contact the author directly. I'll also add the comment.  Take care & thanks!
