### ISSUE TITLE
v0.10.41 Crashing on MacOS 

### ISSUE THREAD

**Issue by wdennis** [laurent22/joplin#148]
Experiencing crashes when Joplin goes to sync on two MacBooks I have... Syncs seem to be happening; I can get what new stuff I put in (before the sync crashes the app) on another device.

If you can tell me how to get more details, I'd be happy to; I got the log msgs posted below out of the System.log

MacBook 1:
```
Wills-MacBook-Air:~ will$ uname -a
Darwin Wills-MacBook-Air 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
```

MacBook 2:
```
AirDennis:~ will$ uname -a
Darwin AirDennis 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64
```

### Operating system

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [X] Desktop
- [ ] Mobile
- [ ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

*If there is an error, please copy and paste the full error message*
```
Jan  8 22:27:27 Wills-MacBook-Air com.apple.xpc.launchd[1] (net.cozic.joplin-desktop.2236[43990]): Service exited with abnormal code: 1
Jan  8 22:28:03 Wills-MacBook-Air com.apple.xpc.launchd[1] (net.cozic.joplin-desktop.2236[43999]): Service exited with abnormal code: 1
Jan  8 22:30:55 Wills-MacBook-Air com.apple.xpc.launchd[1] (net.cozic.joplin-desktop.2236[44025]): Service exited with abnormal code: 1
```
---

**Comment by laurent22** [comment]
Hello, please could you enable the debugging features [as described here](https://github.com/laurent22/joplin/blob/master/README_debugging.md) and let me know if you find any warning or error?

**Comment by wdennis** [comment]
On the "AirDennis" MacBook:

```
AirDennis:~ will$ cat ~/.config/joplin-desktop/log.txt
2018-01-07 10:57:46: "Profile directory: /Users/will/.config/joplin-desktop"
2018-01-07 10:57:46: "First start: detected locale as en_GB"
2018-01-07 10:57:46: "Trying to load 0 master keys..."
2018-01-07 10:57:46: "Loaded master keys: 0"
2018-01-07 10:57:47: "Trying to load 0 master keys..."
2018-01-07 10:57:47: "Loaded master keys: 0"
2018-01-07 10:57:47: "Scheduling sync operation..."
2018-01-07 10:57:48: "DecryptionWorker: starting decryption..."
2018-01-07 10:57:48: "DecryptionWorker: completed decryption."
2018-01-07 10:57:50: "Preparing scheduled sync"
2018-01-07 10:57:50: "Synchroniser is missing credentials - manual sync required to authenticate."
2018-01-07 10:57:50: "Updading all notifications..."
2018-01-07 10:57:50: "Garbage collecting alarms..."
2018-01-07 10:57:51: "DecryptionWorker: starting decryption..."
2018-01-07 10:57:51: "DecryptionWorker: completed decryption."
2018-01-07 10:58:25: "Saving updated OneDrive auth."
2018-01-07 10:58:25: "Scheduling sync operation..."
2018-01-07 10:58:25: "Preparing scheduled sync"
2018-01-07 10:58:25: "Could not run background sync:"
2018-01-07 10:58:25: "SyntaxError: Unexpected token o in JSON at position 1
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at timeoutCallback (/Applications/Joplin.app/Contents/Resources/app/lib/registry.js:83:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)"
2018-01-07 10:58:32: "Scheduling sync operation..."
2018-01-07 10:58:32: "Preparing scheduled sync"
2018-01-07 10:58:32: "Could not run background sync:"
2018-01-07 10:58:32: "SyntaxError: Unexpected token o in JSON at position 1
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at timeoutCallback (/Applications/Joplin.app/Contents/Resources/app/lib/registry.js:83:29)
    at <anonymous>"
2018-01-07 10:58:37: "Scheduling sync operation..."
2018-01-07 10:58:37: "Preparing scheduled sync"
2018-01-07 10:58:37: "Could not run background sync:"
2018-01-07 10:58:37: "SyntaxError: Unexpected token o in JSON at position 1
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at timeoutCallback (/Applications/Joplin.app/Contents/Resources/app/lib/registry.js:83:29)
    at <anonymous>"
```
Also, this Joplin instance (v0.10.41) never did sync any content down from OneDrive. Tried removing & reinstalling app, same behavior (launches, app runs, but after 10-20 sec's, app crashes (disappears from desktop.)

**Comment by wdennis** [comment]
On the "Wills-MacBook-Air" MacBook:
```
2018-01-09 08:41:20: "Profile directory: /Users/will/.config/joplin-desktop"
2018-01-09 08:41:20: "Trying to load 0 master keys..."
2018-01-09 08:41:20: "Loaded master keys: 0"
2018-01-09 08:41:20: "Reducer action", "SETTING_UPDATE_ALL"
2018-01-09 08:41:20: "Refreshing notes:", "null", "null"
2018-01-09 08:41:20: "Reducer action", "NOTE_UPDATE_ALL, "{\"options\":{\"order\":[{\"by\":\"user_updated_time\",\"dir\":\"DESC\"}],\"uncompletedTodosOnTop\":true},\"parentId\":null}""
2018-01-09 08:41:20: "Reducer action", "NOTE_SELECT, "
2018-01-09 08:41:20: "Trying to load 0 master keys..."
2018-01-09 08:41:20: "Loaded master keys: 0"
2018-01-09 08:41:20: "Reducer action", "MASTERKEY_REMOVE_NOT_LOADED"
2018-01-09 08:41:20: "Setting up recurrent sync with interval 300"
2018-01-09 08:41:20: "Reducer action", "FOLDER_UPDATE_ALL"
2018-01-09 08:41:20: "Reducer action", "TAG_UPDATE_ALL"
2018-01-09 08:41:20: "Reducer action", "MASTERKEY_UPDATE_ALL"
2018-01-09 08:41:20: "Reducer action", "FOLDER_SELECT, c2c06d3cd4714697ad902e5648da153c"
2018-01-09 08:41:20: "Scheduling sync operation..."
2018-01-09 08:41:21: "Reducer action", "APP_STATE_SET"
2018-01-09 08:41:21: "Reducer action", "WINDOW_CONTENT_SIZE_SET"
2018-01-09 08:41:21: "Reducer action", "NOTE_VISIBLE_PANES_SET"
2018-01-09 08:41:21: "Reducer action", "SETTING_UPDATE_ONE"
2018-01-09 08:41:21: "Reducer action", "APP_STATE_SET"
2018-01-09 08:41:22: "DecryptionWorker: starting decryption..."
2018-01-09 08:41:22: "Refreshing notes:", "2", "c2c06d3cd4714697ad902e5648da153c"
2018-01-09 08:41:22: "Reducer action", "NOTE_UPDATE_ALL, "{\"options\":{\"order\":[{\"by\":\"user_updated_time\",\"dir\":\"DESC\"}],\"uncompletedTodosOnTop\":true},\"parentId\":\"c2c06d3cd4714697ad902e5648da153c\"}""
2018-01-09 08:41:22: "Reducer action", "NOTE_SELECT, 5ea7768f70a44dd6ad60970434221d71"
2018-01-09 08:41:22: "DecryptionWorker: completed decryption."
2018-01-09 08:41:23: "Preparing scheduled sync"
2018-01-09 08:41:23: "Saving updated OneDrive auth."
2018-01-09 08:41:24: "Token expired: refreshing..."
2018-01-09 08:41:24: "Saving updated OneDrive auth."
2018-01-09 08:41:24: "Reducer action", "SETTING_UPDATE_ONE"
2018-01-09 08:41:24: "Starting scheduled sync"
2018-01-09 08:41:24: "Reducer action", "SYNC_STARTED"
2018-01-09 08:41:24: "Sync: starting: Starting synchronisation to target 3... [1515505284952]"
2018-01-09 08:41:24: "Reducer action", "SYNC_REPORT_UPDATE"
2018-01-09 08:41:24: "mkdir /drive/root:/Apps/Joplin/.sync"
2018-01-09 08:41:25: "mkdir /drive/root:/Apps/Joplin/.resource"
2018-01-09 08:41:25: "delta /drive/root:/Apps/Joplin"
2018-01-09 08:41:26: "get /drive/root:/Apps/Joplin/b415817d68224f8ca0adbbf3a29a3e4b.md"
2018-01-09 08:41:27: "Sync: finished: Synchronisation finished [1515505284952]"
2018-01-09 08:41:27: "Reducer action", "SYNC_REPORT_UPDATE"
2018-01-09 08:41:27: "Operations completed: "
2018-01-09 08:41:27: "Total folders: 1"
2018-01-09 08:41:27: "Total notes: 5"
2018-01-09 08:41:27: "Total resources: 4"
2018-01-09 08:41:27: "Reducer action", "SYNC_COMPLETED"
2018-01-09 08:41:27: "Reducer action", "SETTING_UPDATE_ONE"
2018-01-09 08:41:27: "Setting up recurrent sync with interval 300"
2018-01-09 08:41:27: "Updading all notifications..."
2018-01-09 08:41:27: "Garbage collecting alarms..."
2018-01-09 08:41:28: "DecryptionWorker: starting decryption..."
2018-01-09 08:41:28: "DecryptionWorker: completed decryption."
2018-01-09 08:41:43: "Scheduling sync operation..."
2018-01-09 08:41:43: "Preparing scheduled sync"
2018-01-09 08:41:43: "Starting scheduled sync"
2018-01-09 08:41:43: "Reducer action", "SYNC_STARTED"
2018-01-09 08:41:43: "Sync: starting: Starting synchronisation to target 3... [1515505303534]"
2018-01-09 08:41:43: "Reducer action", "SYNC_REPORT_UPDATE"
2018-01-09 08:41:43: "mkdir /drive/root:/Apps/Joplin/.sync"
2018-01-09 08:41:44: "mkdir /drive/root:/Apps/Joplin/.resource"
2018-01-09 08:41:45: "delta /drive/root:/Apps/Joplin"
2018-01-09 08:41:47: "Sync: finished: Synchronisation finished [1515505303534]"
2018-01-09 08:41:47: "Reducer action", "SYNC_REPORT_UPDATE"
2018-01-09 08:41:47: "Operations completed: "
2018-01-09 08:41:47: "Total folders: 1"
2018-01-09 08:41:47: "Total notes: 5"
2018-01-09 08:41:47: "Total resources: 4"
2018-01-09 08:41:47: "Reducer action", "SYNC_COMPLETED"
2018-01-09 08:41:47: "Reducer action", "SETTING_UPDATE_ONE"
2018-01-09 08:41:47: "Setting up recurrent sync with interval 300"
```
Again, this instance (v0.10.41) crashes, seemingly after a sync.

**Comment by laurent22** [comment]
Yes this is a known bug in this version (although I didn't know it would actually crash). Please try with the latest one 0.10.43 and let me know if it's fixed.

**Comment by wdennis** [comment]
Can one upgrade thru the app, or just d/l the latest installer and run it?

**Comment by laurent22** [comment]
It's setup to download the update on startup and install it when the application is closed. But for bugs like this it's better to download the update directly rather than wait for it to do it automatically.

**Comment by thinway** [comment]
I had the same problem on my laptop (OS X 10.12.6). Upgrading to the latest version seems like the problem no longer appears.

**Comment by wdennis** [comment]
Yup, upgrading to 0.10.43 resolves the problem - thanks!
