### ISSUE TITLE
Will not start on macOS

### ISSUE THREAD

**Issue by jastuccio** [laurent22/joplin#150]
### Operating system
- [ ] macOS

### Application
Desktop

```
/usr/local/Cellar/joplin/0.10.87/libexec/lib/node_modules/joplin/lib/models/BaseItem.js:615
			);
			^
SyntaxError: Unexpected token )
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/Cellar/joplin/0.10.87/libexec/lib/node_modules/joplin/lib/models/Note.js:4:18)

```
Here are lines 610 - 615.  Looks good to me 🤔

```
const sql = sprintf(`
				SELECT id
				FROM %s
				WHERE encryption_applied = 0`,
				this.db().escapeField(ItemClass.tableName()),
			);
```
---

**Comment by laurent22** [comment]
I guess the extra `,` before `);` shouldn't be there, but it's weird it works in most versions. Maybe node 9 is more strict for this and it breaks. Any chance you could remove this coma and see if it works?

**Comment by jastuccio** [comment]
My node version was 7.9 I did not realize I had gotten so far behind.  Updating to node v9.3 resolved this issue.
