### ISSUE TITLE
Issue with installation of terminal application

### ISSUE THREAD

**Issue by leveled** [laurent22/joplin#1521]
### Operating system

- Linux (Debian)

### Application

- Terminal

I'm having issues installing the Joplin terminal application. If it it makes a difference I am running a Debian container on ChromeOS, although I'm not sure if that is what is causing the issue.

```
adi@penguin:~$ NPM_CONFIG_PREFIX=~/.joplin-bin npm install -g joplin
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
/home/adi/.joplin-bin/bin/joplin -> /home/adi/.joplin-bin/lib/node_modules/joplin/main.js

> sharp@0.22.1 install /home/adi/.joplin-bin/lib/node_modules/joplin/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.4/libvips-8.7.4-linux-x64.tar.gz

> sqlite3@4.0.8 install /home/adi/.joplin-bin/lib/node_modules/joplin/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
[sqlite3] Success: "/home/adi/.joplin-bin/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v72-linux-x64/node_sqlite3.node" is installed via remote
+ joplin@1.0.127
added 377 packages from 706 contributors in 78.232s
adi@penguin:~$ sudo ln -s ~/.joplin-bin/bin/joplin /usr/bin/joplin
adi@penguin:~$ joplin
internal/modules/cjs/loader.js:613
    throw err;
    ^

Error: Cannot find module '../locales/index.js'
Require stack:
- /home/adi/.joplin-bin/lib/node_modules/joplin/lib/locale.js
- /home/adi/.joplin-bin/lib/node_modules/joplin/lib/logger.js
- /home/adi/.joplin-bin/lib/node_modules/joplin/lib/database.js
- /home/adi/.joplin-bin/lib/node_modules/joplin/lib/BaseModel.js
- /home/adi/.joplin-bin/lib/node_modules/joplin/lib/models/Note.js
- /home/adi/.joplin-bin/lib/node_modules/joplin/lib/reducer.js
- /home/adi/.joplin-bin/lib/node_modules/joplin/lib/BaseApplication.js
- /home/adi/.joplin-bin/lib/node_modules/joplin/app.js
- /home/adi/.joplin-bin/lib/node_modules/joplin/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at supportedLocales (/home/adi/.joplin-bin/lib/node_modules/joplin/lib/locale.js:194:46)
    at closestSupportedLocale (/home/adi/.joplin-bin/lib/node_modules/joplin/lib/locale.js:215:18)
    at localeStrings (/home/adi/.joplin-bin/lib/node_modules/joplin/lib/locale.js:278:17)
    at _ (/home/adi/.joplin-bin/lib/node_modules/joplin/lib/locale.js:297:16)
    at Function.label (/home/adi/.joplin-bin/lib/node_modules/joplin/lib/SyncTargetFilesystem.js:19:10)
    at Function.addClass (/home/adi/.joplin-bin/lib/node_modules/joplin/lib/SyncTargetRegistry.js:13:27)
```

**Comment by laurent22** [comment]
Please try with the latest version 1.0.128, it should work with this one.

**Comment by chrmoritz** [comment]
It still doesn't work in 1.0.129 (1.0.128 is fine) because https://github.com/laurent22/joplin/commit/4638f11c5ea8f99a7a2f8ab35de178791b92b8e9 moved all the js files to a `app` directory, but the [`bin` entry in `package.json`](https://github.com/laurent22/joplin/blob/master/CliClient/package.json#L25) still points to `./main.js`. So either this entry point should be changed to `./app/main.js` or all the js files should be moved to the top level folder again as it was before.

**Comment by laurent22** [comment]
Right, the new build script was broken. Please give a try to v1.0.135

**Comment by chrmoritz** [comment]
Yeah thanks, 1.0.135 is working fine for me again.
