### ISSUE TITLE
macOS version can not autoupdate to 0.10.43 due to checksum mismatch

### ISSUE THREAD

**Issue by r618** [laurent22/joplin#157]
### Operating system

- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

*If there is an error, please copy and paste the full error message*

/Applications/Joplin.app/Contents/MacOS/Joplin 
Unhandled promise rejection Promise {
  _bitField: 18087936,
  _fulfillmentHandler0: 
   Error: Cannot download "https://github.com/laurent22/joplin/releases/download/v0.10.43/Joplin-0.10.43-mac.zip": Error: sha512 checksum mismatch, expected Jp5LY1BXleAeoYvCykH0ezF73RRzBjRSS9kFjYG+KmIgI6bwTeQyzuzd3YfFf0lLqvMsHan+1u9ANo/oe+nwNQ==, got QByvoAQjpYgS2/TvSIE4Ss8wcD3N1AjGngnOYA8sxfKq6/L0H+THNrx/q6BVjNPLgHHyWWWWkw6iBHYui+gBVw==
       at DigestTransform.<anonymous> (/Applications/Joplin.app/Contents/Resources/app/node_modules/electron-updater/src/MacUpdater.ts:74:22)
       at emitOne (events.js:101:20)
       at DigestTransform.emit (events.js:191:7)
       at done (_stream_transform.js:178:19)
       at _stream_transform.js:119:9
       at DigestTransform._flush (/Applications/Joplin.app/Contents/Resources/app/node_modules/electron-updater/node_modules/builder-util-runtime/src/httpExecutor.ts:231:9)
       at DigestTransform.<anonymous> (_stream_transform.js:118:12)
       at Object.onceWrapper (events.js:293:19)
       at emitNone (events.js:86:13)
       at DigestTransform.emit (events.js:188:7)
       at prefinish (_stream_writable.js:500:12)
       at finishMaybe (_stream_writable.js:508:7)
       at endWritable (_stream_writable.js:520:3)
       at DigestTransform.Writable.end (_stream_writable.js:485:5)
       at IncomingMessage.onend (_stream_readable.js:513:10)
       at Object.onceWrapper (events.js:293:19)
   From previous event:
       at /Applications/Joplin.app/Contents/Resources/app/node_modules/electron-updater/src/MacUpdater.ts:44:12
   From previous event:
       at MacUpdater.doDownloadUpdate (/Applications/Joplin.app/Contents/Resources/app/node_modules/electron-updater/out/MacUpdater.js:127:11)
       at /Applications/Joplin.app/Contents/Resources/app/node_modules/electron-updater/src/AppUpdater.ts:304:25
       at Generator.next (<anonymous>)
   From previous event:
       at MacUpdater.downloadUpdate (/Applications/Joplin.app/Contents/Resources/app/node_modules/electron-updater/out/AppUpdater.js:355:11)
       at /Applications/Joplin.app/Contents/Resources/app/node_modules/electron-updater/src/AppUpdater.ts:280:49
   From previous event:
       at MacUpdater.doCheckForUpdates (/Applications/Joplin.app/Contents/Resources/app/node_modules/electron-updater/out/AppUpdater.js:326:11)
       at /Applications/Joplin.app/Contents/Resources/app/node_modules/electron-updater/src/AppUpdater.ts:228:25
       at Generator.next (<anonymous>)
       at runCallback (timers.js:672:20)
       at tryOnImmediate (timers.js:645:5)
       at processImmediate [as _immediateCallback] (timers.js:617:5)
   From previous event:
       at MacUpdater._checkForUpdates (/Applications/Joplin.app/Contents/Resources/app/node_modules/electron-updater/out/AppUpdater.js:280:11)
       at MacUpdater.checkForUpdates (/Applications/Joplin.app/Contents/Resources/app/node_modules/electron-updater/src/AppUpdater.ts:177:35)
       at MacUpdater.checkForUpdatesAndNotify (/Applications/Joplin.app/Contents/Resources/app/node_modules/electron-updater/src/AppUpdater.ts:197:17)
       at Bridge.checkForUpdatesAndNotify (/Applications/Joplin.app/Contents/Resources/app/bridge.js:122:28)
       at callFunction (/Applications/Joplin.app/Contents/Resources/electron.asar/browser/rpc-server.js:249:18)
       at EventEmitter.<anonymous> (/Applications/Joplin.app/Contents/Resources/electron.asar/browser/rpc-server.js:357:5)
       at emitMany (events.js:127:13)
       at EventEmitter.emit (events.js:204:7)
       at WebContents.<anonymous> (/Applications/Joplin.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:13)
       at emitTwo (events.js:106:13)
       at WebContents.emit (events.js:194:7),
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined,
  _trace: 
   { Error
       at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/Applications/Joplin.app/Contents/Resources/app/node_modules/bluebird/js/release/debuggability.js:400:19)
       at new PromiseSpawn (/Applications/Joplin.app/Contents/Resources/app/node_modules/bluebird/js/release/generators.js:43:17)
       at /Applications/Joplin.app/Contents/Resources/app/node_modules/bluebird/js/release/generators.js:197:21
       at MacUpdater.downloadUpdate (/Applications/Joplin.app/Contents/Resources/app/node_modules/electron-updater/out/AppUpdater.js:355:11)
       at /Applications/Joplin.app/Contents/Resources/app/node_modules/electron-updater/src/AppUpdater.ts:280:49
       at Generator.next (<anonymous>)
       at Generator.tryCatcher (/Applications/Joplin.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
       at PromiseSpawn._promiseFulfilled (/Applications/Joplin.app/Contents/Resources/app/node_modules/bluebird/js/release/generators.js:97:49)
       at Async._drainQueue (/Applications/Joplin.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:138:12)
       at Async._drainQueues (/Applications/Joplin.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:143:10)
       at Immediate.Async.drainQueues (/Applications/Joplin.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:17:14)
       at runCallback (timers.js:672:20)
       at tryOnImmediate (timers.js:645:5)
       at processImmediate [as _immediateCallback] (timers.js:617:5)
     _parent: 
      { Error
          at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/Applications/Joplin.app/Contents/Resources/app/node_modules/bluebird/js/release/debuggability.js:400:19)
          at new PromiseSpawn (/Applications/Joplin.app/Contents/Resources/app/node_modules/bluebird/js/release/generators.js:43:17)
          at /Applications/Joplin.app/Contents/Resources/app/node_modules/bluebird/js/release/generators.js:197:21
          at MacUpdater.doCheckForUpdates (/Applications/Joplin.app/Contents/Resources/app/node_modules/electron-updater/out/AppUpdater.js:326:11)
          at /Applications/Joplin.app/Contents/Resources/app/node_modules/electron-updater/src/AppUpdater.ts:228:25
          at Generator.next (<anonymous>)
          at Generator.tryCatcher (/Applications/Joplin.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
          at PromiseSpawn._promiseFulfilled (/Applications/Joplin.app/Contents/Resources/app/node_modules/bluebird/js/release/generators.js:97:49)
          at Async._drainQueue (/Applications/Joplin.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:138:12)
          at Async._drainQueues (/Applications/Joplin.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:143:10)
          at Immediate.Async.drainQueues (/Applications/Joplin.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:17:14)
          at runCallback (timers.js:672:20)
          at tryOnImmediate (timers.js:645:5)
          at processImmediate [as _immediateCallback] (timers.js:617:5)
        _parent: [Object],
        _promisesCreated: 0,
        _length: 2,
        _promiseCreated: null },
     _promisesCreated: 0,
     _length: 3,
     _promiseCreated: null } } reason: Error: Cannot download "https://github.com/laurent22/joplin/releases/download/v0.10.43/Joplin-0.10.43-mac.zip": Error: sha512 checksum mismatch, expected Jp5LY1BXleAeoYvCykH0ezF73RRzBjRSS9kFjYG+KmIgI6bwTeQyzuzd3YfFf0lLqvMsHan+1u9ANo/oe+nwNQ==, got QByvoAQjpYgS2/TvSIE4Ss8wcD3N1AjGngnOYA8sxfKq6/L0H+THNrx/q6BVjNPLgHHyWWWWkw6iBHYui+gBVw==
    at DigestTransform.<anonymous> (/Applications/Joplin.app/Contents/Resources/app/node_modules/electron-updater/src/MacUpdater.ts:74:22)
    at emitOne (events.js:101:20)
    at DigestTransform.emit (events.js:191:7)
    at done (_stream_transform.js:178:19)
    at _stream_transform.js:119:9
    at DigestTransform._flush (/Applications/Joplin.app/Contents/Resources/app/node_modules/electron-updater/node_modules/builder-util-runtime/src/httpExecutor.ts:231:9)
    at DigestTransform.<anonymous> (_stream_transform.js:118:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at DigestTransform.emit (events.js:188:7)
    at prefinish (_stream_writable.js:500:12)
    at finishMaybe (_stream_writable.js:508:7)
    at endWritable (_stream_writable.js:520:3)
    at DigestTransform.Writable.end (_stream_writable.js:485:5)
    at IncomingMessage.onend (_stream_readable.js:513:10)
    at Object.onceWrapper (events.js:293:19)
From previous event:
    at /Applications/Joplin.app/Contents/Resources/app/node_modules/electron-updater/src/MacUpdater.ts:44:12
From previous event:
    at MacUpdater.doDownloadUpdate (/Applications/Joplin.app/Contents/Resources/app/node_modules/electron-updater/out/MacUpdater.js:127:11)
    at /Applications/Joplin.app/Contents/Resources/app/node_modules/electron-updater/src/AppUpdater.ts:304:25
    at Generator.next (<anonymous>)
From previous event:
    at MacUpdater.downloadUpdate (/Applications/Joplin.app/Contents/Resources/app/node_modules/electron-updater/out/AppUpdater.js:355:11)
    at /Applications/Joplin.app/Contents/Resources/app/node_modules/electron-updater/src/AppUpdater.ts:280:49
From previous event:
    at MacUpdater.doCheckForUpdates (/Applications/Joplin.app/Contents/Resources/app/node_modules/electron-updater/out/AppUpdater.js:326:11)
    at /Applications/Joplin.app/Contents/Resources/app/node_modules/electron-updater/src/AppUpdater.ts:228:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at MacUpdater._checkForUpdates (/Applications/Joplin.app/Contents/Resources/app/node_modules/electron-updater/out/AppUpdater.js:280:11)
    at MacUpdater.checkForUpdates (/Applications/Joplin.app/Contents/Resources/app/node_modules/electron-updater/src/AppUpdater.ts:177:35)
    at MacUpdater.checkForUpdatesAndNotify (/Applications/Joplin.app/Contents/Resources/app/node_modules/electron-updater/src/AppUpdater.ts:197:17)
    at Bridge.checkForUpdatesAndNotify (/Applications/Joplin.app/Contents/Resources/app/bridge.js:122:28)
    at callFunction (/Applications/Joplin.app/Contents/Resources/electron.asar/browser/rpc-server.js:249:18)
    at EventEmitter.<anonymous> (/Applications/Joplin.app/Contents/Resources/electron.asar/browser/rpc-server.js:357:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (/Applications/Joplin.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)

---

**Comment by laurent22** [comment]
Thanks for report. Do you see this error directly in the application or is it only in the log?

**Comment by r618** [comment]
The application simply disappears -
log is from command line run where the control is returned when process exits

**Comment by laurent22** [comment]
Was it v0.10.41 that you were using? In the meantime if you manually update to 0.10.43 is it working? I will try to fix this anyway so that it doesn't crash the application again.

**Comment by r618** [comment]
Yes, from 0.10.41
Manually downloaded 0.10.43 seems to be OK so far
