### ISSUE TITLE
Linux CLI - Export individual note or notebook fails, drops out of session

### ISSUE THREAD

**Issue by createchange** [laurent22/joplin#171]
### Operating system

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] Android
- [ ] iOS

### Application

- [ ] Desktop
- [ ] Mobile
- [X] Terminal

*If there is an error, please copy and paste the full error message*

When I try to export a single note or notebook, as soon as I type the first hyphen (-) in ":export --note <note>" I immediately get dropped out of the joplin session and presented with the following error message:

```
Unhandled` promise rejection Promise {
  <rejected> TypeError: Cannot read property 'indexOf' of undefined
    at toCommandLine (/home/jhw/.joplin-bin/lib/node_modules/joplin/autocompletion.js:126:11)
    at l.map.a (/home/jhw/.joplin-bin/lib/node_modules/joplin/autocompletion.js:57:22)
    at Array.map (<anonymous>)
    at handleAutocompletionPromise (/home/jhw/.joplin-bin/lib/node_modules/joplin/autocompletion.js:57:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7) } reason: TypeError: Cannot read property 'indexOf' of undefined
    at toCommandLine (/home/jhw/.joplin-bin/lib/node_modules/joplin/autocompletion.js:126:11)
    at l.map.a (/home/jhw/.joplin-bin/lib/node_modules/joplin/autocompletion.js:57:22)
    at Array.map (<anonymous>)
    at handleAutocompletionPromise (/home/jhw/.joplin-bin/lib/node_modules/joplin/autocompletion.js:57:15)
    at <anonymous>
    at process._tickCallback `(internal/process/next_tick.js:160:7)
```

Just like last time, your work is greatly appreciated. You've improved my workflow and reduce my murder of trees.

**Comment by laurent22** [comment]
@gabcoh, any idea? It seems to be some auto completion issue?

**Comment by gabcoh** [comment]
#174

**Comment by gabcoh** [comment]
Sorry about that. I hope this fixes it.

**Comment by createchange** [comment]
Thanks @gabcoh - that did solve it. I notice that it is called autocomplete.js - when editing notes it autocompletes the note/book name, but for export this does not happen. Is that in the pipeline?

Also, is there any possibility of exporting with a new file name, rather the string randomstring.md file it currently outputs?

Thanks again for your work!
