### ISSUE TITLE
NetxCloud/WebDAV sync failure

### ISSUE THREAD

**Issue by jpmv27** [laurent22/joplin#1712]
### Operating system

- Windows 7 32-bit
- Windows 10 64-bit

### Application

- Desktop 1.0.160

I just upgraded NextCloud to 16.0.2, so this may be related.
After creating a new note in Joplin, sync to NextCloud fails

2019-07-05 18:06:43: "Sync: finished: Synchronisation finished [1562364379754]"
2019-07-05 18:06:43: "Operations completed: "
2019-07-05 18:06:43: "createRemote: 1"
2019-07-05 18:06:43: "Total folders: 64"
2019-07-05 18:06:43: "Total notes: 362"
2019-07-05 18:06:43: "Total resources: 341"
2019-07-05 18:06:43: "There was some errors:"
2019-07-05 18:06:43: "Error: PUT 0a67ccc002094e0d8f3a4d7711388303.md: An exception occurred while executing 'INSERT INTO "oc_file_locks" ("key", "lock", "ttl") VALUES(?, ?, ?) ON CONFLICT DO NOTHING' with params ["files\/805aedb7e4369936182fa0d0220408e8", 1, 1562368003]:

SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "ON"
LINE 1: ..._locks" ("key", "lock", "ttl") VALUES($1, $2, $3) ON CONFLIC...
                                                             ^ (Exception Doctrine\DBAL\Exception\SyntaxErrorException) (500): <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Doctrine\DBAL\Exception\SyntaxErrorException</s:exception>
  <s:message>An exception occurred while executing 'INSERT INTO "oc_file_locks" ("key", "lock", "ttl") VALUES(?, ?, ?) ON CONFLICT DO NOTHING' with params ["files\/805aedb7e4369936182fa0d0220408e8", 1, 1562368003]:

SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "ON"
LINE 1: ..._locks" ("key", "lock", "ttl") VALUES($1, $2, $3) ON CONFLIC...
                                                             ^</s:message>
</d:error>

Code: 500
Error: PUT 0a67ccc002094e0d8f3a4d7711388303.md: An exception occurred while executing 'INSERT INTO "oc_file_locks" ("key", "lock", "ttl") VALUES(?, ?, ?) ON CONFLICT DO NOTHING' with params ["files\/805aedb7e4369936182fa0d0220408e8", 1, 1562368003]:

SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "ON"
LINE 1: ..._locks" ("key", "lock", "ttl") VALUES($1, $2, $3) ON CONFLIC...
                                                             ^ (Exception Doctrine\DBAL\Exception\SyntaxErrorException) (500): <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Doctrine\DBAL\Exception\SyntaxErrorException</s:exception>
  <s:message>An exception occurred while executing 'INSERT INTO "oc_file_locks" ("key", "lock", "ttl") VALUES(?, ?, ?) ON CONFLICT DO NOTHING' with params ["files\/805aedb7e4369936182fa0d0220408e8", 1, 1562368003]:

SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "ON"
LINE 1: ..._locks" ("key", "lock", "ttl") VALUES($1, $2, $3) ON CONFLIC...
                                                             ^</s:message>
</d:error>

    at newError (C:\Users\martin\AppData\Local\Programs\Joplin\resources\app.asar\lib\WebDavApi.js:349:11)
    at WebDavApi.exec (C:\Users\martin\AppData\Local\Programs\Joplin\resources\app.asar\lib\WebDavApi.js:375:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)"

**Comment by jpmv27** [comment]
In case anyone else sees this, it's a Postgres compatibility issue with NextCloud:
https://github.com/nextcloud/server/issues/15613

Closing.
