### ISSUE TITLE
Build fails when installed from AUR repository.

### ISSUE THREAD

**Issue by Lattitude75** [laurent22/joplin#1845]
I tried to build it form the package of arch repositories and the installation from the script file usig wget. Both, failed to give me the joplin-desktop application. The following is the error from the command using yay. I only included the last part of the output which shows the error. I tried `node-pre-gyp install --fallback-tp-build`, it works. But, this build fails. 
```
$ yay -S joplin
...
../src/database.cc:470:62:   required from here
../src/async.h:29:52: warning: cast between incompatible function types from ‘void (*)(uv_async_t*, int)’ {aka ‘void (*)(uv_async_s*, int)’} to ‘uv_async_cb’ {aka ‘void (*)(uv_async_s*)’} [-Wcast-function-type]
make: *** [node_sqlite3.target.mk:125: Release/obj.target/node_sqlite3/src/database.o] Error 1
make: Leaving directory '/home/saipavanchitta/.cache/yay/joplin/src/joplin-1.0.161/ElectronClient/app/node_modules/sqlite3/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.2.11-arch1-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/saipavanchitta/.cache/yay/joplin/src/joplin-1.0.161/ElectronClient/app/node_modules/sqlite3/lib/binding/node-v72-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/saipavanchitta/.cache/yay/joplin/src/joplin-1.0.161/ElectronClient/app/node_modules/sqlite3/lib/binding/node-v72-linux-x64" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /home/saipavanchitta/.cache/yay/joplin/src/joplin-1.0.161/ElectronClient/app/node_modules/sqlite3
gyp ERR! node -v v12.9.1
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/saipavanchitta/.cache/yay/joplin/src/joplin-1.0.161/ElectronClient/app/node_modules/sqlite3/lib/binding/node-v72-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/saipavanchitta/.cache/yay/joplin/src/joplin-1.0.161/ElectronClient/app/node_modules/sqlite3/lib/binding/node-v72-linux-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/saipavanchitta/.cache/yay/joplin/src/joplin-1.0.161/ElectronClient/app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Linux 5.2.11-arch1-1-ARCH
node-pre-gyp ERR! command "/usr/bin/node" "/home/saipavanchitta/.cache/yay/joplin/src/joplin-1.0.161/ElectronClient/app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/saipavanchitta/.cache/yay/joplin/src/joplin-1.0.161/ElectronClient/app/node_modules/sqlite3
node-pre-gyp ERR! node -v v12.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/saipavanchitta/.cache/yay/joplin/src/joplin-1.0.161/ElectronClient/app/node_modules/sqlite3/lib/binding/node-v72-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/saipavanchitta/.cache/yay/joplin/src/joplin-1.0.161/ElectronClient/app/node_modules/sqlite3/lib/binding/node-v72-linux-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.2.0 (node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.2.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@1.0.1 (node_modules/7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.6 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.6: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.0.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/saipavanchitta/.npm/_logs/2019-09-02T08_37_39_196Z-debug.log
==> ERROR: A failure occurred in build().
    Aborting...
Error making: joplin
```

## Environment

Joplin version: 1.0.161-1
Platform: Arch Linux

Please help. 

Thanks

**Comment by alfredopalhares** [comment]
Hello, 

I am the package maintainer of the [AUR Package](https://github.com/alfredopalhares/joplin-pkgbuild/ ) if you have problems please file a bug report there, as this might not be an upstream issue at to begin with. 

Regards,

**Comment by tessus** [comment]
As @alfredopalhares mentioned, please open an issue in the AUR package rep.
