### ISSUE TITLE
OSx desktop app opens with blank white screen

### ISSUE THREAD

**Issue by jobspierings** [laurent22/joplin#187]
When opening the desktop Joplin App there's a white screen and user can only quit the app via menu:

<img width="896" alt="screen" src="https://user-images.githubusercontent.com/5601623/35504818-5e897584-04e4-11e8-9301-5e6b36e8cd50.png">

note: 

* Following this I installed the terminal app, that does work.
* I made a `flags.txt` but dev. tools do not open.
* log file below.

### Operating system

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [X] Desktop
- [ ] Mobile
- [ ] Terminal

 
`log-database.txt`:

```
2018-01-29 10:36:55: "Database was open successfully"
2018-01-29 10:36:55: "Checking for database schema update..."
2018-01-29 10:36:55: "Current database version", "0"
2018-01-29 10:36:55: "Converting database to version 1"
2018-01-29 10:36:55: "Converting database to version 2"
2018-01-29 10:36:55: "Converting database to version 3"
2018-01-29 10:36:55: "Converting database to version 4"
2018-01-29 10:36:55: "Converting database to version 5"
2018-01-29 10:36:55: "Converting database to version 6"
2018-01-29 10:36:55: "Converting database to version 7"
2018-01-29 10:36:55: "Converting database to version 8"
2018-01-29 10:36:55: "Converting database to version 9"
2018-01-29 10:36:55: "Initializing tables..."
2018-01-29 10:36:55: "Saving settings..."
2018-01-29 10:36:55: "Settings have been saved."
2018-01-29 10:53:31: "Database was open successfully"
2018-01-29 10:53:31: "Checking for database schema update..."
2018-01-29 10:53:31: "Current database version", "9"
2018-01-29 10:53:32: "Saving settings..."
2018-01-29 10:53:32: "BEGIN TRANSACTION"
2018-01-29 10:53:32: "DELETE FROM settings"
2018-01-29 10:53:32: "INSERT INTO `settings` (`key`, `value`) VALUES (?, ?)"
2018-01-29 10:53:32: "["sync.3.context",""]"
2018-01-29 10:53:32: "INSERT INTO `settings` (`key`, `value`) VALUES (?, ?)"
2018-01-29 10:53:32: "["locale","nl_BE"]"
2018-01-29 10:53:32: "INSERT INTO `settings` (`key`, `value`) VALUES (?, ?)"
2018-01-29 10:53:32: "["firstStart","0"]"
2018-01-29 10:53:32: "INSERT INTO `settings` (`key`, `value`) VALUES (?, ?)"
2018-01-29 10:53:32: "["activeFolderId","79c7ba864a1e412fa5cb7fb53ec907f5"]"
2018-01-29 10:53:32: "COMMIT"
2018-01-29 10:53:32: "Settings have been saved."
2018-01-29 10:53:32: "
				SELECT *
				FROM `notes`
				WHERE encryption_applied = 1
				LIMIT 100
				"
2018-01-29 10:53:32: "
				SELECT *
				FROM `folders`
				WHERE encryption_applied = 1
				LIMIT 100
				"
2018-01-29 10:53:32: "
				SELECT *
				FROM `resources`
				WHERE (encryption_blob_encrypted = 1 OR encryption_applied = 1)
				LIMIT 100
				"
2018-01-29 10:53:32: "
				SELECT *
				FROM `tags`
				WHERE encryption_applied = 1
				LIMIT 100
				"
2018-01-29 10:53:32: "
				SELECT *
				FROM `note_tags`
				WHERE encryption_applied = 1
				LIMIT 100
				"

```

**Comment by laurent22** [comment]
Hi, it seems the app is not starting at all. Please could you try to enable [debug mode](https://github.com/laurent22/joplin/blob/master/README_desktop.md) on the desktop app and check the content of log.txt?

**Comment by seeseekey** [comment]
The same here. I use macOS 10.13.2. I think you mean this [https://github.com/laurent22/joplin/blob/master/README_debugging.md](link) for the debug mode (instead of the desktop readme)?

I try to start the debug mode, but nothing happens. No new entries since i installed the .51 version in the log.txt and no menu entries (only Joplin -> Quit menu).

**Comment by jobspierings** [comment]
Confirm: I tried to invoke debug mode as instructed (adding file flags.txt etc) but no new entries appear in log.txt.

**Comment by laurent22** [comment]
Unfortunately I don't have a Mac to test at the moment, but in the meantime you could try to install one of the previous versions: https://github.com/laurent22/joplin/releases

By the way, is there any error or warning in the [Console](https://www.macobserver.com/tmo/article/mac_os_x_using_console_to_troubleshoot_problems) when this crash happens?

**Comment by yyandrew** [comment]
Same issue here.

> Fatal error:
Cannot find module 'fbjs/lib/focusNode'
Error: Cannot find module 'fbjs/lib/focusNode'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Applications/Joplin.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:26:17
    at Object.<anonymous> (/Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:15399:5)
    at Object.<anonymous> (/Applications/Joplin.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:15402:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)

This is the error message.Hope it is helpful.

Thank you.

**Comment by jobspierings** [comment]
this is the output:

> standaard    09:03:01.761603 +0100    Joplin Helper    GVA info: preferred scaler idx 1
fout    09:03:01.790570 +0100    Joplin            AEGetDescData of non-desc type 'reco' not a good idea
standaard    09:03:01.830495 +0100    Joplin Helper    GVA info: preferred scaler idx 1
standaard    09:03:11.464476 +0100    Joplin    LSExceptions shared instance invalidated for timeout.
fout    09:04:18.962539 +0100    Joplin            AEGetDescData of non-desc type 'reco' not a good idea
standaard    09:04:18.990191 +0100    Joplin Helper    GVA info: preferred scaler idx 1
standaard    09:04:19.037236 +0100    Joplin Helper    GVA info: preferred scaler idx 1

**Comment by ingpf** [comment]
I also meet this issue

**Comment by Dadanaut** [comment]
I’m having the same problem. Sadly. But keep up the good work. I’m happy about the existence of Joplin. Thanks a lot!

**Comment by laurent22** [comment]
It turns out the build had failed but got uploaded to GitHub anyway so indeed it wasn't working. I've now uploaded a new version (0.10.54). Please give it a try and let me know if it's any better.

**Comment by zelvik** [comment]
Now it's working. Thank you for fix :)

**Comment by mapledyne** [comment]
0.10.54 fixed it for me, too. Thanks!

**Comment by johnsaigle** [comment]
The fix also worked for me!
