### ISSUE TITLE
Fatal error trying to run in Termux

### ISSUE THREAD

**Issue by rcrx** [laurent22/joplin#1905]
Here's the terminal output:

```
$ $HOME/.joplin-bin/bin/joplin
Fatal error:
Error: Cannot determine platform
    at Object.shim.platformName (/data/data/com.termux/files/home/.joplin-bin/lib/node_modules/joplin/lib/shim.js:41:8)
    at Function.metadata (/data/data/com.termux/files/home/.joplin-bin/lib/node_modules/joplin/lib/models/Setting.js:24:25)
    at Function.keyExists (/data/data/com.termux/files/home/.joplin-bin/lib/node_modules/joplin/lib/models/Setting.js:472:22)
    at /data/data/com.termux/files/home/.joplin-bin/lib/node_modules/joplin/lib/models/Setting.js:518:15
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Application.start (/data/data/com.termux/files/home/.joplin-bin/lib/node_modules/joplin/lib/BaseApplication.js:599:3)
    at async Application.start (/data/data/com.termux/files/home/.joplin-bin/lib/node_modules/joplin/app.js:374:10)
$
```
Any suggestion of how to resolve this would be appreciated.

**Comment by laurent22** [comment]
Most likely Termux set the env to some unknown string. Could you try to create a script called "platform.js" with the following content?

    console.info(process.platform);

Then run `node platform.js'. What does it print?

**Comment by rcrx** [comment]
`android`

**Comment by laurent22** [comment]
Could you give a try to cli-v1.0.149 to see if it works?

**Comment by rcrx** [comment]
> Could you give a try to cli-v1.0.149 to see if it works?

Happy to report that it works.

Note: installed with 
```
NPM_CONFIG_PREFIX=~/.joplin-bin npm install -g --platform=linux joplin
```
