### ISSUE TITLE
Crash on joplin CLI: Unhandled promise rejection Promise ... encryption_applied

### ISSUE THREAD

**Issue by himmelbuerger** [laurent22/joplin#1938]
## Environment

Joplin version: joplin 1.0.149 (prod)
Platform: linux terminal
OS specifcs:Linux penguin 4.19.60-06185-g54aa50936831 #1 SMP PREEMPT Wed Aug 14 01:17:34 PDT 2019 x86_64 GNU/Linux (Chromebook)

## Steps To Reproduce

1. open joplin in terminal
2. :mknote test
3 write something
4. Save it and return to joplin
5. Joplin crashes and the data is lost
6. See error message:
edit: Note has been saved.                                                                                                                             
Unhandled promise rejection Promise {
  <rejected> TypeError: Cannot read property 'encryption_applied' of null
      at ResourceService.indexNoteResources (/home/user/.joplin-bin/lib/node_modules/joplin/lib/services/ResourceService.js:57:15)
      at processTicksAndRejections (internal/process/task_queues.js:85:5)
      at async ResourceService.maintenance (/home/user/.joplin-bin/lib/node_modules/joplin/lib/services/ResourceService.js:135:3)
} reason: TypeError: Cannot read property 'encryption_applied' of null
    at ResourceService.indexNoteResources (/home/user/.joplin-bin/lib/node_modules/joplin/lib/services/ResourceService.js:57:15)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async ResourceService.maintenance (/home/user/.joplin-bin/lib/node_modules/joplin/lib/services/ResourceService.js:135:3)

Describe what you expected to happen:

Joplin saves the note or at least it stays somewhere. Joplin does not crash.

## Logfile
[log.txt](https://github.com/laurent22/joplin/files/3679695/log.txt)

**Comment by laurent22** [comment]
This will be fixed in the next release but for now you can run `joplin e2ee decrypt` to make sure all your notes are decrypted, which will prevent this indexing crash.
