### ISSUE TITLE
Missing katex.css.js

### ISSUE THREAD

**Issue by CameronDevine** [laurent22/joplin#195]
### Operating system

- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

I pulled the latest master branch because math support was added, however the Electron Client will not run anymore. It appears there is a new file which was not included in the latest commit, `ElectronClient/app/lib/csstojs/katex.css.js`. I also checked in `ReactNativeClient/lib` and there is not a `csstojs` directory there. The full error message given is below.

````
Fatal error:
Cannot find module 'lib/csstojs/katex.css.js'
Error: Cannot find module 'lib/csstojs/katex.css.js'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/cameron/Documents/Projects/joplin/ElectronClient/app/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/cameron/Documents/Projects/joplin/ElectronClient/app/lib/MdToHtml_Katex.js:3:18)
    at Object.<anonymous> (/home/cameron/Documents/Projects/joplin/ElectronClient/app/lib/MdToHtml_Katex.js:49:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
````

**Comment by laurent22** [comment]
Right, that's a new build step that I didn't add to BUILD.md. You basically need to go the Tools directory, and run `npm install`. Then from `ElectronClient/app` run `npm install` again.

In general the latest build instructions are in the `script` part of https://github.com/laurent22/joplin/blob/master/.travis.yml
