### ISSUE TITLE
0.10.59 doesn't launch on HighSierra

### ISSUE THREAD

**Issue by KlugFR** [laurent22/joplin#196]
### Operating system
- [X] macOS High Sierra

### Application
- [X] Desktop

I've just downloaded 0.10.59 and set it up on High Sierra.

When I launch it, Joplin window pops up, then an error window:
```
Fatal error:
Could not call remote function 'createTray'. Check that the function signature is correct. Underlying error: Error processing argument at index 0, conversion failure from /Applications/Joplin.app/Contents/Resources/app/build/icons/16x16.png
Error: Could not call remote function 'createTray'. Check that the function signature is correct. Underlying error: Error processing argument at index 0, conversion failure from /Applications/Joplin.app/Contents/Resources/app/build/icons/16x16.png
    at callFunction (/Applications/Joplin.app/Contents/Resources/electron.asar/browser/rpc-server.js:257:11)
    at EventEmitter.<anonymous> (/Applications/Joplin.app/Contents/Resources/electron.asar/browser/rpc-server.js:357:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (/Applications/Joplin.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
Error: Could not call remote function 'createTray'. Check that the function signature is correct. Underlying error: Error processing argument at index 0, conversion failure from /Applications/Joplin.app/Contents/Resources/app/build/icons/16x16.png
Error: Could not call remote function 'createTray'. Check that the function signature is correct. Underlying error: Error processing argument at index 0, conversion failure from /Applications/Joplin.app/Contents/Resources/app/build/icons/16x16.png
    at callFunction (/Applications/Joplin.app/Contents/Resources/electron.asar/browser/rpc-server.js:257:11)
    at EventEmitter.<anonymous> (/Applications/Joplin.app/Contents/Resources/electron.asar/browser/rpc-server.js:357:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (/Applications/Joplin.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
    at metaToValue (/Applications/Joplin.app/Contents/Resources/electron.asar/renderer/api/remote.js:234:13)
    at Object.remoteMemberFunction (/Applications/Joplin.app/Contents/Resources/electron.asar/renderer/api/remote.js:118:18)
    at Application.updateTray (/Applications/Joplin.app/Contents/Resources/app/app.js:374:8)
    at Application.start (/Applications/Joplin.app/Contents/Resources/app/app.js:434:8)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

If I close the error window, Joplin window stays empty.

**Comment by laurent22** [comment]
There was some issue with the tray icon, please give a try to this update: https://github.com/laurent22/joplin/releases/tag/v0.10.60

**Comment by KlugFR** [comment]
That fixed it.
