### ISSUE TITLE
MacOS desktop client can't connect to WebDAV

### ISSUE THREAD

**Issue by raman325** [laurent22/joplin#2040]
When attempting to synchronize to my WebDAV server using the desktop MacOS client, I get the following error: `Error: PROPFIND .lock: Cannot parse XML response (200)`. As you can see in the logs below, Joplin seems to be going somewhere unexpected because it is seeing responses from the NAS that my WebDAV server is being hosted on rather than the WebDAV server itself. Three things of note:

1. My iOS client is configured with the exact same WebDAV settings and can synchronize successfully - I verified this by modifying a note on my phone, running a sync to verify that Joplin indicates a successful upload and sync, and then verifying on my WebDAV server that the file was actually updated.
2. When I go to my Preferences and run "Check synchronization configuration" status I get a success
3. This used to work but I think the behavior changed sometime in one of the last two to three releases (I can't pin down exactly when it occurred because at some point it was intermittent and I assumed it was an issue on my end)

## Environment

Joplin version: 1.0.170
Platform: Synology Docker bytemark/webdav:latest
OS specifics: MacOS Catalina (10.15)

## Steps To Reproduce

1. Set up WebDAV synchronization across multiple clients (in my case I have two Macs, one running Catalina and one running Mojave, as well as an iPhone)
2. Verify that synchronization configuration shows at successful
3. Attempt a synchronization and observe the behavior

Describe what you expected to happen: Synchronization is successful

## Logfile

```log
2019-10-29 10:33:19: "Profile directory: /Users/myuser/.config/joplin-desktop"
2019-10-29 10:33:19: "Trying to load 2 master keys..."
2019-10-29 10:33:19: "Loaded master keys: 2"
2019-10-29 10:33:19: "ResourceFetcher: Auto-add resources: Mode: always"
2019-10-29 10:33:19: "ResourceFetcher: Auto-added resources: 0"
2019-10-29 10:33:19: "Trying to load 2 master keys..."
2019-10-29 10:33:19: "Loaded master keys: 2"
2019-10-29 10:33:19: "Scheduling sync operation..."
2019-10-29 10:33:19: "Trying to load 2 master keys..."
2019-10-29 10:33:19: "Loaded master keys: 2"
2019-10-29 10:33:19: "Scheduling sync operation..."
2019-10-29 10:33:19: "Trying to load 2 master keys..."
2019-10-29 10:33:19: "Loaded master keys: 2"
2019-10-29 10:33:19: "Scheduling sync operation..."
2019-10-29 10:33:19: "Scheduling sync operation..."
2019-10-29 10:33:19: "RevisionService::runInBackground: Starting background service with revision collection interval 600000"
2019-10-29 10:33:21: "DecryptionWorker: starting decryption..."
2019-10-29 10:33:21: "DecryptionWorker: completed decryption."
2019-10-29 10:33:23: "RevisionService::maintenance: Starting..."
2019-10-29 10:33:23: "RevisionService::maintenance: Service is enabled"
2019-10-29 10:33:24: "RevisionService::collectRevisions: Created revisions for 0 notes"
2019-10-29 10:33:24: "RevisionService::maintenance: Done in 108ms"
2019-10-29 10:33:24: "Scheduling sync operation..."
2019-10-29 10:33:24: "Preparing scheduled sync"
2019-10-29 10:33:24: "Starting scheduled sync"
2019-10-29 10:33:29: "SearchEngine: Updating FTS table..."
2019-10-29 10:33:29: "SearchEngine: Updated FTS table in 2ms. Inserted: 0. Deleted: 0"
2019-10-29 10:33:47: "Error: PROPFIND .lock: Cannot parse XML response (200): <!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=11" />
<meta name="msapplication-TileImage" content="resources/images/icon_tile.png?v=4398" />
<meta name="application-name" content="diskstation&nbsp;-&nbsp;Synology&nbsp;DiskStation" />
<meta name="msapplication-TileColor" content="#246BB3"/>
<meta name="description" content="DiskStation provides a full-featured network attached storage (NAS) solution to help you manage, backup and share data among Windows, Mac and Linux easily." />
<meta name="keywords" content="Multitasking,Web Application,Personal Cloud" />

<link rel="apple-touch-icon" href="webman/resources/images/icon_dsm_96.png?v=4398" />
<link rel="mask-icon" href="webman/safari_pin_icon.svg" color="#0086E5" />
<link rel="shortcut icon" href="webman/favicon.ico?v=4399" />
<link rel="shortcut icon" href="webman/resources/images/icon_dsm_96.png?v=4398" sizes="96x96"/>
<link rel="shortcut icon" href="webman/
Code: 200
Error: PROPFIND .lock: Cannot parse XML response (200): <!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=11" />
<meta name="msapplication-TileImage" content="resources/images/icon_tile.png?v=4398" />
<meta name="application-name" content="diskstation&nbsp;-&nbsp;Synology&nbsp;DiskStation" />
<meta name="msapplication-TileColor" content="#246BB3"/>
<meta name="description" content="DiskStation provides a full-featured network attached storage (NAS) solution to help you manage, backup and share data among Windows, Mac and Linux easily." />
<meta name="keywords" content="Multitasking,Web Application,Personal Cloud" />

<link rel="apple-touch-icon" href="webman/resources/images/icon_dsm_96.png?v=4398" />
<link rel="mask-icon" href="webman/safari_pin_icon.svg" color="#0086E5" />
<link rel="shortcut icon" href="webman/favicon.ico?v=4399" />
<link rel="shortcut icon" href="webman/resources/images/icon_dsm_96.png?v=4398" sizes="96x96"/>
<link rel="shortcut icon" href="webman/
    at newError (/Applications/Joplin.app/Contents/Resources/app/lib/WebDavApi.js:384:11)
    at loadResponseJson (/Applications/Joplin.app/Contents/Resources/app/lib/WebDavApi.js:393:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)"
2019-10-29 10:33:47: "Req 10:33:24: MKCOL https://dav.mydomain.com/.sync/ {"headers":{"Authorization":"********","If-None-Match":"JoplinIgnore-43342"},"timeout":120000,"maxRetry":0}"
2019-10-29 10:33:47: "Res 10:33:24: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method MKCOL is not allowed for the URL /.sync/.</p>
</body></html>
"
2019-10-29 10:33:47: "Req 10:33:24: MKCOL https://dav.mydomain.com/.lock/ {"headers":{"Authorization":"********","If-None-Match":"JoplinIgnore-34760"},"timeout":120000,"maxRetry":0}"
2019-10-29 10:33:47: "Res 10:33:24: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method MKCOL is not allowed for the URL /.lock/.</p>
</body></html>
"
2019-10-29 10:33:47: "Req 10:33:24: MKCOL https://dav.mydomain.com/.resource/ {"headers":{"Authorization":"********","If-None-Match":"JoplinIgnore-50431"},"timeout":120000,"maxRetry":0}"
2019-10-29 10:33:47: "Res 10:33:24: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method MKCOL is not allowed for the URL /.resource/.</p>
</body></html>
"
2019-10-29 10:33:47: "Req 10:33:25: PROPFIND https://dav.mydomain.com/.lock {"headers":{"Depth":1,"Authorization":"********","If-None-Match":"JoplinIgnore-4296","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","timeout":120000,"maxRetry":0}"
2019-10-29 10:33:47: "Res 10:33:25: <!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=11" />
<meta name="msapplication-TileImage" content="resources/images/icon_tile.png?v=4398" />
<meta name="application-name" content="diskstation&nbsp;-&nbsp;Synology&nbsp;DiskStation" />
<meta name="msapplication-TileColor" content="#246BB3"/>
<meta name="description" content="DiskStation provides a full-featured network attached storage (NAS) solution to help you manage, backup and share data among Windows, Mac and Linux easily." />
<meta name="keywords" content="Multitasking,Web Application,Personal Cloud" />

<link rel="apple-touch-icon" href="webman/resources/images/icon_dsm_96.png?v=4398" />
<link rel="mask-icon" href="webman/safari_pin_icon.svg" color="#0086E5" />
<link rel="shortcut icon" href="webman/favicon.ico?v=4399" />
<link rel="shortcut icon" href="webman/resources/images/icon_dsm_96.png?v=4398" sizes="96x96"/>
<link rel="shortcut icon" href="webman/resources/images/icon_dsm_64.png?v=4398" sizes="64x64"/>
<link rel="shortcut icon" href="webman/resources/images/icon_dsm_48.png?v=4398" sizes="48x48"/>
<link rel="shortcut icon" href="webman/resources/images/icon_dsm_32.png?v=4398" sizes="32x32"/>
<link rel="shortcut icon" href="webman/resources/images/icon_dsm_16.png?v=4398" sizes="16x16"/>
<title>diskstation&nbsp;-&nbsp;Synology&nbsp;DiskStation</title>
<link rel="stylesheet" type="text/css" href="scripts/ext-3/resources/css/ext-all.css?v=1557442135" />
<link rel="stylesheet" type="text/css" href="scripts/ext-3/resources/css/xtheme-gray.css?v=1557442135" />
<link rel="stylesheet" type="text/css" href="scripts/ext-3/ux/ux-all.css?v=1557442135" />
<link rel="stylesheet" type="text/css" href="synoSDSjslib/sds.css?v=1557442142" />
<link rel="stylesheet" type="text/css" href="webman/resources/css/desktop.css?v=1562143394" />
<style type="text/css">
@import url("webman/modules/DataDrivenDocuments/style.css?v=1557442311");
@import url("webman/modules/ResourceMonitor/style.css?v=1557442311");
@import url("webman/modules/FileTaskMonitor/style.css?v=1555584024");
@import url("webman/modules/VideoPlayer2/style.css?v=1557442309");
@import url("webman/modules/HotkeyManager/style.css?v=1557442311");
@import url("webman/modules/Widgets/style.css?v=1557442311");
@import url("webman/modules/PersonalSettings/style.css?v=1557442311");
@import url("webman/modules/AdminCenter/style.css?v=1557442342");
@import url("webman/modules/EzInternet/style.css?v=1557442311");
@import url("webman/modules/WelcomeApp/style.css?v=1557442311");
@import url("webman/modules/WelcomeTip/style.css?v=1557442312");
@import url("webman/modules/ExternalDevices/style.css?v=1557442311");
@import url("webman/modules/MyDSCenter/style.css?v=1557442311");
@import url("webman/modules/HelpBrowser/style.css?v=1557442311");
@import url("webman/modules/PkgManApp/style.css?v=1557442311");
@import url("webman/modules/iSCSI/style.css?v=1557442145");
@import url("webman/modules/TaskSchedulerUtils/style.css?v=1557442311");
@import url("webman/modules/StorageManager/style.css?v=1557442311");
@import url("webman/modules/SecurityScan/style.css?v=1557442332");
@import url("webman/modules/TaskSchedulerWidget/style.css?v=1557442311");
@import url("webman/modules/C3/style.css?v=1557442311");
@import url("webman/modules/BandwidthControl/style.css?v=1557442145");
@import url("webman/modules/PollingTask/style.css?v=1557442312");
@import url("webman/modules/PhotoViewer/style.css?v=1557442311");
@import url("webman/modules/DSMNotify/style.css?v=1557442311");
@import url("webman/modules/Utils/style.css?v=1557442311");
@import url("webman/modules/FileBrowser/style.css?v=1555584060");
@import url("webman/modules/DiskMessageHandler/style.css?v=1557442311");
@import url("webman/modules/SupportForm/style.css?v=1557442311");
@import url("webman/modules/SystemInfoApp/style.css?v=1557442311");
</style>
<style type="text/css">
@import url("webman/modules/Share/style.css?v=1557442311");
@import url("webman/modules/ThumbConvertProgress/style.css?v="
2019-10-29 10:33:47: "Req 10:33:29: PROPFIND https://dav.mydomain.com/.lock {"headers":{"Depth":1,"Authorization":"********","If-None-Match":"JoplinIgnore-18","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","timeout":120000,"maxRetry":0}"
2019-10-29 10:33:47: "Res 10:33:29: <!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=11" />
<meta name="msapplication-TileImage" content="resources/images/icon_tile.png?v=4398" />
<meta name="application-name" content="diskstation&nbsp;-&nbsp;Synology&nbsp;DiskStation" />
<meta name="msapplication-TileColor" content="#246BB3"/>
<meta name="description" content="DiskStation provides a full-featured network attached storage (NAS) solution to help you manage, backup and share data among Windows, Mac and Linux easily." />
<meta name="keywords" content="Multitasking,Web Application,Personal Cloud" />

<link rel="apple-touch-icon" href="webman/resources/images/icon_dsm_96.png?v=4398" />
<link rel="mask-icon" href="webman/safari_pin_icon.svg" color="#0086E5" />
<link rel="shortcut icon" href="webman/favicon.ico?v=4399" />
<link rel="shortcut icon" href="webman/resources/images/icon_dsm_96.png?v=4398" sizes="96x96"/>
<link rel="shortcut icon" href="webman/resources/images/icon_dsm_64.png?v=4398" sizes="64x64"/>
<link rel="shortcut icon" href="webman/resources/images/icon_dsm_48.png?v=4398" sizes="48x48"/>
<link rel="shortcut icon" href="webman/resources/images/icon_dsm_32.png?v=4398" sizes="32x32"/>
<link rel="shortcut icon" href="webman/resources/images/icon_dsm_16.png?v=4398" sizes="16x16"/>
<title>diskstation&nbsp;-&nbsp;Synology&nbsp;DiskStation</title>
<link rel="stylesheet" type="text/css" href="scripts/ext-3/resources/css/ext-all.css?v=1557442135" />
<link rel="stylesheet" type="text/css" href="scripts/ext-3/resources/css/xtheme-gray.css?v=1557442135" />
<link rel="stylesheet" type="text/css" href="scripts/ext-3/ux/ux-all.css?v=1557442135" />
<link rel="stylesheet" type="text/css" href="synoSDSjslib/sds.css?v=1557442142" />
<link rel="stylesheet" type="text/css" href="webman/resources/css/desktop.css?v=1562143394" />
<style type="text/css">
@import url("webman/modules/DataDrivenDocuments/style.css?v=1557442311");
@import url("webman/modules/ResourceMonitor/style.css?v=1557442311");
@import url("webman/modules/FileTaskMonitor/style.css?v=1555584024");
@import url("webman/modules/VideoPlayer2/style.css?v=1557442309");
@import url("webman/modules/HotkeyManager/style.css?v=1557442311");
@import url("webman/modules/Widgets/style.css?v=1557442311");
@import url("webman/modules/PersonalSettings/style.css?v=1557442311");
@import url("webman/modules/AdminCenter/style.css?v=1557442342");
@import url("webman/modules/EzInternet/style.css?v=1557442311");
@import url("webman/modules/WelcomeApp/style.css?v=1557442311");
@import url("webman/modules/WelcomeTip/style.css?v=1557442312");
@import url("webman/modules/ExternalDevices/style.css?v=1557442311");
@import url("webman/modules/MyDSCenter/style.css?v=1557442311");
@import url("webman/modules/HelpBrowser/style.css?v=1557442311");
@import url("webman/modules/PkgManApp/style.css?v=1557442311");
@import url("webman/modules/iSCSI/style.css?v=1557442145");
@import url("webman/modules/TaskSchedulerUtils/style.css?v=1557442311");
@import url("webman/modules/StorageManager/style.css?v=1557442311");
@import url("webman/modules/SecurityScan/style.css?v=1557442332");
@import url("webman/modules/TaskSchedulerWidget/style.css?v=1557442311");
@import url("webman/modules/C3/style.css?v=1557442311");
@import url("webman/modules/BandwidthControl/style.css?v=1557442145");
@import url("webman/modules/PollingTask/style.css?v=1557442312");
@import url("webman/modules/PhotoViewer/style.css?v=1557442311");
@import url("webman/modules/DSMNotify/style.css?v=1557442311");
@import url("webman/modules/Utils/style.css?v=1557442311");
@import url("webman/modules/FileBrowser/style.css?v=1555584060");
@import url("webman/modules/DiskMessageHandler/style.css?v=1557442311");
@import url("webman/modules/SupportForm/style.css?v=1557442311");
@import url("webman/modules/SystemInfoApp/style.css?v=1557442311");
</style>
<style type="text/css">
@import url("webman/modules/Share/style.css?v=1557442311");
@import url("webman/modules/ThumbConvertProgress/style.css?v="
2019-10-29 10:33:47: "Req 10:33:36: PROPFIND https://dav.mydomain.com/.lock {"headers":{"Depth":1,"Authorization":"********","If-None-Match":"JoplinIgnore-73030","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","timeout":120000,"maxRetry":0}"
2019-10-29 10:33:47: "Res 10:33:36: <!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=11" />
<meta name="msapplication-TileImage" content="resources/images/icon_tile.png?v=4398" />
<meta name="application-name" content="diskstation&nbsp;-&nbsp;Synology&nbsp;DiskStation" />
<meta name="msapplication-TileColor" content="#246BB3"/>
<meta name="description" content="DiskStation provides a full-featured network attached storage (NAS) solution to help you manage, backup and share data among Windows, Mac and Linux easily." />
<meta name="keywords" content="Multitasking,Web Application,Personal Cloud" />

<link rel="apple-touch-icon" href="webman/resources/images/icon_dsm_96.png?v=4398" />
<link rel="mask-icon" href="webman/safari_pin_icon.svg" color="#0086E5" />
<link rel="shortcut icon" href="webman/favicon.ico?v=4399" />
<link rel="shortcut icon" href="webman/resources/images/icon_dsm_96.png?v=4398" sizes="96x96"/>
<link rel="shortcut icon" href="webman/resources/images/icon_dsm_64.png?v=4398" sizes="64x64"/>
<link rel="shortcut icon" href="webman/resources/images/icon_dsm_48.png?v=4398" sizes="48x48"/>
<link rel="shortcut icon" href="webman/resources/images/icon_dsm_32.png?v=4398" sizes="32x32"/>
<link rel="shortcut icon" href="webman/resources/images/icon_dsm_16.png?v=4398" sizes="16x16"/>
<title>diskstation&nbsp;-&nbsp;Synology&nbsp;DiskStation</title>
<link rel="stylesheet" type="text/css" href="scripts/ext-3/resources/css/ext-all.css?v=1557442135" />
<link rel="stylesheet" type="text/css" href="scripts/ext-3/resources/css/xtheme-gray.css?v=1557442135" />
<link rel="stylesheet" type="text/css" href="scripts/ext-3/ux/ux-all.css?v=1557442135" />
<link rel="stylesheet" type="text/css" href="synoSDSjslib/sds.css?v=1557442142" />
<link rel="stylesheet" type="text/css" href="webman/resources/css/desktop.css?v=1562143394" />
<style type="text/css">
@import url("webman/modules/DataDrivenDocuments/style.css?v=1557442311");
@import url("webman/modules/ResourceMonitor/style.css?v=1557442311");
@import url("webman/modules/FileTaskMonitor/style.css?v=1555584024");
@import url("webman/modules/VideoPlayer2/style.css?v=1557442309");
@import url("webman/modules/HotkeyManager/style.css?v=1557442311");
@import url("webman/modules/Widgets/style.css?v=1557442311");
@import url("webman/modules/PersonalSettings/style.css?v=1557442311");
@import url("webman/modules/AdminCenter/style.css?v=1557442342");
@import url("webman/modules/EzInternet/style.css?v=1557442311");
@import url("webman/modules/WelcomeApp/style.css?v=1557442311");
@import url("webman/modules/WelcomeTip/style.css?v=1557442312");
@import url("webman/modules/ExternalDevices/style.css?v=1557442311");
@import url("webman/modules/MyDSCenter/style.css?v=1557442311");
@import url("webman/modules/HelpBrowser/style.css?v=1557442311");
@import url("webman/modules/PkgManApp/style.css?v=1557442311");
@import url("webman/modules/iSCSI/style.css?v=1557442145");
@import url("webman/modules/TaskSchedulerUtils/style.css?v=1557442311");
@import url("webman/modules/StorageManager/style.css?v=1557442311");
@import url("webman/modules/SecurityScan/style.css?v=1557442332");
@import url("webman/modules/TaskSchedulerWidget/style.css?v=1557442311");
@import url("webman/modules/C3/style.css?v=1557442311");
@import url("webman/modules/BandwidthControl/style.css?v=1557442145");
@import url("webman/modules/PollingTask/style.css?v=1557442312");
@import url("webman/modules/PhotoViewer/style.css?v=1557442311");
@import url("webman/modules/DSMNotify/style.css?v=1557442311");
@import url("webman/modules/Utils/style.css?v=1557442311");
@import url("webman/modules/FileBrowser/style.css?v=1555584060");
@import url("webman/modules/DiskMessageHandler/style.css?v=1557442311");
@import url("webman/modules/SupportForm/style.css?v=1557442311");
@import url("webman/modules/SystemInfoApp/style.css?v=1557442311");
</style>
<style type="text/css">
@import url("webman/modules/Share/style.css?v=1557442311");
@import url("webman/modules/ThumbConvertProgress/style.css?v="
2019-10-29 10:33:47: "Req 10:33:47: PROPFIND https://dav.mydomain.com/.lock {"headers":{"Depth":1,"Authorization":"********","If-None-Match":"JoplinIgnore-42665","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","timeout":120000,"maxRetry":0}"
2019-10-29 10:33:47: "Res 10:33:47: <!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=11" />
<meta name="msapplication-TileImage" content="resources/images/icon_tile.png?v=4398" />
<meta name="application-name" content="diskstation&nbsp;-&nbsp;Synology&nbsp;DiskStation" />
<meta name="msapplication-TileColor" content="#246BB3"/>
<meta name="description" content="DiskStation provides a full-featured network attached storage (NAS) solution to help you manage, backup and share data among Windows, Mac and Linux easily." />
<meta name="keywords" content="Multitasking,Web Application,Personal Cloud" />

<link rel="apple-touch-icon" href="webman/resources/images/icon_dsm_96.png?v=4398" />
<link rel="mask-icon" href="webman/safari_pin_icon.svg" color="#0086E5" />
<link rel="shortcut icon" href="webman/favicon.ico?v=4399" />
<link rel="shortcut icon" href="webman/resources/images/icon_dsm_96.png?v=4398" sizes="96x96"/>
<link rel="shortcut icon" href="webman/resources/images/icon_dsm_64.png?v=4398" sizes="64x64"/>
<link rel="shortcut icon" href="webman/resources/images/icon_dsm_48.png?v=4398" sizes="48x48"/>
<link rel="shortcut icon" href="webman/resources/images/icon_dsm_32.png?v=4398" sizes="32x32"/>
<link rel="shortcut icon" href="webman/resources/images/icon_dsm_16.png?v=4398" sizes="16x16"/>
<title>diskstation&nbsp;-&nbsp;Synology&nbsp;DiskStation</title>
<link rel="stylesheet" type="text/css" href="scripts/ext-3/resources/css/ext-all.css?v=1557442135" />
<link rel="stylesheet" type="text/css" href="scripts/ext-3/resources/css/xtheme-gray.css?v=1557442135" />
<link rel="stylesheet" type="text/css" href="scripts/ext-3/ux/ux-all.css?v=1557442135" />
<link rel="stylesheet" type="text/css" href="synoSDSjslib/sds.css?v=1557442142" />
<link rel="stylesheet" type="text/css" href="webman/resources/css/desktop.css?v=1562143394" />
<style type="text/css">
@import url("webman/modules/DataDrivenDocuments/style.css?v=1557442311");
@import url("webman/modules/ResourceMonitor/style.css?v=1557442311");
@import url("webman/modules/FileTaskMonitor/style.css?v=1555584024");
@import url("webman/modules/VideoPlayer2/style.css?v=1557442309");
@import url("webman/modules/HotkeyManager/style.css?v=1557442311");
@import url("webman/modules/Widgets/style.css?v=1557442311");
@import url("webman/modules/PersonalSettings/style.css?v=1557442311");
@import url("webman/modules/AdminCenter/style.css?v=1557442342");
@import url("webman/modules/EzInternet/style.css?v=1557442311");
@import url("webman/modules/WelcomeApp/style.css?v=1557442311");
@import url("webman/modules/WelcomeTip/style.css?v=1557442312");
@import url("webman/modules/ExternalDevices/style.css?v=1557442311");
@import url("webman/modules/MyDSCenter/style.css?v=1557442311");
@import url("webman/modules/HelpBrowser/style.css?v=1557442311");
@import url("webman/modules/PkgManApp/style.css?v=1557442311");
@import url("webman/modules/iSCSI/style.css?v=1557442145");
@import url("webman/modules/TaskSchedulerUtils/style.css?v=1557442311");
@import url("webman/modules/StorageManager/style.css?v=1557442311");
@import url("webman/modules/SecurityScan/style.css?v=1557442332");
@import url("webman/modules/TaskSchedulerWidget/style.css?v=1557442311");
@import url("webman/modules/C3/style.css?v=1557442311");
@import url("webman/modules/BandwidthControl/style.css?v=1557442145");
@import url("webman/modules/PollingTask/style.css?v=1557442312");
@import url("webman/modules/PhotoViewer/style.css?v=1557442311");
@import url("webman/modules/DSMNotify/style.css?v=1557442311");
@import url("webman/modules/Utils/style.css?v=1557442311");
@import url("webman/modules/FileBrowser/style.css?v=1555584060");
@import url("webman/modules/DiskMessageHandler/style.css?v=1557442311");
@import url("webman/modules/SupportForm/style.css?v=1557442311");
@import url("webman/modules/SystemInfoApp/style.css?v=1557442311");
</style>
<style type="text/css">
@import url("webman/modules/Share/style.css?v=1557442311");
@import url("webman/modules/ThumbConvertProgress/style.css?v="
2019-10-29 10:33:47: "Operations completed: "
2019-10-29 10:33:47: "Total folders: 4"
2019-10-29 10:33:47: "Total notes: 26"
2019-10-29 10:33:47: "Total resources: 25"
2019-10-29 10:33:47: "There was some errors:"
2019-10-29 10:33:47: "Error: PROPFIND .lock: Cannot parse XML response (200): <!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=11" />
<meta name="msapplication-TileImage" content="resources/images/icon_tile.png?v=4398" />
<meta name="application-name" content="diskstation&nbsp;-&nbsp;Synology&nbsp;DiskStation" />
<meta name="msapplication-TileColor" content="#246BB3"/>
<meta name="description" content="DiskStation provides a full-featured network attached storage (NAS) solution to help you manage, backup and share data among Windows, Mac and Linux easily." />
<meta name="keywords" content="Multitasking,Web Application,Personal Cloud" />

<link rel="apple-touch-icon" href="webman/resources/images/icon_dsm_96.png?v=4398" />
<link rel="mask-icon" href="webman/safari_pin_icon.svg" color="#0086E5" />
<link rel="shortcut icon" href="webman/favicon.ico?v=4399" />
<link rel="shortcut icon" href="webman/resources/images/icon_dsm_96.png?v=4398" sizes="96x96"/>
<link rel="shortcut icon" href="webman/
Code: 200
Error: PROPFIND .lock: Cannot parse XML response (200): <!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=11" />
<meta name="msapplication-TileImage" content="resources/images/icon_tile.png?v=4398" />
<meta name="application-name" content="diskstation&nbsp;-&nbsp;Synology&nbsp;DiskStation" />
<meta name="msapplication-TileColor" content="#246BB3"/>
<meta name="description" content="DiskStation provides a full-featured network attached storage (NAS) solution to help you manage, backup and share data among Windows, Mac and Linux easily." />
<meta name="keywords" content="Multitasking,Web Application,Personal Cloud" />

<link rel="apple-touch-icon" href="webman/resources/images/icon_dsm_96.png?v=4398" />
<link rel="mask-icon" href="webman/safari_pin_icon.svg" color="#0086E5" />
<link rel="shortcut icon" href="webman/favicon.ico?v=4399" />
<link rel="shortcut icon" href="webman/resources/images/icon_dsm_96.png?v=4398" sizes="96x96"/>
<link rel="shortcut icon" href="webman/
    at newError (/Applications/Joplin.app/Contents/Resources/app/lib/WebDavApi.js:384:11)
    at loadResponseJson (/Applications/Joplin.app/Contents/Resources/app/lib/WebDavApi.js:393:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)"
2019-10-29 10:33:49: "ResourceService::indexNoteResources: Start"
2019-10-29 10:33:50: "ResourceService::indexNoteResources: Completed"
2019-10-29 10:33:50: "ResourceService::deleteOrphanResources:", "[]"
```

**Comment by raman325** [comment]
This may be related to #1755 as when I hit the URL in my browser I get a directory listing

**Comment by raman325** [comment]
Looks like a known issue with this container: BytemarkHosting/docker-webdav#4

Going to close this

**Comment by raman325** [comment]
Actually @laurent22 any thoughts on why this is not an issue for the iOS client?

**Comment by laurent22** [comment]
I have no idea, as this is the same code for iOS and all the other clients.

I know that iOS adds extra headers which was causing bugs and for which I had to add workarounds, so it's possible these extra headers are actually making it work in this particular case.

**Comment by raman325** [comment]
Got it. Well for what it's worth, I checked the Docker logs for my container and it looks like both the iOS client and MacOS client get [405](https://httpstatuses.com/405)'s when making the MKCOL call, but the MacOS client performs multiple PROPFINDs which each return a [301](https://httpstatuses.com/301) while the iOS client performs a single PROPFIND which returns a [207](https://httpstatuses.com/207). I wonder if the 207 is encapsulating the multiple 301s but it's being treated as an OK here: https://github.com/laurent22/joplin/blob/master/ReactNativeClient/lib/WebDavApi.js#L405. If that's the case, the question is what are the implications of ignoring those errors and continuing with the sync operations?

**Comment by tessus** [comment]
@raman325 
> I've reopened this just to ensure visibility for this conversation. 

That's why these kind of issues belong to the forum. Whatever the outcome, people will see the discussion. And let's be honest. No user searches closed tickets (they don't even ssearch open ones). And we can't leave it open either, because otherwise we'd have an unmanageable number of issues.

@laurent22 maybe we could add another label that indicates some useful info, so at least we can create a link that lists those issues fot reference.
