### ISSUE TITLE
App crashes on Huawei P10 on startup

### ISSUE THREAD

**Issue by elfacht** [laurent22/joplin#2073]
Since a while the app crashes on Huawei P10 approx. 10 seconds after starting it. It doesn't occur on fresh installs, but with WebDav or Nextcloud syncing (didn't check the other options).  I have around 500 notes with images, links, checkboxes and nothing special. I don't use ToDos. I do have encryption activated and I'm syncing via Nextcloud (before that I used WebDav on Synology DS).

## Environment

Joplin version: 1.0.310
Platform: Android
OS specifcs: Android 9 / EMUI-Version 9.1.0 (Build 9.1.0.252)
Model: VTR-L09

## Steps To Reproduce

1. Install Joplin
2. Setup sync from desktop to either WebDav or Nextcloud
3. Have around 500 notes in (nested) notebooks
4. Using encryption
5. Sync on Android phone

## Logfile

[syncReport-1573489444975.txt](https://github.com/laurent22/joplin/files/3832269/syncReport-1573489444975.txt)

**Comment by laurent22** [comment]
For crashes, we would need a crash report from the device directly: https://joplinapp.org/debugging

**Comment by elfacht** [comment]
@laurent22 

I copied the relevant sections from it. If you need a certain section please let me know:

```
11-11 17:24:07.449 10349 22465 22785 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-2
11-11 17:24:07.449 10349 22465 22785 E AndroidRuntime: Process: net.cozic.joplin, PID: 22465
11-11 17:24:07.449 10349 22465 22785 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 118033536 byte allocation with 25165824 free bytes and 86MB until OOM, max allowed footprint 471401896, growth limit 536870912
11-11 17:24:07.449 10349 22465 22785 E AndroidRuntime: 	at java.lang.StringFactory.newStringFromChars(StringFactory.java:267)
11-11 17:24:07.449 10349 22465 22785 E AndroidRuntime: 	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:252)
11-11 17:24:07.449 10349 22465 22785 E AndroidRuntime: 	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:65)
11-11 17:24:07.449 10349 22465 22785 E AndroidRuntime: 	at android.util.Base64.encodeToString(Base64.java:456)
11-11 17:24:07.449 10349 22465 22785 E AndroidRuntime: 	at com.RNFetchBlob.RNFetchBlobFS.readFile(RNFetchBlobFS.java:199)
11-11 17:24:07.449 10349 22465 22785 E AndroidRuntime: 	at com.RNFetchBlob.RNFetchBlob$6.run(RNFetchBlob.java:226)
11-11 17:24:07.449 10349 22465 22785 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
11-11 17:24:07.449 10349 22465 22785 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
11-11 17:24:07.449 10349 22465 22785 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-11 17:24:07.449 10349 22465 22785 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:784)
11-11 17:24:26.657 10349 23119 23223 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-3
11-11 17:24:26.657 10349 23119 23223 E AndroidRuntime: Process: net.cozic.joplin, PID: 23119
11-11 17:24:26.657 10349 23119 23223 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 118033536 byte allocation with 8388608 free bytes and 85MB until OOM, max allowed footprint 455330912, growth limit 536870912
11-11 17:24:26.657 10349 23119 23223 E AndroidRuntime: 	at java.lang.StringFactory.newStringFromChars(StringFactory.java:267)
11-11 17:24:26.657 10349 23119 23223 E AndroidRuntime: 	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:252)
11-11 17:24:26.657 10349 23119 23223 E AndroidRuntime: 	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:65)
11-11 17:24:26.657 10349 23119 23223 E AndroidRuntime: 	at android.util.Base64.encodeToString(Base64.java:456)
11-11 17:24:26.657 10349 23119 23223 E AndroidRuntime: 	at com.RNFetchBlob.RNFetchBlobFS.readFile(RNFetchBlobFS.java:199)
11-11 17:24:26.657 10349 23119 23223 E AndroidRuntime: 	at com.RNFetchBlob.RNFetchBlob$6.run(RNFetchBlob.java:226)
11-11 17:24:26.657 10349 23119 23223 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
11-11 17:24:26.657 10349 23119 23223 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
11-11 17:24:26.657 10349 23119 23223 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-11 17:24:26.657 10349 23119 23223 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:784)

Chattiest UIDs in crash log buffer:                          Size
UID   PACKAGE                                               BYTES
10349 net.cozic.joplin                                       7636
1110106 com.instagram.android                                4257

------ 0.075s was the duration of 'LOG STATISTICS' ------
------ LAST LOGCAT (logcat -L -b all -v threadtime -v printable -v uid -d *:v) ------
*** command 'logcat -L -b all -v threadtime -v printable -v uid -d *:v' failed: exit code 1
------ 0.018s was the duration of 'LAST LOGCAT' ------
------ VM TRACES JUST NOW (/data/anr/dumptrace_BtUEK6: 2019-11-11 18:45:47) ------

ACTIVITY MANAGER URI PERMISSIONS (dumpsys activity permissions)
  Granted Uri Permissions:
  * UID 1000 holds:
    UriPermission{46ba1e2 content://com.huawei.hidisk.fileprovider/root/storage/emulated/0/Android/data/net.cozic.joplin/files/syncReport-1573489444975.txt [user 0]}
      targetUserId=0 sourcePkg=com.huawei.hidisk targetPkg=com.huawei.android.internal.app
      mode=0x1 owned=0x0 global=0x1 persistable=0x0 persisted=0x0

  Time since processes crashed:
    Process net.cozic.joplin uid 10349: last crashed +57m53s365ms ago



Message 84: { when=+1m55s852ms what=11 arg2=-1 obj=net.cozic.joplin target=com.android.server.usage.AppStandbyController$AppStandbyHandler }



Uid u0a349:
    state=cch  
    Package net.cozic.joplin:
      READ_EXTERNAL_STORAGE (allow): 
          Access: top   = 2019-11-11 17:29:15.233 (-1h17m13s649ms)
                  bg    = 2019-11-11 13:02:50.561 (-5h43m38s321ms)
                  cch   = 2019-11-11 17:29:15.174 (-1h17m13s708ms)
      WRITE_EXTERNAL_STORAGE (allow): 
          Access: top   = 2019-11-11 17:29:15.233 (-1h17m13s649ms)
                  bg    = 2019-11-11 13:02:50.561 (-5h43m38s321ms)
                  cch   = 2019-11-11 17:29:15.174 (-1h17m13s708ms)



+2d02h36m59s808ms (2) 059 c4100020 +top=u0a348:"net.cozic.joplin"
+2d02h36m59s852ms (2) 059 c4100020 pkgactive=u0a348:"net.cozic.joplin"

SubsystemPowerState Empty
    +2d02h37m21s848ms (2) 058 c4100020 stats=0:"wakelock-change"
    +2d02h37m27s353ms (2) 058 c4100020 stats=0:"remove-uid"
    +2d02h37m33s710ms (2) 058 c4100020 stats=0:"remove-uid"
    +2d02h37m35s287ms (2) 058 c4100020 stats=0:"remove-uid"
    +2d02h37m39s923ms (2) 058 c4100020 -top=u0a348:"net.cozic.joplin"


2019-11-11 17:24:07 data_app_crash (text, 1098 bytes)
    Process: net.cozic.joplin/PID: 22465/Flags: 0x3898be44/Package: net.co ...
2019-11-11 17:24:26 data_app_crash (text, 1096 bytes)
    Process: net.cozic.joplin/PID: 23119/Flags: 0x3898be44/Package: net.co ...


[net.cozic.joplin]
      Signing KeySets: 298

---null  10349  net.cozic.joplin  true---
   cpu power: (2,2, 102,2, 11,8) time: (2162, 0, 0, 108, 1802, sf(ms): 251370)
   wifi power: (1,165, 0,260, 9,373, 3,250) bg_RT: (271,17MB 2,65MB 189643 43652) fg_RT: (1794,16MB 24,24MB 1259193 395068) scan power: (0,00, 0,00) time: (0, 0)




 App in dead list State Info :
    PackageName:net.cozic.joplin
        Type:-1
        UID:[10349]
        Alarm unified(s):0, pending:false




time="2019-11-11 17:24:07" type=MOVE_TO_BACKGROUND package=net.cozic.joplin class=net.cozic.joplin.MainActivity flags=0x0 
time="2019-11-11 17:24:10" type=MOVE_TO_FOREGROUND package=net.cozic.joplin class=net.cozic.joplin.MainActivity flags=0x0 
time="2019-11-11 17:24:23" type=MOVE_TO_BACKGROUND package=net.cozic.joplin class=net.cozic.joplin.MainActivity flags=0x0 
```

**Comment by elfacht** [comment]
Somehow the app is running pretty stable since a few days. I cleared all the data and set up the sync via Nextcloud, but selcted `WebDav` as the option. Will keep an eye on it!

**Comment by laurent22** [comment]
Thanks for the feedback @elfacht. From the log, this is the app running out of memory for some reason. I'm hoping to fix this some day by switching to a different library to download the files. If it happens again anyway, feel free to post here.
