### ISSUE TITLE
notification not working in portable app 

### ISSUE THREAD

**Issue by era20** [laurent22/joplin#2144]
Alarm reminder of ToDo s  does not work in Desktop-Version. 

One can set an alarm and a synchronised Android Joplin reminds as it should, but reminder not working in Desktop-Version.

## Environment

Joplin version: Joplin portable 1.0.174.2317
Platform: Windows
OS specifcs: 7

**Comment by laurent22** [comment]
Log?

**Comment by era20** [comment]
Just set an alarm to a reminder.
See log lines
[log-lastAlarmSet.txt](https://github.com/laurent22/joplin/files/3917259/log-lastAlarmSet.txt)

**Comment by laurent22** [comment]
```
2019-12-03 15:56:00: "AlarmServiceDriverNode::scheduleNotification: Triggering notification:", "{"appID":"net.cozic.joplin-desktop","title":"TEST TO REminder","icon":"C:/Users/auer/AppData/Local/Temp/nsq36D9.tmp/app/resources/build/icons/512x512.png"}"
2019-12-03 15:56:00: "AlarmServiceDriverNode::scheduleNotification: node-notifier response:", "Error: Message is required.
Error: Message is required.
    at doNotification (C:\Users\auer\AppData\Local\Temp\nsq36D9.tmp\app\resources\app.asar\node_modules\node-notifier\notifiers\balloon.js:121:14)
    at WindowsBalloon.notify (C:\Users\auer\AppData\Local\Temp\nsq36D9.tmp\app\resources\app.asar\node_modules\node-notifier\notifiers\balloon.js:91:5)
    at setTimeout (C:\Users\auer\AppData\Local\Temp\nsq36D9.tmp\app\resources\app.asar\lib\services\AlarmServiceDriverNode.js:77:14)", "undefined"

```

**Comment by laurent22** [comment]
Seems the message property is required for Windows 7. I'll add it for the next version.

**Comment by corona6** [comment]
I have a same problem at Mac OS. (Needs more property?)

```
2019-12-12 16:00:00: "AlarmServiceDriverNode::scheduleNotification: Triggering notification:", "{"appID":"net.cozic.joplin-desktop","title":"test todo","icon":"/Applications/Joplin.app/Contents/Resources/build/icons/512x512.png"}"
2019-12-12 16:00:00: "AlarmServiceDriverNode::scheduleNotification: node-notifier response:", "Error: Message, group, remove or list property is required.
Error: Message, group, remove or list property is required.
    at NotificationCenter.notify (/Applications/Joplin.app/Contents/Resources/app/node_modules/node-notifier/notifiers/notificationcenter.js:75:14)
    at setTimeout (/Applications/Joplin.app/Contents/Resources/app/lib/services/AlarmServiceDriverNode.js:77:14)", "undefined"
```

#### Environment

Joplin 1.0.175 (prod, darwin)
Revision: 7ad407a (HEAD)
