### ISSUE TITLE
1.0.177 and 1.0.178: git repo not found error when building

### ISSUE THREAD

**Issue by taw00** [laurent22/joplin#2256]
I'm building the app. I see this. It doesn't say much that I understand, but ... 
```
[ ... ]
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/VerticalResizer.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/plugins/GotoAnything.jsx...
fatal: not a git repository (or any of the parent directories): .git
Could not get git info Error: Command failed: git rev-parse --abbrev-ref HEAD
fatal: not a git repository (or any of the parent directories): .git

    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at Object.<anonymous> (/builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/compile-package-info.js:23:11)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  status: 128,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 66 61 74 61 6c 3a 20 6e 6f 74 20 61 20 67 69 74 20 72 65 70 6f 73 69 74 6f 72 79 20 28 6f 72 20 61 6e 79 20 6f 66 20 74 68 65 20 70 61 72 65 6e 74 20 ... 19 more bytes>
  ],
  pid: 362,
  stdout: <Buffer >,
  stderr: <Buffer 66 61 74 61 6c 3a 20 6e 6f 74 20 61 20 67 69 74 20 72 65 70 6f 73 69 74 6f 72 79 20 28 6f 72 20 61 6e 79 20 6f 66 20 74 68 65 20 70 61 72 65 6e 74 20 ... 19 more bytes>
}
```

**Comment by taw00** [comment]
The application successfully builds, but when run, it looks like this (see image: all white, just a window frame really). I don't know if the issue initially reported with this bug and the failure to run (see image) are related. Note: the appimage you guys built seems to work fine. Both the appimage and my build, when run from the commandline, show the same minor errors, so I don't know what is going on here without digging into an strace or some such.

![Screenshot from 2020-01-02 10-54-06](https://user-images.githubusercontent.com/6908872/71676988-985b2d80-2d4f-11ea-9c1d-ced9fc16513d.png)

**Comment by laurent22** [comment]
As mentioned in BUILD.md, did you try this?

> - In ElectronAppWrapper, set `debugEarlyBugs` to `true`. This will force the window to show up and should open the console next to it, which should display any error.

**Comment by taw00** [comment]
I'll take a look. Holidays. Just meant I took a preliminary stab at it. I'll let you know.
-todd

**Comment by taw00** [comment]
The console error says that loader.js is not there, which is unsurprising since there is a git failure in the build process. I will try to dig into why that git repo is not resolving.

**Comment by taw00** [comment]
Maybe more info is helpful. This happens within the `npm install` after the `cd ElectronClient/app` ...
```
+ npm install

> sqlite3@4.1.1 install /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
[sqlite3] Success: "/builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/node_modules/sqlite3/lib/binding/node-v72-linux-x64/node_sqlite3.node" is installed via remote

> ejs@2.7.4 postinstall /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> core-js@3.5.0 postinstall /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/node_modules/global-agent/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> electron@7.1.5 postinstall /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/node_modules/electron
> node install.js


> Joplin@1.0.177 postinstall /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app
> node compile.js && node compile-package-info.js && node electronRebuild.js

Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/ClipperConfigScreen.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/ConfigMenuBar.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/ConfigScreen.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/DialogButtonRow.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/DropboxLoginScreen.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/EncryptionConfigScreen.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/ExtensionBadge.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/Header.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/HelpButton.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/IconButton.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/ImportScreen.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/ItemList.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/MainScreen.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/Navigator.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/NoteList.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/NotePropertiesDialog.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/NoteRevisionViewer.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/NoteSearchBar.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/NoteStatusBar.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/NoteText.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/NoteTextViewer.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/OneDriveLoginScreen.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/PromptDialog.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/Root.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/SideBar.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/StatusScreen.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/TagItem.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/TagList.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/Toolbar.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/ToolbarButton.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/ToolbarSpace.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/gui/VerticalResizer.jsx...
Compiling /builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/plugins/GotoAnything.jsx...
fatal: not a git repository (or any of the parent directories): .git
Could not get git info Error: Command failed: git rev-parse --abbrev-ref HEAD
fatal: not a git repository (or any of the parent directories): .git

    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at Object.<anonymous> (/builddir/build/BUILD/joplin-1.0/joplin-1.0.177/ElectronClient/app/compile-package-info.js:23:11)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  status: 128,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 66 61 74 61 6c 3a 20 6e 6f 74 20 61 20 67 69 74 20 72 65 70 6f 73 69 74 6f 72 79 20 28 6f 72 20 61 6e 79 20 6f 66 20 74 68 65 20 70 61 72 65 6e 74 20 ... 19 more bytes>
  ],
  pid: 418,
  stdout: <Buffer >,
  stderr: <Buffer 66 61 74 61 6c 3a 20 6e 6f 74 20 61 20 67 69 74 20 72 65 70 6f 73 69 74 6f 72 79 20 28 6f 72 20 61 6e 79 20 6f 66 20 74 68 65 20 70 61 72 65 6e 74 20 ... 19 more bytes>
}
```

**Comment by taw00** [comment]
@laurent22
Did you change something where a git call is now being used somewhere buried in the scripts? I ran across something similar with my riot builds and it has something to do with js.sdk being new and versionings not lining up and a git call made mid-process and in certain circumstances everything fails because the repo acted upon ends up not being a git repo.

I am articulating that poorly, but... are you doing some funky stuff to pull in a newer library forcibly?

**Comment by laurent22** [comment]
In compile-package-info.js we have some code that gets the current commit, but it's been there for a long time. There's a try/catch block to make sure that if the git commands fail, they don't prevent the app to build, so not sure what is happening.

**Comment by taw00** [comment]
Okay. Thanks. I haven't had a solid block of time to really dig into it yet. I'll let you know if I find anything.

**Comment by laurent22** [comment]
Ok let me know. If needed I can make a few tweaks to accommodate building from tar.

**Comment by taw00** [comment]
FYI @laurent22 1.0.178 also failing. Same way.
I also tried just making the tarball into a git repo with `git init` and all that did was trigger a "wrong HEAD version" error (wording is not exact).

**Comment by taw00** [comment]
Same error, even when building from a downloaded version of the repo that includes the git info.
I am running out of ideas.

**Comment by taw00** [comment]
Okay. I got it to build. But only by cloning the repository — `git clone https://github.com/laurent22/joplin.git --branch=v1.0.178 joplin-1.0.178` — And that is broken. Cuz, the repo tarred up is over 100MB. And it's messy for other reasons. I am not sure how to get by this. Open to suggestions. Otherwise, the build fails.

**Comment by taw00** [comment]
I'm going to experiment. And if need be, I will artificially do something with that block of code:
```
if (typeof branch !== 'undefined' && typeof hash !== 'undefined') {
    packageInfo.git = { branch: branch, hash: hash };
}
```

I'm no javascript expert, but I suspect I can figure out how to plug in expected values if push comes to shove.

**Comment by taw00** [comment]
This is all a red herring. Something is wrong with 1.0.177. I don't know what it is, but it was disguised by this error in the build. And the console pulls up the same error as displayed in the build.

1.0.177 displays a white screen and that is it. 1.0.178 though it errors in the build (and it is labeled "fatal" which is scary), it is fully functional after the build. Or at least it seems to be. I don't know what that git data is supposed to do, but since the released tarball doesn't have git info, it just throws up that fatal (though not fatal) error.

I don't know what to make of it. It bothers me that I couldn't pin down why 1.0.177 was broken. But there you have it, @laurent22 ... I hope all that helps. Closing this, but... Yeah. Dunno.

**Comment by laurent22** [comment]
There was two problems: first the git command was printing directly to stdout, and then we were printing the error message too, thus the messy output.

The error is fatal for git indeed, as there's no .git directory, but not for us since it's not critical information.

So I've tweaked the script to fix these issues, so it will now build more cleanly when no .git directory is present.
