### ISSUE TITLE
PROPFIND : Unknown error 2 (500): (Code 500) with WebDAV synchronization

### ISSUE THREAD

**Issue by Trilarion** [laurent22/joplin#2261]
Cannot synchronize with WebDAV from my webspace provider (udmedia.de). It gives an error with Joplin. The displayed error message after a few seconds waiting time is: PROPFIND .lock/: Unknown error 2 (500).

From Edge for example access seems to work. Folders ".sync", ".resource", ".lock" are created.

## Environment

Joplin version: 1.0.175
Platform: Windows
OS specifcs: 10

## Steps To Reproduce

1. Get webspace from udmedia.de that includes webdav capability.
2. Setup webdav with this webspace.
3. Insert webdav URL in Joplin/Options/Synchronization
4. Check synchronization status or click on synchronize in the main window

Describe what you expected to happen:

No error. Synching instead.

## Logfile

No output in the console.

From log file:

> 2020-01-03 17:57:04: "Garbage collecting alarms..."
2020-01-03 17:57:04: "RevisionService::maintenance: Starting..."
2020-01-03 17:57:04: "RevisionService::maintenance: Service is enabled"
2020-01-03 17:57:04: "RevisionService::collectRevisions: Created revisions for 0 notes"
2020-01-03 17:57:04: "RevisionService::maintenance: Done in 107ms"
2020-01-03 17:57:09: "Scheduling sync operation..."
2020-01-03 17:57:09: "Preparing scheduled sync"
2020-01-03 17:57:09: "Starting scheduled sync"
2020-01-03 17:57:30: "Error: MKCOL .sync/: Unknown error 2 (500): 
Code: 500
Error: MKCOL .sync/: Unknown error 2 (500): 
    at newError (C:\Program Files\Joplin\resources\app.asar\lib\WebDavApi.js:393:11)
    at WebDavApi.exec (C:\Program Files\Joplin\resources\app.asar\lib\WebDavApi.js:423:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)"
2020-01-03 17:57:30: "Req 17:56:24: MKCOL https://webdav.frype.de/joplin/.sync/ {"headers":{"Authorization":"********","If-None-Match":"JoplinIgnore-89702","User-Agent":"Joplin/1.0"},"timeout":120000,"maxRetry":0}"
2020-01-03 17:57:30: "Res 17:56:24: "
2020-01-03 17:57:30: "Req 17:56:24: MKCOL https://webdav.frype.de/joplin/.lock/ {"headers":{"Authorization":"********","If-None-Match":"JoplinIgnore-3623","User-Agent":"Joplin/1.0"},"timeout":120000,"maxRetry":0}"
2020-01-03 17:57:30: "Res 17:56:24: "
2020-01-03 17:57:30: "Req 17:56:24: MKCOL https://webdav.frype.de/joplin/.resource/ {"headers":{"Authorization":"********","If-None-Match":"JoplinIgnore-73280","User-Agent":"Joplin/1.0"},"timeout":120000,"maxRetry":0}"
2020-01-03 17:57:30: "Res 17:56:24: "
2020-01-03 17:57:30: "Req 17:56:24: PROPFIND https://webdav.frype.de/joplin/.lock/ {"headers":{"Depth":1,"Authorization":"********","If-None-Match":"JoplinIgnore-34468","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","timeout":120000,"maxRetry":0}"
2020-01-03 17:57:30: "Res 17:56:24: "
2020-01-03 17:57:30: "Req 17:56:28: PROPFIND https://webdav.frype.de/joplin/.lock/ {"headers":{"Depth":1,"Authorization":"********","If-None-Match":"JoplinIgnore-42848","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","timeout":120000,"maxRetry":0}"
2020-01-03 17:57:30: "Res 17:56:28: "
2020-01-03 17:57:30: "Req 17:56:36: PROPFIND https://webdav.frype.de/joplin/.lock/ {"headers":{"Depth":1,"Authorization":"********","If-None-Match":"JoplinIgnore-87059","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","timeout":120000,"maxRetry":0}"
2020-01-03 17:57:30: "Res 17:56:36: "
2020-01-03 17:57:30: "Req 17:56:46: PROPFIND https://webdav.frype.de/joplin/.lock/ {"headers":{"Depth":1,"Authorization":"********","If-None-Match":"JoplinIgnore-62908","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","timeout":120000,"maxRetry":0}"
2020-01-03 17:57:30: "Res 17:56:46: "
2020-01-03 17:57:30: "Req 17:57:09: MKCOL https://webdav.frype.de/joplin/.sync/ {"headers":{"Authorization":"********","If-None-Match":"JoplinIgnore-38486","User-Agent":"Joplin/1.0"},"timeout":120000,"maxRetry":0}"
2020-01-03 17:57:30: "Res 17:57:09: "
2020-01-03 17:57:30: "Req 17:57:13: MKCOL https://webdav.frype.de/joplin/.sync/ {"headers":{"Authorization":"********","If-None-Match":"JoplinIgnore-53983","User-Agent":"Joplin/1.0"},"timeout":120000,"maxRetry":0}"
2020-01-03 17:57:30: "Res 17:57:13: "
2020-01-03 17:57:30: "Req 17:57:20: MKCOL https://webdav.frype.de/joplin/.sync/ {"headers":{"Authorization":"********","If-None-Match":"JoplinIgnore-57958","User-Agent":"Joplin/1.0"},"timeout":120000,"maxRetry":0}"
2020-01-03 17:57:30: "Res 17:57:20: "
2020-01-03 17:57:30: "Req 17:57:30: MKCOL https://webdav.frype.de/joplin/.sync/ {"headers":{"Authorization":"********","If-None-Match":"JoplinIgnore-76446","User-Agent":"Joplin/1.0"},"timeout":120000,"maxRetry":0}"
2020-01-03 17:57:30: "Res 17:57:30: "
2020-01-03 17:57:30: "Operations completed: "
2020-01-03 17:57:30: "Total folders: 1"
2020-01-03 17:57:30: "Total notes: 4"
2020-01-03 17:57:30: "Total resources: 3"
2020-01-03 17:57:30: "There was some errors:"
2020-01-03 17:57:30: "Error: MKCOL .sync/: Unknown error 2 (500): 
Code: 500
Error: MKCOL .sync/: Unknown error 2 (500): 
    at newError (C:\Program Files\Joplin\resources\app.asar\lib\WebDavApi.js:393:11)
    at WebDavApi.exec (C:\Program Files\Joplin\resources\app.asar\lib\WebDavApi.js:423:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)"

**Comment by tessus** [comment]
This is a user question. Please use the forum.

It looks like you have authorization issues with your provider. Is 2FA enabled? In that case, you usually have to create a token on the server and use that instead of the password.
Either way, error 500 is an internal server error. Thus talk to the server admin.

This is not a bug in Joplin.

**Comment by Trilarion** [comment]
Are you sure, that it's not a bug in Joplin? As I wrote, using the very same WebDAV URL and user name as well as password I can access the WebDAV space just fine with a browser like Edge or the Windows explorer at exactly the same time? From my perspective the only thing that doesn't work is Joplin currently.

I'm happy to post at the forum, just wanted to check that it's really not a bug.

**Comment by tessus** [comment]
Let's put it that way. 97% of these error messages turn out to be the user's fault. Or the provider's.
We like to use the gh issue tracker to track real/reproducible bugs, so if we find out it is one, we can re-open this or create a new one.

e.g. we have test cases for webdav. They pass.
I use Nextcloud - which uses webdav - and it works. I have an Apache webdav endpoint for testing. It works. I use all clients except the desktop versions on Linux and Windows. They work.

**Comment by Trilarion** [comment]
Okay, will use the forum.

**Comment by Trilarion** [comment]
I contacted my webspace service. It was able to reproduce and solve the problem. It now works. Thanks for taking the time and answering to this report here.

**Comment by tessus** [comment]
Can you please let us know what the fix was? This might help others with the same error in the future. This is the reason why this should have been done on the forum. Now nobody knows about it and nobody knows what the problem was....

**Comment by manuelm** [comment]
Our WebDAV service was unable to generate an ETag-Header for a directory and returned an HTTP 500 instead. ETags for files were working fine though.

**Comment by tessus** [comment]
@manuelm thanks!

**Comment by tessus** [comment]
https://discourse.joplinapp.org/t/propfind-unknown-error-2-500-code-500-with-webdav-synchronization/5081?u=tessus
