### ISSUE TITLE
Desktop and command line versions cannot be used in parallel after update of Desktop version

### ISSUE THREAD

**Issue by danifischer** [laurent22/joplin#2392]
Homebrew versions for Joplin Desktop and Joplin command line are different:
- Desktop: 1.0.179
- Command line: 1.0.150

Due to this the same data sources cannot be used for both.

```
> brew info joplin
joplin: stable 1.0.150 (bottled)
```

```
> brew cask info joplin
joplin: 1.0.179
```

## Environment

Joplin version: 1.0.179 & 1.0.150
Platform: MacOS
OS specifcs: Catalina 10.15.2

## Steps To Reproduce

1. Install both versions
2. Set a symlink to have the same data source for both versions
3. Use the Desktop version first to create a document
4. Console version will not start

Describe what you expected to happen:
Using the same data source should be possible with both versions.

## Logfile

```
Fatal error:
Error: Unknown profile version. Most likely this is an old version of Joplin, while the profile was created by a newer version. Please upgrade Joplin at https://joplinapp.org and try again.
    at JoplinDatabase.upgradeDatabase (/usr/local/Cellar/joplin/1.0.150/libexec/lib/node_modules/joplin/lib/joplin-database.js:311:38)
    at JoplinDatabase.initialize (/usr/local/Cellar/joplin/1.0.150/libexec/lib/node_modules/joplin/lib/joplin-database.js:708:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Application.start (/usr/local/Cellar/joplin/1.0.150/libexec/lib/node_modules/joplin/lib/BaseApplication.js:597:3)
    at async Application.start (/usr/local/Cellar/joplin/1.0.150/libexec/lib/node_modules/joplin/app.js:386:10)
```

**Comment by laurent22** [comment]
>  Using the same data source should be possible with both versions.

It fact it should not. We explicitly don't support this use case, as it can lead to loss of data or corrupted profiles.

Having the same data on desktop and cli is supported via synchronisation.
