### ISSUE TITLE
CLI relies on node in PATH (collision when user switches between versions)

### ISSUE THREAD

**Issue by cabbage** [laurent22/joplin#250]
### Operating system

- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [ ] Desktop
- [ ] Mobile
- [x] Terminal

Hi,

I use [nvm](https://github.com/creationix/nvm) (Node Version Manager) to switch through different node versions as I need it. This leads to missing dependencies when I start joplin while having a different node version in PATH than the one installed by Homebrew. 

```
11:50 $ nvm use default
Now using node v8.9.3 (npm v5.5.1)
✔ ~
11:50 $ joplin
module.js:538
    throw err;
    ^

Error: Cannot find module '/usr/local/Cellar/joplin/1.0.99/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v57-darwin-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/Cellar/joplin/1.0.99/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```
When I use the node installed by Homebrew there's no issue. However, I don't want to be bothered to check which node is currently active before starting joplin.

Maybe for the brew build you could use `$(brew --prefix)/bin/node` in `run.sh` instead of the node available in the current shell.

**Comment by laurent22** [comment]
Doing this application side might too heavy because it'd need to check the OS, if brew is available, and if it is if it was indeed installed via Homebrew. Is it not possible to create an alias and force the right node version before starting the app?
