### ISSUE TITLE
macOS CLI: Unhandled promise rejection Promise

### ISSUE THREAD

**Issue by elfacht** [laurent22/joplin#2536]
Starting the app on Mojave 10.14.6 via CLI doesn't work for me:

```
$ joplin
Unhandled promise rejection Promise {
  <rejected> TypeError: Cannot read property 'parent_id' of null
    at FolderListWidget.folderDepth (/Users/elfacht/.nvm/versions/node/v9.8.0/lib/node_modules/joplin/gui/FolderListWidget.js:46:16)
    at FolderListWidget.itemRenderer [as itemRenderer_] (/Users/elfacht/.nvm/versions/node/v9.8.0/lib/node_modules/joplin/gui/FolderListWidget.js:28:33)
    at FolderListWidget.render (/Users/elfacht/.nvm/versions/node/v9.8.0/lib/node_modules/joplin/node_modules/tkwidgets/ListWidget.js:285:46)
    at FolderListWidget.render (/Users/elfacht/.nvm/versions/node/v9.8.0/lib/node_modules/joplin/gui/FolderListWidget.js:152:9)
    at Renderer.renderWidget (/Users/elfacht/.nvm/versions/node/v9.8.0/lib/node_modules/joplin/node_modules/tkwidgets/framework/Renderer.js:53:12)
    at Renderer.renderWidget (/Users/elfacht/.nvm/versions/node/v9.8.0/lib/node_modules/joplin/node_modules/tkwidgets/framework/Renderer.js:74:15)
    at Renderer.renderWidget (/Users/elfacht/.nvm/versions/node/v9.8.0/lib/node_modules/joplin/node_modules/tkwidgets/framework/Renderer.js:74:15)
    at <anonymous> } reason: TypeError: Cannot read property 'parent_id' of null
    at FolderListWidget.folderDepth (/Users/elfacht/.nvm/versions/node/v9.8.0/lib/node_modules/joplin/gui/FolderListWidget.js:46:16)
    at FolderListWidget.itemRenderer [as itemRenderer_] (/Users/elfacht/.nvm/versions/node/v9.8.0/lib/node_modules/joplin/gui/FolderListWidget.js:28:33)
    at FolderListWidget.render (/Users/elfacht/.nvm/versions/node/v9.8.0/lib/node_modules/joplin/node_modules/tkwidgets/ListWidget.js:285:46)
    at FolderListWidget.render (/Users/elfacht/.nvm/versions/node/v9.8.0/lib/node_modules/joplin/gui/FolderListWidget.js:152:9)
    at Renderer.renderWidget (/Users/elfacht/.nvm/versions/node/v9.8.0/lib/node_modules/joplin/node_modules/tkwidgets/framework/Renderer.js:53:12)
    at Renderer.renderWidget (/Users/elfacht/.nvm/versions/node/v9.8.0/lib/node_modules/joplin/node_modules/tkwidgets/framework/Renderer.js:74:15)
    at Renderer.renderWidget (/Users/elfacht/.nvm/versions/node/v9.8.0/lib/node_modules/joplin/node_modules/tkwidgets/framework/Renderer.js:74:15)
    at <anonymous>
```

Changing the Node versions via `nvm` to 8.* or 10.* won't help. Either did `joplin e2ee decrypt`.

## Environment

Joplin version: 1.0.153 (CLI), 1.0.179 (desktop)
Platform: macOS Mojave
OS specifcs: 10.14.6

## Steps To Reproduce

1. Install Joplin via .dmg
2. Setup sync with Nextcloud or smth. (Don't know if this error occurs on fresh installs)
3. Start the application via CLI with `joplin`

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/4230773/log.txt)

**Comment by tessus** [comment]
I'm using macOS 10.14.6 and I can't reproduce this. joplin 1.0.155 (prod)

**Comment by elfacht** [comment]
@tessus Maybe its a `1.0.179` related problem. That's the version I'm using.

**Comment by tessus** [comment]
@elfacht there'a no 1.0.179 version for cli. I'm seriously confused. Are you using the desktop version or the cli version?

You mentioned in step 3 that you atarted the application with `joplin`. You can't start the desktop app with `joplin`. You would have to go to `/Applications/Joplin.app/Contents/MacOS/` and start the app with `./Joplin`.

**Comment by elfacht** [comment]
@tessus Sorry, my fault. The CLI is on version 1.0.153 and I'm expecting the CLI version to open.

**Comment by tessus** [comment]
@elfacht please update the cli version to 1.0.155.

**Comment by elfacht** [comment]
@tessus `brew upgrade joplin` only delivers 1.0.153. Installing it via `npm` throws a new error. Any idea how to get the 1.0.155?

**Comment by elfacht** [comment]
Ok, somehow it works now with Node 10.* and installing via npm …

**Comment by tessus** [comment]
@laurent22 I think it's time to remove the `brew install` option from the documentation.

**Comment by laurent22** [comment]
Hmm, I'd rather have it there since it's a popular option, but yes the issue is that we can't support it. All this thread should be on the Homebrew repo where they might actually know something.

**Comment by tessus** [comment]
Ok, in that case, we should state that **any** problems when installed via brew will have to be reported to brew.

**Comment by laurent22** [comment]
Yes, I think for this and the Arch Linux package, we should have a text in bold that says **Any problem with this installation method should be reported to http://....** with a link to the respective repositories.
