### ISSUE TITLE
Issue installing on node v6.8.0

### ISSUE THREAD

**Issue by reggi** [laurent22/joplin#26]
```
➜  ~ git:(master) ✗ npm install -g joplin
npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/treggi/.nvm/versions/node/v6.8.0/bin/node" "/Users/treggi/.nvm/versions/node/v6.8.0/bin/npm" "install" "-g" "joplin"
npm ERR! node v6.8.0
npm ERR! npm  v3.10.8
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: mime@^2.0.3
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.6.0, 1.5.0, 1.4.1, 1.3.6, 1.3.4, 1.2.11, 1.2.7, 1.2.6, 1.2.5, 1.2.4, 1.2.2
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'joplin'
npm ERR! notarget 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/treggi/npm-debug.log
```

**Comment by laurent22** [comment]
Yes the app requires Node 8.x to work (I've specified it in the package config but somehow it doesn't show any error about this). I think you can get it from Homebrew as 8.x as recently moved to LTS so it should be available everywhere.

**Comment by reggi** [comment]
Thanks! @laurent22 

Any thoughts in building with nexe (https://github.com/nexe/nexe) and publishing joplin on homebrew?

**Comment by haloux** [comment]
Similar situation: Installed on Node 6.12 (debian-sid)
```greg at observatory in ~/SummitRepos/tools
>>> sudo npm install -g joplin 
npm WARN engine joplin@0.10.77: wanted: {"node":">=8.7.0"} (current: {"node":"6.12.0","npm":"1.4.21"})
-
> sharp@0.18.4 install /usr/local/lib/node_modules/joplin/node_modules/sharp
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/joplin/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/operations.o
  CXX(target) Release/obj.target/sharp/src/pipeline.o
  CXX(target) Release/obj.target/sharp/src/sharp.o
  CXX(target) Release/obj.target/sharp/src/utilities.o
  SOLINK_MODULE(target) Release/obj.target/sharp.node
  COPY Release/sharp.node
  TOUCH Release/obj.target/win_copy_dlls.stamp
make: Leaving directory '/usr/local/lib/node_modules/joplin/node_modules/sharp/build'
npm WARN package.json jsonify@0.0.0 license should be a valid SPDX license expression
npm WARN package.json sntp@1.0.9 No license field.

> sqlite3@3.1.13 install /usr/local/lib/node_modules/joplin/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "/usr/local/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node" is installed via remote
/usr/local/bin/joplin -> /usr/local/lib/node_modules/joplin/main.js
joplin@0.10.77 /usr/local/lib/node_modules/joplin
├── string-padding@1.0.2
├── os-tmpdir@1.0.2
├── sax@1.2.4
├── server-destroy@1.0.1
├── word-wrap@1.2.3
├── html-entities@1.2.1
├── jssha@2.3.1
├── levenshtein@1.0.5
├── uuid@3.1.0
├── mime@2.0.3
├── strip-ansi@4.0.0 (ansi-regex@3.0.0)
├── query-string@4.3.4 (strict-uri-encode@1.1.0, object-assign@4.1.1)
├── yargs-parser@7.0.0 (camelcase@4.1.0)
├── md5@2.2.1 (charenc@0.0.2, crypt@0.0.2, is-buffer@1.1.6)
├── sprintf-js@1.1.1
├── app-module-path@2.2.0
├── node-emoji@1.8.1 (lodash.toarray@4.4.0)
├── proper-lockfile@2.0.1 (graceful-fs@4.1.11, retry@0.10.1)
├── form-data@2.3.1 (asynckit@0.4.0, combined-stream@1.0.5, mime-types@2.1.17)
├── follow-redirects@1.2.6 (debug@3.1.0)
├── tcp-port-used@0.1.2 (debug@0.7.4, q@0.9.7, is2@0.0.9)
├── string-to-stream@1.1.0 (inherits@2.0.3, readable-stream@2.3.3)
├── promise@7.3.1 (asap@2.0.6)
├── node-persist@2.1.0 (q@1.1.2, mkdirp@0.5.1, is-absolute@0.2.6)
├── node-fetch@1.7.3 (is-stream@1.1.0, encoding@0.1.12)
├── fs-extra@3.0.1 (universalify@0.1.1, jsonfile@3.0.1, graceful-fs@4.1.11)
├── moment@2.19.3
├── tkwidgets@0.5.20 (wrap-ansi@3.0.1, slice-ansi@1.0.0, node-emoji@1.8.1, string-width@2.1.1, chalk@2.3.0, emphasize@1.5.0, terminal-kit@1.14.3)
├── redux@3.7.2 (symbol-observable@1.1.0, loose-envify@1.3.1, lodash-es@4.17.4)
├── lodash@4.17.4
├── sharp@0.18.4 (detect-libc@0.2.0, semver@5.4.1, simple-get@2.7.0, nan@2.8.0, color@2.0.1, tar@3.2.1, caw@2.0.1)
└── sqlite3@3.1.13 (nan@2.7.0)
```

When run, the following occurs:
```greg at observatory in ~/SummitRepos/tools
>>> joplin    
/usr/local/lib/node_modules/joplin/app.js:47
	async guessTypeAndLoadItem(pattern, options = null) {
	      ^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/joplin/main.js:7:17)
```
I understand that it requires Node8.x to work. Just shedding some light onto some of the reasons _why_ it might not work.

**Comment by laurent22** [comment]
Thanks, the installation issues have now been clarified in the doc.
