### ISSUE TITLE
Error: Unsupported WebDAV URL format

### ISSUE THREAD

**Issue by hubitor** [laurent22/joplin#2707]
I wanted to try the synchronisation over NextCloud for the first time but it didn't work. I've uninstalled Joplin, removed all config folders and reinstalled. Now I'm trying again following the instructions from the Welcome notebook as well as:
[https://joplinapp.org/faq/#nextcloud-sync-is-not-working](https://joplinapp.org/faq/#nextcloud-sync-is-not-working)
[https://github.com/laurent22/joplin/issues/61#issuecomment-373282608](url)
but the synchronization still does not work although Joplin gives this message:

> Success! Synchronization configuration appears to be correct.

I click on the Synchronize button but no files are synced. 

## Environment

Joplin version: 1.0.179-1
Platform: Linux
OS specifics: Arch Linux

## Steps to reproduce

1. Run NextCloud ($ docker run -d -p 8080:80 nextcloud)
2. Install Joplin
3. Setup NextCloud according to the instructions
 a. Copy WebDAV URL from the settings in NextCloud:
http://localhost:8080/remote.php/dav/files/docker/
 b. Create a folder `Joplin` under the root.
 c. Joplin Settings: Nextcloud WebDAV URL: http://localhost:8080/remote.php/dav/files/docker/Joplin
 d. Click on the button "Check synchronisation configuration"
3. Start Syncing

## Logfile

```
2020-03-09 19:39:34: "Profile directory: /home/nick/.config/joplin-desktop"
2020-03-09 19:39:39: "First start: detected locale as en_US"
2020-03-09 19:39:39: "Trying to load 0 master keys..."
2020-03-09 19:39:39: "Loaded master keys: 0"
2020-03-09 19:39:39: "ResourceFetcher: Auto-add resources: Mode: always"
2020-03-09 19:39:39: "ResourceFetcher: Auto-added resources: 0"
2020-03-09 19:39:39: "Running migration: 20"
2020-03-09 19:39:39: "Running migration: 27"
2020-03-09 19:39:39: "Trying to load 0 master keys..."
2020-03-09 19:39:39: "Loaded master keys: 0"
2020-03-09 19:39:39: "Scheduling sync operation..."
2020-03-09 19:39:39: "Trying to load 0 master keys..."
2020-03-09 19:39:39: "Loaded master keys: 0"
2020-03-09 19:39:39: "Scheduling sync operation..."
2020-03-09 19:39:39: "Trying to load 0 master keys..."
2020-03-09 19:39:39: "Loaded master keys: 0"
2020-03-09 19:39:39: "Scheduling sync operation..."
2020-03-09 19:39:40: "Scheduling sync operation..."
2020-03-09 19:39:40: "RevisionService::runInBackground: Starting background service with revision collection interval 600000"
2020-03-09 19:39:40: "Scheduling sync operation..."
2020-03-09 19:39:40: "DecryptionWorker: cannot start because no master key is currently loaded."
2020-03-09 19:39:41: "Scheduling sync operation..."
2020-03-09 19:39:41: "Scheduling sync operation..."
2020-03-09 19:39:41: "Scheduling sync operation..."
2020-03-09 19:39:41: "Scheduling sync operation..."
2020-03-09 19:39:44: "RevisionService::maintenance: Starting..."
2020-03-09 19:39:44: "RevisionService::maintenance: Service is enabled"
2020-03-09 19:39:44: "RevisionService::collectRevisions: Created revisions for 0 notes"
2020-03-09 19:39:44: "RevisionService::maintenance: Done in 292ms"
2020-03-09 19:39:49: "SearchEngine: Updating FTS table..."
2020-03-09 19:40:10: "ResourceService::indexNoteResources: Start"
2020-03-09 19:40:10: "ResourceService::indexNoteResources: Completed"
2020-03-09 19:40:10: "ResourceService::deleteOrphanResources:", "[]"
2020-03-09 19:40:11: "Preparing scheduled sync"
2020-03-09 19:40:11: "Saving updated Dropbox auth."
2020-03-09 19:40:11: "Synchroniser is missing credentials - manual sync required to authenticate."
2020-03-09 19:44:39: "Running background sync on timer..."
2020-03-09 19:44:39: "Scheduling sync operation..."
2020-03-09 19:44:39: "Preparing scheduled sync"
2020-03-09 19:44:39: "Synchroniser is missing credentials - manual sync required to authenticate."
2020-03-09 19:49:39: "Running background sync on timer..."
2020-03-09 19:49:39: "Scheduling sync operation..."
2020-03-09 19:49:39: "Preparing scheduled sync"
2020-03-09 19:49:39: "Synchroniser is missing credentials - manual sync required to authenticate."
2020-03-09 19:49:40: "RevisionService::maintenance: Starting..."
2020-03-09 19:49:40: "RevisionService::maintenance: Service is enabled"
2020-03-09 19:49:40: "RevisionService::collectRevisions: Created revisions for 0 notes"
2020-03-09 19:49:40: "RevisionService::maintenance: Done in 104ms"
2020-03-09 19:54:39: "Running background sync on timer..."
2020-03-09 19:54:39: "Scheduling sync operation..."
2020-03-09 19:54:39: "Preparing scheduled sync"
2020-03-09 19:54:39: "Synchroniser is missing credentials - manual sync required to authenticate."
2020-03-09 19:58:56: "Could not setup sync target:", "Error: Unsupported WebDAV URL format: http://localhost:8080/remote.php/dav/files/docker/Joplin
Error: Unsupported WebDAV URL format: http://localhost:8080/remote.php/dav/files/docker/Joplin
    at Function.baseUrlFromNextcloudWebDavUrl (/usr/share/joplin/resources/app/lib/JoplinServerApi.js:60:19)
    at Object.baseUrl (/usr/share/joplin/resources/app/lib/SyncTargetNextcloud.js:59:35)
    at JoplinServerApi.baseUrl (/usr/share/joplin/resources/app/lib/JoplinServerApi.js:53:43)
    at JoplinServerApi.<anonymous> (/usr/share/joplin/resources/app/lib/JoplinServerApi.js:117:33)
    at Generator.next (<anonymous>)
    at /usr/share/joplin/resources/app/lib/JoplinServerApi.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/share/joplin/resources/app/lib/JoplinServerApi.js:4:12)
    at JoplinServerApi.exec (/usr/share/joplin/resources/app/lib/JoplinServerApi.js:99:16)
    at JoplinServerApi.<anonymous> (/usr/share/joplin/resources/app/lib/JoplinServerApi.js:75:25)"
2020-03-09 19:59:26: "Scheduling sync operation..."
2020-03-09 19:59:26: "Preparing scheduled sync"
2020-03-09 19:59:26: "Starting scheduled sync"
2020-03-09 19:59:39: "Running background sync on timer..."
2020-03-09 19:59:39: "Scheduling sync operation..."
2020-03-09 19:59:39: "Preparing scheduled sync"
2020-03-09 19:59:39: "Starting scheduled sync"
2020-03-09 19:59:39: "Synchronisation is already in progress. State: in_progress"
2020-03-09 19:59:40: "RevisionService::maintenance: Starting..."
2020-03-09 19:59:40: "RevisionService::maintenance: Service is enabled"
2020-03-09 19:59:40: "RevisionService::collectRevisions: Created revisions for 0 notes"
2020-03-09 19:59:40: "RevisionService::maintenance: Done in 102ms"
```

**Comment by laurent22** [comment]
This is not a bug, please use the forum for support.
