### ISSUE TITLE
Tests fail for master

### ISSUE THREAD

**Issue by anihm136** [laurent22/joplin#2766]
Joplin version: 1.0.194
Platform: Linux
OS specifics: Ubuntu 19.10

## Steps to reproduce

1. Clone the Joplin repository
2. Run `npm install`, then `npm run build`
3. Change directory to `CliClient`
4. Run `npm run test`

## Describe what you expected to happen
All tests should pass. I've been having issues passing tests on my fork all morning, so I decided to try it on a fresh clone. 3 of the tests fail:
```
Failures:
1) services_Revision should not delete old revisions if one of them is still encrypted (3)
  Message:
    Expected 0 to be 1.
  Stack:
    Error: Expected 0 to be 1.
        at <Jasmine>
        at /home/anirudh/Projects/joplin/CliClient/tests-build/services_Revision.js:371:41
        at <Jasmine>
        at processTicksAndRejections (internal/process/task_queues.js:97:5)

2) HtmlToHtml should convert from Html to Html
  Message:
    Unhandled promise rejection: Error: Accessing database before it has been initialised
  Stack:
    Error: Accessing database before it has been initialised
        at Function.db (/home/anirudh/Projects/joplin/CliClient/tests-build/lib/BaseModel.js:546:24)
        at Function.add (/home/anirudh/Projects/joplin/CliClient/tests-build/lib/models/ItemChange.js:24:15)
        at <Jasmine>
        at processTicksAndRejections (internal/process/task_queues.js:97:5)

Suite error: HtmlToHtml
  Message:
    Unhandled promise rejection: Error: Accessing database before it has been initialised
  Stack:
    Error: Accessing database before it has been initialised
        at Function.db (/home/anirudh/Projects/joplin/CliClient/tests-build/lib/BaseModel.js:546:24)
        at Function.add (/home/anirudh/Projects/joplin/CliClient/tests-build/lib/models/ItemChange.js:24:15)
        at <Jasmine>
        at processTicksAndRejections (internal/process/task_queues.js:97:5)

262 specs, 3 failures
Finished in 559.064 seconds
Randomized with seed 81397 (jasmine --random=true --seed=81397)
```

**Comment by mic704b** [comment]
Please update to latest master and try again.

**Comment by anihm136** [comment]
Fixed by latest commit. Thanks!
