### ISSUE TITLE
reminder with dash as first character in note body sent with notify-send fails

### ISSUE THREAD

**Issue by jronallo** [laurent22/joplin#2818]
If a to-do note includes a dash as the first character then notify-send fails to send the scheduled notification. This can be the case where the first line of the note is the first line of a simple list or list of checkboxes. This can be simplified where any to-do which begins with the very first character in the note body being a dash fails to have the notification send when using notify-send. The dash means that the note body is treated as a parameter for notify-send.

## Environment

Joplin version: 1.0.193
Platform: Linux
OS specifics: Ubuntu 19.10

## Steps to reproduce

1. Create a new to-do note with a "-" as the first character.
2. Schedule a reminder for a minute out.
3. Wait...
4. Look in log for error message.

## Describe what you expected to happen

Reminders without a dash as the first character of the note body show a notification.

Expectation is that a notification where the first character is a dash would have been sent. It may be that any leading dash needs to be escaped. 

## Logfile

```
2020-03-20 09:00:56: "Scheduling notification for note 06a74f188fa24594b869efa8eda80e8a", "{"id":17,"date":"2020-03-20T13:01:00.325Z","title":"just dash as first character","body":"-\n\nmore text"}"

2020-03-20 09:01:00: "AlarmServiceDriverNode::scheduleNotification: node-notifier response:", "Error: Command failed: notify-send "just dash as first character" "-\n\nmore text" --icon "/tmp/.mount_Joplinu3xj3u/resources/build/icons/512x512.png"
Unknown option -\n\nmore text

Code: 1
Error: Command failed: notify-send "just dash as first character" "-\n\nmore text" --icon "/tmp/.mount_Joplinu3xj3u/resources/build/icons/512x512.png"
Unknown option -\n\nmore text

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)", "undefined"
```

**Comment by laurent22** [comment]
https://github.com/mikaelbr/node-notifier/issues/319

**Comment by p2635** [comment]
I don't know if it's related but I just tried reminders on a todo note for the first time (not the note body) and it doesn't work. Environment is Kubuntu 20.10 and Joplin 1.3.11
