### ISSUE TITLE
Cannot find module sqlite3

### ISSUE THREAD

**Issue by niczem** [laurent22/joplin#29]
When I am trying to run joplin after installing it on ubuntu the following error appers:

`
$ joplin
module.js:515
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/joplin/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
`

Sysinfo

`
$ npm -v

5.4.2
$ node -v

v8.8.1
$ lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
`

**Comment by laurent22** [comment]
I think it might be a permission issue. Could you try to move your default directory under home as described there, and then try to install it again? https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npms-default-directory-to-another-directory

**Comment by laurent22** [comment]
Please see here for more info about the terminal app installation: https://github.com/laurent22/joplin/issues/17
