### ISSUE TITLE
Crash in new Markdown editor

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#2939]
When adding some text at the beginning of an empty note:

```plaintext
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: FATAL EXCEPTION: main
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: Process: net.cozic.joplin, PID: 12963
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: java.lang.IndexOutOfBoundsException: setSpan (4 ... 4) ends beyond length 3
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1325)
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:676)
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at android.text.Selection.setSelection(Selection.java:94)
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at android.text.Selection.setSelection(Selection.java:78)
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at android.widget.TextView.semSetSelection(TextView.java:17146)
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at android.widget.EditText.setSelection(EditText.java:148)
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at com.facebook.react.views.textinput.ReactEditText.setSelection(ReactEditText.java:285)
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at com.facebook.react.views.textinput.ReactTextInputManager.updateExtraData(ReactTextInputManager.java:215)
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at com.facebook.react.views.textinput.ReactTextInputManager.updateExtraData(ReactTextInputManager.java:59)
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.updateViewExtraData(NativeViewHierarchyManager.java:157)
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$UpdateViewExtraData.execute(UIViewOperationQueue.java:236)
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:779)
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:888)
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue.access$2200(UIViewOperationQueue.java:42)
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:948)
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:28)
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:174)
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:994)
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:794)
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:725)
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7811)
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
03-30 00:59:41.508 10311 12963 12963 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

**Comment by coderrsid** [comment]
I guess the platform we're talking about is Android here, right?

**Comment by roman-r-m** [comment]
For me it does not happen when simply adding a text but it does happen when I type a word and then delete it (I'm using SwiftKey and can delete the last word by swiping right).

Seems related: https://github.com/facebook/react-native/issues/25265
[Apparently](https://github.com/imnapo/react-native-cn-richtext-editor/issues/81#issuecomment-603211656) it's fixed in RN 0.62

**Comment by kowalskidev** [comment]
To discuss this issue I've created a topic on discourse: https://discourse.joplinapp.org/t/android-joplin-keeps-stopping-while-using-editor-mode/7905

**Comment by laurent22** [comment]
@devonzuegel, just to let you know this is why I haven't made an announcement for the new text editor yet, but it's available on Android and iOS. I'll wait till this bug is fixed, hopefully it's just a matter of upgrading React Native.

**Comment by bedwardly-down** [comment]
![EED14E68-834D-4A02-8188-CDA75E867270](https://user-images.githubusercontent.com/59133880/79528821-a304ae80-8030-11ea-85ac-1cffcbba2d99.jpeg)


Here’s my log from it crashing on my Android phone but it happens while editing a note with multiple images and for some reason, a third of the screen is just a black bar that can be typed into.

**Comment by kowalskidev** [comment]
> It also doesn’t seem to happen at all on my iPhone 11. So, is this just an Android only bug?

We are not sure yet! But now as you are saying it's not happening in your iPhone looks like it's working fine in iOS.  As Laurent said this issue is related react-native hopefully upgrading react-native version would solve this issue.

**Comment by roman-r-m** [comment]
I've just tried building with RN 0.62 where this bug is supposed to be fixed.
I can confirm that Joplin does not crash any more, however when I'm typing the cursor jumps all over the place so the editor is still unusable at least for me.

**Comment by laurent22** [comment]
>  I can confirm that Joplin does not crash any more, however when I'm typing the cursor jumps all over the place so the editor is still unusable at least for me.

Hmm, looks like they still haven't fixed the cursor issues then. It's also the reason why the undo/redo feature on mobile doesn't restore the cursor because I found it was completely unreliable (the component would say the position is X when in fact it's Y).

**Comment by roman-r-m** [comment]
Not sure if the undo cursor issue is related - I've seen it with the old editor.
