### ISSUE TITLE
joplin Start the error

### ISSUE THREAD

**Issue by pptfz** [laurent22/joplin#2950]
When I started joplin, I reported the following error. I don't know how to solve this one

internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module '/usr/local/Cellar/joplin/1.0.161_1/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v72-darwin-x64/node_sqlite3.node'
Require stack:
- /usr/local/Cellar/joplin/1.0.161_1/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/sqlite3.js
- /usr/local/Cellar/joplin/1.0.161_1/libexec/lib/node_modules/joplin/lib/database-driver-node.js
- /usr/local/Cellar/joplin/1.0.161_1/libexec/lib/node_modules/joplin/lib/BaseApplication.js
- /usr/local/Cellar/joplin/1.0.161_1/libexec/lib/node_modules/joplin/app.js
- /usr/local/Cellar/joplin/1.0.161_1/libexec/lib/node_modules/joplin/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/local/Cellar/joplin/1.0.161_1/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/Cellar/joplin/1.0.161_1/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/sqlite3.js',
    '/usr/local/Cellar/joplin/1.0.161_1/libexec/lib/node_modules/joplin/lib/database-driver-node.js',
    '/usr/local/Cellar/joplin/1.0.161_1/libexec/lib/node_modules/joplin/lib/BaseApplication.js',
    '/usr/local/Cellar/joplin/1.0.161_1/libexec/lib/node_modules/joplin/app.js',
    '/usr/local/Cellar/joplin/1.0.161_1/libexec/lib/node_modules/joplin/main.js'
  ]
}

**Comment by tessus** [comment]
You apparently use `brew`. We do manage the brew packages. Please open an issue with them.

The only supported Linux version is the AppImage (and the cli via npm). Everything else is maintained by somebody else.
