### ISSUE TITLE
Error: The maximum request length supported is 4MB.

### ISSUE THREAD

**Issue by xindubawukong** [laurent22/joplin#2998]
## Environment

Joplin version: 
```
Joplin 1.0.197 (prod, darwin)

Client ID: 32ec62d4862043dba204fa6bd310bd96
Sync Version: 1
Profile Version: 28

Revision: 719afba (master)
```
Platform: MacOS desktop app
OS specifics: MacOS 10.14.6

## Steps to reproduce

1. Open Joplin
2. Select `Ondrive` as Synchronisation target
3. Click `Synchronise`
4. The left-bottom shows:
![image](https://user-images.githubusercontent.com/22728970/78654406-0a1ab880-78f7-11ea-93a3-f64337135832.png)

## Describe what you expected to happen

I expect no error.

## Logfile

```
2020-04-07 17:33:09: "Error: The maximum request length supported is 4MB.
Code: BadRequest
Header: {"_headers":{"cache-control":["private"],"content-type":["application/json; charset=utf-8"],"strict-transport-security":["max-age=31536000"],"date":["Tue, 07 Apr 2020 09:33:10 GMT"],"connection":["close"],"content-length":["240"]}}
Request: PUT https://graph.microsoft.com/v1.0/drive/root:/%E5%BA%94%E7%94%A8/Joplin/.resource/2bf3aaf6c194411da5d1a4b7c09d841b:/content null null {"path":"/Users/xdbwk/.config/joplin-desktop/resources/2bf3aaf6c194411da5d1a4b7c09d841b.zip","source":"file","headers":{"Authorization":"bearer EwB4A8l6BAAUO9chh8cJscQLmU+LSWpbnr0vmwwAAbT8B8MQ394Ayrk2kPQ2ryISxOSEpRT4DB5ImUBYzaZLtVAhn5ymO/JHDPteBt4gkLvsTdMwPspnuJNZtu3OildCazTStxTbw5V+nC1EDDw9nSnvOqNfORNxSkfGFP7mwFIY779hNJ/6lSOSITd8z3l/revIUCMnBTQW6Y4EIhWp32fO+LMmbx4nlRUFuAGHelyWQWM4N/1J8nsm4iF6y2JuWVBvH22P5NZTcMi7gZ4ViaLayYe6QM2syrl+fg+BsHqCoEkSxN8jCUkBL3cA9BwmjoWlvM59xVaWLoyhVGkgzM0M6BGPD6HU4FEyKh04y5Viq8e0ztD7Ty2+h+WP6jsDZgAACDlI4lu6XVDySAIU+yRj92CE1QpZPDWoyFKx775KSpvCFYrGGb5s2iVb5uf9WsBoMBHmh9uT9BGyrIVnmKXNP1MkOz1dOAV+Nu9MY+vZSlT3q2MTvo+qkL4Tnb1yr8owYm/VELsleO4mDhwml0lk62fLFEQkoB7JCSpHJC9gxKV2Q/+RSu5MV/PSDbgYJFoJCT420KGRhAayatZ63bQFfVn3L9+GtyAIzSO1q/h55R7o7MxA64N8HUbpDRYf7/mKh666pktn1OfK1HugMtEizc6SQt258pSnqCn4l/4RYXmdRQzyJ88k1CC1MuBqpBBRGh3SfpkPGo1+Jrkz2CkRj392PfeCFlW5VTx
Error: The maximum request length supported is 4MB.
    at OneDriveApi.oneDriveErrorResponseToError (/Applications/Joplin.app/Contents/Resources/app.asar/lib/onedrive-api.js:124:19)
    at OneDriveApi.exec (/Applications/Joplin.app/Contents/Resources/app.asar/lib/onedrive-api.js:195:24)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async FileApiDriverOneDrive.put (/Applications/Joplin.app/Contents/Resources/app.asar/lib/file-api-driver-onedrive.js:134:16)
    at async tryAndRepeat (/Applications/Joplin.app/Contents/Resources/app.asar/lib/file-api.js:37:19)
    at async Synchronizer.start (/Applications/Joplin.app/Contents/Resources/app.asar/lib/synchronizer.js:441:10)
    at async timeoutCallback (/Applications/Joplin.app/Contents/Resources/app.asar/lib/registry.js:131:26)"
2020-04-07 17:33:09: "Setting up recurrent sync with interval 300"
2020-04-07 17:33:09: "Updating all notifications..."
2020-04-07 17:33:09: "Garbage collecting alarms..."
2020-04-07 17:33:10: "DecryptionWorker: cannot start because no master key is currently loaded."
2020-04-07 17:33:11: "ResourceService::indexNoteResources: Start"
2020-04-07 17:33:11: "ResourceService::indexNoteResources: Completed"
2020-04-07 17:33:11: "ResourceService::deleteOrphanResources:", "[]"
2020-04-07 17:33:17: "Scheduling sync operation...", "0"
2020-04-07 17:33:17: "Preparing scheduled sync"
2020-04-07 17:33:17: "Starting scheduled sync"
2020-04-07 17:33:17: "Sync: starting: Starting synchronisation to target 3... [1586251997819]"
2020-04-07 17:33:17: "mkdir /drive/root:/%E5%BA%94%E7%94%A8/Joplin/.sync"
2020-04-07 17:33:18: "mkdir /drive/root:/%E5%BA%94%E7%94%A8/Joplin/.lock"
2020-04-07 17:33:19: "mkdir /drive/root:/%E5%BA%94%E7%94%A8/Joplin/.resource"
2020-04-07 17:33:20: "list /drive/root:/%E5%BA%94%E7%94%A8/Joplin"
2020-04-07 17:33:22: "get /drive/root:/%E5%BA%94%E7%94%A8/Joplin/.sync/version.txt"
2020-04-07 17:33:23: "put /drive/root:/%E5%BA%94%E7%94%A8/Joplin/.sync/version.txt", "null"
2020-04-07 17:33:25: "stat /drive/root:/%E5%BA%94%E7%94%A8/Joplin/2bf3aaf6c194411da5d1a4b7c09d841b.md"
2020-04-07 17:33:26: "Sync: createRemote: remote does not exist, and local is new and has never been synced: Resource: (Local 2bf3aaf6c194411da5d1a4b7c09d841b)"
2020-04-07 17:33:27: "Uploading a large resource (resourceId: 2bf3aaf6c194411da5d1a4b7c09d841b, size:12382232 bytes) which may tie up the sync process."
2020-04-07 17:33:27: "put /drive/root:/%E5%BA%94%E7%94%A8/Joplin/.resource/2bf3aaf6c194411da5d1a4b7c09d841b", "{"path":"/Users/xdbwk/.config/joplin-desktop/resources/2bf3aaf6c194411da5d1a4b7c09d841b.zip","source":"file"}"
2020-04-07 17:33:29: "Error: The maximum request length supported is 4MB.
Code: BadRequest
Header: {"_headers":{"cache-control":["private"],"content-type":["application/json; charset=utf-8"],"strict-transport-security":["max-age=31536000"],"date":["Tue, 07 Apr 2020 09:33:30 GMT"],"connection":["close"],"content-length":["240"]}}
Request: PUT https://graph.microsoft.com/v1.0/drive/root:/%E5%BA%94%E7%94%A8/Joplin/.resource/2bf3aaf6c194411da5d1a4b7c09d841b:/content null null {"path":"/Users/xdbwk/.config/joplin-desktop/resources/2bf3aaf6c194411da5d1a4b7c09d841b.zip","source":"file","headers":{"Authorization":"bearer EwB4A8l6BAAUO9chh8cJscQLmU+LSWpbnr0vmwwAAbT8B8MQ394Ayrk2kPQ2ryISxOSEpRT4DB5ImUBYzaZLtVAhn5ymO/JHDPteBt4gkLvsTdMwPspnuJNZtu3OildCazTStxTbw5V+nC1EDDw9nSnvOqNfORNxSkfGFP7mwFIY779hNJ/6lSOSITd8z3l/revIUCMnBTQW6Y4EIhWp32fO+LMmbx4nlRUFuAGHelyWQWM4N/1J8nsm4iF6y2JuWVBvH22P5NZTcMi7gZ4ViaLayYe6QM2syrl+fg+BsHqCoEkSxN8jCUkBL3cA9BwmjoWlvM59xVaWLoyhVGkgzM0M6BGPD6HU4FEyKh04y5Viq8e0ztD7Ty2+h+WP6jsDZgAACDlI4lu6XVDySAIU+yRj92CE1QpZPDWoyFKx775KSpvCFYrGGb5s2iVb5uf9WsBoMBHmh9uT9BGyrIVnmKXNP1MkOz1dOAV+Nu9MY+vZSlT3q2MTvo+qkL4Tnb1yr8owYm/VELsleO4mDhwml0lk62fLFEQkoB7JCSpHJC9gxKV2Q/+RSu5MV/PSDbgYJFoJCT420KGRhAayatZ63bQFfVn3L9+GtyAIzSO1q/h55R7o7MxA64N8HUbpDRYf7/mKh666pktn1OfK1HugMtEizc6SQt258pSnqCn4l/4RYXmdRQzyJ88k1CC1MuBqpBBRGh3SfpkPGo1+Jrkz2CkRj392PfeCFlW5VTx
Error: The maximum request length supported is 4MB.
    at OneDriveApi.oneDriveErrorResponseToError (/Applications/Joplin.app/Contents/Resources/app.asar/lib/onedrive-api.js:124:19)
    at OneDriveApi.exec (/Applications/Joplin.app/Contents/Resources/app.asar/lib/onedrive-api.js:195:24)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async FileApiDriverOneDrive.put (/Applications/Joplin.app/Contents/Resources/app.asar/lib/file-api-driver-onedrive.js:134:16)
    at async tryAndRepeat (/Applications/Joplin.app/Contents/Resources/app.asar/lib/file-api.js:37:19)
    at async Synchronizer.start (/Applications/Joplin.app/Contents/Resources/app.asar/lib/synchronizer.js:441:10)
    at async timeoutCallback (/Applications/Joplin.app/Contents/Resources/app.asar/lib/registry.js:131:26)"
2020-04-07 17:33:29: "Sync: finished: Synchronisation finished [1586251997819]"
2020-04-07 17:33:29: "Operations completed: "
2020-04-07 17:33:29: "createRemote: 1"
2020-04-07 17:33:29: "Total folders: 12"
2020-04-07 17:33:29: "Total notes: 194"
2020-04-07 17:33:29: "Total resources: 974"
2020-04-07 17:33:29: "There was some errors:"
2020-04-07 17:33:29: "Error: The maximum request length supported is 4MB.
Code: BadRequest
Header: {"_headers":{"cache-control":["private"],"content-type":["application/json; charset=utf-8"],"strict-transport-security":["max-age=31536000"],"date":["Tue, 07 Apr 2020 09:33:30 GMT"],"connection":["close"],"content-length":["240"]}}
Request: PUT https://graph.microsoft.com/v1.0/drive/root:/%E5%BA%94%E7%94%A8/Joplin/.resource/2bf3aaf6c194411da5d1a4b7c09d841b:/content null null {"path":"/Users/xdbwk/.config/joplin-desktop/resources/2bf3aaf6c194411da5d1a4b7c09d841b.zip","source":"file","headers":{"Authorization":"bearer EwB4A8l6BAAUO9chh8cJscQLmU+LSWpbnr0vmwwAAbT8B8MQ394Ayrk2kPQ2ryISxOSEpRT4DB5ImUBYzaZLtVAhn5ymO/JHDPteBt4gkLvsTdMwPspnuJNZtu3OildCazTStxTbw5V+nC1EDDw9nSnvOqNfORNxSkfGFP7mwFIY779hNJ/6lSOSITd8z3l/revIUCMnBTQW6Y4EIhWp32fO+LMmbx4nlRUFuAGHelyWQWM4N/1J8nsm4iF6y2JuWVBvH22P5NZTcMi7gZ4ViaLayYe6QM2syrl+fg+BsHqCoEkSxN8jCUkBL3cA9BwmjoWlvM59xVaWLoyhVGkgzM0M6BGPD6HU4FEyKh04y5Viq8e0ztD7Ty2+h+WP6jsDZgAACDlI4lu6XVDySAIU+yRj92CE1QpZPDWoyFKx775KSpvCFYrGGb5s2iVb5uf9WsBoMBHmh9uT9BGyrIVnmKXNP1MkOz1dOAV+Nu9MY+vZSlT3q2MTvo+qkL4Tnb1yr8owYm/VELsleO4mDhwml0lk62fLFEQkoB7JCSpHJC9gxKV2Q/+RSu5MV/PSDbgYJFoJCT420KGRhAayatZ63bQFfVn3L9+GtyAIzSO1q/h55R7o7MxA64N8HUbpDRYf7/mKh666pktn1OfK1HugMtEizc6SQt258pSnqCn4l/4RYXmdRQzyJ88k1CC1MuBqpBBRGh3SfpkPGo1+Jrkz2CkRj392PfeCFlW5VTx
Error: The maximum request length supported is 4MB.
    at OneDriveApi.oneDriveErrorResponseToError (/Applications/Joplin.app/Contents/Resources/app.asar/lib/onedrive-api.js:124:19)
    at OneDriveApi.exec (/Applications/Joplin.app/Contents/Resources/app.asar/lib/onedrive-api.js:195:24)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async FileApiDriverOneDrive.put (/Applications/Joplin.app/Contents/Resources/app.asar/lib/file-api-driver-onedrive.js:134:16)
    at async tryAndRepeat (/Applications/Joplin.app/Contents/Resources/app.asar/lib/file-api.js:37:19)
    at async Synchronizer.start (/Applications/Joplin.app/Contents/Resources/app.asar/lib/synchronizer.js:441:10)
    at async timeoutCallback (/Applications/Joplin.app/Contents/Resources/app.asar/lib/registry.js:131:26)"
2020-04-07 17:33:29: "Setting up recurrent sync with interval 300"
```

In the console there're two warnings, but I don't think it matters:
![image](https://user-images.githubusercontent.com/22728970/78653881-59141e00-78f6-11ea-8446-ae64a1d108e1.png)

**Comment by laurent22** [comment]
> The maximum request length supported is 4MB.

Is there something unclear about this?

**Comment by xindubawukong** [comment]
> > The maximum request length supported is 4MB.
> 
> Is there something unclear about this?

I see. But it took much time to find which note includes that large file. Maybe the error message should show more infomation about it.

**Comment by Nullmaruzero** [comment]
Same problem here since today. I guess OneDrive is a bad choice for many nested notebooks (up to 3 levels). I have 15 notes in total, including 6 Welcome to Joplin ones. Only one with some pictures images but I have predefined my whole notepad layout into 21 notepads (including nested) and it blew up.
Removing all the attachments helped. Attachments are not being deleted with the note itself.

Despite adding just a 200 characters long note (plain txt), I suddenly hit the 4MB limit, with everything else being already in sync. Only after removing attachments from the notes via Note attachments tool (the notes were still there, I did not delete them) could I synchronize again.

That would mean that there is a cap of how many attachments (and perhaps notes?) you can possibly have if the synch engine bulks everything into one huge request...
