### ISSUE TITLE
Mobile: resource size check can be bypassed potentially causing the app to crash

### ISSUE THREAD

**Issue by roman-r-m** [laurent22/joplin#3107]
A few users reported having the app crashing due to large attachments (https://github.com/laurent22/joplin/issues/2424 & https://github.com/laurent22/joplin/issues/2943) or just being able to download attachments larger than 10mb (https://discourse.joplinapp.org/t/whats-the-file-size-limit-for-an-attachment-in-android-2146/4545/8?u=roman_r_m)

It seems there's a bug in synchronizer where you can bypass the max resource size check. I managed to reproduce it and the related OOM crash.

The steps are:
- have Dropbox sync and encryption set up (tbf I did not check whether any of these is required to reproduce - I suspect it's only Dropbox that is relevant)
- on desktop create a note, attach a large file and sync
- sync on mobile - as expected the attachment won't be downloaded
- back on desktop move the note to another notebook and sync again
- sync again on mobile - depending on the attachment size the app might download and decrypt it successfully or crash with OOM

Edit:
I've only tested this on Android so it may or may not affect iOS.

**Comment by roman-r-m** [comment]
And the stacktrace I'm seeing is the same as in one of the issues I mentioned:
```
04-21 08:18:42.709 20256 20688 W et.cozic.jopli: Throwing OutOfMemoryError with VmSize 43116316 kB "Failed to allocate a 124178936 byte allocation with 25165824 free bytes and 65MB until OOM, max allowed footprint 493843928, growth limit 536870912"
04-21 08:18:42.710 20256 20265 W System  : A resource failed to call close. 
04-21 08:18:42.733 20256 20688 E AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
04-21 08:18:42.733 20256 20688 E AndroidRuntime: Process: net.cozic.joplin, PID: 20256
04-21 08:18:42.733 20256 20688 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 124178936 byte allocation with 25165824 free bytes and 65MB until OOM, max allowed footprint 493843928, growth limit 536870912
04-21 08:18:42.733 20256 20688 E AndroidRuntime: 	at java.lang.StringFactory.newStringFromChars(StringFactory.java:267)
04-21 08:18:42.733 20256 20688 E AndroidRuntime: 	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:252)
04-21 08:18:42.733 20256 20688 E AndroidRuntime: 	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:65)
04-21 08:18:42.733 20256 20688 E AndroidRuntime: 	at android.util.Base64.encodeToString(Base64.java:456)
04-21 08:18:42.733 20256 20688 E AndroidRuntime: 	at com.RNFetchBlob.RNFetchBlobFS.readFile(RNFetchBlobFS.java:215)
04-21 08:18:42.733 20256 20688 E AndroidRuntime: 	at com.RNFetchBlob.RNFetchBlob$6.run(RNFetchBlob.java:227)
04-21 08:18:42.733 20256 20688 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
04-21 08:18:42.733 20256 20688 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
04-21 08:18:42.733 20256 20688 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-21 08:18:42.733 20256 20688 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:784)
```

**Comment by roman-r-m** [comment]
@laurent22 I raised it mostly for visibility. Instead of trying to fix this I'm going to try finding the memory leak - decrypting a 60mb file should not cause OutOfMemoryError on a relatively modern smartphone.

**Comment by roman-r-m** [comment]
While the issue is not fixed it should not break synchronization anymore.
