### ISSUE TITLE
After most recent update, CLI app looking for wrong version of node_sqlite3

### ISSUE THREAD

**Issue by Datamance** [laurent22/joplin#3139]
Just updated joplin with homebrew yesterday - seeing this today when trying to start up the joplin CLI gives me this:

```
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module '/usr/local/Cellar/joplin/1.0.163_1/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v79-darwin-x64/node_sqlite3.node'
Require stack:
- /usr/local/Cellar/joplin/1.0.163_1/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/sqlite3.js
- /usr/local/Cellar/joplin/1.0.163_1/libexec/lib/node_modules/joplin/lib/database-driver-node.js
- /usr/local/Cellar/joplin/1.0.163_1/libexec/lib/node_modules/joplin/lib/BaseApplication.js
- /usr/local/Cellar/joplin/1.0.163_1/libexec/lib/node_modules/joplin/app.js
- /usr/local/Cellar/joplin/1.0.163_1/libexec/lib/node_modules/joplin/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/Cellar/joplin/1.0.163_1/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/Cellar/joplin/1.0.163_1/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/sqlite3.js',
    '/usr/local/Cellar/joplin/1.0.163_1/libexec/lib/node_modules/joplin/lib/database-driver-node.js',
    '/usr/local/Cellar/joplin/1.0.163_1/libexec/lib/node_modules/joplin/lib/BaseApplication.js',
    '/usr/local/Cellar/joplin/1.0.163_1/libexec/lib/node_modules/joplin/app.js',
    '/usr/local/Cellar/joplin/1.0.163_1/libexec/lib/node_modules/joplin/main.js'
  ]
}
```

Correct, there's no module there at `.../binding/node-v79-darwin-x64/...` - but there is one at `.../binding/node-v83-darwin-x64/...`

Using [asdf](https://github.com/asdf-vm/asdf) for version management, not that it matters.

## Environment
Joplin version: 
```
❯ ls /usr/local/Cellar/joplin/
1.0.163_1
```
Platform: 
```
❯ uname -a
Darwin myhost.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
```
OS specifics: 
Mac OS Catalina 10.15.4

## Steps to reproduce

1. Install most recent version of joplin 
2. type `joplin`

## Describe what you expected to happen
It works.

**Comment by Datamance** [comment]
Nevermind - it looks like this is a duplicate of https://github.com/laurent22/joplin/issues/886, which in turn refers to https://github.com/mapbox/node-sqlite3/issues/1064. 

I think when I ran `brew update && brew upgrade` my brew version of node got updated to 14.0.0, whilst my asdf-managed version was still at 13.12.0.

Once I upgraded my asdf-managed version, it was all good to go. I also uninstalled and reinstalled `joplin` but not entirely sure I needed to do that.
