### ISSUE TITLE
Android Index out of Bounds crash when editing

### ISSUE THREAD

**Issue by hawalter** [laurent22/joplin#3199]
## Environment

Joplin version: 1.0.329
Platform: Pixel 3XL Android 10
OS specifics: QQ2A.200501.001.B2

## Steps to reproduce

Case 1:
1. Start new note and type a few characters.
2. Touch so cursor moves into the middle of the typed chars.
3. Occasionly, the cursor will spontaneously move before the next to last char.
4. Touch to move cursor after the last char and the app crashes.
Crashed 3 times in a row. Then no spontaneous movement.

Case 2:
1. Start typing in note body
2. Press on text so cursor appear.
3. Long press so selection handles appears.
4. Long press so option menu appears and select Cut. App crashes.
Crashed once and then worked correctly.

## Describe what you expected to happen
Enter new chars at end of line without crashing.

## Logfile
Case 1:
java.lang.IndexOutOfBoundsException: setSpan (12 ... 12) ends beyond length 11
        at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1325)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:676)
        at android.text.Selection.setSelection(Selection.java:94)
        at android.text.Selection.setSelection(Selection.java:78)
        at android.widget.EditText.setSelection(EditText.java:129)
        at com.facebook.react.views.textinput.ReactEditText.setSelection(ReactEditText.java:285)
        at com.facebook.react.views.textinput.ReactTextInputManager.updateExtraData(ReactTextInputManager.java:215)
        at com.facebook.react.views.textinput.ReactTextInputManager.updateExtraData(ReactTextInputManager.java:59)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.updateViewExtraData(NativeViewHierarchyManager.java:157)
        at com.facebook.react.uimanager.UIViewOperationQueue$UpdateViewExtraData.execute(UIViewOperationQueue.java:236)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:779)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:888)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2200(UIViewOperationQueue.java:42)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:948)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:28)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:174)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:965)
        at android.view.Choreographer.doCallbacks(Choreographer.java:791)
        at android.view.Choreographer.doFrame(Choreographer.java:722)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

Case 2:
2020-05-11 09:26:08.036 25656-25656/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.cozic.joplin, PID: 25656
    java.lang.IndexOutOfBoundsException: setSpan (4 ... 4) ends beyond length 0
        at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1325)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:676)
        at android.text.Selection.setSelection(Selection.java:96)
        at android.text.Selection.setSelection(Selection.java:78)
        at android.widget.EditText.setSelection(EditText.java:129)
        at com.facebook.react.views.textinput.ReactEditText.setSelection(ReactEditText.java:285)
        at com.facebook.react.views.textinput.ReactTextInputManager.updateExtraData(ReactTextInputManager.java:215)
        at com.facebook.react.views.textinput.ReactTextInputManager.updateExtraData(ReactTextInputManager.java:59)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.updateViewExtraData(NativeViewHierarchyManager.java:157)
        at com.facebook.react.uimanager.UIViewOperationQueue$UpdateViewExtraData.execute(UIViewOperationQueue.java:236)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:779)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:888)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2200(UIViewOperationQueue.java:42)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:948)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:28)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:174)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:965)
        at android.view.Choreographer.doCallbacks(Choreographer.java:791)
        at android.view.Choreographer.doFrame(Choreographer.java:722)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by roman-r-m** [comment]
Duplicate of https://github.com/laurent22/joplin/issues/2939

**Comment by roman-r-m** [comment]
Not stale as far as I know

**Comment by tim-elmer** [comment]
Still an issue. Obnoxious bot.

**Comment by tim-elmer** [comment]
.

**Comment by tim-elmer** [comment]
Bot begone.

**Comment by tim-elmer** [comment]
Is there a PR fixing it? Obnoxious bot is obnoxious.
