### ISSUE TITLE
Sync with OneDrive fails

### ISSUE THREAD

**Issue by MoreDelay** [laurent22/joplin#3237]
I'm trying to sync my desktop app with a sync state via OneDrive, which worked once (and even now with the Android version) but somehow not anymore for the desktop app.

## Environment

Joplin version: 1.0.201
Platform: Windows/Desktop
OS specifics: 

## Steps to reproduce

1. Create new profile
2. Connect synchronization via OneDrive
3. Try to sync and get no updates

## Describe what you expected to happen
Hey, I just installed Joplin and I have trouble synchronizing via OneDrive. Apparently I could first upload a new note but now it keeps saying that it synchronized, while the changes are still missing that I can see within the OneDrive folder (when looking at all these md files with an editor). I even tried to delete the whole profile to re-establish the account information but the same error occurred again.

The logs mention an unhandled error on timeout. If that is an error by OneDrive I would like to at least get some feedback within the app. The app only prints "completed" which suggests it was successful, which it obviously wasn't.

## Logfile

~/.config/joplin-desktop/log.txt:
```
2020-05-20 12:56:49: "Profile directory: C:/Users/Dennis/.config/joplin-desktop"
2020-05-20 12:56:53: "First start: detected locale as en_GB"
2020-05-20 12:56:53: "Trying to load 0 master keys..."
2020-05-20 12:56:53: "Loaded master keys: 0"
2020-05-20 12:56:53: "ResourceFetcher: Auto-add resources: Mode: always"
2020-05-20 12:56:53: "ResourceFetcher: Auto-added resources: 0"
2020-05-20 12:56:53: "Running migration: 20"
2020-05-20 12:56:53: "Running migration: 27"
2020-05-20 12:56:53: "Trying to load 0 master keys..."
2020-05-20 12:56:53: "Loaded master keys: 0"
2020-05-20 12:56:53: "Scheduling sync operation...", "10000"
2020-05-20 12:56:53: "Trying to load 0 master keys..."
2020-05-20 12:56:53: "Loaded master keys: 0"
2020-05-20 12:56:53: "Scheduling sync operation...", "10000"
2020-05-20 12:56:53: "Trying to load 0 master keys..."
2020-05-20 12:56:53: "Loaded master keys: 0"
2020-05-20 12:56:53: "Scheduling sync operation...", "10000"
2020-05-20 12:56:53: "Scheduling sync operation...", "10000"
2020-05-20 12:56:53: "RevisionService::runInBackground: Starting background service with revision collection interval 600000"
2020-05-20 12:56:54: "Scheduling sync operation...", "30000"
2020-05-20 12:56:54: "Scheduling sync operation...", "30000"
2020-05-20 12:56:54: "DecryptionWorker: cannot start because no master key is currently loaded."
2020-05-20 12:56:54: "Scheduling sync operation...", "30000"
2020-05-20 12:56:54: "Scheduling sync operation...", "30000"
2020-05-20 12:56:54: "Scheduling sync operation...", "30000"
2020-05-20 12:56:55: "Scheduling sync operation...", "30000"
2020-05-20 12:56:57: "RevisionService::maintenance: Starting..."
2020-05-20 12:56:57: "RevisionService::maintenance: Service is enabled"
2020-05-20 12:56:57: "RevisionService::collectRevisions: Created revisions for 0 notes"
2020-05-20 12:56:57: "RevisionService::maintenance: Done in 235ms"
2020-05-20 12:57:02: "Scheduling sync operation...", "30000"
2020-05-20 12:57:03: "SearchEngine: Updating FTS table..."
2020-05-20 12:57:03: "Scheduling sync operation...", "30000"
2020-05-20 12:57:11: "Saving updated Dropbox auth."
2020-05-20 12:57:20: "Saving updated OneDrive auth."
2020-05-20 12:57:23: "ResourceService::indexNoteResources: Start"
2020-05-20 12:57:24: "ResourceService::indexNoteResources: Completed"
2020-05-20 12:57:24: "ResourceService::deleteOrphanResources:", "[]"
2020-05-20 12:57:33: "Preparing scheduled sync"
2020-05-20 12:57:33: "Synchroniser is missing credentials - manual sync required to authenticate."
2020-05-20 12:57:34: "Saving updated OneDrive auth."
2020-05-20 12:57:35: "Saving updated OneDrive auth."
2020-05-20 12:57:35: "Scheduling sync operation...", "0"
2020-05-20 12:57:35: "Preparing scheduled sync"
2020-05-20 12:57:35: "Starting scheduled sync"
2020-05-20 12:58:02: "Got unhandled error:", "ETIMEDOUT", "request to https://graph.microsoft.com/v1.0/drive/root:/Apps/Joplin/957f4c397b6f479a9c7130674be8039e.md?select=name%2Cfile%2Cfolder%2CfileSystemInfo%2CparentReference failed, reason: connect ETIMEDOUT 40.126.9.51:443", "FetchError: request to https://graph.microsoft.com/v1.0/drive/root:/Apps/Joplin/957f4c397b6f479a9c7130674be8039e.md?select=name%2Cfile%2Cfolder%2CfileSystemInfo%2CparentReference failed, reason: connect ETIMEDOUT 40.126.9.51:443
Code: ETIMEDOUT
FetchError: request to https://graph.microsoft.com/v1.0/drive/root:/Apps/Joplin/957f4c397b6f479a9c7130674be8039e.md?select=name%2Cfile%2Cfolder%2CfileSystemInfo%2CparentReference failed, reason: connect ETIMEDOUT 40.126.9.51:443
    at ClientRequest.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\node-fetch\index.js:133:11)
    at ClientRequest.emit (events.js:203:13)
    at TLSSocket.socketErrorListener (_http_client.js:399:9)
    at TLSSocket.emit (events.js:203:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)"
2020-05-20 12:58:02: "FetchError: request to https://graph.microsoft.com/v1.0/drive/root:/Apps/Joplin/957f4c397b6f479a9c7130674be8039e.md?select=name%2Cfile%2Cfolder%2CfileSystemInfo%2CparentReference failed, reason: connect ETIMEDOUT 40.126.9.51:443
Code: ETIMEDOUT
FetchError: request to https://graph.microsoft.com/v1.0/drive/root:/Apps/Joplin/957f4c397b6f479a9c7130674be8039e.md?select=name%2Cfile%2Cfolder%2CfileSystemInfo%2CparentReference failed, reason: connect ETIMEDOUT 40.126.9.51:443
    at ClientRequest.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\node-fetch\index.js:133:11)
    at ClientRequest.emit (events.js:203:13)
    at TLSSocket.socketErrorListener (_http_client.js:399:9)
    at TLSSocket.emit (events.js:203:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)"
2020-05-20 12:58:02: "Operations completed: "
2020-05-20 12:58:02: "createRemote: 7"
2020-05-20 12:58:02: "Total folders: 2"
2020-05-20 12:58:02: "Total notes: 6"
2020-05-20 12:58:02: "Total resources: 3"
2020-05-20 12:58:03: "DecryptionWorker: cannot start because no master key is currently loaded."
2020-05-20 13:03:02: "Running background sync on timer..."
2020-05-20 13:03:02: "Scheduling sync operation...", "0"
2020-05-20 13:03:02: "Preparing scheduled sync"
2020-05-20 13:03:02: "Starting scheduled sync"
2020-05-20 13:03:24: "Got unhandled error:", "ETIMEDOUT", "request to https://graph.microsoft.com/v1.0/drive/root:/Apps/Joplin/.resource?select=name%2Cfile%2Cfolder%2CfileSystemInfo%2CparentReference failed, reason: connect ETIMEDOUT 40.126.9.113:443", "FetchError: request to https://graph.microsoft.com/v1.0/drive/root:/Apps/Joplin/.resource?select=name%2Cfile%2Cfolder%2CfileSystemInfo%2CparentReference failed, reason: connect ETIMEDOUT 40.126.9.113:443
Code: ETIMEDOUT
FetchError: request to https://graph.microsoft.com/v1.0/drive/root:/Apps/Joplin/.resource?select=name%2Cfile%2Cfolder%2CfileSystemInfo%2CparentReference failed, reason: connect ETIMEDOUT 40.126.9.113:443
    at ClientRequest.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\node-fetch\index.js:133:11)
    at ClientRequest.emit (events.js:203:13)
    at TLSSocket.socketErrorListener (_http_client.js:399:9)
    at TLSSocket.emit (events.js:203:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)"
2020-05-20 13:03:24: "FetchError: request to https://graph.microsoft.com/v1.0/drive/root:/Apps/Joplin/.resource?select=name%2Cfile%2Cfolder%2CfileSystemInfo%2CparentReference failed, reason: connect ETIMEDOUT 40.126.9.113:443
Code: ETIMEDOUT
FetchError: request to https://graph.microsoft.com/v1.0/drive/root:/Apps/Joplin/.resource?select=name%2Cfile%2Cfolder%2CfileSystemInfo%2CparentReference failed, reason: connect ETIMEDOUT 40.126.9.113:443
    at ClientRequest.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\node-fetch\index.js:133:11)
    at ClientRequest.emit (events.js:203:13)
    at TLSSocket.socketErrorListener (_http_client.js:399:9)
    at TLSSocket.emit (events.js:203:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)"
2020-05-20 13:03:24: "Operations completed: "
2020-05-20 13:03:24: "Total folders: 2"
2020-05-20 13:03:24: "Total notes: 6"
2020-05-20 13:03:24: "Total resources: 3"
2020-05-20 13:03:25: "DecryptionWorker: cannot start because no master key is currently loaded."
2020-05-20 13:08:10: "RevisionService::maintenance: Starting..."
2020-05-20 13:08:10: "RevisionService::maintenance: Service is enabled"
2020-05-20 13:08:10: "RevisionService::collectRevisions: Created revisions for 0 notes"
2020-05-20 13:08:10: "RevisionService::maintenance: Done in 294ms"
```

**Comment by phucng** [comment]
@MoreDelay 
Did you try to uninstall Joplin, delete the folder ~/.config/joplin-desktop, and then re-install Joplin? I got similar issue (Joplin doesn't sync with OneDrive) and it works again after I did the above steps.

**Comment by MoreDelay** [comment]
I tried it just now, I still got a FetchError in my log because of a time out.

It seems some things actually get synced, just not everything every time. Just now (after reinstalling as you advised), I could upload changes that I made in my desktop app and immediately see them on my phone. Although a note I deleted on desktop still appeared on my phone. At the same time a change I made on my phone (that I can see in OneDrive when opening the files with an editor) did not appear on the desktop app (although, I have to admit, it works *sometimes*. Right now I wait a few days/syncs until it finally shows up on my PC)

**Comment by TheOnlyTrueJonathanHeard** [comment]
@MoreDelay  do you use joplin behind a proxy? It might be related to #164. See especially kenden's comment: https://github.com/laurent22/joplin/issues/164#issuecomment-490863643.

**Comment by MoreDelay** [comment]
@TheOnlyTrueJonathanHeard No, this doesn't seem to fit my problem. In that bug issue, the reported error in the log is ECONNREFUSED, while in my case it is just ETIMEDOUT. There also seems to be no indication that authentication failed. In fact, it seems to update a few files before getting stuck and throwing a timeout after a while.

After a few days with this problem now, this problem feels like it exists because of some kind of race condition. With each sync, it basically seems random how many files it can fetch before getting stuck. Sometimes it doesn't fetch anything before timeouting, sometimes it fetches a few files and updates some files (most of the time it fetches/updates 5-20 files of around 100 before stopping progress). Strangely enough I have no problem at all on Android, it reliably fetches all files within a second or two. 

Unfortunately I'm not experienced enough to look into the code and find the race condition myself (I tried but it takes too long for me to understand the code). But I hope this gives some extra information.

**Comment by TheOnlyTrueJonathanHeard** [comment]
@MoreDelay
Ok It was just a guess.  I think a Timeout Error usually occurs when your request doesn't reach the addressed recipient (e.g. when the app fails to use a proxy or when a firewall blocks the outgoing request) or when the specified address doesn't exist. As you are downloading some files we can assume that it is not due to the first mentioned opportunity. So I think that joplin on your windows machine tries for some reasons to download a resource which doesn't exist in Onedrive and rejects afterwards to download other resources (maybe due to a not handled exception). So from my point of view this should be changed in the source code but this is not easy and I don't know if this will be fixed in the near future. The main reason why it is difficult to fix it that it can't be reliable reproduced. I have tried a lot to reproduce this with a "clean" onedrive account (an account where i have deleted the joplin folder) and a clean install on windows and android but without success. I am happy to solve the bug if you find a way to reliable reproduce it but without that we would need to communicate a lot before I would be able to fix it and this is too time-consuming for me (and probably also for others ...).  

However I think that there are some ways you can try which will fix the  problem for you: 

1. Try to update to v1.0.218 on windows and to the newest version on Android (if not happened automatically). In this version the 4 MB Onedrive limit has been solved. I don't think that this will fix your problem but I also didn't expect this in another case but luckily I was wrong (see  https://discourse.joplinapp.org/t/android-sync-not-working-changes-not-updating-on-desktop-no-error-message/9304/20?u=johnny) 
2. If the first solution didn't work: Backup your notes, make a full reinstall (delete your joplin data on all devices and on onedrive), install joplin again and import your backup (see https://discourse.joplinapp.org/t/android-sync-not-working-changes-not-updating-on-desktop-no-error-message/9304/15?u=johnny for full instructions)

**Comment by MoreDelay** [comment]
@TheOnlyTrueJonathanHeard 
I installed the latest version (although I have no files larger than 5kb), uninstalled and also deleted every directory of Joplin I could find (programs, appdata, home folder and onedrive) and reinstalled it (also on my phone), I still cannot download everything in one go. I also tried to see how it looks in a Ubuntu VM on my computer, and even there I got a similar problem, although to a much lesser extend (it gets many more files than on windows, sometimes even all. Mostly it's just very slow for some items). 

This got really confusing for me now. My phone and my computer are on the same network (one in WLAN, one in LAN), so there should not be any difference there, but both on Windows and on Ubuntu the performance takes a great hit when syncing with OneDrive. This behavior is very unreliable and I think as long as there is no other way for me to provide you with more detailed logs, there is nothing you can do for me. I have no idea where to even look for a cause now. Perhaps I'll just close this issue because of its weirdness and it fixes itself at some point.

I also tried DropBox now. I didn't use it for years, but in this case it seems to work, so I'll stick with that for the time being.
