### ISSUE TITLE
OneDrive Sync(fetch) doesn't work on Ubuntu 17.10 

### ISSUE THREAD

**Issue by ktrueda** [laurent22/joplin#326]
### Operating system

- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

I like Jopline. But I can"t use it on Ubuntu 17.10.

When I make new note on my machine(Ubuntu 17.10), Joplin upload the note to Onedrive.
(I can see the file via http://onedrive.live.com/)
But I make new note on another machine(Mac OSX), Joplin on machine(Ubuntu 17.10) doesn't fetch the file.

**Comment by laurent22** [comment]
Could you enable debug mode and check if there's any error in the log? https://github.com/laurent22/joplin/blob/master/readme/debugging.md

**Comment by ktrueda** [comment]
I tryed to run debug mode. But it failed.

I think that console window will be seen if it  run on debug mode.
But I can't find console window .

```
$ cat ~/.config/joplin/flags.txt
--open-dev-tools --log-level debug
$ cat ~/.config/Joplin/flags.txt
--open-dev-tools --log-level debug
$ ./Joplin-1.0.79-x86_64.AppImage
```

**Comment by laurent22** [comment]
Sorry flags.txt should actually go in joplin-desktop

**Comment by ktrueda** [comment]
![screenshot from 2018-03-25 15-33-15](https://user-images.githubusercontent.com/4489901/37872396-e0c39862-3041-11e8-9015-dd9ccd9ae53b.png)

There are no log at console.

And left sidebar shows

```
Fetched items 2/41
Completed ...
```

I guessed that Joplin failed to fetch 39 notes.

**Comment by laurent22** [comment]
Could you check what's in the log in ~/.config/joplin-desktop ? Is there any error or warning?

**Comment by ktrueda** [comment]
I found  error log belog in ~/.config/joplin-desktop/log.txt

```
2018-03-25 17:35:43: "Got unhandled error:", "ECONNRESET", "request to https://public.ch.files.1drv.com/y4m_dv6pnvYDqVvJ7txSXsEReUXmlDtB6Qx7WsNz_Q3QV6PHAlGbA3FgArBlDxr5dFBc_QJB81gUYePC1F-fliovEGWUwNEZjIpXalcNqt175skhrMtYucbUH6oGaLxWFdZSw0xVVhTCAigP49wNn1rZ5u4DDrnH0yPQvEOpCdKFH4AbzN-3J_i_Pe-65tMHo7AZPqW2t8-L9ZV3X00BaKARl8NgW8FZGlZbUlegVbp0Hs/bb88e0d203d940e5814f1c169c207f24.md failed, reason: read ECONNRESET", "FetchError: request to https://public.ch.files.1drv.com/y4m_dv6pnvYDqVvJ7txSXsEReUXmlDtB6Qx7WsNz_Q3QV6PHAlGbA3FgArBlDxr5dFBc_QJB81gUYePC1F-fliovEGWUwNEZjIpXalcNqt175skhrMtYucbUH6oGaLxWFdZSw0xVVhTCAigP49wNn1rZ5u4DDrnH0yPQvEOpCdKFH4AbzN-3J_i_Pe-65tMHo7AZPqW2t8-L9ZV3X00BaKARl8NgW8FZGlZbUlegVbp0Hs/bb88e0d203d940e5814f1c169c207f24.md failed, reason: read ECONNRESET
Code: ECONNRESET
FetchError: request to https://public.ch.files.1drv.com/y4m_dv6pnvYDqVvJ7txSXsEReUXmlDtB6Qx7WsNz_Q3QV6PHAlGbA3FgArBlDxr5dFBc_QJB81gUYePC1F-fliovEGWUwNEZjIpXalcNqt175skhrMtYucbUH6oGaLxWFdZSw0xVVhTCAigP49wNn1rZ5u4DDrnH0yPQvEOpCdKFH4AbzN-3J_i_Pe-65tMHo7AZPqW2t8-L9ZV3X00BaKARl8NgW8FZGlZbUlegVbp0Hs/bb88e0d203d940e5814f1c169c207f24.md failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/tmp/.mount_JoplinaH6H02/app/resources/app/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at emitErrorNT (net.js:1283:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)"
2018-03-25 17:35:43: "FetchError: request to https://public.ch.files.1drv.com/y4m_dv6pnvYDqVvJ7txSXsEReUXmlDtB6Qx7WsNz_Q3QV6PHAlGbA3FgArBlDxr5dFBc_QJB81gUYePC1F-fliovEGWUwNEZjIpXalcNqt175skhrMtYucbUH6oGaLxWFdZSw0xVVhTCAigP49wNn1rZ5u4DDrnH0yPQvEOpCdKFH4AbzN-3J_i_Pe-65tMHo7AZPqW2t8-L9ZV3X00BaKARl8NgW8FZGlZbUlegVbp0Hs/bb88e0d203d940e5814f1c169c207f24.md failed, reason: read ECONNRESET
Code: ECONNRESET
FetchError: request to https://public.ch.files.1drv.com/y4m_dv6pnvYDqVvJ7txSXsEReUXmlDtB6Qx7WsNz_Q3QV6PHAlGbA3FgArBlDxr5dFBc_QJB81gUYePC1F-fliovEGWUwNEZjIpXalcNqt175skhrMtYucbUH6oGaLxWFdZSw0xVVhTCAigP49wNn1rZ5u4DDrnH0yPQvEOpCdKFH4AbzN-3J_i_Pe-65tMHo7AZPqW2t8-L9ZV3X00BaKARl8NgW8FZGlZbUlegVbp0Hs/bb88e0d203d940e5814f1c169c207f24.md failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/tmp/.mount_JoplinaH6H02/app/resources/app/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at emitErrorNT (net.js:1283:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)"
2018-03-25 17:35:43: "Sync: finished: Synchronisation finished [1521966128408]"

```

**Comment by laurent22** [comment]
Connection errors are fine and the operation will simply be resumed on the next sync. Are there some notes or notebooks not syncing if you try again?

**Comment by tessus** [comment]
@ktrueda I'll close this issue since no feedback has been given for over a year.
