### ISSUE TITLE
Error when synchronizing - Error: GET .sync/version.txt: Unknown error 2 (500): <

### ISSUE THREAD

**Issue by armaccloud** [laurent22/joplin#3313]
After I have installed Joplin on my new laptop with PoP!_OS (appimage) and synchronizing the notes, both the Joplin client on the laptop and the client on my Android phone give this error and the synchronization doesn't succeed.

Last error: Error: GET .sync/version.txt: Unknown error 2 (500): <

## Environment

Joplin version: 1.0.216 (Desktop) | 1.0.329 (Android)
Platform: PoP!_OS | Android LineageOS

## Steps to reproduce

1. Have an existing Joplin instance running with notebooks and notes
2. Install appimage package
3. Synchronize the notes and enter the encryption key for decryption in the settings
4. Wait for the synchronization to finish
5. At some point, after making new notes, the error occurs

## Describe what you expected to happen
The synchronization should finish without an error

## Logfile
2020-06-01 10:24:55: "Req 10:24:55: GET https://***website***/remote.php/webdav/Notes/.sync/version.txt {"headers":{"Authorization":"********","User-Agent":"Joplin/1.0"},"timeout":120000,"maxRetry":0}"
2020-06-01 10:24:55: "Res 10:24:55: <"
2020-06-01 10:24:55: "Operations completed: "
2020-06-01 10:24:55: "Total folders: 13"
2020-06-01 10:24:55: "Total notes: 245"
2020-06-01 10:24:55: "Total resources: 169"
2020-06-01 10:24:55: "There was some errors:"
2020-06-01 10:24:55: "Error: GET .sync/version.txt: Unknown error 2 (500): <
Code: 500
Error: GET .sync/version.txt: Unknown error 2 (500): <
    at newError (/tmp/.mount_JoplinrSwvli/resources/app.asar/lib/WebDavApi.js:399:11)
    at WebDavApi.exec (/tmp/.mount_JoplinrSwvli/resources/app.asar/lib/WebDavApi.js:429:10)"
2020-06-01 10:24:56: "DecryptionWorker: starting decryption..."
2020-06-01 10:24:56: "DecryptionWorker: completed decryption."

**Comment by laurent22** [comment]
Error 500 indicates a server error, so you should probably check the log on that side.

**Comment by armaccloud** [comment]
Eventually I followed these steps to solve the issue

- Created a Joplin RAW backup
- Then created a new folder for Joplin to Sync to on Nextcloud
- Cleared Joplin from all data
- Synced with the newly created folder on Nextcloud
- Imported the RAW file into Joplin
- Let the sync run
- Enabled encryption

- Removed all data from Joplin on Android
- Synced with the newly created folder on Nextcloud
