### ISSUE TITLE
Error syncing with WebDAV

### ISSUE THREAD

**Issue by GeneralZero** [laurent22/joplin#340]
### Operating system

- [ ] Windows
- [ ] macOS
- [X] Linux
- [X] Android
- [ ] iOS

### Application

- [X] Desktop
- [X] Mobile
- [ ] Terminal

I get an error when syncing with my Baïkal WebDAV server. Is there any verbose information that I can view to track down the problem?

```
2018-03-27 15:10:51: "Trying to load 0 master keys..."
2018-03-27 15:10:51: "Loaded master keys: 0"
2018-03-27 15:10:51: "Trying to load 0 master keys..."
2018-03-27 15:10:51: "Loaded master keys: 0"
2018-03-27 15:10:51: "Scheduling sync operation..."
2018-03-27 15:10:51: "Scheduling sync operation..."
2018-03-27 15:10:52: "DecryptionWorker: starting decryption..."
2018-03-27 15:10:52: "DecryptionWorker: completed decryption."
2018-03-27 15:10:53: "Scheduling sync operation..."
2018-03-27 15:10:53: "Preparing scheduled sync"
2018-03-27 15:10:53: "Starting scheduled sync"
2018-03-27 15:11:17: "TypeError: Cannot read property '0' of null
TypeError: Cannot read property '0' of null
    at WebDavApi.resourcePropByName (/tmp/.mount_JoplinZ2WDXq/app/resources/app/lib/WebDavApi.js:166:19)
    at FileApiDriverWebDav.statFromResource_ (/tmp/.mount_JoplinZ2WDXq/app/resources/app/lib/file-api-driver-webdav.js:58:41)
    at FileApiDriverWebDav.stat (/tmp/.mount_JoplinZ2WDXq/app/resources/app/lib/file-api-driver-webdav.js:33:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)"
2018-03-27 15:11:17: "Operations completed: "
2018-03-27 15:11:17: "Total folders: 0"
2018-03-27 15:11:17: "Total notes: 0"
2018-03-27 15:11:17: "Total resources: 0"
2018-03-27 15:11:17: "There was some errors:"
2018-03-27 15:11:17: "TypeError: Cannot read property '0' of null
TypeError: Cannot read property '0' of null
    at WebDavApi.resourcePropByName (/tmp/.mount_JoplinZ2WDXq/app/resources/app/lib/WebDavApi.js:166:19)
    at FileApiDriverWebDav.statFromResource_ (/tmp/.mount_JoplinZ2WDXq/app/resources/app/lib/file-api-driver-webdav.js:58:41)
    at FileApiDriverWebDav.stat (/tmp/.mount_JoplinZ2WDXq/app/resources/app/lib/file-api-driver-webdav.js:33:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)"
2018-03-27 15:11:21: "ResourceService::indexNoteResources: Start"
2018-03-27 15:11:21: "ResourceService::indexNoteResources: Completed"
2018-03-27 15:11:21: "ResourceService::deleteOrphanResources:", "[]"
```

**Comment by laurent22** [comment]
Most likely something not quite standard. Is there any account that can be used for testing?

**Comment by GeneralZero** [comment]
Testing account has been made.

URL: https://cal.generalzero.org/
Username: test
Password: Testing123

**Comment by dincsi** [comment]
I experienced similar problem with box sync. I got _Missing Master Key_ message on  Encryption option screen. Is there any way to get the encryption key manually?

**Comment by GeneralZero** [comment]
I did some more configuration and it seems like its a problem with making a folder called .sync. Is there any way that I can change the name it makes?

`WARNING: Bad MKCOL request on '/.sync': Can't translate name safely to filesystem: '.sync'`

**Comment by laurent22** [comment]
Does this Baïkal app is also supposed to handle WebDAV? Because their web page only mentioned calendars and contacts.

I think there are too many issues with their implementation so I don't think it will be possible to support it. The XML they send back is a bit strange (it has no namespace) although it's possible to work around it. However, when I try to create a ".sync" directory it just says "Bad request" even though I know the request is valid.

It's possible they don't allow directories that start with a "dot" but in that case it's probably something they need to fix on their end.

**Comment by GeneralZero** [comment]
You are right it does not support WebDAV.
