### ISSUE TITLE
Fatal error in Windows 10

### ISSUE THREAD

**Issue by bnovak1** [laurent22/joplin#3483]
## Environment

Joplin version:  1.0.226
Platform: Windows
OS specifics: Windows 10 Home version 1904

## Steps to reproduce

1.  Open Joplin
2. 
3. 

## Describe what you expected to happen

Instead of showing notes as expected, an error message is immediately shown which is below.

## Logfile

Error
Joplin encountered a fatal error and could not continue. To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

Message
Cannot read property 'id' of null

Stack trace
TypeError: Cannot read property 'id' of null
    at NoteToolbar (C:\Users\bnovak1\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteToolbar\NoteToolbar.js:51:43)
    at renderWithHooks (C:\Users\bnovak1\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:15108:18)
    at mountIndeterminateComponent (C:\Users\bnovak1\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:17342:13)
    at beginWork$1 (C:\Users\bnovak1\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:18486:16)
    at HTMLUnknownElement.callCallback (C:\Users\bnovak1\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:347:14)
    at Object.invokeGuardedCallbackDev (C:\Users\bnovak1\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:397:16)
    at invokeGuardedCallback (C:\Users\bnovak1\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:454:31)
    at beginWork$$1 (C:\Users\bnovak1\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:23217:7)
    at performUnitOfWork (C:\Users\bnovak1\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:22208:12)
    at workLoopSync (C:\Users\bnovak1\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:22185:22)
Component stack

    in NoteToolbar (created by Connect(NoteToolbar))
    in Connect(NoteToolbar) (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in NoteEditor (created by Connect(NoteEditor))
    in Connect(NoteEditor) (created by MainScreenComponent)
    in div (created by MainScreenComponent)
    in MainScreenComponent (created by Connect(MainScreenComponent))
    in Connect(MainScreenComponent) (created by NavigatorComponent)
    in div (created by NavigatorComponent)
    in NavigatorComponent (created by Connect(NavigatorComponent))
    in Connect(NavigatorComponent) (created by RootComponent)
    in RootComponent (created by Connect(RootComponent))
    in Connect(RootComponent)
    in ErrorBoundary
    in Provider

**Comment by wolfen-stein** [comment]
Same problem on Mac.

Joplin version: 1.0.226
Platform: Mac
OS specifics: macOS Mojave 10.14.6

```
Error
Joplin encountered a fatal error and could not continue. To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

Message
Cannot read property 'id' of null

Stack trace
TypeError: Cannot read property 'id' of null
    at NoteToolbar (/Applications/Joplin.app/Contents/Resources/app.asar/gui/NoteToolbar/NoteToolbar.js:51:43)
    at renderWithHooks (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:15108:18)
    at mountIndeterminateComponent (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:17342:13)
    at beginWork$1 (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:18486:16)
    at HTMLUnknownElement.callCallback (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:347:14)
    at Object.invokeGuardedCallbackDev (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:397:16)
    at invokeGuardedCallback (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:454:31)
    at beginWork$$1 (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23217:7)
    at performUnitOfWork (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22208:12)
    at workLoopSync (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22185:22)
Component stack

    in NoteToolbar (created by Connect(NoteToolbar))
    in Connect(NoteToolbar) (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in NoteEditor (created by Connect(NoteEditor))
    in Connect(NoteEditor) (created by MainScreenComponent)
    in div (created by MainScreenComponent)
    in MainScreenComponent (created by Connect(MainScreenComponent))
    in Connect(MainScreenComponent) (created by NavigatorComponent)
    in div (created by NavigatorComponent)
    in NavigatorComponent (created by Connect(NavigatorComponent))
    in Connect(NavigatorComponent) (created by RootComponent)
    in RootComponent (created by Connect(RootComponent))
    in Connect(RootComponent)
    in ErrorBoundary
    in Provider
```

**Comment by laurent22** [comment]
Please try v227 as that should be fixed.

**Comment by 2pascal** [comment]
Having this issue today on Windows 10
