### ISSUE TITLE
Error when trying to delete notebook with unselected "Cancel" button

### ISSUE THREAD

**Issue by arthurk** [laurent22/joplin#3485]
A bit of an edge case but I noticed that the app crashes when I try to delete a notebook that has a note in it but I unselect the cancel button (it doesn't crash when the notebook is empty). To reproduce:

1. Create notebook and a note
2. Right click and click delete
3. The "Cancel" in the modal is pre-selected (blue) but it can be unselected by holding down the mouse button and dragging the mouse cursor away from it. It then looks like this:

<img width="422" alt="Screen Shot 2020-07-12 at 4 30 50 PM" src="https://user-images.githubusercontent.com/23406/87242197-131ea700-c45d-11ea-8c92-2d082c591146.png">

4. Click on "Delete" and the app crashes with the stacktrace below.

## Environment

Joplin for Desktop
Copyright © 2016-2020 Laurent Cozic
Joplin 1.0.226 (prod, darwin)
Sync Version: 1
Profile Version: 30
Keychain Supported: Yes
Revision: 9c05707 (master)

## Logfile

```
Error
Joplin encountered a fatal error and could not continue. To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

Message
Cannot read property 'id' of null

Stack trace
TypeError: Cannot read property 'id' of null
    at NoteToolbar (/Applications/Joplin.app/Contents/Resources/app.asar/gui/NoteToolbar/NoteToolbar.js:51:43)
    at renderWithHooks (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:15108:18)
    at mountIndeterminateComponent (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:17342:13)
    at beginWork$1 (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:18486:16)
    at HTMLUnknownElement.callCallback (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:347:14)
    at Object.invokeGuardedCallbackDev (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:397:16)
    at invokeGuardedCallback (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:454:31)
    at beginWork$$1 (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23217:7)
    at performUnitOfWork (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22208:12)
    at workLoopSync (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22185:22)
Component stack

    in NoteToolbar (created by Connect(NoteToolbar))
    in Connect(NoteToolbar) (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in NoteEditor (created by Connect(NoteEditor))
    in Connect(NoteEditor) (created by MainScreenComponent)
    in div (created by MainScreenComponent)
    in MainScreenComponent (created by Connect(MainScreenComponent))
    in Connect(MainScreenComponent) (created by NavigatorComponent)
    in div (created by NavigatorComponent)
    in NavigatorComponent (created by Connect(NavigatorComponent))
    in Connect(NavigatorComponent) (created by RootComponent)
    in RootComponent (created by Connect(RootComponent))
    in Connect(RootComponent)
    in ErrorBoundary
    in Provider
```

**Comment by laurent22** [comment]
Please try v227 as that should be fixed.
