### ISSUE TITLE
SyntaxError on OS X (Homebrew) v. 1.0.106

### ISSUE THREAD

**Issue by Jestre** [laurent22/joplin#353]
### Operating system

- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [ ] Desktop
- [ ] Mobile
- [x] Terminal

OSX with Homebrew.  After a `brew upgrade` this morning, I received an upgrade to both joplin and node, versions 1.0.106 and 9.10.1 respectively.

When I try to run `joplin` or `joplin help` etc, I get the following error:

```node
$ joplin

/usr/local/Cellar/joplin/1.0.106/libexec/lib/node_modules/joplin/main.js:13
const { app } = require('./app.js');
      ^
SyntaxError: Unexpected token {
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```
Am I missing something?  I looked through old tickets, and saw this error mentioned previously, but it seemed to be related to the Linux install method.

Thanks

**Comment by Jestre** [comment]
nvm error
