### ISSUE TITLE
Blocked a frame with origin "file://" from accessing a cross-origin frame.

### ISSUE THREAD

**Issue by odboy** [laurent22/joplin#3693]
## Environment

Joplin version: Joplin 1.0.233(prod, win32)
Platform: Windows 10
OS specifics: 

## Steps to reproduce
paste `/etc/hosts` in search bar

## Describe what you expected to happen
just search the string

## Logfile

```
Error
Joplin encountered a fatal error and could not continue. To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

Message
Blocked a frame with origin "file://" from accessing a cross-origin frame.

Stack trace
Error: Blocked a frame with origin "file://" from accessing a cross-origin frame.
    at NoteTextViewerComponent.destroyWebview (C:\Users\admin\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteTextViewer.min.js:81:42)
    at NoteTextViewerComponent.componentWillUnmount (C:\Users\admin\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteTextViewer.min.js:103:8)
    at callComponentWillUnmountWithTimer (C:\Users\admin\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:19866:12)
    at HTMLUnknownElement.callCallback (C:\Users\admin\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:347:14)
    at Object.invokeGuardedCallbackDev (C:\Users\admin\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:397:16)
    at invokeGuardedCallback (C:\Users\admin\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:454:31)
    at safelyCallComponentWillUnmount (C:\Users\admin\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:19873:5)
    at commitUnmount (C:\Users\admin\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:20293:11)
    at commitNestedUnmounts (C:\Users\admin\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:20349:5)
    at unmountHostComponents (C:\Users\admin\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:20645:7)
Component stack

    in NoteTextViewerComponent (created by Connect(NoteTextViewerComponent))
    in Connect(NoteTextViewerComponent) (created by ForwardRef(AceEditor))
    in div (created by ForwardRef(AceEditor))
    in div (created by ForwardRef(AceEditor))
    in div (created by ForwardRef(AceEditor))
    in ForwardRef(AceEditor) (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in NoteEditor (created by Connect(NoteEditor))
    in Connect(NoteEditor) (created by MainScreenComponent)
    in div (created by MainScreenComponent)
    in MainScreenComponent (created by Connect(MainScreenComponent))
    in Connect(MainScreenComponent) (created by NavigatorComponent)
    in div (created by NavigatorComponent)
    in NavigatorComponent (created by Connect(NavigatorComponent))
    in Connect(NavigatorComponent) (created by RootComponent)
    in RootComponent (created by Connect(RootComponent))
    in Connect(RootComponent)
    in ErrorBoundary
    in Provider
```

**Comment by laurent22** [comment]
I cannot replicate this bug, but it might be due to one of your notes that contain the string "/etc/hosts" or maybe just the strings "etc" and "hosts" separately. To see if I can replicate the issue please could you try to find this note and copy and paste the Markdown content here?
