### ISSUE TITLE
Joplin Fatal Error after modifying the userstyle.css

### ISSUE THREAD

**Issue by xarthurx** [laurent22/joplin#3726]
## Steps to reproduce

1. modify the theme `userstyle.css`  with https://github.com/amandamcg/joplin-theme/blob/master/theme/userstyle.css
2. reload Joplin.
3. 

## Logfile
Error
Joplin encountered a fatal error and could not continue. To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

Message
Blocked a frame with origin "file://" from accessing a cross-origin frame.

Version info
Joplin for Desktop

Copyright © 2016-2020 Laurent Cozic
Joplin 1.0.242 (prod, win32)

Client ID: 766eac223764400f86982bf080bba71b
Sync Version: 2
Profile Version: 33
Keychain Supported: Yes

Revision: 3a33e5f4 (master)
Stack trace
Error: Blocked a frame with origin "file://" from accessing a cross-origin frame.
    at NoteTextViewerComponent.destroyWebview (C:\Users\xarthur\scoop\apps\joplin\1.0.242\resources\app.asar\gui\NoteTextViewer.min.js:81:42)
    at NoteTextViewerComponent.componentWillUnmount (C:\Users\xarthur\scoop\apps\joplin\1.0.242\resources\app.asar\gui\NoteTextViewer.min.js:103:8)
    at callComponentWillUnmountWithTimer (C:\Users\xarthur\scoop\apps\joplin\1.0.242\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:19866:12)
    at HTMLUnknownElement.callCallback (C:\Users\xarthur\scoop\apps\joplin\1.0.242\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:347:14)
    at Object.invokeGuardedCallbackDev (C:\Users\xarthur\scoop\apps\joplin\1.0.242\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:397:16)
    at invokeGuardedCallback (C:\Users\xarthur\scoop\apps\joplin\1.0.242\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:454:31)
    at safelyCallComponentWillUnmount (C:\Users\xarthur\scoop\apps\joplin\1.0.242\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:19873:5)
    at commitUnmount (C:\Users\xarthur\scoop\apps\joplin\1.0.242\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:20293:11)
    at commitNestedUnmounts (C:\Users\xarthur\scoop\apps\joplin\1.0.242\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:20349:5)
    at unmountHostComponents (C:\Users\xarthur\scoop\apps\joplin\1.0.242\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:20645:7)
Component stack

    in NoteTextViewerComponent (created by Connect(NoteTextViewerComponent))
    in Connect(NoteTextViewerComponent) (created by ForwardRef(CodeMirror))
    in div (created by ForwardRef(CodeMirror))
    in div (created by ForwardRef(CodeMirror))
    in div (created by ForwardRef(CodeMirror))
    in ForwardRef(CodeMirror) (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in NoteEditor (created by Connect(NoteEditor))
    in Connect(NoteEditor) (created by MainScreenComponent)
    in div (created by MainScreenComponent)
    in MainScreenComponent (created by Connect(MainScreenComponent))
    in Connect(MainScreenComponent) (created by NavigatorComponent)
    in div (created by NavigatorComponent)
    in NavigatorComponent (created by Connect(NavigatorComponent))
    in Connect(NavigatorComponent) (created by RootComponent)
    in RootComponent (created by Connect(RootComponent))
    in Connect(RootComponent)
    in ErrorBoundary
    in Provider

**Comment by laurent22** [comment]
Could you share the note that caused the issue (as a JEX file)?

**Comment by xarthurx** [comment]
OK, I double-check the issue. It seems was not caused by the note, but rather "in-app refresh of the userstyle".
Steps to reproduce:

1. Modify `userstyle.css`
2. Help->toggle development tools.
3. Ctrl-R to refresh the style without exit Joplin and restart. (The current note will be displayed in the updated style).
4. Click on any other note. ---> This will cause the crash.

Additional note:
1. Once the crash occur, Joplin will show the above info.
2. Right-click the Joplin icon in the tray and exit does not work.
3. Using **Task Manager** to kill the Joplin process does not work.

I have to restart the computer to make Joplin start again.

**Comment by butterflyx** [comment]
I can confirm this. 
Same behavior, same reason.

My trace:

```
Error
Joplin encountered a fatal error and could not continue. To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

Message
Blocked a frame with origin "file://" from accessing a cross-origin frame.

Version info
Joplin for Desktop

Copyright © 2016-2020 Laurent Cozic
Joplin 1.1.4 (prod, win32)

Client-ID: 0836c8e7b6224f2996d09207cee47b1e
Sync-Version: 2
Profil-Version: 34
Unterstützter Schlüsselbund: Ja

Revision: 9610b7e6 (master)
Stack trace
Error: Blocked a frame with origin "file://" from accessing a cross-origin frame.
    at NoteTextViewerComponent.destroyWebview (C:\Users\ms\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteTextViewer.min.js:81:42)
    at NoteTextViewerComponent.componentWillUnmount (C:\Users\ms\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteTextViewer.min.js:103:8)
    at callComponentWillUnmountWithTimer (C:\Users\ms\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:19866:12)
    at HTMLUnknownElement.callCallback (C:\Users\ms\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:347:14)
    at Object.invokeGuardedCallbackDev (C:\Users\ms\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:397:16)
    at invokeGuardedCallback (C:\Users\ms\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:454:31)
    at safelyCallComponentWillUnmount (C:\Users\ms\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:19873:5)
    at commitUnmount (C:\Users\ms\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:20293:11)
    at commitNestedUnmounts (C:\Users\ms\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:20349:5)
    at unmountHostComponents (C:\Users\ms\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:20645:7)
Component stack

    in NoteTextViewerComponent (created by Connect(NoteTextViewerComponent))
    in Connect(NoteTextViewerComponent) (created by ForwardRef(CodeMirror))
    in div (created by ForwardRef(CodeMirror))
    in div (created by ForwardRef(CodeMirror))
    in div (created by ForwardRef(CodeMirror))
    in ForwardRef(CodeMirror) (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in NoteEditor (created by Connect(NoteEditor))
    in Connect(NoteEditor) (created by MainScreenComponent)
    in div (created by MainScreenComponent)
    in MainScreenComponent (created by Connect(MainScreenComponent))
    in Connect(MainScreenComponent) (created by NavigatorComponent)
    in div (created by NavigatorComponent)
    in NavigatorComponent (created by Connect(NavigatorComponent))
    in Connect(NavigatorComponent) (created by RootComponent)
    in RootComponent (created by Connect(RootComponent))
    in Connect(RootComponent)
    in ErrorBoundary
    in Provider
```
