### ISSUE TITLE
macos filesync: Error: EROFS: read-only file system

### ISSUE THREAD

**Issue by RMHogervorst** [laurent22/joplin#3762]
Hello devs, I have a weird issue. I'm using joplin on my android phone and use file sync and syncthing to sync it to my macbook. This all works, the .md files are on my disk. 
I installed joplin on my macbook (using the 'hack' to activate the program (right click open from applications) because it is not signed).
In the sync settings I refer to the correct folder ` /Users/MYUSERNAME/Documents/syncthing_folders/Joplin`

But then I get the following error in log.txt (in :
```
2020-09-17 16:19:15: "Could not acquire synchroniser:"
Error: Error: EROFS: read-only file system, mkdir '/ '. Path:  /Users/MYUSERNAME/Documents/syncthing_folders/Joplin
    at FileApiDriverLocal.fsErrorToJsError_ (/Applications/Joplin.app/Contents/Resources/app.asar/lib/file-api-driver-local.js:20:18)
    at FileApiDriverLocal.mkdir (/Applications/Joplin.app/Contents/Resources/app.asar/lib/file-api-driver-local.js:120:15)"
```

I went into the security and privacy settings and enabled full disk access for the joplin app but to no avail. I also set the folder and underlying files to read&write for everyone

I have several ideas what could be wrong: 
- the app is blocked because it is not trusted
- the file ownership is different?
- I did not refer to the correct folder?

## Environment

Joplin version: 1.0.245 (prod, darwin) / Sync Version: 2 / Profile Version: 33 / Keychain Supported: Yes / Revision: 2aa7eaa (master)
Platform: MACOS
OS specifics: Catelina 10.15.6

## Steps to reproduce

1. install joplin on android 
2. sync to file system
3. copy files to macos
4. install joplin on macos
5. set up file sync and refer to synced folder / copied folder in disk
6. failure

## Describe what you expected to happen
I expected the notebooks I have on my android phone to show in the joplin app on my macbook, but they do not.

## Logfile

```
CommandService::execute: /Applications/Joplin.app/Contents/Resources/app.asar/lib/services/CommandService.js:144

synchronize 
{syncStarted: false}
syncStarted: false
__proto__: Object

```

**Comment by RMHogervorst** [comment]
This is still not working. Any ideas on what the cause of the problem is?
