### ISSUE TITLE
'Joplin encountered a fatal error and could not continue.'

### ISSUE THREAD

**Issue by cristianvasquez** [laurent22/joplin#3835]
Joplin told me to report an error, so I did. 

Error
Joplin encountered a fatal error and could not continue. To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

Message
Blocked a frame with origin "file://" from accessing a cross-origin frame.

Version info
Joplin for Desktop

Copyright © 2016-2020 Laurent Cozic
Joplin 1.2.2 (prod, linux)

Client ID: d5cfaab2a8564c6682075abc6c2ab585
Sync Version: 2
Profile Version: 34
Keychain Supported: No

Revision: 95e7f3d (master)
Stack trace
Error: Blocked a frame with origin "file://" from accessing a cross-origin frame.
    at NoteTextViewerComponent.destroyWebview (/tmp/.mount_Joplin93LK2F/resources/app.asar/gui/NoteTextViewer.min.js:81:42)
    at NoteTextViewerComponent.componentWillUnmount (/tmp/.mount_Joplin93LK2F/resources/app.asar/gui/NoteTextViewer.min.js:103:8)
    at callComponentWillUnmountWithTimer (/tmp/.mount_Joplin93LK2F/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:19866:12)
    at HTMLUnknownElement.callCallback (/tmp/.mount_Joplin93LK2F/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:347:14)
    at Object.invokeGuardedCallbackDev (/tmp/.mount_Joplin93LK2F/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:397:16)
    at invokeGuardedCallback (/tmp/.mount_Joplin93LK2F/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:454:31)
    at safelyCallComponentWillUnmount (/tmp/.mount_Joplin93LK2F/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:19873:5)
    at commitUnmount (/tmp/.mount_Joplin93LK2F/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:20293:11)
    at commitNestedUnmounts (/tmp/.mount_Joplin93LK2F/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:20349:5)
    at unmountHostComponents (/tmp/.mount_Joplin93LK2F/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:20645:7)
Component stack

    in NoteTextViewerComponent (created by Connect(NoteTextViewerComponent))
    in Connect(NoteTextViewerComponent) (created by ForwardRef(CodeMirror))
    in div (created by ForwardRef(CodeMirror))
    in div (created by ForwardRef(CodeMirror))
    in div (created by ForwardRef(CodeMirror))
    in ForwardRef(CodeMirror) (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in NoteEditor (created by Connect(NoteEditor))
    in Connect(NoteEditor) (created by ResizableLayout)
    in div (created by ResizableLayout)
    in div (created by ResizableLayout)
    in div (created by ResizableLayout)
    in ResizableLayout (created by MainScreenComponent)
    in div (created by MainScreenComponent)
    in MainScreenComponent (created by Connect(MainScreenComponent))
    in Connect(MainScreenComponent) (created by NavigatorComponent)
    in div (created by NavigatorComponent)
    in NavigatorComponent (created by Connect(NavigatorComponent))
    in Connect(NavigatorComponent) (created by RootComponent)
    in ThemeProvider (created by RootComponent)
    in StyleSheetManager (created by RootComponent)
    in RootComponent (created by Connect(RootComponent))
    in Connect(RootComponent)
    in ErrorBoundary
    in Provider

## Environment

Joplin version: pre-release v1.2.2
Platform: Desktop
OS specifics: Linux ubuntu

## Steps to reproduce

1. This happened when opening the 'options page' 
2. I close and open Joplin, and the error stays there
3. I restarted and the error is gone

## Describe what you expected to happen

I expected it to open

**Comment by laurent22** [comment]
Are you able to replicate this crash with a particular note, or is it random?

**Comment by cristianvasquez** [comment]
It happened at random
