### ISSUE TITLE
Lost all notes without any specific action. 

### ISSUE THREAD

**Issue by nivasr** [laurent22/joplin#3846]
[log-database.txt](https://github.com/laurent22/joplin/files/5295497/log-database.txt)
[log.txt](https://github.com/laurent22/joplin/files/5295498/log.txt)
[userchrome.css.txt](https://github.com/laurent22/joplin/files/5295500/userchrome.css.txt)

I will try not to sound dramatic, but I lost all notes, except 6 that were under sync issues. 

**Steps to reproduce:**
Nothing abnormal, as far as I can tell. Open a note, type a few sentences every few 30 minutes or so depending on workload, meetings...

I did have a few sync errors the last few days, and I have been moving them back to the notebook where they should have been.

Joplin version:  Joplin 1.1.4 (prod, darwin), Sync Version: 2, Profile Version: 34, Keychain Supported: Yes, Revision: 9610b7e (master)
Platform: MacOS 10.15.6
OS specifics:  10.15.6
App configuration: Installed in applications, sync set to local folder, every 5 minutes, to a folder under my user Id.
Recent changes: No changes to the data folder above. I have been playing with the userChrome.css files (adding a couple of css classes). I have provided the file below.

This is what I find in the logs:
*log-database.txt*, the log has been repeats of this message for the last couple of days. This seems to have started at `2020-09-22 15:17:39` but I am sure the notes were there at 4 pm today (2020-09-28). I know they were not there at 6 pm today (2020-09-28).

```
2020-09-23 16:24:11: "Current database version", "33"
2020-09-23 16:24:11: "Converting database to version 34"
2020-09-23 16:24:11: "Could not upgrade to database v34 - fuzzy search will not be used", "Error: Error: SQLITE_ERROR: no such module: spellfix1: CREATE VIRTUAL TABLE notes_spellfix USING spellfix1
Code: SQLITE_ERROR
Error: Error: SQLITE_ERROR: no such module: spellfix1: CREATE VIRTUAL TABLE notes_spellfix USING spellfix1
    at DatabaseDriverNode.sqliteErrorToJsError (/Applications/Joplin.app/Contents/Resources/app.asar/lib/database-driver-node.js:21:18)
    at JoplinDatabase.sqliteErrorToJsError (/Applications/Joplin.app/Contents/Resources/app.asar/lib/database.js:22:24)
    at JoplinDatabase.tryCall (/Applications/Joplin.app/Contents/Resources/app.asar/lib/database.js:90:17)"
2020-09-23 16:24:12: "Saving settings..."
2020-09-23 16:24:12: "Settings have been saved."
2020-09-23 16:35:00: "Database was open successfully"
2020-09-23 16:35:00: "Checking for database schema update..."
2020-09-23 16:35:00: "Current database version", "33"
2020-09-23 16:35:00: "Converting database to version 34"
2020-09-23 16:35:00: "Could not upgrade to database v34 - fuzzy search will not be used", "Error: Error: SQLITE_ERROR: no such module: spellfix1: CREATE VIRTUAL TABLE notes_spellfix USING spellfix1
Code: SQLITE_ERROR
Error: Error: SQLITE_ERROR: no such module: spellfix1: CREATE VIRTUAL TABLE notes_spellfix USING spellfix1
    at DatabaseDriverNode.sqliteErrorToJsError (/Applications/Joplin.app/Contents/Resources/app.asar/lib/database-driver-node.js:21:18)
    at JoplinDatabase.sqliteErrorToJsError (/Applications/Joplin.app/Contents/Resources/app.asar/lib/database.js:22:24)
    at JoplinDatabase.tryCall (/Applications/Joplin.app/Contents/Resources/app.asar/lib/database.js:90:17)"
2020-09-23 16:35:01: "Saving settings..."

```

**log.txt**   
The no of notes have drastically gone down from 47 at `2020-09-28 16:33:16` to 6 at `2020-09-28 16:38:18`.
the Fail Safe error has been repeating from `2020-09-23 16:45:37`. I did not know this was a problem because this is the first time I saw the logs.
```
2020-09-28 16:28:15: "Preparing scheduled sync"
2020-09-28 16:28:15: "Starting scheduled sync"
2020-09-28 16:28:15: "Sync target info:", "{"version":2}"
2020-09-28 16:28:16: "TaskQueue.stop: syncDownload: waiting for tasks to complete: 0"
2020-09-28 16:28:16: "TaskQueue.stop: syncDownload: Done, waited for 0"
2020-09-28 16:28:16: "Operations completed: "
2020-09-28 16:28:16: "updateRemote: 1"
2020-09-28 16:28:16: "Total folders: 9"
2020-09-28 16:28:16: "Total notes: 47"
2020-09-28 16:28:16: "Total resources: 8"
2020-09-28 16:33:16: "Running background sync on timer..."
2020-09-28 16:33:16: "Preparing scheduled sync"
2020-09-28 16:33:16: "Starting scheduled sync"
2020-09-28 16:33:16: "Sync target info:", "{"version":2}"
2020-09-28 16:33:16: "TaskQueue.stop: syncDownload: waiting for tasks to complete: 0"
2020-09-28 16:33:16: "TaskQueue.stop: syncDownload: Done, waited for 0"
2020-09-28 16:33:16: "BasicDelta: Report: {"timestamp":1600789968024,"older":0,"newer":19,"equal":0}"
2020-09-28 16:33:16: "Error: Fail-safe: Sync was interrupted because 90% of the data (164 items) is about to be deleted. To override this behaviour disable the fail-safe in the sync settings.. Path: /Users/nivasr/Data/JoplinNotes"
2020-09-28 16:33:16: "Operations completed: "
2020-09-28 16:33:16: "Total folders: 9"
2020-09-28 16:33:16: "Total notes: 47"
2020-09-28 16:33:16: "Total resources: 8"
2020-09-28 16:33:16: "There was some errors:"
2020-09-28 16:33:16: "Error: Fail-safe: Sync was interrupted because 90% of the data (164 items) is about to be deleted. To override this behaviour disable the fail-safe in the sync settings.. Path: /Users/nivasr/Data/JoplinNotes"
2020-09-28 16:33:17: "DecryptionWorker: cannot start because no master key is currently loaded."
2020-09-28 16:34:49: "RevisionService::maintenance: Starting..."
2020-09-28 16:34:49: "RevisionService::maintenance: Service is enabled"
2020-09-28 16:34:49: "RevisionService::collectRevisions: Created revisions for 1 notes"
2020-09-28 16:34:49: "RevisionService::maintenance: Done in 132ms"
2020-09-28 16:38:16: "Running background sync on timer..."
2020-09-28 16:38:16: "Preparing scheduled sync"
2020-09-28 16:38:16: "Starting scheduled sync"
2020-09-28 16:38:16: "Sync target info:", "{"version":2}"
2020-09-28 16:38:16: "TaskQueue.stop: syncDownload: waiting for tasks to complete: 0"
2020-09-28 16:38:16: "TaskQueue.stop: syncDownload: Done, waited for 0"
2020-09-28 16:38:16: "BasicDelta: Report: {"timestamp":1600789968024,"older":0,"newer":20,"equal":0}"
2020-09-28 16:38:18: "BasicDelta: Report: {"timestamp":1601325496106,"older":19,"newer":0,"equal":1}"
2020-09-28 16:38:18: "Operations completed: "
2020-09-28 16:38:18: "createRemote: 1"
2020-09-28 16:38:18: "fetchingTotal: 184"
2020-09-28 16:38:18: "fetchingProcessed: 184"
2020-09-28 16:38:18: "deleteLocal: 160"
2020-09-28 16:38:18: "Total folders: 0"
2020-09-28 16:38:18: "Total notes: 6"
2020-09-28 16:38:18: "Total resources: 0"
2020-09-28 16:38:19: "DecryptionWorker: cannot start because no master key is currently loaded."
2020-09-28 16:38:26: "SearchEngine: Updating FTS table..."
2020-09-28 16:38:26: "SearchEngine: Updated FTS table in 170ms. Inserted: 0. Deleted: 41"

```

**Comment by laurent22** [comment]
It seems all your notes were deleted on the sync target, which is why you have this message in the log:

> Error: Fail-safe: Sync was interrupted because 90% of the data (164 items) is about to be deleted. To override this behaviour disable the fail-safe in the sync settings.. Path: /Users/nivasr/Data/JoplinNote

Normally it should have warned you on the UI too and unless you disable fail-safe it should not have deleted the notes. This is a mechanism to allow you to backup your notes and fix whatever the problem was on the sync target.

At this point, your best option is to restore from a backup if you have one. It can be a JEX archive you might have exported, or a backup of the sync target.

**Comment by nivasr** [comment]
This is very interesting as I did not get any warning on the UI. I did get a conflict message, but that was for only a few notes (and ironically those are the only ones that were not deleted).  Anyway, thanks for the response.
