### ISSUE TITLE
Sync error with Onedrive for Business with onedrive user setting as chinese language

### ISSUE THREAD

**Issue by imfannet** [laurent22/joplin#3878]
## Environment

Joplin version: 1.2.4
Platform: Windows
OS specifics: Windows 10 2004
Location: Mainland China

## Steps to reproduce

1. Open newly installed Joplin 1.2.4
2. Enable sync with Onedrive for Business (Office 365 Dev) with user setting include chinese language (only Onedrive setting matters)
3. Start sync
4. Switch language setting from chinese to english, clean the config and re-open Joplin and set sync again

## Describe what you expected to happen

First time sync with chinese failed with error followed:
'Not a valid URL: https://graph.microsoft.com/v1.0/drives/b!U5ByDreWY0uX7JzebDoZXLs4Te6LoFtNkGpCqJIzI2z2iWS_AdFdQanepjAILUQD/root:/应用/Joplin/info.json:/content"'

PS: 应用 = Apps which was setup automaticly

Sync with english running as expected. (Folder change from 应用 to Apps)

## Logfile

Checked Database Log shows Joplin get Onedrive API/token/secret works fine.

Main logs followed:
```
2020-10-08 00:15:11: "Saving updated OneDrive auth."
2020-10-08 00:15:38: "Saving updated OneDrive auth."
2020-10-08 00:15:39: "Saving updated OneDrive auth."
2020-10-08 00:15:39: "Scheduling sync operation...", "0"
2020-10-08 00:15:39: "Preparing scheduled sync"
2020-10-08 00:15:40: "Starting scheduled sync"
2020-10-08 00:15:40: "Sync: starting: Starting synchronisation to target 3... [1602087340663]"
2020-10-08 00:15:40: "get /drives/b!U5ByDreWY0uX7JzebDoZXLs4Te6LoFtNkGpCqJIzI2z2iWS_AdFdQanepjAILUQD/root:/应用/Joplin/info.json"
2020-10-08 00:15:40: "Got unhandled error:", "undefined", "Not a valid URL: https://graph.microsoft.com/v1.0/drives/b!U5ByDreWY0uX7JzebDoZXLs4Te6LoFtNkGpCqJIzI2z2iWS_AdFdQanepjAILUQD/root:/应用/Joplin/info.json:/content", "Error: Not a valid URL: https://graph.microsoft.com/v1.0/drives/b!U5ByDreWY0uX7JzebDoZXLs4Te6LoFtNkGpCqJIzI2z2iWS_AdFdQanepjAILUQD/root:/应用/Joplin/info.json:/content
Error: Not a valid URL: https://graph.microsoft.com/v1.0/drives/b!U5ByDreWY0uX7JzebDoZXLs4Te6LoFtNkGpCqJIzI2z2iWS_AdFdQanepjAILUQD/root:/应用/Joplin/info.json:/content
    at Object.shim.fetch (C:\Program Files\Joplin\resources\app.asar\lib\shim-init-node.js:292:28)
    at OneDriveApi.exec (C:\Program Files\Joplin\resources\app.asar\lib\onedrive-api.js:252:28)
    at OneDriveApi.execText (C:\Program Files\Joplin\resources\app.asar\lib\onedrive-api.js:355:31)
    at FileApiDriverOneDrive.get (C:\Program Files\Joplin\resources\app.asar\lib\file-api-driver-onedrive.js:110:37)
    at C:\Program Files\Joplin\resources\app.asar\lib\file-api.js:250:42
    at tryAndRepeat (C:\Program Files\Joplin\resources\app.asar\lib\file-api.js:38:25)
    at FileApi.get (C:\Program Files\Joplin\resources\app.asar\lib\file-api.js:250:10)
    at MigrationHandler.<anonymous> (C:\Program Files\Joplin\resources\app.asar\lib\services\synchronizer\MigrationHandler.js:40:56)
    at Generator.next (<anonymous>)
    at C:\Program Files\Joplin\resources\app.asar\lib\services\synchronizer\MigrationHandler.js:8:71"
```
## Some opinion

Seems related to Javascript with bad support for including Chinese character in url (or maybe also with other i18n character,not tested).

**Comment by gsongsong** [comment]
Sorry, but I want to bump it up. I am using OneDrive for Business and having the same issue.
