### ISSUE TITLE
App launch and termination errors on MacOs Mojave

### ISSUE THREAD

**Issue by 707** [laurent22/joplin#3968]
## Environment

Joplin version: 1.2.6 (prod, darwin)
Platform:  MacOs Mojave 10.14.6
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes
Revision: f5f117c (master)

## Steps to reproduce

1. Proceed to exit Joplin
2. Joplin gets stuck and does not exit
3. Proceed to force close Joplin
4. Proceed to open Joplin

## Describe what you expected to happen
Joplin should exit without the need for a force close.

## Logfile
When relaunching the app everytime, the error message dialog box shows this.

Uncaught Exception:
RangeError [ERR_OUT_OF_RANGE]: The value of "err" is out of range. It must be a negative integer. Received 536870212
    at Object.getSystemErrorName (util.js:220:11)
    at exceptionWithHostPort (internal/errors.js:495:21)
    at internalConnect (net.js:907:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:301:12)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1050:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:65:10)

**Comment by 707** [comment]
Just an update that the issue still persists as of version 1.3.18 (prod, darwin) with the error dialog box message showing:

> Uncaught Exception:
RangeError [ERR_OUT_OF_RANGE]: The value of "err" is out of range. It must be a negative integer. Received 536870212
    at Object.getSystemErrorName (util.js:220:11)
    at exceptionWithHostPort (internal/errors.js:495:21)
    at internalConnect (net.js:907:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:301:12)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1050:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:65:10)

**Comment by 707** [comment]
Issue still persists as of Joplin 1.4.19 (prod, darwin).
