### ISSUE TITLE
Joplin upgrade fails

### ISSUE THREAD

**Issue by alexriabtsev** [laurent22/joplin#3972]
## Environment

Joplin version: 1.2.6 (1.2.6.2812)
Platform: desktop
OS specifics: macOS Big Sur

## Steps to reproduce

1. Getting notification that Joplin needs to be upgraded
2. Clicking
3. Getting an error below

## Describe what you expected to happen
Error
The sync target could not be upgraded due to an error. For support, please copy the complete content of this page and paste it in the forum: https://discourse.joplinapp.org/

The full error was:

Cannot use 'in' operator to search for 'd:multistatus' in null

TypeError: Cannot use 'in' operator to search for 'd:multistatus' in null
    at WebDavApi.valueFromJson (/Applications/Joplin.app/Contents/Resources/app.asar/lib/WebDavApi.js:144:72)
    at WebDavApi.arrayFromJson (/Applications/Joplin.app/Contents/Resources/app.asar/lib/WebDavApi.js:182:15)
    at FileApiDriverWebDav.list (/Applications/Joplin.app/Contents/Resources/app.asar/lib/file-api-driver-webdav.js:136:32)
    at async tryAndRepeat (/Applications/Joplin.app/Contents/Resources/app.asar/lib/file-api.js:38:19)
    at async FileApi.list (/Applications/Joplin.app/Contents/Resources/app.asar/lib/file-api.js:196:18)

## Logfile
No menu called "Open profile directory"

**Comment by laurent22** [comment]
If you go to `~/.config/joplin-desktop` you'll find the log file and normally it should contain info about the request that fails and its response. Could you post this here? And what is your WebDAV server?

**Comment by alexriabtsev** [comment]
there are 4 of them 
[log-autoupdater.txt](https://github.com/laurent22/joplin/files/5430914/log-autoupdater.txt)
[log-clipper.txt](https://github.com/laurent22/joplin/files/5430915/log-clipper.txt)
[log-database.txt](https://github.com/laurent22/joplin/files/5430916/log-database.txt)

log.txt is 33 MB and can't be attached here

**Comment by laurent22** [comment]
> log.txt is 33 MB and can't be attached here

and this is what's needed. Could you just cut the last lines at about the time the bug happened?

**Comment by alexriabtsev** [comment]
2020-10-23 11:21:14: "Running background sync on timer..."
2020-10-23 11:21:14: "Preparing scheduled sync"
2020-10-23 11:21:14: "Starting scheduled sync"
2020-10-23 11:21:14: "Synchronisation is already in progress. State: in_progress"
2020-10-23 11:25:05: "Error: Cannot acquire sync lock: either the lock could be written but not read back. Or it was expired before it was read again.
Error: Cannot acquire sync lock: either the lock could be written but not read back. Or it was expired before it was read again.
    at LockHandler.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/lib/services/synchronizer/LockHandler.js:170:31)
    at Generator.next (<anonymous>)
    at fulfilled (/Applications/Joplin.app/Contents/Resources/app.asar/lib/services/synchronizer/LockHandler.js:5:58)"
2020-10-23 11:25:05: "Req 11:20:02: PROPFIND https://nc.nl.tab.digital/remote.php/dav/files/alex.riabtsev@protonmail.com/locks/ {"headers":{"Depth":1,"Authorization":"********","If-None-Match":"JoplinIgnore-3775","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","timeout":120000,"maxRetry":0}"
2020-10-23 11:25:05: "Res 11:20:02: "
2020-10-23 11:25:05: "Req 11:20:13: PROPFIND https://nc.nl.tab.digital/remote.php/dav/files/alex.riabtsev@protonmail.com/locks/ {"headers":{"Depth":1,"Authorization":"********","If-None-Match":"JoplinIgnore-50576","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","timeout":120000,"maxRetry":0}"
2020-10-23 11:25:05: "Res 11:20:13: "
2020-10-23 11:25:05: "Req 11:20:13: PROPFIND https://nc.nl.tab.digital/remote.php/dav/files/alex.riabtsev@protonmail.com/locks/ {"headers":{"Depth":1,"Authorization":"********","If-None-Match":"JoplinIgnore-55182","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","timeout":120000,"maxRetry":0}"
2020-10-23 11:25:05: "Res 11:20:13: "
2020-10-23 11:25:05: "Req 11:20:13: DELETE https://nc.nl.tab.digital/remote.php/dav/files/alex.riabtsev@protonmail.com/locks/exclusive_desktop_f2e5f508c9fa4f5bb6e47b9bba5c813f.json {"headers":{"Authorization":"********","If-None-Match":"JoplinIgnore-53230","User-Agent":"Joplin/1.0"},"timeout":120000,"maxRetry":0}"
2020-10-23 11:25:05: "Res 11:20:13: "
2020-10-23 11:25:05: "Req 11:21:41: PROPFIND https://nc.nl.tab.digital/remote.php/dav/files/alex.riabtsev@protonmail.com/locks/ {"headers":{"Depth":1,"Authorization":"********","If-None-Match":"JoplinIgnore-87760","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","timeout":120000,"maxRetry":0}"
2020-10-23 11:25:05: "Res 11:21:41: "
2020-10-23 11:25:05: "Req 11:21:41: PROPFIND https://nc.nl.tab.digital/remote.php/dav/files/alex.riabtsev@protonmail.com/locks/ {"headers":{"Depth":1,"Authorization":"********","If-None-Match":"JoplinIgnore-13058","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","timeout":120000,"maxRetry":0}"
2020-10-23 11:25:05: "Res 11:21:41: <!DOCTYPE html>
<html class="ng-csp" data-placeholder-focus="false" lang="en" data-locale="en" >
	<head
 data-requesttoken="">
		<meta charset="utf-8">
		<title>
		Nextcloud		</title>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
				<meta name="apple-itunes-app" content="app-id=1125420102">
				<meta name="theme-color" content="#0082c9">
		<link rel="icon" href="/core/img/favicon.ico">
		<link rel="apple-touch-icon" href="/core/img/favicon-touch.png">
		<link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#0082c9">
		<link rel="manifest" href="/apps/theming/manifest?v=2">
		<link rel="stylesheet" href="/core/css/guest.css?v=1734b012-2">
		<script nonce="QkREWXVsRkxFYzJzQUlmNjZrQmhhUGQrYnpsdWlPdUQ1RjBwNUZsNUxqZz06UVZHWjB6WUtXb2ZjVnUycXVDTXVLNUF3VzJvRzI0ekswalZDeXhKTVlGcz0=" defer src="/core/js/dist/main.js?v=1734b012-2"></script>
<script nonce="QkREWXVsRkxFYzJzQUlmNjZrQmhhUGQrYnpsdWlPdUQ1RjBwNUZsNUxqZz06UVZHWjB6WUtXb2ZjVnUycXVDTXVLNUF3VzJvRzI0ekswalZDeXhKTVlGcz0=" defer src="/js/core/merged-template-prepend.js?v=1734b012-2"></script>
<script nonce="QkREWXVsRkxFYzJzQUlmNjZrQmhhUGQrYnpsdWlPdUQ1RjBwNUZsNUxqZz06UVZHWjB6WUtXb2ZjVnUycXVDTXVLNUF3VzJvRzI0ekswalZDeXhKTVlGcz0=" defer src="/core/search/js/search.js?v=1734b012-2"></script>
<script nonce="QkREWXVsRkxFYzJzQUlmNjZrQmhhUGQrYnpsdWlPdUQ1RjBwNUZsNUxqZz06UVZHWjB6WUtXb2ZjVnUycXVDTXVLNUF3VzJvRzI0ekswalZDeXhKTVlGcz0=" defer src="/core/search/js/searchprovider.js?v=1734b012-2"></script>
<script nonce="QkREWXVsRkxFYzJzQUlmNjZrQmhhUGQrYnpsdWlPdUQ1RjBwNUZsNUxqZz06UVZHWjB6WUtXb2ZjVnUycXVDTXVLNUF3VzJvRzI0ekswalZDeXhKTVlGcz0=" defer src="/core/js/files/fileinfo.js?v=1734b012-2"></script>
<script nonce="QkREWXVsRkxFYzJzQUlmNjZrQmhhUGQrYnpsdWlPdUQ1RjBwNUZsNUxqZz06UVZHWjB6WUtXb2ZjVnUycXVDTXVLNUF3VzJvRzI0ekswalZDeXhKTVlGcz0=" defer src="/core/js/files/client.js?v=1734b012-2"></script>
			</head>
	<body id="body-login">
		<noscript>
	<div id="nojavascript">
		<div>
			This application requires JavaScript for correct operation. Please <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">enable JavaScript</a> and reload the page.		</div>
	</div>
</noscript>
				<div class="wrapper">
			<div class="v-align">
									<header role="banner">
						<div id="header">
							<div class="logo">
								<h1 class="hidden-visually">
									Nextcloud								</h1>
																	<img src="/core/img/logo/logo.svg?v=6ba72f0e6e9358eb7fcd0f297c2bd0318c72f6e6"/>
															</div>
						</div>
					</header>
								<main>
					<div class="error error-wide">
	<h2>Internal Server Error</h2>
	<p>The server was unable to complete your request.</p>
	<p>If this happens again, please send the technical details below to the server administrator.</p>
	<p>More details can be found in the server log.</p>

	<h3>Technical details</h3>
	<ul>
		<li>Remote Address: 188.163.81.103</li>
		<li>Request ID: VDzrnRhhvjYSgE7wlBns</li>
			</ul>

	</div>
				</main>
			</div>
		</div>
		<footer role="contentinfo">
			<p class="info">
				<a href="https://nextcloud.com" target="_blank" rel="noreferrer noopener">Nextcloud</a> – a safe home for all your data			</p>
		</footer>
	</body>
</html>
"
2020-10-23 11:25:05: "Req 11:21:49: PROPFIND https://nc.nl.tab.digital/remote.php/dav/files/alex.riabtsev@protonmail.com/locks/ {"headers":{"Depth":1,"Authorization":"********","If-None-Match":"JoplinIgnore-15120","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","timeout":120000,"maxRetry":0}"
2020-10-23 11:25:05: "Res 11:21:49: "
2020-10-23 11:25:05: "Req 11:21:49: PROPFIND https://nc.nl.tab.digital/remote.php/dav/files/alex.riabtsev@protonmail.com/locks/ {"headers":{"Depth":1,"Authorization":"********","If-None-Match":"JoplinIgnore-51678","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","timeout":120000,"maxRetry":0}"
2020-10-23 11:25:05: "Res 11:21:49: "
2020-10-23 11:25:05: "Req 11:22:59: PROPFIND https://nc.nl.tab.digital/remote.php/dav/files/alex.riabtsev@protonmail.com/locks/ {"headers":{"Depth":1,"Authorization":"********","If-None-Match":"JoplinIgnore-30633","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","timeout":120000,"maxRetry":0}"
2020-10-23 11:25:05: "Res 11:22:59: <?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns"><d:response><d:href>/remote.php/dav/files/alex.riabtsev@protonmail.com/locks/</d:href><d:propstat><d:prop><d:getlastmodified>Fri, 23 Oct 2020 08:18:39 GMT</d:getlastmodified><d:resourcetype><d:collection/></d:resourcetype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/remote.php/dav/files/alex.riabtsev@protonmail.com/locks/exclusive_desktop_f2e5f508c9fa4f5bb6e47b9bba5c813f.json</d:href><d:propstat><d:prop><d:getlastmodified>Fri, 23 Oct 2020 08:18:29 GMT</d:getlastmodified><d:resourcetype/></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/remote.php/dav/files/alex.riabtsev@protonmail.com/locks/sync_desktop_f2e5f508c9fa4f5bb6e47b9bba5c813f.json</d:href><d:propstat><d:prop><d:getlastmodified>Fri, 23 Oct 2020 08:18:29 GMT</d:getlastmodified><d:resourcetype/></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>"
2020-10-23 11:25:05: "Req 11:22:59: PROPFIND https://nc.nl.tab.digital/remote.php/dav/files/alex.riabtsev@protonmail.com/locks/ {"headers":{"Depth":1,"Authorization":"********","If-None-Match":"JoplinIgnore-47139","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","timeout":120000,"maxRetry":0}"
2020-10-23 11:25:05: "Res 11:22:59: <?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns"><d:response><d:href>/remote.php/dav/files/alex.riabtsev@protonmail.com/locks/</d:href><d:propstat><d:prop><d:getlastmodified>Fri, 23 Oct 2020 08:18:39 GMT</d:getlastmodified><d:resourcetype><d:collection/></d:resourcetype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/remote.php/dav/files/alex.riabtsev@protonmail.com/locks/exclusive_desktop_f2e5f508c9fa4f5bb6e47b9bba5c813f.json</d:href><d:propstat><d:prop><d:getlastmodified>Fri, 23 Oct 2020 08:18:29 GMT</d:getlastmodified><d:resourcetype/></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/remote.php/dav/files/alex.riabtsev@protonmail.com/locks/sync_desktop_f2e5f508c9fa4f5bb6e47b9bba5c813f.json</d:href><d:propstat><d:prop><d:getlastmodified>Fri, 23 Oct 2020 08:18:29 GMT</d:getlastmodified><d:resourcetype/></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>"
2020-10-23 11:25:05: "Req 11:25:05: DELETE https://nc.nl.tab.digital/remote.php/dav/files/alex.riabtsev@protonmail.com/locks/sync_desktop_f2e5f508c9fa4f5bb6e47b9bba5c813f.json {"headers":{"Authorization":"********","If-None-Match":"JoplinIgnore-87735","User-Agent":"Joplin/1.0"},"timeout":120000,"maxRetry":0}"
2020-10-23 11:25:05: "Res 11:25:05: "
2020-10-23 11:25:05: "Operations completed: "
2020-10-23 11:25:05: "Total folders: 8"
2020-10-23 11:25:05: "Total notes: 11288"
2020-10-23 11:25:05: "Total resources: 11392"
2020-10-23 11:25:05: "There was some errors:"
2020-10-23 11:25:05: "Error: Cannot acquire sync lock: either the lock could be written but not read back. Or it was expired before it was read again.
Error: Cannot acquire sync lock: either the lock could be written but not read back. Or it was expired before it was read again.
    at LockHandler.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/lib/services/synchronizer/LockHandler.js:170:31)
    at Generator.next (<anonymous>)
    at fulfilled (/Applications/Joplin.app/Contents/Resources/app.asar/lib/services/synchronizer/LockHandler.js:5:58)"

**Comment by laurent22** [comment]
Unfortunately that looks like a misconfigured server as the request is valid and works in other servers, but on this one:

<h2>Internal Server Error</h2>
	<p>The server was unable to complete your request.</p>
	<p>If this happens again, please send the technical details below to the server administrator.</p>
	<p>More details can be found in the server log.</p>

* * *

So as the error message say, the next step would be to check the server logs and fix the configuration.
