### ISSUE TITLE
Problem syncing on Mac with joplin-desktop and webDAV

### ISSUE THREAD

**Issue by thatkraftkid** [laurent22/joplin#399]
### Operating system

- macOS

### Application

- Desktop

Hi,
I have set up Joplin on my work computer syncing via webDAV through Namecheap (which hosts a couple of my webpages). I've imported all my Evernote notes (in the neighborhood of 3000 items -notes, tags, and folders). Everything seems to have uploaded fine, and I have been able to sync with my iPhone (though it crashed a few times before it downloaded everything). When I try to sync to my home computer, it will always hang at a certain point, as though it hits a file it doesn't like. It will always show "Fetched items: 604/100" and stop after a while. When I enabled debugging mode, 
I keep seeing this error: "Error: getaddrinfo ENOTFOUND" followed by the URL of my webdav server listed twice. I've deleted the app and the ~/.config/joplin-desktop folder several times, and even created a new webDAV directory to start over fresh, and the same thing happens (it just hangs at a different number out of 1000, but it doesn't seem to be the same file causing the trouble, but I didn't save the previous config folders). After the ENOTFOUND error, it then lists this: 

 at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)"
2018-04-09 20:32:35: "Sync: finished: Synchronisation finished [1523319825277]"
2018-04-09 20:32:35: "Reducer action", "SYNC_REPORT_UPDATE"
2018-04-09 20:32:35: "Operations completed: "
2018-04-09 20:32:35: "fetchingTotal: 1000"
2018-04-09 20:32:35: "fetchingProcessed: 604"
2018-04-09 20:32:35: "createLocal: 1"
2018-04-09 20:32:36: "Total folders: 7"
2018-04-09 20:32:36: "Total notes: 596"
2018-04-09 20:32:36: "Total resources: 0"
2018-04-09 20:32:36: "Reducer action", "SYNC_COMPLETED"
2018-04-09 20:32:36: "Setting up recurrent sync with interval 1800"

and then stops. This is a Macbook running Sierra. Last week, I wiped it, did a fresh install of Sierra and restored everything from Time Machine, but that was before I installed Joplin.

**Comment by thatkraftkid** [comment]
I managed to get around the problem. Namecheap lets you mount the webDAV server on your desktop, so I did that, set my Joplin prefs to sync to a local  directory (that mounted drive), let it finish, then changed the settings back to the webDAV URL, and the sync completed fine. Not sure what was hanging it up, but all seems well.
