### ISSUE TITLE
CLI version Install fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by Sensanaty** [laurent22/joplin#3996]
## Environment

Joplin version: 1.2.6
Platform: Linux
OS specifics: Ubuntu 20.04, Node v 15.0.1, npm v 7.0.3

## Steps to reproduce

1. Running `npm install -g joplin` throws an error. I also tried the `NPM_CONFIG_PREFIX` command, and also tried running `npm install --unsafe-perm`, to the same errors

## Describe what you expected to happen

For Joplin to install

## Logfile

<details>
    <summary>Console output of `npm install -g --unsafe-perm joplin`</summary>

```
❯ npm install -g --unsafe-perm joplin
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated jssha@2.4.2: jsSHA versions < 3.0.0 will no longer receive feature updates
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /home/sensanaty/.nvm/versions/node/v15.0.1/lib/node_modules/joplin/node_modules/sqlite3
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! make: Entering directory '/home/sensanaty/.nvm/versions/node/v15.0.1/lib/node_modules/joplin/node_modules/sqlite3/build'
npm ERR!   ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c
npm ERR! make: Leaving directory '/home/sensanaty/.nvm/versions/node/v15.0.1/lib/node_modules/joplin/node_modules/sqlite3/build'
npm ERR! Failed to execute '/home/sensanaty/.nvm/versions/node/v15.0.1/bin/node /home/sensanaty/.nvm/versions/node/v15.0.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/sensanaty/.nvm/versions/node/v15.0.1/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v88-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/sensanaty/.nvm/versions/node/v15.0.1/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v88-linux-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.11.0
npm ERR! node-pre-gyp info using node@15.0.1 | linux | x64
npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download 
npm ERR! node-pre-gyp info check checked for "/home/sensanaty/.nvm/versions/node/v15.0.1/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v88-linux-x64/node_sqlite3.node" (not found)
npm ERR! node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v88-linux-x64.tar.gz
npm ERR! node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v88-linux-x64.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v88-linux-x64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and node@15.0.1 (node-v88 ABI, glibc) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v88-linux-x64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.0.1 | linux | x64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.0.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.5 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/sensanaty/.nvm/versions/node/v15.0.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/sensanaty/.nvm/versions/node/v15.0.1/lib/node_modules/joplin/node_modules/sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/sensanaty/.nvm/versions/node/v15.0.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/sensanaty/.cache/node-gyp/15.0.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/sensanaty/.cache/node-gyp/15.0.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/sensanaty/.nvm/versions/node/v15.0.1/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/sensanaty/.cache/node-gyp/15.0.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/sensanaty/.nvm/versions/node/v15.0.1/lib/node_modules/joplin/node_modules/sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.0.1 | linux | x64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! /bin/sh: 1: python: not found
npm ERR! make: *** [deps/action_before_build.target.mk:13: Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c] Error 127
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/sensanaty/.nvm/versions/node/v15.0.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:327:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:277:12)
npm ERR! gyp ERR! System Linux 5.4.0-52-generic
npm ERR! gyp ERR! command "/home/sensanaty/.nvm/versions/node/v15.0.1/bin/node" "/home/sensanaty/.nvm/versions/node/v15.0.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/sensanaty/.nvm/versions/node/v15.0.1/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v88-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/sensanaty/.nvm/versions/node/v15.0.1/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v88-linux-x64" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v88"
npm ERR! gyp ERR! cwd /home/sensanaty/.nvm/versions/node/v15.0.1/lib/node_modules/joplin/node_modules/sqlite3
npm ERR! gyp ERR! node -v v15.0.1
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/home/sensanaty/.nvm/versions/node/v15.0.1/bin/node /home/sensanaty/.nvm/versions/node/v15.0.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/sensanaty/.nvm/versions/node/v15.0.1/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v88-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/sensanaty/.nvm/versions/node/v15.0.1/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v88-linux-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/sensanaty/.nvm/versions/node/v15.0.1/lib/node_modules/joplin/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:327:20)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1048:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
npm ERR! node-pre-gyp ERR! System Linux 5.4.0-52-generic
npm ERR! node-pre-gyp ERR! command "/home/sensanaty/.nvm/versions/node/v15.0.1/bin/node" "/home/sensanaty/.nvm/versions/node/v15.0.1/lib/node_modules/joplin/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /home/sensanaty/.nvm/versions/node/v15.0.1/lib/node_modules/joplin/node_modules/sqlite3
npm ERR! node-pre-gyp ERR! node -v v15.0.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.11.0
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sensanaty/.npm/_logs/2020-10-29T09_42_07_938Z-debug.log
```

</details>

**Comment by roman-r-m** [comment]
This seems to be the problem:
```
npm ERR! /bin/sh: 1: python: not found
```

**Comment by Sensanaty** [comment]
Ah i forgot this was a new install

Symlinking `python3` to `python` solved it

`sudo ln -s /usr/bin/python3 /usr/bin/python`
