### ISSUE TITLE
Joplin encountered a fatal error and could not continue. Help Me!

### ISSUE THREAD

**Issue by yimisunrise** [laurent22/joplin#4028]
Error
Joplin encountered a fatal error and could not continue. To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

Message
Maximum call stack size exceeded

Version info
Joplin for Desktop

Copyright © 2016-2020 Laurent Cozic
Joplin 1.2.6 (prod, linux)

客户端 ID: 0fdc23d031bd4d89941f51da8b284e5f
同步版本: 2
配置文件版本: 34
密钥链支持: 否

修订: f5f117c (master)
Stack trace
RangeError: Maximum call stack size exceeded
    at String.match (<anonymous>)
    at StringStream.match (/tmp/.mount_JoplinO4Cfba/resources/app.asar/node_modules/codemirror/lib/codemirror.js:869:47)
    at Object.<anonymous> (/tmp/.mount_JoplinO4Cfba/resources/app.asar/node_modules/codemirror/mode/markdown/markdown.js:696:14)
    at Object.token (/tmp/.mount_JoplinO4Cfba/resources/app.asar/node_modules/codemirror/mode/markdown/markdown.js:855:20)
    at Object.token (/tmp/.mount_JoplinO4Cfba/resources/app.asar/gui/NoteEditor/NoteBody/CodeMirror/utils/useJoplinMode.js:85:43)
    at readToken (/tmp/.mount_JoplinO4Cfba/resources/app.asar/node_modules/codemirror/lib/codemirror.js:1168:24)
    at runMode (/tmp/.mount_JoplinO4Cfba/resources/app.asar/node_modules/codemirror/lib/codemirror.js:1225:36)
    at highlightLine (/tmp/.mount_JoplinO4Cfba/resources/app.asar/node_modules/codemirror/lib/codemirror.js:1071:5)
    at getLineStyles (/tmp/.mount_JoplinO4Cfba/resources/app.asar/node_modules/codemirror/lib/codemirror.js:1115:20)
    at buildLineContent (/tmp/.mount_JoplinO4Cfba/resources/app.asar/node_modules/codemirror/lib/codemirror.js:1748:40)
Component stack

    in ForwardRef(CodeMirror) (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in NoteEditor (created by Connect(NoteEditor))
    in Connect(NoteEditor) (created by ResizableLayout)
    in div (created by ResizableLayout)
    in div (created by ResizableLayout)
    in div (created by ResizableLayout)
    in ResizableLayout (created by MainScreenComponent)
    in div (created by MainScreenComponent)
    in MainScreenComponent (created by Connect(MainScreenComponent))
    in Connect(MainScreenComponent) (created by NavigatorComponent)
    in div (created by NavigatorComponent)
    in NavigatorComponent (created by Connect(NavigatorComponent))
    in Connect(NavigatorComponent) (created by RootComponent)
    in ThemeProvider (created by RootComponent)
    in StyleSheetManager (created by RootComponent)
    in RootComponent (created by Connect(RootComponent))
    in Connect(RootComponent)
    in ErrorBoundary
    in Provider

**Comment by CalebJohn** [comment]
@yimisunrise Would it be possible for you to provide us with the note that caused this crash? It seems it is a specific note that caused it.

**Comment by yimisunrise** [comment]
> @yimisunrise Would it be possible for you to provide us with the note that caused this crash? It seems it is a specific note that caused it.

I'm sorry!I've been busy lately and haven't been paying attention to your information.This problem was probably caused by special characters, when I copied a large chunk of web page text into the edit area.I then solved this problem by removing the ~ /.config/Joplin directories.

**Comment by CalebJohn** [comment]
@yimisunrise no worries, glad to see you were able to get things working.
Thanks for the information, I'm sure we'll eventually be able to replicate and fix this!
