### ISSUE TITLE
Sync crash with Joplin version 1.3.15

### ISSUE THREAD

**Issue by searjeant** [laurent22/joplin#4051]
## Environment

Joplin version: 1.3.15 (prod, win32)
Platform: Windows
OS specifics: Windows 10 Enterprise, Version 10.0.17763 Build 17763

## Steps to reproduce

1. Installed Joplin portable 1.3.15 on Win 10 machine with no existing local Joplin profile. I have notes in S3 which I will sync down to this machine.
2. Start client. All appears normal - welcome messages etc. all present. 
3. Go to settings. Configure sync with my S3 bucket/account/secret. Check connection - success is reported.
4. Back to the application. Click Synchronise.
5. Sync appears to be working normally - I can see folders / notes appearing in the UI.
6. Then suddenly the application window contents is replaced with the following:

```
Error
Joplin encountered a fatal error and could not continue. To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.
Message
Cannot read property 'toLowerCase' of undefined
Version info
Joplin for Desktop

Copyright © 2016-2020 Laurent Cozic
Joplin 1.3.15 (prod, win32)

Client ID: 629b9bbe79284d4387e79a545a6a3ff6
Sync Version: 2
Profile Version: 34
Keychain Supported: No

Revision: 0cc544a95 (master)
Stack trace
TypeError: Cannot read property 'toLowerCase' of undefined
    at C:\Users\rsearg\AppData\Local\Temp\1jpDq5r6O9blCMwLK5H26V58wCO\resources\app.asar\lib\components\shared\side-menu-shared.js:57:18
    at Array.sort (<anonymous>)
    at Object.shared.renderTags (C:\Users\rsearg\AppData\Local\Temp\1jpDq5r6O9blCMwLK5H26V58wCO\resources\app.asar\lib\components\shared\side-menu-shared.js:53:7)
    at SideBarComponent.render (C:\Users\rsearg\AppData\Local\Temp\1jpDq5r6O9blCMwLK5H26V58wCO\resources\app.asar\gui\SideBar\SideBar.js:452:35)
    at finishClassComponent (C:\Users\rsearg\AppData\Local\Temp\1jpDq5r6O9blCMwLK5H26V58wCO\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:17039:31)
    at updateClassComponent (C:\Users\rsearg\AppData\Local\Temp\1jpDq5r6O9blCMwLK5H26V58wCO\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:16994:24)
    at beginWork$1 (C:\Users\rsearg\AppData\Local\Temp\1jpDq5r6O9blCMwLK5H26V58wCO\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:18505:16)
    at HTMLUnknownElement.callCallback (C:\Users\rsearg\AppData\Local\Temp\1jpDq5r6O9blCMwLK5H26V58wCO\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:347:14)
    at Object.invokeGuardedCallbackDev (C:\Users\rsearg\AppData\Local\Temp\1jpDq5r6O9blCMwLK5H26V58wCO\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:397:16)
    at invokeGuardedCallback (C:\Users\rsearg\AppData\Local\Temp\1jpDq5r6O9blCMwLK5H26V58wCO\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:454:31)
Component stack
   in SideBarComponent (created by Connect(SideBarComponent))
    in Connect(SideBarComponent) (created by ResizableLayout)
    in div (created by ResizableLayout)
    in div (created by Resizable)
    in Resizable (created by ResizableLayout)
    in div (created by ResizableLayout)
    in ResizableLayout (created by MainScreenComponent)
    in div (created by MainScreenComponent)
    in MainScreenComponent (created by Connect(MainScreenComponent))
    in Connect(MainScreenComponent) (created by NavigatorComponent)
    in div (created by NavigatorComponent)
    in NavigatorComponent (created by Connect(NavigatorComponent))
    in Connect(NavigatorComponent) (created by RootComponent)
    in ThemeProvider (created by RootComponent)
    in StyleSheetManager (created by RootComponent)
    in RootComponent (created by Connect(RootComponent))
    in Connect(RootComponent)
    in ErrorBoundary
    in Provider
```

**Comment by laurent22** [comment]
That should be fixed in the latest release, if not let met know: https://github.com/laurent22/joplin/releases/tag/v1.3.17

**Comment by searjeant** [comment]
Fix confirmed.  Thank you so much for finding and fixing this so quickly. Joplin has become an essential tool!
