### ISSUE TITLE
SQLITE_ERROR on fresh install "Could not upgrade to database v34"

### ISSUE THREAD

**Issue by ioogithub** [laurent22/joplin#4069]
## Environment

Joplin version:  1.3.18
Platform: Linux
OS specifics: KDE Neon 5.20.1

## Steps to reproduce
1. Install Joplin
2. Enter encryption password
3. Enter sync target infomation and click "Syncronize"
4 Observe the SQL error in the log.

## Describe what you expected to happen
No errors on a fresh Joplin install.

## Logfile
```
2020-11-09 16:14:26: "Converting database to version 34"
2020-11-09 16:14:26: "Could not upgrade to database v34 - fuzzy search will not be used", "Error: Error: SQLITE_ERROR: no such module: spellfix1: CREATE VIRTUAL TABLE notes_spellfix USING spellfix1
Code: SQLITE_ERROR
Error: Error: SQLITE_ERROR: no such module: spellfix1: CREATE VIRTUAL TABLE notes_spellfix USING spellfix1
    at DatabaseDriverNode.sqliteErrorToJsError (/tmp/.mount_JoplinsdE83d/resources/app.asar/lib/database-driver-node.js:21:18)
    at JoplinDatabase.sqliteErrorToJsError (/tmp/.mount_JoplinsdE83d/resources/app.asar/lib/database.js:25:24)
    at JoplinDatabase.tryCall (/tmp/.mount_JoplinsdE83d/resources/app.asar/lib/database.js:113:17)"
2020-11-09 16:14:26: "Migration failed with fallback and will not be repeated - saving version number"
2020-11-09 16:14:26: "New version: 34. Previously recorded version: 0"
```

**Comment by laurent22** [comment]
This is an error in the log isn't it? And it says "Migration failed with fallback", so you can ignore it.
