### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by xplosionmind** [laurent22/joplin#4129]
## Environment

Joplin version: 1.3.8
Platform: MacOS
OS specifics: 11.0.1

## Description

When performing a search (all of a sudden, after having performed other several ones) the app crashes.   
upon reopening, the issue happens again as soon as I search

## Logfile

```
Error
Joplin encountered a fatal error and could not continue. To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

Message
Maximum call stack size exceeded

Version info
Joplin for Desktop

Copyright © 2016-2020 Laurent Cozic
Joplin 1.3.18 (prod, darwin)

Client ID: e9ed7835451249a09f659bb49aa49e4e
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: 6b75485 (master)
Stack trace
RangeError: Maximum call stack size exceeded
    at String.match (<anonymous>)
    at StringStream.match (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/codemirror/lib/codemirror.js:869:47)
    at Object.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/codemirror/mode/markdown/markdown.js:696:14)
    at Object.token (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/codemirror/mode/markdown/markdown.js:855:20)
    at Object.token (/Applications/Joplin.app/Contents/Resources/app.asar/gui/NoteEditor/NoteBody/CodeMirror/utils/useJoplinMode.js:86:43)
    at readToken (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/codemirror/lib/codemirror.js:1168:24)
    at runMode (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/codemirror/lib/codemirror.js:1225:36)
    at highlightLine (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/codemirror/lib/codemirror.js:1071:5)
    at getLineStyles (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/codemirror/lib/codemirror.js:1115:20)
    at buildLineContent (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/codemirror/lib/codemirror.js:1748:40)
Component stack

    in NoteEditor (created by Connect(NoteEditor))
    in Connect(NoteEditor) (created by ResizableLayout)
    in div (created by ResizableLayout)
    in div (created by ResizableLayout)
    in div (created by ResizableLayout)
    in ResizableLayout (created by MainScreenComponent)
    in div (created by MainScreenComponent)
    in MainScreenComponent (created by Connect(MainScreenComponent))
    in Connect(MainScreenComponent) (created by NavigatorComponent)
    in div (created by NavigatorComponent)
    in NavigatorComponent (created by Connect(NavigatorComponent))
    in Connect(NavigatorComponent) (created by RootComponent)
    in ThemeProvider (created by RootComponent)
    in StyleSheetManager (created by RootComponent)
    in RootComponent (created by Connect(RootComponent))
    in Connect(RootComponent)
    in ErrorBoundary
    in Provider
```

**Comment by laurent22** [comment]
It's likely that it's displaying a particular note when the app crashes, can you find out what note it is and, if so could you export it as JEX or copy and paste the Markdown here? Also does it happen with v1.4 too?

**Comment by laurent22** [comment]
@CalebJohn, it seems the app call stack reaches the limit on that line: 

https://github.com/laurent22/joplin/blob/717b8da1f89db2d1ef67e497a34d5db05c5bb370/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useJoplinMode.ts#L95

Can you think of anything in here that could cause an infinite loop?

**Comment by CalebJohn** [comment]
No, that line calls in to some CodeMirror functions, it shouldn't be able to recurse. It would be helpful to get an example of a note that causes this as this seems that is a bug in CodeMirror itself.

**Comment by CalebJohn** [comment]
Looks like #4028 had the same error.

**Comment by xplosionmind** [comment]
Pardon me, I stopped using Joplin in these very days so I can't help you anymore.

**Comment by mptpro** [comment]
I just started having the same issue. I was using Joplin (moving a note, I think) and this error poped-up. After closing the app and re-launching I still get the error. Re-booted still getting it.


Error
Joplin encountered a fatal error and could not continue. To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

Message
Maximum call stack size exceeded

Version info
Joplin for Desktop

Copyright © 2016-2021 Laurent Cozic
Joplin 1.7.11 (prod, darwin)

Client ID: 5c67d72cecd245f29e0317efdc1eaa10
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: f560563 (master)
Stack trace
RangeError: Maximum call stack size exceeded
    at String.match (<anonymous>)
    at StringStream.match (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/codemirror/lib/codemirror.js:869:47)
    at Object.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/codemirror/mode/markdown/markdown.js:696:14)
    at Object.token (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/codemirror/mode/markdown/markdown.js:855:20)
    at Object.token (/Applications/Joplin.app/Contents/Resources/app.asar/gui/NoteEditor/NoteBody/CodeMirror/utils/useJoplinMode.js:86:43)
    at readToken (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/codemirror/lib/codemirror.js:1168:24)
    at runMode (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/codemirror/lib/codemirror.js:1225:36)
    at highlightLine (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/codemirror/lib/codemirror.js:1071:5)
    at getLineStyles (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/codemirror/lib/codemirror.js:1115:20)
    at buildLineContent (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/codemirror/lib/codemirror.js:1748:40)
Component stack

    in ForwardRef(CodeMirror) (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in NoteEditor (created by Connect(NoteEditor))
    in Connect(NoteEditor) (created by ResizableLayout)
    in div (created by styled.div)
    in styled.div (created by ResizableLayout)
    in div (created by ResizableLayout)
    in div (created by ResizableLayout)
    in ResizableLayout (created by MainScreenComponent)
    in div (created by MainScreenComponent)
    in MainScreenComponent (created by Connect(MainScreenComponent))
    in Connect(MainScreenComponent) (created by NavigatorComponent)
    in div (created by NavigatorComponent)
    in NavigatorComponent (created by Connect(NavigatorComponent))
    in Connect(NavigatorComponent) (created by RootComponent)
    in ThemeProvider (created by RootComponent)
    in StyleSheetManager (created by RootComponent)
    in RootComponent (created by Connect(RootComponent))
    in Connect(RootComponent)
    in ErrorBoundary
    in Provider

**Comment by CalebJohn** [comment]
@mptpro would it be possible for you to export that note and share it with us (right click and export to JEX)? If not, maybe a description would help? For example, do you use special unicode characters? Does it contain a lot of math, etc?

**Comment by mptpro** [comment]
Thanks fir your respond @CalebJohn .  I don't remember which note it was, however I do have a lot of notes with embedded images as I imported 600+ notes from Keep-->Evernote file--> Joplin and those embedded images have a LOT of code. I suspect that is the problem. It is an arduous process has I have to "cut" each image, paste it into a Google Doc, download it, then attached it to the note, then delete the embedded image.
