### ISSUE TITLE
No notification on MacOS 10.15.7?

### ISSUE THREAD

**Issue by PatrickDanes** [laurent22/joplin#4142]
Dear all,

first of all, many thanks to the developers of this wonderful software!  I have been looking for this kind of tool for so long...  It will advantageously replace a solution that has long brought me little satisfaction.

Everything has worked like a charm during my first tests, except notifications.  I tried to understand the corresponding section of the webpage, browsed a past discussion on https://discourse.joplinapp.org/t/notification-center-mac-does-not-have-joplin/2089/9 and visited ''node-notifier'' github website.  Nevertheless, I haven't dared to install a new version of ''node-notifier'' nor to change the default settings, because I (mistakenly?) understood that notifications should work by default.

I am using MacOS Catalina 10.15.7, Joplin 1.4.12, and here is the contents of ~/.config/joplin-desktop/log.txt between the time when the notification was defined and the time when it should have appeared.  BTW, ''note-notifier'' does not appear in the Notifications page of my laptop Preferences.

My apologies if I wrongly labeled it as a bug.  Best wishes.
--Patrick

    2020-11-26 18:10:04: "CommandService::execute:", "editAlarm", "[]"
    2020-11-26 18:10:14: "Scheduling notification for note 298adfcefe7046e181b26fa9d01a40b8", "{"id":12,"noteId":"298adfcefe7046e181b26fa9d01a40b8","date":"2020-11-26T17:12:00.000Z","title":"bla","body":"bla"}"
    2020-11-26 18:10:14: "AlarmServiceDriverNode::scheduleNotification: Notification 12 with interval: 105806ms"
    2020-11-26 18:10:15: "CommandService::execute:", "synchronize", "[false]"
    2020-11-26 18:10:15: "Preparing scheduled sync"
    2020-11-26 18:10:15: "Starting scheduled sync"
    2020-11-26 18:10:15: "Sync target info:", "{"version":2}"
    2020-11-26 18:10:15: "TaskQueue.stop: syncDownload: waiting for tasks to complete: 0"
    2020-11-26 18:10:15: "TaskQueue.stop: syncDownload: Done, waited for 0"
    2020-11-26 18:10:15: "BasicDelta: Report: {"timestamp":1606408591368,"older":904,"newer":1,"equal":1}"
    2020-11-26 18:10:16: "Operations completed: "
    2020-11-26 18:10:16: "updateRemote: 1"
    2020-11-26 18:10:16: "fetchingTotal: 1"
    2020-11-26 18:10:16: "fetchingProcessed: 1"
    2020-11-26 18:10:16: "Total folders: 4"
    2020-11-26 18:10:16: "Total notes: 9"
    2020-11-26 18:10:16: "Total resources: 868"
    2020-11-26 18:10:16: "Saving settings..."
    2020-11-26 18:10:16: "Settings have been saved."
    2020-11-26 18:10:17: "DecryptionWorker: cannot start because no master key is currently loaded."
    2020-11-26 18:10:24: "SearchEngine: Updating FTS table..."
    2020-11-26 18:10:24: "Saving settings..."
    2020-11-26 18:10:24: "Settings have been saved."
    2020-11-26 18:10:24: "SearchEngine: Updated FTS table in 24ms. Inserted: 1. Deleted: 0"
    2020-11-26 18:12:00: "AlarmServiceDriverNode::scheduleNotification: Triggering notification:", "{"appID":"net.cozic.joplin-desktop","title":"bla","icon":"/Applications/Joplin.app/Contents/Resources/build/icons/512x512.png","message":"bla"}"
    2020-11-26 18:12:00: "AlarmServiceDriverNode::scheduleNotification: node-notifier response:", "Error: Command failed: /var/folders/9_/msgq4c956szggbh0mbw1gnrh0000gn/T/.net.cozic.joplin-desktop.QyQlRU -appID "net.cozic.joplin-desktop" -title "bla" -message "bla" -appIcon "/Applications/Joplin.app/Contents/Resources/build/icons/512x512.png" -timeout "10" -json "true"
    2020-11-26 18:12:00.040 .net.cozic.joplin-desktop.QyQlRU[46225:1896804] No Info.plist file in application bundle or no NSPrincipalClass in the Info.plist file, exiting
    
    Code: 1
    Error: Command failed: /var/folders/9_/msgq4c956szggbh0mbw1gnrh0000gn/T/.net.cozic.joplin-desktop.QyQlRU -appID "net.cozic.joplin-desktop" -title "bla" -message "bla" -appIcon "/Applications/Joplin.app/Contents/Resources/build/icons/512x512.png" -timeout "10" -json "true"
    2020-11-26 18:12:00.040 .net.cozic.joplin-desktop.QyQlRU[46225:1896804] No Info.plist file in application bundle or no NSPrincipalClass in the Info.plist file, exiting
    
        at ChildProcess.exithandler (child_process.js:312:12)
        at ChildProcess.emit (events.js:310:20)
        at ChildProcess.EventEmitter.emit (domain.js:482:12)
        at maybeClose (internal/child_process.js:1021:16)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)", ""

**Comment by laurent22** [comment]
Should be fixed in latest version
