### ISSUE TITLE
macOS app fails to open due to invalid language code "en-IN" while `setSpellCheckerLanguages`

### ISSUE THREAD

**Issue by pqrth** [laurent22/joplin#4146]
macOS app fails to open with fatal error `Could not call remote method 'setSpellCheckerLanguages'`
* `Underlying error: Invalid language code provided: "en-IN" is not a valid language code`

## Environment

Joplin version: 1.4.12
Platform: macOS
OS specifics: 10.15.7

## Steps to reproduce

1. Upgrade to the latest Joplin release, 1.4.12 on macOS: `brew upgrade`
2. Open the app after successful upgrade

## Describe what you expected to happen

**Expected**: The macOS app opens successfully

**Actual**: An error dialog box opens with fatal error and Joplin specific controls in Electron are disabled.

![FCE5DCEA-D1AA-416F-A6DC-33A1B86B8858](https://user-images.githubusercontent.com/6792160/100403535-2b4a3800-3085-11eb-95b4-7429aa2f68e4.png)

## Logfile

```
Fatal error:

Could not call remote method 'setSpellCheckerLanguages'. Check that the method signature is correct. Underlying error: Invalid language code provided: "en-IN" is not a valid language code
Underlying stack: Error: Invalid language code provided: "en-IN" is not a valid language code
    at electron/js2c/browser_init.js:213:7789
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:213:4246)
    at IpcMainImpl.emit (events.js:310:20)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:157:8848)
    at WebContents.emit (events.js:310:20)


Error: Could not call remote method 'setSpellCheckerLanguages'. Check that the method signature is correct. Underlying error: Invalid language code provided: "en-IN" is not a valid language code
Underlying stack: Error: Invalid language code provided: "en-IN" is not a valid language code
    at electron/js2c/browser_init.js:213:7789
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:213:4246)
    at IpcMainImpl.emit (events.js:310:20)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:157:8848)
    at WebContents.emit (events.js:310:20)

    at electron/js2c/browser_init.js:213:7817
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:213:4246)
    at IpcMainImpl.emit (events.js:310:20)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:157:8848)
    at WebContents.emit (events.js:310:20)
```

## Workaround
1. Close the Joplin macOS app
2. Follow the [macOS official docs](https://support.apple.com/en-in/guide/mac-help/mh26684/10.15/mac/10.15#mchlp6f578d0) to change the system language to _English (UK)_.
2. Reopen the Joplin macOS app, the app seems to cache/store the system language for the new spell check feature.
3. Change the system language back to the regional one, say _English (India)_.

**Comment by ersuniljoshi** [comment]
+1, same issue for me as well.

**Comment by laurent22** [comment]
I wonder where en-IN comes from - is "English (India)" in your list of spell checker languages?

**Comment by nfarrar** [comment]
Just got this same issue after running 'brew upgrade' on MacOS 11.0.1.

```
Fatal error:

Could not call remote method 'setSpellCheckerLanguages'. Check that the method signature is correct. Underlying error: Error processing argument at index 0, conversion failure from 
Underlying stack: TypeError: Error processing argument at index 0, conversion failure from 
at electron/js2c/browser_init.js:213:7789
at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:213:4246)
at IpcMainImpl.emit (events.js:310:20)
at WebContents.<anonymous> (electron/js2c/browser_init.js:157:8848)
at WebContents.emit (events.js:310:20)


Error: Could not call remote method 'setSpellCheckerLanguages'. Check that the method signature is correct. Underlying error: Error processing argument at index 0, conversion failure from 
Underlying stack: TypeError: Error processing argument at index 0, conversion failure from 
at electron/js2c/browser_init.js:213:7789
at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:213:4246)
at IpcMainImpl.emit (events.js:310:20)
at WebContents.<anonymous> (electron/js2c/browser_init.js:157:8848)
at WebContents.emit (events.js:310:20)

at electron/js2c/browser_init.js:213:7817
at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:213:4246)
at IpcMainImpl.emit (events.js:310:20)
at WebContents.<anonymous> (electron/js2c/browser_init.js:157:8848)
at WebContents.emit (events.js:310:20)
```

Attempted work-around above, does not work for me.
