### ISSUE TITLE
Joplin 1.4.12 crashes while start, 'for Invalid language code provided: "en-IN" is not a valid language code'

### ISSUE THREAD

**Issue by bhavikbavishi123** [laurent22/joplin#4150]
note that prior version works fine, on upgrade to `1.4.12` fails

```bash
Fatal error:

Could not call remote method 'setSpellCheckerLanguages'. Check that the method signature is correct. Underlying error: Invalid language code provided: "en-IN" is not a valid language code
Underlying stack: Error: Invalid language code provided: "en-IN" is not a valid language code
    at electron/js2c/browser_init.js:213:7789
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:213:4246)
    at IpcMainImpl.emit (events.js:310:20)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:157:8848)
    at WebContents.emit (events.js:310:20)


Error: Could not call remote method 'setSpellCheckerLanguages'. Check that the method signature is correct. Underlying error: Invalid language code provided: "en-IN" is not a valid language code
Underlying stack: Error: Invalid language code provided: "en-IN" is not a valid language code
    at electron/js2c/browser_init.js:213:7789
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:213:4246)
    at IpcMainImpl.emit (events.js:310:20)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:157:8848)
    at WebContents.emit (events.js:310:20)

    at electron/js2c/browser_init.js:213:7817
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:213:4246)
    at IpcMainImpl.emit (events.js:310:20)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:157:8848)
    at WebContents.emit (events.js:310:20)
```

## Environment

Joplin version: 1.4.12
Platform: MacOS
OS specifics: Catalina

<img width="1432" alt="Screenshot 2020-11-27 at 5 56 47 PM" src="https://user-images.githubusercontent.com/24971868/100449437-ee5c6080-30d9-11eb-850b-8eac19728a9b.png">

**Comment by laurent22** [comment]
https://github.com/laurent22/joplin/issues/4146
