### ISSUE TITLE
Sync failed, reason: unable to verify the first certificate

### ISSUE THREAD

**Issue by rexzhang** [laurent22/joplin#4219]
macOS version can not sync to webdav server ,but iOS(10.4.1) version is fine.

my webdev server url: https://rexzhang.myds.me:5006/home/Joplin

## Environment

Joplin version: 
```
Joplin 1.4.19 (prod, darwin)

Client ID: 9b3d22af1ce749ca9059a29e7ee47a82
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: de123ee (master)
```
Platform: x86-64 mbp
OS specifics: macOS 11

## Logfile

```
/Applications/Joplin…n/lib/Logger.js:165 22:16:56: CommandService::execute: synchronize false
/Applications/Joplin…n/lib/Logger.js:165 22:16:56: Preparing scheduled sync
/Applications/Joplin…n/lib/Logger.js:165 22:16:56: Starting scheduled sync
/Applications/Joplin…n/lib/Logger.js:165 22:17:02: Saving settings...
/Applications/Joplin…n/lib/Logger.js:165 22:17:02: Settings have been saved.
/Applications/Joplin…n/lib/Logger.js:165 22:17:22: RevisionService::maintenance: Starting...
/Applications/Joplin…n/lib/Logger.js:165 22:17:22: RevisionService::maintenance: Service is enabled
/Applications/Joplin…n/lib/Logger.js:165 22:17:22: RevisionService::collectRevisions: Created revisions for 0 notes
/Applications/Joplin…n/lib/Logger.js:165 22:17:22: RevisionService::maintenance: Done in 110ms
/Applications/Joplin…n/lib/Logger.js:165 22:17:37: 
FetchError {name: "FetchError", message: "request to https://rexzhang.myds.me:5006/home/Jopl…d, reason: unable to verify the first certificate", type: "system", errno: "UNABLE_TO_VERIFY_LEAF_SIGNATURE", code: "UNABLE_TO_VERIFY_LEAF_SIGNATURE", …}
code: "UNABLE_TO_VERIFY_LEAF_SIGNATURE"
errno: "UNABLE_TO_VERIFY_LEAF_SIGNATURE"
message: "request to https://rexzhang.myds.me:5006/home/Joplin/info.json failed, reason: unable to verify the first certificate"
name: "FetchError"
type: "system"
stack: "FetchError: request to https://rexzhang.myds.me:5006/home/Joplin/info.json failed, reason: unable to verify the first certificate↵    at ClientRequest.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/node-fetch/index.js:133:11)↵    at ClientRequest.emit (events.js:310:20)↵    at ClientRequest.EventEmitter.emit (domain.js:482:12)↵    at TLSSocket.socketErrorListener (_http_client.js:426:9)↵    at TLSSocket.emit (events.js:310:20)↵    at TLSSocket.EventEmitter.emit (domain.js:482:12)↵    at emitErrorNT (internal/streams/destroy.js:92:8)↵    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)↵    at processTicksAndRejections (internal/process/task_queues.js:84:21)"
__proto__: Error
constructor: ƒ FetchError(message, type, systemError)
__proto__: Object
log	@	/Applications/Joplin…n/lib/Logger.js:165
error	@	/Applications/Joplin…in/lib/Logger.js:54
(anonymous)	@	/Applications/Joplin…Synchronizer.js:822
rejected	@	/Applications/Joplin…b/Synchronizer.js:6
Promise.then (async)		
step	@	/Applications/Joplin…b/Synchronizer.js:7
fulfilled	@	/Applications/Joplin…b/Synchronizer.js:5
Promise.then (async)		
step	@	/Applications/Joplin…b/Synchronizer.js:7
(anonymous)	@	/Applications/Joplin…b/Synchronizer.js:8
__awaiter	@	/Applications/Joplin…b/Synchronizer.js:4
start	@	/Applications/Joplin…Synchronizer.js:280
timeoutCallback	@	/Applications/Joplin…lib/registry.js:130
async function (async)		
timeoutCallback	@	/Applications/Joplin…lib/registry.js:100
reg.scheduleSync	@	/Applications/Joplin…lib/registry.js:153
(anonymous)	@	/Applications/Joplin…s/synchronize.js:53
fulfilled	@	/Applications/Joplin…ds/synchronize.js:5
Promise.then (async)		
step	@	/Applications/Joplin…ds/synchronize.js:7
fulfilled	@	/Applications/Joplin…ds/synchronize.js:5
Promise.then (async)		
step	@	/Applications/Joplin…ds/synchronize.js:7
(anonymous)	@	/Applications/Joplin…ds/synchronize.js:8
__awaiter	@	/Applications/Joplin…ds/synchronize.js:4
execute	@	/Applications/Joplin…s/synchronize.js:25
(anonymous)	@	/Applications/Joplin…mmandService.js:141
(anonymous)	@	/Applications/Joplin…CommandService.js:8
__awaiter	@	/Applications/Joplin…CommandService.js:4
execute	@	/Applications/Joplin…mmandService.js:136
onClick	@	/Applications/Joplin…eBar/SideBar.js:415
onClick	@	/Applications/Joplin…utton/Button.js:173
callCallback	@	/Applications/Joplin….development.js:347
invokeGuardedCallbackDev	@	/Applications/Joplin….development.js:397
invokeGuardedCallback	@	/Applications/Joplin….development.js:454
invokeGuardedCallbackAndCatchFirstError	@	/Applications/Joplin….development.js:468
executeDispatch	@	/Applications/Joplin….development.js:600
executeDispatchesInOrder	@	/Applications/Joplin….development.js:622
executeDispatchesAndRelease	@	/Applications/Joplin….development.js:725
executeDispatchesAndReleaseTopLevel	@	/Applications/Joplin….development.js:733
forEachAccumulated	@	/Applications/Joplin….development.js:707
runEventsInBatch	@	/Applications/Joplin….development.js:750
runExtractedPluginEventsInBatch	@	/Applications/Joplin….development.js:881
handleTopLevel	@	/Applications/Joplin…development.js:5901
batchedEventUpdates	@	/Applications/Joplin…development.js:2344
dispatchEventForPluginEventSystem	@	/Applications/Joplin…development.js:5996
dispatchEvent	@	/Applications/Joplin…development.js:6025
unstable_runWithPriority	@	/Applications/Joplin….development.js:643
runWithPriority$2	@	/Applications/Joplin…evelopment.js:11305
discreteUpdates$1	@	/Applications/Joplin…evelopment.js:21672
discreteUpdates	@	/Applications/Joplin…development.js:2359
dispatchDiscreteEvent	@	/Applications/Joplin…development.js:5979
/Applications/Joplin…n/lib/Logger.js:165 22:17:37: Operations completed: 
/Applications/Joplin…n/lib/Logger.js:165 22:17:37: Total folders: 13
/Applications/Joplin…n/lib/Logger.js:165 22:17:37: Total notes: 132
/Applications/Joplin…n/lib/Logger.js:165 22:17:37: Total resources: 272
/Applications/Joplin…n/lib/Logger.js:165 22:17:37: There was some errors:
/Applications/Joplin…n/lib/Logger.js:165 22:17:37: 
FetchError {name: "FetchError", message: "request to https://rexzhang.myds.me:5006/home/Jopl…d, reason: unable to verify the first certificate", type: "system", errno: "UNABLE_TO_VERIFY_LEAF_SIGNATURE", code: "UNABLE_TO_VERIFY_LEAF_SIGNATURE", …}
log	@	/Applications/Joplin…n/lib/Logger.js:165
warn	@	/Applications/Joplin…in/lib/Logger.js:53
(anonymous)	@	/Applications/Joplin…Synchronizer.js:193
fulfilled	@	/Applications/Joplin…b/Synchronizer.js:5
Promise.then (async)		
step	@	/Applications/Joplin…b/Synchronizer.js:7
fulfilled	@	/Applications/Joplin…b/Synchronizer.js:5
Promise.then (async)		
step	@	/Applications/Joplin…b/Synchronizer.js:7
fulfilled	@	/Applications/Joplin…b/Synchronizer.js:5
Promise.then (async)		
step	@	/Applications/Joplin…b/Synchronizer.js:7
(anonymous)	@	/Applications/Joplin…b/Synchronizer.js:8
__awaiter	@	/Applications/Joplin…b/Synchronizer.js:4
logSyncSummary	@	/Applications/Joplin…Synchronizer.js:166
(anonymous)	@	/Applications/Joplin…Synchronizer.js:841
rejected	@	/Applications/Joplin…b/Synchronizer.js:6
Promise.then (async)		
step	@	/Applications/Joplin…b/Synchronizer.js:7
fulfilled	@	/Applications/Joplin…b/Synchronizer.js:5
Promise.then (async)		
step	@	/Applications/Joplin…b/Synchronizer.js:7
(anonymous)	@	/Applications/Joplin…b/Synchronizer.js:8
__awaiter	@	/Applications/Joplin…b/Synchronizer.js:4
start	@	/Applications/Joplin…Synchronizer.js:280
timeoutCallback	@	/Applications/Joplin…lib/registry.js:130
async function (async)		
timeoutCallback	@	/Applications/Joplin…lib/registry.js:100
reg.scheduleSync	@	/Applications/Joplin…lib/registry.js:153
(anonymous)	@	/Applications/Joplin…s/synchronize.js:53
fulfilled	@	/Applications/Joplin…ds/synchronize.js:5
Promise.then (async)		
step	@	/Applications/Joplin…ds/synchronize.js:7
fulfilled	@	/Applications/Joplin…ds/synchronize.js:5
Promise.then (async)		
step	@	/Applications/Joplin…ds/synchronize.js:7
(anonymous)	@	/Applications/Joplin…ds/synchronize.js:8
__awaiter	@	/Applications/Joplin…ds/synchronize.js:4
execute	@	/Applications/Joplin…s/synchronize.js:25
(anonymous)	@	/Applications/Joplin…mmandService.js:141
(anonymous)	@	/Applications/Joplin…CommandService.js:8
__awaiter	@	/Applications/Joplin…CommandService.js:4
execute	@	/Applications/Joplin…mmandService.js:136
onClick	@	/Applications/Joplin…eBar/SideBar.js:415
onClick	@	/Applications/Joplin…utton/Button.js:173
callCallback	@	/Applications/Joplin….development.js:347
invokeGuardedCallbackDev	@	/Applications/Joplin….development.js:397
invokeGuardedCallback	@	/Applications/Joplin….development.js:454
invokeGuardedCallbackAndCatchFirstError	@	/Applications/Joplin….development.js:468
executeDispatch	@	/Applications/Joplin….development.js:600
executeDispatchesInOrder	@	/Applications/Joplin….development.js:622
executeDispatchesAndRelease	@	/Applications/Joplin….development.js:725
executeDispatchesAndReleaseTopLevel	@	/Applications/Joplin….development.js:733
forEachAccumulated	@	/Applications/Joplin….development.js:707
runEventsInBatch	@	/Applications/Joplin….development.js:750
runExtractedPluginEventsInBatch	@	/Applications/Joplin….development.js:881
handleTopLevel	@	/Applications/Joplin…development.js:5901
batchedEventUpdates	@	/Applications/Joplin…development.js:2344
dispatchEventForPluginEventSystem	@	/Applications/Joplin…development.js:5996
dispatchEvent	@	/Applications/Joplin…development.js:6025
unstable_runWithPriority	@	/Applications/Joplin….development.js:643
runWithPriority$2	@	/Applications/Joplin…evelopment.js:11305
discreteUpdates$1	@	/Applications/Joplin…evelopment.js:21672
discreteUpdates	@	/Applications/Joplin…development.js:2359
dispatchDiscreteEvent	@	/Applications/Joplin…development.js:5979
/Applications/Joplin…n/lib/Logger.js:165 22:17:37: Trying to reload note that has been deleted: null
/Applications/Joplin…n/lib/Logger.js:165 22:17:38: DecryptionWorker: cannot start because no master key is currently loaded.
```

**Comment by rexzhang** [comment]
Maybe related to this information: https://stackoverflow.com/questions/31673587/error-unable-to-verify-the-first-certificate-in-nodejs

**Comment by JackGruber** [comment]
Did you include the complete certificate chain in your certificate file?
DST Root CA X3, R3 and your rexzhang.myds.me certificate?

**Comment by JackGruber** [comment]
OK, i have checked your certificate. You need to include the `R2` certificate.

**Comment by rexzhang** [comment]
Thanks, I have forwarded this information to the NAS(synology) manufacturer。

**Comment by rexzhang** [comment]
This link browser can work normally, as well as the iOS version. Can the compatibility of the macOS version be enhanced?

**Comment by rexzhang** [comment]
I found it; Let’s Encrypt transition from X3 to R3 intermediate.

Ref:
- https://letsencrypt.org/certificates/
- https://letsencrypt.org/2020/09/17/new-root-and-intermediates.html
- https://community.letsencrypt.org/t/transition-from-x3-to-r3-intermediate/134465

**Comment by rexzhang** [comment]
check with  https://www.geocerts.com/ssl-checker
![截屏2020-12-17 15 22 11](https://user-images.githubusercontent.com/238707/102456200-c37f7f80-407b-11eb-9abc-0ad4b155c50b.png)

Ref:
- https://letsencrypt.org/certificates/
- https://letsencrypt.org/2020/09/17/new-root-and-intermediates.html
- https://community.letsencrypt.org/t/transition-from-x3-to-r3-intermediate/134465

**Comment by JackGruber** [comment]
The problem is the not complet Certificate Chain on your certificate under `rexzhang.myds.me:5006/home/Joplin` !
In the certificate is the R3 not included! 

![grafik](https://user-images.githubusercontent.com/24863925/102461076-29521400-4048-11eb-88e2-b9c238779841.png)

The same on the online tool you have used. 
![grafik](https://user-images.githubusercontent.com/24863925/102460837-db3d1080-4047-11eb-9f23-d4e8e62ed25a.png)

**Comment by rexzhang** [comment]
Uh... I don’t know why the test results are different... -_-!

**Comment by JackGruber** [comment]
Do you have installted DSM7 preview?

Discussion in the forum:
https://discourse.joplinapp.org/t/android-app-wont-sync/13210

**Comment by rexzhang** [comment]
Yes, it's DSM7 preview

**Comment by JackGruber** [comment]
OK, I have analyzed the problem in more detail on a Syno with DSM7 and have opend a post in the DSM7 beta community. 
[WebDAV server use cert.pem instead of fullchain.pem](https://community.synology.com/enu/forum/20/post/139622)

As a workaround you can do the following, 
1) Login as root
2) `cp /var/packages/WebDAVServer/target/etc/httpd/conf/extra/httpd-ssl.conf-cipher-webdav /var/packages/WebDAVServer/target/etc/httpd/conf/extra/httpd-ssl.conf-cipher-webdav.bak`
3) `sed -i -e "s/cert.pem/fullchain.pem/g" /var/packages/WebDAVServer/target/etc/httpd/conf/extra/httpd-ssl.conf-cipher-webdav`
4) `/var/packages/WebDAVServer/target/scripts/synowebdavserver_httpd_control.sh restart`

**Comment by rexzhang** [comment]
change `/var/packages/WebDAVServer/target/etc/httpd/conf/extra/httpd-ssl.conf-cipher-webdav`
```
AddType application/x-x509-ca-cert  .crt
AddType application/x-pkcs7-crl     .crl


SSLCertificateFile      "/usr/local/etc/certificate/WebDAVServer/webdav/cert.pem"
SSLCertificateKeyFile   "/usr/local/etc/certificate/WebDAVServer/webdav/privkey.pem"

Include /usr/syno/etc/security-profile/tls-profile/config/synowebdavserver_httpd.conf

SSLSessionTickets       off
```
to
```
AddType application/x-x509-ca-cert  .crt
AddType application/x-pkcs7-crl     .crl


SSLCertificateFile      "/usr/local/etc/certificate/WebDAVServer/webdav/fullchain.pem"
SSLCertificateKeyFile   "/usr/local/etc/certificate/WebDAVServer/webdav/privkey.pem"

Include /usr/syno/etc/security-profile/tls-profile/config/synowebdavserver_httpd.conf

SSLSessionTickets       off
```
it work! thank you!

**Comment by JackGruber** [comment]
Glad to hear, I am also in contact with the Syno support ...

**Comment by JackGruber** [comment]
Confirmed by Synology developers, this is a known issue that they are currently working on.
