### ISSUE TITLE
Joplin CLI installation issue: Something went wrong installing the "sharp" module

### ISSUE THREAD

**Issue by jt196** [laurent22/joplin#4233]
## Environment

Joplin version: terminal CLI version
Platform: Mac
OS specifics: Catalina

## Steps to reproduce

1. On installation after `NPM_CONFIG_PREFIX=~/.joplin-bin npm install -g joplin`
2. I try to run `joplin`, and get this error:

```
/Users/<userdir>/.joplin-bin/lib/node_modules/joplin/node_modules/sharp/lib/constructor.js:34
  throw new Error(error);
  ^

Error:
Something went wrong installing the "sharp" module

dlopen(/Users/<userdir>/.joplin-bin/lib/node_modules/joplin/node_modules/sharp/build/Release/sharp.node, 1): Library not loaded: @rpath/libgobject-2.0.0.dylib
  Referenced from: /Users/<userdir>/.joplin-bin/lib/node_modules/joplin/node_modules/sharp/build/Release/sharp.node
  Reason: image not found

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (/Users/<userdir>/.joplin-bin/lib/node_modules/joplin/node_modules/sharp/lib/constructor.js:34:9)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/<userdir>/.joplin-bin/lib/node_modules/joplin/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
```
Joplin was working but I attempted to upgrade and got this output. 

Attempted to remove the sharp node module directory and run the installation script again but it's still coming out with this error.

**Comment by jt196** [comment]
Updated node, and deleted the joplin bin, now getting more error messages. 

Here's the full log: https://pastebin.com/5WK1kyp8

And what's showing up on the terminal:

```
❯ NPM_CONFIG_PREFIX=~/.joplin-bin npm install -g joplin
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated highlight.js@9.12.0: Version no longer supported. Upgrade to @latest
npm WARN deprecated highlight.js@9.12.0: Version no longer supported. Upgrade to @latest
npm ERR! code 1
npm ERR! path /Users/[user_dir]/.joplin-bin/lib/node_modules/joplin/node_modules/sqlite3
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/[user_dir]/.joplin-bin/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/napi-v6-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/[user_dir]/.joplin-bin/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/napi-v6-darwin-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.11.0
npm ERR! node-pre-gyp info using node@12.18.1 | darwin | x64
npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download
npm ERR! node-pre-gyp info check checked for "/Users/[user_dir]/.joplin-bin/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/napi-v6-darwin-x64/node_sqlite3.node" (not found)
npm ERR! node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-darwin-x64.tar.gz
npm ERR! node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-darwin-x64.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-darwin-x64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not found for sqlite3@5.0.1 and node@12.18.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-darwin-x64.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@12.18.1 | darwin | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@12.18.1 | darwin | x64
npm ERR! gyp info find Python using Python version 3.7.6 found at "/Users/[user_dir]/opt/anaconda3/bin/python3"
npm ERR! gyp info spawn /Users/[user_dir]/opt/anaconda3/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/[user_dir]/.joplin-bin/lib/node_modules/joplin/node_modules/sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/[user_dir]/Library/Caches/node-gyp/12.18.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/[user_dir]/Library/Caches/node-gyp/12.18.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/[user_dir]/Library/Caches/node-gyp/12.18.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/[user_dir]/.joplin-bin/lib/node_modules/joplin/node_modules/sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
npm ERR! No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
npm ERR! No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
npm ERR!
npm ERR!
npm ERR!
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@12.18.1 | darwin | x64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
npm ERR! gyp ERR! System Darwin 20.2.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/[user_dir]/.joplin-bin/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/napi-v6-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/[user_dir]/.joplin-bin/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/napi-v6-darwin-x64" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
npm ERR! gyp ERR! cwd /Users/[user_dir]/.joplin-bin/lib/node_modules/joplin/node_modules/sqlite3
npm ERR! gyp ERR! node -v v12.18.1
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/[user_dir]/.joplin-bin/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/napi-v6-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/[user_dir]/.joplin-bin/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/napi-v6-darwin-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/[user_dir]/.joplin-bin/lib/node_modules/joplin/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
npm ERR! node-pre-gyp ERR! System Darwin 20.2.0
npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/[user_dir]/.joplin-bin/lib/node_modules/joplin/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /Users/[user_dir]/.joplin-bin/lib/node_modules/joplin/node_modules/sqlite3
npm ERR! node-pre-gyp ERR! node -v v12.18.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.11.0
npm ERR! node-pre-gyp ERR! not ok
```

**Comment by brucejuz** [comment]
I have the same problem as you. 
May be the joplin CLI does not support the Mac

**Comment by mattalexx** [comment]
I have the same problem on Arch Linux, trying to install Joplin 2.3.5 using the AUR repo: https://aur.archlinux.org/packages/joplin/.

Joplin 2.3.5
Node v16.9.1

```shell
% makepkg -s
...
npm ERR! code 1
npm ERR! path /home/-/joplin/src/joplin-2.3.5/packages/lib/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
npm ERR! make: Entering directory '/home/-/joplin/src/joplin-2.3.5/packages/lib/node_modules/sharp/build'
npm ERR!   TOUCH Release/obj.target/libvips-cpp.stamp
npm ERR!   CC(target) Release/obj.target/nothing/node_modules/node-addon-api/nothing.o
npm ERR!   AR(target) Release/obj.target/node_modules/node-addon-api/nothing.a
npm ERR!   COPY Release/nothing.a
npm ERR!   CXX(target) Release/obj.target/sharp/src/common.o
npm ERR! make: Leaving directory '/home/-/joplin/src/joplin-2.3.5/packages/lib/node_modules/sharp/build'
npm ERR! info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.0/libvips-8.10.0-linux-x64.tar.br
npm ERR! ERR! sharp Please delete /home/-/joplin/src/npm-cache/_libvips/libvips-8.10.0-linux-x64.tar.br as it is not a valid tarball
npm ERR! ERR! sharp unexpected end of file
npm ERR! info sharp Attempting to build from source via node-gyp but this may fail due to the above error
npm ERR! info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.9.1 | linux | x64
npm ERR! (node:902878) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /usr/bin/python2
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/-/joplin/src/joplin-2.3.5/packages/lib/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/-/joplin/src/joplin-2.3.5/packages/lib/node_modules/sharp/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/-/joplin/src/joplin-2.3.5/packages/lib/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/-/.node-gyp/16.9.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/-/.node-gyp/16.9.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/-/joplin/src/joplin-2.3.5/packages/lib/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/-/.node-gyp/16.9.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/-/joplin/src/joplin-2.3.5/packages/lib/node_modules/sharp',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
npm ERR! <command-line>: note: this is the location of the previous definition
npm ERR! ../src/common.cc:24:10: fatal error: vips/vips8: No such file or directory
npm ERR!    24 | #include <vips/vips8>
npm ERR!       |          ^~~~~~~~~~~~
npm ERR! compilation terminated.
npm ERR! make: *** [sharp.target.mk:137: Release/obj.target/sharp/src/common.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/-/joplin/src/joplin-2.3.5/packages/lib/node_modules/node-gyp/lib/build.js:262:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 5.14.5-arch1-1
npm ERR! gyp ERR! command "/usr/bin/node" "/home/-/joplin/src/joplin-2.3.5/packages/lib/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /home/-/joplin/src/joplin-2.3.5/packages/lib/node_modules/sharp
npm ERR! gyp ERR! node -v v16.9.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/-/joplin/src/npm-cache/_logs/2021-09-20T03_31_38_418Z-debug.log

lerna ERR! npm install --cache /home/-/joplin/src/npm-cache exited 1 in '@joplin/lib'
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
npm ERR! code 1
npm ERR! path /home/-/joplin/src/joplin-2.3.5
npm ERR! command failed
npm ERR! command sh -c npm run bootstrap --no-ci && npm run build

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/-/joplin/src/npm-cache/_logs/2021-09-20T03_31_40_303Z-debug.log
==> ERROR: A failure occurred in build().
    Aborting...
makepkg -s  156.24s user 21.64s system 156% cpu 1:54.02 total

```
