### ISSUE TITLE
应用版本：1.5.12  同步完成后，提示“最后的错误”

### ISSUE THREAD

**Issue by chenjiazhi1014** [laurent22/joplin#4261]
Error: PROPFIND /: Unknown error 2 (404): Not Found
    at newError (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:406:11)
    at WebDavApi.exec (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:436:10)
    at async FileApiDriverWebDav.list (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api-driver-webdav.js:134:18)
    at async getDirStats (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api-driver-webdav.js:92:19)
    at async basicDelta (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api.js:338:27)
    at async FileApiDriverWebDav.delta (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api-driver-webdav.js:96:10)
    at async tryAndRepeat (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api.js:38:19)"

**Comment by chenjiazhi1014** [comment]
![image](https://user-images.githubusercontent.com/53961619/103255396-24844d00-49c4-11eb-808f-59458a434732.png)

**Comment by laurent22** [comment]
Hello, most people who can provide support here don't understand Chinese so it's best if you can post in English. From the look of it anyway, your WebDAV URL is incorrect so check it again.

**Comment by tessus** [comment]
Closing this. For questions how to use Joplin, the forum is the right place.
