### ISSUE TITLE
OneDrive always full sync issue

### ISSUE THREAD

**Issue by daviding924** [laurent22/joplin#4313]
## Environment

Joplin version: Win 1.5.14, iOS 10.5.1
Platform: Windows, macOS, iOS, Android
OS specifics: Windows 10, iOS 14.3

## Steps to reproduce

1. setup Synchronization target to OneDrive
2. sync until first full sync done
3. sync again, it is still full sync

## Describe what you expected to happen
I have 17000 notes, about 38000 items in Joplin, I use OneDrive as storage, and sync every day. In 2020, every thing is fine. But I got full sync issue in 2021.

Joplin always full sync every time. I try to delete Joplin App, all of JoplinProfile and data in local. After first full sync finished, it still full sync again and again, or stop in middle, no delta sync.

I use latest Joplin version in Windows 10, macOS, iOS and Android, which have same issue.

## Logfile
Windows Log when sync break in middle:
2021-01-06 10:19:34: "RevisionService::maintenance: Starting..."
2021-01-06 10:19:34: "RevisionService::maintenance: Service is enabled"
2021-01-06 10:19:34: "RevisionService::collectRevisions: Created revisions for 0 notes"
2021-01-06 10:19:52: "Got unhandled error:", "ECONNRESET", "request to https://public.bn.files.1drv.com/y4mgSQZv_y7Zv3FeAejXs7CDf3N6qXtlo13TSp4bo72xoyYgK73DcU3SmhYiCTInoClDmxBIPWngQiilR7jJVcTY8iVcDzhmmxRG8MyzWMtPFbqr5z83VihAk4LPtsvo-0_JC9DRV4lipzUw4GpY56OmLSkm6SRlwFfjJEpBPTRfnyIyuQYo0IDTVxlW72-tDoII4TbiYWbCl8lOkn6KJvvkDzK0WvtV9nWQLj_evuSFFc/36b02c3421c94ece8c88cd03872ad0ad.md failed, reason: read ECONNRESET", "FetchError: request to https://public.bn.files.1drv.com/y4mgSQZv_y7Zv3FeAejXs7CDf3N6qXtlo13TSp4bo72xoyYgK73DcU3SmhYiCTInoClDmxBIPWngQiilR7jJVcTY8iVcDzhmmxRG8MyzWMtPFbqr5z83VihAk4LPtsvo-0_JC9DRV4lipzUw4GpY56OmLSkm6SRlwFfjJEpBPTRfnyIyuQYo0IDTVxlW72-tDoII4TbiYWbCl8lOkn6KJvvkDzK0WvtV9nWQLj_evuSFFc/36b02c3421c94ece8c88cd03872ad0ad.md failed, reason: read ECONNRESET
Code: ECONNRESET
FetchError: request to https://public.bn.files.1drv.com/y4mgSQZv_y7Zv3FeAejXs7CDf3N6qXtlo13TSp4bo72xoyYgK73DcU3SmhYiCTInoClDmxBIPWngQiilR7jJVcTY8iVcDzhmmxRG8MyzWMtPFbqr5z83VihAk4LPtsvo-0_JC9DRV4lipzUw4GpY56OmLSkm6SRlwFfjJEpBPTRfnyIyuQYo0IDTVxlW72-tDoII4TbiYWbCl8lOkn6KJvvkDzK0WvtV9nWQLj_evuSFFc/36b02c3421c94ece8c88cd03872ad0ad.md failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (C:\Users\D\AppData\Local\Temp\1mM0wIAapQQoIcMOyYoSSmZVYw2\resources\app.asar\node_modules\@joplin\lib\node_modules\node-fetch\index.js:133:11)
    at ClientRequest.emit (events.js:310:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)"
2021-01-06 10:19:52: "Got unhandled error:", "ECONNRESET", "request to https://public.bn.files.1drv.com/y4mTLy1GF7uqrdJZrlPY0CCBBvFSKjKgG0lILduof2jzcPGEn5dJptujTN0rKhUfZOVI1EIxEXmhn7aZMGwk_mB2sX4TyfHwR9PLZiu8oBobQNgciAZZEbHrsbTop8NAfb9FIR8ckIOYdmiIEqlqfwOqrDMqLZRCDBrN-C79PVfNsO5uX-qHtrovA2yQo_XWK348cCokUeMPi-y6y6Q6uWb7JtLQYNh9tbmkABRbe26iU4/bd6433dc802944f08e818523a95c637a.md failed, reason: read ECONNRESET", "FetchError: request to https://public.bn.files.1drv.com/y4mTLy1GF7uqrdJZrlPY0CCBBvFSKjKgG0lILduof2jzcPGEn5dJptujTN0rKhUfZOVI1EIxEXmhn7aZMGwk_mB2sX4TyfHwR9PLZiu8oBobQNgciAZZEbHrsbTop8NAfb9FIR8ckIOYdmiIEqlqfwOqrDMqLZRCDBrN-C79PVfNsO5uX-qHtrovA2yQo_XWK348cCokUeMPi-y6y6Q6uWb7JtLQYNh9tbmkABRbe26iU4/bd6433dc802944f08e818523a95c637a.md failed, reason: read ECONNRESET
Code: ECONNRESET
FetchError: request to https://public.bn.files.1drv.com/y4mTLy1GF7uqrdJZrlPY0CCBBvFSKjKgG0lILduof2jzcPGEn5dJptujTN0rKhUfZOVI1EIxEXmhn7aZMGwk_mB2sX4TyfHwR9PLZiu8oBobQNgciAZZEbHrsbTop8NAfb9FIR8ckIOYdmiIEqlqfwOqrDMqLZRCDBrN-C79PVfNsO5uX-qHtrovA2yQo_XWK348cCokUeMPi-y6y6Q6uWb7JtLQYNh9tbmkABRbe26iU4/bd6433dc802944f08e818523a95c637a.md failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (C:\Users\D\AppData\Local\Temp\1mM0wIAapQQoIcMOyYoSSmZVYw2\resources\app.asar\node_modules\@joplin\lib\node_modules\node-fetch\index.js:133:11)
    at ClientRequest.emit (events.js:310:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)"
2021-01-06 10:19:53: "FetchError: On file 36b02c3421c94ece8c88cd03872ad0ad.md: request to https://public.bn.files.1drv.com/y4mgSQZv_y7Zv3FeAejXs7CDf3N6qXtlo13TSp4bo72xoyYgK73DcU3SmhYiCTInoClDmxBIPWngQiilR7jJVcTY8iVcDzhmmxRG8MyzWMtPFbqr5z83VihAk4LPtsvo-0_JC9DRV4lipzUw4GpY56OmLSkm6SRlwFfjJEpBPTRfnyIyuQYo0IDTVxlW72-tDoII4TbiYWbCl8lOkn6KJvvkDzK0WvtV9nWQLj_evuSFFc/36b02c3421c94ece8c88cd03872ad0ad.md failed, reason: read ECONNRESET
Code: ECONNRESET
FetchError: request to https://public.bn.files.1drv.com/y4mgSQZv_y7Zv3FeAejXs7CDf3N6qXtlo13TSp4bo72xoyYgK73DcU3SmhYiCTInoClDmxBIPWngQiilR7jJVcTY8iVcDzhmmxRG8MyzWMtPFbqr5z83VihAk4LPtsvo-0_JC9DRV4lipzUw4GpY56OmLSkm6SRlwFfjJEpBPTRfnyIyuQYo0IDTVxlW72-tDoII4TbiYWbCl8lOkn6KJvvkDzK0WvtV9nWQLj_evuSFFc/36b02c3421c94ece8c88cd03872ad0ad.md failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (C:\Users\D\AppData\Local\Temp\1mM0wIAapQQoIcMOyYoSSmZVYw2\resources\app.asar\node_modules\@joplin\lib\node_modules\node-fetch\index.js:133:11)
    at ClientRequest.emit (events.js:310:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)"

**Comment by limer-org** [comment]
I have the same.
Start syncing and crash.

Pobieranie obiektów 1092/1100.
Ukończono: 08/01/2021 08:53
Ostatni błąd: SyntaxError: On file d9df413810bf1095d82deaee07e181e8.md: OneDriveApi::exec: Cannot parse JSON error: <!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body {font-family:Arial; margin-left:40px; }img { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-s

**Comment by limer-org** [comment]
After this changes I must full sync ?? After update desktop client ver. 1.6.5 again taken full sync.

**Comment by limer-org** [comment]
On my mobile client - Android 1.5.1 - objects to sync are 4 time larger than I have in OneDrive.
Android client has to make full sync every time.

**Comment by LMSSonos** [comment]
@limer-org What was the resolution to your issue? Have exact the same problem on Android (1.5.1) and Windows (1.5.14 portable)

**Comment by limer-org** [comment]
I didn't resolved this. For now I uninstalled Android App. I Cleared up OneDrive repo with Joplin. On my desktop (Linux) I imported JEX and sync to new OneDrive repo. Maybe this will help. This is solution of @laurent22 mentioned in #4305 .

**Comment by LMSSonos** [comment]
@limer-org thanks, I will wait and see what happens on #4305
