### ISSUE TITLE
Synchronisation is very slow and never finishes

### ISSUE THREAD

**Issue by homofortis** [laurent22/joplin#4325]
I've been using Joplin client on multiple platforms synchronising via OneDrive. The syncronisaton is extremely slow and hasn't been finishing since the last few days. 
<img width="788" alt="Screenshot 2021-01-08 at 16 03 54" src="https://user-images.githubusercontent.com/3680999/104039665-916ec280-51ce-11eb-810e-c0bf4d0676d3.png">
<img width="262" alt="Screenshot 2021-01-08 at 08 20 05" src="https://user-images.githubusercontent.com/3680999/104039743-a6e3ec80-51ce-11eb-864b-c40eaa1424b8.png">

## Environment

Joplin version: 
Joplin 1.5.14 (prod, darwin)
Sync Version: 2
Profile Version: 34
Platform: 
macOS, Linux, Windows, Android
OS specifics: 
Mac OS X 11.1
ubuntu 20.10
Windows 10 Home
Android 10

## Steps to reproduce

1. Start Joplin
2. Synchronise
3. zzzzzzz

## Describe what you expected to happen
1. Start Joplin
2. Synchronise
3. Synchronisation completed in less than 3 mins.

## Logfile

`
...
2021-01-08 16:26:33: "Settings have been saved."
2021-01-08 16:26:36: "Saving settings..."
2021-01-08 16:26:36: "Settings have been saved."
2021-01-08 16:26:38: "Saving settings..."
2021-01-08 16:26:38: "Settings have been saved."
2021-01-08 16:26:39: "Saving settings..."
2021-01-08 16:26:39: "Settings have been saved."
2021-01-08 16:26:40: "Saving settings..."
2021-01-08 16:26:40: "Settings have been saved."
2021-01-08 16:26:40: "Saving settings..."
2021-01-08 16:26:40: "Settings have been saved."
2021-01-08 16:32:00: "Saving settings..."
2021-01-08 16:32:00: "Running background sync on timer..."
2021-01-08 16:32:00: "Preparing scheduled sync"
2021-01-08 16:32:00: "Starting scheduled sync"
2021-01-08 16:32:00: "Synchronisation is already in progress. State: in_progress"
2021-01-08 16:32:01: "Settings have been saved."
2021-01-08 16:32:01: "Saving settings..."
2021-01-08 16:32:01: "Settings have been saved."
2021-01-08 16:32:03: "Could not refresh lock - cancelling sync. Error was:", "Error: Lock has expired
Code: lockExpired
Error: Lock has expired
    at LockHandler.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/LockHandler.js:289:25)
    at Generator.next (<anonymous>)
    at fulfilled (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/LockHandler.js:5:58)"
2021-01-08 16:32:03: "TaskQueue.stop: syncDownload: waiting for tasks to complete: 2"
2021-01-08 16:32:03: "TaskQueue.stop: syncDownload: Done, waited for 305"
2021-01-08 16:32:03: "Saving settings..."
2021-01-08 16:32:03: "Settings have been saved."
2021-01-08 16:32:03: "Synchronisation was cancelled."
2021-01-08 16:32:03: "Operations completed: "
2021-01-08 16:32:03: "fetchingTotal: 4424"
2021-01-08 16:32:03: "fetchingProcessed: 4422"
2021-01-08 16:32:03: "cancelling: 1"
2021-01-08 16:32:03: "Total folders: 99"
2021-01-08 16:32:03: "Total notes: 1032"
2021-01-08 16:32:03: "Total resources: 64"
2021-01-08 16:32:04: "Saving settings..."
2021-01-08 16:32:04: "Settings have been saved."
2021-01-08 16:32:04: "DecryptionWorker: cannot start because no master key is currently loaded."
2021-01-08 16:32:11: "Saving settings..."
2021-01-08 16:32:11: "Settings have been saved."
2021-01-08 16:32:40: "Saving settings..."
2021-01-08 16:32:40: "Settings have been saved."
2021-01-08 16:33:41: "RevisionService::maintenance: Starting..."
2021-01-08 16:33:41: "RevisionService::maintenance: Service is enabled"
2021-01-08 16:33:41: "RevisionService::collectRevisions:", "Error: Could not create revision for note: c6de47a7cd8440e6be28e036cef9e018: Invalid patch string: @@ -0,0 +1,5 @@\n+Dec29\n
Could not create revision for note: c6de47a7cd8440e6be28e036cef9e018: Error: Invalid patch string: @@ -0,0 +1,5 @@\n+Dec29\n
    at diff_match_patch.patch_fromText (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/diff-match-patch/index.js:2092:13)
    at Function.applyTextPatch (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/models/Revision.js:24:15)
    at Function.mergeDiffs (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/models/Revision.js:197:24)
    at async RevisionService.createNoteRevision_ (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/RevisionService.js:94:20)
    at async RevisionService.collectRevisions (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/RevisionService.js:153:21)
    at async RevisionService.maintenance (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/RevisionService.js:261:5)"
2021-01-08 16:33:41: "RevisionService::collectRevisions: Created revisions for 0 notes"
2021-01-08 16:33:41: "RevisionService::maintenance: Done in 116ms"`

**Comment by CalebJohn** [comment]
@homofortis 

I think the issue isn't 100% known yet, but this appears to be another issue with the OneDrive api provided by Microsoft. Unfortunately, that means that nothing can be done until they fix it on their end, at which point it will suddenly start working for you and everybody else.
There are some people on the forum discussing the issue, I suggest you look there for more information
https://discourse.joplinapp.org/t/since-onedrive-sync-error-this-morning-each-sync-fetches-all-items/13622

**Comment by homofortis** [comment]
@CalebJohn thank you for your response, seems like pre-release 1.6.5 fixes the issue.
