### ISSUE TITLE
"About" in Help menu does not work

### ISSUE THREAD

**Issue by alusiani** [laurent22/joplin#4331]
## Environment

Joplin version: 1.5.14
Platform: Linux
OS specifics: Fedora 32

## Steps to reproduce

1. select "About" in "Help" menu
2. nothing happens

## Describe what you expected to happen

the version of Joplin should be displayed

## Logfile

```
electron/js2c/renderer_init.js:83 Uncaught Error: Could not call remote method 'buildDir'. Check that the method signature is correct. Underlying error: Cannot find build dir
Underlying stack: Error: Cannot find build dir
    at ElectronAppWrapper.buildDir (/usr/share/org.joplinapp.joplin/desktop/resources/app.asar/ElectronAppWrapper.js:232:23)
    at electron/js2c/browser_init.js:213:7789
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:213:4246)
    at IpcMainImpl.emit (events.js:310:20)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:157:8848)
    at WebContents.emit (events.js:310:20)

    at electron/js2c/browser_init.js:213:7817
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:213:4246)
    at IpcMainImpl.emit (events.js:310:20)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:157:8848)
    at WebContents.emit (events.js:310:20)
exception @ electron/js2c/renderer_init.js:83
metaToValue @ electron/js2c/renderer_init.js:83
remoteMemberFunction @ electron/js2c/renderer_init.js:83
_showAbout @ /usr/share/org.joplinapp.joplin/desktop/resources/app.asar/gui/MenuBar.js:316
click @ /usr/share/org.joplinapp.joplin/desktop/resources/app.asar/gui/MenuBar.js:614
apply @ electron/js2c/renderer_init.js:107
(anonymous) @ electron/js2c/renderer_init.js:83
(anonymous) @ electron/js2c/renderer_init.js:83
(anonymous) @ electron/js2c/renderer_init.js:103
emit @ events.js:310
EventEmitter.emit @ domain.js:482
onMessage @ electron/js2c/renderer_init.js:91
```

**Comment by alusiani** [comment]
> Hey there, it looks like there has been no activity on this issue recently. Has the issue been fixed, or does it still require the community's attention? This issue may be closed if no further activity occurs. You may comment on the issue and I will leave it open. Thank you for your contributions.

Hi,

the problem persists in Joplin 1.71 on Fedora 32 Linux. I see the following in the debug window:

```
electron/js2c/renderer_init.js:83 Uncaught Error: Could not call remote method 'buildDir'. Check that the method signature is correct. Underlying error: Cannot find build dir
Underlying stack: Error: Cannot find build dir
    at ElectronAppWrapper.buildDir (/usr/share/org.joplinapp.joplin/desktop/resources/app.asar/ElectronAppWrapper.js:232:23)
    at electron/js2c/browser_init.js:213:7789
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:213:4246)
    at IpcMainImpl.emit (events.js:310:20)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:157:8848)
    at WebContents.emit (events.js:310:20)

    at electron/js2c/browser_init.js:213:7817
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:213:4246)
    at IpcMainImpl.emit (events.js:310:20)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:157:8848)
    at WebContents.emit (events.js:310:20)
```

**Comment by alusiani** [comment]
> Hey there, it looks like there has been no activity on this issue recently. Has the issue been fixed, or does it still require the community's attention? This issue may be closed if no further activity occurs. You may comment on the issue and I will leave it open. Thank you for your contributions.

Hi,

the problem persists in Joplin 1.7.11. I attach the log content:

```[txt]
electron/js2c/renderer_init.js:83 Uncaught Error: Could not call remote method 'buildDir'. Check that the method signature is correct. Underlying error: Cannot find build dir
Underlying stack: Error: Cannot find build dir
    at ElectronAppWrapper.buildDir (/usr/share/org.joplinapp.joplin/desktop/resources/app.asar/ElectronAppWrapper.js:232:23)
    at electron/js2c/browser_init.js:213:7789
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:213:4246)
    at IpcMainImpl.emit (events.js:310:20)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:157:8848)
    at WebContents.emit (events.js:310:20)

    at electron/js2c/browser_init.js:213:7817
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:213:4246)
    at IpcMainImpl.emit (events.js:310:20)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:157:8848)
    at WebContents.emit (events.js:310:20)
```

**Comment by alusiani** [comment]
This is an unharmful error, but persists in Joplin v1.8.5 in Fedora 32, I report below the debug messages:

```
Uncaught Error: Could not call remote method 'buildDir'. Check that the method signature is correct. Underlying error: Cannot find build dir
Underlying stack: Error: Cannot find build dir
    at ElectronAppWrapper.buildDir (/usr/share/org.joplinapp.joplin/desktop/resources/app.asar/ElectronAppWrapper.js:242:23)
    at electron/js2c/browser_init.js:213:7853
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:213:4254)
    at IpcMainImpl.emit (events.js:310:20)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:157:8961)
    at WebContents.emit (events.js:310:20)

    at electron/js2c/browser_init.js:213:7881
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:213:4254)
    at IpcMainImpl.emit (events.js:310:20)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:157:8961)
    at WebContents.emit (events.js:310:20)
```

**Comment by alusiani** [comment]
> Hey there, it looks like there has been no activity on this issue recently. Has the issue been fixed, or does it still require the community's attention? This issue may be closed if no further activity occurs. You may comment on the issue and I will leave it open. Thank you for your contributions.

Hi,

the issue is now solved! It was related to just the binary RPM for Fedora. The issue can be closed.
