### ISSUE TITLE
generator-joplin Cannot read property 'context' of undefined

### ISSUE THREAD

**Issue by JackGruber** [laurent22/joplin#4360]
Version: generator-joplin@1.7.1

When I run `npm run dist` with the generator-joplin version 1.7.1 I get the following error: 

```
> joplin-plugin-a@1.0.0 prepare C:\git\meine\test
> npm run dist


> joplin-plugin-a@1.0.0 dist C:\git\meine\test
> webpack --joplin-plugin-config buildMain && webpack --joplin-plugin-config buildExtraScripts && webpack --joplin-plugin-config createArchive

C:\git\meine\test\node_modules\webpack-cli\bin\cli.js:154
                        if (typeof outputOptions.context === "undefined") outputOptions.context = firstOptions.context;
                                                                                                               ^

TypeError: Cannot read property 'context' of undefined
    at processOptions (C:\git\meine\test\node_modules\webpack-cli\bin\cli.js:154:91)
    at C:\git\meine\test\node_modules\webpack-cli\bin\cli.js:364:3
    at Object.parse (C:\git\meine\test\node_modules\webpack-cli\node_modules\yargs\yargs.js:576:18)
    at C:\git\meine\test\node_modules\webpack-cli\bin\cli.js:49:8
    at Object.<anonymous> (C:\git\meine\test\node_modules\webpack-cli\bin\cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\git\meine\test\node_modules\webpack\bin\webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! joplin-plugin-a@1.0.0 dist: `webpack --joplin-plugin-config buildMain && webpack --joplin-plugin-config buildExtraScripts && webpack --joplin-plugin-config createArchive`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the joplin-plugin-a@1.0.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gruber\AppData\Roaming\npm-cache\_logs\2021-01-14T13_48_45_741Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! joplin-plugin-a@1.0.0 prepare: `npm run dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the joplin-plugin-a@1.0.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gruber\AppData\Roaming\npm-cache\_logs\2021-01-14T13_48_45_784Z-debug.log
```

**Comment by laurent22** [comment]
Do you have a repo url to replicate this?

**Comment by JackGruber** [comment]
This happens also when I create a empty one from scratch but also when I update the framework on the following repo: 
https://github.com/JackGruber/joplin-plugin-combine-notes

**Comment by laurent22** [comment]
Thanks for the info, I think that should be fixed now. Could you give a try to 1.7.2?

**Comment by JackGruber** [comment]
@laurent22 looks fine.

**Comment by JackGruber** [comment]
@laurent22 perhaps I was a bit too quick.

When I run `npm run dist` the `dist` folder is deleted and no files created. 
This habbens with new repos and existing repos. 

Es wird nun kein dist/

**Comment by laurent22** [comment]
Thanks for letting me know and indeed it was broken again (really need to find a way to unit test this). If you upgrade to the latest version 1.7.3 it should work.

**Comment by JackGruber** [comment]
thanks, the scripts are generated again.
