### ISSUE TITLE
Get error after installing "simple backup"

### ISSUE THREAD

**Issue by istudyatuni** [laurent22/joplin#4520]
## Environment

Joplin version: See below
Platform: Linux
OS specifics: Manjaro Linux

## Steps to reproduce

I'm not sure, but

1. Install "simple backup"
2. Reload
3. Go to settings

Note: before it i install "LinkGraph", but after it reload app without trouble

## Describe what you expected to happen

Bug not exist :)

## Logfile

[log1.txt](https://github.com/laurent22/joplin/files/5971337/log1.txt)

It's not full log, I cut last block (from starting install LinkGraph)

# Get this message

Error
Joplin encountered a fatal error and could not continue. To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

Message
md.options is not a function

Version info
Joplin for Desktop

Copyright © 2016-2021 Laurent Cozic
Joplin 1.6.8 (prod, linux)

Идентификатор клиента: 85272f30ba484a059bcafc53df53b1ed
Синхронизированная версия: 2
Версия профиля: 34
Поддерживаемая связка ключей: Нет

Изменения: fc7bd41 (master)
Stack trace
TypeError: md.options is not a function
    at ConfigScreenComponent.settingToComponent (/tmp/.mount_Joplin9LjfL9/resources/app.asar/gui/ConfigScreen/ConfigScreen.js:331:39)
    at createSettingComponents (/tmp/.mount_Joplin9LjfL9/resources/app.asar/gui/ConfigScreen/ConfigScreen.js:144:42)
    at ConfigScreenComponent.sectionToComponent (/tmp/.mount_Joplin9LjfL9/resources/app.asar/gui/ConfigScreen/ConfigScreen.js:149:30)
    at Object.shared.settingsToComponents2 (/tmp/.mount_Joplin9LjfL9/resources/app.asar/node_modules/@joplin/lib/components/shared/config-shared.js:184:28)
    at ConfigScreenComponent.render (/tmp/.mount_Joplin9LjfL9/resources/app.asar/gui/ConfigScreen/ConfigScreen.js:528:37)
    at finishClassComponent (/tmp/.mount_Joplin9LjfL9/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:17039:31)
    at updateClassComponent (/tmp/.mount_Joplin9LjfL9/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:16994:24)
    at beginWork$1 (/tmp/.mount_Joplin9LjfL9/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:18505:16)
    at HTMLUnknownElement.callCallback (/tmp/.mount_Joplin9LjfL9/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:347:14)
    at Object.invokeGuardedCallbackDev (/tmp/.mount_Joplin9LjfL9/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:397:16)
Component stack

    in ConfigScreenComponent (created by Connect(ConfigScreenComponent))
    in Connect(ConfigScreenComponent) (created by NavigatorComponent)
    in div (created by NavigatorComponent)
    in NavigatorComponent (created by Connect(NavigatorComponent))
    in Connect(NavigatorComponent) (created by RootComponent)
    in ThemeProvider (created by RootComponent)
    in StyleSheetManager (created by RootComponent)
    in RootComponent (created by Connect(RootComponent))
    in Connect(RootComponent)
    in ErrorBoundary
    in Provider

**Comment by istudyatuni** [comment]
I updated and all is good)
