### ISSUE TITLE
Cannot install CLI application on WSL (ubuntu)

### ISSUE THREAD

**Issue by duarteocarmo** [laurent22/joplin#4547]
Followed installation instructions for terminal application. 

Currently running node v10.23.3 and npm v6.14.11

Here is the tail of the logfile:

```
14656 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/joplin/node_modules/chokidar/node_modules/fsevents):
14657 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
14658 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
14658 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
14658 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
14658 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
14659 verbose stack Error: keytar@7.4.0 install: `prebuild-install || npm run build`
14659 verbose stack Exit status 1
14659 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
14659 verbose stack     at EventEmitter.emit (events.js:198:13)
14659 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14659 verbose stack     at ChildProcess.emit (events.js:198:13)
14659 verbose stack     at maybeClose (internal/child_process.js:982:16)
14659 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14660 verbose pkgid keytar@7.4.0
14661 verbose cwd /home/doc
14662 verbose Linux 4.4.0-18362-Microsoft
14663 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "joplin"
14664 verbose node v10.23.3
14665 verbose npm  v6.14.11
14666 error code ELIFECYCLE
14667 error errno 1
14668 error keytar@7.4.0 install: `prebuild-install || npm run build`
14668 error Exit status 1
14669 error Failed at the keytar@7.4.0 install script.
14669 error This is probably not a problem with npm. There is likely additional logging output above.
14670 verbose exit [ 1, true ]
```

## Environment

Joplin version: not applicable
Platform: Linux via WSL
OS specifics: Ubuntu

## Steps to reproduce

1. Get node from package manager
2. `sudo apt-get install -y nodejs && sudo apt-get install gcc g++ make`
3. `NPM_CONFIG_PREFIX=~/.joplin-bin npm install -g joplin` 
4. `sudo ln -s ~/.joplin-bin/bin/joplin /usr/bin/joplin` 

## Describe what you expected to happen
Successful installation of joplin CLI application. 

Instead of that, I just get command not found..

## Logfile

[2021-02-17T12_56_44_639Z-debug.log](https://github.com/laurent22/joplin/files/5995817/2021-02-17T12_56_44_639Z-debug.log)

**Comment by jalajcodes** [comment]
I just installed it via the steps you mentioned and it's working fine for me. I am running node 14.6.0 and npm 6.14.6. 
Can you try again after upgrading node and npm?
