### ISSUE TITLE
mac版joplin 报错

### ISSUE THREAD

**Issue by hxf236386915** [laurent22/joplin#4552]
因为过年有十几天没用电脑，电脑也没有关机。然后年后再打开的时候，电脑没电了，等充电重启之后，joplin就打不开了，报错这个，点击确定就退出里，尝试了写在重装等等都不行，求解决。

Fatal error:

Error: SQLITE_CORRUPT: database disk image is malformed: CREATE TABLE folders (id TEXT PRIMARY KEY, title TEXT NOT NULL DEFAULT "", created_time INT NOT NULL, updated_time INT NOT NULL);

Error: Error: SQLITE_CORRUPT: database disk image is malformed: CREATE TABLE folders (id TEXT PRIMARY KEY, title TEXT NOT NULL DEFAULT "", created_time INT NOT NULL, updated_time INT NOT NULL);
    at DatabaseDriverNode.sqliteErrorToJsError (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/database-driver-node.js:21:18)
    at JoplinDatabase.sqliteErrorToJsError (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/database.js:26:24)
    at JoplinDatabase.tryCall (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/database.js:114:17)
    at async JoplinDatabase.transactionExecBatch (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/database.js:174:5)
    at async JoplinDatabase.upgradeDatabase (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/joplin-database.js:858:5)
    at async JoplinDatabase.initialize (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/joplin-database.js:946:22)
![image](https://user-images.githubusercontent.com/28081698/108374290-c47b8b80-723b-11eb-8333-430b93f335e6.png)

**Comment by rexzhang** [comment]
这个应该是本地用于存储笔记的 sqlite 文件损坏了，你在删除 joplin app 时没有同时删除用户数据文件。

```shell
rm -rf ~/.config/joplin-desktop
```

**Comment by hxf236386915** [comment]
我没有删除joplin APP呀
我不记得，我的用户数据文件在哪里了呀
那我要怎么做呢

**Comment by rexzhang** [comment]
joplin的文件都在 ‘ ~/.config/joplin-desktop’ 目录下面

**Comment by hxf236386915** [comment]
> joplin的文件都在'〜/ .config / joplin-desktop'目录下

你说的是应用程序里的 .config 文件吧  ，我这里找不到呢

**Comment by hxf236386915** [comment]
你说的这个文件，我这里找不到呢

**Comment by hxf236386915** [comment]
解决了  谢谢

**Comment by rexzhang** [comment]
不客气，我也是使用者。解决了记得关闭这个 issue 哦
