### ISSUE TITLE
Error: Property or method "setHtml" does not exist in "joplin.views.dialogs.open.setHtml"

### ISSUE THREAD

**Issue by CapZhang** [laurent22/joplin#4569]
## Environment

Joplin version:  1.7.11
Platform:  windows 10

## issue 
1. start joplin
2. load plugin
My plugin needs Dialogs

```js
11:44:14: joplin.plugins: Uncaught exception in plugin "joplin-plugin-file-encryption": Error: Property or method "setHtml" does not exist in "joplin.views.dialogs.open.setHtml"
    at Object.<anonymous> (D:\Program\Joplin\resources\app.asar\node_modules\@joplin\lib\services\plugins\utils\executeSandboxCall.js:47:23)
    at Generator.next (<anonymous>)
    at D:\Program\Joplin\resources\app.asar\node_modules\@joplin\lib\services\plugins\utils\executeSandboxCall.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Program\Joplin\resources\app.asar\node_modules\@joplin\lib\services\plugins\utils\executeSandboxCall.js:4:12)
    at Object.executeSandboxCall [as default] (D:\Program\Joplin\resources\app.asar\node_modules\@joplin\lib\services\plugins\utils\executeSandboxCall.js:37:12)
    at PluginRunner.<anonymous> (D:\Program\Joplin\resources\app.asar\services\plugins\PluginRunner.js:135:68)
    at Generator.next (<anonymous>)
    at D:\Program\Joplin\resources\app.asar\services\plugins\PluginRunner.js:8:71
    at new Promise (<anonymous>)
```

**Comment by CalebJohn** [comment]
@CapZhang 

Have you run `npm run update` in the root of your plugin? It looks like your local api version is out of date.

**Comment by CapZhang** [comment]
> @CapZhang
> 
> Have you run `npm run update` in the root of your plugin? It looks like your local api version is out of date.

Thank you for your help. 
I have executed `npm run update` and `npm run dist`, but the problem still exists

**Comment by CalebJohn** [comment]
I see, Looking closer it appears that you have a typo.

The call should be `joplin.views.dialogs.setHtml` but you have called `joplin.views.dialogs.open.setHtml` which doesn't exist.

Please feel free to share your code if you are still having trouble getting it to work.
