### ISSUE TITLE
Error from wrong version of node_sqlite3.node

### ISSUE THREAD

**Issue by TheShed412** [laurent22/joplin#458]
### Operating system

- Linux Mint 18.2

### Application

- Terminal

After installing node 8 and allowing for global install, I get this error on executing in terminal:

```
module.js:549
    throw err;
    ^

Error: Cannot find module '/usr/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/joplin/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```
When checking `/usr/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/` I didn't find `node-v57-linux-x64/node_sqlite3.node` but I found `node-v48-linux-x64/node_sqlite3.node`

**Comment by laurent22** [comment]
For user support, please post instead on the forum https://discourse.joplin.cozic.net/

This issue is not a bug but a problem with the way the app was installed and later ran.
