### ISSUE TITLE
Unable to synchronize with mDNS host on LAN

### ISSUE THREAD

**Issue by rongcuid** [laurent22/joplin#4587]
I have a Nextcloud machine on local network, configured with mDNS resolved as `nextcloudpi.local`. I cannot set up synchronization using the Joplin desktop app, giving the following error:

```
Error. Please check that URL, username, password, etc. are correct and that the sync target is accessible. The reported error was:
request to https://nextcloudpi.local/remote.php/dav/files/ncp/Joplin/ failed, reason: getaddrinfo ENOTFOUND nextcloudpi.local (Code ENOTFOUND)
```
## Environment

Joplin version: 1.7.11
Platform: Linux
OS specifics: Pop OS 20.04, flatpak

## Steps to reproduce

1. Have a Nextcloud machine on local network, set up with mDNS service
2. Try to use Nextcloud synchronization

## Describe what you expected to happen
Connect to Nextcloud

## Logfile

```
2021-02-22 20:08:38: "Could not setup sync target:", "Error: Unsupported WebDAV URL format: https://nextcloudpi.local/remote.php/dav/files/ncp/Joplin
Error: Unsupported WebDAV URL format: https://nextcloudpi.local/remote.php/dav/files/ncp/Joplin
    at Function.baseUrlFromNextcloudWebDavUrl (/app/joplin-desktop/resources/app/node_modules/@joplin/lib/JoplinServerApi.js:60:19)
    at Object.baseUrl (/app/joplin-desktop/resources/app/node_modules/@joplin/lib/SyncTargetNextcloud.js:59:35)
    at JoplinServerApi.baseUrl (/app/joplin-desktop/resources/app/node_modules/@joplin/lib/JoplinServerApi.js:53:43)
    at JoplinServerApi.<anonymous> (/app/joplin-desktop/resources/app/node_modules/@joplin/lib/JoplinServerApi.js:117:33)
    at Generator.next (<anonymous>)
    at /app/joplin-desktop/resources/app/node_modules/@joplin/lib/JoplinServerApi.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/joplin-desktop/resources/app/node_modules/@joplin/lib/JoplinServerApi.js:4:12)
    at JoplinServerApi.exec (/app/joplin-desktop/resources/app/node_modules/@joplin/lib/JoplinServerApi.js:99:16)
    at JoplinServerApi.<anonymous> (/app/joplin-desktop/resources/app/node_modules/@joplin/lib/JoplinServerApi.js:75:25)"
```

**Comment by rongcuid** [comment]
I just checked iOS app, and it too does not work, giving  "Network request failed" error.

**Comment by rongcuid** [comment]
Keep it open
