### ISSUE TITLE
Failed to Install Joplin 1.7.5 Desktop on Arch Linux - NPM Electron

### ISSUE THREAD

**Issue by l-ucky** [laurent22/joplin#4617]
I deleted everything on my PC (Arch Linux) containing the word Joplin, and then I reinstalled Joplin. I've been having sync issues and this was recommended for me to do. Now, after deleting and reinstalling, I am met with this error. I'm not able to use Joplin at all currently.

``` 0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dist',
1 verbose cli   '--',
1 verbose cli   '--publish=never',
1 verbose cli   '--linux',
1 verbose cli   '--x64',
1 verbose cli   '--dir=dist/',
1 verbose cli   '-c.electronDist=/usr/lib/electron',
1 verbose cli   '-c.electronVersion=11.3.0'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v15.10.0
4 verbose run-script [ 'predist', 'dist', 'postdist' ]
5 info lifecycle @joplin/app-desktop@1.7.11~predist: @joplin/app-desktop@1.7.11
6 info lifecycle @joplin/app-desktop@1.7.11~dist: @joplin/app-desktop@1.7.11
7 verbose lifecycle @joplin/app-desktop@1.7.11~dist: unsafe-perm in lifecycle true
8 verbose lifecycle @joplin/app-desktop@1.7.11~dist: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/lucky/Downloads/joplin/src/joplin-1.7.11/packages/app-desktop/node_modules/.bin:/home/lucky/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/opt/cuda/bin:/opt/cuda/integration/nsight-compute:/opt/cuda/integration/nsight-systems:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
9 verbose lifecycle @joplin/app-desktop@1.7.11~dist: CWD: /home/lucky/Downloads/joplin/src/joplin-1.7.11/packages/app-desktop
10 silly lifecycle @joplin/app-desktop@1.7.11~dist: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'npm run electronRebuild && npx electron-builder "--publish=never" "--linux" "--x64" "--dir=dist/" "-c.electronDist=/usr/lib/electron" "-c.electronVersion=11.3.0"'
10 silly lifecycle ]
11 silly lifecycle @joplin/app-desktop@1.7.11~dist: Returned: code: 1  signal: null
12 info lifecycle @joplin/app-desktop@1.7.11~dist: Failed to exec dist script
13 verbose stack Error: @joplin/app-desktop@1.7.11 dist: `npm run electronRebuild && npx electron-builder "--publish=never" "--linux" "--x64" "--dir=dist/" "-c.electronDist=/usr/lib/electron" "-c.electronVersion=11.3.0"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (node:events:378:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (node:events:378:20)
13 verbose stack     at maybeClose (node:internal/child_process:1067:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
14 verbose pkgid @joplin/app-desktop@1.7.11
15 verbose cwd /home/lucky/Downloads/joplin/src/joplin-1.7.11/packages/app-desktop
16 verbose Linux 5.11.2-zen1-1-zen
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dist" "--" "--publish=never" "--linux" "--x64" "--dir=dist/" "-c.electronDist=/usr/lib/electron" "-c.electronVersion=11.3.0"
18 verbose node v15.10.0
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error @joplin/app-desktop@1.7.11 dist: `npm run electronRebuild && npx electron-builder "--publish=never" "--linux" "--x64" "--dir=dist/" "-c.electronDist=/usr/lib/electron" "-c.electronVersion=11.3.0"`
22 error Exit status 1
23 error Failed at the @joplin/app-desktop@1.7.11 dist script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by CalebJohn** [comment]
The only officially supported way to install Joplin desktop on Linux (any distro) is to use the AppImage format. You can download it directly from the [releases page](https://github.com/laurent22/joplin/releases/tag/v1.7.11), or use the below script

```
wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash
```

If you want to install using the AUR package, you'll [need to take it up with the package maintainer](https://github.com/laurent22/joplin/tree/v1.7.11#unsupported-methods).

**Comment by miku86** [comment]
And why did you remove the Issue template?

Which versions (arch, kernel etc.) do you use?
How do you try to install the packages?
How can we reproduce this?

**Comment by VIUBillyB** [comment]
I used the the version on Arch with the AUR repo to install Joplin and that worked nicely.
chaotic-aur/joplin 1.7.11-2 (joplin) [installed]
    A note taking and to-do application with synchronization capabilities - CLI App
