### ISSUE TITLE
CLI: TypeError lines[i].matchAll is not a function

### ISSUE THREAD

**Issue by Eothred** [laurent22/joplin#4696]
I opened the joplin CLI and hit the button "n" (to figure out how it works), and found that the app crashes 

## Environment

Joplin version: joplin 1.7.0 (prod)
Platform: Manjaro Linux
OS specifics: Linux mycomp 5.10.19-1-MANJARO #1 SMP PREEMPT Fri Feb 26 11:38:34 UTC 2021 x86_64 GNU/Linux

## Steps to reproduce

1.  Open Joplin CLI
2.  Click on "n"

## Describe what you expected to happen

No crash

## Stdout

```
% joplin
Unhandled promise rejection Promise {
  <rejected> TypeError: lines[i].matchAll is not a function
      at LinkSelector.findLinks (/usr/share/joplin/LinkSelector.js:32:32)
      at LinkSelector.updateText (/usr/share/joplin/LinkSelector.js:47:32)
      at LinkSelector.updateNote (/usr/share/joplin/LinkSelector.js:52:14)
      at LinkSelector.changeLink (/usr/share/joplin/LinkSelector.js:78:18)
      at AppGui.processFunctionCommand (/usr/share/joplin/app-gui.js:469:48)
      at Object.term.on (/usr/share/joplin/app-gui.js:798:12)
      at Function.NextGenEvents.listenerWrapper (/usr/share/joplin/node_modules/nextgen-events/lib/NextGenEvents.js:473:33)
      at Function.NextGenEvents.emitToOneListener (/usr/share/joplin/node_modules/nextgen-events/lib/NextGenEvents.js:788:17)
      at Function.NextGenEvents.emitEvent (/usr/share/joplin/node_modules/nextgen-events/lib/NextGenEvents.js:631:18)
      at Terminal.NextGenEvents.emit (/usr/share/joplin/node_modules/nextgen-events/lib/NextGenEvents.js:504:23) } reason: TypeError: lines[i].matchAll is not a function
    at LinkSelector.findLinks (/usr/share/joplin/LinkSelector.js:32:32)
    at LinkSelector.updateText (/usr/share/joplin/LinkSelector.js:47:32)
    at LinkSelector.updateNote (/usr/share/joplin/LinkSelector.js:52:14)
    at LinkSelector.changeLink (/usr/share/joplin/LinkSelector.js:78:18)
    at AppGui.processFunctionCommand (/usr/share/joplin/app-gui.js:469:48)
    at Object.term.on (/usr/share/joplin/app-gui.js:798:12)
    at Function.NextGenEvents.listenerWrapper (/usr/share/joplin/node_modules/nextgen-events/lib/NextGenEvents.js:473:33)
    at Function.NextGenEvents.emitToOneListener (/usr/share/joplin/node_modules/nextgen-events/lib/NextGenEvents.js:788:17)
    at Function.NextGenEvents.emitEvent (/usr/share/joplin/node_modules/nextgen-events/lib/NextGenEvents.js:631:18)
    at Terminal.NextGenEvents.emit (/usr/share/joplin/node_modules/nextgen-events/lib/NextGenEvents.js:504:23)
```
## Logfile

```
2021-03-17 16:10:30: App: "Profile directory: /home/user/.config/joplin"
2021-03-17 16:10:30: "Database was open successfully"
2021-03-17 16:10:30: "Checking for database schema update..."
2021-03-17 16:10:30: "Current database version", "{"version":34,"table_fields_version":34}"
2021-03-17 16:10:30: "Upgrading database from version 34"
2021-03-17 16:10:30: "New version: 34. Previously recorded version: 34"
2021-03-17 16:10:30: "KeychainService: checking if keychain supported"
2021-03-17 16:10:30: "KeychainService: check was already done - skipping. Supported:", "0"
2021-03-17 16:10:30: App: "Client ID: <hash>"
2021-03-17 16:10:30: "Trying to load 0 master keys..."
2021-03-17 16:10:30: "Loaded master keys: 0"
2021-03-17 16:10:30: "ResourceFetcher: Auto-add resources: Mode: always"
2021-03-17 16:10:30: "ResourceFetcher: Auto-added resources: 0"
2021-03-17 16:10:30: "Setting up recurrent sync with interval 300"
2021-03-17 16:10:30: App: "Refreshing notes:", "null", "null"
2021-03-17 16:10:30: "Trying to load 0 master keys..."
2021-03-17 16:10:30: "Loaded master keys: 0"
2021-03-17 16:10:30: "Scheduling sync operation...", "10000"
2021-03-17 16:10:30: "Setting up recurrent sync with interval 300"
2021-03-17 16:10:30: "Trying to load 0 master keys..."
2021-03-17 16:10:30: "Loaded master keys: 0"
2021-03-17 16:10:30: "Scheduling sync operation...", "10000"
2021-03-17 16:10:30: "Trying to load 0 master keys..."
2021-03-17 16:10:30: "Loaded master keys: 0"
2021-03-17 16:10:30: "Scheduling sync operation...", "10000"
2021-03-17 16:10:30: App: "Rebuilding items...", "null", "", "null"
2021-03-17 16:10:30: "RevisionService::runInBackground: Starting background service with revision collection interval 600000"
2021-03-17 16:10:30: App: "Rebuilding items...", "Folder", "<hash>", "null"
2021-03-17 16:10:30: App: "Refreshing notes:", "2", "<hash>"
2021-03-17 16:10:30: App: "Rebuilding items...", "Folder", "<hash>", "null"
```

**Comment by pompeiifreckles** [comment]
Hey I am not able to reproduce the issue, can I get some more details about this. Is it only specific to version 1.7.0 or is it also in 1.8.0. The dev branch is already in 1.8.0 so I don't know where I can get 1.7.0 version. I will try running the app on manjaro to make sure its not distro specific just in case and let you know here.

Joplin version: joplin 1.8.0 (dev)
Platform: Gentoo
OS specifics: Linux tux 5.4.97-gentoo #3 SMP Sun Feb 21 22:36:42 IST 2021 x86_64 AMD Ryzen 7 3800X 8-Core Processor AuthenticAMD GNU/Linux

**Comment by pompeiifreckles** [comment]
I also tried to recreate the bug with joplin v1.7.0 (dev) on gentoo but its working fine and  pressing 'n' does not trigger any app crashes

**Comment by tessus** [comment]
@pompeiifreckles the op was talking about the CLI version

**Comment by tessus** [comment]
The latest CLI version is 1.6.4.

If you are using anything other than 1.6.4, you are using a version from a packager or a portage system.
Thus please open issues with them.

**Comment by pompeiifreckles** [comment]
Nope, didn't encounter any problem, I used the latest release source from github, coz joplin is not packaged for gentoo. I also verified the version, infact double checked  for joplin cli version. Didn't see any crash.

**Comment by Eothred** [comment]
Hi, lots of feedback already, thanks for trying to reproduce.

Regarding the version, I ran `joplin version` which said 1.7.0, however my package says 1.7.11, from AUR. You can read the build script here: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=joplin (bash syntax, so you can probably understand which version is used without knowing about Arch/Manjaro)

I tested the 1.6.4 installed by the command `NPM_CONFIG_PREFIX=~/.joplin-bin npm install -g joplin`, and get same crash. Wild guess then I have something weird configured on my side. This one says 1.6.4 as you said.

```
% ~/.joplin-bin/bin/joplin 
Unhandled promise rejection Promise {
  <rejected> TypeError: lines[i].matchAll is not a function
      at LinkSelector.findLinks (/home/username/.joplin-bin/lib/node_modules/joplin/LinkSelector.js:32:32)
      at LinkSelector.updateText (/home/username/.joplin-bin/lib/node_modules/joplin/LinkSelector.js:47:32)
      at LinkSelector.updateNote (/home/username/.joplin-bin/lib/node_modules/joplin/LinkSelector.js:52:14)
      at LinkSelector.changeLink (/home/username/.joplin-bin/lib/node_modules/joplin/LinkSelector.js:78:18)
      at AppGui.processFunctionCommand (/home/username/.joplin-bin/lib/node_modules/joplin/app-gui.js:469:48)
      at Object.term.on (/home/username/.joplin-bin/lib/node_modules/joplin/app-gui.js:798:12)
      at Function.NextGenEvents.listenerWrapper (/home/username/.joplin-bin/lib/node_modules/joplin/node_modules/nextgen-events/lib/NextGenEvents.js:473:33)
      at Function.NextGenEvents.emitToOneListener (/home/username/.joplin-bin/lib/node_modules/joplin/node_modules/nextgen-events/lib/NextGenEvents.js:788:17)
      at Function.NextGenEvents.emitEvent (/home/username/.joplin-bin/lib/node_modules/joplin/node_modules/nextgen-events/lib/NextGenEvents.js:631:18)
      at Terminal.NextGenEvents.emit (/home/username/.joplin-bin/lib/node_modules/joplin/node_modules/nextgen-events/lib/NextGenEvents.js:504:23) } reason: TypeError: lines[i].matchAll is not a function
    at LinkSelector.findLinks (/home/username/.joplin-bin/lib/node_modules/joplin/LinkSelector.js:32:32)
    at LinkSelector.updateText (/home/username/.joplin-bin/lib/node_modules/joplin/LinkSelector.js:47:32)
    at LinkSelector.updateNote (/home/username/.joplin-bin/lib/node_modules/joplin/LinkSelector.js:52:14)
    at LinkSelector.changeLink (/home/username/.joplin-bin/lib/node_modules/joplin/LinkSelector.js:78:18)
    at AppGui.processFunctionCommand (/home/username/.joplin-bin/lib/node_modules/joplin/app-gui.js:469:48)
    at Object.term.on (/home/username/.joplin-bin/lib/node_modules/joplin/app-gui.js:798:12)
    at Function.NextGenEvents.listenerWrapper (/home/username/.joplin-bin/lib/node_modules/joplin/node_modules/nextgen-events/lib/NextGenEvents.js:473:33)
    at Function.NextGenEvents.emitToOneListener (/home/username/.joplin-bin/lib/node_modules/joplin/node_modules/nextgen-events/lib/NextGenEvents.js:788:17)
    at Function.NextGenEvents.emitEvent (/home/username/.joplin-bin/lib/node_modules/joplin/node_modules/nextgen-events/lib/NextGenEvents.js:631:18)
    at Terminal.NextGenEvents.emit (/home/username/.joplin-bin/lib/node_modules/joplin/node_modules/nextgen-events/lib/NextGenEvents.js:504:23)
```

**Comment by tessus** [comment]
I can't reproduce the error. Sometimes it doesn't work with the latest node versions. Another problem I've encountered was a build issue with npm 7.

I'm using the following versions and it works with them.

```
$ npm version
{
  npm: '6.14.11',
  ares: '1.16.1',
  brotli: '1.0.9',
  cldr: '37.0',
  icu: '67.1',
  llhttp: '2.1.3',
  modules: '83',
  napi: '7',
  nghttp2: '1.41.0',
  node: '14.15.0',
  openssl: '1.1.1g',
  tz: '2020a',
  unicode: '13.0',
  uv: '1.40.0',
  v8: '8.4.371.19-node.17',
  zlib: '1.2.11'
}
```

**Comment by roman-r-m** [comment]
Looks like this function (`matchAll`) is only available starting from node version 12:
https://stackoverflow.com/questions/55691536/does-node-js-support-the-string-matchall-method

**Comment by tessus** [comment]
Well, I hope the OP uses at least node 12....

From the docs:

<img width="224" alt="image" src="https://user-images.githubusercontent.com/223439/112022262-83132000-8b08-11eb-8050-952c9ffbde64.png">

**Comment by Eothred** [comment]
Damnit, that was my mistake then. I thought the package manager would take care of this, however I had accidentally an older nodejs lts (10.24) installed. Changed to the standard nodejs package and now all is fine.

On https://joplinapp.org/terminal/ it says 10+ is sufficient, but I guess that is for an older version then?

Apologies, and thanks for debugging.

**Comment by tessus** [comment]
> On https://joplinapp.org/terminal/ it says 10+ is sufficient, but I guess that is for an older version then?

Yes, we apparently forgot to update the terminal page, when we updated the main page. I'll update it soon.
