### ISSUE TITLE
Unexpected identifier error

### ISSUE THREAD

**Issue by astropanic** [laurent22/joplin#47]
### Operating system

- [ ] Windows
- [x ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [ ] Desktop
- [ ] Mobile
- [x ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

Just installed as instructed with:

`npm install -g joplin`

after:

`joplin` I get an stacktrace

*If there is an error, please copy and paste the full error message*

`/usr/local/lib/node_modules/joplin/app.js:47
	async guessTypeAndLoadItem(pattern, options = null) {
	      ^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/joplin/main.js:7:17)
    at Module._compile (module.js:571:32)
`

---

**Comment by jeffhiltz** [comment]
Duplicate: https://github.com/laurent22/joplin/issues/17
