### ISSUE TITLE
[Bug] Android app: Nextcloud URL expects the user to use %20 instead of space in path

### ISSUE THREAD

**Issue by milankni** [laurent22/joplin#470]
### Operating system
- Android

### Application
- Mobile

### Spaces in URL
If there is a space in Nextcloud URL, sync fails. The user has to use "https://nextcloud.example.org/remote.php/webdav/Some/path/with%20space" instead.
This is not obvious and it is not required in the Linux desktop app.

The Android app should transliterate spaces to standard URL notation automatically.

**Comment by milankni** [comment]
Interestingly, after migration from Evernote to the Desktop app (via ENEX files) and lot of hours of syncing of both Android app and desktop app, now the desktop app complains too:
```
2018-04-29 09:21:17: "Operations completed: "
2018-04-29 09:21:17: "Total folders: 1"
2018-04-29 09:21:17: "Total notes: 1"
2018-04-29 09:21:17: "Total resources: 0"
2018-04-29 09:21:17: "There was some errors:"
2018-04-29 09:21:17: "Error: href /remote.php/webdav/Documents/Joplin%20Notes/ not in baseUrl https://nextcloud.example.orgt/r
emote.php/webdav/Documents/Joplin Notes nor relativeBaseUrl /remote.php/webdav/Documents/Joplin Notes
Error: href /remote.php/webdav/Documents/Joplin%20Notes/ not in baseUrl https://nextcloud.example.org/remote.php/webdav/Docum
ents/Joplin Notes nor relativeBaseUrl /remote.php/webdav/Documents/Joplin Notes
    at FileApiDriverWebDav.hrefToRelativePath_ (/tmp/.mount_JoplinBUvKW3/app/resources/app/lib/file-api-driver-webdav.js
:96:10)
    at FileApiDriverWebDav.statsFromResources_ (/tmp/.mount_JoplinBUvKW3/app/resources/app/lib/file-api-driver-webdav.js
:109:22)
    at FileApiDriverWebDav.list (/tmp/.mount_JoplinBUvKW3/app/resources/app/lib/file-api-driver-webdav.js:274:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)"
```
However, in the desktop app it worked just fine to use regular space in URL. Until now.

I tried to search all the files in Nextcould local file system for "%20" and did not find anything. So I guess the URL is not stored in any file (I do not use encryption) so the bug may not be influenced by the URL set in the Android app. (But then again, who knows without studying the code...)

Changing the URL also in the desktop app to have %20 instead of spaces resolved the problem, eventually.

P.S. Debugging console did not show anything on sync.
