### ISSUE TITLE
Fatal Error: SQLITE_NOTADB: file is not a database

### ISSUE THREAD

**Issue by hic090** [laurent22/joplin#4838]
Hi there, just wanted to test out Joplin but didn't get very far -- see below. The error messages are slightly different for versions 1.7.10, 1.7.11 and 1.8.1:

## Description
SQL-related Fatal Error occurs at first start after installing Joplin 1.7.10, 1.7.11 and 1.8.11 on macOS 11.2.3.

## Environment

Joplin version: 1.7.10, 1.7.11 and 1.8.1
Platform: macOS 
OS specifics: 11.2.3

## Steps to reproduce

1. Install app
2. Open app
3. Error occurs immediately

## Error Log for 1.7.10 and 1.7.11

Fatal error:

Error: SQLITE_NOTADB: file is not a database: CREATE TABLE folders (id TEXT PRIMARY KEY, title TEXT NOT NULL DEFAULT "", created_time INT NOT NULL, updated_time INT NOT NULL);

Error: Error: SQLITE_NOTADB: file is not a database: CREATE TABLE folders (id TEXT PRIMARY KEY, title TEXT NOT NULL DEFAULT "", created_time INT NOT NULL, updated_time INT NOT NULL);
at DatabaseDriverNode.sqliteErrorToJsError (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/database-driver-node.js:21:18)
at JoplinDatabase.sqliteErrorToJsError (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/database.js:26:24)
at JoplinDatabase.tryCall (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/database.js:114:17)
at async JoplinDatabase.transactionExecBatch (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/database.js:174:5)
at async JoplinDatabase.upgradeDatabase (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/joplin-database.js:858:5)
at async JoplinDatabase.initialize (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/joplin-database.js:946:22)

------------------------
## Error Log for 1.8.1

SQLITE_NOTADB: file is not a database: CREATE TABLE folders (id TEXT PRIMARY KEY, title TEXT NOT NULL DEFAULT "", created_time INT NOT NULL, updated_time INT NOT NULL);

Error: Error: SQLITE_NOTADB: file is not a database: CREATE TABLE folders (id TEXT PRIMARY KEY, title TEXT NOT NULL DEFAULT "", created_time INT NOT NULL, updated_time INT NOT NULL);
at DatabaseDriverNode.sqliteErrorToJsError (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/database-driver-node.js:21:18)
at JoplinDatabase.sqliteErrorToJsError (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/database.js:34:30)
at JoplinDatabase.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/database.js:124:36)
at Generator.throw (<anonymous>)
at rejected (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/database.js:6:65)**

**Comment by laurent22** [comment]
For some reason your database file, which is in ~/.config/joplin-desktop/database.sqlite is corrupted.

**Comment by hffaust** [comment]
I had this happen on a windows system and I had to delete C:\Users\USERNAME\.config\joplin-desktop  and then uninstall and reinstall joplin to fix it.... Hopefully you have all your notes syncing somewhere otherwise they might be gone forever.
