### ISSUE TITLE
Persistent message: Some items cannot be synchronized. View them now

### ISSUE THREAD

**Issue by armaccloud** [laurent22/joplin#4862]
## Description
Since I reinstalled my laptop and with it, joplin, it gives a sync error after getting all the notes from Nextcloud.

## Environment

Joplin version: 1.7.11
Platform: Linux
OS specifics: Pop!_OS 20.10

## Steps to reproduce

1. Clear & Reinstall Joplin
2. Enter the decryption password in the settings while synchronization is happening
3. Verify that one or more items don't get decrypted well

## Describe what you expected to happen
For the synchronization to be well executed without errors, or provide a hint to fix it.

## What I have tried

- Removed the attachment in the Android app, sync
- Synced the desktop app > no result
- Removed the note in the Android app, sync
- Synced the desktop app > no result
- Removed the resource from the nextcloud server
- Synced the desktop app > no result
- Tried the option to "retry" in the desktop app > no result

## Screenshots
![image](https://user-images.githubusercontent.com/9272078/115293630-db652e00-a157-11eb-9f76-ff5ad355ac25.png)
![image](https://user-images.githubusercontent.com/9272078/115293670-e455ff80-a157-11eb-9c0a-336e3c05835e.png)

### Logging
<details>
<summary>Joplin Log</summary>

```
2021-04-17 18:34:19: "DecryptionWorker: starting decryption..."
2021-04-17 18:34:19: "DecryptionWorker: error for: a84f05d2c6af415fb76276f79119995b (resources)", "Error: Error: ENOENT: no such file or directory, open '/home/arno/.config/joplin-desktop/resources/a84f05d2c6af415fb76276f79119995b.crypted'. Path: /home/arno/.config/joplin-desktop/resources/a84f05d2c6af415fb76276f79119995b.crypted
Code: ENOENT
Error: Error: ENOENT: no such file or directory, open '/home/arno/.config/joplin-desktop/resources/a84f05d2c6af415fb76276f79119995b.crypted'. Path: /home/arno/.config/joplin-desktop/resources/a84f05d2c6af415fb76276f79119995b.crypted
    at FsDriverNode.fsErrorToJsError_ (/app/joplin-desktop/resources/app/node_modules/@joplin/lib/fs-driver-node.js:22:24)
    at FsDriverNode.<anonymous> (/app/joplin-desktop/resources/app/node_modules/@joplin/lib/fs-driver-node.js:172:28)
    at Generator.throw (<anonymous>)
    at rejected (/app/joplin-desktop/resources/app/node_modules/@joplin/lib/fs-driver-node.js:6:65)", "{"id":"a84f05d2c6af415fb76276f79119995b","title":"Eco-Village Asuchillo - English - CURRENT.pdf","mime":"application/pdf","filename":"","created_time":1597955423381,"updated_time":1597955423381,"user_created_time":1597955423381,"user_updated_time":1597955423381,"file_extension":"pdf","encryption_cipher_text":"","encryption_applied":0,"encryption_blob_encrypted":1,"size":5471138,"is_shared":0,"type_":4}"
2021-04-17 18:34:19: "DecryptionWorker: completed decryption."
2021-04-17 18:35:11: "RevisionService::maintenance: Starting..."
2021-04-17 18:35:11: "RevisionService::maintenance: Service is enabled"
2021-04-17 18:35:11: "RevisionService::collectRevisions: Created revisions for 5 notes"
2021-04-17 18:35:12: "RevisionService::maintenance: Done in 1622ms"
2021-04-17 18:37:24: "Running background sync on timer..."
2021-04-17 18:37:24: "Preparing scheduled sync"
2021-04-17 18:37:24: "Starting scheduled sync"
2021-04-17 18:37:24: "Synchronisation is already in progress. State: in_progress"
2021-04-17 18:41:58: "ResourceFetcher: Could not download resource: 6f5635b038a24b0b84499ccb6bca2a5f", "Error: connect ETIMEDOUT 46.165.196.66:443
Code: ETIMEDOUT
Error: connect ETIMEDOUT 46.165.196.66:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)"
2021-04-17 18:41:59: "DecryptionWorker: starting decryption..."
2021-04-17 18:41:59: "DecryptionWorker: error for: a84f05d2c6af415fb76276f79119995b (resources)", "Error: Error: ENOENT: no such file or directory, open '/home/arno/.config/joplin-desktop/resources/a84f05d2c6af415fb76276f79119995b.crypted'. Path: /home/arno/.config/joplin-desktop/resources/a84f05d2c6af415fb76276f79119995b.crypted
Code: ENOENT
Error: Error: ENOENT: no such file or directory, open '/home/arno/.config/joplin-desktop/resources/a84f05d2c6af415fb76276f79119995b.crypted'. Path: /home/arno/.config/joplin-desktop/resources/a84f05d2c6af415fb76276f79119995b.crypted
    at FsDriverNode.fsErrorToJsError_ (/app/joplin-desktop/resources/app/node_modules/@joplin/lib/fs-driver-node.js:22:24)
    at FsDriverNode.<anonymous> (/app/joplin-desktop/resources/app/node_modules/@joplin/lib/fs-driver-node.js:172:28)
    at Generator.throw (<anonymous>)
    at rejected (/app/joplin-desktop/resources/app/node_modules/@joplin/lib/fs-driver-node.js:6:65)", "{"id":"a84f05d2c6af415fb76276f79119995b","title":"Eco-Village Asuchillo - English - CURRENT.pdf","mime":"application/pdf","filename":"","created_time":1597955423381,"updated_time":1597955423381,"user_created_time":1597955423381,"user_updated_time":1597955423381,"file_extension":"pdf","encryption_cipher_text":"","encryption_applied":0,"encryption_blob_encrypted":1,"size":5471138,"is_shared":0,"type_":4}"
2021-04-17 18:41:59: "DecryptionWorker: completed decryption."
2021-04-17 18:42:23: "ResourceFetcher: Could not download resource: 83de7192509540dc94c8a3d45b61b7e9", "Error: connect ETIMEDOUT 46.165.196.66:443
Code: ETIMEDOUT
Error: connect ETIMEDOUT 46.165.196.66:443
```
</details>

Seems to be the same: #3828

**Comment by armaccloud** [comment]
What I have done to solve this issue is the following;

### Reset
**Computer**
- Full export (JEX)
- Removed sync connection
- Removed encryption
- Removed the .Joplin Desktop folder from the computer

**Joplin Android App**
- Removed storage + cache (total reset)

**On the remote server**
- Removed sync folder

### Reinstall
On the remote server
- Created .Joplin folder

**Computer**
- Imported JEX file
- Added sync connection to remote server
- Enabled encryption
- Initiated sync

**Joplin Android App**
- Added sync connection to remote server
- Entered decryption password
- Initiated sync
