### ISSUE TITLE
md.options is not a function

### ISSUE THREAD

**Issue by mymilkbottles** [laurent22/joplin#4871]
Error
Joplin encountered a fatal error and could not continue. To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

Message
md.options is not a function

Version info
Joplin for Desktop

Copyright © 2016-2021 Laurent Cozic
Joplin 1.6.7 (prod, darwin)

客户端 ID: 8e93720c2cfb4e03a7a9f936f8c95d64
同步版本: 2
配置文件版本: 34
支持的密钥链: 是

修订: b74b849 (master)
Stack trace
TypeError: md.options is not a function
    at ConfigScreenComponent.settingToComponent (/Applications/Joplin.app/Contents/Resources/app.asar/gui/ConfigScreen/ConfigScreen.js:331:39)
    at createSettingComponents (/Applications/Joplin.app/Contents/Resources/app.asar/gui/ConfigScreen/ConfigScreen.js:144:42)
    at ConfigScreenComponent.sectionToComponent (/Applications/Joplin.app/Contents/Resources/app.asar/gui/ConfigScreen/ConfigScreen.js:149:30)
    at Object.shared.settingsToComponents2 (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/components/shared/config-shared.js:184:28)
    at ConfigScreenComponent.render (/Applications/Joplin.app/Contents/Resources/app.asar/gui/ConfigScreen/ConfigScreen.js:528:37)
    at finishClassComponent (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:17039:31)
    at updateClassComponent (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:16994:24)
    at beginWork$1 (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:18505:16)
    at HTMLUnknownElement.callCallback (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:347:14)
    at Object.invokeGuardedCallbackDev (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:397:16)
Component stack

    in ConfigScreenComponent (created by Connect(ConfigScreenComponent))
    in Connect(ConfigScreenComponent) (created by NavigatorComponent)
    in div (created by NavigatorComponent)
    in NavigatorComponent (created by Connect(NavigatorComponent))
    in Connect(NavigatorComponent) (created by RootComponent)
    in ThemeProvider (created by RootComponent)
    in StyleSheetManager (created by RootComponent)
    in RootComponent (created by Connect(RootComponent))
    in Connect(RootComponent)
    in ErrorBoundary
    in Provider

**Comment by laurent22** [comment]
This is fixed in 1.7 or 1.8

**Comment by mymilkbottles** [comment]
ok, thx!
