### ISSUE TITLE
Sync timeout with WebDAV at files near 10Mb.

### ISSUE THREAD

**Issue by LightTemplar** [laurent22/joplin#4880]
Syncing never ends, it freezes at some point and no counters are changed. In the log.txt I see timeout on the resource, which is 8.8 Mb.

The bug #869 looks the same, though I don't have E2EE enabled. And there were also a question on the forum: https://discourse.joplinapp.org/t/synchronisation-with-nextcloud-stops/5275

My log looks pretty much like those. I checked that resource, it is downloaded without any problem. I have attached this GIF here.

## Environment
Joplin 1.7.11 (prod, linux)

Sync Version: 2
Profile Version: 34
Keychain Supported: No
Revision: f560563 (master)

Platform: Linux
OS specifics: Kubuntu 20.04.1

## Steps to reproduce

1. Create a note, add some media into it big enough, like 9Mb. Like that one GIF, which I attached here
2. try to sync via webdav.

## Describe what you expected to happen
Syncing goes well

## Logfile

```
2021-04-22 20:18:12: "Saving settings..."
2021-04-22 20:18:12: "Settings have been saved."
2021-04-22 20:18:24: FileApi: "list "
2021-04-22 20:18:25: FileApi: "list "
2021-04-22 20:18:25: FileApi: "list "
2021-04-22 20:18:25: FileApi: "put locks/sync_desktop_2f79b413b8be411091430d05c3e9a98a.json", "null"
2021-04-22 20:18:45: FileApi: "list "
2021-04-22 20:18:46: FileApi: "list "
2021-04-22 20:18:46: "FetchError: network timeout at: https://webdav.yandex.ru/joplin/.resource/2c7e13d0898a4b73951fccfd608b2e4e
FetchError: network timeout at: https://webdav.yandex.ru/joplin/.resource/2c7e13d0898a4b73951fccfd608b2e4e
    at /tmp/.mount_JoplinQUCcTc/resources/app.asar/node_modules/@joplin/lib/node_modules/node-fetch/index.js:126:13"
2021-04-22 20:18:46: FileApi: "delete locks/sync_desktop_2f79b413b8be411091430d05c3e9a98a.json"
2021-04-22 20:18:47: "Sync: finished: Synchronisation finished [1619115011230]"
2021-04-22 20:18:47: "Operations completed: "
2021-04-22 20:18:47: "createRemote: 1"
2021-04-22 20:18:47: "Total folders: 18"
2021-04-22 20:18:47: "Total notes: 225"
2021-04-22 20:18:47: "Total resources: 796"
2021-04-22 20:18:47: "Setting up recurrent sync with interval 300"
2021-04-22 20:18:47: "Sync has finished and note has never been changed - reloading it"
2021-04-22 20:18:48: "DecryptionWorker: cannot start because no master key is currently loaded."
2021-04-22 20:23:47: "Running background sync on timer..."
2021-04-22 20:23:47: "Scheduling sync operation...", "0"
2021-04-22 20:23:47: "Preparing scheduled sync"
2021-04-22 20:23:47: "Starting scheduled sync"
2021-04-22 20:23:47: "Sync: starting: Starting synchronisation to target 6... [1619115827959]"
2021-04-22 20:23:48: FileApi: "get info.json"
2021-04-22 20:23:48: "Sync target info:", "{"version":2}"
2021-04-22 20:23:48: FileApi: "list "
2021-04-22 20:23:48: FileApi: "list "
2021-04-22 20:23:48: FileApi: "put temp/timeCheck26021.txt", "null"
2021-04-22 20:23:50: FileApi: "stat temp/timeCheck26021.txt"
2021-04-22 20:23:50: FileApi: "delete temp/timeCheck26021.txt"
2021-04-22 20:23:50: FileApi: "put locks/sync_desktop_2f79b413b8be411091430d05c3e9a98a.json", "null"
2021-04-22 20:23:52: FileApi: "list "
2021-04-22 20:23:52: FileApi: "list "
2021-04-22 20:23:53: FileApi: "stat 2c7e13d0898a4b73951fccfd608b2e4e.md"
2021-04-22 20:23:53: "Sync: createRemote: remote does not exist, and local is new and has never been synced: Resource: (Local 2c7e13d0898a4b73951fccfd608b2e4e)"
2021-04-22 20:23:53: FileApi: "put .resource/2c7e13d0898a4b73951fccfd608b2e4e", "{"path":"/home/alexander/.config/joplin-desktop/resources/2c7e13d0898a4b73951fccfd608b2e4e.gif","source":"file"}"
2021-04-22 20:24:53: FileApi: "list "
2021-04-22 20:24:55: FileApi: "list "
2021-04-22 20:24:55: FileApi: "list "
2021-04-22 20:24:55: FileApi: "put locks/sync_desktop_2f79b413b8be411091430d05c3e9a98a.json", "null"
2021-04-22 20:25:53: FileApi: "list "
2021-04-22 20:25:53: FileApi: "list "
2021-04-22 20:25:53: FileApi: "list "
2021-04-22 20:25:54: FileApi: "put locks/sync_desktop_2f79b413b8be411091430d05c3e9a98a.json", "null"
2021-04-22 20:26:53: FileApi: "list "
2021-04-22 20:26:54: FileApi: "list "
2021-04-22 20:26:54: FileApi: "list "
2021-04-22 20:26:54: FileApi: "put locks/sync_desktop_2f79b413b8be411091430d05c3e9a98a.json", "null"
2021-04-22 20:27:17: "RevisionService::maintenance: Starting..."
2021-04-22 20:27:17: "RevisionService::maintenance: Service is enabled"
2021-04-22 20:27:17: "RevisionService::collectRevisions: Created revisions for 0 notes"
2021-04-22 20:27:17: "RevisionService::maintenance: Done in 119ms"
2021-04-22 20:27:53: FileApi: "list "
2021-04-22 20:27:53: FileApi: "list "
2021-04-22 20:27:53: FileApi: "list "
2021-04-22 20:27:54: FileApi: "put locks/sync_desktop_2f79b413b8be411091430d05c3e9a98a.json", "null"
2021-04-22 20:28:47: "Running background sync on timer..."
2021-04-22 20:28:47: "Scheduling sync operation...", "0"
2021-04-22 20:28:47: "Preparing scheduled sync"
2021-04-22 20:28:47: "Starting scheduled sync"
2021-04-22 20:28:47: "Synchronisation is already in progress. State: in_progress"
2021-04-22 20:28:47: "Setting up recurrent sync with interval 300"
2021-04-22 20:28:53: FileApi: "list "
2021-04-22 20:28:53: FileApi: "list "
2021-04-22 20:28:53: FileApi: "list "
2021-04-22 20:28:54: FileApi: "put locks/sync_desktop_2f79b413b8be411091430d05c3e9a98a.json", "null"
2021-04-22 20:29:53: FileApi: "list "
2021-04-22 20:29:54: FileApi: "list "
2021-04-22 20:29:54: FileApi: "list "
2021-04-22 20:29:54: FileApi: "put locks/sync_desktop_2f79b413b8be411091430d05c3e9a98a.json", "null"
2021-04-22 20:30:53: FileApi: "list "
2021-04-22 20:30:54: FileApi: "list "
2021-04-22 20:30:54: FileApi: "list "
2021-04-22 20:30:54: FileApi: "put locks/sync_desktop_2f79b413b8be411091430d05c3e9a98a.json", "null"
2021-04-22 20:31:53: FileApi: "list "
2021-04-22 20:31:54: FileApi: "list "
2021-04-22 20:31:54: FileApi: "list "
2021-04-22 20:31:54: FileApi: "put locks/sync_desktop_2f79b413b8be411091430d05c3e9a98a.json", "null"
2021-04-22 20:32:18: FileApi: "list "
2021-04-22 20:32:19: FileApi: "list "
2021-04-22 20:32:19: "FetchError: network timeout at: https://webdav.yandex.ru/joplin/.resource/2c7e13d0898a4b73951fccfd608b2e4e
FetchError: network timeout at: https://webdav.yandex.ru/joplin/.resource/2c7e13d0898a4b73951fccfd608b2e4e
    at /tmp/.mount_JoplinQUCcTc/resources/app.asar/node_modules/@joplin/lib/node_modules/node-fetch/index.js:126:13"
2021-04-22 20:32:19: FileApi: "delete locks/sync_desktop_2f79b413b8be411091430d05c3e9a98a.json"
2021-04-22 20:32:20: "Sync: finished: Synchronisation finished [1619115827959]"
2021-04-22 20:32:20: "Operations completed: "
2021-04-22 20:32:20: "createRemote: 1"
2021-04-22 20:32:20: "Total folders: 18"
2021-04-22 20:32:20: "Total notes: 225"
2021-04-22 20:32:20: "Total resources: 796"
2021-04-22 20:32:20: "Setting up recurrent sync with interval 300"
2021-04-22 20:32:21: "DecryptionWorker: cannot start because no master key is currently loaded."
2021-04-22 20:33:06: "Sync has finished and note has never been changed - reloading it"


```
![d6cec9bc8b9c439b82f508761868ee46](https://user-images.githubusercontent.com/453783/115765046-8f5bf880-a3a6-11eb-8655-7d0ac3c6fc1f.gif)

**Comment by laurent22** [comment]
Most likely an issue with the Nextcloud provider.

**Comment by LightTemplar** [comment]
My issue isn't with an ordinary Nextcloud provider, this is a Yandex.Disk with WebDAV access, the biggest Russian file hosting service. And, as I said, I have downloaded that file via WebDAV without any problem. 

Is there a tool or another possibility to check it more precisely? If it really relays on Yandex I could then file them a report.

**Comment by roman-r-m** [comment]
> Is there a tool or another possibility to check it more precisely? If it really relays on Yandex I could then file them a report.

If you run with debug enabled, I think it'll print request headers in log, this might help.
You can also try the latest pre-release, I've made some improvements related to WebDAV there, though from your description it does not look like it's related.

How do you set up WebDAV there anyway?

**Comment by laurent22** [comment]
It could be that it's throttling down when there are too many connections. Maybe try to reduce the max connections down to 1 in the options.

**Comment by LightTemplar** [comment]
I have tried the pre-release and set max connections to 1 - the problem is still here.

and I checked in debugger, method "PUT", not "GET" gives the timeout.
And, I've researched a bit: there is an upload problem with Yandex Disk: https://with.raidrive.com/t/webdav-upload-problem-warn-waituploadposition-upload-wait-timeout/2033/5
I don't know if there is a way to solve this problem :(

> How do you set up WebDAV there anyway?
url: https://webdav.yandex.ru/your_sync_folder
login and password as they are.

**Comment by laurent22** [comment]
Yes as suspected they are doing something to restrict their API in some cases. They want to prevent backup to their cloud, but a side effect of this is that it's pretty much unusable for Joplin.

**Comment by roman-r-m** [comment]
>  I don't know if there is a way to solve this problem :(

I think they have a desktop app? Maybe use it in combination with  file system sync?

**Comment by LightTemplar** [comment]
> I think they have a desktop app? Maybe use it in combination with file system sync?

This could a workaround, if it also would work on android. So, it seems, I have to change my backup service. 
I saw, you have a server part now. I'm looking forward to the release of it!
