### ISSUE TITLE
Upgrade error

### ISSUE THREAD

**Issue by xiaoxiao9689** [laurent22/joplin#4892]
Error
The sync target could not be upgraded due to an error. For support, please copy the complete content of this page and paste it in the forum: https://discourse.joplinapp.org/

The full error was:

request to https://api.dropboxapi.com/2/files/create_folder_v2 failed, reason: connect ETIMEDOUT 74.86.151.162:443

FetchError: request to https://api.dropboxapi.com/2/files/create_folder_v2 failed, reason: connect ETIMEDOUT 74.86.151.162:443
    at ClientRequest.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:310:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by roman-r-m** [comment]
Just a network timeout when connecting to Dropbox, does not seem to be an issue with Joplin. Maybe try on another network?
