### ISSUE TITLE
Sharing a note via Joplin Server fails due to app trying to use NextCloud

### ISSUE THREAD

**Issue by Someguy123** [laurent22/joplin#4895]
I've setup Joplin Server 1.8.2 on my own server, and pointed my desktop and mobile Joplin apps at the server without issues, however, when I right click on a note and press "Share note", followed by "Copy Shareable Link", I get an error complaining about it being unable to connect to the Joplin Nextcloud App, as per this screenshot:

<img width="481" alt="image" src="https://user-images.githubusercontent.com/1267260/116289445-66fb4200-a78a-11eb-80f7-7830ffde2a33.png">

I have previously used the following synchronisation methods over the past few months, in order:

1. Dropbox
2. WebDAV (not nextcloud)
3. back to Dropbox
4. NextCloud (without the joplin app since it doesn't work on modern nextcloud)
5. Joplin Server

I've cleared the configuration boxes for WebDAV and Nextcloud under Synchronisation, to try and make sure Joplin has no reason to use either of them - but it hasn't helped.

According to the docs, sharing is definitely supported in the Joplin Server: https://joplinapp.org/spec/server_sharing/

## Environment

Joplin version: 1.7.11
Platform: macOS
OS specifics: macOS Mojave (10.14.6) running on an Intel 64-bit iMac Pro

Joplin Server version: 1.8.2 (commit: 2531e8945)
NodeJS: v12.22.1

## Steps to reproduce

1. Configure Joplin desktop app to use Joplin Server
2. Right click on a note and press "Share Note"
3. Click "Copy shareable link"
4. The error occurs.

## Describe what you expected to happen

The note to be shared publicly via Joplin Server, and the link copied to my clipboard.

## Logfile

```
2021-04-27 18:47:31: "DecryptionWorker: completed decryption."
2021-04-27 18:47:31: "Starting scheduled sync"
2021-04-27 18:47:32: "Sync target info:", "{"version":2}"
2021-04-27 18:47:33: "Operations completed: "
2021-04-27 18:47:33: "fetchingTotal: -"
2021-04-27 18:47:33: "Total folders: 9"
2021-04-27 18:47:33: "Total notes: 889"
2021-04-27 18:47:33: "Total resources: 472"
2021-04-27 18:47:33: "Updating all notifications..."
2021-04-27 18:47:33: "Garbage collecting alarms..."
2021-04-27 18:47:34: "RevisionService::maintenance: Starting..."
2021-04-27 18:47:34: "RevisionService::maintenance: Service is enabled"
2021-04-27 18:47:34: "RevisionService::collectRevisions: Created revisions for 0 notes"
2021-04-27 18:47:34: "RevisionService::maintenance: Done in 106ms"
2021-04-27 18:47:34: "DecryptionWorker: starting decryption..."
2021-04-27 18:47:34: "DecryptionWorker: completed decryption."
2021-04-27 18:47:37: "ShareNoteDialog: Cannot share note:", "Error: Unsupported WebDAV URL format: https://cloud.someguy123.net/remote.php/dav/files/chris/Joplin
Error: Unsupported WebDAV URL format: https://cloud.someguy123.net/remote.php/dav/files/chris/Joplin
    at Function.baseUrlFromNextcloudWebDavUrl (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/JoplinServerApi.js:60:19)
    at Object.baseUrl (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/SyncTargetNextcloud.js:59:35)
    at JoplinServerApi.baseUrl (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/JoplinServerApi.js:53:43)
    at JoplinServerApi.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/JoplinServerApi.js:117:33)
    at Generator.next (<anonymous>)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/JoplinServerApi.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/JoplinServerApi.js:4:12)
    at JoplinServerApi.exec (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/JoplinServerApi.js:99:16)
    at /Applications/Joplin.app/Contents/Resources/app.asar/gui/ShareNoteDialog.js:101:46"
2021-04-27 18:47:44: "SearchEngine: Updating FTS table..."
2021-04-27 18:47:44: "SearchEngine: Updated FTS table in 1ms. Inserted: 0. Deleted: 0"
2021-04-27 18:48:00: "ResourceService::indexNoteResources: Start"
2021-04-27 18:48:00: "ResourceService::indexNoteResources: Completed"
2021-04-27 18:48:00: "ResourceService::deleteOrphanResources:", "[]"
2021-04-27 18:49:38: "Preparing scheduled sync"
2021-04-27 18:49:38: "Starting scheduled sync"
2021-04-27 18:49:39: "Sync target info:", "{"version":2}"
2021-04-27 18:49:40: "TaskQueue.stop: syncDownload: waiting for tasks to complete: 0"
2021-04-27 18:49:40: "TaskQueue.stop: syncDownload: Done, waited for 0"
2021-04-27 18:49:40: "Operations completed: "
2021-04-27 18:49:40: "updateRemote: 1"
2021-04-27 18:49:40: "fetchingTotal: 1"
2021-04-27 18:49:40: "fetchingProcessed: 1"
2021-04-27 18:49:40: "Total folders: 9"
2021-04-27 18:49:40: "Total notes: 889"
2021-04-27 18:49:40: "Total resources: 472"
2021-04-27 18:49:41: "DecryptionWorker: starting decryption..."
2021-04-27 18:49:41: "DecryptionWorker: completed decryption."
2021-04-27 18:49:44: "ShareNoteDialog: Cannot share note:", "Error: Unsupported WebDAV URL format: https://cloud.someguy123.net/remote.php/dav/files/chris/Joplin
Error: Unsupported WebDAV URL format: https://cloud.someguy123.net/remote.php/dav/files/chris/Joplin
    at Function.baseUrlFromNextcloudWebDavUrl (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/JoplinServerApi.js:60:19)
    at Object.baseUrl (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/SyncTargetNextcloud.js:59:35)
    at JoplinServerApi.baseUrl (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/JoplinServerApi.js:53:43)
    at JoplinServerApi.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/JoplinServerApi.js:117:33)
    at Generator.next (<anonymous>)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/JoplinServerApi.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/JoplinServerApi.js:4:12)
    at JoplinServerApi.exec (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/JoplinServerApi.js:99:16)
    at /Applications/Joplin.app/Contents/Resources/app.asar/gui/ShareNoteDialog.js:101:46"
2021-04-27 18:49:48: "SearchEngine: Updating FTS table..."
2021-04-27 18:49:48: "SearchEngine: Updated FTS table in 26ms. Inserted: 1. Deleted: 0"
2021-04-27 18:50:42: "Could not set setting on the keychain. Will be saved to database instead: sync.5.password:", "Error: Password is required.
Error: Password is required.
    at checkRequired (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/keytar/lib/keytar.js:5:11)
    at Object.setPassword (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/keytar/lib/keytar.js:20:5)
    at KeychainServiceDriver.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/keychain/KeychainServiceDriver.node.js:19:43)
    at Generator.next (<anonymous>)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/keychain/KeychainServiceDriver.node.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/keychain/KeychainServiceDriver.node.js:4:12)
    at KeychainServiceDriver.setPassword (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/keychain/KeychainServiceDriver.node.js:16:16)
    at KeychainService.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/keychain/KeychainService.js:45:32)
    at Generator.next (<anonymous>)"
2021-04-27 18:50:48: "Could not set setting on the keychain. Will be saved to database instead: sync.5.password:", "Error: Password is required.
Error: Password is required.
    at checkRequired (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/keytar/lib/keytar.js:5:11)
    at Object.setPassword (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/keytar/lib/keytar.js:20:5)
    at KeychainServiceDriver.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/keychain/KeychainServiceDriver.node.js:19:43)
    at Generator.next (<anonymous>)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/keychain/KeychainServiceDriver.node.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/keychain/KeychainServiceDriver.node.js:4:12)
    at KeychainServiceDriver.setPassword (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/keychain/KeychainServiceDriver.node.js:16:16)
    at KeychainService.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/keychain/KeychainService.js:45:32)
    at Generator.next (<anonymous>)"
2021-04-27 18:50:49: "Could not set setting on the keychain. Will be saved to database instead: sync.5.password:", "Error: Password is required.
Error: Password is required.
    at checkRequired (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/keytar/lib/keytar.js:5:11)
    at Object.setPassword (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/keytar/lib/keytar.js:20:5)
    at KeychainServiceDriver.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/keychain/KeychainServiceDriver.node.js:19:43)
    at Generator.next (<anonymous>)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/keychain/KeychainServiceDriver.node.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/keychain/KeychainServiceDriver.node.js:4:12)
    at KeychainServiceDriver.setPassword (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/keychain/KeychainServiceDriver.node.js:16:16)
    at KeychainService.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/keychain/KeychainService.js:45:32)
    at Generator.next (<anonymous>)"
2021-04-27 18:50:56: "ShareNoteDialog: Cannot share note:", "Error: Unsupported WebDAV URL format: 
Error: Unsupported WebDAV URL format: 
    at Function.baseUrlFromNextcloudWebDavUrl (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/JoplinServerApi.js:60:19)
    at Object.baseUrl (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/SyncTargetNextcloud.js:59:35)
    at JoplinServerApi.baseUrl (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/JoplinServerApi.js:53:43)
    at JoplinServerApi.syncTargetId (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/JoplinServerApi.js:66:82)
    at /Applications/Joplin.app/Contents/Resources/app.asar/gui/ShareNoteDialog.js:97:42
    at Generator.next (<anonymous>)
    at fulfilled (/Applications/Joplin.app/Contents/Resources/app.asar/gui/ShareNoteDialog.js:5:58)"
2021-04-27 18:51:36: "Could not set setting on the keychain. Will be saved to database instead: sync.5.password:", "Error: Password is required.
Error: Password is required.
    at checkRequired (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/keytar/lib/keytar.js:5:11)
    at Object.setPassword (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/keytar/lib/keytar.js:20:5)
    at KeychainServiceDriver.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/keychain/KeychainServiceDriver.node.js:19:43)
    at Generator.next (<anonymous>)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/keychain/KeychainServiceDriver.node.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/keychain/KeychainServiceDriver.node.js:4:12)
    at KeychainServiceDriver.setPassword (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/keychain/KeychainServiceDriver.node.js:16:16)
    at KeychainService.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/keychain/KeychainService.js:45:32)
    at Generator.next (<anonymous>)"
2021-04-27 18:51:42: "ShareNoteDialog: Cannot share note:", "Error: Unsupported WebDAV URL format: 
Error: Unsupported WebDAV URL format: 
    at Function.baseUrlFromNextcloudWebDavUrl (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/JoplinServerApi.js:60:19)
    at Object.baseUrl (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/SyncTargetNextcloud.js:59:35)
    at JoplinServerApi.baseUrl (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/JoplinServerApi.js:53:43)
    at JoplinServerApi.syncTargetId (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/JoplinServerApi.js:66:82)
    at /Applications/Joplin.app/Contents/Resources/app.asar/gui/ShareNoteDialog.js:97:42
    at Generator.next (<anonymous>)
    at fulfilled (/Applications/Joplin.app/Contents/Resources/app.asar/gui/ShareNoteDialog.js:5:58)"
2021-04-27 18:52:27: "Could not set setting on the keychain. Will be saved to database instead: sync.5.password:", "Error: Password is required.
Error: Password is required.
    at checkRequired (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/keytar/lib/keytar.js:5:11)
    at Object.setPassword (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/keytar/lib/keytar.js:20:5)
    at KeychainServiceDriver.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/keychain/KeychainServiceDriver.node.js:19:43)
    at Generator.next (<anonymous>)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/keychain/KeychainServiceDriver.node.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/keychain/KeychainServiceDriver.node.js:4:12)
    at KeychainServiceDriver.setPassword (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/keychain/KeychainServiceDriver.node.js:16:16)
    at KeychainService.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/keychain/KeychainService.js:45:32)
    at Generator.next (<anonymous>)"
2021-04-27 18:52:30: "ShareNoteDialog: Cannot share note:", "Error: Unsupported WebDAV URL format: 
Error: Unsupported WebDAV URL format: 
    at Function.baseUrlFromNextcloudWebDavUrl (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/JoplinServerApi.js:60:19)
    at Object.baseUrl (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/SyncTargetNextcloud.js:59:35)
    at JoplinServerApi.baseUrl (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/JoplinServerApi.js:53:43)
    at JoplinServerApi.syncTargetId (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/JoplinServerApi.js:66:82)
    at /Applications/Joplin.app/Contents/Resources/app.asar/gui/ShareNoteDialog.js:97:42
    at Generator.next (<anonymous>)
    at fulfilled (/Applications/Joplin.app/Contents/Resources/app.asar/gui/ShareNoteDialog.js:5:58)"
2021-04-27 18:52:40: App: "Profile directory: /Users/chris/.config/joplin-desktop"
2021-04-27 18:52:40: "Database was open successfully"
2021-04-27 18:52:40: "Checking for database schema update..."
2021-04-27 18:52:40: "Current database version", "{"version":34,"table_fields_version":34}"
2021-04-27 18:52:40: "Upgrading database from version 34"
2021-04-27 18:52:40: "New version: 34. Previously recorded version: 34"
2021-04-27 18:52:40: "KeychainService: checking if keychain supported"
2021-04-27 18:52:40: "KeychainService: check was already done - skipping. Supported:", "1"
2021-04-27 18:52:40: App: "Client ID: REDACTED"
```

**Comment by Someguy123** [comment]
I installed the 1.8.2 Mac desktop application, and it now seems to actually integrate with Joplin Server, BUT, it still throws an error. Just a different one saying that the file doesn't exist.

<img width="571" alt="image" src="https://user-images.githubusercontent.com/1267260/116294734-38806580-a790-11eb-8c1c-0357e13599ca.png">
