### ISSUE TITLE
installation problem with npm

### ISSUE THREAD

**Issue by muralikodali** [laurent22/joplin#49]
**Ubunutu mate 16.04 - terminal based installation**

**terminal output is as follows**:

/home/murali/.nvm/versions/node/v4.7.0/lib/node_modules/joplin/main.js:7
const { app } = require('./app.js');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3

**Comment by laurent22** [comment]
Please see here: https://github.com/laurent22/joplin/issues/17
