### ISSUE TITLE
win10 client can't complete the synchronization

### ISSUE THREAD

**Issue by haitaogithub** [laurent22/joplin#491]
### Operating system

- [X] Windows
- macOS
- Linux
- Android
- iOS

### Application

- [X] Desktop
- Mobile
- Terminal

One of my win10 desktop joplin can't finish the synchronization(another win10 instance can and ios also work well), it's stuck at the middle of the progress.
BTW I used webdav at the server side.
Please check the log bellow, only 19 of the 26 are fetched.
```
2018-05-05 14:34:33: "Starting scheduled sync"
2018-05-05 14:35:00: "ResourceService::indexNoteResources: Start"
2018-05-05 14:35:00: "ResourceService::indexNoteResources: Completed"
2018-05-05 14:35:00: "ResourceService::deleteOrphanResources:", "[]"
2018-05-05 14:37:55: "Error: getaddrinfo ENOTFOUND 192.168.1.1:88 192.168.1.1:88:88
Code: ENOTFOUND
Error: getaddrinfo ENOTFOUND 192.168.1.1:88 192.168.1.1:88:88
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)"
2018-05-05 14:37:55: "Operations completed: "
2018-05-05 14:37:55: "fetchingTotal: 26"
2018-05-05 14:37:55: "fetchingProcessed: 19"
2018-05-05 14:37:55: "createLocal: 1"
2018-05-05 14:37:55: "Total folders: 3"
2018-05-05 14:37:55: "Total notes: 3"
2018-05-05 14:37:55: "Total resources: 0"
2018-05-05 14:42:55: "Running background sync on timer..."
2018-05-05 14:42:55: "Scheduling sync operation..."
2018-05-05 14:42:55: "Preparing scheduled sync"
2018-05-05 14:42:55: "Starting scheduled sync"
```

**Comment by laurent22** [comment]
Hmm yes that's strange, it seems something is adding the port number twice. As far as I know the app aren't working properly with non-standard ports and that could be the reason.

**Comment by bufferovercat** [comment]
Same problem here. Win10 client only fetchs 51 of 250 notes, using nextcloud:

2018-05-19 22:42:57: "Error: getaddrinfo ENOTFOUND 192.168.20.20:9993 192.168.20.20:9993:9993

Linux and android clients work fine.
