### ISSUE TITLE
Joplin server: corrupt user?

### ISSUE THREAD

**Issue by Derkades** [laurent22/joplin#4986]
## Environment

Joplin server version: 1.7.2
Platform: official docker image

## Steps to reproduce

I'm not sure what I did to cause it. In the last couple days I did add a new (third) user. I also temporarily updated to 2.0.1, but as soon as I realized it was not backwards compatible with older clients I restored a database backup and reverted back to `:latest`.

Logging in using the admin user works, but the using the second non-admin user:
![image](https://user-images.githubusercontent.com/15892014/118615187-c6b0a000-b7c0-11eb-8ea0-8d608198c63d.png)

When logged in as the `admin@localhost` user, the second user is listed in the 'Users' table but clicking Edit produces this error
![image](https://user-images.githubusercontent.com/15892014/118615366-f3fd4e00-b7c0-11eb-8f25-6be9d3ae9c94.png)

log
```
2021-05-18 08:07:18: [error] App: TypeError: Cannot read property 'id' of undefined
    at /home/joplin/packages/server/src/routes/index/users.ts:63:47
    at Generator.next (<anonymous>)
    at fulfilled (/home/joplin/packages/server/dist/routes/index/users.js:5:58)
```

Note syncing fails with a similar error:
```
2021-05-18 08:09:01: [error] App: TypeError: Cannot read property 'id' of undefined
    at /home/joplin/packages/server/src/routes/api/files.ts:48:56
    at Generator.next (<anonymous>)
    at /home/joplin/packages/server/dist/routes/api/files.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/joplin/packages/server/dist/routes/api/files.js:4:12)
    at /home/joplin/packages/server/src/routes/api/files.ts:47:78
    at /home/joplin/packages/server/src/middleware/routeHandler.ts:19:27
    at Generator.next (<anonymous>)
    at /home/joplin/packages/server/dist/middleware/routeHandler.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/joplin/packages/server/dist/middleware/routeHandler.js:4:12)
    at default_1 (/home/joplin/packages/server/dist/middleware/routeHandler.js:18:12)
    at dispatch (/home/joplin/packages/server/node_modules/koa-compose/index.js:42:32)
    at /home/joplin/packages/server/src/middleware/notificationHandler.ts:75:33
    at Generator.next (<anonymous>)
    at /home/joplin/packages/server/dist/middleware/notificationHandler.js:8:71
```

**Comment by Derkades** [comment]
probably pebkac when restoring the database
