### ISSUE TITLE
Exit status 137 and container crash during long running sync

### ISSUE THREAD

**Issue by jeffabailey** [laurent22/joplin#4992]
## Environment

Joplin version: v2.0.1
Platform:  Synology with the stock Postgresql server version, (PostgreSQL) 9.3.25
OS specifics: 

cat /etc/VERSION
majorversion="6"
minorversion="2"
major="6"
minor="2"
micro="4"
productversion="6.2.4"
buildphase="GM"
buildnumber="25556"
smallfixnumber="0"
nano="0"
base="25556"
builddate="2021/03/04"
buildtime="19:44:30"

## Steps to reproduce

1. Run a sync with a few thousand notes?

## Describe what you expected to happen

The container to stay up and continue serving requests.

## Logfile

[2021-05-19T22_18_34_423Z-debug.log](https://github.com/laurent22/joplin/files/6511918/2021-05-19T22_18_34_423Z-debug.log)

Errors before the log file was dropped.

```
2021-05-19 22:04:53: App: GET /api/items/root:/.resource/f4d0b8da923749fda78668c7718c8113:/content 
2021-05-19 22:04:53: App: GET /api/items/root:/f4d0b8da923749fda78668c7718c8113.md:/content 
2021-05-19 22:04:54: App: GET /api/items/root:/.resource/57d5787b7cd448b39ef34e3c72dd5640:/content KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? at Client_PG.acquireConnection (/home/joplin/packages/server/node_modules/knex/lib/client.js:295:26) at runNextTicks (internal/process/task_queues.js:62:5) at listOnTimeout (internal/timers.js:523:9) at processTimers (internal/timers.js:497:7) 

KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? at Client_PG.acquireConnection (/home/joplin/packages/server/node_modules/knex/lib/client.js:295:26) at runNextTicks (internal/process/task_queues.js:62:5) at listOnTimeout (internal/timers.js:523:9) at processTimers (internal/timers.js:497:7) 

KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? at Client_PG.acquireConnection (/home/joplin/packages/server/node_modules/knex/lib/client.js:295:26) at runNextTicks (internal/process/task_queues.js:62:5) at processTimers (internal/timers.js:494:9) KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? at Client_PG.acquireConnection (/home/joplin/packages/server/node_modules/knex/lib/client.js:295:26) at runNextTicks (internal/process/task_queues.js:62:5) at listOnTimeout (internal/timers.js:523:9) at processTimers (internal/timers.js:497:7) 

KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? at Client_PG.acquireConnection (/home/joplin/packages/server/node_modules/knex/lib/client.js:295:26) at runNextTicks (internal/process/task_queues.js:62:5) at listOnTimeout (internal/timers.js:523:9) at processTimers (internal/timers.js:497:7) KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? at Client_PG.acquireConnection (/home/joplin/packages/server/node_modules/knex/lib/client.js:295:26)
```

**Comment by jeffabailey** [comment]
I don't see any other errors except the KnexTimeoutError within the first several lines.

Here's the whole log. Synology dumps the log as HTML, so I converted it to text to shrink the log file. It has some ugly formatting it threw in as a bonus.

[container-log.txt](https://github.com/laurent22/joplin/files/6516178/container-log.txt)

If anything jumps out let me know if you want me to dig for more info.

**Comment by jeffabailey** [comment]
One other note, it is reproducible right now. I've been restarting the container to sync with one of my local stores that used to be on OneDrive, and it keeps crashing.

**Comment by jeffabailey** [comment]
It appears that everything finally finished syncing.

I set the container to auto-restart if it crashes, so I have a workaround.

Let me know if you want me to do some debugging. I wouldn't mind helping out if you can give me a few pointers. I can likely reproduce the problem by creating a new database and start the sync again.
