### ISSUE TITLE
Image is invalid or does not exist  - when pasting image from clipboard 

### ISSUE THREAD

**Issue by GeneralGG** [laurent22/joplin#5021]
## Description

Joplin cannot paste images from clipboard under an arch linux distro

## Environment

Joplin version: 1.8.5 installed with yay (same issue with version 1.7.x)
Platform: Arch Linux, just updated as of today
OS specifics: KDE desktop

## Steps to reproduce

1. Take a screenshot (fe with spectacle tool), copy this to clipboard
2. CTRL+V into any joplin note
3. Error message popups up "Image is invalid or does not exist: /path/to/image/name.png

## Describe what you expected to happen
I'd expect the clipboard is pasted into my joplin note.

## Logfile
2021-05-28 11:47:40: "Attaching /home/damien/.config/joplin-desktop/tmp/7f7ec93b472fbe0d7e6d698bc1a3a08e.png"
2021-05-28 11:47:40: "Error: Image is invalid or does not exist: /home/damien/.config/joplin-desktop/tmp/7f7ec93b472fbe0d7e6d698bc1a3a08e.png
Error: Image is invalid or does not exist: /home/damien/.config/joplin-desktop/tmp/7f7ec93b472fbe0d7e6d698bc1a3a08e.png
    at handleResizeImage_ (/usr/share/joplin-desktop/resources/app.asar/node_modules/@joplin/lib/shim-init-node.js:140:31)
    at Object.shim.createResourceFromPath (/usr/share/joplin-desktop/resources/app.asar/node_modules/@joplin/lib/shim-init-node.js:242:21)
    at async Object.shim.attachFileToNoteBody (/usr/share/joplin-desktop/resources/app.asar/node_modules/@joplin/lib/shim-init-node.js:275:15)"

A this point, the image is created into the ./tmp directory, but its size is 0.

## Notes
1. I have copy/pasted the ~/.config/joplin-desktop whole folder to a new pc. Joplin version on the source computer was the same
2. I made sure the users connected has all the rights to joplin-desktop folder recursively
3. No other issue detected than the inability to paste 
4. KDE under Wayland (but it's also under wayland on the other PC and works great)

**Comment by GeneralGG** [comment]
Digged a bit more this issue
- No issue under X11, the issue is coming from Wayland (coming with latest KDE implementation).
