### ISSUE TITLE
Fatal error: Error:SQLITE_CORRUPT

### ISSUE THREAD

**Issue by byronkg** [laurent22/joplin#5040]
Fatal error: 

Error: SQLITE_CORRUPT: database disk image is malformed: SELECT count(*) at total FROM notes WHERE is_conflict = 1

Error:  Error: SQLITE_CORRUPT: database disk image is malformed: SELECT count(*) at total FROM notes WHERE is_conflict = 1
  at DatabaseDriverNode.sqliteErrorToJsError(/tmp/.mount_Jopline23xkbb/-resources/app.asar/node_modules/@jopline/lib/database-driver-node.js:21:18) at JoplinDatabase.sqliteErrorToJsError(/tmp/.mount_Jopline23xkbb/-resources/app.asar/node_modules/@jopline/lib/database.js:34:30) at JoplinDatabase.sqliteErrorToJsError(/tmp/.mount_Jopline23xkbb/-resources/app.asar/node_modules/@jopline/lib/database.js:124:36) at Generator.throw(<anonymous>) at rejected(/tmp/.mount_Jopline23xkbb/-resources/app.asar/node_modules/@jopline/lib/database.js:6:65)

## Environment

Joplin version: 1.85
Platform: Linux
OS specifics: Kali 2021

## Steps to reproduce

1. Run Joplin app on kali
2. Application Error 

## Describe what you expected to happen

Weird that Joplin database suddenly corrupt? Notebook was open and running for 2 days then crashed. When reopened error comes up.

**Comment by byronkg** [comment]
Fixed:  Open sqlite database with a sqlite database browser. Change is_conflict values from 1 to 0. Reload Joplin Application.

**Comment by byronkg** [comment]
Haven't seen this issue with versions 2.x.x
