### ISSUE TITLE
"Invalid Property Format" due to truncated md file in sync target

### ISSUE THREAD

**Issue by notAunty** [laurent22/joplin#5056]
## Environment

Joplin version: 1.8.5 AppImage
Platform: Linux
OS specifics: Ubuntu 20.04

## Steps to reproduce

1. Use Joplin as normal
2. Sync shows last error with long details.
3. Get into the logs.txt and get the logs

## Describe what you expected to happen
Sync to be successful, but it failed with notes not syncing to and from the client with error.

## Logfile

Notes: `ct` field have been replaced with `xxx` as I'm not too sure how sensitive is it.
***
```
2021-06-06 23:49:12: "Error: On file d1ef23f75be431019e7f44db4d1421ff.md: Invalid property format: encr: id: d1ef23f75be431019e7f44db4d1421ff
parent_id: a9a7972cdb8f4854842cdf74e172fb51
created_time: 
updated_time: 2021-05-10T01:37:33.925Z
is_conflict: 
latitude: 
longitude: 
altitude: 
author: 
source_url: 
is_todo: 
todo_due: 
todo_completed: 
source: 
source_application: 
application_data: 
order: 
user_created_time: 
user_updated_time: 
encryption_cipher_text: JED01000022058bf691435aae4ef28ef330f46de1696c0005ec{"iv":"bwVFy7nqQaeO9yElMLTFmw==","v":1,"iter":101,"ks":128,"ts":64,"mode":"ccm","adata":"","cipher":"aes","salt":"onPxGP+o0bM=","ct":"xxx"}
encr
Error: On file d1ef23f75be431019e7f44db4d1421ff.md: Invalid property format: encr: id: d1ef23f75be431019e7f44db4d1421ff
parent_id: a9a7972cdb8f4854842cdf74e172fb51
created_time: 
updated_time: 2021-05-10T01:37:33.925Z
is_conflict: 
latitude: 
longitude: 
altitude: 
author: 
source_url: 
is_todo: 
todo_due: 
todo_completed: 
source: 
source_application: 
application_data: 
order: 
user_created_time: 
user_updated_time: 
encryption_cipher_text: JED01000022058bf691435aae4ef28ef330f46de1696c0005ec{"iv":"bwVFy7nqQaeO9yElMLTFmw==","v":1,"iter":101,"ks":128,"ts":64,"mode":"ccm","adata":"","cipher":"aes","salt":"onPxGP+o0bM=","ct":"xxx"}
encr
    at Function.<anonymous> (/tmp/.mount_JoplinysJsy0/resources/app.asar/node_modules/@joplin/lib/models/BaseItem.js:443:31)
    at Generator.next (<anonymous>)
    at /tmp/.mount_JoplinysJsy0/resources/app.asar/node_modules/@joplin/lib/models/BaseItem.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/tmp/.mount_JoplinysJsy0/resources/app.asar/node_modules/@joplin/lib/models/BaseItem.js:4:12)
    at Function.unserialize (/tmp/.mount_JoplinysJsy0/resources/app.asar/node_modules/@joplin/lib/models/BaseItem.js:428:16)
    at Synchronizer.<anonymous> (/tmp/.mount_JoplinysJsy0/resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:678:65)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_JoplinysJsy0/resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5:58)"
```

**Comment by notAunty** [comment]
I have fixed it by deleting the corrupted md file from my cloud storage and the error went away. Not too sure what was the root cause, but I wish that deleting the md file doesnt remove any of my notes.

**Comment by notAunty** [comment]
I have manage to recover the notes content from jex file that I have backed-up. Deleting the md file from sync target straight away removes the note entry.
