### ISSUE TITLE
v2.0.10 - Fatal error:  Unknown key: sync.9.directory

### ISSUE THREAD

**Issue by brown131** [laurent22/joplin#5086]
I just upgraded  to the Joplin 2.0.10 on MacOS v11.4 and when I try to start the application I get the error below. I tried rolling back but it gave me an "Unknown profile version" error, so now I'm stuck and I can't run Joplin anymore.

````
Fatal error:

Unknown key: sync.9.directory

Error: Unknown key: sync.9.directory
at Function.settingMetadata (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/models/Setting.js:1065:19)
at Function.formatValue (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/models/Setting.js:1312:25)
at Function.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/models/Setting.js:1173:57)
at Generator.next (<anonymous>)
at fulfilled (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/models/Setting.js:5:58)
````

**Comment by laurent22** [comment]
The latest release should fix this: https://github.com/laurent22/joplin/releases/tag/v2.0.11

**Comment by brown131** [comment]
It does. Thanks for the quick turnaround!
