### ISSUE TITLE
Web clipper stucked at "Permission needed... Starting" 

### ISSUE THREAD

**Issue by qmeeus** [laurent22/joplin#5127]
Hi,

I just installed the web clipper on Linux but I cannot make it work. I have authorized the web clipper service in the app and checked that the firewall does not block local traffic to/from this port. A token is generated by the app but I don't know whether I should input it somewhere in a config file or something. The web clipper gets stuck on any URL with message "Permission needed... Starting". It seems that the token is not properly passed to the api.

## Environment

Joplin version: 2.0.11
Platform: Linux 5.10.42
OS specifics: Manjaro 

## Steps to reproduce

1. Go to any webpage
2. Click on the extension

Inspect popup gives the following error:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
main.chunk.js:1 Uncaught (in promise) Error: {"error":"Not Found: \n\nError: Not Found\n    at Api.<anonymous> (/tmp/.mount_JoplinAEEFgk/resources/app.asar/node_modules/@joplin/lib/services/rest/Api.js:71:23)\n    at Generator.next (<anonymous>)\n    at /tmp/.mount_JoplinAEEFgk/resources/app.asar/node_modules/@joplin/lib/services/rest/Api.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/tmp/.mount_JoplinAEEFgk/resources/app.asar/node_modules/@joplin/lib/services/rest/Api.js:4:12)\n    at Api.route (/tmp/.mount_JoplinAEEFgk/resources/app.asar/node_modules/@joplin/lib/services/rest/Api.js:64:16)\n    at execRequest (/tmp/.mount_JoplinAEEFgk/resources/app.asar/node_modules/@joplin/lib/ClipperServer.js:161:39)\n    at Server.<anonymous> (/tmp/.mount_JoplinAEEFgk/resources/app.asar/node_modules/@joplin/lib/ClipperServer.js:204:7)\n    at Server.emit (events.js:310:20)\n    at Server.EventEmitter.emit (domain.js:482:12)"}
    at e.<anonymous> (main.chunk.js:1)
    at u (2.chunk.js:2)
    at Generator._invoke (2.chunk.js:2)
    at Generator.forEach.e.<computed> [as next] (2.chunk.js:2)
    at r (2.chunk.js:2)
    at a (2.chunk.js:2)
```

**Comment by laurent22** [comment]
See pinned issue https://github.com/laurent22/joplin/issues/5125
