### ISSUE TITLE
CLI can't sync notebooks created in GUI

### ISSUE THREAD

**Issue by giannivh** [laurent22/joplin#514]
### Operating system

- macOS (version 10.13.4)

### Application

- Desktop (version 1.0.91)
- Terminal (version 1.0.106)

### Bug description

I've imported my Evernote notes/TODOs into Joplin using the Mac app (GUI). I've reordered some stuff and then tried to switch over to the CLI app. After calling the `:sync` command, it crashes with the following error:
```
Created remote items: 12. Fetched items: 1/138. Completed: 11/05/2018 14:30 Last error: Error: Unknown field: parent_id
```

Enabled debug mode, this was written in the log:
```
2018-05-11 14:30:12: "Sync: fetchingProcessed: Processing fetched item"
2018-05-11 14:30:12: "Reducer action", "SYNC_REPORT_UPDATE"
2018-05-11 14:30:12: "get 3ed839c454884850a3855e9780b7e847.md"
2018-05-11 14:30:12: "Error: Unknown field: parent_id
Error: Unknown field: parent_id
    at Function.fieldType (/usr/local/Cellar/joplin/1.0.106_1/libexec/lib/node_modules/joplin/lib/BaseModel.js:79:9)
    at Function.unserialize_format (/usr/local/Cellar/joplin/1.0.106_1/libexec/lib/node_modules/joplin/lib/models/BaseItem.js:219:47)
    at Function.unserialize (/usr/local/Cellar/joplin/1.0.106_1/libexec/lib/node_modules/joplin/lib/models/BaseItem.js:353:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)"
2018-05-11 14:30:12: "Sync: finished: Synchronisation finished [1526041808231]"
```

The item is a Joplin notebook, created in the GUI, which the CLI can't decipher. 

The notebook metadata is:
```
NotebookNameHere

id: 3ed839c454884850a3855e9780b7e847
created_time: 2018-05-11T11:57:18.786Z
updated_time: 2018-05-11T11:57:18.786Z
user_created_time: 2018-05-11T11:57:18.786Z
user_updated_time: 2018-05-11T11:57:18.786Z
encryption_cipher_text: 
encryption_applied: 0
parent_id: 
type_: 2
```

It syncs fine on the mobile app though.

I only want to use the cli, but I'm currently blocked.

**Comment by laurent22** [comment]
This is due to an incomparability between the CLI app and the desktop one (which is more recent). For now, please update the CLI app to v1.0.107+ and it should work.

**Comment by giannivh** [comment]
I installed through brew, and .106 is the latest version:
`Warning: joplin 1.0.106_1 is already installed and up-to-date`

Maybe publish a new version?

**Comment by laurent22** [comment]
107 is already published but maybe not available yet. Try in a few minutes and see if you get that version.

**Comment by giannivh** [comment]
Alright, I'll wait it out! Thanks for the fast reply :)

**Comment by giannivh** [comment]
Confirmed working with 1.0.107.
