### ISSUE TITLE
Server migration issues from 2.01 to 2.1.6

### ISSUE THREAD

**Issue by jt196** [laurent22/joplin#5152]
```
,
> @joplin/server@2.1.6 start /home/joplin/packages/server,
> node dist/app.js,
,
2021-07-02 14:18:14: App: Starting server v2.1.6 (prod) on port 22300 and PID 26...,
2021-07-02 14:18:14: App: Running in Docker: true,
2021-07-02 14:18:14: App: Public base URL: http://[joplin-URL]:22300,
2021-07-02 14:18:14: App: API base URL: http://[joplin-URL]:22300,
2021-07-02 14:18:14: App: User content base URL: http://[joplin-URL]:22300,
2021-07-02 14:18:14: App: Log dir: /home/joplin/packages/server/logs,
2021-07-02 14:18:14: App: DB Config: {,
  client: 'pg',,
  name: 'joplin',,
  user: 'joplin',,
  password: '********',,
  port: 5432,,
  host: 'db',
},
2021-07-02 14:18:14: App: Trying to connect to database...,
2021-07-02 14:18:14: App: Connection check: {,
  latestMigration: { name: '20190913171451_create.js' },,
  isCreated: true,,
  error: null,
},
2021-07-02 14:18:37: App: Migrating database...,
Can't take lock to run migrations: Migration table is already locked,
If you are sure migrations are not running you can release the lock manually by running 'knex migrate:unlock',
[MigrationLocked: Migration table is already locked],
npm ERR! code ELIFECYCLE,
npm ERR! errno 1,
npm ERR! @joplin/server@2.1.6 start: `node dist/app.js`,
npm ERR! Exit status 1,,
 ,
npm ERR! Failed at the @joplin/server@2.1.6 start script.,
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.,
,
npm ERR! A complete log of this run can be found in:,
npm ERR!     /home/joplin/.npm/_logs/2021-07-02T14_18_37_774Z-debug.log
```

## Environment

Joplin version: Server 2.01 upgrade to 2.1.6 via Docker
Platform: Docker

Getting some weird messages - looks like DB migration issues between 2.01 to 2.1.6 in the Docker set up. Logs above. Downgrading it back to 2.0.1 causes further errors to pop up.

**Comment by jt196** [comment]
Managed to login to the container and unlock the database, getting some more errors now: 

```
2021-07-02 14:42:06: App: Migrating database...,
migration file "20210618192423_jop_updated_time.js" failed,
migration failed with error: alter table "items" add column "jop_updated_time" bigint not null default '0' - column "jop_updated_time" of relation "items" already exists,
error: alter table "items" add column "jop_updated_time" bigint not null default '0' - column "jop_updated_time" of relation "items" already exists,
    at Parser.parseErrorMessage (/home/joplin/packages/server/node_modules/pg-protocol/src/parser.ts:357:11),
    at Parser.handlePacket (/home/joplin/packages/server/node_modules/pg-protocol/src/parser.ts:186:21),
    at Parser.parse (/home/joplin/packages/server/node_modules/pg-protocol/src/parser.ts:101:30),
    at Socket.<anonymous> (/home/joplin/packages/server/node_modules/pg-protocol/src/index.ts:7:48),
    at Socket.emit (events.js:314:20),
    at addChunk (_stream_readable.js:297:12),
    at readableAddChunk (_stream_readable.js:272:9),
    at Socket.Readable.push (_stream_readable.js:213:10),
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {,
  length: 140,,
  severity: 'ERROR',,
  code: '42701',,
  detail: undefined,,
  hint: undefined,,
  position: undefined,,
  internalPosition: undefined,,
  internalQuery: undefined,,
  where: undefined,,
  schema: undefined,,
  table: undefined,,
  column: undefined,,
  dataType: undefined,,
  constraint: undefined,,
  file: 'tablecmds.c',,
  line: '6486',,
  routine: 'check_for_column_name_collision',
},
npm ERR! code ELIFECYCLE,
npm ERR! errno 1,
npm ERR! @joplin/server@2.1.6 start: `node dist/app.js`,
npm ERR! Exit status 1,,
 ,
npm ERR! Failed at the @joplin/server@2.1.6 start script.,
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.,
,
npm ERR! A complete log of this run can be found in:,
npm ERR!     /home/joplin/.npm/_logs/2021-07-02T14_42_06_728Z-debug.log,
,
> @joplin/server@2.1.6 start /home/joplin/packages/server,
> node dist/app.js,
,
2021-07-02 14:42:15: App: Starting server v2.1.6 (prod) on port 22300 and PID 18...,
2021-07-02 14:42:15: App: Running in Docker: true,
2021-07-02 14:42:15: App: Public base URL: http://[joplin_URL]:22300,
2021-07-02 14:42:15: App: API base URL: http://[joplin_URL]:22300,
2021-07-02 14:42:15: App: User content base URL: http://[joplin_URL]:22300,
2021-07-02 14:42:15: App: Log dir: /home/joplin/packages/server/logs,
2021-07-02 14:42:15: App: DB Config: {,
  client: 'pg',,
  name: '[name]',,
  user: '[user]',,
  password: '********',,
  port: 5432,,
  host: 'db',
},
2021-07-02 14:42:15: App: Trying to connect to database...,
2021-07-02 14:42:15: App: Connection check: {,
  latestMigration: { name: '20190913171451_create.js' },,
  isCreated: true,,
  error: null,
}
```

**Comment by laurent22** [comment]
you need to delete items.jop_updated_time, then restart the server

**Comment by jt196** [comment]
That seems to have done it. Annoyingly, I created a new container and initiated a force re-up. Going back to the original container seems to not break that. Is there a way to turn off the force re-up @laurent22? Like changing the sync target for example or resetting the preferences?

**Comment by jt196** [comment]
If anybody has this problem and needs to run through the steps, this should do the job: 

- Log into Docker image: `sudo docker exec -it [your_image_name] /bin/bash`
- Open DB inside the image: `psql -d [your_joplin_database_name] -U [your_joplin_db_user] -W`
- enter your Joplin db password.
- Remove column: `alter table public.items drop column jop_updated_time;`
- Quit out `/q`, exit container and restart the app container.
