### ISSUE TITLE
KaTeX macros are not being recognised

### ISSUE THREAD

**Issue by VBtheFirbolg** [laurent22/joplin#5187]
## Environment

Joplin version: 2.1.8
Platform: Linux
OS specifics: Ubuntu 20.04.2 LTS

I just upgraded the app from version 1.7.13 (I am not sure about the 13, my apologies) to 2.1.8, and the KaTeX macros that I had defined at the beginning of each document are returning some errors (they worked fine in 1.7.13). 

## Steps to reproduce

1. Open the app and enter some macro, say `\gdef{\L}{\mathcal{L}}` within math-mode.
2. I am getting the error `KaTeX parse error: Expected a control sequence at position 6: \gdef{̲\L}{\mathcal{L}...`

## Describe what you expected to happen

I expected it to work as it did in 1.7.13, where this error was not being encountered.

## Logfile

I might have not done what was needed here, so I will be happy to furnish additional details if anyone walks me through what to do. The following was a highlighted error message in the console.

```
Katex error for: \gdef{\L}{\mathcal{L}}
 ParseError: KaTeX parse error: Expected a control sequence at position 6: \gdef{̲\L}{\mathcal{L}…
    at new ParseError (/tmp/.mount_JoplinY7C4m7/resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/renderer/node_modules/katex/dist/katex.js:99:14)
    at Object.handler (/tmp/.mount_JoplinY7C4m7/resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/renderer/node_modules/katex/dist/katex.js:8415:13)
    at Parser.callFunction (/tmp/.mount_JoplinY7C4m7/resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/renderer/node_modules/katex/dist/katex.js:17224:19)
    at Parser.parseFunction (/tmp/.mount_JoplinY7C4m7/resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/renderer/node_modules/katex/dist/katex.js:17207:17)
    at Parser.parseGroup (/tmp/.mount_JoplinY7C4m7/resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/renderer/node_modules/katex/dist/katex.js:17598:21)
    at Parser.parseAtom (/tmp/.mount_JoplinY7C4m7/resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/renderer/node_modules/katex/dist/katex.js:17079:21)
    at Parser.parseExpression (/tmp/.mount_JoplinY7C4m7/resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/renderer/node_modules/katex/dist/katex.js:16942:23)
    at Parser.parse (/tmp/.mount_JoplinY7C4m7/resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/renderer/node_modules/katex/dist/katex.js:16896:22)
    at parseTree (/tmp/.mount_JoplinY7C4m7/resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/renderer/node_modules/katex/dist/katex.js:17838:21)
    at renderToDomTree (/tmp/.mount_JoplinY7C4m7/resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/renderer/node_modules/katex/dist/katex.js:17948:16)
```

**Comment by VBtheFirbolg** [comment]
My apologies again, turns out it was a syntax error in KaTeX. Gosh, this is embarrassing.
