### ISSUE TITLE
macos desktop sync fails - dropbox "socket hang up"

### ISSUE THREAD

**Issue by jessbk** [laurent22/joplin#5217]
I have one Mac that fails to sync, whether I add new content to it, or new content to the "remote" from another Joplin instance(on another system). There are no errors on the UI, but the logs show...

```
"FetchError: request to https://content.dropboxapi.com/2/files/upload failed, reason: socket hang up
Code: ECONNRESET
```

I have uninstalled, cleared '.config/joplin-desktop', and re-auth'ed with dropbox multiple times. I have manage a couple of times to get a successful sync, but it is few and far between. Another macos (11.4, arm) syncs successfully every time on the same wifi.

Stand-alone Dropbox app sync works on this host without issue.

## Environment

Joplin version: Joplin 2.1.9 (prod, darwin)
Platform: macos
OS specifics: macos 11.4 (intel)

## Steps to reproduce

1. Push synchronize button
2. (or) wait for scheduled sync
3. 

## Logfile

```
2021-07-20 13:57:24: "Running background sync on timer..."
2021-07-20 13:57:24: "Preparing scheduled sync"
2021-07-20 13:57:24: "Starting scheduled sync"
2021-07-20 13:57:24: "Sync: starting: Starting synchronisation to target 7... supportsAccurateTimestamp = false; supportsMultiPut = false [1626803844260]"
2021-07-20 13:57:24: "Indexing resources..."
2021-07-20 13:57:24: "ResourceService::indexNoteResources: Start"
2021-07-20 13:57:24: "ResourceService::indexNoteResources: Completed"
2021-07-20 13:57:24: "Sync target info:", "{"version":2}"
2021-07-20 13:57:29: "Sync: updateRemote: local has changes: Note: (Local 7230fde37fff4a36b12f5312549c430d): (Remote 7230fde37fff4a36b12f5312549c430d.md)"
2021-07-20 13:57:51: "FetchError: request to https://content.dropboxapi.com/2/files/upload failed, reason: socket hang up
Code: ECONNRESET
FetchError: request to https://content.dropboxapi.com/2/files/upload failed, reason: socket hang up
    at ClientRequest.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:310:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.socketOnEnd (_http_client.js:453:9)
    at TLSSocket.emit (events.js:322:22)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)"
2021-07-20 13:57:51: "Sync: finished: Synchronisation finished [1626803844260]"
2021-07-20 13:57:51: "Operations completed: "
2021-07-20 13:57:51: "updateRemote: 1"
2021-07-20 13:57:51: "Total folders: 5"
2021-07-20 13:57:51: "Total notes: 375"
2021-07-20 13:57:51: "Total resources: 129"
2021-07-20 13:57:53: "DecryptionWorker: starting decryption..."
2021-07-20 13:57:53: "DecryptionWorker: completed decryption."
```

**Comment by jessbk** [comment]
update: i tried onedrive as an alternative to dropbox and am getting the same behavior....

```2021-07-21 16:38:51: "Saving updated OneDrive auth."
2021-07-21 16:39:34: "Saving updated OneDrive auth."
2021-07-21 16:39:35: "Saving updated OneDrive auth."
2021-07-21 16:39:35: "Preparing scheduled sync"
2021-07-21 16:39:37: "Starting scheduled sync"
2021-07-21 16:39:37: "Sync: starting: Starting synchronisation to target 3... supportsAccurateTimestamp = false; supportsMultiPut = false [1626899977426]"
2021-07-21 16:39:37: "Indexing resources..."
2021-07-21 16:39:37: "ResourceService::indexNoteResources: Start"
2021-07-21 16:39:37: "ResourceService::indexNoteResources: Completed"
2021-07-21 16:39:38: "Sync target info:", "{"version":0}"
2021-07-21 16:39:38: "Sync target is new - setting it up..."
2021-07-21 16:39:38: "MigrationHandler: Sync target version is 0 or 1 - creating "locks" and "temp" directory:", "{"version":0}"
2021-07-21 16:39:40: "MigrationHandler: Acquiring exclusive lock"
2021-07-21 16:39:42: "MigrationHandler: Acquired exclusive lock:", "{"type":"exclusive","clientType":"desktop","clientId":"22fa5ee3224c44879ed323c54134fa09","updatedTime":1626899981990}"
2021-07-21 16:39:42: "MigrationHandler: Migrating from version 0 to version 1"
2021-07-21 16:39:45: "MigrationHandler: Done migrating from version 0 to version 1"
2021-07-21 16:39:45: "MigrationHandler: Migrating from version 1 to version 2"
2021-07-21 16:39:46: "MigrationHandler: Done migrating from version 1 to version 2"
2021-07-21 16:39:46: "MigrationHandler: Releasing exclusive lock"
2021-07-21 16:39:47: "Sync: createRemote: remote does not exist, and local is new and has never been synced: Note: (Local 7230fde37fff4a36b12f5312549c430d)"
2021-07-21 16:39:47: OneDriveApi: "Got error below - retrying (0)..."
2021-07-21 16:39:47: OneDriveApi: "FetchError: request to https://graph.microsoft.com/v1.0/drive/root:/Apps/Joplin/7230fde37fff4a36b12f5312549c430d.md:/content failed, reason: socket hang up
Code: ECONNRESET
FetchError: request to https://graph.microsoft.com/v1.0/drive/root:/Apps/Joplin/7230fde37fff4a36b12f5312549c430d.md:/content failed, reason: socket hang up
    at ClientRequest.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:310:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.socketOnEnd (_http_client.js:453:9)
    at TLSSocket.emit (events.js:322:22)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)"
2021-07-21 16:39:53: OneDriveApi: "Got error below - retrying (1)..."
2021-07-21 16:39:53: OneDriveApi: "FetchError: request to https://graph.microsoft.com/v1.0/drive/root:/Apps/Joplin/7230fde37fff4a36b12f5312549c430d.md:/content failed, reason: read ECONNRESET
Code: ECONNRESET
FetchError: request to https://graph.microsoft.com/v1.0/drive/root:/Apps/Joplin/7230fde37fff4a36b12f5312549c430d.md:/content failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:310:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)"
2021-07-21 16:39:59: "Running background sync on timer..."
2021-07-21 16:39:59: "Preparing scheduled sync"
2021-07-21 16:39:59: "Starting scheduled sync"
2021-07-21 16:39:59: "Synchronisation is already in progress. State: in_progress"
2021-07-21 16:40:03: OneDriveApi: "Got error below - retrying (2)..."
2021-07-21 16:40:03: OneDriveApi: "FetchError: request to https://graph.microsoft.com/v1.0/drive/root:/Apps/Joplin/7230fde37fff4a36b12f5312549c430d.md:/content failed, reason: socket hang up
Code: ECONNRESET
FetchError: request to https://graph.microsoft.com/v1.0/drive/root:/Apps/Joplin/7230fde37fff4a36b12f5312549c430d.md:/content failed, reason: socket hang up
    at ClientRequest.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:310:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.socketOnEnd (_http_client.js:453:9)
    at TLSSocket.emit (events.js:322:22)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)"
2021-07-21 16:40:18: OneDriveApi: "Got error below - retrying (3)..."
2021-07-21 16:40:18: OneDriveApi: "FetchError: request to https://graph.microsoft.com/v1.0/drive/root:/Apps/Joplin/7230fde37fff4a36b12f5312549c430d.md:/content failed, reason: read ECONNRESET
Code: ECONNRESET
FetchError: request to https://graph.microsoft.com/v1.0/drive/root:/Apps/Joplin/7230fde37fff4a36b12f5312549c430d.md:/content failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:310:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)"
2021-07-21 16:40:38: OneDriveApi: "Got error below - retrying (4)..."
2021-07-21 16:40:38: OneDriveApi: "FetchError: request to https://graph.microsoft.com/v1.0/drive/root:/Apps/Joplin/7230fde37fff4a36b12f5312549c430d.md:/content failed, reason: read ECONNRESET
Code: ECONNRESET
FetchError: request to https://graph.microsoft.com/v1.0/drive/root:/Apps/Joplin/7230fde37fff4a36b12f5312549c430d.md:/content failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:310:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)"```

**Comment by JackGruber** [comment]
The error message says that no connection can be established to the servers.
Is a proxy / firewall being used?

**Comment by jessbk** [comment]
There is a corporate proxy "pac" file, but I have tried disabling it and also adding the dropbox api hostname to the exclude list. 

Sync did work initially, maybe a couple of times.

I can see traffic moving both ways to/from content.dropboxapi.com with ngrep. 

I can curl "https://content.dropboxapi.com/2/files/upload" directly and get the expected auth error. 1password syncs correctly, and I have no other Dropbox (or OneDrive) issues. It does seem like a networking issue on my side, though it is only noticeably affecting Joplin. 

Is there a way to increase the timeout for these calls? Any other suggestions for debugging?

**Comment by jessbk** [comment]
I think I found the culprit, Cisco AMP for Endpoints Service, which is required for our corporate Anyconnect VPN. Disabling the AMP network extension allowed a successful sync. Note that this was without being connected to the VPN.
