### ISSUE TITLE
Unknown field: parent_id

### ISSUE THREAD

**Issue by crequill** [laurent22/joplin#530]
### Operating system

- Linux

### Application

- Desktop

On Arch Linux, I try to synchronize with a directory synced with a nextcloud server. A previous synchronization was done between my iphone and nextcloud server. On Arch Linux, I get an error:

2018-05-17 18:26:13: "There was some errors:"
2018-05-17 18:26:13: "Error: Unknown field: parent_id
Error: Unknown field: parent_id
    at Function.fieldType (/usr/share/joplin/resources/app/lib/BaseModel.js:79:9)
    at Function.unserialize_format (/usr/share/joplin/resources/app/lib/models/BaseItem.js:219:47)
    at Function.unserialize (/usr/share/joplin/resources/app/lib/models/BaseItem.js:353:27)
    at <anonymous>"
2018-05-17 18:26:13: "Reducer action", "SYNC_COMPLETED"
2018-05-17 18:26:13: "Setting up recurrent sync with interval 300"

I put a breakpoint in BaseItem.js, the problem is with note 461ec8f77b18488da78aeb7711ca3451:

> Mes notes
>
> id: 461ec8f77b18488da78aeb7711ca3451
> created_time: 2018-04-11T19:09:39.666Z
> updated_time: 2018-04-11T19:09:39.666Z
> user_created_time: 2018-04-11T19:09:39.666Z
> user_updated_time: 2018-04-11T19:09:39.666Z
> encryption_cipher_text: 
> encryption_applied: 0
> parent_id: 
> type_: 2

**Comment by laurent22** [comment]
Hi, you need the latest version of the desktop app.
