### ISSUE TITLE
Sync stopped working with OneDrive in 2.2.7

### ISSUE THREAD

**Issue by nikkehtine** [laurent22/joplin#5307]
I've been using Joplin with OneDrive for syncing my notes, with encryption turned on. After the 2.2.7 update I was prompted to log in to OneDrive again, and after doing so, I started getting an error that says `The provided drive id appears to be malformed, or does not represent a valid drive`

## Environment

Joplin version: `Joplin 2.2.7 (prod, win32)` `Sync Version: 2` `Profile Version: 39` `Keychain Supported: Yes` `Revision: 6d1a2e2`
Platform: Windows 10
OS specifics: x64 21H1

## Steps to reproduce

1. Log in to OneDrive with the new login screen
2. Synchronize

## Describe what you expected to happen

The program should sync notes with OneDrive like it did before

## Logfile

```
2021-08-14 14:16:53: "CommandService::execute:", "synchronize", "[false]"
2021-08-14 14:16:53: "Could not acquire synchroniser:"
2021-08-14 14:16:53: "Error: The provided drive id appears to be malformed, or does not represent a valid drive.
Code: invalidRequest
Header: {"_headers":{"connection":["close"],"date":["Sat, 14 Aug 2021 12:16:53 GMT"],"content-type":["application/json"],"cache-control":["no-cache"],"transfer-encoding":["chunked"],"content-encoding":["gzip"],"vary":["Accept-Encoding"],"strict-transport-security":["max-age=31536000"],"request-id":["b3344ec7-4749-4b31-8a76-085906cdff81"],"client-request-id":["b3344ec7-4749-4b31-8a76-085906cdff81"],"x-ms-ags-diagnostic":["{\"ServerInfo\":{\"DataCenter\":\"West Europe\",\"Slice\":\"E\",\"Ring\":\"5\",\"ScaleUnit\":\"001\",\"RoleInstance\":\"AM4PEPF0000DE33\"}}"]}}
Request: GET https://graph.microsoft.com/v1.0/me/drives/9e356c93e63d07d6/special/approot null null {"headers":{"Authorization":"bearer eyJ0eXAiOiJKV1QiLCJub25jZSI6Ik0zODkzd082bnZGNW1xRG9kcm5Gc3pVbjlzVWRGQldrTjh0TDJORG9YV3MiLCJhbGciOiJSUzI1NiIsIng1dCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyIsImtpZCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9kOTk1ZmFhNy04YzllLTQ3NDUtOTk0YS01MDZlMjJhZjkzNTMvIiwiaWF0IjoxNjI4OTQyNTA5LCJuYmYiOjE2Mjg5NDI1MDksImV4cCI6MTYyODk0NjQwOSwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkUyWmdZTkI4S1J4cDFtN2RHYWNXWThsNUpXQnVTMkRZbXRVTExQajE2MXczeGJPRm53Y0EiLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6IkpvcGxpbiIsImFwcGlkIjoiZTA5ZmMwZGUtYzk1OC00MjRmLTgzYTItZTU2YTcyMWQzMzFiIiwiYXBwaWRhY3IiOiIxIiwiZmFtaWx5X25hbWUiOiJXYXJ1bmVrIiwiZ2l2ZW5fbmFtZSI6Ik5vcmJlcnQiLCJpZHR5cCI6InVzZXIiLCJpcGFkZHIiOiIxOTIuMTA5Ljg0LjE0NSIsIm5hbWUiOiJXYXJ1bmVrIE5vcmJlcnQiLCJvaWQiOiJhZjI5ZjFjMC1lZDI4LTRhMzUtYTgzZC05NTM0MDIwYTIwZjEiLCJwbGF0ZiI6IjMiL
Error: The provided drive id appears to be malformed, or does not represent a valid drive.
    at OneDriveApi.oneDriveErrorResponseToError (C:\Users\apollo\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:124:28)
    at OneDriveApi.<anonymous> (C:\Users\apollo\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:306:40)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\apollo\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:5:58)"
```

**Comment by nikkehtine** [comment]
Unlinking Joplin from Microsoft account settings, deleting the Joplin profile folder, and then completely uninstalling the app and installing the 2.3.3 update fixed it for me. I don't know if I should close the issue.
