### ISSUE TITLE
POSTGRES_HOST issues with localhost and 127.0.0.1

### ISSUE THREAD

**Issue by Expro** [laurent22/joplin#5386]
When setting POSTGRES_HOST to "localhost" or "127.0.0.1", Joplin incorrectly resolves that to "host.docker.internal" and fails to connect to dabatase.
Please note that providing name of container with Postgres on Kubernetes is not valid solution.

## Environment

Joplin version: :latest tag on hub.docker.com
Platform: Linux
OS specifics: Centos 8.x + Kubernetes

## Steps to reproduce

1. Launch container with POSTGRES_HOST variable set to either "hostname" or "127.0.0.1".

## Describe what you expected to happen
Joplin correctly resolves "localhost" to 127.0.0.1 or accepts "127.0.0.1" as IP and does not try to do some weird DNS resolve back and forth.

## Logfile

> @joplin/server@2.2.10 start /home/joplin/packages/server
> node dist/app.js

2021-08-25 18:13:54: App: Starting server v2.2.10 (prod) on port 22300 and PID 26...
2021-08-25 18:13:54: App: Running in Docker: true
2021-08-25 18:13:54: App: Log dir: /home/joplin/packages/server/logs
2021-08-25 18:13:54: App: DB Config: {
  client: 'pg',
  name: 'joplin',
  user: 'joplin',
  password: '********',
  port: 5432,
  host: 'host.docker.internal'
}
2021-08-25 18:13:54: App: Trying to connect to database...
2021-08-25 18:13:54: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-08-25 18:13:55: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-08-25 18:13:56: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-08-25 18:13:57: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-08-25 18:13:58: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-08-25 18:13:59: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-08-25 18:14:03: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-08-25 18:14:04: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-08-25 18:14:05: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-08-25 18:14:06: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-08-25 18:14:07: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-08-25 18:14:08: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-08-25 18:14:09: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-08-25 18:14:10: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-08-25 18:14:11: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-08-25 18:14:12: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-08-25 18:14:13: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-08-25 18:14:14: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-08-25 18:14:15: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-08-25 18:14:16: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-08-25 18:14:17: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-08-25 18:14:18: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-08-25 18:14:19: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-08-25 18:14:20: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-08-25 18:14:21: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-08-25 18:14:22: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-08-25 18:14:23: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-08-25 18:14:24: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-08-25 18:14:25: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-08-25 18:14:25: [error] db: Timeout trying to connect to database: Error: getaddrinfo ENOTFOUND host.docker.internal
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'host.docker.internal'
}
Error: Timeout trying to connect to database. Last error was: getaddrinfo ENOTFOUND host.docker.internal
    at Object.<anonymous> (/home/joplin/packages/server/src/db.ts:89:10)
    at Generator.next (<anonymous>)
    at fulfilled (/home/joplin/packages/server/dist/db.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @joplin/server@2.2.10 start: `node dist/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @joplin/server@2.2.10 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/joplin/.npm/_logs/2021-08-25T18_14_25_213Z-debug.log

**Comment by daniellandau** [comment]
Without fixing the code, one can work around it by adding `--net=host --add-host=host.docker.internal:127.0.0.1` to the docker run command line.
