### ISSUE TITLE
Fatal error: Cannot use 'in' operator to search for 'enabled' in undefined

### ISSUE THREAD

**Issue by dbogdanov** [laurent22/joplin#5391]
Opening the application leads to an immediate error:

```
Cannot use 'in' operator to search for 'enabled' in undefined
```

```
Stack trace
TypeError: Cannot use 'in' operator to search for 'enabled' in undefined
    at Object.masterKeyEnabled (/tmp/.mount_Joplin6Jut2X/resources/app.asar/node_modules/@joplin/lib/services/synchronizer/syncInfoUtils.js:229:19)
    at Object.showMissingMasterKeyMessage (/tmp/.mount_Joplin6Jut2X/resources/app.asar/node_modules/@joplin/lib/services/e2ee/utils.js:112:30)
    at Function.mapStateToProps [as mapToProps] (/tmp/.mount_Joplin6Jut2X/resources/app.asar/gui/MainScreen/MainScreen.js:642:46)
    at mapToPropsProxy (/tmp/.mount_Joplin6Jut2X/resources/app.asar/node_modules/react-redux/lib/connect/wrapMapToProps.js:54:92)
    at handleNewState (/tmp/.mount_Joplin6Jut2X/resources/app.asar/node_modules/react-redux/lib/connect/selectorFactory.js:63:26)
    at handleSubsequentCalls (/tmp/.mount_Joplin6Jut2X/resources/app.asar/node_modules/react-redux/lib/connect/selectorFactory.js:80:30)
    at pureFinalPropsSelector (/tmp/.mount_Joplin6Jut2X/resources/app.asar/node_modules/react-redux/lib/connect/selectorFactory.js:85:32)
    at Object.runComponentSelector (/tmp/.mount_Joplin6Jut2X/resources/app.asar/node_modules/react-redux/lib/components/connectAdvanced.js:43:25)
    at Connect.onStateChange (/tmp/.mount_Joplin6Jut2X/resources/app.asar/node_modules/react-redux/lib/components/connectAdvanced.js:216:23)
    at Object.notify (/tmp/.mount_Joplin6Jut2X/resources/app.asar/node_modules/react-redux/lib/utils/Subscription.js:30:21)
Component stack

    in Connect(MainScreenComponent) (created by NavigatorComponent)
    in div (created by NavigatorComponent)
    in NavigatorComponent (created by Connect(NavigatorComponent))
    in Connect(NavigatorComponent) (created by RootComponent)
    in ThemeProvider (created by RootComponent)
    in StyleSheetManager (created by RootComponent)
    in RootComponent (created by Connect(RootComponent))
    in Connect(RootComponent)
    in ErrorBoundary
    in Provider

```

## Environment
Joplin version: Joplin 2.4.2 
Platform:  Linux
OS specifics: Ubuntu 21.04

## Debug log
Joplin 2.4.2 (prod, linux)
Sync Version: 3
Profile Version: 39
Keychain Supported: No
Revision: 75d118b

Plugins:
```
[
    {
        "id": "joplin.plugin.note.tabs",
        "name": "Note Tabs",
        "enabled": false,
        "version": "1.4.0"
    },
    {
        "id": "com.whatever.quick-links",
        "name": "Quick Links",
        "enabled": true,
        "version": "1.2.2"
    },
    {
        "id": "joplin.plugin.ambrt.backlinksToNote",
        "name": "Automatic Backlinks to note",
        "enabled": true,
        "version": "2.0.11"
    },
    {
        "id": "io.treymo.LinkGraph",
        "name": "Link Graph UI",
        "enabled": false,
        "version": "1.0.1"
    },
    {
        "id": "joplin-plugin-file-encryption",
        "name": "File encryption",
        "enabled": true,
        "version": "1.0.0"
    },
    {
        "id": "joplin.plugin.benji.favorites",
        "name": "Favorites",
        "enabled": true,
        "version": "1.3.0"
    },
    {
        "id": "plugin.calebjohn.rich-markdown",
        "name": "Rich Markdown",
        "enabled": false,
        "version": "0.7.1"
    },
    {
        "id": "joplin.plugin.ambrt.embedSearch",
        "name": "Embed Search",
        "enabled": true,
        "version": "1.0.11"
    }
]
```

**Comment by laurent22** [comment]
I'll try to fix this as soon as possible. It keeps doing it even after you close the app and restarts?
