### ISSUE TITLE
synchronization error FetchError: On file download failed, reason: connect EHOSTUNREACH

### ISSUE THREAD

**Issue by banan314** [laurent22/joplin#5415]
I encrypted my notes and synchronized them.

During upload to Dropbox there was a synchronization error:
```
Items that cannot be synchronized
These items will remain on the device but will not be uploaded to the sync target. In order to find these items, either search for the title or the ID (which is displayed in brackets above).
- bbbbbbbbbbbbbbbbbbbbb.png (ccccccccccccccccc) could not be uploaded: `File not found:Error: Error: ENOENT: no such file or directory, open '/home/kamil/.config/joplin-desktop/resources/ccccccccccccccccc.png'. Path: /home/kamil/.config/joplin-desktop/resources/ccccccccccccccccccccccccccc.png` Retry
- eeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.png (ddddddddddddddddddddddddddddd) could not be uploaded: `File not found:Error: Error: ENOENT: no such file or directory, open '/home/kamil/.config/joplin-desktop/resources/ddddddddddddddddddddddddddd.png'. Path: /home/kamil/.config/joplin-desktop/resources/ddddddddddddddddddddddddddddd.png` Retry
```

 Notes are uploaded to Dropbox server. Then Joplin desktop wants to fetch them again and there is an error.

I get the following error all the time I want to synchronize.

```
Fetched items: 835/1000.
Completed: 03.09.2021 17:05 (138s)
Last error: FetchError: On file aaaaaaaaaaaaaaaaaaa.md: request to https://content.dropboxapi.com/2/files/download failed, reason: connect EHOSTUNREACH 162.125.66.14:443
```

## Environment

Joplin version: 2.4.1 
Platform: Linux
OS specifics: Linux Mint
Profile: 39
Sync Version: 3
Keychain Supported: No

## Steps to reproduce

I guess encrypt notes and try to synchronize them.

## Describe what you expected to happen

No synchronization errors.

What to do now? Delete local version? Delete remote version?

## Logfile

```
Synchronizer: There was some errors:
log @ /tmp/.mount_joplinLgTOOX/resources/app.asar/node_modules/@joplin/lib/Logger.js:188

7:05:35: Synchronizer: FetchErrorcode: "EHOSTUNREACH"errno: "EHOSTUNREACH"message: "On file aaaaaaaaaaaaaaaaaaaaa.md: request to https://content.dropboxapi.com/2/files/download failed, reason: connect EHOSTUNREACH 162.125.66.14:443"name: "FetchError"type: "system"stack: "FetchError: On file aaaaaaaaaaaaaaaaaaaaaaaaaaaaa.md: request to https://content.dropboxapi.com/2/files/download failed, reason: connect EHOSTUNREACH 162.125.66.14:443
    at ClientRequest.<anonymous> (/tmp/.mount_joplinLgTOOX/resources/app.asar/node_modules/@joplin/lib/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:310:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)"__proto__: Errorconstructor: ƒ FetchError(message, type, systemError)arguments: nullcaller: nulllength: 3name: "FetchError"prototype: Error {constructor: ƒ}super_: ƒ Error()__proto__: ƒ ()[[FunctionLocation]]: /tmp/.mount_joplinLgTOOX/resources/app.asar/node_modules/@joplin/lib/node_modules/node-fetch/lib/fetch-error.js:18[[Scopes]]: Scopes[2]__proto__: Object
log @ /tmp/.mount_joplinLgTOOX/resources/app.asar/node_modules/@joplin/lib/Logger.js:188
```
Warning :warning: 
```
/tmp/.mount_joplinLgTOOX/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11494 Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Connect(Dialog), Connect(HelpButtonComponent)
```

**Comment by banan314** [comment]
perhaps unchecking fail-safe helps?

**Comment by laurent22** [comment]
looks like a Dropbox issue, it should probably work if you try again later

**Comment by banan314** [comment]
> looks like a Dropbox issue, it should probably work if you try again later

I've been fetching resources on the phone (clean install) for over 2 hours without any issue so far.

**Comment by banan314** [comment]
The sync on the phone finished, but I still had the same error on my desktop. I decided to delete my local version and re-download it from Dropbox. Looking good so far.

**Comment by laurent22** [comment]
Also check your firewall

**Comment by banan314** [comment]
@laurent22 My firewall is disabled. 

I tried to disable Dropbox sync as well. I changed the number of concurrent connections to 13. I reuploaded the notes to the target. 

I get the same error upon fetching about 865 items: `EHOSTUNREACH`. Always a different markdown file though.

What should I do?

**Comment by banan314** [comment]
I've paused syncing in Dropbox client and set the number of max concurrent connections to 1. It's fetched over 1000 items and is going on, fingers crossed.

**Comment by tessus** [comment]
Apparently Dropbox is rate-limiting too many concurrent connections. The default of 5 should work though. I don't think you have to set it to 1.

**Comment by banan314** [comment]
@tessus I had changed it to 6 some time ago, it probably caused the issue as you say.
