### ISSUE TITLE
windows+linux sync stuck,jolin2.4.7

### ISSUE THREAD

**Issue by ilaer** [laurent22/joplin#5489]
## Environment

Joplin version: 2.4.7
Platform: windows11,deepin linux
OS specifics: 

## Steps to reproduce

1. 
2. 
3. 

## Logfile

2021-09-21 20:39:47: App: "Profile directory: C:/Users/ila/.config/joplin-desktop"
2021-09-21 20:39:47: "Database was open successfully"
2021-09-21 20:39:47: "Checking for database schema update..."
2021-09-21 20:39:47: "Current database version", "{"version":39,"table_fields_version":39}"
2021-09-21 20:39:47: "Upgrading database from version 39"
2021-09-21 20:39:47: "New version: 39. Previously recorded version: 39"
2021-09-21 20:39:47: "KeychainService: checking if keychain supported"
2021-09-21 20:39:47: "KeychainService: check was already done - skipping. Supported:", "1"
2021-09-21 20:39:47: e2ee/utils: "Master password is not set - trying to get it from the active master key..."
2021-09-21 20:39:47: handleSyncStartupOperation: "Processing operation:", "0"
2021-09-21 20:39:47: App: "Client ID: 25a66838d06c4ec69925eb7837962d0d"
2021-09-21 20:39:47: e2ee/utils: "Trying to load 0 master keys..."
2021-09-21 20:39:47: e2ee/utils: "Loaded master keys: 0"
2021-09-21 20:39:47: "ResourceFetcher: Auto-add resources: Mode: always"
2021-09-21 20:39:47: "ResourceFetcher: Auto-added resources: 0"
2021-09-21 20:39:47: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-09-21 20:39:47: e2ee/utils: "Trying to load 0 master keys..."
2021-09-21 20:39:47: e2ee/utils: "Loaded master keys: 0"
2021-09-21 20:39:47: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-09-21 20:39:47: e2ee/utils: "Trying to load 0 master keys..."
2021-09-21 20:39:47: e2ee/utils: "Loaded master keys: 0"
2021-09-21 20:39:47: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-09-21 20:39:47: e2ee/utils: "Trying to load 0 master keys..."
2021-09-21 20:39:47: e2ee/utils: "Loaded master keys: 0"
2021-09-21 20:39:47: "app.start: doing regular boot"
2021-09-21 20:39:47: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-09-21 20:39:47: e2ee/utils: "Trying to load 0 master keys..."
2021-09-21 20:39:47: e2ee/utils: "Loaded master keys: 0"
2021-09-21 20:39:47: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-09-21 20:39:47: e2ee/utils: "Trying to load 0 master keys..."
2021-09-21 20:39:47: e2ee/utils: "Loaded master keys: 0"
2021-09-21 20:39:47: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-09-21 20:39:47: e2ee/utils: "Trying to load 0 master keys..."
2021-09-21 20:39:47: e2ee/utils: "Loaded master keys: 0"
2021-09-21 20:39:47: RevisionService: "RevisionService::runInBackground: Starting background service with revision collection interval 600000"
2021-09-21 20:39:47: SpellCheckerServiceDriverNative: "Set effective language from "en-US" to "en-US""
2021-09-21 20:39:48: "DecryptionWorker: cannot start because no master key is currently loaded."
2021-09-21 20:39:48: "Preparing scheduled sync"
2021-09-21 20:39:48: "Starting scheduled sync"
2021-09-21 20:39:48: Synchronizer: "Sync: starting: Starting synchronisation to target 6... supportsAccurateTimestamp = false; supportsMultiPut = false [1632227988727]"
2021-09-21 20:39:48: Synchronizer: "Indexing resources..."
2021-09-21 20:39:48: "ResourceService::indexNoteResources: Start"
2021-09-21 20:39:48: "ResourceService::indexNoteResources: Completed"
2021-09-21 20:39:49: Synchronizer: "Sync target remote info:", "{"version_":3,"masterKeys_":[],"e2ee_":{"value":false,"updatedTime":0},"activeMasterKeyId_":{"value":"","updatedTime":0}}"
2021-09-21 20:39:49: Synchronizer: "Sync target is already setup - checking it..."
2021-09-21 20:39:49: Synchronizer: "Sync target local info:", "{"version_":3,"masterKeys_":[],"e2ee_":{"value":false,"updatedTime":0},"activeMasterKeyId_":{"value":"","updatedTime":0}}"
2021-09-21 20:39:51: RevisionService: "RevisionService::maintenance: Starting..."
2021-09-21 20:39:51: RevisionService: "RevisionService::maintenance: Service is enabled"
2021-09-21 20:39:51: RevisionService: "RevisionService::collectRevisions: Created revisions for 0 notes"
2021-09-21 20:39:51: RevisionService: "RevisionService::maintenance: Done in 136ms"
2021-09-21 20:39:57: "SearchEngine: Updating FTS table..."
2021-09-21 20:39:57: "SearchEngine: Updated FTS table in 4ms. Inserted: 0. Deleted: 0"
2021-09-21 20:40:17: "ResourceService::indexNoteResources: Start"
2021-09-21 20:40:17: "ResourceService::indexNoteResources: Completed"
2021-09-21 20:40:17: "ResourceService::deleteOrphanResources:", "[]"
2021-09-21 20:41:39: App: "Profile directory: C:/Users/ila/.config/joplin-desktop"
2021-09-21 20:41:39: "Database was open successfully"
2021-09-21 20:41:39: "Checking for database schema update..."
2021-09-21 20:41:39: "Current database version", "{"version":39,"table_fields_version":39}"
2021-09-21 20:41:39: "Upgrading database from version 39"
2021-09-21 20:41:39: "New version: 39. Previously recorded version: 39"
2021-09-21 20:41:39: "KeychainService: checking if keychain supported"
2021-09-21 20:41:39: "KeychainService: check was already done - skipping. Supported:", "1"
2021-09-21 20:41:39: e2ee/utils: "Master password is not set - trying to get it from the active master key..."
2021-09-21 20:41:39: handleSyncStartupOperation: "Processing operation:", "0"
2021-09-21 20:41:39: App: "Client ID: 25a66838d06c4ec69925eb7837962d0d"
2021-09-21 20:41:39: e2ee/utils: "Trying to load 0 master keys..."
2021-09-21 20:41:39: e2ee/utils: "Loaded master keys: 0"
2021-09-21 20:41:39: "ResourceFetcher: Auto-add resources: Mode: always"
2021-09-21 20:41:39: "ResourceFetcher: Auto-added resources: 0"
2021-09-21 20:41:39: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-09-21 20:41:39: e2ee/utils: "Trying to load 0 master keys..."
2021-09-21 20:41:39: e2ee/utils: "Loaded master keys: 0"
2021-09-21 20:41:39: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-09-21 20:41:39: e2ee/utils: "Trying to load 0 master keys..."
2021-09-21 20:41:39: e2ee/utils: "Loaded master keys: 0"
2021-09-21 20:41:39: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-09-21 20:41:39: e2ee/utils: "Trying to load 0 master keys..."
2021-09-21 20:41:39: e2ee/utils: "Loaded master keys: 0"
2021-09-21 20:41:39: "app.start: doing regular boot"
2021-09-21 20:41:39: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-09-21 20:41:39: e2ee/utils: "Trying to load 0 master keys..."
2021-09-21 20:41:39: e2ee/utils: "Loaded master keys: 0"
2021-09-21 20:41:39: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-09-21 20:41:39: e2ee/utils: "Trying to load 0 master keys..."
2021-09-21 20:41:39: e2ee/utils: "Loaded master keys: 0"
2021-09-21 20:41:39: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-09-21 20:41:39: e2ee/utils: "Trying to load 0 master keys..."
2021-09-21 20:41:39: e2ee/utils: "Loaded master keys: 0"
2021-09-21 20:41:40: RevisionService: "RevisionService::runInBackground: Starting background service with revision collection interval 600000"
2021-09-21 20:41:40: SpellCheckerServiceDriverNative: "Set effective language from "en-US" to "en-US""
2021-09-21 20:41:40: "DecryptionWorker: cannot start because no master key is currently loaded."
2021-09-21 20:41:41: "Preparing scheduled sync"
2021-09-21 20:41:41: "Starting scheduled sync"
2021-09-21 20:41:41: Synchronizer: "Sync: starting: Starting synchronisation to target 6... supportsAccurateTimestamp = false; supportsMultiPut = false [1632228101008]"
2021-09-21 20:41:41: Synchronizer: "Indexing resources..."
2021-09-21 20:41:41: "ResourceService::indexNoteResources: Start"
2021-09-21 20:41:41: "ResourceService::indexNoteResources: Completed"
2021-09-21 20:41:41: Synchronizer: "Sync target remote info:", "{"version_":3,"masterKeys_":[],"e2ee_":{"value":false,"updatedTime":0},"activeMasterKeyId_":{"value":"","updatedTime":0}}"
2021-09-21 20:41:41: Synchronizer: "Sync target is already setup - checking it..."
2021-09-21 20:41:41: Synchronizer: "Sync target local info:", "{"version_":3,"masterKeys_":[],"e2ee_":{"value":false,"updatedTime":0},"activeMasterKeyId_":{"value":"","updatedTime":0}}"
2021-09-21 20:41:50: App: "Profile directory: C:/Users/ila/.config/joplin-desktop"
2021-09-21 20:41:50: "Database was open successfully"
2021-09-21 20:41:50: "Checking for database schema update..."
2021-09-21 20:41:50: "Current database version", "{"version":39,"table_fields_version":39}"
2021-09-21 20:41:50: "Upgrading database from version 39"
2021-09-21 20:41:50: "New version: 39. Previously recorded version: 39"
2021-09-21 20:41:50: "KeychainService: checking if keychain supported"
2021-09-21 20:41:50: "KeychainService: check was already done - skipping. Supported:", "1"
2021-09-21 20:41:50: e2ee/utils: "Master password is not set - trying to get it from the active master key..."
2021-09-21 20:41:50: handleSyncStartupOperation: "Processing operation:", "0"
2021-09-21 20:41:50: App: "Client ID: 25a66838d06c4ec69925eb7837962d0d"
2021-09-21 20:41:50: e2ee/utils: "Trying to load 0 master keys..."
2021-09-21 20:41:50: e2ee/utils: "Loaded master keys: 0"
2021-09-21 20:41:50: "ResourceFetcher: Auto-add resources: Mode: always"
2021-09-21 20:41:50: "ResourceFetcher: Auto-added resources: 0"
2021-09-21 20:41:50: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-09-21 20:41:50: e2ee/utils: "Trying to load 0 master keys..."
2021-09-21 20:41:50: e2ee/utils: "Loaded master keys: 0"
2021-09-21 20:41:50: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-09-21 20:41:50: e2ee/utils: "Trying to load 0 master keys..."
2021-09-21 20:41:50: e2ee/utils: "Loaded master keys: 0"
2021-09-21 20:41:50: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-09-21 20:41:50: e2ee/utils: "Trying to load 0 master keys..."
2021-09-21 20:41:50: e2ee/utils: "Loaded master keys: 0"
2021-09-21 20:41:50: "app.start: doing regular boot"
2021-09-21 20:41:50: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-09-21 20:41:50: e2ee/utils: "Trying to load 0 master keys..."
2021-09-21 20:41:50: e2ee/utils: "Loaded master keys: 0"
2021-09-21 20:41:50: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-09-21 20:41:50: e2ee/utils: "Trying to load 0 master keys..."
2021-09-21 20:41:50: e2ee/utils: "Loaded master keys: 0"
2021-09-21 20:41:50: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-09-21 20:41:50: e2ee/utils: "Trying to load 0 master keys..."
2021-09-21 20:41:50: e2ee/utils: "Loaded master keys: 0"
2021-09-21 20:41:50: RevisionService: "RevisionService::runInBackground: Starting background service with revision collection interval 600000"
2021-09-21 20:41:50: SpellCheckerServiceDriverNative: "Set effective language from "en-US" to "en-US""
2021-09-21 20:41:51: "DecryptionWorker: cannot start because no master key is currently loaded."
2021-09-21 20:41:51: "Preparing scheduled sync"
2021-09-21 20:41:51: "Starting scheduled sync"
2021-09-21 20:41:51: Synchronizer: "Sync: starting: Starting synchronisation to target 6... supportsAccurateTimestamp = false; supportsMultiPut = false [1632228111847]"
2021-09-21 20:41:51: Synchronizer: "Indexing resources..."
2021-09-21 20:41:51: "ResourceService::indexNoteResources: Start"
2021-09-21 20:41:52: "ResourceService::indexNoteResources: Completed"
2021-09-21 20:41:52: Synchronizer: "Sync target remote info:", "{"version_":3,"masterKeys_":[],"e2ee_":{"value":false,"updatedTime":0},"activeMasterKeyId_":{"value":"","updatedTime":0}}"
2021-09-21 20:41:52: Synchronizer: "Sync target is already setup - checking it..."
2021-09-21 20:41:52: Synchronizer: "Sync target local info:", "{"version_":3,"masterKeys_":[],"e2ee_":{"value":false,"updatedTime":0},"activeMasterKeyId_":{"value":"","updatedTime":0}}"
2021-09-21 20:41:54: RevisionService: "RevisionService::maintenance: Starting..."
2021-09-21 20:41:54: RevisionService: "RevisionService::maintenance: Service is enabled"
2021-09-21 20:41:54: RevisionService: "RevisionService::collectRevisions: Created revisions for 0 notes"
2021-09-21 20:41:54: RevisionService: "RevisionService::maintenance: Done in 121ms"
2021-09-21 20:42:00: "SearchEngine: Updating FTS table..."
2021-09-21 20:42:00: "SearchEngine: Updated FTS table in 3ms. Inserted: 0. Deleted: 0"
2021-09-21 20:42:20: "ResourceService::indexNoteResources: Start"
2021-09-21 20:42:20: "ResourceService::indexNoteResources: Completed"
2021-09-21 20:42:20: "ResourceService::deleteOrphanResources:", "[]"
2021-09-21 20:42:24: Synchronizer: "TaskQueue.stop: syncDownload: waiting for tasks to complete: 0"
2021-09-21 20:42:24: Synchronizer: "TaskQueue.stop: syncDownload: Done, waited for 0"
2021-09-21 20:42:24: Synchronizer: "Sync: cancelling"
2021-09-21 20:42:33: "SearchEngine: Updating FTS table..."
2021-09-21 20:42:33: "SearchEngine: Updated FTS table in 47ms. Inserted: 1. Deleted: 0"
2021-09-21 20:42:36: PluginState: "FetchError: request to https://raw.githubusercontent.com/joplin/plugins/master/manifests.json failed, reason: getaddrinfo ENOENT raw.githubusercontent.com
Code: ENOENT
FetchError: request to https://raw.githubusercontent.com/joplin/plugins/master/manifests.json failed, reason: getaddrinfo ENOENT raw.githubusercontent.com
    at ClientRequest.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\node_modules\node-fetch\index.js:133:11)
    at ClientRequest.emit (events.js:310:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)"
2021-09-21 20:46:50: "Running background sync on timer..."
2021-09-21 20:46:50: "Preparing scheduled sync"
2021-09-21 20:46:50: "Starting scheduled sync"
2021-09-21 20:46:50: "Synchronisation is already in progress. State: in_progress"
2021-09-21 20:51:50: "Running background sync on timer..."
2021-09-21 20:51:50: "Preparing scheduled sync"
2021-09-21 20:51:50: RevisionService: "RevisionService::maintenance: Starting..."
2021-09-21 20:51:50: RevisionService: "RevisionService::maintenance: Service is enabled"
2021-09-21 20:51:50: "Starting scheduled sync"
2021-09-21 20:51:50: "Synchronisation is already in progress. State: in_progress"
2021-09-21 20:51:50: RevisionService: "RevisionService::collectRevisions: Created revisions for 1 notes"
2021-09-21 20:51:50: RevisionService: "RevisionService::maintenance: Done in 161ms"

**Comment by ilaer** [comment]
已新建远程项目: 1。
已完成: 2021-09-21 22:04（12s）
最后错误: Error: Error: Error: EISDIR: illegal operation on a directory, readlink 'Z:\.resource\5f585cf61683499d890c4e24f1f42a21'. Path: D:/softs/joplin/JoplinProfile/resources/5f585cf61683499d890c4e24f1f42a21.png. Path: Z:/.resource/5f585cf61683499d890c4e24f1f42a21

**Comment by laurent22** [comment]
> Error: Error: Error

Well at least we know it's an error.

From the look of it you need to check your path, make sure it's correct and files are accessible on it.

**Comment by ilaer** [comment]
> > Error: Error: Error
> 
> Well at least we know it's an error.
> 
> From the look of it you need to check your path, make sure it's correct and files are accessible on it.

i try "file system" and "webdav",always sync stuck,or error like it.
