### ISSUE TITLE
Desktop client stopped syncing to a server with a Let’s Encrypt’s certificate

### ISSUE THREAD

**Issue by devosb** [laurent22/joplin#5514]
## Environment

Joplin version: 2.3.5 and 2.4.9
Platform: Linux
OS specifics:  Ubuntu 18.04 and 20.04

## Steps to reproduce

1. Try to sync to server (either periodically or manually requested)
2. Joplin says (the hostname has been changed in the output and logs below)
```
Last error: FetchError: request to https://example.com/nextcloud/remote.php/webdav/joplin/info.json failed, reason: certificate has expired
```

## Describe what you expected to happen

A sync would happen.

And a sync does happen, on Apple iPadOS and iOS 14.8 with the latest Joplin app from the App Store. While Joplin (on Ubuntu) does say that the certificate has expired, I don't see any certificate warning on the Apple devices when using Joplin, nor does Firefox nor Chrome on Ubuntu 20.04 when logging into the Nextcloud server. Using either desktop web browser to inspect the certificate shows that the validity (between early Sep and early Dec of 2021) is okay.

The server is getting an certificate from Let's Encrypt. I wonder if Joplin has it's own list of certificate authorities, and if that needs to be updated with the very recent expiry of the original IdentTrust DST Root CA X3 cert that Let's Encrypt was using. [An article](https://techcrunch.com/2021/09/21/lets-encrypt-root-expiry/)  say that root certificate is expiring today, and applications and some OS need to switch to using the ISRG Root X1 certificate.

The timing seems too close to be a coincidence. Joplin 2.3.5 worked on Ubuntu yesterday (29 Sep 2021) in the early afternoon (UTC-6). This morning around 10 am (UTC-6 which is 14:00 UTC) the sync did not work. And [another article](https://scotthelme.co.uk/lets-encrypt-old-root-expiration/) says that the original root certificate expired at 14:01 UTC.

## Logfile

```
/tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/Logger.js:188 10:28:03: Synchronizer: There was some errors:
log @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/Logger.js:188
warn @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/Logger.js:63
(anonymous) @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:232
fulfilled @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
Promise.then (async)
step @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
fulfilled @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
Promise.then (async)
step @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
fulfilled @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
Promise.then (async)
step @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
(anonymous) @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:8
__awaiter @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:4
logSyncSummary @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:206
(anonymous) @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:1019
fulfilled @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
Promise.then (async)
step @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
rejected @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:6
Promise.then (async)
step @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
fulfilled @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
Promise.then (async)
step @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
fulfilled @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
Promise.then (async)
step @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
fulfilled @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5
Promise.then (async)
step @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:7
(anonymous) @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:8
__awaiter @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:4
start @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:322
(anonymous) @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/registry.js:121
fulfilled @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/registry.js:5
Promise.then (async)
step @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/registry.js:7
fulfilled @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/registry.js:5
Promise.then (async)
step @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/registry.js:7
(anonymous) @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/registry.js:8
__awaiter @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/registry.js:4
timeoutCallback @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/registry.js:77
(anonymous) @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/registry.js:146
(anonymous) @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/registry.js:8
__awaiter @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/registry.js:4
Registry.scheduleSync @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/registry.js:57
(anonymous) @ /tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/registry.js:223
listOnTimeout @ internal/timers.js:549
processTimers @ internal/timers.js:492
/tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/Logger.js:188 10:28:03: Synchronizer: FetchError {name: "FetchError", message: "request to https://example.com/nextcloud/remot…info.json failed, reason: certificate has expired", type: "system", errno: "CERT_HAS_EXPIRED", code: "CERT_HAS_EXPIRED", …}code: "CERT_HAS_EXPIRED"errno: "CERT_HAS_EXPIRED"message: "request to https://example.com/nextcloud/remote.php/webdav/joplin/info.json failed, reason: certificate has expired"name: "FetchError"type: "system"stack: "FetchError: request to https://example.com/nextcloud/remote.php/webdav/joplin/info.json failed, reason: certificate has expired↵    at ClientRequest.<anonymous> (/tmp/.mount_JoplinT80Zmh/resources/app.asar/node_modules/@joplin/lib/node_modules/node-fetch/index.js:133:11)↵    at ClientRequest.emit (events.js:310:20)↵    at ClientRequest.EventEmitter.emit (domain.js:482:12)↵    at TLSSocket.socketErrorListener (_http_client.js:426:9)↵    at TLSSocket.emit (events.js:310:20)↵    at TLSSocket.EventEmitter.emit (domain.js:482:12)↵    at emitErrorNT (internal/streams/destroy.js:92:8)↵    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)↵    at processTicksAndRejections (internal/process/task_queues.js:84:21)"__proto__: Error
```

**Comment by devosb** [comment]
Seems like the same issue was reported while I was typing this up.

- https://github.com/laurent22/joplin/issues/5513
- https://github.com/flathub/net.cozic.joplin_desktop/issues/22

**Comment by laurent22** [comment]
Closed in favour of the other issue, but feel free to add as a comment any missing info.
