### ISSUE TITLE
No matching version found for @joplin/lib@~2.5

### ISSUE THREAD

**Issue by Paragoumba** [laurent22/joplin#5522]
I tried to update the joplin package from the AUR to the version 2.5.1 but @joplin/lib version 2.5 doesn't seem to have been uploaded. The latest version on npmjs.org is 2.4.3

## Environment

Joplin version: 2.5.1
Platform: Linux
OS specifics: ArchLinux

## Steps to reproduce

1. Try to build the app with the last pre-release

## Describe what you expected to happen
I expected Joplin 2.5.1 to compile

## Logfile

```
@joplin/lib: No matching version found for @joplin/lib@~2.5.
     at module.exports (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
     at /usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
     at async Promise.all (index 0)
     at async Arborist.[buildDepStep] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1017:5)
     at async Arborist.buildIdealTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:210:7)
     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:147:5)
     at async Install.install (/usr/lib/node_modules/npm/lib/install.js:170:5)
```

**Comment by Paragoumba** [comment]
Yeah you're right I'll fix it. And I think this is a bug as the app-cli package uses a version of joplin/lib that doesn't exists

**Comment by Paragoumba** [comment]
Updated

**Comment by laurent22** [comment]
We only support the build method described in BUILD.md. Anything else I don't know as I've never tried.

**Comment by Paragoumba** [comment]
Yes exactly. I fixed it by not compiling nor installing the CLI as I don't use it. I know it's not a good solution but I needed to have an up to date working joplin-desktop

**Comment by alfredopalhares** [comment]
I am still working on this issue at the moment, and it was its preventing me from updating the package.
