### ISSUE TITLE
Date error while importing Evernote *.enex

### ISSUE THREAD

**Issue by rapedapeda** [laurent22/joplin#557]
### Operating system
- macOS

### Application
- Desktop

### Error log

```
/Applications/Joplin.app/Contents/Resources/app/lib/import-enex.js:23 Uncaught Error: Invalid date: 20180306T91108 AMZ
    at dateToTimestamp (/Applications/Joplin.app/Contents/Resources/app/lib/import-enex.js:23:9)
    at SAXStream.<anonymous> (/Applications/Joplin.app/Contents/Resources/app/lib/import-enex.js:281:26)
    at emitOne (events.js:96:13)
    at SAXStream.emit (events.js:191:7)
    at SAXParser.me._parser.(anonymous function) [as ontext] (/Applications/Joplin.app/Contents/Resources/app/node_modules/sax/lib/sax.js:258:17)
    at emit (/Applications/Joplin.app/Contents/Resources/app/node_modules/sax/lib/sax.js:624:35)
    at closeText (/Applications/Joplin.app/Contents/Resources/app/node_modules/sax/lib/sax.js:634:26)
    at emitNode (/Applications/Joplin.app/Contents/Resources/app/node_modules/sax/lib/sax.js:628:26)
    at closeTag (/Applications/Joplin.app/Contents/Resources/app/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/Applications/Joplin.app/Contents/Resources/app/node_modules/sax/lib/sax.js:1436:13)

```

### ​Description

I'm getting this error when importing .enex files exported by the Evernote (also Mac) app.

**Comment by laurent22** [comment]
I'm not sure what "AMZ" is. Is there any chance you could open the ENEX file in a text editor and search for the "20180306T91108" string? Then could you post here the tag that contains this string? For example `<created>20180306T91108 AMZ</created>`

**Comment by laurent22** [comment]
Actually I think I know what it is. "91108 AMZ" probably means "9:11:08 am", and Z for UTC time zone. It will be fixed in the next release.
