### ISSUE TITLE
Server: DB autoupgrade can silently stall and never complete

### ISSUE THREAD

**Issue by Artanicus** [laurent22/joplin#5670]
## Environment

Joplin version: 2.5.10-beta (Server), Joplin 2.5.10 Desktop client (OS X)
Platform: Server
OS specifics: Tried with Docker image built from latest d22a29ee3d and the one labeled as `:2.5.10-beta`

## Steps to reproduce

1. With an existing user, create a new Notebook and select `Share Notebook...` from it's right-click menu in Joplin Desktop. (I'm using the OS X version )
2. Wait for the forced sync caused by the dialog to complete.

## Describe what you expected to happen

Expected to get an editable field where I can enter the email of the user I want to share to. Instead the dialog never becomes editable due to a backend failure. The failure is visible in the sync status panel and on server stderr.

## Logfile
```
2021-11-03 15:27:20: [error] App: 10.0.10.1 error: select distinct "items"."id", "items"."name", "items"."mime_type", "items"."updated_time", "items"."created_time", "items"."content_size", "items"."jop_id", "items"."jop_parent_id", "items"."jop_share_id", "items"."jop_type", "items"."jop_encryption_applied", "items"."jop_updated_time", "items"."owner_id" from "user_items" left join "items" on "items"."id" = "user_items"."item_id" where "user_items"."user_id" in ($1) and "name" in ($2) - column items.owner_id does not exist
    at Parser.parseErrorMessage (/home/joplin/packages/server/node_modules/pg-protocol/src/parser.ts:357:11)
    at Parser.handlePacket (/home/joplin/packages/server/node_modules/pg-protocol/src/parser.ts:186:21)
    at Parser.parse (/home/joplin/packages/server/node_modules/pg-protocol/src/parser.ts:101:30)
    at Socket.<anonymous> (/home/joplin/packages/server/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23) {
  length: 113,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '289',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3513',
  routine: 'errorMissingColumn'
}
```

This should probably block full release of Server 2.5.10

**Comment by laurent22** [comment]
What's the latest database migration (it shows up when you start the server)?

**Comment by Artanicus** [comment]
```
2021-11-03 15:14:23: App: Trying to connect to database...
2021-11-03 15:14:24: App: Connection check: {
  latestMigration: { name: '20210927183928_events.js' },
  isCreated: true,
  error: null
}
```

**Comment by laurent22** [comment]
It looks like some migrations didn't run. Do you have DB_AUTO_MIGRATION set to "0"?

**Comment by Artanicus** [comment]
I do not:
```
2021-11-03 16:21:17: App: DB Config: {
  client: 'pg',
  name: 'joplin',
  slowQueryLogEnabled: false,
  slowQueryLogMinDuration: 1000,
  autoMigration: true,
  user: 'joplin',
  password: '********',
  port: 28315,
  host: '10.0.10.4'
}

The logs for automigration are a bit weird:
```
2021-11-03 16:21:22: App: Auto-migrating database...
Processing items 0 / 39
2021-11-03 16:21:33: App: Starting services...
```

I don't see it completing anywhere further down the logs either. By the timestamps the auto migration is attempted before the first errors in the log, which are the missing column triggered by a sync.

```
Here's my full env's in use, Postgres is started as a sibling task.

Joplin:
```
 TZ  = "Europe/Berlin"
          APP_BASE_URL  = "https://joplin.example.com"
          APP_PORT      = "22300"
          DB_CLIENT     = "pg"
          POSTGRES_USER     = "joplin"
          POSTGRES_DATABASE = "joplin"
          POSTGRES_HOST     = "${NOMAD_IP_db}"
          POSTGRES_PORT     = "${NOMAD_HOST_PORT_db}"
          MAILER_ENABLED    = 1
         MAILER_NOREPLY_EMAIL = "joplinadmin+noreply@example.com"
          MAILER_HOST       = "smtp.example.com"
          MAILER_PORT       = 587
          MAILER_SECURE     = 0
```

Postgres (`postgres:13.1`):
```
TZ            = "Europe/Berlin"
          POSTGRES_USER = "joplin"
          POSTGRES_DB   = "joplin"
          POSTGRES_PASSWORD = "******"
```

Nothing obvious on the postgres side logs, besides the expected:
```
2021-11-03 16:22:54.663 EET [33] ERROR:  column items.owner_id does not exist at character 289
2021-11-03 16:22:54.663 EET [33] STATEMENT:  select distinct "items"."id", "items"."name", "items"."mime_type", "items"."updated_time", "items"."created_time", "items"."content_size", "items"."jop_id", "items"."jop_parent_id", "items"."jop_share_id", "items"."jop_type", "items"."jop_encryption_applied", "items"."jop_updated_time", "items"."owner_id" from "user_items" left join "items" on "items"."id" = "user_items"."item_id" where "user_items"."user_id" in ($1) and "name" in ($2)
2021-11-03 16:22:58.717 EET [33] ERROR:  column items.owner_id does not exist at character 289
```

**Comment by Artanicus** [comment]
Yeah, that migration message seems to be there for every start. So the migration gets stuck somehow it seems. I'll see if I can add some more instrumentation (read: massive logging) around that portion of the code to see what's going on.

**Comment by Artanicus** [comment]
Nice. So what happens is that it sits at 0/39 for a few seconds and then exits. 

```
$ node packages/server/dist/app.js migrate list
2021-11-03 20:01:53: MigrateCommand: ✓ 20190913171451_create
2021-11-03 20:01:53: MigrateCommand: ✓ 20203012152842_notifications
2021-11-03 20:01:53: MigrateCommand: ✓ 20203012152842_shares
2021-11-03 20:01:53: MigrateCommand: ✓ 20210201143859_app_share
2021-11-03 20:01:53: MigrateCommand: ✓ 20210321112923_joplin_items
2021-11-03 20:01:53: MigrateCommand: ✓ 20210328114529_share_folder
2021-11-03 20:01:53: MigrateCommand: ✓ 20210412110640_item_refactor
2021-11-03 20:01:53: MigrateCommand: ✓ 20210517173042_user_item_size_limit
2021-11-03 20:01:53: MigrateCommand: ✓ 20210518150551_can_share
2021-11-03 20:01:53: MigrateCommand: ✓ 20210518172311_mailer
2021-11-03 20:01:53: MigrateCommand: ✓ 20210526180359_account_type
2021-11-03 20:01:53: MigrateCommand: ✓ 20210527161932_can_upload
2021-11-03 20:01:53: MigrateCommand: ✓ 20210531150817_stripe
2021-11-03 20:01:53: MigrateCommand: ✓ 20210618192423_jop_updated_time
2021-11-03 20:01:53: MigrateCommand: ✓ 20210621185454_share_permissions
2021-11-03 20:01:53: MigrateCommand: ✓ 20210702182439_account_max_total_size
2021-11-03 20:01:53: MigrateCommand: ✓ 20210702182440_account_max_total_size_2
2021-11-03 20:01:53: MigrateCommand: ✓ 20210703155118_lowercase_emails
2021-11-03 20:01:53: MigrateCommand: ✓ 20210703202852_account_total_size_int_fix
2021-11-03 20:01:53: MigrateCommand: ✓ 20210703202853_account_total_size_int_fix_2
2021-11-03 20:01:53: MigrateCommand: ✓ 20210721161355_user_is_deleted
2021-11-03 20:01:53: MigrateCommand: ✓ 20210809163307_email_key
2021-11-03 20:01:53: MigrateCommand: ✓ 20210809222118_email_key_fix
2021-11-03 20:01:53: MigrateCommand: ✓ 20210819165350_user_flags
2021-11-03 20:01:53: MigrateCommand: ✓ 20210927183928_events
2021-11-03 20:01:53: MigrateCommand: ✓ 20211027112530_item_owner
2021-11-03 20:01:53: MigrateCommand: ✓ 20211030103016_item_owner_name_unique
```

Running it again the migration is not re-run. So clearly this time at least it did something useful. Sure enough, now sync and the sharing dialog no longer trigger the bug.

**Comment by Artanicus** [comment]
Just a quick note that it happened again with the latest upgrades. The logs seem to imply that the automatic is run but the changes don't actually happen until I run them manually. Will keep poking at it since this is getting into the murder mystery territory.
