### ISSUE TITLE
Joplin Server stopped accepting the boolean values "true" and "false" in v2.6.2

### ISSUE THREAD

**Issue by whalehub** [laurent22/joplin#5677]
## Environment
**Joplin version:** 2.6.2
**Platform:** Linux
**OS specifics:** Debian 11

## Steps to reproduce
1. Install Docker.
2. Launch Joplin server v2.6.2 with an environment variable that has a boolean value of "true" or "false":
```
docker run --rm -it -e MAILER_ENABLED=false joplin/server:2.6.2-beta
```

## Describe what you expected to happen
Joplin Server accepted the boolean values of "true" and "false" in previous versions (see below), but ever since [this](https://github.com/laurent22/joplin/commit/b5d792c606248343495286613795310781795dfd#diff-d61778a2ecda32d50dbb2c9c8d8d848c717ef6876891883ca3a9959c82034c1eR127-R129) commit was merged, it only accepts "1" and "0" respectively (see below as well).

```
docker run --rm -it -e MAILER_ENABLED=false joplin/server:2.5.10-beta

> @joplin/server@2.5.10 start
> node dist/app.js

2021-11-05 07:17:33: App: Starting server v2.5.10 (prod) on port 22300 and PID 19...
2021-11-05 07:17:33: App: Running in Docker: true
2021-11-05 07:17:33: App: Public base URL: http://localhost:22300
2021-11-05 07:17:33: App: API base URL: http://localhost:22300
2021-11-05 07:17:33: App: User content base URL: http://localhost:22300
2021-11-05 07:17:33: App: Log dir: /home/joplin/packages/server/logs
2021-11-05 07:17:33: App: DB Config: {
  client: 'sqlite3',
  name: '/home/joplin/packages/server/db-prod.sqlite',
  slowQueryLogEnabled: false,
  slowQueryLogMinDuration: 10000,
  autoMigration: true,
  asyncStackTraces: true
}
2021-11-05 07:17:33: App: Trying to connect to database...
2021-11-05 07:17:33: App: Connection check: { latestMigration: null, isCreated: false, error: null }
2021-11-05 07:17:33: App: Auto-migrating database...
2021-11-05 07:17:34: App: Starting services...
2021-11-05 07:17:34: ShareService: Starting maintenance...
2021-11-05 07:17:34: EmailService: Service will be disabled because mailer config is not set or is explicitly disabled
2021-11-05 07:17:34: TaskService: Scheduling #1 (Delete expired tokens): 0 */6 * * *
2021-11-05 07:17:34: TaskService: Scheduling #2 (Update total sizes): 0 * * * *
2021-11-05 07:17:34: TaskService: Scheduling #3 (Process oversized accounts): 0 */2 30 * *
2021-11-05 07:17:34: App: Call this for testing: `curl http://localhost:22300/api/ping`
2021-11-05 07:17:34: ShareService: Maintenance completed in 23ms
```

```
docker run --rm -it -e MAILER_ENABLED=0 joplin/server:2.6.2-beta

> @joplin/server@2.6.2 start
> node dist/app.js

2021-11-05 07:19:37: App: Starting server v2.6.2 (prod) on port 22300 and PID 20...
2021-11-05 07:19:37: App: Running in Docker: true
2021-11-05 07:19:37: App: Public base URL: http://localhost:22300
2021-11-05 07:19:37: App: API base URL: http://localhost:22300
2021-11-05 07:19:37: App: User content base URL: http://localhost:22300
2021-11-05 07:19:37: App: Log dir: /home/joplin/packages/server/logs
2021-11-05 07:19:37: App: DB Config: {
  client: 'sqlite3',
  name: '/home/joplin/packages/server/db-prod.sqlite',
  slowQueryLogEnabled: false,
  slowQueryLogMinDuration: 1000,
  autoMigration: true,
  asyncStackTraces: true
}
2021-11-05 07:19:37: App: Mailer Config: {
  enabled: false,
  host: '',
  port: 587,
  secure: true,
  authUser: '',
  authPassword: '********',
  noReplyName: '',
  noReplyEmail: ''
}
2021-11-05 07:19:37: App: Trying to connect to database...
2021-11-05 07:19:37: App: Connection check: { latestMigration: null, isCreated: false, error: null }
2021-11-05 07:19:38: App: Auto-migrating database...
2021-11-05 07:19:38: App: Starting services...
2021-11-05 07:19:38: ShareService: Starting maintenance...
2021-11-05 07:19:38: EmailService: Service will be disabled because mailer config is not set or is explicitly disabled
2021-11-05 07:19:38: TaskService: Scheduling #1 (Delete expired tokens): 0 */6 * * *
2021-11-05 07:19:38: TaskService: Scheduling #2 (Update total sizes): 0 * * * *
2021-11-05 07:19:38: TaskService: Scheduling #3 (Process oversized accounts): 0 */2 30 * *
2021-11-05 07:19:38: App: Call this for testing: `curl http://localhost:22300/api/ping`
2021-11-05 07:19:38: ShareService: Maintenance completed in 23ms
```

## Logfile
```
> @joplin/server@2.6.2 start
> node dist/app.js

Error: Invalid boolean for for env variable MAILER_ENABLED: false
    at Object.parseEnv (/home/joplin/packages/server/src/env.ts:128:58)
    at /home/joplin/packages/server/src/app.ts:99:23
    at Generator.next (<anonymous>)
    at fulfilled (/home/joplin/packages/server/dist/app.js:5:58)
```

**Comment by laurent22** [comment]
It was a bug that it was "accepting" false as a string, as you could have put any string and it would have worked. Now you need to set it as 0 or 1. But also please watch this pull request as we're going to change the mailer settings: https://github.com/laurent22/joplin/pull/5369

**Comment by whalehub** [comment]
> Now you need to set it as 0 or 1.

How come? The default values for environment variables that only accept boolean values still use "true" and "false" instead of "1" and 0" (see [here](https://github.com/laurent22/joplin/commit/b5d792c606248343495286613795310781795dfd#diff-d61778a2ecda32d50dbb2c9c8d8d848c717ef6876891883ca3a9959c82034c1eR70-R75) for reference), so the user should be able to as well, right?

**Comment by laurent22** [comment]
No it's 0 and 1 and it's always been. The difference now is that validation is stricter. Before anything other than "1" was understood as false. Including the string "false", but even the string "true" would be understood as false. Now if it's anything other than 0 or 1 it throws an error.

The error message is rubbish though and should be improved.

**Comment by whalehub** [comment]
@laurent22 I understand that the previous behavior was broken, but I don't understand why the fix for it is to only accept 0 or 1. JavaScript allows you to check if a value is a boolean using `typeof` and that very check is already being used by Joplin [here](https://github.com/laurent22/joplin/commit/b5d792c606248343495286613795310781795dfd#diff-d61778a2ecda32d50dbb2c9c8d8d848c717ef6876891883ca3a9959c82034c1eR127). That's why I'm confused about the need for an additional check for 0 or 1 after that.
