### ISSUE TITLE
Could not refresh lock - cancelling sync when on macos sync nextcloud 

### ISSUE THREAD

**Issue by nzlov** [laurent22/joplin#5717]
sync fail and very slow.

## Environment

Joplin version: 2.5.12
Platform: macos
OS specifics: macos 11.6.1

## Steps to reproduce

1. Delete local data and re-download from sync target

## Describe what you expected to happen

sync success.

## Logfile

```
2021-11-14 00:01:53: RepositoryApi: "findWorkingMirror: Could not connect to https://raw.githubusercontent.com/joplin/plugins/master:", "TypeError: Failed to fetch
TypeError: Failed to fetch"
2021-11-14 00:01:54: RepositoryApi: "findWorkingMirror: Using: https://cdn.staticaly.com/gh/joplin/plugins/master"
2021-11-14 00:02:06: App: "Profile directory: /Users/nzlov/.config/joplin-desktop"
2021-11-14 00:02:06: "Database was open successfully"
2021-11-14 00:02:06: "Checking for database schema update..."
2021-11-14 00:02:06: "Current database version", "null"
2021-11-14 00:02:06: "Upgrading database from version 0"
2021-11-14 00:02:06: "Converting database to version 1"
2021-11-14 00:02:06: "Converting database to version 2"
2021-11-14 00:02:06: "Converting database to version 3"
2021-11-14 00:02:06: "Converting database to version 4"
2021-11-14 00:02:06: "Converting database to version 5"
2021-11-14 00:02:06: "Converting database to version 6"
2021-11-14 00:02:06: "Converting database to version 7"
2021-11-14 00:02:06: "Converting database to version 8"
2021-11-14 00:02:06: "Converting database to version 9"
2021-11-14 00:02:06: "Converting database to version 10"
2021-11-14 00:02:06: "Converting database to version 11"
2021-11-14 00:02:06: "Converting database to version 12"
2021-11-14 00:02:06: "Converting database to version 13"
2021-11-14 00:02:06: "Converting database to version 14"
2021-11-14 00:02:06: "Converting database to version 15"
2021-11-14 00:02:06: "Converting database to version 16"
2021-11-14 00:02:06: "Converting database to version 17"
2021-11-14 00:02:06: "Converting database to version 18"
2021-11-14 00:02:06: "Converting database to version 19"
2021-11-14 00:02:06: "Converting database to version 20"
2021-11-14 00:02:06: "Converting database to version 21"
2021-11-14 00:02:06: "Converting database to version 22"
2021-11-14 00:02:06: "Converting database to version 23"
2021-11-14 00:02:06: "Converting database to version 24"
2021-11-14 00:02:06: "Converting database to version 25"
2021-11-14 00:02:06: "Converting database to version 26"
2021-11-14 00:02:06: "Converting database to version 27"
2021-11-14 00:02:06: "Converting database to version 28"
2021-11-14 00:02:06: "Converting database to version 29"
2021-11-14 00:02:06: "Converting database to version 30"
2021-11-14 00:02:06: "Converting database to version 31"
2021-11-14 00:02:06: "Converting database to version 32"
2021-11-14 00:02:06: "Converting database to version 33"
2021-11-14 00:02:06: "Converting database to version 34"
2021-11-14 00:02:06: "Migration failed with fallback and will not be repeated - saving version number"
2021-11-14 00:02:06: "Converting database to version 35"
2021-11-14 00:02:06: "Converting database to version 36"
2021-11-14 00:02:06: "Converting database to version 37"
2021-11-14 00:02:06: "Converting database to version 38"
2021-11-14 00:02:06: "Converting database to version 39"
2021-11-14 00:02:06: "New version: 39. Previously recorded version: 0"
2021-11-14 00:02:06: "Initializing tables..."
2021-11-14 00:02:06: "KeychainService: checking if keychain supported"
2021-11-14 00:02:06: "KeychainService: tried to set and get password. Result was:", "mytest"
2021-11-14 00:02:06: e2ee/utils: "Master password is not set - trying to get it from the active master key..."
2021-11-14 00:02:06: handleSyncStartupOperation: "Processing operation:", "0"
2021-11-14 00:02:06: App: "Client ID: bde3c67575014edb864d604da108b5dd"
2021-11-14 00:02:06: "First start: detected locale as en_GB"
2021-11-14 00:02:06: models/Setting: "Skipping all default migrations..."
2021-11-14 00:02:06: e2ee/utils: "Trying to load 0 master keys..."
2021-11-14 00:02:06: e2ee/utils: "Loaded master keys: 0"
2021-11-14 00:02:06: "ResourceFetcher: Auto-add resources: Mode: always"
2021-11-14 00:02:06: "ResourceFetcher: Auto-added resources: 0"
2021-11-14 00:02:06: "Running migration: 20"
2021-11-14 00:02:06: "Running migration: 27"
2021-11-14 00:02:06: "Running migration: 33"
2021-11-14 00:02:06: "SearchEngine: Updating FTS table..."
2021-11-14 00:02:06: "Running migration: 35"
2021-11-14 00:02:06: "SearchEngine: Updating FTS table..."
2021-11-14 00:02:06: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-11-14 00:02:06: e2ee/utils: "Trying to load 0 master keys..."
2021-11-14 00:02:06: e2ee/utils: "Loaded master keys: 0"
2021-11-14 00:02:06: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-11-14 00:02:06: e2ee/utils: "Trying to load 0 master keys..."
2021-11-14 00:02:06: e2ee/utils: "Loaded master keys: 0"
2021-11-14 00:02:06: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-11-14 00:02:06: e2ee/utils: "Trying to load 0 master keys..."
2021-11-14 00:02:06: e2ee/utils: "Loaded master keys: 0"
2021-11-14 00:02:06: "app.start: doing regular boot"
2021-11-14 00:02:06: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-11-14 00:02:06: e2ee/utils: "Trying to load 0 master keys..."
2021-11-14 00:02:06: e2ee/utils: "Loaded master keys: 0"
2021-11-14 00:02:06: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-11-14 00:02:06: e2ee/utils: "Trying to load 0 master keys..."
2021-11-14 00:02:06: e2ee/utils: "Loaded master keys: 0"
2021-11-14 00:02:06: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-11-14 00:02:06: e2ee/utils: "Trying to load 0 master keys..."
2021-11-14 00:02:06: e2ee/utils: "Loaded master keys: 0"
2021-11-14 00:02:07: RevisionService: "RevisionService::runInBackground: Starting background service with revision collection interval 600000"
2021-11-14 00:02:07: SpellCheckerServiceDriverNative: "Set effective language from "en-US" to "en-US""
2021-11-14 00:02:07: SpellCheckerServiceDriverNative: "Set effective language from "en-US" to "en-US""
2021-11-14 00:02:08: "DecryptionWorker: cannot start because no master key is currently loaded."
2021-11-14 00:02:08: "Preparing scheduled sync"
2021-11-14 00:02:08: "Sync cancelled - no sync target is selected."
2021-11-14 00:02:08: "Updating all notifications..."
2021-11-14 00:02:08: "Garbage collecting alarms..."
2021-11-14 00:02:09: "DecryptionWorker: cannot start because no master key is currently loaded."
2021-11-14 00:02:11: RevisionService: "RevisionService::maintenance: Starting..."
2021-11-14 00:02:11: RevisionService: "RevisionService::maintenance: Service is enabled"
2021-11-14 00:02:11: RevisionService: "RevisionService::collectRevisions: Created revisions for 0 notes"
2021-11-14 00:02:11: RevisionService: "RevisionService::maintenance: Done in 138ms"
2021-11-14 00:02:12: checkForUpdates: "Starting..."
2021-11-14 00:02:12: checkForUpdates: "Checking with options {"includePreReleases":false}"
2021-11-14 00:02:14: checkForUpdates: "Current version: 2.5.12"
2021-11-14 00:02:14: checkForUpdates: "Latest version: 2.5.12"
2021-11-14 00:02:14: checkForUpdates: "Is Pre-release:", "false"
2021-11-14 00:02:14: checkForUpdates: "Done."
2021-11-14 00:02:16: "SearchEngine: Updating FTS table..."
2021-11-14 00:02:16: "SearchEngine: Updated FTS table in 32ms. Inserted: 5. Deleted: 0"
2021-11-14 00:02:19: RepositoryApi: "findWorkingMirror: Could not connect to https://raw.githubusercontent.com/joplin/plugins/master:", "TypeError: Failed to fetch
TypeError: Failed to fetch"
2021-11-14 00:02:19: RepositoryApi: "findWorkingMirror: Using: https://cdn.staticaly.com/gh/joplin/plugins/master"
2021-11-14 00:02:37: "ResourceService::indexNoteResources: Start"
2021-11-14 00:02:37: "ResourceService::indexNoteResources: Completed"
2021-11-14 00:02:37: "ResourceService::deleteOrphanResources:", "[]"
2021-11-14 00:02:38: "Preparing scheduled sync"
2021-11-14 00:02:38: "Sync cancelled - no sync target is selected."
2021-11-14 00:04:05: App: "Profile directory: /Users/nzlov/.config/joplin-desktop"
2021-11-14 00:04:05: "Database was open successfully"
2021-11-14 00:04:05: "Checking for database schema update..."
2021-11-14 00:04:05: "Current database version", "{"version":39,"table_fields_version":39}"
2021-11-14 00:04:05: "Upgrading database from version 39"
2021-11-14 00:04:05: "New version: 39. Previously recorded version: 39"
2021-11-14 00:04:05: "KeychainService: checking if keychain supported"
2021-11-14 00:04:05: "KeychainService: check was already done - skipping. Supported:", "1"
2021-11-14 00:04:05: e2ee/utils: "Master password is not set - trying to get it from the active master key..."
2021-11-14 00:04:05: handleSyncStartupOperation: "Processing operation:", "2"
2021-11-14 00:04:05: App: "Client ID: bde3c67575014edb864d604da108b5dd"
2021-11-14 00:04:05: models/Setting: "Applying default migrations..."
2021-11-14 00:04:05: e2ee/utils: "Trying to load 0 master keys..."
2021-11-14 00:04:05: e2ee/utils: "Loaded master keys: 0"
2021-11-14 00:04:05: "ResourceFetcher: Auto-add resources: Mode: always"
2021-11-14 00:04:05: "ResourceFetcher: Auto-added resources: 0"
2021-11-14 00:04:05: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-11-14 00:04:05: e2ee/utils: "Trying to load 0 master keys..."
2021-11-14 00:04:05: e2ee/utils: "Loaded master keys: 0"
2021-11-14 00:04:05: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-11-14 00:04:05: e2ee/utils: "Trying to load 0 master keys..."
2021-11-14 00:04:05: e2ee/utils: "Loaded master keys: 0"
2021-11-14 00:04:05: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-11-14 00:04:05: e2ee/utils: "Trying to load 0 master keys..."
2021-11-14 00:04:05: e2ee/utils: "Loaded master keys: 0"
2021-11-14 00:04:05: "app.start: doing regular boot"
2021-11-14 00:04:05: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-11-14 00:04:05: e2ee/utils: "Trying to load 0 master keys..."
2021-11-14 00:04:05: e2ee/utils: "Loaded master keys: 0"
2021-11-14 00:04:05: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-11-14 00:04:05: e2ee/utils: "Trying to load 0 master keys..."
2021-11-14 00:04:05: e2ee/utils: "Loaded master keys: 0"
2021-11-14 00:04:05: App: ""syncInfoCache" was changed - setting up encryption related code"
2021-11-14 00:04:05: e2ee/utils: "Trying to load 0 master keys..."
2021-11-14 00:04:05: e2ee/utils: "Loaded master keys: 0"
2021-11-14 00:04:05: RevisionService: "RevisionService::runInBackground: Starting background service with revision collection interval 600000"
2021-11-14 00:04:05: SpellCheckerServiceDriverNative: "Set effective language from "en-US" to "en-US""
2021-11-14 00:04:06: "DecryptionWorker: cannot start because no master key is currently loaded."
2021-11-14 00:04:06: "Preparing scheduled sync"
2021-11-14 00:04:06: "Starting scheduled sync"
2021-11-14 00:04:06: Synchronizer: "Sync: starting: Starting synchronisation to target 5... supportsAccurateTimestamp = false; supportsMultiPut = false [1636819446903]"
2021-11-14 00:04:06: Synchronizer: "Indexing resources..."
2021-11-14 00:04:06: "ResourceService::indexNoteResources: Start"
2021-11-14 00:04:07: "ResourceService::indexNoteResources: Completed"
2021-11-14 00:04:09: RevisionService: "RevisionService::maintenance: Starting..."
2021-11-14 00:04:09: RevisionService: "RevisionService::maintenance: Service is enabled"
2021-11-14 00:04:09: RevisionService: "RevisionService::collectRevisions: Created revisions for 0 notes"
2021-11-14 00:04:09: RevisionService: "RevisionService::maintenance: Done in 106ms"
2021-11-14 00:04:10: checkForUpdates: "Starting..."
2021-11-14 00:04:10: checkForUpdates: "Checking with options {"includePreReleases":false}"
2021-11-14 00:04:13: checkForUpdates: "Current version: 2.5.12"
2021-11-14 00:04:13: checkForUpdates: "Latest version: 2.5.12"
2021-11-14 00:04:13: checkForUpdates: "Is Pre-release:", "false"
2021-11-14 00:04:13: checkForUpdates: "Done."
2021-11-14 00:04:14: Synchronizer: "Sync target remote info:", "{"version_":3,"masterKeys_":[],"e2ee_":{"value":false,"updatedTime":0},"activeMasterKeyId_":{"value":"","updatedTime":0},"ppk_":{"value":null,"updatedTime":0}}"
2021-11-14 00:04:14: Synchronizer: "Sync target is already setup - checking it..."
2021-11-14 00:04:14: Synchronizer: "Sync target local info:", "{"version_":3,"masterKeys_":[],"e2ee_":{"value":false,"updatedTime":0},"activeMasterKeyId_":{"value":"","updatedTime":0},"ppk_":{"value":null,"updatedTime":0}}"
2021-11-14 00:04:15: "SearchEngine: Updating FTS table..."
2021-11-14 00:04:15: "SearchEngine: Updated FTS table in 1ms. Inserted: 0. Deleted: 0"
2021-11-14 00:04:35: "ResourceService::indexNoteResources: Start"
2021-11-14 00:04:35: "ResourceService::indexNoteResources: Completed"
2021-11-14 00:04:35: "ResourceService::deleteOrphanResources:", "[]"
2021-11-14 00:05:45: Synchronizer: "BasicDelta: Report: {"timestamp":0,"older":0,"newer":1,"equal":0}"
2021-11-14 00:05:45: Synchronizer: "Sync: fetchingTotal: Fetching delta items from sync target"
2021-11-14 00:05:45: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2021-11-14 00:05:53: Synchronizer: "Sync: createLocal: remote exists but local does not: (Remote 014fb7c529864bbcb3f69d15365b0e31.md)"
2021-11-14 00:05:53: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2021-11-14 00:06:01: Synchronizer: "Sync: createLocal: remote exists but local does not: (Remote 01618cf97b854e1a98731ab8d90f2a92.md)"
2021-11-14 00:06:01: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2021-11-14 00:06:01: "ResourceFetcher: Auto-add resources: Mode: always"
2021-11-14 00:06:01: "ResourceFetcher: Auto-added resources: 1"
2021-11-14 00:06:01: "ResourceFetcher: Auto-add resources: Mode: always"
2021-11-14 00:06:01: "ResourceFetcher: Auto-added resources: 0"
2021-11-14 00:06:15: Synchronizer: "Sync: createLocal: remote exists but local does not: (Remote 018dc8e52a224b369cafa08de5d15992.md)"
2021-11-14 00:06:15: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2021-11-14 00:06:15: "ResourceFetcher: Auto-add resources: Mode: always"
2021-11-14 00:06:15: "ResourceFetcher: Auto-added resources: 1"
2021-11-14 00:06:16: "ResourceFetcher: Auto-add resources: Mode: always"
2021-11-14 00:06:16: "ResourceFetcher: Auto-added resources: 0"
2021-11-14 00:06:20: RepositoryApi: "findWorkingMirror: Could not connect to https://raw.githubusercontent.com/joplin/plugins/master:", "TypeError: Failed to fetch
TypeError: Failed to fetch"
2021-11-14 00:06:21: RepositoryApi: "findWorkingMirror: Using: https://cdn.staticaly.com/gh/joplin/plugins/master"
2021-11-14 00:06:29: Synchronizer: "Sync: createLocal: remote exists but local does not: (Remote 02203c11c1f4480393f2d872faf5367a.md)"
2021-11-14 00:06:29: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2021-11-14 00:06:29: "ResourceFetcher: Auto-add resources: Mode: always"
2021-11-14 00:06:29: "ResourceFetcher: Auto-added resources: 0"
2021-11-14 00:06:37: Synchronizer: "Sync: createLocal: remote exists but local does not: (Remote 0399054a76524be892160ec541cc0c82.md)"
2021-11-14 00:06:37: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2021-11-14 00:06:45: Synchronizer: "Sync: createLocal: remote exists but local does not: (Remote 040ce83433e84b80b1b1b86e4821e242.md)"
2021-11-14 00:06:45: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2021-11-14 00:06:45: "ResourceFetcher: Auto-add resources: Mode: always"
2021-11-14 00:06:45: "ResourceFetcher: Auto-added resources: 1"
2021-11-14 00:06:45: "ResourceFetcher: Auto-add resources: Mode: always"
2021-11-14 00:06:45: "ResourceFetcher: Auto-added resources: 0"
2021-11-14 00:06:59: Synchronizer: "Sync: createLocal: remote exists but local does not: (Remote 0484efc8ec50416f97432f95e16733fd.md)"
2021-11-14 00:06:59: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2021-11-14 00:06:59: "ResourceFetcher: Auto-add resources: Mode: always"
2021-11-14 00:06:59: "ResourceFetcher: Auto-added resources: 1"
2021-11-14 00:06:59: "ResourceFetcher: Auto-add resources: Mode: always"
2021-11-14 00:06:59: "ResourceFetcher: Auto-added resources: 0"
2021-11-14 00:07:13: Synchronizer: "Sync: createLocal: remote exists but local does not: (Remote 04b144169dd0408aa578eda38304a793.md)"
2021-11-14 00:07:13: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2021-11-14 00:07:13: "ResourceFetcher: Auto-add resources: Mode: always"
2021-11-14 00:07:13: "ResourceFetcher: Auto-added resources: 1"
2021-11-14 00:07:13: "ResourceFetcher: Auto-add resources: Mode: always"
2021-11-14 00:07:13: "ResourceFetcher: Auto-added resources: 0"
2021-11-14 00:07:27: Synchronizer: "Sync: createLocal: remote exists but local does not: (Remote 04b8c750453c428d8848b978520f5483.md)"
2021-11-14 00:07:27: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2021-11-14 00:07:27: "ResourceFetcher: Auto-add resources: Mode: always"
2021-11-14 00:07:27: "ResourceFetcher: Auto-added resources: 1"
2021-11-14 00:07:28: "ResourceFetcher: Auto-add resources: Mode: always"
2021-11-14 00:07:28: "ResourceFetcher: Auto-added resources: 0"
2021-11-14 00:07:41: Synchronizer: "Sync: createLocal: remote exists but local does not: (Remote 04dd92787e3c474e8e3a40056770803c.md)"
2021-11-14 00:07:41: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2021-11-14 00:07:41: "ResourceFetcher: Auto-add resources: Mode: always"
2021-11-14 00:07:41: "ResourceFetcher: Auto-added resources: 0"
2021-11-14 00:07:51: Synchronizer: "Sync: createLocal: remote exists but local does not: (Remote 0601baa26c4a47b1bcd52227bb246357.md)"
2021-11-14 00:07:51: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2021-11-14 00:07:51: "ResourceFetcher: Auto-add resources: Mode: always"
2021-11-14 00:07:51: "ResourceFetcher: Auto-added resources: 1"
2021-11-14 00:07:52: "ResourceFetcher: Auto-add resources: Mode: always"
2021-11-14 00:07:52: "ResourceFetcher: Auto-added resources: 0"
2021-11-14 00:08:05: Synchronizer: "Sync: createLocal: remote exists but local does not: (Remote 06f921f150ab4eaba964cb639ecada28.md)"
2021-11-14 00:08:05: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2021-11-14 00:08:05: "ResourceFetcher: Auto-add resources: Mode: always"
2021-11-14 00:08:05: "ResourceFetcher: Auto-added resources: 0"
2021-11-14 00:08:12: Synchronizer: "Sync: createLocal: remote exists but local does not: (Remote 06fb2e0618304a14a14dae5daaf92868.md)"
2021-11-14 00:08:12: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2021-11-14 00:08:21: Synchronizer: "Sync: createLocal: remote exists but local does not: (Remote 082e04f0c16d463eb88ec57a25db95f7.md)"
2021-11-14 00:08:21: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2021-11-14 00:08:22: "SearchEngine: Updating FTS table..."
2021-11-14 00:08:22: "SearchEngine: Updated FTS table in 44ms. Inserted: 1. Deleted: 0"
2021-11-14 00:08:29: Synchronizer: "Sync: createLocal: remote exists but local does not: (Remote 087639e4ce0541529a5777e9a97a46d1.md)"
2021-11-14 00:08:29: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2021-11-14 00:08:38: Synchronizer: "Sync: createLocal: remote exists but local does not: (Remote 08abd70203f0436d8cd566a5d288ad43.md)"
2021-11-14 00:08:38: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2021-11-14 00:08:39: "SearchEngine: Updating FTS table..."
2021-11-14 00:08:40: "SearchEngine: Updated FTS table in 29ms. Inserted: 1. Deleted: 0"
2021-11-14 00:08:47: Synchronizer: "Sync: createLocal: remote exists but local does not: (Remote 08cb488584af43539c1541efcac651dd.md)"
2021-11-14 00:08:47: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2021-11-14 00:08:55: Synchronizer: "Sync: createLocal: remote exists but local does not: (Remote 096680e8f5b24a98a86d16ad7e8218a1.md)"
2021-11-14 00:08:55: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2021-11-14 00:09:04: Synchronizer: "Sync: createLocal: remote exists but local does not: (Remote 09996eb2097d497b8b5ca7f3a12e8e94.md)"
2021-11-14 00:09:05: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2021-11-14 00:09:05: "ResourceFetcher: Auto-add resources: Mode: always"
2021-11-14 00:09:05: "ResourceFetcher: Auto-added resources: 1"
2021-11-14 00:09:05: "ResourceFetcher: Auto-add resources: Mode: always"
2021-11-14 00:09:05: "ResourceFetcher: Auto-added resources: 0"
2021-11-14 00:09:18: Synchronizer: "Sync: createLocal: remote exists but local does not: (Remote 0ab07b506012401889d934e45e320f1a.md)"
2021-11-14 00:09:18: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2021-11-14 00:09:18: "ResourceFetcher: Auto-add resources: Mode: always"
2021-11-14 00:09:18: "ResourceFetcher: Auto-added resources: 0"
2021-11-14 00:09:26: Synchronizer: "Sync: createLocal: remote exists but local does not: (Remote 0b6176b6f34445358fbadc5435ac2480.md)"
2021-11-14 00:09:26: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2021-11-14 00:09:28: "SearchEngine: Updating FTS table..."
2021-11-14 00:09:28: "SearchEngine: Updated FTS table in 31ms. Inserted: 2. Deleted: 0"
2021-11-14 00:09:35: Synchronizer: "Sync: createLocal: remote exists but local does not: (Remote 0bb4fb47a59d4a36acafed9eba55d2d7.md)"
2021-11-14 00:09:35: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2021-11-14 00:09:44: Synchronizer: "Sync: createLocal: remote exists but local does not: (Remote 0bbef918c6dd41b6b035e6c959999ec5.md)"
2021-11-14 00:09:44: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2021-11-14 00:09:52: Synchronizer: "Sync: createLocal: remote exists but local does not: (Remote 0c4b465d7989491cb05a2039e470ee96.md)"
2021-11-14 00:09:52: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2021-11-14 00:09:52: "ResourceFetcher: Auto-add resources: Mode: always"
2021-11-14 00:09:52: "ResourceFetcher: Auto-added resources: 1"
2021-11-14 00:09:52: "ResourceFetcher: Auto-add resources: Mode: always"
2021-11-14 00:09:52: "ResourceFetcher: Auto-added resources: 0"
2021-11-14 00:09:54: "SearchEngine: Updating FTS table..."
2021-11-14 00:09:54: "SearchEngine: Updated FTS table in 29ms. Inserted: 1. Deleted: 0"
2021-11-14 00:10:07: Synchronizer: "Could not refresh lock - cancelling sync. Error was:", "Error: Lock has expired
Code: lockExpired
Error: Lock has expired
    at LockHandler.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/LockHandler.js:301:25)
    at Generator.next (<anonymous>)
    at fulfilled (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/LockHandler.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
2021-11-14 00:10:07: Synchronizer: "TaskQueue.stop: syncDownload: waiting for tasks to complete: 20"
2021-11-14 00:10:07: Synchronizer: "Sync: cancelling"
2021-11-14 00:10:07: "ResourceFetcher: Auto-add resources: Mode: always"
2021-11-14 00:10:07: "ResourceFetcher: Auto-added resources: 0"
2021-11-14 00:10:14: Synchronizer: "Sync: createLocal: remote exists but local does not: (Remote 0d289154c34c42e0b5318f6b9d9a87f3.md)"
2021-11-14 00:10:14: "ResourceFetcher: Auto-add resources: Mode: always"
2021-11-14 00:10:14: "ResourceFetcher: Auto-added resources: 1"
2021-11-14 00:10:14: "ResourceFetcher: Auto-add resources: Mode: always"
2021-11-14 00:10:14: "ResourceFetcher: Auto-added resources: 0"
2021-11-14 00:10:28: "ResourceFetcher: Auto-add resources: Mode: always"
2021-11-14 00:10:28: "ResourceFetcher: Auto-added resources: 0"
2021-11-14 00:10:37: Synchronizer: "TaskQueue.stop: syncDownload: timed out waiting for task to complete"
2021-11-14 00:10:37: Synchronizer: "TaskQueue.stop: syncDownload: Done, waited for 30004"
2021-11-14 00:13:10: Synchronizer: "Synchronisation was cancelled."
2021-11-14 00:13:10: Synchronizer: "Sync: finished: Synchronisation finished [1636819446903]"
2021-11-14 00:13:10: Synchronizer: "Operations completed: "
2021-11-14 00:13:10: Synchronizer: "fetchingTotal: 50"
2021-11-14 00:13:10: Synchronizer: "fetchingProcessed: 25"
2021-11-14 00:13:10: Synchronizer: "createLocal: 25"
2021-11-14 00:13:10: Synchronizer: "cancelling: 1"
2021-11-14 00:13:10: Synchronizer: "Total folders: 1"
2021-11-14 00:13:10: Synchronizer: "Total notes: 5"
2021-11-14 00:13:10: Synchronizer: "Total resources: 10"
2021-11-14 00:13:10: "Updating all notifications..."
2021-11-14 00:13:10: "Garbage collecting alarms..."
2021-11-14 00:13:11: "DecryptionWorker: cannot start because no master key is currently loaded."
2021-11-14 00:14:05: RevisionService: "RevisionService::maintenance: Starting..."
2021-11-14 00:14:05: RevisionService: "RevisionService::maintenance: Service is enabled"
2021-11-14 00:14:06: RevisionService: "RevisionService::collectRevisions: Created revisions for 0 notes"
2021-11-14 00:14:06: RevisionService: "RevisionService::maintenance: Done in 110ms"
2021-11-14 00:14:22: "Trying to reload note that has been deleted:", "null"

```

**Comment by manolonte** [comment]
I am still having a similar issue in Windows 10, nextcloud is target and Joplin version is 2.6.10. After less than half an hour and 200 items synchronized I see in log file:

2022-02-03 12:26:06: Synchronizer: "BasicDelta: Report: {"timestamp":1641373387000,"older":249,"newer":50,"equal":1}"
2022-02-03 12:26:06: Synchronizer: "Sync: fetchingTotal: Fetching delta items from sync target"
2022-02-03 12:26:06: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2022-02-03 12:26:14: Synchronizer: "Could not refresh lock - cancelling sync. Error was:", "Error: Lock has expired
Code: lockExpired
Error: Lock has expired
    at LockHandler.<anonymous> (C:\Users\guerrm21\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\services\synchronizer\LockHandler.js:347:25)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\guerrm21\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\services\synchronizer\LockHandler.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
