### ISSUE TITLE
The sync target could not be upgraded due to an error.

### ISSUE THREAD

**Issue by mpatca** [laurent22/joplin#5773]
The upgrade ends with an error message.

## Environment

Joplin version: 2.6.2
Platform: Windows 
OS specifics: 10

## Steps to reproduce

The error occurs when upgrading.

## Logfile

"Error
The sync target could not be upgraded due to an error. For support, please copy the complete content of this page and paste it in the forum: https://discourse.joplinapp.org/

The full error was:

Invalid lock client type: 2_desktop_f466761cfb1349a795b712d964cfaad6

Error: Invalid lock client type: 2_desktop_f466761cfb1349a795b712d964cfaad6
    at lockNameToObject (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\synchronizer\LockHandler.js:43:15)
    at LockHandler.lockFileToObject (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\synchronizer\LockHandler.js:142:16)
    at LockHandler.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\synchronizer\LockHandler.js:160:35)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\synchronizer\LockHandler.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)"

**Comment by cyphase** [comment]
I have the same issue, on Linux. I also tried upgrading mobile simultaneously and got a sync error saying `Error: Error: Operation not permitted. Path: /storage/.../Joplin/locks/2_2_38d2...c0db.json`.

**Comment by Dunc0** [comment]
I have this issue on Android. I was setting up sync for the first time with dropbox.

I first synced with Windows 10 and Dropbox successfully. Then tried to sync Android to dropbox and got The message:

Error 

The Sync target could not be upgraded due to an error . . . 

"Invalid lock client type:2_mobile_...

**Comment by bhulk** [comment]
I also have this problem:

Invalid lock client type: 2_desktop_90c944e39b4f4e338f15a7998dfb6fa8

**Comment by RicDeveloper** [comment]
Same like other. First installation on Win10, I create some notes, synched on Dropbox and then I enables encryption and re-synched. (no problems)
Next I installed the Android app, enabled synchronization with Dropbox (succesfully authenticate), but I got the same error
Invalid lock client type:  xxxxxxxx

**Comment by rugervakten** [comment]
Same issue here on Android. Sync via Resilio sync. Has worked fine for a long time.

**Comment by MadScienceZone** [comment]
I'm seeing the same issue on Android as well, using dropbox sync. Brand-new install as a 2nd device trying to sync my existing dropbox to the android.

```
invalid lock client type 2_mobile_13b3d0a3b7584a65bbda95451a1a5146
```

**Comment by hefax** [comment]
I have a similar issue as well. 

Joplin version: 2.6.2
Platform: Linux
Trying to sync with nextcloud via WebDAV

I get this on my main computer (where I had an older version of Joplin working fine) after I installed Joplin on my laptop I didn't get it to sync. After I updated to 2.6.2 on my main computer, it too started complaining about this. 


```
Invalid lock client type: 2_desktop_63d8fe82b17d4df49fc473271919b223

Error: Invalid lock client type: 2_desktop_63d8fe82b17d4df49fc473271919b223
    at lockNameToObject (/usr/lib/joplin/resources/app.asar/node_modules/@joplin/lib/services/synchronizer/LockHandler.js:43:15)
    at LockHandler.lockFileToObject (/usr/lib/joplin/resources/app.asar/node_modules/@joplin/lib/services/synchronizer/LockHandler.js:142:16)
    at LockHandler.<anonymous> (/usr/lib/joplin/resources/app.asar/node_modules/@joplin/lib/services/synchronizer/LockHandler.js:160:35)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/joplin/resources/app.asar/node_modules/@joplin/lib/services/synchronizer/LockHandler.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by bhulk** [comment]
I found a solution for me, I went into Dropbox and deleted the file that enclosed the synced items, then went back into desktop app and re-synced, it created a fresh copy in dropbox and synced to my phone. The folders got screwed up, but everything is still there just now unorganized.
Your mileage may vary for this as I do not think this is the official "fix"

**Comment by MadScienceZone** [comment]
I tried @bhulk 's solution, but unfortunately it didn't solve the problem.
(I exported all my content to a backup file, deleted the dropbox data, removed all the content from the app [because otherwise Joplin gets confused by the now-empty dropbox], re-imported the content, and re-synced. That put everything back the way it was, with all the content in Jopin and synced to a brand new dropbox folder. However, when I then added the Joplin app on my Android tablet, I got the same error as described above when trying to sync with dropbox to get the content on that device.)

**Comment by MadScienceZone** [comment]
I was able to resolve my issue with synchronization. It turns out my desktop client was a much earlier revision than I thought had been installed. Once that was upgraded everything works fine.

**Comment by cstrife1** [comment]
MadScienceZone above key me on the fix and it works. My Android Joplin using newest version (as of 20211213) wasn't sync due to sync target upgrade failure. So, I checked my Windows Joplin and it was an older build using Sync V2. I updated to newest Windows joplin, updated sync target to V3 from Windows. Then Android one syncs properly.

**Comment by Altrac00** [comment]
I have problem sync in Android, using filesystem sync with Syncthing. In windows 10 all works fine.
Both in latest version, Reinstaled in android, change sync folder on both devices.
![Screenshot_20211221-115642](https://user-images.githubusercontent.com/96493479/146976617-ed313b13-b60b-4e60-96d2-e64beea6886b.png)

**Comment by Dunc0** [comment]
Just wanted to come back and say that upgrading my windows10 instance *twice* fixed my issue.

I initiated the first update which lead to a change in behavior on android, but did not fully resolve the issue. A few days later, Joplin prompted me to upgrade the win 10 instance again, which I did. After that completed, I tried to sync on Android again and this time it worked perfectly.

I'm guessing that I was on such an old version from the initial download (maybe the download file should be updated?) that a stepwise upgrade was required.

Cheers!

**Comment by hefax** [comment]
Well I just fixed my issue by editing the info.json file on the server side (sync target side).  I just changed the version from 2 to 3 manually. I have no idea if I messed up anything by doing that but now the sync works on all my devices and everything seems to be working.. 

![image](https://user-images.githubusercontent.com/3091710/147474151-bbbfc629-62a3-4dd5-a4d3-c65829f6813b.png)

This feels like an awful hack with possibility for data corruption so be sure to backup everything before attempting this.. (but it world for me so I though I'd share.. )

**Comment by laurent22** [comment]
That was possibly a temporary issue after the upgrade. It doesn't seem to happen anymore but let's keep the bug open for now.
