### ISSUE TITLE
Joplin encountered a fatal error and could not continue.

### ISSUE THREAD

**Issue by MrCaringi** [laurent22/joplin#5799]
Joplin cant start in windows machine

## Environment

Joplin version: 2.0.1
Platform: Windows
OS specifics: 

## Steps to reproduce

1. 
2. 
3. 

## Describe what you expected to happen
To be able to open joplin

## Logfile

Message
Cannot read properties of null (reading 'wrappedInstance')

Version info
Joplin for Desktop

Copyright © 2016-2021 Laurent Cozic
Joplin 2.5.12 (prod, win32)

Client ID: 398c7be2cf9143f9863582261d366ffe
Sync Version: 3
Profile Version: 39
Keychain Supported: Yes

Revision: 884b86f
Plugins
[
    {
        "id": "ylc395.betterMarkdownViewer",
        "name": "Better Markdown Viewer",
        "enabled": true,
        "version": "2.0.1"
    },
    {
        "id": "joplin.plugin.note.tabs",
        "name": "Note Tabs",
        "enabled": true,
        "version": "1.4.0"
    }
]
Stack trace
TypeError: Cannot read properties of null (reading 'wrappedInstance')
    at C:\Users\jean.caringi\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteEditor\NoteBody\CodeMirror\CodeMirror.js:631:32
    at commitHookEffectList (C:\Users\jean.caringi\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:19986:26)
    at commitPassiveHookEffects (C:\Users\jean.caringi\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:20016:11)
    at HTMLUnknownElement.callCallback (C:\Users\jean.caringi\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:347:14)
    at Object.invokeGuardedCallbackDev (C:\Users\jean.caringi\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:397:16)
    at invokeGuardedCallback (C:\Users\jean.caringi\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:454:31)
    at flushPassiveEffectsImpl (C:\Users\jean.caringi\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:22868:7)
    at unstable_runWithPriority (C:\Users\jean.caringi\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\scheduler\cjs\scheduler.development.js:643:12)
    at runWithPriority$2 (C:\Users\jean.caringi\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11305:10)
    at flushPassiveEffects (C:\Users\jean.caringi\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:22841:10)
Component stack

    in ForwardRef(CodeMirror) (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in NoteEditor (created by Connect(NoteEditor))
    in Connect(NoteEditor) (created by ResizableLayout)
    in div (created by styled.div)
    in styled.div (created by ResizableLayout)
    in div (created by Resizable)
    in Resizable (created by ResizableLayout)
    in div (created by ResizableLayout)
    in ResizableLayout (created by MainScreenComponent)
    in div (created by MainScreenComponent)
    in MainScreenComponent (created by Connect(MainScreenComponent))
    in Connect(MainScreenComponent) (created by NavigatorComponent)
    in div (created by NavigatorComponent)
    in NavigatorComponent (created by Connect(NavigatorComponent))
    in Connect(NavigatorComponent) (created by RootComponent)
    in ThemeProvider (created by RootComponent)
    in StyleSheetManager (created by RootComponent)
    in RootComponent (created by Connect(RootComponent))
    in Connect(RootComponent)
    in ErrorBoundary
    in Provider

**Comment by laurent22** [comment]
How does it work with the latest version?

**Comment by MrCaringi** [comment]
I rebooted the windows.... now it works... dont know what happened.
thanks for your reply!
