### ISSUE TITLE
invalid sqlite3 version after "brew install joplin"

### ISSUE THREAD

**Issue by sv3nd** [laurent22/joplin#58]
### Operating system

- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [ ] Desktop
- [ ] Mobile
- [x] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

Hi, 

Thanks for developing joplin :) 

I just did a first-time install of Joplin terminal through `brew install joplin`, though as soon as I try to start it the startup script fails, complaining about a missing sqlite3 module. It seems the module is present but not in the expected version (see trace below). 

I am not familiar with javascript nor node. Don't hesitate to let me know if I can contribute any additional trace or test. 

Svend 

```
>joplin
module.js:471
    throw err;
    ^

Error: Cannot find module '/usr/local/Cellar/joplin/0.10.65/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v48-darwin-x64/node_sqlite3.
node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/Cellar/joplin/0.10.65/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)


> ls -l /usr/local/Cellar/joplin/0.10.65/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/
total 32
drwxr-xr-x  3 svend  admin    96 Nov  1 15:50 binding
-rw-r--r--  1 svend  admin    39 Nov  1 15:50 index.js
-rw-r--r--  1 svend  admin  5554 Nov  1 15:50 sqlite3.js
-rw-r--r--  1 svend  admin  1437 Nov  1 15:50 trace.js

> ls -l /usr/local/Cellar/joplin/0.10.65/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/binding
total 0
drwxr-xr-x  3 svend  admin  96 Dec  2 11:02 node-v57-darwin-x64


```

*If there is an error, please copy and paste the full error message*

---

**Comment by laurent22** [comment]
Hello, was node and npm installed via Homebrew?

**Comment by laurent22** [comment]
Also what is your node and npm version? `node --version && npm --version`

**Comment by sv3nd** [comment]
Hi, 

node seems to be have been installed via `brew`, though that's not the case of `npm`, I don't recall how I installed it: 

```
> brew list
ansible         gcc             glib            joplin          libtiff         mpfr            pandoc-citeproc python          tmux
cairo           gd              gmp             jpeg            libtool         mysql           parquet-tools   python3         unrar
cdargs          gdbm            gradle          libevent        libyaml         node            pcre            r               webp
exa             gettext         graphviz        libffi          maven           openssl         pixman          readline        wget
fontconfig      git             icu4c           libmpc          md5sha1sum      openssl@1.1     pkg-config      sbt             xz
freetype        git-lfs         isl             libpng          micro           pandoc          postgresql      sqlite          zsh

> which npm
/usr/local/bin/npm

> ls -l /usr/local/bin/npm
lrwxr-xr-x  1 502  staff  38 Dec 13  2016 /usr/local/bin/npm -> ../lib/node_modules/npm/bin/npm-cli.js
```
as for the versions: 
```
> node --version
v6.9.2

> npm --version
3.10.9
```

**Comment by laurent22** [comment]
The app actually requires node 8+ (I'm going to specify this in the Homebrew formula). Could you try to uninstall node and npm and reinstall them with Homebrew?
