### ISSUE TITLE
Joplin does not trust Android certificate store?

### ISSUE THREAD

**Issue by OdinVex** [laurent22/joplin#5871]
Yet another “Network Request Failed” post. Joplin Android won't connect to local WebDAV, Desktops all do.

I use my own certificate authority in my domain behind my router with private DNS as well. I've installed my CA-certificate on all devices, including my Android devices. While some apps need to be told to use Android's certificate/security store to work (Firefox, for example), some automatically trust the Android CS store.

I use my CA to sign certificates, the chain included is served by the web server. Other devices, Linux/Windows, they all work, even without “Ignore TLS certificate errors”, but that doesn't work. I believe it *only* ignores self-signed certificates, instead of TLS certificate errors (such as what I believe is happening, that Joplin isn't trusting it because it doesn't trust the CA or the Android CS store which does.)

## Environment

Joplin version: 2.6.3
Platform: Android
OS specifics:  v7, v9

## Steps to reproduce

1. Create a CA, import to all devices as trusted CA. Sign any intermediate/end certificates for use with a WebDAV server.
2. Point Joplin to a WebDAV.
3. Fail at synchronizing.

[syncReport-1639758713530.txt](https://github.com/laurent22/joplin/files/7736529/syncReport-1639758713530.txt)

**Comment by OdinVex** [comment]
If I wasn't clear, I'm putting forth that “Ignore TLS certificate errors” does not ignore TLS certificate errors, only self-signed certificate errors.

**Comment by roman-r-m** [comment]
It should trust all certificates. Does yours have `SubjectAlternativeName` matching the host name?

**Comment by roman-r-m** [comment]
That log is useless for such errors. Can you connect using adb and search for exceptions during synchronization?

**Comment by OdinVex** [comment]
> It should trust all certificates. Does yours have `SubjectAlternativeName` matching the host name?
> 
> EDIT Actually, this shouldn't be an issue.
Wildcard.
> That log is useless for such errors. Can you connect using adb and search for exceptions during synchronization?
I know, I've no idea why Joplin even has such logs, given the reason for the error is lost. I'll muck around to figure it out.

**Comment by roman-r-m** [comment]
> > It should trust all certificates. Does yours have `SubjectAlternativeName` matching the host name?
> > 
> > EDIT Actually, this shouldn't be an issue.
> Wildcard, and other software (Firefox for Android) will recognize it as trusted when told to use the Android CS store.
> > That log is useless for such errors. Can you connect using adb and search for exceptions during synchronization?
> I know, I've no idea why Joplin even has such logs, given the reason for the error is lost. I'll muck around to figure it out.

This log is useful when an error originates from the js side. In this case however this is coming from the native code, I think the library Joplin uses only reports a generic network request failed message

**Comment by OdinVex** [comment]
> > > It should trust all certificates. Does yours have `SubjectAlternativeName` matching the host name?
> > > EDIT Actually, this shouldn't be an issue.
> > > Wildcard, and other software (Firefox for Android) will recognize it as trusted when told to use the Android CS store.
> > > That log is useless for such errors. Can you connect using adb and search for exceptions during synchronization?
> > > I know, I've no idea why Joplin even has such logs, given the reason for the error is lost. I'll muck around to figure it out.
> 
> This log is useful when an error originates from the js side. In this case however this is coming from the native code, I think the library Joplin uses only reports a generic network request failed message

Does Joplin use ReactJS blegh? Most blocks of logs from random apps are out of order, but this bit I've determined the following tails `JOPLIN  : Set ignore TLS errors: true`:
`12-17 14:03:18.435 20267 20293 W System.err: java.lang.Exception: File does not exist
12-17 14:03:18.435 20267 20293 W System.err: 	at com.rnfs.RNFSManager.unlink(RNFSManager.java:650)
12-17 14:03:18.435 20267 20293 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
12-17 14:03:18.435 20267 20293 W System.err: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
12-17 14:03:18.435 20267 20293 W System.err: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
12-17 14:03:18.435 20267 20293 W System.err: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
12-17 14:03:18.435 20267 20293 W System.err: 	at android.os.Handler.handleCallback(Handler.java)
12-17 14:03:18.435 20267 20293 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java)
12-17 14:03:18.435 20267 20293 W System.err: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
12-17 14:03:18.435 20267 20293 W System.err: 	at android.os.Looper.loop(Looper.java)
12-17 14:03:18.435 20267 20293 W System.err: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
12-17 14:03:18.435 20267 20293 W System.err: 	at java.lang.Thread.run(Thread.java)`

**Comment by roman-r-m** [comment]
That seems unrelated, something to do with file system access.

**Comment by OdinVex** [comment]
> That seems unrelated, something to do with file system access.

By the logs, it only happens shortly after checking synchronization, but alright. Nothing else stands out at all.

**Comment by OdinVex** [comment]
By the way, the Linux version of Joplin won't work without “Ignore TLS certificate errors”, despite the CA being trusted by my OS (added to Linux certificate store). Need an option to trust OS certificate store.

**Comment by OdinVex** [comment]
It is unresolved.

**Comment by OdinVex** [comment]
It is unresolved.

**Comment by OdinVex** [comment]
It is unresolved.

**Comment by OdinVex** [comment]
It is unresolved.

**Comment by OdinVex** [comment]
Check out DAVx5, open-source, they include a switch to trust/distrust Android certificate store.

**Comment by OdinVex** [comment]
It is unresolved.

**Comment by OdinVex** [comment]
It is unresolved.

**Comment by andersonfreitas** [comment]
I have a custom CA and trusted on my Android. Enabling the “Ignore TLS certificate errors” works and synchronizes with a Joplin Server (with the flag unchecked it doesn't), however, it seems that the way images are downloaded uses a different connection scheme that ignores the “Ignore TLS certificate errors”, so no images are downloaded from notes (exception `java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`).

**Comment by OdinVex** [comment]
@andersonfreitas, That usually means the server hosting the images isn't sending the root/intermediate certificates with the certificate during connection. When a TLS connection is made, the entire 'chain' of certs (or a subset) is sent. Yours is probably just the end entity, bad practice. What version of Joplin are you using? What version of Android? Is it a cert added to the Android System Store?

**Comment by OdinVex** [comment]
It is unresolved.

**Comment by OdinVex** [comment]
It is unresolved.

**Comment by OdinVex** [comment]
It is unresolved.

**Comment by OdinVex** [comment]
It is unresolved.

**Comment by OdinVex** [comment]
It is unresolved. Starting to wonder how many issues Joplin really has if they're constantly automatically closed as suggested.

**Comment by OdinVex** [comment]
It is unresolved.

**Comment by OdinVex** [comment]
It is unresolved.

**Comment by OdinVex** [comment]
It is unresolved.

**Comment by gbakeman** [comment]
Adding on to hopefully see some movement on this, and fend off the aggressive bot (lol.) More detailed error messages would be nice, too.

**Comment by OdinVex** [comment]
> Adding on to hopefully see some movement on this, and fend off the aggressive bot (lol.) More detailed error messages would be nice, too.

No need for more detailed error messages, it's an issue regarding Joplin simply not using System-trusted certs or even the ability to trust thumbprints.

**Comment by gbakeman** [comment]
> No need for more detailed error messages, it's an issue regarding Joplin simply not using System-trusted certs or even the ability to trust thumbprints.

Right, and I don't mean to go too far offtopic, but I've just spent far too much time troubleshooting this problem before I even thought it could be a TLS issue. As I think the beginning of your report implies,

> Yet another “Network Request Failed” post.

This message is very common, and also quite unhelpful. But as someone else later said, it's a native library that generates the error so it sounds like the Joplin team has their hands tied on that subject.

Again, sorry for going offtopic - hope this issue specifically is fixed.

**Comment by OdinVex** [comment]
> This message is very common, and also quite unhelpful. But as someone else later said, it's a native library that generates the error so it sounds like the Joplin team has their hands tied on that subject.

Turning off TLS/SSL, it's fine. Using a LetsEncrypt cert or one from a common CA, it's fine. Use my own CA, not fine, because it doesn't trust the cert. I had the problem with the desktop version until I forcibly told it what folder to use for certs punching through Flatkrap's \*\*\*\*ty sandboxing. It's a cert store issue. Software should trust the system cert store. Joplin's hands may be tied, I'm just keeping this alive until fixed. A ton of these RADs for web-based “apps” all use the same moronic backends that don't follow standards for certs and only trust their own included certs. An example would be Firefox. This crappy behavior is Firefox's default, along with their completely-misguided walling on connection trust workarounds. You have to enable a config option to trust the system store. Baffling behavior. I can comprehend providing users an option to NOT trust the system store, but it should be trusted by default. Worst case? At least optional use of the system store, configurable by the user.

**Comment by bryab** [comment]
I just would like to add that I have the same problem.  It's funny because I only enabled SSL on my local web server to satisfy the requirements of the Jopin iOS app, which now requires that all connections be made over https.  I got iOS working with a trusted CA cert, but now Android doesn't work because the Joplin Android app doesn't respect the system's trusted certs.

**Comment by sv1sjp** [comment]
Hey, I noticed that this issue exists for many years and I want to ask why in the Android version of Joplin there is not an option to add "Custom TLS certificates" as it exists in Desktop versions of Joplin? 

On Android, I am getting this error with "Ignore TLS certificate errors" enabled:
Last Error: Error: uploadBlob PUT https://192.168.1.10/nextcloud/remote.php/webdav/joplin/.resource/..... Error: ReactNativeBlobUtil request Error java.lang.illegalStateException. Use of own trust manager but none definedjava.lang.illegalStateException: Use of own trust manager but none define"



I am getting this error only from android version of joplin, from my fedora it works perfectly

**Comment by OdinVex** [comment]
It is unresolved.

**Comment by personalizedrefrigerator** [comment]
[I'm adding this to my to-do list!](https://github.com/users/personalizedrefrigerator/projects/2/views/1?pane=issue&itemId=32016362)

(No promises that I'll be able to fix this any time soon, though!)

**Comment by OdinVex** [comment]
> [I'm adding this to my to-do list!](https://github.com/users/personalizedrefrigerator/projects/2/views/1?pane=issue&itemId=32016362)
> 
> (No promises that I'll be able to fix this any time soon, though!)

I think a fundamental library change is required. Something about an upstream library needing it.

**Comment by personalizedrefrigerator** [comment]
That's probably the case. However, it's also possible it's an issue with [network_security_config.xml](https://github.com/laurent22/joplin/blob/9f5924984cebf435396d04a37e2c3a0cee583a67/packages/app-mobile/android/app/src/main/res/xml/network_security_config.xml) ([documentation](https://developer.android.com/training/articles/security-config)).

**Comment by OdinVex** [comment]
Maybe...but I don't see it trusting the system store, though, unless this Joplin doesn't have “system”. The documented section on “Configure a custom CA” sounds promising, save for the fact that it needs it as a resource?  I don't do Android development, is this limited to deployment resources or can that reference a user-writable folder or, better, just trust the system store?

**Comment by personalizedrefrigerator** [comment]
Related:
- https://github.com/facebook/react-native/issues/20488
- https://github.com/laurent22/joplin/commit/7e9972d99ff92da4b45595acbfed89c8bcd5afb8
- #680

**Comment by OdinVex** [comment]
It is unresolved.

**Comment by Geroldin** [comment]
hi,
i'm having the same issue even with a valid certificate 
Mobile Phone: Samsung S21 5G (SM-G991B/DS) 
Android Version: 13 (Samsung One UI 5.1)
Joplin Android App Version: 2.12.3
Opera Browser 77.4.4095.74896
Samsung Internet 22.0.6.9
Joplin Server v2.13.1  

I've installed Joplin Server on Docker running on a Synology NAS. I'm currently using the Synology NAS Revers Proxy to publish the app.
Access via Joplin Desktop App v.2.12.18 (Ubuntu LTS 22.04) works just fine. Access from mobil browser (same device) works as well without issues and no certificate issues / warnings.
The setting "ignore tls certificate issues" is enables. I always end up with the error message: 'Trust anchor for certificate path not found' .

Please find below the sync Report log from the App and a screenshot from the certificate:
[syncReport-1696596233931.txt](https://github.com/laurent22/joplin/files/12831420/syncReport-1696596233931.txt)

![Screenshot from 2023-10-06 14-50-58](https://github.com/laurent22/joplin/assets/86980264/2f69fbc9-cb85-43b3-b6b4-d9b5148fdca5)
![Screenshot from 2023-10-06 15-04-46](https://github.com/laurent22/joplin/assets/86980264/c5179719-5a97-43ae-af2e-5cebf6f2e4e2)

**Comment by Geroldin** [comment]
Short addition: Network Connectivity check in configuration says everything is fine. Strange when I disable "ignore TLS certificate issus"  I get an `Network request failed` message. Saying I should check my user/pw and server address.

**Comment by Geroldin** [comment]
Might have found a fix. Seems like the intermediate Certificaze was unknown and therefor untrusted. When I installed it in the Android CA Store the connection started to work. So might just be a bad (cheap) wildcard certificate.
I even could disable "ignore tls certificate isaues".

**Comment by OdinVex** [comment]
This may have been fixed an update or two ago, not sure when. I can finally disable 'Ignore TLS Certificate Issues' as well. (My cert is directly below the CA in my chain, so there was no intermediate certificate issue, just a store trust issue. Seems fixed now, upstream library fixed maybe?)
