### ISSUE TITLE
Mime Type 

### ISSUE THREAD

**Issue by aricooperman** [laurent22/joplin#5874]
Using the API to create notes and adding content to 'body_html' field. See a bunch of messages in the log file about mime type handling when downloading images. Example:

`2021-12-17 16:23:16: "Cannot download image at https://notices.rei.com/pub/as?_ri_=X0Gzc2X%3DAQpglLjHJlYQGtrIPzdXSg6L3bcaczdX82XevAYoocpqg0zfceYDa09w6h1OzdolWzgnVXHkMX%3Dw&_ei_=EuFBWJqUWaLLkAGD46ZqJrW_ym9PZ_WWeMJIWfOFTzbdFS3iToXu0WrWUz56cbKiJ8lhAa89pLdTWYIjWRRINAPizRDdVCb01OYGMd1A-cNtwf_zMkyaor4SPZwfpAq9LlVcOYau1rtaKCI7ESZtmww2veg_QRCOzgCuiwY32C0a_jehC18hu2EW94e9RPMEINAhtyqzlb-NxJo9WLoIfmsRwVhE_2DngNrO9QyMGPWKtNGgJ0grq_AqRM.", "TypeError: mimeType.toLowerCase is not a function
TypeError: mimeType.toLowerCase is not a function
    at Object.toFileExtension (/tmp/.mount_JoplinB8vnxi/resources/app.asar/node_modules/@joplin/lib/mime-utils.js:23:23)
    at /tmp/.mount_JoplinB8vnxi/resources/app.asar/node_modules/@joplin/lib/services/rest/routes/notes.js:167:34
    at Generator.next (<anonymous>)
    at /tmp/.mount_JoplinB8vnxi/resources/app.asar/node_modules/@joplin/lib/services/rest/routes/notes.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/tmp/.mount_JoplinB8vnxi/resources/app.asar/node_modules/@joplin/lib/services/rest/routes/notes.js:4:12)
    at tryToGuessImageExtFromMimeType (/tmp/.mount_JoplinB8vnxi/resources/app.asar/node_modules/@joplin/lib/services/rest/routes/notes.js:163:12)
    at /tmp/.mount_JoplinB8vnxi/resources/app.asar/node_modules/@joplin/lib/services/rest/routes/notes.js:205:39
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_JoplinB8vnxi/resources/app.asar/node_modules/@joplin/lib/services/rest/routes/notes.js:5:58)"`

## Environment

Joplin version:  2.6.9
Platform:  Linux
OS specifics: Fedora 35

## Steps to reproduce

1. Attempt to import a note that has the example URL above

## Describe what you expected to happen
No TypeError

**Comment by laurent22** [comment]
Fixed in https://github.com/laurent22/joplin/commit/2f1047e3eb258bc40116f39f51342538baa457fb#diff-da552e455c73fcb1b59e2f97641790541b905496d1e0b27cc59566dfa7701d3fL29 and will be in next release.
