### ISSUE TITLE
Unable to verify the first certificate

### ISSUE THREAD

**Issue by feilix** [laurent22/joplin#5886]
## Environment

Joplin version: 2.6.9
Platform: Windows
OS specifics: Windows10 19043.1151

## Steps to reproduce

1. Click Help -> Check fro updates..., then wait a few seconds
2. Error occurs
![图片](https://user-images.githubusercontent.com/55008613/146724262-0e3a35c8-d55c-4a7f-9413-42df2b219f23.png)

## Describe what you expected to happen

1. Is here something wrong with my system or network? Or something I need to config? the log file is :
      ```
      2021-12-20 14:17:38: checkForUpdates: "Starting..."
      2021-12-20 14:17:38: checkForUpdates: "Checking with options {"includePreReleases":false}"
      2021-12-20 14:17:38: checkForUpdates: "FetchError: request to https://api.github.com/repos/laurent22/joplin/releases failed, reason: unable to verify the first certificate
      Code: UNABLE_TO_VERIFY_LEAF_SIGNATURE
      FetchError: request to https://api.github.com/repos/laurent22/joplin/releases failed, reason: unable to verify the first certificate
          at ClientRequest.<anonymous> (C:\Users\kkk\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\node_modules\node-fetch\index.js:133:11)
          at ClientRequest.emit (events.js:376:20)
          at TLSSocket.socketErrorListener (_http_client.js:475:9)
          at TLSSocket.emit (events.js:376:20)
          at emitErrorNT (internal/streams/destroy.js:106:8)
          at emitErrorCloseNT (internal/streams/destroy.js:74:3)
          at processTicksAndRejections (internal/process/task_queues.js:82:21)"
      2021-12-20 14:17:38: checkForUpdates: "Done."
      ```

2. The plugins search did not work, which presents:
  ![图片](https://user-images.githubusercontent.com/55008613/146725292-3885f0d9-186d-4d71-8884-a696e278c28f.png)
  
    the log file is: 
      ```
      2021-12-20 15:00:12: RepositoryApi: "findWorkingMirror: Using: https://raw.githubusercontent.com/joplin/plugins/master"
      2021-12-20 15:00:12: PluginState: "FetchError: request to https://raw.githubusercontent.com/joplin/plugins/master/manifests.json failed, reason: unable to verify the first certificate
      Code: UNABLE_TO_VERIFY_LEAF_SIGNATURE
      FetchError: request to https://raw.githubusercontent.com/joplin/plugins/master/manifests.json failed, reason: unable to verify the first certificate
          at ClientRequest.<anonymous> (C:\Users\kkk\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\node_modules\node-fetch\index.js:133:11)
          at ClientRequest.emit (events.js:376:20)
          at TLSSocket.socketErrorListener (_http_client.js:475:9)
          at TLSSocket.emit (events.js:376:20)
          at emitErrorNT (internal/streams/destroy.js:106:8)
          at emitErrorCloseNT (internal/streams/destroy.js:74:3)
          at processTicksAndRejections (internal/process/task_queues.js:82:21)"
      ```
3.  The Synchronize meets the same problem -> unable to verify the first certificate.

## Solution:
I have found the solution. Tools -> Options-> Synchronization -> WebDAV, then show advanced settings, check "IGnore TLS certificate errors".
![图片](https://user-images.githubusercontent.com/55008613/147050744-327799c5-9508-4e1b-bc4f-2c6da7e2143f.png)

May this option be better to move to the General column?

**Comment by feilix** [comment]
I have found the solution. Tools -> Options-> Synchronization -> WebDAV, then show advanced settings, check "IGnore TLS certificate errors".
![图片](https://user-images.githubusercontent.com/55008613/147050744-327799c5-9508-4e1b-bc4f-2c6da7e2143f.png)

So, I think this option will may be better to move to General column?

**Comment by graphit0** [comment]
Thanks for documenting the issue and providing the solution. Does it mean that the issue is no longer relevant and may be closed?

**Comment by feilix** [comment]
> Thanks for documenting the issue and providing the solution. Does it mean that the issue is no longer relevant and may be closed?

OK.

**Comment by skwde** [comment]
For others coming here that are note satisfied with this solution:

Add the path to the `rootCA.pem` under `Settings > Synchronization > Advanced Settings > Custom TLS certificates`

For details see https://discourse.joplinapp.org/t/synch-with-nextcloud-using-self-signed-certificate-failed/31482
