### ISSUE TITLE
Sync must fail, not succeed, due to sync timeout caused by external networking.

### ISSUE THREAD

**Issue by jtagcat** [laurent22/joplin#5937]
**READ https://github.com/laurent22/joplin/issues/5937#issuecomment-1003223795**

***

## Environment

Joplin version: 2.6.10
Platform: Fatpak
OS specifics: Fedora 34
Joplin Server 2.7.3

## Steps to reproduce

1. Open app
2. Press sync
3. No network interruptions, no nothing interruptions
4. It still syncs
5. For fewty minutes

Sometimes, rarely it does the half-a-second sync, I don't remember when I last saw it.

## Logfile
Cowardly refused to provide logfiles, as they include tons of data, including contents of notes. Please make a tool/mode to redact logs. You should not ask users for their data, especially in public, especially without them knowing.

Notes:
 - Using joplin cloud; used to use nextcloud, it is not present in GUI config, but it started off going to it.
 - I'm pretty sure that when it gets stuck on syncing, it doesn't actually sync notes. (even though it reports a sync complete) edit: changes like 5 syncs before, android client reports it is up to date
 - Cancelled at 00:44:05, it hangs. (It started syncing right after app open, using sync attempt no 2 for cleaner logs)
 - Button showed ready to sync. Started again at 01:35:13; 01:56:21
 - Server is UTC, client is UTC+2; 23:35:13; 23:56:21
 - Android and iOS clients can sync fine, always.
 - auto-sync has been turned off beforehand

edit: here is the sync run, keywords: `redacted\d+` `COLLAPSED`, `REDACTED`
```
2021-12-31 01:35:13: "CommandService::execute:", "synchronize", "[]"
2021-12-31 01:35:13: "Scheduling sync operation...", "0"
2021-12-31 01:35:13: "Preparing scheduled sync"
2021-12-31 01:35:13: "Starting scheduled sync"
2021-12-31 01:35:13: Synchronizer: "Sync: starting: Starting synchronisation to target 9... supportsAccurateTimestamp = true; supportsMultiPut = true [1640907313032]"
2021-12-31 01:35:13: Synchronizer: "Indexing resources..."
2021-12-31 01:35:13: "ResourceService::indexNoteResources: Start"
2021-12-31 01:35:13: "ResourceService::indexNoteResources: Completed"
2021-12-31 01:35:13: models/Folder: "updateFolderShareIds:", "{"shareUpdateCount":0,"unshareUpdateCount":0}"
2021-12-31 01:35:13: models/Folder: "updateNoteShareIds: notes to update:", "0"
2021-12-31 01:35:13: FileApi: "get info.json"
2021-12-31 01:37:13: JoplinServerApi: "curl -v -X POST -H "X-API-MIN-VERSION: 2.6.0" -H "Content-Type: application/json" -H "Content-Length: 134" --data '{"email":"user@domain.tld","password":"******"}' 'https://joplinserver/api/sessions'"
2021-12-31 01:37:13: JoplinServerApi: "Code:", "undefined"
2021-12-31 01:37:13: JoplinServerApi: "FetchError: network timeout at: https://joplinserver/api/sessions
FetchError: network timeout at: https://joplinserver/api/sessions
    at /app/joplin-desktop/resources/app/node_modules/@joplin/lib/node_modules/node-fetch/index.js:126:13"
2021-12-31 01:37:13: JoplinServerApi: "Could not acquire session:", "undefined", "
", "FetchError: network timeout at: https://joplinserver/api/sessions
FetchError: network timeout at: https://joplinserver/api/sessions
    at /app/joplin-desktop/resources/app/node_modules/@joplin/lib/node_modules/node-fetch/index.js:126:13"
2021-12-31 01:39:17: JoplinServerApi: "curl -v -X POST -H "X-API-MIN-VERSION: 2.6.0" -H "Content-Type: application/json" -H "Content-Length: 134" --data '{"email":"user@domain.tld","password":"******"}' 'https://joplinserver/api/sessions'"
2021-12-31 01:39:17: JoplinServerApi: "Code:", "undefined"
2021-12-31 01:39:17: JoplinServerApi: "FetchError: network timeout at: https://joplinserver/api/sessions
FetchError: network timeout at: https://joplinserver/api/sessions
    at /app/joplin-desktop/resources/app/node_modules/@joplin/lib/node_modules/node-fetch/index.js:126:13"
2021-12-31 01:39:17: JoplinServerApi: "Could not acquire session:", "undefined", "
", "FetchError: network timeout at: https://joplinserver/api/sessions
FetchError: network timeout at: https://joplinserver/api/sessions
    at /app/joplin-desktop/resources/app/node_modules/@joplin/lib/node_modules/node-fetch/index.js:126:13"
2021-12-31 01:41:18: PluginRunner: "Got message (3): joplin.commands.execute", "["openNote","redacted1"]"
2021-12-31 01:41:18: "CommandService::execute:", "openNote", "["redacted1"]"
2021-12-31 01:41:18: "Loading existing note", "redacted1"
2021-12-31 01:41:18: PluginRunner: "Got message (3): joplin.workspace.selectedNote", "[]"
2021-12-31 01:41:18: PluginRunner: "Got message (3): joplin.workspace.selectedNote", "[]"
2021-12-31 01:41:18: UserWebview: "Got message", "postMessageService.response", "{"message":{"responseId":"userWebview_16409076787460.016092467740865146","error":null}}"
2021-12-31 01:41:18: "Loaded note:", "REDACTED"
2021-12-31 01:41:18: App: "Refreshing notes:", "2", "redacted2"
2021-12-31 01:41:19: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted1","tags"],{"fields":["id","title"],"order_by":"title","order_dir":"ASC","page":1}]"
2021-12-31 01:41:19: PluginRunner: "Got message (3): joplin.workspace.selectedNote", "[]"
2021-12-31 01:41:19: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted3","tags"],{"fields":["id","title"],"order_by":"title","order_dir":"ASC","page":1}]"
2021-12-31 01:41:19: PluginRunner: "Got message (3): joplin.settings.globalValue", "["showCompletedTodos"]"
2021-12-31 01:41:19: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted1"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:19: PluginRunner: "Got message (3): joplin.settings.globalValue", "["editor.codeView"]"
2021-12-31 01:41:19: PluginRunner: "Got message (3): joplin.settings.globalValue", "["noteVisiblePanes"]"
2021-12-31 01:41:19: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted10"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:19: PluginRunner: "Got message (3): joplin.settings.globalValue", "["editor.codeView"]"
2021-12-31 01:41:19: PluginRunner: "Got message (3): joplin.settings.globalValue", "["noteVisiblePanes"]"
2021-12-31 01:41:19: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted9"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:20: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted8"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:20: "CommandService::execute:", "focusSearch", "[]"
2021-12-31 01:41:20: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted7"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:20: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted6"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:20: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted5"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:20: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted4"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:20: PluginRunner: "Got message (3): joplin.views.panels.setHtml", "<hidden>"
2021-12-31 01:41:21: UserWebview: "Got message", "setHtml", "COLLAPSED"
2021-12-31 01:41:22: "Garbage collecting alarms..."
2021-12-31 01:41:22: App: "Refreshing notes:", "7", "redacted11"
2021-12-31 01:41:23: RevisionService: "RevisionService::maintenance: Starting..."
2021-12-31 01:41:23: RevisionService: "RevisionService::maintenance: Service is enabled"
2021-12-31 01:41:23: PluginRunner: "Got message (3): joplin.workspace.selectedNote", "[]"
2021-12-31 01:41:23: PluginRunner: "Got message (3): joplin.workspace.selectedNote", "[]"
2021-12-31 01:41:23: PluginRunner: "Got message (3): joplin.workspace.selectedNote", "[]"
2021-12-31 01:41:23: "Loading existing note", "redacted9"
2021-12-31 01:41:23: PluginRunner: "Got message (3): joplin.settings.globalValue", "["showCompletedTodos"]"
2021-12-31 01:41:23: PluginRunner: "Got message (3): joplin.workspace.selectedNote", "[]"
2021-12-31 01:41:23: PluginRunner: "Got message (3): joplin.workspace.selectedNote", "[]"
2021-12-31 01:41:23: RevisionService: "RevisionService::collectRevisions: Created revisions for 0 notes"
2021-12-31 01:41:23: "Loaded note:", "REDACTED"
2021-12-31 01:41:24: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted1"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:24: JoplinServerApi: "curl -v -X POST -H "X-API-MIN-VERSION: 2.6.0" -H "Content-Type: application/json" -H "Content-Length: 134" --data '{"email":"user@domain.tld","password":"******"}' 'https://joplinserver/api/sessions'"
2021-12-31 01:41:24: JoplinServerApi: "Code:", "undefined"
2021-12-31 01:41:24: JoplinServerApi: "FetchError: network timeout at: https://joplinserver/api/sessions
FetchError: network timeout at: https://joplinserver/api/sessions
    at /app/joplin-desktop/resources/app/node_modules/@joplin/lib/node_modules/node-fetch/index.js:126:13"
2021-12-31 01:41:24: JoplinServerApi: "Could not acquire session:", "undefined", "
", "FetchError: network timeout at: https://joplinserver/api/sessions
FetchError: network timeout at: https://joplinserver/api/sessions
    at /app/joplin-desktop/resources/app/node_modules/@joplin/lib/node_modules/node-fetch/index.js:126:13"
2021-12-31 01:41:25: RevisionService: "RevisionService::maintenance: Done in 2176ms"
2021-12-31 01:41:25: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted9","tags"],{"fields":["id","title"],"order_by":"title","order_dir":"ASC","page":1}]"
2021-12-31 01:41:25: PluginRunner: "Got message (3): joplin.workspace.selectedNote", "[]"
2021-12-31 01:41:25: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted10"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:25: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted1","tags"],{"fields":["id","title"],"order_by":"title","order_dir":"ASC","page":1}]"
2021-12-31 01:41:25: PluginRunner: "Got message (3): joplin.settings.globalValue", "["showCompletedTodos"]"
2021-12-31 01:41:25: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted9"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:25: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted1"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:26: App: "Refreshing notes:", "7", "redacted11"
2021-12-31 01:41:26: PluginRunner: "Got message (3): joplin.settings.globalValue", "["editor.codeView"]"
2021-12-31 01:41:27: PluginRunner: "Got message (3): joplin.workspace.selectedNote", "[]"
2021-12-31 01:41:27: PluginRunner: "Got message (3): joplin.workspace.selectedNote", "[]"
2021-12-31 01:41:27: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted8"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:27: PluginRunner: "Got message (3): joplin.settings.globalValue", "["noteVisiblePanes"]"
2021-12-31 01:41:27: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted10"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:27: PluginRunner: "Got message (3): joplin.workspace.selectedNote", "[]"
2021-12-31 01:41:27: "Loading existing note", "redacted9"
2021-12-31 01:41:27: PluginRunner: "Got message (3): joplin.settings.globalValue", "["editor.codeView"]"
2021-12-31 01:41:27: PluginRunner: "Got message (3): joplin.settings.globalValue", "["showCompletedTodos"]"
2021-12-31 01:41:27: PluginRunner: "Got message (3): joplin.workspace.selectedNote", "[]"
2021-12-31 01:41:27: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted7"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:27: PluginRunner: "Got message (3): joplin.workspace.selectedNote", "[]"
2021-12-31 01:41:27: "Loaded note:", "REDACTED"
2021-12-31 01:41:28: PluginRunner: "Got message (3): joplin.settings.globalValue", "["noteVisiblePanes"]"
2021-12-31 01:41:28: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted9"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:28: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted1"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:29: PluginRunner: "Got message (3): joplin.workspace.selectedNote", "[]"
2021-12-31 01:41:29: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted6"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:29: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted9","tags"],{"fields":["id","title"],"order_by":"title","order_dir":"ASC","page":1}]"
2021-12-31 01:41:29: App: "Refreshing notes:", "2", "redacted12"
2021-12-31 01:41:29: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted8"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:29: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted10"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:29: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted5"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:29: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted9","tags"],{"fields":["id","title"],"order_by":"title","order_dir":"ASC","page":1}]"
2021-12-31 01:41:29: PluginRunner: "Got message (3): joplin.settings.globalValue", "["showCompletedTodos"]"
2021-12-31 01:41:29: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted7"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:29: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted9"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:29: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted1"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:29: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted4"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:29: PluginRunner: "Got message (3): joplin.settings.globalValue", "["editor.codeView"]"
2021-12-31 01:41:29: models/Setting: "Saving settings..."
2021-12-31 01:41:29: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted6"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:29: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted8"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:30: PluginRunner: "Got message (3): joplin.settings.globalValue", "["noteVisiblePanes"]"
2021-12-31 01:41:30: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted10"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:30: PluginRunner: "Got message (3): joplin.views.panels.setHtml", "<hidden>"
2021-12-31 01:41:30: UserWebview: "Got message", "setHtml", "COLLAPSED"
2021-12-31 01:41:30: PluginRunner: "Got message (3): joplin.settings.globalValue", "["editor.codeView"]"
2021-12-31 01:41:30: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted5"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:30: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted7"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:30: PluginRunner: "Got message (3): joplin.settings.globalValue", "["noteVisiblePanes"]"
2021-12-31 01:41:31: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted9"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:31: PluginRunner: "Got message (3): joplin.commands.execute", "["openNote","redacted1"]"
2021-12-31 01:41:31: "CommandService::execute:", "openNote", "["redacted1"]"
2021-12-31 01:41:31: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted4"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:31: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted6"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:31: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted8"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:32: "Loading existing note", "redacted1"
2021-12-31 01:41:32: PluginRunner: "Got message (3): joplin.views.panels.setHtml", "<hidden>"
2021-12-31 01:41:32: UserWebview: "Got message", "setHtml", "COLLAPSED"
2021-12-31 01:41:32: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted5"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:32: PluginRunner: "Got message (3): joplin.workspace.selectedNote", "[]"
2021-12-31 01:41:32: PluginRunner: "Got message (3): joplin.workspace.selectedNote", "[]"
2021-12-31 01:41:32: UserWebview: "Got message", "postMessageService.response", "{"message":{"responseId":"userWebview_16409076907030.85397686638139","error":null}}"
2021-12-31 01:41:32: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted7"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:33: models/Setting: "Saving settings..."
2021-12-31 01:41:33: "Loaded note:", "REDACTED"
2021-12-31 01:41:33: App: "Refreshing notes:", "2", "redacted2"
2021-12-31 01:41:33: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted4"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:33: PluginRunner: "Got message (3): joplin.workspace.selectedNote", "[]"
2021-12-31 01:41:33: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted1","tags"],{"fields":["id","title"],"order_by":"title","order_dir":"ASC","page":1}]"
2021-12-31 01:41:33: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted6"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:33: PluginRunner: "Got message (3): joplin.views.panels.setHtml", "<hidden>"
2021-12-31 01:41:34: UserWebview: "Got message", "setHtml", "COLLAPSED"
2021-12-31 01:41:35: PluginRunner: "Got message (3): joplin.settings.globalValue", "["showCompletedTodos"]"
2021-12-31 01:41:35: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted9","tags"],{"fields":["id","title"],"order_by":"title","order_dir":"ASC","page":1}]"
2021-12-31 01:41:35: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted5"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:35: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted1"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:35: PluginRunner: "Got message (3): joplin.settings.globalValue", "["editor.codeView"]"
2021-12-31 01:41:35: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted4"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:35: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted10"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:35: PluginRunner: "Got message (3): joplin.settings.globalValue", "["noteVisiblePanes"]"
2021-12-31 01:41:35: PluginRunner: "Got message (3): joplin.settings.globalValue", "["editor.codeView"]"
2021-12-31 01:41:35: PluginRunner: "Got message (3): joplin.views.panels.setHtml", "<hidden>"
2021-12-31 01:41:35: PluginRunner: "Got message (3): joplin.settings.globalValue", "["noteVisiblePanes"]"
2021-12-31 01:41:35: UserWebview: "Got message", "setHtml", "COLLAPSED"
2021-12-31 01:41:35: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted9"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:36: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted8"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:36: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted7"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:37: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted6"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:37: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted5"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:37: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted4"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:41:37: PluginRunner: "Got message (3): joplin.views.panels.setHtml", "<hidden>"
2021-12-31 01:41:37: UserWebview: "Got message", "setHtml", "COLLAPSED"
2021-12-31 01:41:38: models/Setting: "Settings have been saved."
2021-12-31 01:41:39: models/Setting: "Settings have been saved."
2021-12-31 01:43:35: JoplinServerApi: "curl -v -X POST -H "X-API-MIN-VERSION: 2.6.0" -H "Content-Type: application/json" -H "Content-Length: 134" --data '{"email":"user@domain.tld","password":"******"}' 'https://joplinserver/api/sessions'"
2021-12-31 01:43:35: JoplinServerApi: "Code:", "undefined"
2021-12-31 01:43:35: JoplinServerApi: "FetchError: network timeout at: https://joplinserver/api/sessions
FetchError: network timeout at: https://joplinserver/api/sessions
    at /app/joplin-desktop/resources/app/node_modules/@joplin/lib/node_modules/node-fetch/index.js:126:13"
2021-12-31 01:43:35: JoplinServerApi: "Could not acquire session:", "undefined", "
", "FetchError: network timeout at: https://joplinserver/api/sessions
FetchError: network timeout at: https://joplinserver/api/sessions
    at /app/joplin-desktop/resources/app/node_modules/@joplin/lib/node_modules/node-fetch/index.js:126:13"
2021-12-31 01:43:35: Synchronizer: "FetchError: network timeout at: https://joplinserver/api/sessions
FetchError: network timeout at: https://joplinserver/api/sessions
    at /app/joplin-desktop/resources/app/node_modules/@joplin/lib/node_modules/node-fetch/index.js:126:13"
2021-12-31 01:51:23: RevisionService: "RevisionService::maintenance: Starting..."
2021-12-31 01:51:23: RevisionService: "RevisionService::maintenance: Service is enabled"
2021-12-31 01:51:23: RevisionService: "RevisionService::collectRevisions: Created revisions for 0 notes"
2021-12-31 01:51:23: RevisionService: "RevisionService::maintenance: Done in 116ms"
2021-12-31 01:56:20: JoplinServerApi: "curl -v -X POST -H "X-API-MIN-VERSION: 2.6.0" -H "Content-Type: application/json" -H "Content-Length: 134" --data '{"email":"user@domain.tld","password":"******"}' 'https://joplinserver/api/sessions'"
2021-12-31 01:56:20: JoplinServerApi: "Code:", "undefined"
2021-12-31 01:56:20: JoplinServerApi: "FetchError: network timeout at: https://joplinserver/api/sessions
FetchError: network timeout at: https://joplinserver/api/sessions
    at /app/joplin-desktop/resources/app/node_modules/@joplin/lib/node_modules/node-fetch/index.js:126:13"
2021-12-31 01:56:20: JoplinServerApi: "Could not acquire session:", "undefined", "
", "FetchError: network timeout at: https://joplinserver/api/sessions
FetchError: network timeout at: https://joplinserver/api/sessions
    at /app/joplin-desktop/resources/app/node_modules/@joplin/lib/node_modules/node-fetch/index.js:126:13"
2021-12-31 01:56:20: ShareService: "Failed to run maintenance:", "FetchError: network timeout at: https://joplinserver/api/sessions
FetchError: network timeout at: https://joplinserver/api/sessions
    at /app/joplin-desktop/resources/app/node_modules/@joplin/lib/node_modules/node-fetch/index.js:126:13"
2021-12-31 01:56:20: Synchronizer: "Sync: finished: Synchronisation finished [1640907313032]"
2021-12-31 01:56:20: Synchronizer: "Operations completed: "
2021-12-31 01:56:20: Synchronizer: "Total folders: 15"
2021-12-31 01:56:20: Synchronizer: "Total notes: 209"
2021-12-31 01:56:20: Synchronizer: "Total resources: 225"
2021-12-31 01:56:20: "Recurrent sync is disabled"
2021-12-31 01:56:20: PluginRunner: "Got message (3): joplin.workspace.selectedNote", "[]"
2021-12-31 01:56:20: PluginRunner: "Got message (3): joplin.settings.globalValue", "["showCompletedTodos"]"
2021-12-31 01:56:20: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted1"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:56:20: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted10"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:56:20: "Sync has finished and note has never been changed - reloading it"
2021-12-31 01:56:20: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted9"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:56:20: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted8"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:56:20: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted7"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:56:20: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted6"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:56:20: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted5"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:56:20: PluginRunner: "Got message (3): joplin.data.get", "[["notes","redacted4"],{"fields":["id","title","is_todo","todo_completed"]}]"
2021-12-31 01:56:20: PluginRunner: "Got message (3): joplin.views.panels.setHtml", "<hidden>"
2021-12-31 01:56:21: "DecryptionWorker: starting decryption..."
2021-12-31 01:56:21: "DecryptionWorker: completed decryption."
```

Server:
```
2021-12-30 22:30:00: TaskService: Completed #3 (Process oversized accounts) in 27ms
2021-12-30 22:39:40: App: GET / (302) (2ms)
2021-12-30 22:39:40: App: GET /home (200) (8ms)
2021-12-30 22:39:40: App: GET /css/fontawesome/css/all.min.css (200) (9ms)
2021-12-30 22:39:40: App: GET /css/main.css (200) (12ms)
2021-12-30 22:39:40: App: GET /css/bulma.min.css (200) (7ms)
2021-12-30 22:39:40: App: GET /js/jquery.min.js (200) (4ms)
2021-12-30 22:39:40: App: GET /css/index/home.css (200) (3ms)
2021-12-30 22:39:40: App: GET /js/main.js (200) (2ms)
2021-12-30 22:39:40: App: GET /images/Logo.png (200) (2ms)
2021-12-30 22:39:40: App: GET /css/fontawesome/webfonts/fa-solid-900.woff2 (200) (1ms)
2021-12-30 22:39:41: [error] App: 404: GET /favicon.ico: dKUPJLXHDPHks6w0UoYDy4AXoYkZwzcM: Path not found: favicon.ico
2021-12-30 22:39:41: App: GET /favicon.ico (404) (2ms)
2021-12-30 22:48:22: [error] App: 404: GET /robots.txt: 138.246.253.24: Path not found: robots.txt
2021-12-30 22:48:22: App: GET /robots.txt (404) (4ms)
2021-12-30 23:00:00: TaskService: Running #2 (Update total sizes) (scheduled)...
2021-12-30 23:00:01: TaskService: Completed #2 (Update total sizes) in 78ms
2021-12-30 23:45:51: [error] App: 400: GET /api/sessions: dKUPJLXHDPHks6w0UoYDy4AXoYkZwzcM: Not allowed: GET api/sessions
2021-12-30 23:45:51: App: GET /api/sessions (400) (3ms)
2021-12-31 00:00:00: TaskService: Running #1 (Delete expired tokens) (scheduled)...
2021-12-31 00:00:00: TaskService: Running #8 (Process user deletions) (scheduled)...
2021-12-31 00:00:00: TaskService: Running #2 (Update total sizes) (scheduled)...
2021-12-31 00:00:00: TaskService: Completed #1 (Delete expired tokens) in 58ms
2021-12-31 00:00:00: TaskService: Completed #8 (Process user deletions) in 57ms
2021-12-31 00:00:00: TaskService: Completed #2 (Update total sizes) in 86ms
```

**Comment by jtagcat** [comment]
Search for `network timeout at` returned #5300 #164 (oh no, that's a low number)

I normally run with Tailscale and OpenVPN; the latter seems to be at fault here. Uncertain, and needs more testing. In any case, this needs a better failure mode / warning.

**Comment by jtagcat** [comment]
It differs from the mentioned issues that in this case, it can never reach the server through the connection the OS provided, the host as a whole being a problem, not Joplin.

First, Joplin should fail, not indicate that a sync run had been completed; second, it'd be a nice to have it warn that something is wrong.

**Comment by jtagcat** [comment]
stop abusing my notifications

**Comment by jtagcat** [comment]
i really do need to write that antistale bot

**Comment by jtagcat** [comment]
a

**Comment by jtagcat** [comment]
i give up
