### ISSUE TITLE
Error: Cannot retrieve the network time from pool.ntp.org:123: Timeout waiting for NTP response.

### ISSUE THREAD

**Issue by gthbusrr** [laurent22/joplin#5973]
## Environment

Joplin Server Version: `@joplin/server@2.7.3`
Running in **Docker Container** on **Synology DS918+**

## Steps to reproduce
Whenever I start the container with `docker-compose up -d`, it shows an error of `Error: Cannot retrieve the network time from pool.ntp.org:123: Timeout waiting for NTP response.` and restart itself. I've tried `docker-compose down` and prune all _containers_, _images_ and _volumes_. When I run `nslookup pool.ntp.org`, it returns the correct IP address with no issue.

Another related issue found on [Reddit](https://www.reddit.com/r/synology/comments/rgoavu/network_time_issue_causing_joplin_server_error/)

## Describe what you expected to happen

To start server as intended.

## Logfile

```
> @joplin/server@2.7.3 start
> node dist/app.js

2022-01-07 19:34:56: App: Starting server v2.7.3 (prod) on port 22300 and PID 20...
Error: Cannot retrieve the network time from pool.ntp.org:123: Timeout waiting for NTP response.
    at Timeout._onTimeout (/home/joplin/packages/lib/vendor/ntp-client.js:79:22)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
npm notice 
npm notice New minor version of npm available! 8.1.2 -> 8.3.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.3.0>
npm notice Run `npm install -g npm@8.3.0` to update!
npm notice 

> @joplin/server@2.7.3 start
> node dist/app.js

2022-01-07 19:35:43: App: Starting server v2.7.3 (prod) on port 22300 and PID 21...
Error: Cannot retrieve the network time from pool.ntp.org:123: Timeout waiting for NTP response.
    at Timeout._onTimeout (/home/joplin/packages/lib/vendor/ntp-client.js:79:22)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

> @joplin/server@2.7.3 start
> node dist/app.js

2022-01-07 19:36:30: App: Starting server v2.7.3 (prod) on port 22300 and PID 22...
Error: Cannot retrieve the network time from pool.ntp.org:123: Timeout waiting for NTP response.
    at Timeout._onTimeout (/home/joplin/packages/lib/vendor/ntp-client.js:79:22)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

> @joplin/server@2.7.3 start
> node dist/app.js

2022-01-07 19:37:17: App: Starting server v2.7.3 (prod) on port 22300 and PID 20...
Error: Cannot retrieve the network time from pool.ntp.org:123: Timeout waiting for NTP response.
    at Timeout._onTimeout (/home/joplin/packages/lib/vendor/ntp-client.js:79:22)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

> @joplin/server@2.7.3 start
> node dist/app.js

2022-01-07 19:38:05: App: Starting server v2.7.3 (prod) on port 22300 and PID 19...
Error: Cannot retrieve the network time from pool.ntp.org:123: Timeout waiting for NTP response.
    at Timeout._onTimeout (/home/joplin/packages/lib/vendor/ntp-client.js:79:22)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

> @joplin/server@2.7.3 start
> node dist/app.js

2022-01-07 19:38:51: App: Starting server v2.7.3 (prod) on port 22300 and PID 19...
Error: Cannot retrieve the network time from pool.ntp.org:123: Timeout waiting for NTP response.
    at Timeout._onTimeout (/home/joplin/packages/lib/vendor/ntp-client.js:79:22)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

> @joplin/server@2.7.3 start
> node dist/app.js

2022-01-07 19:39:38: App: Starting server v2.7.3 (prod) on port 22300 and PID 20...
Error: Cannot retrieve the network time from pool.ntp.org:123: Timeout waiting for NTP response.
    at Timeout._onTimeout (/home/joplin/packages/lib/vendor/ntp-client.js:79:22)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

> @joplin/server@2.7.3 start
> node dist/app.js

2022-01-07 19:40:29: App: Starting server v2.7.3 (prod) on port 22300 and PID 20...
Error: Cannot retrieve the network time from pool.ntp.org:123: Timeout waiting for NTP response.
    at Timeout._onTimeout (/home/joplin/packages/lib/vendor/ntp-client.js:79:22)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

## Docker Compose File
```
version: '3.3'

services:
    joplin-db:
        image: postgres:13.1
        container_name: joplin-db
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=*****
            - POSTGRES_USER=*****
            - POSTGRES_DB=*****
    joplin:
        image: joplin/server:latest
        container_name: joplin
        depends_on:
            - joplin-db
        restart: unless-stopped
        ports:
            - '*****:22300'
        environment:
            - APP_PORT=22300
            - APP_BASE_URL=*****
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=*****
            - POSTGRES_DATABASE=*****
            - POSTGRES_USER=*****
            - POSTGRES_PORT=*****
            - POSTGRES_HOST=joplin-db

```

**Comment by laurent22** [comment]
The server needs to access that ntp domain - maybe that needs to be allowed on the firewall?

**Comment by gthbusrr** [comment]
I don't think it's blocked. `ntpdate -u pool.ntp.org` returns `* Jan **:**:** ntpdate[****]: adjust time server **.**.**.** offset *.** sec`, so it's working on my machine. Can the server startup skip time check? Thanks 👍

**Comment by laurent22** [comment]
You can set MAX_TIME_DRIFT to 0

**Comment by gthbusrr** [comment]
Hi @laurent22 , Thank you very much~~~ setting `MAX_TIME_DRIFT` to 0 worked. I also added `/etc/localtime:/etc/localtime:ro` to `volumes` attribute to sync time between host and container. Thanks.

**Comment by Waldorf3** [comment]
Why do you even bother trying to set the time in a docker-container? 

It will always depend on the time in the host being set correct.

**Comment by HubKing** [comment]
I also had the same problem and set the max drift thing. Firewall was disabled, so I am not sure why this is happening. Isn't this a bug?

**Comment by laurent22** [comment]
It's not a bug, it just gives you the information - the time drift, which you should aim to fix as it can cause subtle problems with sync. If for whatever reason it's not possible to fix, due to firewall, slow network or other issues, you can just disable the check.

**Comment by leder11011** [comment]
> 

Can you please elaborate on this solution?

**Comment by leder11011** [comment]
ntp timestamp is one hour early, please investigate:
```
2022-11-01 05:19:24: App: NTP time offset: 624ms
```

**Comment by jquiros2** [comment]
Same here.  If someone has it down pat we could propose adding it to the docs.
Could someone show how they expoed port 123... I tried with --expose and with -p 123:123/udp but nada.

Have gotten away with this hack for a year:

docker run --net=host --add-host=host.docker.internal:127.0.0.1 --env-file /home/jquiros/joplin/.env -p 22300:22300 -p 123:123/udp joplin/server:latest &
sleep 4
docker exec -u 0 -it `docker ps | grep joplin | awk {'print $1'}` perl -pi -e 's/pool.ntp.org/time.nist.gov/g' /home/joplin/packages/lib/vendor/ntp-client.js
#this just to see the file was edited: docker exec -u 0 -it `docker ps | grep joplin | awk {'print $1'}` cat /home/joplin/packages/lib/vendor/ntp-client.js | grep nist

**Comment by NeiBaf79** [comment]
> Hi @laurent22 , Thank you very much~~~ setting `MAX_TIME_DRIFT` to 0 worked. I also added `/etc/localtime:/etc/localtime:ro` to `volumes` attribute to sync time between host and container. Thanks.

Hi Laurent,
How did you set MAX_TIME_DRIFT to 0 ? I have the same error but i don't know how to set this value.
Thank you

**Comment by violet4** [comment]
@NeiBaf79 log into the docker container shell, then edit the `MAX_TIME_DRIFT to 0` in `/home/joplin/packages/server/dist/env.js`

i went through a big roundabout way to get `/home/joplin/packages/server` folder turned into a local volume so i could edit that file, because it was nearly impossible to edit anything in the bare-bones container.
