### ISSUE TITLE
ERR_INVALID_URL web ui

### ISSUE THREAD

**Issue by dan3805** [laurent22/joplin#6008]
I have a curious problem, the synchronization of the applications works with the default password, but the web interface tells me `` invalid url ''
![image](https://user-images.githubusercontent.com/35934387/149033472-68a15e98-4d82-49bc-9110-22be064dc5cf.png)

here is what I have in the log

`2022-01-11 22:42:50: [error] App: Middleware error on /login: TypeError: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at acceptOrigin (/home/joplin/packages/server/src/app.ts:121:21)
    at Object.origin (/home/joplin/packages/server/src/app.ts:188:8)
    at cors (/home/joplin/packages/server/node_modules/@koa/cors/index.js:60:24)
    at dispatch (/home/joplin/packages/server/node_modules/koa-compose/index.js:42:32)
    at /home/joplin/packages/server/src/app.ts:180:10
    at Generator.next (<anonymous>)
    at /home/joplin/packages/server/dist/app.js:8:71 {
  input: 'null',
  code: 'ERR_INVALID_URL'
}`

but app connection is working 
![image](https://user-images.githubusercontent.com/35934387/149033650-e65eb3cd-11e5-4401-814e-1a1cef051ea7.png)

yml here : https://github.com/dockserver/dockserver/blob/master/apps/selfhosted/joplin-server.yml

**Comment by HobbledGrubs** [comment]
I didn't manage to get this to work on Apache but it worked with a simple Nginx config.  A bit annoying but I didn't have time to play with Apache further.  I use Apache to proxy tons of stuff so it was a little surprising.

**Comment by fbonalair** [comment]
I have the same screen when I am trying to login, I have a HTTP 500 with this HTTP page, nothing special in logs:
```
> @joplin/server@2.5.1 start
> node dist/app.js

2022-03-20 21:29:58: App: Starting server v2.5.1 (prod) on port 22300 and PID 20...
2022-03-20 21:29:58: App: Running in Docker: true
2022-03-20 21:29:58: App: Public base URL: https://note.example.com:443
2022-03-20 21:29:58: App: API base URL: https://note.example.com:443
2022-03-20 21:29:58: App: User content base URL: https://note.example.com:443
2022-03-20 21:29:58: App: Log dir: /home/joplin/packages/server/logs
2022-03-20 21:29:58: App: DB Config: {
  client: 'pg',
  name: 'joplin',
  slowQueryLogEnabled: false,
  slowQueryLogMinDuration: 10000,
  user: 'joplin',
  password: '********',
  port: 5432,
  host: 'postgresql'
}
2022-03-20 21:29:58: App: Trying to connect to database...
2022-03-20 21:29:58: App: Connection check: {
  latestMigration: { name: '20190913171451_create.js' },
  isCreated: true,
  error: null
}
2022-03-20 21:29:59: App: Migrating database...
2022-03-20 21:29:59: App: Starting services...
2022-03-20 21:29:59: ShareService: Starting maintenance...
2022-03-20 21:29:59: EmailService: Service will be disabled because mailer config is not set or is explicitly disabled
2022-03-20 21:29:59: TaskService: Scheduling task #1 (Delete expired tokens): 0 */6 * * *
2022-03-20 21:29:59: TaskService: Scheduling task #2 (Update total sizes): 0 * * * *
2022-03-20 21:29:59: TaskService: Scheduling task #3 (Process oversized accounts): 0 14 * * *
2022-03-20 21:29:59: App: Call this for testing: `curl https://note.example.com:443/api/ping`
2022-03-20 21:29:59: ShareService: Maintenance completed in 46ms
2022-03-20 21:30:02: App: GET /login (29ms)
2022-03-20 21:30:02: App: GET /css/fontawesome/css/all.min.css (9ms)
2022-03-20 21:30:02: App: GET /js/jquery.min.js (8ms)
2022-03-20 21:30:02: App: GET /css/main.css (18ms)
2022-03-20 21:30:02: App: GET /css/bulma.min.css (10ms)
2022-03-20 21:30:02: App: GET /js/main.js (13ms)
2022-03-20 21:30:02: App: GET /images/Logo.png (5ms)

```
For my setup, I am on Kubernetes, using k3s. Traefik is used as reverse proxy to handle SSL termination and direct traffic from my subdomain to the container joplin/server:2. I am using PostgreSQL as database.
My environment values for the app are:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: joplin-env-values
data:
  APP_BASE_URL: "https://note.example.com:443"
  APP_PORT: "443"
  DB_CLIENT: "pg"
  POSTGRES_HOST: "postgresql"
  POSTGRES_PORT: "5432"
```
Though I managed to login and change the default admin using kubectl port-forward and APP_BASE_URL as `http://localhost`.
PS: I have sanitized the domain to note.example.com

**Comment by fbonalair** [comment]
Anyone or anything on this issue?

**Comment by Z0pyrus** [comment]
Same Issue.

**Comment by Buri** [comment]
I managed to work around this issue by 
```apache
RequestHeader set Origin "https://<server name>" early
```

Hopefully this helps somebody

**Comment by Borega** [comment]
got the same issue and cant rly make sense of @Buri comment. Can someone explain? Does someone have an Idea what to do? Error is the same as OP

**Comment by hardwareadictos** [comment]
Same issue here on a freshly installed Docker server

**Comment by hardwareadictos** [comment]
Can you give more info about this please?

> I managed to work around this issue by
> 
> ```apache-config
> RequestHeader set Origin "https://<server name>" early
> ```
> 
> Hopefully this helps somebody

**Comment by Buri** [comment]
This is my vhost config:
```apache2
<IfModule mod_ssl.c>
    <VirtualHost *:443>
        ServerName joplin.example.com
        ProxyPass / http://joplin.docker.example.com:22300/ retry=10 Keepalive=On
        ProxyPassReverse / http://joplin.docker.example.com:22300/
        SSLEngine on
        ProxyRequests Off
        ProxyPreserveHost On
        ProxyVia Full
        RequestHeader set Origin "https://joplin.example.com" early
    </VirtualHost>
</IfModule>
```

**Comment by atb00ker** [comment]
For people who land on this page in the future,

My nginx configuration added the header:

```
add_header Referrer-Policy                   "no-referrer"       always;
```

which was causing problem for me,

Adding this in the server block fixed it.
```
add_header Referrer-Policy "strict-origin-when-cross-origin" always;
```
