### ISSUE TITLE
Decryption of attachments not working in some cases

### ISSUE THREAD

**Issue by nbartkowiak** [laurent22/joplin#6139]
In some (rare) cases attachments can not be decrypted (UI-Message: "_some items can not be decrypted_").
The behaviour was already described in #4403 and #4472, but both were closed due to inactivity - thus not fixed.
I first try to delete the affected `.crypted`-files and do a following sync, but that did not solve the problem with these files.
Only if I delete them manually in `~/.config/joplin-desktop/resources` and get them from another device to store them again in the resources folder, I can fix that certain problem.
A valuable information is, that the affected attachments are synced without problem on other devices (another linux notebook as well as my android device - but with other joplin versions running). So the sync source should be fine.

## Environment

Joplin version: 2.6.10
Platform: Linux
OS specifics: Ubuntu 20.04.3 LTS

## Steps to reproduce
Currently I have no idea how to reproduce that issue with new corrupt files. When a file is corrupt, all attempts of decryption (also with a leading sync) fail with the error message that follows.

## Describe what you expected to happen
The application should try to compare and sync corrupt files again to decrypt them successfully.

## Logfile
`
2022-02-10 10:17:23: "DecryptionWorker: starting decryption..."
2022-02-10 10:17:23: "DecryptionWorker: error for: a7cd30fb42504f2e9fd26fe9ccc1ce22 (resources)", "Error: json decode: this isn't json!
Error: json decode: this isn't json!
    at EncryptionService.<anonymous> (/tmp/.mount_JoplinYS1QRR/resources/app.asar/node_modules/@joplin/lib/services/e2ee/EncryptionService.js:
387:23)
    at Generator.next (<anonymous>)
    at /tmp/.mount_JoplinYS1QRR/resources/app.asar/node_modules/@joplin/lib/services/e2ee/EncryptionService.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/tmp/.mount_JoplinYS1QRR/resources/app.asar/node_modules/@joplin/lib/services/e2ee/EncryptionService.js:4:12)
    at EncryptionService.decrypt (/tmp/.mount_JoplinYS1QRR/resources/app.asar/node_modules/@joplin/lib/services/e2ee/EncryptionService.js:368:
16)
    at EncryptionService.<anonymous> (/tmp/.mount_JoplinYS1QRR/resources/app.asar/node_modules/@joplin/lib/services/e2ee/EncryptionService.js:
442:46)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_JoplinYS1QRR/resources/app.asar/node_modules/@joplin/lib/services/e2ee/EncryptionService.js:5:58)", "{"id":"a7cd
30fb42504f2e9fd26fe9ccc1ce22","title":"1-6.png","mime":"image/png","filename":"","created_time":1644093638585,"updated_time":1644093638585,"us
er_created_time":1644093638585,"user_updated_time":1644093638585,"file_extension":"png","encryption_cipher_text":"","encryption_applied":0,"en
cryption_blob_encrypted":1,"size":314240,"is_shared":0,"share_id":"","master_key_id":"","type_":4}"
2022-02-10 10:17:23: "DecryptionWorker: error for: 145d480c28ba4292b64fb54efbb8bf3f (resources)", "Error: json decode: this isn't json!
Error: json decode: this isn't json!
    at EncryptionService.<anonymous> (/tmp/.mount_JoplinYS1QRR/resources/app.asar/node_modules/@joplin/lib/services/e2ee/EncryptionService.js:387:23)
    at Generator.next (<anonymous>)
    at /tmp/.mount_JoplinYS1QRR/resources/app.asar/node_modules/@joplin/lib/services/e2ee/EncryptionService.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/tmp/.mount_JoplinYS1QRR/resources/app.asar/node_modules/@joplin/lib/services/e2ee/EncryptionService.js:4:12)
    at EncryptionService.decrypt (/tmp/.mount_JoplinYS1QRR/resources/app.asar/node_modules/@joplin/lib/services/e2ee/EncryptionService.js:368:16)
    at EncryptionService.<anonymous> (/tmp/.mount_JoplinYS1QRR/resources/app.asar/node_modules/@joplin/lib/services/e2ee/EncryptionService.js:442:46)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_JoplinYS1QRR/resources/app.asar/node_modules/@joplin/lib/services/e2ee/EncryptionService.js:5:58)", "{"id":"145d480c28ba4292b64fb54efbb8bf3f","title":"print.PDF","mime":"application/pdf","filename":"","created_time":1644186724090,"updated_time":1644186724090,"user_created_time":1644186724090,"user_updated_time":1644186724090,"file_extension":"PDF","encryption_cipher_text":"","encryption_applied":0,"encryption_blob_encrypted":1,"size":621876,"is_shared":0,"share_id":"","master_key_id":"","type_":4}"
2022-02-10 10:17:23: "DecryptionWorker: completed decryption."
`

**Comment by acidbourbon** [comment]
I have the same problem. Different devices (all linux PCs) sync and decrypt most of the files correctly. But each picks random files to fail at decrypting (and keep failing).

**Comment by ScaredyCat** [comment]
This is still an issue. Suffering the same p[roblems as others, random "Some items cannot be decrypted."  with no indications as to the reason or cause.

Unfortunately this makes Joplin unreliable. 

Seems that every time this is reported the issue gets closed due to inactivity.

**Comment by m10d** [comment]
Still an issue.  I guess I'll open ANOTHER issue.  How is this bot helping things @laurent22 ?

**Comment by FarrimWildaxe** [comment]
I've got the same issue, what I found is:

Computer 1 - Joplin where encryption/decryption works is at **v2.18.8**, sync version: 3, profile version: **43**.

Computer 2 - Joplin which decryption weren't working was in **v2.12.x**, sync version: 3, profile version: **42**.

So, I tried to update older Joplin on computer 2 and decryption works :)
