### ISSUE TITLE
OneDrive Sync not fetching resources in all devices (iOS and Windows)

### ISSUE THREAD

**Issue by Pitenager** [laurent22/joplin#6493]
## Environment

Joplin version: Joplin 2.7.15 (prod, win32) Client ID: 6f9a7dc1afd94f2d98500b9a162914d6  Sync Version: 3 Profile Version: 41 Keychain Supported: Yes Revision: 8352e23
Platform: Windows (but also iOS and macOS)
OS specifics:   Windows 10.0.18363 N/A Build 18363 ----- iOS 15.4.1 ----- macOS 12.3.1

## Steps to reproduce

1.  Having and initial Joplin installation in one device, install Joplin in another one and link it with the OneDrive account where you have the contents you want to sync
2.  Click in Synchronize and wait until it is complete
3.  After the synchronization process in the new device ends, it won't have all the original contents from the first one or, at least, it won't display all (I've found by using the Search function that those notes/notebooks are still there and are accessible, but the UI does not show them.

## Describe what you expected to happen
I expect to synchronize the contents between devices resulting in the same final state in all of them.
For example, in the following image I'm accessing a note from a notebook that is not displayed in the UI:
![sync](https://user-images.githubusercontent.com/32803812/167266579-41379566-2ad8-492d-86b2-59581eb36ac3.png)

The Tree must be:
![image](https://user-images.githubusercontent.com/32803812/167266838-01c4af34-d9d3-4961-808c-b33db42528c6.png)

This is just an example of a note, but that whole tree is not displayed when trying to sync in other devices (and it's 30+ notebooks with a total of 200+ notes)

It is also possible to see that the images are not downloaded/displayed for some reason (maybe the same (?)), but this behaviour is specially common when synchronizing in iOS app.

## Logfile

Log file here:

[log-Copy.txt](https://github.com/laurent22/joplin/files/8645716/log-Copy.txt)

**Comment by Pitenager** [comment]
There is also relevant to mark that the resources that the log file says that are not found, are actually in OneDrive and I can access them manually.

**Comment by Daeraxa** [comment]
Did you keep the device active whilst you did the sync? The app currently doesn't background sync and seems like it has finished when it actually didn't get everything.

**Comment by Pitenager** [comment]
Hi @Daeraxa !

Yes, I have the app open during all the process

**Comment by Pitenager** [comment]
In fact, I just deleted the contents in the new device using "Delete local data and re-download from sync target" and this is the result after synchronizing again:
![image](https://user-images.githubusercontent.com/32803812/167267690-f8cb43d0-1cbd-4793-86ad-111b9b3e4fa8.png)

**Comment by Daeraxa** [comment]
Do any of the other devices show anything similar?
From looking on the forums this issue has been seen before with OneDrive but with no clear solution, possibly related to too many requests in a time period or too many simultaneous connections.

**Comment by Pitenager** [comment]
Yes ! Both: in the iOS and Windows devices the result is the same, I've tried with the default 5 concurrent connections and with 10

**Comment by Daeraxa** [comment]
Have you tried dropping it to 1? Otherwise it might be worth leaving it for a bit and seeing if it works later.

**Comment by Pitenager** [comment]
Finished. No errors, but less notebooks than in the previous image

**Comment by Pitenager** [comment]
![image](https://user-images.githubusercontent.com/32803812/167270993-4742f688-e8c6-4d91-ba3a-aa2f247d0e34.png)

**Comment by Daeraxa** [comment]
Did you get any more of those errors in the log on that sync?

**Comment by Pitenager** [comment]
Yes:

```
2022-05-07 21:30:58: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2022-05-07 21:30:59: "Garbage collecting alarms..."
2022-05-07 21:30:59: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2022-05-07 21:30:59: RevisionService: "maintenance: Starting..."
2022-05-07 21:30:59: RevisionService: "maintenance: Service is enabled"
2022-05-07 21:30:59: RevisionService: "collectRevisions: Created revisions for 0 notes"
2022-05-07 21:30:59: Synchronizer: "Sync: createLocal: remote exists but local does not: (Remote 8dfe45aca8544e68b824016c2d82b0cd.md)"
2022-05-07 21:30:59: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2022-05-07 21:31:00: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2022-05-07 21:31:00: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2022-05-07 21:31:00: RevisionService: "maintenance: Done in 1457ms"
2022-05-07 21:31:00: Synchronizer: "Sync: createLocal: remote exists but local does not: (Remote 0dd7dabf29fb4d8abcf3b5485f914d1c.md)"
2022-05-07 21:31:01: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2022-05-07 21:31:01: OneDriveApi: "Got error below - retrying (0)..."
2022-05-07 21:31:01: OneDriveApi: "SyntaxError: OneDriveApi::exec: Cannot parse JSON error:  Unexpected end of JSON input
SyntaxError: OneDriveApi::exec: Cannot parse JSON error:  Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at OneDriveApi.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:300:46)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
2022-05-07 21:31:07: OneDriveApi: "Got error below - retrying (1)..."
2022-05-07 21:31:07: OneDriveApi: "SyntaxError: OneDriveApi::exec: Cannot parse JSON error:  Unexpected end of JSON input
SyntaxError: OneDriveApi::exec: Cannot parse JSON error:  Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at OneDriveApi.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:300:46)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
2022-05-07 21:31:17: OneDriveApi: "Got error below - retrying (2)..."
2022-05-07 21:31:17: OneDriveApi: "SyntaxError: OneDriveApi::exec: Cannot parse JSON error:  Unexpected end of JSON input
SyntaxError: OneDriveApi::exec: Cannot parse JSON error:  Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at OneDriveApi.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:300:46)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
2022-05-07 21:31:33: OneDriveApi: "Got error below - retrying (3)..."
2022-05-07 21:31:33: OneDriveApi: "SyntaxError: OneDriveApi::exec: Cannot parse JSON error:  Unexpected end of JSON input
SyntaxError: OneDriveApi::exec: Cannot parse JSON error:  Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at OneDriveApi.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:300:46)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
2022-05-07 21:31:53: OneDriveApi: "Got error below - retrying (4)..."
2022-05-07 21:31:53: OneDriveApi: "SyntaxError: OneDriveApi::exec: Cannot parse JSON error:  Unexpected end of JSON input
SyntaxError: OneDriveApi::exec: Cannot parse JSON error:  Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at OneDriveApi.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:300:46)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
2022-05-07 21:32:18: Synchronizer: "Error: On file f1e37f6c9415404dac24d8e91b16e103.md: Could not execute request after multiple attempts: GET https://graph.microsoft.com/v1.0/drive/root:/Apps/Joplin/f1e37f6c9415404dac24d8e91b16e103.md:/content
Error: On file f1e37f6c9415404dac24d8e91b16e103.md: Could not execute request after multiple attempts: GET https://graph.microsoft.com/v1.0/drive/root:/Apps/Joplin/f1e37f6c9415404dac24d8e91b16e103.md:/content
    at OneDriveApi.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:361:19)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:5:58)"
2022-05-07 21:32:19: Synchronizer: "Sync: finished: Synchronisation finished [1651950149511]"
2022-05-07 21:32:19: Synchronizer: "Operations completed: "
2022-05-07 21:32:19: Synchronizer: "updateRemote: 1"
2022-05-07 21:32:19: Synchronizer: "createRemote: 1"
2022-05-07 21:32:19: Synchronizer: "fetchingTotal: 3250"
2022-05-07 21:32:19: Synchronizer: "fetchingProcessed: 3215"
2022-05-07 21:32:19: Synchronizer: "createLocal: 639"
2022-05-07 21:32:19: OneDriveApi: "Got error below - retrying (0)..."
2022-05-07 21:32:19: OneDriveApi: "SyntaxError: OneDriveApi::exec: Cannot parse JSON error:  Unexpected end of JSON input
SyntaxError: OneDriveApi::exec: Cannot parse JSON error:  Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at OneDriveApi.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:300:46)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
2022-05-07 21:32:19: Synchronizer: "Total folders: 130"
2022-05-07 21:32:19: Synchronizer: "Total notes: 479"
2022-05-07 21:32:19: Synchronizer: "Total resources: 1967"
2022-05-07 21:32:19: Synchronizer: "There was some errors:"
2022-05-07 21:32:19: Synchronizer: "Error: On file f1e37f6c9415404dac24d8e91b16e103.md: Could not execute request after multiple attempts: GET https://graph.microsoft.com/v1.0/drive/root:/Apps/Joplin/f1e37f6c9415404dac24d8e91b16e103.md:/content
Error: On file f1e37f6c9415404dac24d8e91b16e103.md: Could not execute request after multiple attempts: GET https://graph.microsoft.com/v1.0/drive/root:/Apps/Joplin/f1e37f6c9415404dac24d8e91b16e103.md:/content
    at OneDriveApi.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:361:19)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:5:58)"
2022-05-07 21:32:20: "DecryptionWorker: cannot start because no master key is currently loaded."
2022-05-07 21:32:25: OneDriveApi: "Got error below - retrying (1)..."
2022-05-07 21:32:25: OneDriveApi: "SyntaxError: OneDriveApi::exec: Cannot parse JSON error:  Unexpected end of JSON input
SyntaxError: OneDriveApi::exec: Cannot parse JSON error:  Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at OneDriveApi.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:300:46)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
2022-05-07 21:32:35: OneDriveApi: "Got error below - retrying (2)..."
2022-05-07 21:32:35: OneDriveApi: "SyntaxError: OneDriveApi::exec: Cannot parse JSON error:  Unexpected end of JSON input
SyntaxError: OneDriveApi::exec: Cannot parse JSON error:  Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at OneDriveApi.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:300:46)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
2022-05-07 21:32:51: OneDriveApi: "Got error below - retrying (3)..."
2022-05-07 21:32:51: OneDriveApi: "SyntaxError: OneDriveApi::exec: Cannot parse JSON error:  Unexpected end of JSON input
SyntaxError: OneDriveApi::exec: Cannot parse JSON error:  Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at OneDriveApi.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:300:46)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
2022-05-07 21:33:11: OneDriveApi: "Got error below - retrying (4)..."
2022-05-07 21:33:11: OneDriveApi: "SyntaxError: OneDriveApi::exec: Cannot parse JSON error:  Unexpected end of JSON input
SyntaxError: OneDriveApi::exec: Cannot parse JSON error:  Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at OneDriveApi.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:300:46)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
````

**Comment by Daeraxa** [comment]
Note sure what else to suggest short of backing up all your data, wiping the sync target and starting over. Probably worth posting to the support category on the forum instead. It seems to be an uncommon problem and nobody has suggested any real solution to it.

**Comment by Pitenager** [comment]
Posted here https://discourse.joplinapp.org/t/changed-title-and-note-no-longer-in-list/25560

**Comment by Pitenager** [comment]
Still waiting for a fix.

**Comment by zeyu2001** [comment]
I've had this issue for quite a while and just realised why it's happening. OneDrive itself has an antivirus mechanism that presents a 403 error whenever you try to download a "malicious" file through the API. Since your notes seem to be security-related topics, it is inevitable that the `.md` files are being picked up as "malicious".

I've fixed this by enabling encryption on Joplin so that OneDrive cannot detect the cleartext payloads.
