### ISSUE TITLE
Sync Error: hasMore not handled

### ISSUE THREAD

**Issue by BetaMaxHeadroom** [laurent22/joplin#6536]
Windows identified some of my notes as malicious scripts. This has lead to sync issues. I would greatly appreciate any help that you are willing to provide. 

## Environment

Joplin version: 2.7.15
Platform: Windows, Linux, and Android
OS specifics: 
Linux: Linux Mint 20.3 x86_64
Windows: 10 and Windows 11
Android: Samsung Galaxy S20 Version G981U1UES2EVE1

## Steps to reproduce

1. Have Joplin syncing without error across Windows and Android 
2. Update Joplin on a Linux host that I haven't authenticated to in months
3. Joplin update is now an appimage
4. Allow automatic syncing via OneDrive
5. Windows identifies some of my notes as malicious code (I am a security engineer/penetration tester)
6. Add exceptions for Windows
7. Start different device that was able to sync yesterday (05/24/2022) in airplane mode to avoid syncing, export all files as .jex file, and attempt to import to affected Joplin instances
8. Unsuccessfully research a 'hasMore not handled' error

## Describe what you expected to happen
I would like to have everything work exactly as it worked before the issue started yesterday, or to have everything work with the recently created .jex file.

## Logfile

`2022-05-25 10:55:03: "Database was open successfully"
2022-05-25 10:55:03: "Checking for database schema update..."
2022-05-25 10:55:03: "Current database version", "{"version":41,"table_fields_version":41}"
2022-05-25 10:55:03: "Upgrading database from version 41"
2022-05-25 10:55:03: "New version: 41. Previously recorded version: 41"
2022-05-25 10:55:04: "KeychainService: checking if keychain supported"
2022-05-25 10:55:04: "KeychainService: check was already done - skipping. Supported:", "0"
2022-05-25 10:55:04: e2ee/utils: "Master password is not set - trying to get it from the active master key..."
2022-05-25 10:55:04: handleSyncStartupOperation: "Processing operation:", "0"
2022-05-25 10:55:04: App: "Client ID: 54bd86184ead4d8ab9e6f51c03e544ea"
2022-05-25 10:55:04: models/Setting: "Applying default migrations..."
2022-05-25 10:55:04: e2ee/utils: "Trying to load 0 master keys..."
2022-05-25 10:55:04: e2ee/utils: "Loaded master keys: 0"
2022-05-25 10:55:04: "ResourceFetcher: Auto-add resources: Mode: always"
2022-05-25 10:55:04: "ResourceFetcher: Auto-added resources: 0"
2022-05-25 10:55:04: App: ""syncInfoCache" was changed - setting up encryption related code"
2022-05-25 10:55:04: e2ee/utils: "Trying to load 0 master keys..."
2022-05-25 10:55:04: e2ee/utils: "Loaded master keys: 0"
2022-05-25 10:55:04: App: ""syncInfoCache" was changed - setting up encryption related code"
2022-05-25 10:55:04: e2ee/utils: "Trying to load 0 master keys..."
2022-05-25 10:55:04: e2ee/utils: "Loaded master keys: 0"
2022-05-25 10:55:04: App: ""syncInfoCache" was changed - setting up encryption related code"
2022-05-25 10:55:04: e2ee/utils: "Trying to load 0 master keys..."
2022-05-25 10:55:04: e2ee/utils: "Loaded master keys: 0"
2022-05-25 10:55:04: "app.start: doing regular boot"
2022-05-25 10:55:04: "KeymapService: Loading keymap from file: /home/userid/.config/joplin-desktop/keymap-desktop.json"
2022-05-25 10:55:04: App: ""syncInfoCache" was changed - setting up encryption related code"
2022-05-25 10:55:04: e2ee/utils: "Trying to load 0 master keys..."
2022-05-25 10:55:04: e2ee/utils: "Loaded master keys: 0"
2022-05-25 10:55:04: App: ""syncInfoCache" was changed - setting up encryption related code"
2022-05-25 10:55:04: e2ee/utils: "Trying to load 0 master keys..."
2022-05-25 10:55:04: e2ee/utils: "Loaded master keys: 0"
2022-05-25 10:55:04: App: ""syncInfoCache" was changed - setting up encryption related code"
2022-05-25 10:55:04: e2ee/utils: "Trying to load 0 master keys..."
2022-05-25 10:55:04: e2ee/utils: "Loaded master keys: 0"
2022-05-25 10:55:04: RevisionService: "runInBackground: Starting background service with revision collection interval 600000"
2022-05-25 10:55:04: PluginService: "Loading plugin from /home/userid/.config/joplin-desktop/cache/com.github.marcgreen.joplin-plugin-semantically-similar-notes"
2022-05-25 10:55:05: PluginService: "Loading plugin from /home/userid/.config/joplin-desktop/cache/joplin.plugin.forcewake.tags-generator"
2022-05-25 10:55:05: "DecryptionWorker: cannot start because no master key is currently loaded."
2022-05-25 10:55:05: PluginService: "Loading plugin from /home/userid/.config/joplin-desktop/cache/outline"
2022-05-25 10:55:05: PluginService: "Loading plugin from /home/userid/.config/joplin-desktop/cache/plugin.calebjohn.rich-markdown"
2022-05-25 10:55:05: "Preparing scheduled sync"
2022-05-25 10:55:05: "Saving updated OneDrive auth."
2022-05-25 10:55:05: SpellCheckerServiceDriverNative: "Set effective language from "en-US" to "en-US""
2022-05-25 10:55:08: joplin.plugins: "Starting plugin: outline"
2022-05-25 10:55:08: joplin.plugins: "Starting plugin: joplin.plugin.forcewake.tags-generator"
2022-05-25 10:55:08: joplin.plugins: "Starting plugin: plugin.calebjohn.rich-markdown"
2022-05-25 10:55:08: joplin.plugins: "Starting plugin: com.github.marcgreen.joplin-plugin-semantically-similar-notes"
2022-05-25 10:55:08: RevisionService: "maintenance: Starting..."
2022-05-25 10:55:08: RevisionService: "maintenance: Service is enabled"
2022-05-25 10:55:09: joplin.plugins: "Finished running onStart handler: joplin.plugin.forcewake.tags-generator (Took 929ms)"
2022-05-25 10:55:09: OneDriveApi: "Token expired: refreshing..."
2022-05-25 10:55:09: RevisionService: "collectRevisions: Created revisions for 0 notes"
2022-05-25 10:55:09: RevisionService: "maintenance: Done in 776ms"
2022-05-25 10:55:10: "Saving updated OneDrive auth."
2022-05-25 10:55:12: joplin.plugins: "Finished running onStart handler: plugin.calebjohn.rich-markdown (Took 3897ms)"
2022-05-25 10:55:12: "Starting scheduled sync"
2022-05-25 10:55:12: Synchronizer: "Sync: starting: Starting synchronisation to target 3... supportsAccurateTimestamp = false; supportsMultiPut = false [1653490512103]"
2022-05-25 10:55:12: Synchronizer: "Indexing resources..."
2022-05-25 10:55:12: "ResourceService::indexNoteResources: Start"
2022-05-25 10:55:13: "ResourceService::indexNoteResources: Completed"
2022-05-25 10:55:14: "SearchEngine: Updating FTS table..."
2022-05-25 10:55:14: "SearchEngine: Updated FTS table in 256ms. Inserted: 0. Deleted: 0"
2022-05-25 10:55:16: Synchronizer: "Sync target remote info:", "{"version_":3,"masterKeys_":[],"e2ee_":{"value":false,"updatedTime":0},"activeMasterKeyId_":{"value":"","updatedTime":0},"ppk_":{"value":null,"updatedTime":0}}"
2022-05-25 10:55:16: Synchronizer: "Sync target is already setup - checking it..."
2022-05-25 10:55:16: Synchronizer: "Sync target local info:", "{"version_":3,"masterKeys_":[],"e2ee_":{"value":false,"updatedTime":0},"activeMasterKeyId_":{"value":"","updatedTime":0},"ppk_":{"value":null,"updatedTime":0}}"
2022-05-25 10:55:16: joplin.plugins: "Finished running onStart handler: outline (Took 8421ms)"
2022-05-25 10:55:17: BackOffHandler: "Plugin com.github.marcgreen.joplin-plugin-semantically-similar-notes: Applying a backoff of 1 seconds due to frequent plugin API calls. Consider reducing the number of calls, caching the data, or requesting more data per call. API call was: ", "joplin.data.get", "[["notes","21530e07dad347b3896c9ed7df874d2b"],{"fields":["id","parent_id","title","body"],"order_by":"updated_time","order_dir":"DESC","limit":100}]", "[Wait count: 1]"
2022-05-25 10:55:17: BackOffHandler: "Plugin com.github.marcgreen.joplin-plugin-semantically-similar-notes: Applying a backoff of 1 seconds due to frequent plugin API calls. Consider reducing the number of calls, caching the data, or requesting more data per call. API call was: ", "joplin.data.get", "[["notes","1a5d36fd2e9c40b68051a25063a8424c"],{"fields":["id","parent_id","title","body"],"order_by":"updated_time","order_dir":"DESC","limit":100}]", "[Wait count: 1]"
2022-05-25 10:55:17: BackOffHandler: "Plugin com.github.marcgreen.joplin-plugin-semantically-similar-notes: Applying a backoff of 2 seconds due to frequent plugin API calls. Consider reducing the number of calls, caching the data, or requesting more data per call. API call was: ", "joplin.data.get", "[["notes","ec152678ecc5448388b804477e93abe2"],{"fields":["id","parent_id","title","body"],"order_by":"updated_time","order_dir":"DESC","limit":100}]", "[Wait count: 1]"
2022-05-25 10:55:17: BackOffHandler: "Plugin com.github.marcgreen.joplin-plugin-semantically-similar-notes: Applying a backoff of 3 seconds due to frequent plugin API calls. Consider reducing the number of calls, caching the data, or requesting more data per call. API call was: ", "joplin.data.get", "[["notes","c6c1e76280104cf7b80cbed975b485e0"],{"fields":["id","parent_id","title","body"],"order_by":"updated_time","order_dir":"DESC","limit":100}]", "[Wait count: 1]"
2022-05-25 10:55:17: BackOffHandler: "Plugin com.github.marcgreen.joplin-plugin-semantically-similar-notes: Applying a backoff of 5 seconds due to frequent plugin API calls. Consider reducing the number of calls, caching the data, or requesting more data per call. API call was: ", "joplin.data.get", "[["notes","b51aa3cf846f4cb6b67b18443f89fccd"],{"fields":["id","parent_id","title","body"],"order_by":"updated_time","order_dir":"DESC","limit":100}]", "[Wait count: 1]"
2022-05-25 10:55:17: BackOffHandler: "Plugin com.github.marcgreen.joplin-plugin-semantically-similar-notes: Applying a backoff of 8 seconds due to frequent plugin API calls. Consider reducing the number of calls, caching the data, or requesting more data per call. API call was: ", "joplin.data.get", "[["notes","30ed58909e63483595ed23b6357de4c5"],{"fields":["id","parent_id","title","body"],"order_by":"updated_time","order_dir":"DESC","limit":100}]", "[Wait count: 1]"
2022-05-25 10:55:17: BackOffHandler: "Plugin com.github.marcgreen.joplin-plugin-semantically-similar-notes: Applying a backoff of 8 seconds due to frequent plugin API calls. Consider reducing the number of calls, caching the data, or requesting more data per call. API call was: ", "joplin.data.get", "[["notes","a0991b0543d14917ba1cc06022ff27a7"],{"fields":["id","parent_id","title","body"],"order_by":"updated_time","order_dir":"DESC","limit":100}]", "[Wait count: 1]"
2022-05-25 10:55:17: BackOffHandler: "Plugin com.github.marcgreen.joplin-plugin-semantically-similar-notes: Applying a backoff of 8 seconds due to frequent plugin API calls. Consider reducing the number of calls, caching the data, or requesting more data per call. API call was: ", "joplin.data.get", "[["notes","8fe7280a1e414513ba6bdb3f168a9b46"],{"fields":["id","parent_id","title","body"],"order_by":"updated_time","order_dir":"DESC","limit":100}]", "[Wait count: 1]"
2022-05-25 10:55:17: BackOffHandler: "Plugin com.github.marcgreen.joplin-plugin-semantically-similar-notes: Applying a backoff of 8 seconds due to frequent plugin API calls. Consider reducing the number of calls, caching the data, or requesting more data per call. API call was: ", "joplin.data.get", "[["notes","6b982c40460a48ed8c299df87d52a815"],{"fields":["id","parent_id","title","body"],"order_by":"updated_time","order_dir":"DESC","limit":100}]", "[Wait count: 1]"
2022-05-25 10:55:17: BackOffHandler: "Plugin com.github.marcgreen.joplin-plugin-semantically-similar-notes: Applying a backoff of 8 seconds due to frequent plugin API calls. Consider reducing the number of calls, caching the data, or requesting more data per call. API call was: ", "joplin.data.get", "[["notes","36537b49e7814527a13b2ed9147c402b"],{"fields":["id","parent_id","title","body"],"order_by":"updated_time","order_dir":"DESC","limit":100}]", "[Wait count: 1]"
2022-05-25 10:55:17: BackOffHandler: "Plugin com.github.marcgreen.joplin-plugin-semantically-similar-notes: Applying a backoff of 8 seconds due to frequent plugin API calls. Consider reducing the number of calls, caching the data, or requesting more data per call. API call was: ", "joplin.data.get", "[["notes","ea46fe767d3948c0961f088a0fb898e8"],{"fields":["id","parent_id","title","body"],"order_by":"updated_time","order_dir":"DESC","limit":100}]", "[Wait count: 1]"
2022-05-25 10:55:17: BackOffHandler: "Plugin com.github.marcgreen.joplin-plugin-semantically-similar-notes: Applying a backoff of 8 seconds due to frequent plugin API calls. Consider reducing the number of calls, caching the data, or requesting more data per call. API call was: ", "joplin.data.get", "[["notes","af36bea863fc4bab87e9d6076b0f746e"],{"fields":["id","parent_id","title","body"],"order_by":"updated_time","order_dir":"DESC","limit":100}]", "[Wait count: 1]"
2022-05-25 10:55:17: BackOffHandler: "Plugin com.github.marcgreen.joplin-plugin-semantically-similar-notes: Applying a backoff of 8 seconds due to frequent plugin API calls. Consider reducing the number of calls, caching the data, or requesting more data per call. API call was: ", "joplin.data.get", "[["notes","6eca11a1b8c045b389c5376903654a33"],{"fields":["id","parent_id","title","body"],"order_by":"updated_time","order_dir":"DESC","limit":100}]", "[Wait count: 1]"
2022-05-25 10:55:17: BackOffHandler: "Plugin com.github.marcgreen.joplin-plugin-semantically-similar-notes: Applying a backoff of 8 seconds due to frequent plugin API calls. Consider reducing the number of calls, caching the data, or requesting more data per call. API call was: ", "joplin.data.get", "[["notes","33ceae9778d64e28bc721f05441dbd3e"],{"fields":["id","parent_id","title","body"],"order_by":"updated_time","order_dir":"DESC","limit":100}]", "[Wait count: 1]"
2022-05-25 10:55:17: BackOffHandler: "Plugin com.github.marcgreen.joplin-plugin-semantically-similar-notes: Applying a backoff of 8 seconds due to frequent plugin API calls. Consider reducing the number of calls, caching the data, or requesting more data per call. API call was: ", "joplin.data.get", "[["notes","dcc9f6413358459eb63fc74da62717fe"],{"fields":["id","parent_id","title","body"],"order_by":"updated_time","order_dir":"DESC","limit":100}]", "[Wait count: 1]"
2022-05-25 10:55:17: BackOffHandler: "Plugin com.github.marcgreen.joplin-plugin-semantically-similar-notes: Applying a backoff of 8 seconds due to frequent plugin API calls. Consider reducing the number of calls, caching the data, or requesting more data per call. API call was: ", "joplin.data.get", "[["notes","5068752c37654cc1827a671b1c724695"],{"fields":["id","parent_id","title","body"],"order_by":"updated_time","order_dir":"DESC","limit":100}]", "[Wait count: 1]"
2022-05-25 10:55:17: BackOffHandler: "Plugin com.github.marcgreen.joplin-plugin-semantically-similar-notes: Applying a backoff of 8 seconds due to frequent plugin API calls. Consider reducing the number of calls, caching the data, or requesting more data per call. API call was: ", "joplin.data.get", "[["notes","351e06264803448993b6462ba5facb6c"],{"fields":["id","parent_id","title","body"],"order_by":"updated_time","order_dir":"DESC","limit":100}]", "[Wait count: 1]"
2022-05-25 10:55:17: BackOffHandler: "Plugin com.github.marcgreen.joplin-plugin-semantically-similar-notes: Applying a backoff of 8 seconds due to frequent plugin API calls. Consider reducing the number of calls, caching the data, or requesting more data per call. API call was: ", "joplin.data.get", "[["notes","25479d7cadf74a19bcc573a2907ca97d"],{"fields":["id","parent_id","title","body"],"order_by":"updated_time","order_dir":"DESC","limit":100}]", "[Wait count: 1]"
2022-05-25 10:55:17: BackOffHandler: "Plugin com.github.marcgreen.joplin-plugin-semantically-similar-notes: Applying a backoff of 8 seconds due to frequent plugin API calls. Consider reducing the number of calls, caching the data, or requesting more data per call. API call was: ", "joplin.data.get", "[["notes","9e4d736f1cbd4123808a9f78c889eea5"],{"fields":["id","parent_id","title","body"],"order_by":"updated_time","order_dir":"DESC","limit":100}]", "[Wait count: 1]"
2022-05-25 10:55:21: Synchronizer: "Error: hasMore not handled
Error: hasMore not handled
    at LockHandler.<anonymous> (/tmp/.mount_JoplintgYwiD/resources/app.asar/node_modules/@joplin/lib/services/synchronizer/LockHandler.js:163:23)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_JoplintgYwiD/resources/app.asar/node_modules/@joplin/lib/services/synchronizer/LockHandler.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
2022-05-25 10:55:21: Synchronizer: "Sync: finished: Synchronisation finished [1653490512103]"
2022-05-25 10:55:21: Synchronizer: "Operations completed: "
2022-05-25 10:55:21: Synchronizer: "Total folders: 148"
2022-05-25 10:55:21: Synchronizer: "Total notes: 583"
2022-05-25 10:55:21: Synchronizer: "Total resources: 2446"
2022-05-25 10:55:21: Synchronizer: "There was some errors:"
2022-05-25 10:55:21: Synchronizer: "Error: hasMore not handled
Error: hasMore not handled
    at LockHandler.<anonymous> (/tmp/.mount_JoplintgYwiD/resources/app.asar/node_modules/@joplin/lib/services/synchronizer/LockHandler.js:163:23)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_JoplintgYwiD/resources/app.asar/node_modules/@joplin/lib/services/synchronizer/LockHandler.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
2022-05-25 10:55:21: "Updating all notifications..."
2022-05-25 10:55:21: "Garbage collecting alarms..."
2022-05-25 10:55:21: "Trying to reload note that has been deleted:", "null"
2022-05-25 10:55:22: "DecryptionWorker: cannot start because no master key is currently loaded."
2022-05-25 10:55:34: "ResourceService::indexNoteResources: Start"
2022-05-25 10:55:34: "ResourceService::indexNoteResources: Completed"
2022-05-25 10:55:34: "ResourceService::deleteOrphanResources:", "[]"
`

**Comment by navlar** [comment]
I'm having the same issue on Windows 10.
New files on Windows 10 won't sink with other devices.
Same error comes up on other device Macbook... will not update with new files from Windows 10

**Comment by navlar** [comment]
## Data won't sync on OneDrive
```
Last error: Error: hasMore not handled
```

**Joplin v2.9.17 (prod, win32)**
Sync Version: 3
Profile Version: 41
Synchronization: OneDrive

Running on:
Windows 10 and Mac OS 19.15.7

Same error on both machines PC and Mac: 

Completed: 2023-02-19 7:16 PM (4s)
Last error: Error: hasMore not handled

In debug mode I can see this error in the console which seems to correspond to "Error: hasMore not handled"

```
D:\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\Logger.js:190 19:20:15: Synchronizer: Error: hasMore not handled
    at LockHandler.<anonymous> (D:\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\services\synchronizer\LockHandler.js:163:23)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\services\synchronizer\LockHandler.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by uKitago** [comment]
Same error on
- Ubuntu 22.04 (v2.14.19, AppImage), 2 individual machines
- iPadOS 17.3.1 (v12.14.6)
- Win10 Enterprise 22H2 (v2.14.17)
looked like some incompatibility with OneDrive API. Do we have to switch to another switch method?
