### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by Ji-Peng** [laurent22/joplin#6540]
## Environment

Joplin version: Joplin 2.7.15 (prod, darwin)
Platform: MacOS
OS specifics: MacOS Monterey 12.3.1

## Steps to reproduce

Sync setting:
<img width="359" alt="image" src="https://user-images.githubusercontent.com/57220004/170830128-59472acc-528f-45ba-84bb-aeda2a197c47.png">

There was no problem when I used it before, but today I found out that the error occurred, and I didn't update Joplin, and I didn't even restart joplin.

I tried to create a new note locally and found that it can be uploaded to the cloud. So I'm guessing that the error occurs when parsing after downloading the cloud data.

I also tried to synchronize on windows and found the same error, the log file is the same.

## Logfile

2022-05-28 22:32:14: "Preparing scheduled sync"
2022-05-28 22:32:14: "Starting scheduled sync"
2022-05-28 22:32:14: Synchronizer: "Sync: starting: Starting synchronisation to target 8... supportsAccurateTimestamp = false; supportsMultiPut = false [1653748334153]"
2022-05-28 22:32:14: Synchronizer: "Indexing resources..."
2022-05-28 22:32:14: "ResourceService::indexNoteResources: Start"
2022-05-28 22:32:14: "ResourceService::indexNoteResources: Completed"
2022-05-28 22:32:14: Synchronizer: "Sync target remote info:", "{"version_":3,"masterKeys_":[],"e2ee_":{"value":false,"updatedTime":0},"activeMasterKeyId_":{"value":"","updatedTime":0},"ppk_":{"value":null,"updatedTime":0}}"
2022-05-28 22:32:14: Synchronizer: "Sync target is already setup - checking it..."
2022-05-28 22:32:14: Synchronizer: "Sync target local info:", "{"version_":3,"masterKeys_":[],"e2ee_":{"value":false,"updatedTime":0},"activeMasterKeyId_":{"value":"","updatedTime":0},"ppk_":{"value":null,"updatedTime":0}}"
2022-05-28 22:32:15: Synchronizer: "TaskQueue.stop: syncDownload: waiting for tasks to complete: 0"
2022-05-28 22:32:15: Synchronizer: "TaskQueue.stop: syncDownload: Done, waited for 0"
2022-05-28 22:32:39: Synchronizer: "TypeError: Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at FileApiDriverAmazonS3.metadataToStats_ (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api-driver-amazon-s3.js:181:27)
    at FileApiDriverAmazonS3.list (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api-driver-amazon-s3.js:226:32)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getDirStats (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api-driver-amazon-s3.js:193:19)"
2022-05-28 22:32:39: Synchronizer: "Sync: finished: Synchronisation finished [1653748334153]"
2022-05-28 22:32:39: Synchronizer: "Operations completed: "
2022-05-28 22:32:39: Synchronizer: "Total folders: 21"
2022-05-28 22:32:39: Synchronizer: "Total notes: 131"
2022-05-28 22:32:39: Synchronizer: "Total resources: 1"
2022-05-28 22:32:39: Synchronizer: "There was some errors:"
2022-05-28 22:32:39: Synchronizer: "TypeError: Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at FileApiDriverAmazonS3.metadataToStats_ (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api-driver-amazon-s3.js:181:27)
    at FileApiDriverAmazonS3.list (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api-driver-amazon-s3.js:226:32)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getDirStats (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api-driver-amazon-s3.js:193:19)"
2022-05-28 22:32:40: "DecryptionWorker: cannot start because no master key is currently loaded."

**Comment by travnewmatic** [comment]
What was the fix for this?  I've been experiencing this for a while now, on different platforms.  I'm not sure if this is an issue with my S3 provider (backblaze) or my data or what.  Very frustrating :(

**Comment by Ji-Peng** [comment]
Sorry, I forgot what I did. My impression seems to be that it was fixed after filling in these configurations again, which is very strange.
