### ISSUE TITLE
AWS Sync issue with S3 on v.2.8.8 Linux/Ubuntu22

### ISSUE THREAD

**Issue by lclap-versent** [laurent22/joplin#6578]
Using Desktop Joplin application v2.8.8 on Linux
Trying to sync to a bucket and receive the following error message

Followed the exact setup in the instructions, provided valid credentials and region.
Tested with aws cli and all permissions are working correctly.

```
23:34:37: Synchronizer: TemporaryRedirect: Please re-send this request to the specified temporary endpoint. Continue to use the original request endpoint for future requests.


    at deserializeAws_restXmlDeleteObjectCommandError (/tmp/.mount_JoplinY4JtbD/resources/app.asar/node_modules/@joplin/lib/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:5141:41)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /tmp/.mount_JoplinY4JtbD/resources/app.asar/node_modules/@joplin/lib/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:6:20
    at async /tmp/.mount_JoplinY4JtbD/resources/app.asar/node_modules/@joplin/lib/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
    at async StandardRetryStrategy.retry (/tmp/.mount_JoplinY4JtbD/resources/app.asar/node_modules/@joplin/lib/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /tmp/.mount_JoplinY4JtbD/resources/app.asar/node_modules/@joplin/lib/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
```

## Environment

Joplin version:  2.8.8
Platform:  Linux - Ubuntu 22 LTS
OS specifics: 5.15.0-37-generic #39-Ubuntu SMP

## Steps to reproduce

1. press sync button after completing the configuration of the sync (S3 beta)
2. Review console logs, extract the error.

## Logfile

```
    2022-06-12 00:25:12: "Starting scheduled sync"
2022-06-12 00:25:12: Synchronizer: "Sync: starting: Starting synchronisation to target 8... supportsAccurateTimestamp = false; supportsMultiPut = false [1654957512077]"
2022-06-12 00:25:12: Synchronizer: "Indexing resources..."
2022-06-12 00:25:12: "ResourceService::indexNoteResources: Start"
2022-06-12 00:25:12: "ResourceService::indexNoteResources: Completed"
2022-06-12 00:25:12: models/Folder: "updateFolderShareIds:", "{"shareUpdateCount":0,"unshareUpdateCount":0}"
2022-06-12 00:25:12: models/Folder: "updateNoteShareIds: notes to update:", "0"
2022-06-12 00:25:12: FileApi: "get info.json"
2022-06-12 00:25:13: FileApi: "get .sync/version.txt"
2022-06-12 00:25:14: Synchronizer: "Sync target remote info:", "{"version_":0,"masterKeys_":[],"e2ee_":{"value":false,"updatedTime":0},"activeMasterKeyId_":{"value":"","updatedTime":0},"ppk_":{"value":null,"updatedTime":0}}"
2022-06-12 00:25:14: Synchronizer: "Sync target is new - setting it up..."
2022-06-12 00:25:14: FileApi: "get info.json"
2022-06-12 00:25:15: FileApi: "get .sync/version.txt"
2022-06-12 00:25:16: "MigrationHandler: Sync target version is 0 or 1 - creating "locks" and "temp" directory:", "{"version":0}"
2022-06-12 00:25:16: FileApi: "mkdir locks"
2022-06-12 00:25:16: FileApi: "mkdir temp"
2022-06-12 00:25:16: "MigrationHandler: Acquiring exclusive lock"
2022-06-12 00:25:16: FileApi: "list "
2022-06-12 00:25:39: FileApi: "delete locks/2_1_7c7c28688884436b82b3084561f4a952.json"
2022-06-12 00:26:03: Synchronizer: "TemporaryRedirect: Please re-send this request to the specified temporary endpoint. Continue to use the original request endpoint for future requests.
TemporaryRedirect: Please re-send this request to the specified temporary endpoint. Continue to use the original request endpoint for future requests.
    at deserializeAws_restXmlDeleteObjectCommandError (~/joplin/packages/lib/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:5141:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ~/joplin/packages/lib/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:6:20
    at async ~/joplin/packages/lib/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
    at async StandardRetryStrategy.retry (~/joplin/packages/lib/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async ~/joplin/packages/lib/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22"
2022-06-12 00:26:03: Synchronizer: "Sync: finished: Synchronisation finished [1654957512077]"
2022-06-12 00:26:03: Synchronizer: "Operations completed: "
2022-06-12 00:26:03: Synchronizer: "Total folders: 0"
2022-06-12 00:26:03: Synchronizer: "Total notes: 0"
2022-06-12 00:26:03: Synchronizer: "Total resources: 0"
2022-06-12 00:26:03: Synchronizer: "There was some errors:"
2022-06-12 00:26:03: Synchronizer: "TemporaryRedirect: Please re-send this request to the specified temporary endpoint. Continue to use the original request endpoint for future requests.
TemporaryRedirect: Please re-send this request to the specified temporary endpoint. Continue to use the original request endpoint for future requests.
    at deserializeAws_restXmlDeleteObjectCommandError (~/joplin/packages/lib/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:5141:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ~/joplin/packages/lib/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:6:20
    at async ~/joplin/packages/lib/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
    at async StandardRetryStrategy.retry (~/joplin/packages/lib/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async ~/joplin/packages/lib/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22"
2022-06-12 00:26:03: "Setting up recurrent sync with interval 3600"
2022-06-12 00:26:03: "Recurrent sync operation DISABLED!!!"
2022-06-12 00:26:03: models/Setting: "Saving settings..."
2022-06-12 00:26:03: models/Setting: "Settings have been saved."
2022-06-12 00:26:04: "DecryptionWorker: cannot start because no master key is currently loaded."
2022-06-12 00:32:53: RevisionService: "maintenance: Starting..."
2022-06-12 00:32:53: RevisionService: "maintenance: Service is enabled"
2022-06-12 00:32:53: RevisionService: "collectRevisions: Created revisions for 0 notes"
2022-06-12 00:32:53: RevisionService: "maintenance: Done in 104ms"
2022-06-12 00:42:53: RevisionService: "maintenance: Starting..."
2022-06-12 00:42:53: RevisionService: "maintenance: Service is enabled"
2022-06-12 00:42:53: RevisionService: "collectRevisions: Created revisions for 0 notes"
2022-06-12 00:42:53: RevisionService: "maintenance: Done in 103ms"
2022-06-12 00:46:04: models/Setting: "Saving settings..."
```

**Comment by pauldoo** [comment]
For me, the default endpoint configured in Joplin of `https://s3.amazonaws.com` didn't work for my bucket.  I had to change it to the regional service endpoint.  (E.g `https://s3.eu-west-1.amazonaws.com` or `https://s3.us-west-2.amazonaws.com` - or one of the other endpoints depending on where your bucket is located.)

The full list of regional endpoints is available here: https://docs.aws.amazon.com/general/latest/gr/s3.html

I don't know if your error is exactly the same as what mine was, but it wouldn't hurt to try the regional endpoints..

**Comment by lclap-versent** [comment]
Thanks, that was the exact issue :+1: 
I thought perhaps the region would be substituted into the url on sync, i guess not.
Should update the documentation with this reference and the url format, its not very clear.
https://docs.aws.amazon.com/general/latest/gr/s3.html
