### ISSUE TITLE
Error: Got metadata for path but could not fetch content: XXX.md

### ISSUE THREAD

**Issue by traversebitree** [laurent22/joplin#6606]
## Environment

Joplin version: 2.8.8
Platform: Windows 11
WebDAV Server Platform: Windows 11 with IIS 10.0

## Steps to reproduce

1. Sync with webdav.
2. See error "Error: Got metadata for path but could not fetch content: f34c4089c885465089e7d7f53bc3d3ff.md".
![image](https://user-images.githubusercontent.com/30373236/174946143-a1894be8-d8eb-4c59-a2fe-25a7e2a8f91e.png)

3. The file `f34c4089c885465089e7d7f53bc3d3ff.md` at server is not empty.

## Describe what you expected to happen
Just sync successful without the error "Error: Got metadata for path but could not fetch content: xxx.md"

## Logfile

```shell
2022-06-22 12:45:12: "Preparing scheduled sync"
2022-06-22 12:45:12: "Starting scheduled sync"
2022-06-22 12:45:12: Synchronizer: "Sync: starting: Starting synchronisation to target 6... supportsAccurateTimestamp = false; supportsMultiPut = false [1655873112454]"
2022-06-22 12:45:12: Synchronizer: "Indexing resources..."
2022-06-22 12:45:12: "ResourceService::indexNoteResources: Start"
2022-06-22 12:45:12: "ResourceService::indexNoteResources: Completed"
2022-06-22 12:45:12: Synchronizer: "Sync target remote info:", "{"version_":3,"masterKeys_":[],"e2ee_":{"value":false,"updatedTime":0},"activeMasterKeyId_":{"value":"","updatedTime":0},"ppk_":{"value":null,"updatedTime":0}}"
2022-06-22 12:45:12: Synchronizer: "Sync target is already setup - checking it..."
2022-06-22 12:45:12: Synchronizer: "Sync target local info:", "{"version_":3,"masterKeys_":[],"e2ee_":{"value":false,"updatedTime":0},"activeMasterKeyId_":{"value":"","updatedTime":0},"ppk_":{"value":null,"updatedTime":0}}"
2022-06-22 12:45:12: Synchronizer: "Error: Got metadata for path but could not fetch content: f34c4089c885465089e7d7f53bc3d3ff.md
Error: Got metadata for path but could not fetch content: f34c4089c885465089e7d7f53bc3d3ff.md
    at Synchronizer.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:576:43)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
2022-06-22 12:45:12: Synchronizer: "Req 12:45:10: PUT http://192.168.1.2/NasWebDAV/Ddisk/WebDAV/Joplin/locks/1_1_8352bbe990dd44a8bc08cba50696f7ac.json {"headers":{"Authorization":"********","Content-Type":"text/plain","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-6257","User-Agent":"Joplin/1.0","Content-Length":"71"},"body":"{\"type\":1,\"clientType\":1,\"clientId\":\"8352bbe990dd44a8bc08cba50696f7ac\"}","ignoreTlsErrors":true,"timeout":120000,"maxRetry":0}"
2022-06-22 12:45:12: Synchronizer: "Res 12:45:10: "
2022-06-22 12:45:12: Synchronizer: "Req 12:45:10: PROPFIND http://192.168.1.2/NasWebDAV/Ddisk/WebDAV/Joplin/locks/ {"headers":{"Depth":1,"Authorization":"********","Content-Type":"text/xml","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-92570","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","ignoreTlsErrors":true,"timeout":120000,"maxRetry":0}"
2022-06-22 12:45:12: Synchronizer: "Res 12:45:10: <?xml version="1.0" encoding="utf-8"?><D:multistatus xmlns:D="DAV:"><D:response><D:href>http://192.168.1.2/NasWebDAV/Ddisk/WebDAV/Joplin/locks/</D:href><D:propstat><D:status>HTTP/1.1 200 OK</D:status><D:prop><D:getlastmodified>Wed, 22 Jun 2022 04:45:05 GMT</D:getlastmodified><D:resourcetype><D:collection/></D:resourcetype></D:prop></D:propstat></D:response><D:response><D:href>http://192.168.1.2/NasWebDAV/Ddisk/WebDAV/Joplin/locks/1_1_8352bbe990dd44a8bc08cba50696f7ac.json</D:href><D:propstat><D:status>HTTP/1.1 200 OK</D:status><D:prop><D:getlastmodified>Wed, 22 Jun 2022 04:45:05 GMT</D:getlastmodified><D:resourcetype/></D:prop></D:propstat></D:response></D:multistatus>"
2022-06-22 12:45:12: Synchronizer: "Req 12:45:10: PROPFIND http://192.168.1.2/NasWebDAV/Ddisk/WebDAV/Joplin/f34c4089c885465089e7d7f53bc3d3ff.md {"headers":{"Depth":0,"Authorization":"********","Content-Type":"text/xml","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-58492","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","ignoreTlsErrors":true,"timeout":120000,"maxRetry":0}"
2022-06-22 12:45:12: Synchronizer: "Res 12:45:10: <?xml version="1.0" encoding="utf-8"?><D:multistatus xmlns:D="DAV:"><D:response><D:href>http://192.168.1.2/NasWebDAV/Ddisk/WebDAV/Joplin/f34c4089c885465089e7d7f53bc3d3ff.md</D:href><D:propstat><D:status>HTTP/1.1 200 OK</D:status><D:prop><D:getlastmodified>Wed, 22 Jun 2022 00:26:40 GMT</D:getlastmodified><D:resourcetype/></D:prop></D:propstat></D:response></D:multistatus>"
2022-06-22 12:45:12: Synchronizer: "Req 12:45:10: GET http://192.168.1.2/NasWebDAV/Ddisk/WebDAV/Joplin/f34c4089c885465089e7d7f53bc3d3ff.md {"headers":{"Authorization":"********","Cache-Control":"no-store","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":true,"timeout":120000,"maxRetry":0}"
2022-06-22 12:45:12: Synchronizer: "Res 12:45:10: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312"/>
<title>404 - 找不到文件或目录。</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>
"
2022-06-22 12:45:12: Synchronizer: "Req 12:45:10: DELETE http://192.168.1.2/NasWebDAV/Ddisk/WebDAV/Joplin/locks/1_1_8352bbe990dd44a8bc08cba50696f7ac.json {"headers":{"Authorization":"********","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-71159","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":true,"timeout":120000,"maxRetry":0}"
2022-06-22 12:45:12: Synchronizer: "Res 12:45:10: "
2022-06-22 12:45:12: Synchronizer: "Req 12:45:12: GET http://192.168.1.2/NasWebDAV/Ddisk/WebDAV/Joplin/info.json {"headers":{"Authorization":"********","Cache-Control":"no-store","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":true,"timeout":120000,"maxRetry":0}"
2022-06-22 12:45:12: Synchronizer: "Res 12:45:12: {
	"version": 3,
	"e2ee": {
		"value": false,
		"updatedTime": 0
	},
	"activeMasterKeyId": {
		"value": "",
		"updatedTime": 0
	},
	"masterKeys": [],
	"ppk": {
		"value": null,
		"updatedTime": 0
	}
}"
2022-06-22 12:45:12: Synchronizer: "Req 12:45:12: PROPFIND http://192.168.1.2/NasWebDAV/Ddisk/WebDAV/Joplin/locks/ {"headers":{"Depth":1,"Authorization":"********","Content-Type":"text/xml","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-89571","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","ignoreTlsErrors":true,"timeout":120000,"maxRetry":0}"
2022-06-22 12:45:12: Synchronizer: "Res 12:45:12: <?xml version="1.0" encoding="utf-8"?><D:multistatus xmlns:D="DAV:"><D:response><D:href>http://192.168.1.2/NasWebDAV/Ddisk/WebDAV/Joplin/locks/</D:href><D:propstat><D:status>HTTP/1.1 200 OK</D:status><D:prop><D:getlastmodified>Wed, 22 Jun 2022 04:45:05 GMT</D:getlastmodified><D:resourcetype><D:collection/></D:resourcetype></D:prop></D:propstat></D:response></D:multistatus>"
2022-06-22 12:45:12: Synchronizer: "Req 12:45:12: PUT http://192.168.1.2/NasWebDAV/Ddisk/WebDAV/Joplin/locks/1_1_8352bbe990dd44a8bc08cba50696f7ac.json {"headers":{"Authorization":"********","Content-Type":"text/plain","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-88741","User-Agent":"Joplin/1.0","Content-Length":"71"},"body":"{\"type\":1,\"clientType\":1,\"clientId\":\"8352bbe990dd44a8bc08cba50696f7ac\"}","ignoreTlsErrors":true,"timeout":120000,"maxRetry":0}"
2022-06-22 12:45:12: Synchronizer: "Res 12:45:12: "
2022-06-22 12:45:12: Synchronizer: "Req 12:45:12: PROPFIND http://192.168.1.2/NasWebDAV/Ddisk/WebDAV/Joplin/locks/ {"headers":{"Depth":1,"Authorization":"********","Content-Type":"text/xml","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-37323","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","ignoreTlsErrors":true,"timeout":120000,"maxRetry":0}"
2022-06-22 12:45:12: Synchronizer: "Res 12:45:12: <?xml version="1.0" encoding="utf-8"?><D:multistatus xmlns:D="DAV:"><D:response><D:href>http://192.168.1.2/NasWebDAV/Ddisk/WebDAV/Joplin/locks/</D:href><D:propstat><D:status>HTTP/1.1 200 OK</D:status><D:prop><D:getlastmodified>Wed, 22 Jun 2022 04:45:08 GMT</D:getlastmodified><D:resourcetype><D:collection/></D:resourcetype></D:prop></D:propstat></D:response><D:response><D:href>http://192.168.1.2/NasWebDAV/Ddisk/WebDAV/Joplin/locks/1_1_8352bbe990dd44a8bc08cba50696f7ac.json</D:href><D:propstat><D:status>HTTP/1.1 200 OK</D:status><D:prop><D:getlastmodified>Wed, 22 Jun 2022 04:45:08 GMT</D:getlastmodified><D:resourcetype/></D:prop></D:propstat></D:response></D:multistatus>"
2022-06-22 12:45:12: Synchronizer: "Req 12:45:12: PROPFIND http://192.168.1.2/NasWebDAV/Ddisk/WebDAV/Joplin/f34c4089c885465089e7d7f53bc3d3ff.md {"headers":{"Depth":0,"Authorization":"********","Content-Type":"text/xml","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-31069","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","ignoreTlsErrors":true,"timeout":120000,"maxRetry":0}"
2022-06-22 12:45:12: Synchronizer: "Res 12:45:12: <?xml version="1.0" encoding="utf-8"?><D:multistatus xmlns:D="DAV:"><D:response><D:href>http://192.168.1.2/NasWebDAV/Ddisk/WebDAV/Joplin/f34c4089c885465089e7d7f53bc3d3ff.md</D:href><D:propstat><D:status>HTTP/1.1 200 OK</D:status><D:prop><D:getlastmodified>Wed, 22 Jun 2022 00:26:40 GMT</D:getlastmodified><D:resourcetype/></D:prop></D:propstat></D:response></D:multistatus>"
2022-06-22 12:45:12: Synchronizer: "Req 12:45:12: GET http://192.168.1.2/NasWebDAV/Ddisk/WebDAV/Joplin/f34c4089c885465089e7d7f53bc3d3ff.md {"headers":{"Authorization":"********","Cache-Control":"no-store","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":true,"timeout":120000,"maxRetry":0}"
2022-06-22 12:45:12: Synchronizer: "Res 12:45:12: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312"/>
<title>404 - 找不到文件或目录。</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>
"
2022-06-22 12:45:12: Synchronizer: "Sync: finished: Synchronisation finished [1655873112454]"
2022-06-22 12:45:12: Synchronizer: "Operations completed: "
2022-06-22 12:45:12: Synchronizer: "Total folders: 300"
2022-06-22 12:45:12: Synchronizer: "Total notes: 616"
2022-06-22 12:45:12: Synchronizer: "Total resources: 3293"
2022-06-22 12:45:12: Synchronizer: "There was some errors:"
2022-06-22 12:45:12: Synchronizer: "Error: Got metadata for path but could not fetch content: f34c4089c885465089e7d7f53bc3d3ff.md
Error: Got metadata for path but could not fetch content: f34c4089c885465089e7d7f53bc3d3ff.md
    at Synchronizer.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:576:43)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
2022-06-22 12:45:13: "DecryptionWorker: cannot start because no master key is currently loaded."
```

**Comment by traversebitree** [comment]
> Hey there, it looks like there has been no activity on this issue recently. Has the issue been fixed, or does it still require the community's attention? If you require support or are requesting an enhancement or feature then please create a topic on the [Joplin forum](https://discourse.joplinapp.org/). This issue may be closed if no further activity occurs. You may comment on the issue and I will leave it open. Thank you for your contributions.

Don't close ...

**Comment by nomoretorgo** [comment]
Getting same error.  syncing file system by means of google drive.   Joplin v. 2.9.17

**Comment by all4fun** [comment]
Getting same error. syncing file system by means of minio s3 service. Joplin v. 2.9.17

**Comment by pjsgsy** [comment]
Same issue here. Totally new user trying to setup sync. Webdav all works, but after adding a few docs and syncing, android and windows clients (2.11.11) are throwing this error on sync

Created remote items: 8.
Completed: 26/08/2023 08:35 (468ms)
Last error: Error: Got metadata for path but could not fetch content: 42a1cc8155be4697a68e4e3b6fa2c56b.md

I have checked the server folder and that file is in fact there, in the root webdav folder.

**Comment by pjsgsy** [comment]
Further info - I did a 're-upload local data to sync target' on the windows client. This cleared the error and the android client also syncs. However, on the android client, none of the synced notebooks actually show up, even though it says in the sync log it synced all the items. I have encryption on, btw, in case that is relevant. I see the initial posted perhaps did, too.

Same in reverse, too. Create a 'test' notebook on the android client. Sync it. Sync with the desktop client. It says 1 new local item created. Notebook does not appear in list of notebooks! Whilst each device is syncing, it is not seeing each others notes...

So, disabled encryption both ends. Re-upload sync to server on windows client. Try all same again. Still same. Note a great start!
