### ISSUE TITLE
Error sync pCloud / webdav (Platform Windows and Macbook) 

### ISSUE THREAD

**Issue by claudio-tacchini** [laurent22/joplin#6648]
I'm having problems synchronizing data with pcloud using webdav on both my macbook and windows notebooks after updating to a new version. The error message report that is an authentication error or similar, but testing the connection under Options -> synchronisation page it says that webdav configuration is working. 

## Environment

Joplin version: 2.8.8 (prod, win32). Sync version: 3. Profile version: 41. Keychain supported : Yes. Revision: c2a6a13
Platform: Windows 10Pro 64Bit

AND

Joplin 2.8.8 (prod, darwin)

Client ID: fafbeee892f947178b67c4533725cc98
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: c2a6a13

FULL Error message:

Error
The sync target could not be upgraded due to an error. For support, please copy the complete content of this page and paste it in the forum: https://discourse.joplinapp.org/

The full error was:

GET info.json: Unknown error 2 (403): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>403 Forbidden</title> </head><body> <h1>Forbidden</h1> <p>You don't have permission to access this resource.</p> <hr> <address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address> </body></html>

Error: GET info.json: Unknown error 2 (403): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address>
</body></html>

    at newError (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:414:11)
    at WebDavApi.exec (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:444:10)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async FileApiDriverWebDav.get (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api-driver-webdav.js:164:21)

LOG:
2022-07-06 09:27:12: Synchronizer: "Indexing resources..."
2022-07-06 09:27:12: "ResourceService::indexNoteResources: Start"
2022-07-06 09:27:14: "ResourceService::indexNoteResources: Completed"
2022-07-06 09:27:14: RevisionService: "maintenance: Starting..."
2022-07-06 09:27:14: RevisionService: "maintenance: Service is enabled"
2022-07-06 09:27:14: RevisionService: "collectRevisions: Created revisions for 0 notes"
2022-07-06 09:27:14: RevisionService: "maintenance: Done in 350ms"
2022-07-06 09:27:15: checkForUpdates: "Starting..."
2022-07-06 09:27:15: checkForUpdates: "Checking with options {"includePreReleases":false}"
2022-07-06 09:27:15: checkForUpdates: "Current version: 2.8.8"
2022-07-06 09:27:15: checkForUpdates: "Latest version: 2.8.8"
2022-07-06 09:27:15: checkForUpdates: "Is Pre-release:", "false"
2022-07-06 09:27:15: checkForUpdates: "Done."
2022-07-06 09:27:20: "SearchEngine: Updating FTS table..."
2022-07-06 09:27:20: "SearchEngine: Updated FTS table in 3ms. Inserted: 0. Deleted: 0"
2022-07-06 09:27:34: Synchronizer: "Error: GET info.json: Unknown error 2 (403): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address>
</body></html>

Code: 403
Error: GET info.json: Unknown error 2 (403): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address>
</body></html>

    at newError (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:414:11)
    at WebDavApi.exec (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:444:10)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async FileApiDriverWebDav.get (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api-driver-webdav.js:164:21)"
2022-07-06 09:27:34: Synchronizer: "Req 09:27:34: GET https://ewebdav.pcloud.com/joplin/info.json {"headers":{"Authorization":"********","Cache-Control":"no-store","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}"
2022-07-06 09:27:34: Synchronizer: "Res 09:27:34: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address>
</body></html>
"
2022-07-06 09:27:34: Synchronizer: "Sync: finished: Synchronisation finished [1657092431952]"
2022-07-06 09:27:35: Synchronizer: "Operations completed: "
2022-07-06 09:27:35: Synchronizer: "Total folders: 40"
2022-07-06 09:27:35: Synchronizer: "Total notes: 186"
2022-07-06 09:27:35: Synchronizer: "Total resources: 57"
2022-07-06 09:27:35: Synchronizer: "There was some errors:"
2022-07-06 09:27:35: Synchronizer: "Error: GET info.json: Unknown error 2 (403): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address>
</body></html>

Code: 403
Error: GET info.json: Unknown error 2 (403): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address>
</body></html>

    at newError (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:414:11)
    at WebDavApi.exec (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:444:10)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async FileApiDriverWebDav.get (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api-driver-webdav.js:164:21)"
2022-07-06 09:27:35: "Updating all notifications..."
2022-07-06 09:27:35: "Garbage collecting alarms..."
2022-07-06 09:27:36: "DecryptionWorker: cannot start because no master key is currently loaded."
2022-07-06 09:27:40: "ResourceService::indexNoteResources: Start"
2022-07-06 09:27:40: "ResourceService::indexNoteResources: Completed"
2022-07-06 09:27:40: "ResourceService::deleteOrphanResources:", "[]"
2022-07-06 09:30:30: "Preparing scheduled sync"
2022-07-06 09:30:30: "Starting scheduled sync"
2022-07-06 09:30:30: Synchronizer: "Sync: starting: Starting synchronisation to target 6... supportsAccurateTimestamp = false; supportsMultiPut = false [1657092630826]"
2022-07-06 09:30:30: Synchronizer: "Indexing resources..."
2022-07-06 09:30:30: "ResourceService::indexNoteResources: Start"
2022-07-06 09:30:31: "ResourceService::indexNoteResources: Completed"
2022-07-06 09:30:51: Synchronizer: "Error: GET info.json: Unknown error 2 (403): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address>
</body></html>

Code: 403
Error: GET info.json: Unknown error 2 (403): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address>
</body></html>

    at newError (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:414:11)
    at WebDavApi.exec (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:444:10)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async FileApiDriverWebDav.get (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api-driver-webdav.js:164:21)"
2022-07-06 09:30:51: Synchronizer: "Req 09:27:34: GET https://ewebdav.pcloud.com/joplin/info.json {"headers":{"Authorization":"********","Cache-Control":"no-store","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}"
2022-07-06 09:30:51: Synchronizer: "Res 09:27:34: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address>
</body></html>
"
2022-07-06 09:30:51: Synchronizer: "Req 09:30:51: GET https://ewebdav.pcloud.com/joplin/info.json {"headers":{"Authorization":"********","Cache-Control":"no-store","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}"
2022-07-06 09:30:51: Synchronizer: "Res 09:30:51: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address>
</body></html>
"
2022-07-06 09:30:51: Synchronizer: "Sync: finished: Synchronisation finished [1657092630826]"
2022-07-06 09:30:51: Synchronizer: "Operations completed: "
2022-07-06 09:30:52: Synchronizer: "Total folders: 40"
2022-07-06 09:30:52: Synchronizer: "Total notes: 186"
2022-07-06 09:30:52: Synchronizer: "Total resources: 57"
2022-07-06 09:30:52: Synchronizer: "There was some errors:"
2022-07-06 09:30:52: Synchronizer: "Error: GET info.json: Unknown error 2 (403): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address>
</body></html>

Code: 403
Error: GET info.json: Unknown error 2 (403): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address>
</body></html>

    at newError (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:414:11)
    at WebDavApi.exec (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:444:10)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async FileApiDriverWebDav.get (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api-driver-webdav.js:164:21)"
2022-07-06 09:30:53: "DecryptionWorker: cannot start because no master key is currently loaded."
2022-07-06 09:31:10: "Preparing scheduled sync"
2022-07-06 09:31:10: "Starting scheduled sync"
2022-07-06 09:31:10: Synchronizer: "Sync: starting: Starting synchronisation to target 6... supportsAccurateTimestamp = false; supportsMultiPut = false [1657092670443]"
2022-07-06 09:31:10: Synchronizer: "Indexing resources..."
2022-07-06 09:31:10: "ResourceService::indexNoteResources: Start"
2022-07-06 09:31:10: "ResourceService::indexNoteResources: Completed"
2022-07-06 09:31:31: Synchronizer: "Error: GET info.json: Unknown error 2 (403): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address>
</body></html>

Code: 403
Error: GET info.json: Unknown error 2 (403): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address>
</body></html>

    at newError (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:414:11)
    at WebDavApi.exec (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:444:10)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async FileApiDriverWebDav.get (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api-driver-webdav.js:164:21)"
2022-07-06 09:31:31: Synchronizer: "Req 09:27:34: GET https://ewebdav.pcloud.com/joplin/info.json {"headers":{"Authorization":"********","Cache-Control":"no-store","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}"
2022-07-06 09:31:31: Synchronizer: "Res 09:27:34: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address>
</body></html>
"
2022-07-06 09:31:31: Synchronizer: "Req 09:30:51: GET https://ewebdav.pcloud.com/joplin/info.json {"headers":{"Authorization":"********","Cache-Control":"no-store","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}"
2022-07-06 09:31:31: Synchronizer: "Res 09:30:51: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address>
</body></html>
"
2022-07-06 09:31:31: Synchronizer: "Req 09:31:31: GET https://ewebdav.pcloud.com/joplin/info.json {"headers":{"Authorization":"********","Cache-Control":"no-store","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}"
2022-07-06 09:31:31: Synchronizer: "Res 09:31:31: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address>
</body></html>
"
2022-07-06 09:31:31: Synchronizer: "Sync: finished: Synchronisation finished [1657092670443]"
2022-07-06 09:31:31: Synchronizer: "Operations completed: "
2022-07-06 09:31:31: Synchronizer: "Total folders: 40"
2022-07-06 09:31:31: Synchronizer: "Total notes: 186"
2022-07-06 09:31:31: Synchronizer: "Total resources: 57"
2022-07-06 09:31:31: Synchronizer: "There was some errors:"
2022-07-06 09:31:31: Synchronizer: "Error: GET info.json: Unknown error 2 (403): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address>
</body></html>

Code: 403
Error: GET info.json: Unknown error 2 (403): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address>
</body></html>

    at newError (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:414:11)
    at WebDavApi.exec (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:444:10)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async FileApiDriverWebDav.get (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api-driver-webdav.js:164:21)"
2022-07-06 09:31:32: "DecryptionWorker: cannot start because no master key is currently loaded."
2022-07-06 09:36:31: "Running background sync on timer..."
2022-07-06 09:36:31: "Preparing scheduled sync"
2022-07-06 09:36:31: "Starting scheduled sync"
2022-07-06 09:36:31: Synchronizer: "Sync: starting: Starting synchronisation to target 6... supportsAccurateTimestamp = false; supportsMultiPut = false [1657092991193]"
2022-07-06 09:36:31: Synchronizer: "Indexing resources..."
2022-07-06 09:36:31: "ResourceService::indexNoteResources: Start"
2022-07-06 09:36:31: "ResourceService::indexNoteResources: Completed"
2022-07-06 09:36:51: Synchronizer: "Error: GET info.json: Unknown error 2 (403): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address>
</body></html>

Code: 403
Error: GET info.json: Unknown error 2 (403): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address>
</body></html>

    at newError (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:414:11)
    at WebDavApi.exec (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:444:10)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async FileApiDriverWebDav.get (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api-driver-webdav.js:164:21)"
2022-07-06 09:36:51: Synchronizer: "Req 09:27:34: GET https://ewebdav.pcloud.com/joplin/info.json {"headers":{"Authorization":"********","Cache-Control":"no-store","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}"
2022-07-06 09:36:51: Synchronizer: "Res 09:27:34: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address>
</body></html>
"
2022-07-06 09:36:51: Synchronizer: "Req 09:30:51: GET https://ewebdav.pcloud.com/joplin/info.json {"headers":{"Authorization":"********","Cache-Control":"no-store","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}"
2022-07-06 09:36:51: Synchronizer: "Res 09:30:51: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address>
</body></html>
"
2022-07-06 09:36:51: Synchronizer: "Req 09:31:31: GET https://ewebdav.pcloud.com/joplin/info.json {"headers":{"Authorization":"********","Cache-Control":"no-store","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}"
2022-07-06 09:36:51: Synchronizer: "Res 09:31:31: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address>
</body></html>
"
2022-07-06 09:36:51: Synchronizer: "Req 09:36:51: GET https://ewebdav.pcloud.com/joplin/info.json {"headers":{"Authorization":"********","Cache-Control":"no-store","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}"
2022-07-06 09:36:51: Synchronizer: "Res 09:36:51: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address>
</body></html>
"
2022-07-06 09:36:51: Synchronizer: "Sync: finished: Synchronisation finished [1657092991193]"
2022-07-06 09:36:51: Synchronizer: "Operations completed: "
2022-07-06 09:36:51: Synchronizer: "Total folders: 40"
2022-07-06 09:36:51: Synchronizer: "Total notes: 186"
2022-07-06 09:36:51: Synchronizer: "Total resources: 57"
2022-07-06 09:36:51: Synchronizer: "There was some errors:"
2022-07-06 09:36:51: Synchronizer: "Error: GET info.json: Unknown error 2 (403): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address>
</body></html>

Code: 403
Error: GET info.json: Unknown error 2 (403): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address>
</body></html>

    at newError (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:414:11)
    at WebDavApi.exec (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:444:10)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async FileApiDriverWebDav.get (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api-driver-webdav.js:164:21)"
2022-07-06 09:36:52: "DecryptionWorker: cannot start because no master key is currently loaded."
2022-07-06 09:37:10: RevisionService: "maintenance: Starting..."
2022-07-06 09:37:10: RevisionService: "maintenance: Service is enabled"
2022-07-06 09:37:10: RevisionService: "collectRevisions: Created revisions for 0 notes"
2022-07-06 09:37:10: RevisionService: "maintenance: Done in 140ms"
2022-07-06 09:41:51: "Running background sync on timer..."
2022-07-06 09:41:51: "Preparing scheduled sync"
2022-07-06 09:41:51: "Starting scheduled sync"
2022-07-06 09:41:51: Synchronizer: "Sync: starting: Starting synchronisation to target 6... supportsAccurateTimestamp = false; supportsMultiPut = false [1657093311812]"
2022-07-06 09:41:51: Synchronizer: "Indexing resources..."
2022-07-06 09:41:51: "ResourceService::indexNoteResources: Start"
2022-07-06 09:41:52: "ResourceService::indexNoteResources: Completed"
2022-07-06 09:42:12: Synchronizer: "Error: GET info.json: Unknown error 2 (403): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address>
</body></html>

**Comment by Daeraxa** [comment]
pCloud webDAV is not supported - https://joplinapp.org/faq/#the-following-webdav-hosts-are-not-supported.
Also see https://discourse.joplinapp.org/t/the-sync-target-needs-to-be-upgraded/26261/9

**Comment by claudio-tacchini** [comment]
Thank you for your replay.
I was using Joplin with my premium pcloud account and I appreciated a lot this application.
Is there a way to keep using a previous version? Or am I forced to update to the latest version?

**Comment by Daeraxa** [comment]
It isn't, or shouldn't be related to Joplin version as such, pCloud seem to have a problematic WebDAV implementation which isn't seen with other providers.

If it does work with a previous Joplin version then you can of course keep using it but if you have already upgraded you may need to start over on a fresh install. You can of course export and import your notes if you needed to do this.
