### ISSUE TITLE
Client 2.8.8 cannot sync with latest available docker server image 2.7.4-beta

### ISSUE THREAD

**Issue by sebthom** [laurent22/joplin#6656]
I guess the image at https://hub.docker.com/r/joplin/server/tags needs to be rebuild. The latest available is 2.7.4-beta

## Environment

Joplin version: Server: 2.7.4-beta  Client: 2.8.8
Platform:  Server: Linux/Docker  Client: Windows and Android OS
OS specifics: Windows 10, Android 12

## Steps to reproduce

1. Starting the app and click synchronize
2. The error pops up in the client: 
```
Last error: Error: Error 412 Precondition Failed: <!doctype html> <html> <head> <title>Joplin Server - Error</title> <meta charset="utf-8"> <meta name="viewport" content="width=device-width, initial-scale=1" /> <link rel="stylesheet" href="https://myserver/css/bulma.min.css" crossorigin="anonymous"> <!-- <link rel="stylesheet" href="https://myserver/css/bulma-prefers-dark.min.css" crossorigin="anonymous"> --> <link rel="stylesheet" href="https://myserver/css/main.css" cr
   ```

## Describe what you expected to happen

Sync is successful.

## Logfile

```
2022-07-10 19:52:42: Synchronizer: "There was some errors:"
2022-07-10 19:52:42: Synchronizer: "Error: Error 412 Precondition Failed: <!doctype html>
<html>
<head>
	<title>Joplin Server - Error</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<link rel="stylesheet" href="https://myserver/css/bulma.min.css" crossorigin="anonymous">
		<!-- <link rel="stylesheet" href="https://myserver/css/bulma-prefers-dark.min.css" crossorigin="anonymous"> -->
	<link rel="stylesheet" href="https://myserver/css/main.css" crossorigin="anonymous">
	<link rel="stylesheet" href="https://myserver/css/fontawesome/css/all.min.css" crossorigin="anonymous">
	<script src="https://myserver/js/jquery.min.js"></script>
	<script src="https://myserver/js/main.js"></script>
</head>
	<body class="page-error">
		<main class="main">
			<div class="container">

				<script>
					onDocumentReady(function() {
						const buttons = document.getElementsByClassName('close-notification-button');
						
						for (const button of buttons) {
							button.addEventListener(
Code: 412
Error: Error 412 Precondition Failed: <!doctype html>
<html>
<head>
	<title>Joplin Server - Error</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<link rel="stylesheet" href="https://myserver/css/bulma.min.css" crossorigin="anonymous">
		<!-- <link rel="stylesheet" href="https://myserver/css/bulma-prefers-dark.min.css" crossorigin="anonymous"> -->
	<link rel="stylesheet" href="https://myserver/css/main.css" crossorigin="anonymous">
	<link rel="stylesheet" href="https:/myserver/css/fontawesome/css/all.min.css" crossorigin="anonymous">
	<script src="https://myserver/js/jquery.min.js"></script>
	<script src="https://myserver/js/main.js"></script>
</head>
	<body class="page-error">
		<main class="main">
			<div class="container">

				<script>
					onDocumentReady(function() {
						const buttons = document.getElementsByClassName('close-notification-button');
						
						for (const button of buttons) {
							button.addEventListener(
    at newError (C:\apps\office\joplin\resources\app.asar\node_modules\@joplin\lib\JoplinServerApi.js:192:28)
    at JoplinServerApi.<anonymous> (C:\apps\office\joplin\resources\app.asar\node_modules\@joplin\lib\JoplinServerApi.js:232:27)
    at Generator.throw (<anonymous>)
    at rejected (C:\apps\office\joplin\resources\app.asar\node_modules\@joplin\lib\JoplinServerApi.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
2022-07-11 00:52:44: "DecryptionWorker: cannot start because no master key is currently loaded."
```

**Comment by sebthom** [comment]
The issue is still present.

**Comment by Derkades** [comment]
Desktop client 2.8.8 syncs fine with joplin server 2.7-beta for me. But yes, an update would be highly appreciated. It's a bit scary to have software exposed to the internet that hasn't received an update in over half a year.

**Comment by Derkades** [comment]
No image updates have been uploaded to docker hub

**Comment by Maxattax97** [comment]
To anyone who might stumble across this ticket from the internet, I got the same error because my client was Joplin 3.x but the Docker server was 2.x... I didn't realize that there was a 3.x tag, the docs for the docker image are a bit out of date.
