### ISSUE TITLE
DELETE 405 Method Not Allowed

### ISSUE THREAD

**Issue by magnusmanske** [laurent22/joplin#6675]
## Environment

Joplin version: 2.8.8 (darwin)
Platform: MacOS
OS specifics: Catalina

## Steps to reproduce

I have Joplin installed on Android and several MacOS machines, and sync via self-hosted webDAV (via Nextcloud, but using webDAV _not_ Nextcloud!). One of these (but not the others) refuses to sync since a few weeks (months?):
```
Deleted remote items: 1.
Completed: 18/07/2022 13:59 (208s)
Last error: Error: DELETE b5af24523c6147aa8d5856a0e89803d5.md: Unknown error 2 (405): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>405 Method Not Allowed</title> </head><body> <h1>Method Not Allowed</h1> <p>The requested method DELETE is not allowed for this URL.</p> </body></html>
```

## Describe what you expected to happen
Successful sync without errors.

## Logfile
Replaced the server with MY_SERVER_NAME
```
2022-07-18 14:05:45: RevisionService: "maintenance: Starting..."
2022-07-18 14:05:45: RevisionService: "maintenance: Service is enabled"
2022-07-18 14:05:45: RevisionService: "collectRevisions: Created revisions for 0 notes"
2022-07-18 14:05:45: RevisionService: "maintenance: Done in 110ms"
2022-07-18 14:05:46: checkForUpdates: "Starting..."
2022-07-18 14:05:46: checkForUpdates: "Checking with options {"includePreReleases":false}"
2022-07-18 14:05:46: checkForUpdates: "Current version: 2.8.8"
2022-07-18 14:05:46: checkForUpdates: "Latest version: 2.8.8"
2022-07-18 14:05:46: checkForUpdates: "Is Pre-release:", "false"
2022-07-18 14:05:46: checkForUpdates: "Done."
2022-07-18 14:05:51: "SearchEngine: Updating FTS table..."
2022-07-18 14:05:51: "SearchEngine: Updated FTS table in 1ms. Inserted: 0. Deleted: 0"
2022-07-18 14:06:11: "ResourceService::indexNoteResources: Start"
2022-07-18 14:06:11: "ResourceService::indexNoteResources: Completed"
2022-07-18 14:06:11: "ResourceService::deleteOrphanResources:", "[]"
2022-07-18 14:06:15: Synchronizer: "Sync: deleteRemote: local has been deleted: (Remote b5af24523c6147aa8d5856a0e89803d5)"
2022-07-18 14:08:48: Synchronizer: "Error: DELETE b5af24523c6147aa8d5856a0e89803d5.md: Unknown error 2 (405): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method DELETE is not allowed for this URL.</p>
</body></html>

Code: 405
Error: DELETE b5af24523c6147aa8d5856a0e89803d5.md: Unknown error 2 (405): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method DELETE is not allowed for this URL.</p>
</body></html>

    at newError (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:414:11)
    at WebDavApi.exec (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:444:10)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async FileApiDriverWebDav.delete (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api-driver-webdav.js:206:4)"
2022-07-18 14:08:48: Synchronizer: "Req 14:06:15: PUT https://MY_SERVER_NAME/nextcloud/remote.php/webdav/Joplin/locks/1_1_a5b6f70ec9eb49b59956e32f3189df2e.json {"headers":{"Authorization":"********","Content-Type":"text/plain","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-38432","User-Agent":"Joplin/1.0","Content-Length":"109"},"body":"{\"id\":null,\"type\":1,\"clientType\":1,\"clientId\":\"a5b6f70ec9eb49b59956e32f3189df2e\",\"updatedTime\":1658149518000}","ignoreTlsErrors":true,"timeout":120000,"maxRetry":0}"
2022-07-18 14:08:48: Synchronizer: "Res 14:06:15: "
2022-07-18 14:08:48: Synchronizer: "Req 14:06:48: DELETE https://MY_SERVER_NAME/nextcloud/remote.php/webdav/Joplin/b5af24523c6147aa8d5856a0e89803d5.md {"headers":{"Authorization":"********","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-22483","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":true,"timeout":120000,"maxRetry":0}"
2022-07-18 14:08:48: Synchronizer: "Res 14:06:48: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method DELETE is not allowed for this URL.</p>
</body></html>
"
2022-07-18 14:08:48: Synchronizer: "Req 14:07:24: DELETE https://MY_SERVER_NAME/nextcloud/remote.php/webdav/Joplin/b5af24523c6147aa8d5856a0e89803d5.md {"headers":{"Authorization":"********","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-59249","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":true,"timeout":120000,"maxRetry":0}"
2022-07-18 14:08:48: Synchronizer: "Res 14:07:24: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method DELETE is not allowed for this URL.</p>
</body></html>
"
2022-07-18 14:08:48: Synchronizer: "Req 14:07:25: PROPFIND https://MY_SERVER_NAME/nextcloud/remote.php/webdav/Joplin/locks/ {"headers":{"Depth":1,"Authorization":"********","Content-Type":"text/xml","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-89964","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","ignoreTlsErrors":true,"timeout":120000,"maxRetry":0}"
2022-07-18 14:08:48: Synchronizer: "Res 14:07:25: <?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns"><d:response><d:href>/nextcloud/remote.php/webdav/Joplin/locks/</d:href><d:propstat><d:prop><d:getlastmodified>Mon, 18 Jul 2022 13:06:15 GMT</d:getlastmodified><d:resourcetype><d:collection/></d:resourcetype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/nextcloud/remote.php/webdav/Joplin/locks/1_1_a5b6f70ec9eb49b59956e32f3189df2e.json</d:href><d:propstat><d:prop><d:getlastmodified>Mon, 18 Jul 2022 13:06:15 GMT</d:getlastmodified><d:resourcetype/></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>
"
2022-07-18 14:08:48: Synchronizer: "Req 14:07:26: PROPFIND https://MY_SERVER_NAME/nextcloud/remote.php/webdav/Joplin/locks/ {"headers":{"Depth":1,"Authorization":"********","Content-Type":"text/xml","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-99011","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","ignoreTlsErrors":true,"timeout":120000,"maxRetry":0}"
2022-07-18 14:08:48: Synchronizer: "Res 14:07:26: <?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns"><d:response><d:href>/nextcloud/remote.php/webdav/Joplin/locks/</d:href><d:propstat><d:prop><d:getlastmodified>Mon, 18 Jul 2022 13:06:15 GMT</d:getlastmodified><d:resourcetype><d:collection/></d:resourcetype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/nextcloud/remote.php/webdav/Joplin/locks/1_1_a5b6f70ec9eb49b59956e32f3189df2e.json</d:href><d:propstat><d:prop><d:getlastmodified>Mon, 18 Jul 2022 13:06:15 GMT</d:getlastmodified><d:resourcetype/></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>
"
2022-07-18 14:08:48: Synchronizer: "Req 14:07:26: PUT https://MY_SERVER_NAME/nextcloud/remote.php/webdav/Joplin/locks/1_1_a5b6f70ec9eb49b59956e32f3189df2e.json {"headers":{"Authorization":"********","Content-Type":"text/plain","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-3106","User-Agent":"Joplin/1.0","Content-Length":"109"},"body":"{\"id\":null,\"type\":1,\"clientType\":1,\"clientId\":\"a5b6f70ec9eb49b59956e32f3189df2e\",\"updatedTime\":1658149575000}","ignoreTlsErrors":true,"timeout":120000,"maxRetry":0}"
2022-07-18 14:08:48: Synchronizer: "Res 14:07:26: "
2022-07-18 14:08:48: Synchronizer: "Req 14:08:04: DELETE https://MY_SERVER_NAME/nextcloud/remote.php/webdav/Joplin/b5af24523c6147aa8d5856a0e89803d5.md {"headers":{"Authorization":"********","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-49987","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":true,"timeout":120000,"maxRetry":0}"
2022-07-18 14:08:48: Synchronizer: "Res 14:08:04: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method DELETE is not allowed for this URL.</p>
</body></html>
"
2022-07-18 14:08:48: Synchronizer: "Req 14:08:46: PROPFIND https://MY_SERVER_NAME/nextcloud/remote.php/webdav/Joplin/locks/ {"headers":{"Depth":1,"Authorization":"********","Content-Type":"text/xml","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-40005","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","ignoreTlsErrors":true,"timeout":120000,"maxRetry":0}"
2022-07-18 14:08:48: Synchronizer: "Res 14:08:46: <?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns"><d:response><d:href>/nextcloud/remote.php/webdav/Joplin/locks/</d:href><d:propstat><d:prop><d:getlastmodified>Mon, 18 Jul 2022 13:07:26 GMT</d:getlastmodified><d:resourcetype><d:collection/></d:resourcetype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/nextcloud/remote.php/webdav/Joplin/locks/1_1_a5b6f70ec9eb49b59956e32f3189df2e.json</d:href><d:propstat><d:prop><d:getlastmodified>Mon, 18 Jul 2022 13:07:26 GMT</d:getlastmodified><d:resourcetype/></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>
"
2022-07-18 14:08:48: Synchronizer: "Req 14:08:47: DELETE https://MY_SERVER_NAME/nextcloud/remote.php/webdav/Joplin/b5af24523c6147aa8d5856a0e89803d5.md {"headers":{"Authorization":"********","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-94116","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":true,"timeout":120000,"maxRetry":0}"
2022-07-18 14:08:48: Synchronizer: "Res 14:08:47: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method DELETE is not allowed for this URL.</p>
</body></html>
"
2022-07-18 14:08:48: Synchronizer: "Req 14:08:47: PROPFIND https://MY_SERVER_NAME/nextcloud/remote.php/webdav/Joplin/locks/ {"headers":{"Depth":1,"Authorization":"********","Content-Type":"text/xml","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-66970","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","ignoreTlsErrors":true,"timeout":120000,"maxRetry":0}"
2022-07-18 14:08:48: Synchronizer: "Res 14:08:47: <?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns"><d:response><d:href>/nextcloud/remote.php/webdav/Joplin/locks/</d:href><d:propstat><d:prop><d:getlastmodified>Mon, 18 Jul 2022 13:07:26 GMT</d:getlastmodified><d:resourcetype><d:collection/></d:resourcetype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/nextcloud/remote.php/webdav/Joplin/locks/1_1_a5b6f70ec9eb49b59956e32f3189df2e.json</d:href><d:propstat><d:prop><d:getlastmodified>Mon, 18 Jul 2022 13:07:26 GMT</d:getlastmodified><d:resourcetype/></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>
"
2022-07-18 14:08:48: Synchronizer: "Req 14:08:48: PROPFIND https://MY_SERVER_NAME/nextcloud/remote.php/webdav/Joplin/locks/ {"headers":{"Depth":1,"Authorization":"********","Content-Type":"text/xml","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-51152","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","ignoreTlsErrors":true,"timeout":120000,"maxRetry":0}"
2022-07-18 14:08:48: Synchronizer: "Res 14:08:48: <?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns"><d:response><d:href>/nextcloud/remote.php/webdav/Joplin/locks/</d:href><d:propstat><d:prop><d:getlastmodified>Mon, 18 Jul 2022 13:07:26 GMT</d:getlastmodified><d:resourcetype><d:collection/></d:resourcetype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/nextcloud/remote.php/webdav/Joplin/locks/1_1_a5b6f70ec9eb49b59956e32f3189df2e.json</d:href><d:propstat><d:prop><d:getlastmodified>Mon, 18 Jul 2022 13:07:26 GMT</d:getlastmodified><d:resourcetype/></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>
"
2022-07-18 14:09:20: Synchronizer: "Sync: finished: Synchronisation finished [1658149542450]"
2022-07-18 14:09:20: Synchronizer: "Operations completed: "
2022-07-18 14:09:20: Synchronizer: "deleteRemote: 1"
2022-07-18 14:09:20: Synchronizer: "Total folders: 33"
2022-07-18 14:09:20: Synchronizer: "Total notes: 676"
2022-07-18 14:09:20: Synchronizer: "Total resources: 11"
2022-07-18 14:09:20: Synchronizer: "There was some errors:"
2022-07-18 14:09:20: Synchronizer: "Error: DELETE b5af24523c6147aa8d5856a0e89803d5.md: Unknown error 2 (405): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method DELETE is not allowed for this URL.</p>
</body></html>

Code: 405
Error: DELETE b5af24523c6147aa8d5856a0e89803d5.md: Unknown error 2 (405): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method DELETE is not allowed for this URL.</p>
</body></html>

    at newError (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:414:11)
    at WebDavApi.exec (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:444:10)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async FileApiDriverWebDav.delete (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api-driver-webdav.js:206:4)"
2022-07-18 14:09:20: "Updating all notifications..."
2022-07-18 14:09:20: "Garbage collecting alarms..."
2022-07-18 14:09:21: "DecryptionWorker: starting decryption..."
2022-07-18 14:09:21: "DecryptionWorker: completed decryption."
```

**Comment by magnusmanske** [comment]
It appears the file `b5af24523c6147aa8d5856a0e89803d5.md` was already deleted, and Joplin tries to delete it again, which causes the error. I have manually created a blank file of that name and ran the sync, and it failed again but with another file name it could not delete. Now working my way through these but it's a pain, this should be handled better.

**Comment by JackGruber** [comment]
The problem ist that your nexcloud reports a error `405`, the correct response code is `404` for a not found file. 
A error 405 means that the DELETE command is not allowed.

You can check this with `curl`

```
curl -X DELETE https://<URL>/locks/test.md --user <USER>:<PASSWORD>
```

**Comment by magnusmanske** [comment]
That `curl` command will delete an existing file, and silently close for a non-existing file. It does not appear to cause a `405` error. Also, I have two other Joplin installations on different Macs (same Joplin version and setup) that work just fine.

I believe sync just didn't run for quite a while on this particular machine, maybe because of a stale lock file (?).

Can I skip the DELETE commands somehow? I have some new notes in this one I'd like to upload, otherwise I'd just nuke it.

**Comment by magnusmanske** [comment]
I found a workaround:
1. Find the `database.sqlite` file
2. `sqlite3 database.sqlite`
3. `select distinct item_id from deleted_items;`
4. For each `item_id`, run `touch item_id.md` in the Nextcloud Joplin directory
That will Joplin delete the files it wants. Afterwards, you can celan up 0-byte `.md` files created today...
