### ISSUE TITLE
Android: Building from source: Still unable to sync with filesystem

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#6779]
# Summary
![Synchronize: Permission error. Does not have permission MANAGE_DOCUMENTS.](https://user-images.githubusercontent.com/46334387/186336385-0a4608bc-48c7-4346-bc4f-2e962d09e1a9.png)
![](https://user-images.githubusercontent.com/46334387/186337505-58cbf819-c2fe-43d7-8eca-5eeebba4f163.png)

# Issue
## Environment

Joplin version: a5e6491cda3548537d5d032aa63e7e8bc34eceac
Platform: Android 12
OS specifics: Permissions granted: 
![image](https://user-images.githubusercontent.com/46334387/186333945-903b6314-a979-49cf-8780-11f4dd52901f.png)
![image](https://user-images.githubusercontent.com/46334387/186333972-233f5143-1743-49d8-bdfa-74ddfe8119a6.png)

There is no option to grant additional filesystem permissions

## Steps to reproduce

1. Open "settings"
2. Turn on file system sync
3. Select a directory with "directory to synchronize with (absolute path)" input
4. Press save
6. Close settings
7. Press "synchronize"

## Describe what you expected to happen
Joplin should have permissions required to sync with a given directory

## Logfile

<details><summary>Show</summary>

```

 LOG  Running "Joplin" with {"rootTag":21}
 INFO  22:25:51: ====================================
 INFO  22:25:51: Starting application net.cozic.joplin-mobile v2.9.1 (dev)
 INFO  22:25:51: Database was open successfully
 INFO  22:25:51: Checking for database schema update...
 INFO  22:25:51: Current database version {"table_fields_version": 41, "version": 41}
 INFO  22:25:51: Upgrading database from version 41
 INFO  22:25:51: New version: 41. Previously recorded version: 41
 INFO  22:25:51: Database is ready.
 INFO  22:25:51: Loading settings...
 INFO  22:25:51: KeychainService: checking if keychain supported
 INFO  22:25:51: KeychainService: check was already done - skipping. Supported: 0
 LOG  22:25:51: Setting up recurrent sync with interval 300
 INFO  22:25:51: Recurrent sync operation DISABLED!!!
 INFO  22:25:51: e2ee/utils: Trying to load 0 master keys...
 INFO  22:25:51: e2ee/utils: Loaded master keys: 0
 INFO  22:25:51: e2ee/utils: Master password is not set - trying to get it from the active master key...
 LOG  22:25:51: Scheduling sync operation... 10000
 INFO  22:25:51: models/Setting: Applying default migrations...
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
 INFO  22:25:51: PluginAssetsLoader: Assets are up to date. Hash: ea13a22d0df59339b671f6b5700e2914
 INFO  22:25:51: Sync target: 2
 INFO  22:25:51: e2ee/utils: Trying to load 0 master keys...
 INFO  22:25:51: e2ee/utils: Loaded master keys: 0
 INFO  22:25:51: Loading folders...
 LOG  22:25:51: Setting up recurrent sync with interval 300
 INFO  22:25:51: Recurrent sync operation DISABLED!!!
 INFO  22:25:51: ResourceFetcher: Auto-add resources: Mode: always
 LOG  22:25:51: Scheduling sync operation... 1000
 INFO  22:25:51: RevisionService: runInBackground: Starting background service with revision collection interval 30000
 INFO  RSA Tests: Running integration tests...
 INFO  RSA Tests: Decrypting and encrypting using desktop data...
 INFO  22:25:51: ResourceFetcher: Auto-added resources: 0
 INFO  RSA Tests: Data could be decrypted
 INFO  RSA Tests: Data could be encrypted then decrypted
 INFO  RSA Tests: Decrypting and encrypting using mobile data...
 INFO  RSA Tests: Data could be decrypted
 INFO  RSA Tests: Data could be encrypted then decrypted
 INFO  RSA Tests: Decrypting and encrypting using local data...
 INFO  RSA Tests: Data could be decrypted
 INFO  RSA Tests: Data could be encrypted then decrypted
 INFO  22:25:51: Application initialized
 WARN  MenuContext is deprecated and it might be removed in future releases, use MenuProvider instead. 
DeprecatedComponent@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:476708:28
RCTView
View
AnimatedComponent@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:68669:38
AnimatedComponentWrapper
RCTView
View
SideMenuComponent@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:502496:78
Connect(SideMenuComponent)@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:472196:26
RCTView
View
AppComponent@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:116297:79
Connect(AppComponent)@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:472196:26
Provider@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:471973:24
Root@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:116722:79
RCTView
View
RCTView
View
AppContainer@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:76851:36
Joplin(RootComponent)@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:83244:28
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
 INFO  22:25:52: DecryptionWorker: cannot start because no master key is currently loaded.
 INFO  22:25:52: Preparing scheduled sync
 INFO  22:25:52: Could not run background sync:
 INFO  22:25:52: [Error: Error: Directory could not be created. Path: ]
 LOG  22:25:52: Setting up recurrent sync with interval 300
 INFO  22:25:52: Recurrent sync operation DISABLED!!!
 INFO  22:25:52: Updating all notifications...
 INFO  22:25:52: Garbage collecting alarms...
 INFO  22:25:53: DecryptionWorker: cannot start because no master key is currently loaded.
 INFO  22:25:55: RevisionService: maintenance: Starting...
 INFO  22:25:55: RevisionService: maintenance: Service is enabled
 INFO  22:25:55: RevisionService: collectRevisions: Created revisions for 0 notes
 INFO  22:25:55: RevisionService: maintenance: Done in 139ms
 INFO  22:26:01: SearchEngine: Updating FTS table...
 INFO  22:26:01: SearchEngine: Updated FTS table in 7ms. Inserted: 0. Deleted: 0
 INFO  22:26:19: config/lib: Sync settings have been changed - scheduling a sync
 LOG  22:26:19: Scheduling sync operation... 10000
 LOG  22:26:19: models/Setting: Saving settings...
 LOG  22:26:19: models/Setting: Settings have been saved.
 INFO  22:26:21: ResourceService::indexNoteResources: Start
 INFO  22:26:21: RevisionService: maintenance: Starting...
 INFO  22:26:21: RevisionService: maintenance: Service is enabled
 INFO  22:26:21: RevisionService: collectRevisions: Created revisions for 0 notes
 INFO  22:26:21: ResourceService::indexNoteResources: Completed
 INFO  22:26:21: RevisionService: maintenance: Done in 150ms
 INFO  22:26:21: ResourceService::deleteOrphanResources:
 LOG  22:26:23: Scheduling sync operation... 0
 INFO  22:26:23: Preparing scheduled sync
 INFO  22:26:23: Starting scheduled sync
 INFO  22:26:23: Synchronizer: Sync: starting: Starting synchronisation to target 2... supportsAccurateTimestamp = false; supportsMultiPut = false [1661318783422]
 INFO  22:26:23: Synchronizer: Indexing resources...
 INFO  22:26:23: ResourceService::indexNoteResources: Start
 INFO  22:26:23: ResourceService::indexNoteResources: Completed
 LOG  22:26:23: models/Folder: updateFolderShareIds: {"shareUpdateCount": 0, "unshareUpdateCount": 0}
 LOG  22:26:23: models/Folder: updateNoteShareIds: notes to update: 0
 LOG  22:26:23: FileApi: get content://com.android.externalstorage.documents/tree/primary:DCIM/Test/info.json
 LOG  22:26:23: FileApi: get content://com.android.externalstorage.documents/tree/primary:DCIM/Test/.sync/version.txt
 INFO  22:26:23: Synchronizer: Sync target remote info: {"activeMasterKeyId_": {"updatedTime": 0, "value": ""}, "e2ee_": {"updatedTime": 0, "value": false}, "masterKeys_": [], "ppk_": {"updatedTime": 0, "value": null}, "version_": 0}
 INFO  22:26:23: Synchronizer: Sync target is new - setting it up...
 LOG  22:26:23: FileApi: get content://com.android.externalstorage.documents/tree/primary:DCIM/Test/info.json
 LOG  22:26:23: FileApi: get content://com.android.externalstorage.documents/tree/primary:DCIM/Test/.sync/version.txt
 INFO  22:26:23: MigrationHandler: Sync target version is 0 or 1 - creating "locks" and "temp" directory: {"version": 0}
 LOG  22:26:23: FileApi: mkdir content://com.android.externalstorage.documents/tree/primary:DCIM/Test/locks
 LOG  22:26:23: FileApi: mkdir content://com.android.externalstorage.documents/tree/primary:DCIM/Test/temp
 INFO  22:26:23: MigrationHandler: Acquiring exclusive lock
 LOG  22:26:23: FileApi: list content://com.android.externalstorage.documents/tree/primary:DCIM/Test
 LOG  22:26:24: FileApi: put content://com.android.externalstorage.documents/tree/primary:DCIM/Test/temp/timeCheck453786.txt null
 LOG  22:26:24: FileApi: stat content://com.android.externalstorage.documents/tree/primary:DCIM/Test/temp/timeCheck453786.txt
 LOG  22:26:24: FileApi: delete content://com.android.externalstorage.documents/tree/primary:DCIM/Test/temp/timeCheck453786.txt
 LOG  22:26:24: FileApi: put content://com.android.externalstorage.documents/tree/primary:DCIM/Test/locks/2_2_cadc63f9a4154e45bbbade0c456ee155.json null
 LOG  22:26:24: FileApi: list content://com.android.externalstorage.documents/tree/primary:DCIM/Test
 LOG  22:26:24: FileApi: put content://com.android.externalstorage.documents/tree/primary:DCIM/Test/locks/2_2_cadc63f9a4154e45bbbade0c456ee155.json null
 INFO  22:26:24: MigrationHandler: Acquired exclusive lock: {"clientId": "cadc63f9a4154e45bbbade0c456ee155", "clientType": 2, "id": null, "type": 2, "updatedTime": 1661318784000}
 INFO  22:26:24: MigrationHandler: Migrating from version 0 to version 1
 LOG  22:26:24: FileApi: mkdir content://com.android.externalstorage.documents/tree/primary:DCIM/Test/.resource
 LOG  22:26:24: FileApi: mkdir content://com.android.externalstorage.documents/tree/primary:DCIM/Test/.sync
 LOG  22:26:24: FileApi: mkdir content://com.android.externalstorage.documents/tree/primary:DCIM/Test/.lock
 LOG  22:26:24: FileApi: put content://com.android.externalstorage.documents/tree/primary:DCIM/Test/.sync/version.txt null
 LOG  22:26:24: FileApi: put content://com.android.externalstorage.documents/tree/primary:DCIM/Test/info.json null
 INFO  22:26:24: MigrationHandler: Done migrating from version 0 to version 1
 INFO  22:26:24: MigrationHandler: Migrating from version 1 to version 2
 LOG  22:26:24: FileApi: put content://com.android.externalstorage.documents/tree/primary:DCIM/Test/.sync/version.txt null
 LOG  22:26:24: FileApi: put content://com.android.externalstorage.documents/tree/primary:DCIM/Test/.sync/readme.txt null
 LOG  22:26:24: FileApi: mkdir content://com.android.externalstorage.documents/tree/primary:DCIM/Test/locks
 LOG  22:26:24: FileApi: mkdir content://com.android.externalstorage.documents/tree/primary:DCIM/Test/temp
 LOG  22:26:25: FileApi: put content://com.android.externalstorage.documents/tree/primary:DCIM/Test/info.json null
 INFO  22:26:25: MigrationHandler: Done migrating from version 1 to version 2
 INFO  22:26:25: MigrationHandler: Migrating from version 2 to version 3
 LOG  22:26:25: FileApi: put content://com.android.externalstorage.documents/tree/primary:DCIM/Test/info.json null
 INFO  22:26:25: MigrationHandler: Done migrating from version 2 to version 3
 INFO  22:26:25: MigrationHandler: Releasing exclusive lock
 LOG  22:26:25: FileApi: delete content://com.android.externalstorage.documents/tree/primary:DCIM/Test/locks/2_2_cadc63f9a4154e45bbbade0c456ee155.json
 LOG  22:26:25: FileApi: get content://com.android.externalstorage.documents/tree/primary:DCIM/Test/info.json
 INFO  22:26:25: Synchronizer: Sync target is already setup - checking it...
 INFO  22:26:25: Synchronizer: Sync target local info: {"activeMasterKeyId_": {"updatedTime": 0, "value": ""}, "e2ee_": {"updatedTime": 0, "value": false}, "masterKeys_": [], "ppk_": {"updatedTime": 0, "value": null}, "version_": 3}
 LOG  22:26:25: FileApi: list content://com.android.externalstorage.documents/tree/primary:DCIM/Test
 LOG  22:26:25: FileApi: put content://com.android.externalstorage.documents/tree/primary:DCIM/Test/locks/1_2_cadc63f9a4154e45bbbade0c456ee155.json null
 LOG  22:26:25: FileApi: list content://com.android.externalstorage.documents/tree/primary:DCIM/Test
 INFO  22:26:25: Synchronizer: Sync: deleteRemote: local has been deleted: (Remote b1753c0d9f8a42418279c1a37d9a6a30)
 LOG  22:26:25: FileApi: delete content://com.android.externalstorage.documents/tree/primary:DCIM/Test/b1753c0d9f8a42418279c1a37d9a6a30.md
 INFO  22:26:25: Synchronizer: Sync: createRemote: remote does not exist, and local is new and has never been synced: Note: (Local ffc2e0039741427cafe4fcfa92328384)
 LOG  22:26:25: FileApi: put content://com.android.externalstorage.documents/tree/primary:DCIM/Test/ffc2e0039741427cafe4fcfa92328384.md null
 INFO  22:26:25: Synchronizer: Sync: createRemote: remote does not exist, and local is new and has never been synced: Note: (Local 4eb14296b48b4f28ba067c49cc70be33)
 LOG  22:26:25: FileApi: put content://com.android.externalstorage.documents/tree/primary:DCIM/Test/4eb14296b48b4f28ba067c49cc70be33.md null
 INFO  22:26:25: Synchronizer: Sync: createRemote: remote does not exist, and local is new and has never been synced: Note: (Local 3a9eea137b884d9eaf0cf3b396046bc7)
 LOG  22:26:25: FileApi: put content://com.android.externalstorage.documents/tree/primary:DCIM/Test/3a9eea137b884d9eaf0cf3b396046bc7.md null
 INFO  22:26:25: Synchronizer: Sync: createRemote: remote does not exist, and local is new and has never been synced: Note: (Local d171efe0458342bdbdb9fb8d94615791)
 LOG  22:26:26: FileApi: put content://com.android.externalstorage.documents/tree/primary:DCIM/Test/d171efe0458342bdbdb9fb8d94615791.md null
 INFO  22:26:26: Synchronizer: Sync: createRemote: remote does not exist, and local is new and has never been synced: Note: (Local baff65b7f99f47df9cf0b66a80d30f0c)
 LOG  22:26:26: FileApi: put content://com.android.externalstorage.documents/tree/primary:DCIM/Test/baff65b7f99f47df9cf0b66a80d30f0c.md null
 INFO  22:26:26: Synchronizer: Sync: createRemote: remote does not exist, and local is new and has never been synced: Note: (Local d2a59cc750844087903d044514d1cdf0)
 LOG  22:26:26: FileApi: put content://com.android.externalstorage.documents/tree/primary:DCIM/Test/d2a59cc750844087903d044514d1cdf0.md null
 INFO  22:26:26: Synchronizer: Sync: createRemote: remote does not exist, and local is new and has never been synced: Note: (Local 678b5d724a9f44ab98cc2371e748c5fc)
 LOG  22:26:26: FileApi: put content://com.android.externalstorage.documents/tree/primary:DCIM/Test/678b5d724a9f44ab98cc2371e748c5fc.md null
 INFO  22:26:26: Synchronizer: Sync: createRemote: remote does not exist, and local is new and has never been synced: Note: (Local 5d348b7be95c4cfd89cf536101d2a57b)
 LOG  22:26:26: FileApi: put content://com.android.externalstorage.documents/tree/primary:DCIM/Test/5d348b7be95c4cfd89cf536101d2a57b.md null
 INFO  22:26:26: Synchronizer: Sync: createRemote: remote does not exist, and local is new and has never been synced: Note: (Local fa72dde7598b434db58f6e29ae4ce77a)
 LOG  22:26:26: FileApi: put content://com.android.externalstorage.documents/tree/primary:DCIM/Test/fa72dde7598b434db58f6e29ae4ce77a.md null
 INFO  22:26:26: Synchronizer: Sync: createRemote: remote does not exist, and local is new and has never been synced: Note: (Local 5b3eb4c5e4b3402e93c121473a6d207f)
 LOG  22:26:26: FileApi: put content://com.android.externalstorage.documents/tree/primary:DCIM/Test/5b3eb4c5e4b3402e93c121473a6d207f.md null
 INFO  22:26:26: Synchronizer: Sync: createRemote: remote does not exist, and local is new and has never been synced: Folder: (Local a7ad29d0a3e4417eb5afbe857745c417)
 LOG  22:26:26: FileApi: put content://com.android.externalstorage.documents/tree/primary:DCIM/Test/a7ad29d0a3e4417eb5afbe857745c417.md null
 INFO  22:26:27: Synchronizer: Sync: createRemote: remote does not exist, and local is new and has never been synced: Folder: (Local 71c8bf8a8f554fd7949cdc8f6219c6e9)
 LOG  22:26:27: FileApi: put content://com.android.externalstorage.documents/tree/primary:DCIM/Test/71c8bf8a8f554fd7949cdc8f6219c6e9.md null
 INFO  22:26:27: Synchronizer: Sync: createRemote: remote does not exist, and local is new and has never been synced: Folder: (Local e89c32f63ea64f24ba14dcf17e10722f)
 LOG  22:26:27: FileApi: put content://com.android.externalstorage.documents/tree/primary:DCIM/Test/e89c32f63ea64f24ba14dcf17e10722f.md null
 INFO  22:26:27: Synchronizer: Sync: createRemote: remote does not exist, and local is new and has never been synced: Resource: (Local e92552624e564d0db693dd247f0fcdfb)
 LOG  22:26:27: FileApi: put content://com.android.externalstorage.documents/tree/primary:DCIM/Test/.resource/e92552624e564d0db693dd247f0fcdfb {"path": "/data/user/0/net.cozic.joplin/files/e92552624e564d0db693dd247f0fcdfb.svg", "shareId": "", "source": "file"}
 LOG  22:26:27: FileApi: list content://com.android.externalstorage.documents/tree/primary:DCIM/Test
 ERROR  22:26:27: Synchronizer: [Error: Error: Permission Denial: writing com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/tree/primary:DCIM/Test/.resource/e92552624e564d0db693dd247f0fcdfb from pid=9214, uid=10148 requires android.permission.MANAGE_DOCUMENTS, or grantUriPermission(). Path: content://com.android.externalstorage.documents/tree/primary:DCIM/Test/.resource/e92552624e564d0db693dd247f0fcdfb]
 LOG  22:26:27: FileApi: delete content://com.android.externalstorage.documents/tree/primary:DCIM/Test/locks/1_2_cadc63f9a4154e45bbbade0c456ee155.json
 INFO  22:26:27: Synchronizer: Sync: finished: Synchronisation finished [1661318783422]
 INFO  22:26:27: Synchronizer: Operations completed:
 INFO  22:26:27: Synchronizer: deleteRemote: 1
 INFO  22:26:27: Synchronizer: createRemote: 14
 INFO  22:26:27: Synchronizer: Total folders: 3
 INFO  22:26:27: Synchronizer: Total notes: 10
 INFO  22:26:27: Synchronizer: Total resources: 1
 WARN  22:26:27: Synchronizer: There was some errors:
 WARN  22:26:27: Synchronizer: [Error: Error: Permission Denial: writing com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/tree/primary:DCIM/Test/.resource/e92552624e564d0db693dd247f0fcdfb from pid=9214, uid=10148 requires android.permission.MANAGE_DOCUMENTS, or grantUriPermission(). Path: content://com.android.externalstorage.documents/tree/primary:DCIM/Test/.resource/e92552624e564d0db693dd247f0fcdfb]
 LOG  22:26:27: Setting up recurrent sync with interval 300
 INFO  22:26:27: Recurrent sync operation DISABLED!!!
 LOG  22:26:28: models/Setting: Saving settings...
 LOG  22:26:28: models/Setting: Settings have been saved.
 INFO  22:26:28: DecryptionWorker: cannot start because no master key is currently loaded.

```

</details>

I have run both `yarn install` and `yarn build`, after re-building and deploying from Android Studio.

**Comment by personalizedrefrigerator** [comment]
Under "permissions and cache", I do see this:
![External storage reads: 1 item, button says: clear access](https://user-images.githubusercontent.com/46334387/186336593-cb9b0715-9186-4f6b-a135-e71c2dd836b6.png)

And some content is visible in the file manager:
![info.json appears in the selected folder](https://user-images.githubusercontent.com/46334387/186337299-52e0dcc3-1c9d-4ef9-87bb-6e9a6fef2019.png)

**Comment by roman-r-m** [comment]
I too am getting an error, specifically when syncing resources. In my case however the error is different:
```
2022-08-24 22:16:30.593 11518-11610/net.cozic.joplin I/ReactNativeJS: '22:16:30: FileApi:', 'put content://com.android.externalstorage.documents/tree/primary:Joplin/.resource/04426cfbbfac46e99ecfde209a861d05', { path: '/data/user/0/net.cozic.joplin/files/04426cfbbfac46e99ecfde209a861d05.jpg',
      source: 'file',
      shareId: '' }
2022-08-24 22:16:30.621 11518-11518/net.cozic.joplin W/System.err: java.lang.IllegalArgumentException: Invalid URI: content://com.android.externalstorage.documents/tree/primary:Joplin/.resource/04426cfbbfac46e99ecfde209a861d05
2022-08-24 22:16:30.621 11518-11518/net.cozic.joplin W/System.err:     at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
2022-08-24 22:16:30.621 11518-11518/net.cozic.joplin W/System.err:     at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
2022-08-24 22:16:30.621 11518-11518/net.cozic.joplin W/System.err:     at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:704)
2022-08-24 22:16:30.621 11518-11518/net.cozic.joplin W/System.err:     at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1816)
2022-08-24 22:16:30.621 11518-11518/net.cozic.joplin W/System.err:     at android.content.ContentResolver.openOutputStream(ContentResolver.java:1518)
2022-08-24 22:16:30.621 11518-11518/net.cozic.joplin W/System.err:     at com.rnfs.RNFSManager.getOutputStream(RNFSManager.java:122)
2022-08-24 22:16:30.621 11518-11518/net.cozic.joplin W/System.err:     at com.rnfs.RNFSManager.access$300(RNFSManager.java:43)
2022-08-24 22:16:30.621 11518-11518/net.cozic.joplin W/System.err:     at com.rnfs.RNFSManager$CopyFileTask.doInBackground(RNFSManager.java:409)
2022-08-24 22:16:30.621 11518-11518/net.cozic.joplin W/System.err:     at com.rnfs.RNFSManager$CopyFileTask.doInBackground(RNFSManager.java:402)
2022-08-24 22:16:30.621 11518-11518/net.cozic.joplin W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:394)
2022-08-24 22:16:30.621 11518-11518/net.cozic.joplin W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2022-08-24 22:16:30.621 11518-11518/net.cozic.joplin W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
2022-08-24 22:16:30.621 11518-11518/net.cozic.joplin W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2022-08-24 22:16:30.621 11518-11518/net.cozic.joplin W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2022-08-24 22:16:30.621 11518-11518/net.cozic.joplin W/System.err:     at java.lang.Thread.run(Thread.java:923)

```

**Comment by roman-r-m** [comment]
Not sure if my error is different or the same, and the difference in messages is due to different android versions (I used 11).

In any case, the error lies here:
https://github.com/laurent22/joplin/blob/c705ec682cd697c7a93a10a7d8d2f0be4239828e/packages/app-mobile/utils/fs-driver-rn.ts#L194

Here Joplin tries to copy a file from it's local storage and it is allowed to access such file using a regular path instead of a URI. But because of the `&&` there it falls back onto the old method of file access which as we know does not work.
