### ISSUE TITLE
synch probs mac dropbox

### ISSUE THREAD

**Issue by zeitlyn** [laurent22/joplin#6850]
## Environment

Joplin version:  Joplin 2.8.8 (prod, darwin)

Platform:  MacOS 
OS specifics: 12.5.1

## Steps to reproduce

1.  Synch on desktop
2. Synch on laptop
3.  Files from desktop ARE there in Joplin folder in dropbox on laptop BUT are not showing in Joplin
4. There is an error message
last error: SyntaxError: On file 017c92b3bca14966923790411441a6b3.md: Unexpected token d in JSON at position 4

The error from the log file is
2022-09-15 09:49:00: Synchronizer: "SyntaxError: On file 017c92b3bca14966923790411441a6b3.md: Unexpected token d in JSON at position 4
SyntaxError: On file 017c92b3bca14966923790411441a6b3.md: Unexpected token d in JSON at position 4
    at JSON.parse (<anonymous>)
    at Function.unserialize_format (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/models/BaseItem.js:300:30)
    at Function.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/models/BaseItem.js:476:40)
    at Generator.next (<anonymous>)
    at fulfilled (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/models/BaseItem.js:5:58)"
2022-09-15 09:49:01: Synchronizer: "Sync: finished: Synchronisation finished [1663231734820]"

## Describe what you expected to happen

the synched files are there but not shoing in joplin. Should I just delete the problematic file? thanks david

## Logfile

[017c92b3bca14966923790411441a6b3.md](https://github.com/laurent22/joplin/files/9573606/017c92b3bca14966923790411441a6b3.md)

**Comment by zeitlyn** [comment]
Problem still there. Not too bothersome as long as I only work on one machine but sharing isnt working for me in effect at the moment.

**Comment by zeitlyn** [comment]
Sorry I closed this in error. It remains an issue I think
