### ISSUE TITLE
fatal error on opening Joplin when using JoplinCloud and ProtonVPN connected to VPN

### ISSUE THREAD

**Issue by o5t6iaqo7** [laurent22/joplin#6924]
fatal error on opening Joplin when using JoplinCloud and ProtonVPN connected to VPN

it works OK if VPN is off

Error
Joplin encountered a fatal error and could not continue.

To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

If the error persists you may try to [restart in safe mode](https://github.com/laurent22/joplin/issues/new?assignees=&labels=bug&template=bug_report.md&title=#), which will temporarily disable all plugins.

Message
Cannot read properties of null (reading 'wrappedInstance')

Version info
Joplin for Desktop

Copyright © 2016-2022 Laurent Cozic
Joplin 2.8.8 (prod, darwin)

Client ID: ac9df9e83a01451cb49bb4b76cd26c6d
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: c2a6a13
Plugins
[
    {
        "id": "joplin.plugin.benji.favorites",
        "name": "Favorites",
        "enabled": true,
        "version": "1.3.0"
    },
    {
        "id": "ylc395.betterMarkdownViewer",
        "name": "Cursor Sync",
        "enabled": true,
        "version": "2.0.5"
    },
    {
        "id": "com.lki.homenote",
        "name": "Home Note",
        "enabled": true,
        "version": "1.0.4"
    },
    {
        "id": "joplin-insert-date",
        "name": "Insert Date",
        "enabled": true,
        "version": "1.0.1"
    },
    {
        "id": "joplin.plugin.note.tabs",
        "name": "Note Tabs",
        "enabled": true,
        "version": "1.4.0"
    },
    {
        "id": "plugin.calebjohn.rich-markdown",
        "name": "Rich Markdown",
        "enabled": true,
        "version": "0.11.1"
    },
    {
        "id": "io.github.jackgruber.backup",
        "name": "Simple Backup",
        "enabled": true,
        "version": "1.1.1"
    },
    {
        "id": "joplin-plugin-conflict-resolution",
        "name": "Conflict Resolution",
        "enabled": true,
        "version": "1.2.3"
    },
    {
        "id": "joplin.plugin.benji.persistentLayout",
        "name": "Persistent Editor Layout",
        "enabled": false,
        "version": "2.2.0"
    }
]
Stack trace
TypeError: Cannot read properties of null (reading 'wrappedInstance')
    at /Applications/Joplin.app/Contents/Resources/app.asar/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.js:646:32
    at commitHookEffectList (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:19986:26)
    at commitPassiveHookEffects (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:20016:11)
    at HTMLUnknownElement.callCallback (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:347:14)
    at Object.invokeGuardedCallbackDev (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:397:16)
    at invokeGuardedCallback (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:454:31)
    at flushPassiveEffectsImpl (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22868:7)
    at unstable_runWithPriority (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/scheduler/cjs/scheduler.development.js:643:12)
    at runWithPriority$2 (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11305:10)
    at flushPassiveEffects (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22841:10)
Component stack

    in ForwardRef(CodeMirror) (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in div (created by NoteEditor)
    in NoteEditor (created by Connect(NoteEditor))
    in Connect(NoteEditor) (created by ResizableLayout)
    in div (created by styled.div)
    in styled.div (created by ResizableLayout)
    in div (created by Resizable)
    in Resizable (created by ResizableLayout)
    in div (created by ResizableLayout)
    in ResizableLayout (created by MainScreenComponent)
    in div (created by MainScreenComponent)
    in MainScreenComponent (created by Connect(MainScreenComponent))
    in Connect(MainScreenComponent) (created by NavigatorComponent)
    in div (created by NavigatorComponent)
    in NavigatorComponent (created by Connect(NavigatorComponent))
    in Connect(NavigatorComponent) (created by RootComponent)
    in ThemeProvider (created by RootComponent)
    in StyleSheetManager (created by RootComponent)
    in RootComponent (created by Connect(RootComponent))
    in Connect(RootComponent)
    in ErrorBoundary
    in Provider

## Environment

Joplin version: 
Platform: 
OS specifics: 

## Steps to reproduce

1. 
2. 
3.

**Comment by laurent22** [comment]
Are you sure it always happen when vpn is on? It seems completely unrelated
