### ISSUE TITLE
New Project Fails to Install Dependencies

### ISSUE THREAD

**Issue by KempfCreative** [laurent22/joplin#6935]
`yarn install` fails on a fresh install. I have tried multiple versions of Node.

## Environment

Joplin version: 2.88
Platform: MacOS
OS specifics: Monterey 12.3.1

## Steps to reproduce

1. Fork a copy of the Joplin repo.
2. Follow directions to install the repo and set up for local development/
3. Fail to install dependencies.

## Describe what you expected to happen

- I expected the project to be able to run.

## Logfile

```
$ yarn install
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @aws-sdk/client-s3@npm:3.44.0 doesn't provide @aws-sdk/signature-v4-crt (p6155d), requested by @aws-sdk/middleware-sdk-s3
➤ YN0002: │ @aws-sdk/s3-request-presigner@npm:3.44.0 doesn't provide @aws-sdk/signature-v4-crt (pf5946), requested by @aws-sdk/middleware-sdk-s3
➤ YN0060: │ @joplin/app-desktop@workspace:packages/app-desktop provides react (p420ff) with version 16.13.1, which doesn't satisfy what react-test-renderer requests
➤ YN0060: │ @joplin/app-desktop@workspace:packages/app-desktop provides react-dom (p2e5b2) with version 16.9.0, which doesn't satisfy what re-resizable requests
➤ YN0002: │ @joplin/app-desktop@workspace:packages/app-desktop doesn't provide react-is (p0cdf0), requested by styled-components
➤ YN0002: │ @joplin/app-mobile@workspace:packages/app-mobile doesn't provide @types/node (pd8fb3), requested by ts-node
➤ YN0060: │ @joplin/app-mobile@workspace:packages/app-mobile provides react (pb7acb) with version 17.0.2, which doesn't satisfy what react-redux requests
➤ YN0060: │ @joplin/app-mobile@workspace:packages/app-mobile provides react-native (pbf89e) with version 0.66.1, which doesn't satisfy what react-native-webview requests
➤ YN0002: │ @joplin/app-mobile@workspace:packages/app-mobile doesn't provide react-native-windows (pb66a5), requested by react-native-fs
➤ YN0060: │ @joplin/fork-htmlparser2@workspace:packages/fork-htmlparser2 provides eslint (p4ecde) with version 6.8.0, which doesn't satisfy what @typescript-eslint/eslint-plugin and some of its descendants request
➤ YN0060: │ @joplin/fork-htmlparser2@workspace:packages/fork-htmlparser2 provides eslint (p83f76) with version 6.8.0, which doesn't satisfy what @typescript-eslint/parser requests
➤ YN0060: │ @joplin/fork-htmlparser2@workspace:packages/fork-htmlparser2 provides jest (pa940f) with version 26.6.3, which doesn't satisfy what ts-jest requests
➤ YN0002: │ @joplin/pdf-viewer@workspace:packages/pdf-viewer doesn't provide @babel/core (pf7d0e), requested by babel-jest
➤ YN0002: │ @joplin/pdf-viewer@workspace:packages/pdf-viewer doesn't provide react-is (p09697), requested by styled-components
➤ YN0060: │ @joplin/server@workspace:packages/server provides sqlite3 (p9ac44) with version 4.2.0, which doesn't satisfy what @rmp135/sql-ts and some of its descendants request
➤ YN0060: │ @joplin/server@workspace:packages/server provides sqlite3 (p05a2d) with version 4.2.0, which doesn't satisfy what knex requests
➤ YN0002: │ @octokit/rest@npm:16.43.2 doesn't provide @octokit/core (p84523), requested by @octokit/plugin-request-log
➤ YN0002: │ react-native-codegen@npm:0.0.7 doesn't provide @babel/preset-env (pe4ee6), requested by jscodeshift
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 741ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 2s 150ms
➤ YN0000: ┌ Link step
➤ YN0076: │ 7zip-bin-linux@npm:1.3.1 The darwin-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ 7zip-bin-win@npm:2.2.0 The darwin-x64 architecture is incompatible with this module, link skipped.
➤ YN0007: │ @joplin/app-clipper@workspace:packages/app-clipper must be built because it never has been before or the last one failed
➤ YN0007: │ husky@npm:3.1.0 must be built because it never has been before or the last one failed
➤ YN0007: │ nodemon@npm:2.0.15 must be built because it never has been before or the last one failed
➤ YN0007: │ keytar@npm:7.7.0 must be built because it never has been before or the last one failed
➤ YN0007: │ sharp@npm:0.26.3 must be built because it never has been before or the last one failed
➤ YN0007: │ sqlite3@npm:5.0.2 [ea905] must be built because it never has been before or the last one failed
➤ YN0007: │ fsevents@patch:fsevents@npm%3A1.2.13#~builtin<compat/fsevents>::version=1.2.13&hash=18f3a7 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:2.6.12 must be built because it never has been before or the last one failed
➤ YN0007: │ sharp@npm:0.25.4 must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/fontawesome-free@npm:5.15.4 must be built because it never has been before or the last one failed
➤ YN0007: │ electron@npm:18.2.0 must be built because it never has been before or the last one failed
➤ YN0007: │ lzma-native@npm:8.0.6 must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/fontawesome-common-types@npm:0.2.36 must be built because it never has been before or the last one failed
➤ YN0007: │ styled-components@npm:5.3.5 [935a6] must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/fontawesome-common-types@npm:6.1.2 must be built because it never has been before or the last one failed
➤ YN0007: │ ejs@npm:2.7.4 must be built because it never has been before or the last one failed
➤ YN0007: │ sqlite3@npm:4.2.0 must be built because it never has been before or the last one failed
➤ YN0009: │ sqlite3@npm:4.2.0 couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/rz/_v0n3chn3l587__thlx2_mlr0000gn/T/xfs-2081a29a/build.log)
➤ YN0007: │ root@workspace:. must be built because it never has been before or the last one failed
➤ YN0007: │ @joplin/app-mobile@workspace:packages/app-mobile must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/fontawesome-svg-core@npm:1.2.36 must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/free-regular-svg-icons@npm:5.15.4 must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/free-solid-svg-icons@npm:5.15.4 must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/fontawesome-svg-core@npm:6.1.2 must be built because it never has been before or the last one failed
➤ YN0007: │ @fortawesome/free-solid-svg-icons@npm:6.1.2 must be built because it never has been before or the last one failed
➤ YN0009: │ root@workspace:. couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/rz/_v0n3chn3l587__thlx2_mlr0000gn/T/xfs-1dff3d04/build.log)
➤ YN0007: │ @joplin/pdf-viewer@workspace:packages/pdf-viewer must be built because it never has been before or the last one failed
➤ YN0007: │ @joplin/app-desktop@workspace:packages/app-desktop must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 5m 21s
➤ YN0000: Failed with errors in 5m 27s
```
from `/private/var/folders/rz/_v0n3chn3l587__thlx2_mlr0000gn/T/xfs-2081a29a/build.log`
```
# This file contains the result of Yarn building a package (sqlite3@npm:4.2.0)
# Script name: install

node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@16.14.2 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for "~/Sites/personal/joplin/packages/server/node_modules/sqlite3/lib/binding/node-v93-darwin-x64/node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v93-darwin-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v93-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v93-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and node@16.14.2 (node-v93 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v93-darwin-x64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.14.2 | darwin | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.14.2 | darwin | x64
gyp info find Python using Python version 3.8.9 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
gyp info spawn args [
gyp info spawn args   '~/Sites/personal/joplin/packages/tools/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '~/Sites/personal/joplin/packages/server/node_modules/sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '~/Sites/personal/joplin/packages/tools/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '~/Library/Caches/node-gyp/16.14.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=~Library/Caches/node-gyp/16.14.2',
gyp info spawn args   '-Dnode_gyp_dir=~/Sites/personal/joplin/packages/tools/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=~/Library/Caches/node-gyp/16.14.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=~/Sites/personal/joplin/packages/server/node_modules/sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.14.2 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c
/bin/sh: python: command not found
make: *** [Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (~/Sites/personal/joplin/packages/tools/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 21.4.0
gyp ERR! command "~/.nvm/versions/node/v16.14.2/bin/node" "~/Sites/personal/joplin/packages/tools/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=~Sites/personal/joplin/packages/server/node_modules/sqlite3/lib/binding/node-v93-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=~/Sites/personal/joplin/packages/server/node_modules/sqlite3/lib/binding/node-v93-darwin-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
gyp ERR! cwd ~/Sites/personal/joplin/packages/server/node_modules/sqlite3
gyp ERR! node -v v16.14.2
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '~/.nvm/versions/node/v16.14.2/bin/node ~/Sites/personal/joplin/packages/tools/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=~/Sites/personal/joplin/packages/server/node_modules/sqlite3/lib/binding/node-v93-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=~/Sites/personal/joplin/packages/server/node_modules/sqlite3/lib/binding/node-v93-darwin-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (~/Sites/personal/joplin/packages/tools/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Darwin 21.4.0
node-pre-gyp ERR! command "~/.nvm/versions/node/v16.14.2/bin/node" "~/Sites/personal/joplin/packages/tools/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd ~/Sites/personal/joplin/packages/server/node_modules/sqlite3
node-pre-gyp ERR! node -v v16.14.2
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '~/.nvm/versions/node/v16.14.2/bin/node ~/Sites/personal/joplin/packages/tools/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=~/Sites/personal/joplin/packages/server/node_modules/sqlite3/lib/binding/node-v93-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=~/Sites/personal/joplin/packages/server/node_modules/sqlite3/lib/binding/node-v93-darwin-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
```

from `/private/var/folders/rz/_v0n3chn3l587__thlx2_mlr0000gn/T/xfs-1dff3d04/build.log`
```
# This file contains the result of Yarn building a package (root@workspace:.)
# Script name: postinstall

[23:16:58] Using gulpfile ~/Sites/personal/joplin/gulpfile.js
[23:16:58] Starting 'build'...
> yarn [ 'run', 'buildParallel' ]
➤ YN0000: [joplin]: Process started
➤ YN0000: [@joplin/app-mobile]: Process started
➤ YN0000: [@joplin/app-mobile]: [23:17:04] Requiring external module ts-node/register
➤ YN0000: [joplin]: [23:17:04] Using gulpfile ~/Sites/personal/joplin/packages/app-cli/gulpfile.js
➤ YN0000: [joplin]: [23:17:04] Starting 'build'...
➤ YN0000: [joplin]: [23:17:04] Starting 'prepareBuild'...
➤ YN0000: [joplin]: [23:17:04] Finished 'prepareBuild' after 56 ms
➤ YN0000: [joplin]: [23:17:04] Finished 'build' after 59 ms
➤ YN0000: [joplin]: Process exited (exit code 0), completed in 2s 500ms
➤ YN0000: [@joplin/fork-htmlparser2]: Process started
➤ YN0000: [@joplin/app-mobile]: [23:17:07] Using gulpfile ~/Sites/personal/joplin/packages/app-mobile/gulpfile.ts
➤ YN0000: [@joplin/app-mobile]: [23:17:07] Starting 'build'...
➤ YN0000: [@joplin/app-mobile]: [23:17:07] Starting 'buildInjectedJs'...
➤ YN0000: [@joplin/app-mobile]: Building bundle: codeMirrorBundle...
➤ YN0000: [@joplin/fork-htmlparser2]: Process exited (exit code 0), completed in 13s 791ms
➤ YN0000: [@joplin/pdf-viewer]: Process started
➤ YN0000: [@joplin/app-mobile]: Minifying bundle: codeMirrorBundle...
➤ YN0000: [@joplin/app-mobile]: Creating: ~/Sites/personal/joplin/packages/app-mobile/lib/rnInjectedJs/CodeMirror.bundle.js
➤ YN0000: [@joplin/app-mobile]: Creating: ~/Sites/personal/joplin/packages/app-mobile/lib/rnInjectedJs/webviewLib.js
➤ YN0000: [@joplin/app-mobile]: [23:17:52] Finished 'buildInjectedJs' after 45 s
➤ YN0000: [@joplin/app-mobile]: [23:17:52] Starting 'encodeAssets'...
➤ YN0000: [@joplin/app-mobile]: [23:17:52] 'encodeAssets' errored after 85 ms
➤ YN0000: [@joplin/app-mobile]: [23:17:52] Error: EEXIST: file already exists, mkdir '~/Sites/personal/joplin/packages/app-mobile/pluginAssets/katex/fonts'
➤ YN0000: [@joplin/app-mobile]: [23:17:52] 'build' errored after 45 s
➤ YN0000: [@joplin/app-mobile]: Process exited (exit code 1), completed in 50s 636ms
➤ YN0000: [@joplin/server]: Process started
➤ YN0000: [@joplin/server]: [23:17:55] Using gulpfile ~/Sites/personal/joplin/packages/server/gulpfile.js
➤ YN0000: [@joplin/server]: [23:17:55] Starting 'build'...
➤ YN0000: [@joplin/server]: [23:17:55] Starting 'compilePackageInfo'...
➤ YN0000: [@joplin/server]: Generated ~/Sites/personal/joplin/packages/server/dist/packageInfo.js
➤ YN0000: [@joplin/server]: [23:17:55] Finished 'compilePackageInfo' after 69 ms
➤ YN0000: [@joplin/server]: [23:17:55] Finished 'build' after 72 ms
➤ YN0000: [@joplin/server]: Process exited (exit code 0), completed in 2s 802ms
➤ YN0000: [@joplin/turndown]: Process started
➤ YN0000: [@joplin/turndown]: 
➤ YN0000: [@joplin/turndown]: src/turndown.js → lib/turndown.cjs.js...
➤ YN0000: [@joplin/turndown]: created lib/turndown.cjs.js in 660ms
➤ YN0000: [@joplin/turndown]: Process exited (exit code 0), completed in 2s 329ms
➤ YN0000: [@joplin/turndown-plugin-gfm]: Process started
➤ YN0000: [@joplin/turndown-plugin-gfm]: 
➤ YN0000: [@joplin/turndown-plugin-gfm]: src/gfm.js → lib/turndown-plugin-gfm.cjs.js...
➤ YN0000: [@joplin/turndown-plugin-gfm]: created lib/turndown-plugin-gfm.cjs.js in 67ms
➤ YN0000: [@joplin/turndown-plugin-gfm]: Process exited (exit code 0), completed in 1s 527ms
➤ YN0000: [@joplin/pdf-viewer]: asset main.js 1.62 MiB [compared for emit] [minimized] [big] (name: main) 1 related asset
➤ YN0000: [@joplin/pdf-viewer]: asset pdf.worker.js 994 KiB [compared for emit] [minimized] [big] (name: pdf.worker) 1 related asset
➤ YN0000: [@joplin/pdf-viewer]: orphan modules 129 KiB [orphan] 5 modules
➤ YN0000: [@joplin/pdf-viewer]: runtime modules 972 bytes 5 modules
➤ YN0000: [@joplin/pdf-viewer]: modules by path ./ 3.93 MiB 59 modules
➤ YN0000: [@joplin/pdf-viewer]: modules by path ../lib/ 14.3 KiB
➤ YN0000: [@joplin/pdf-viewer]:   ../lib/shim.ts 13.7 KiB [built] [code generated]
➤ YN0000: [@joplin/pdf-viewer]:   ../lib/hooks/useAsyncEffect.ts 682 bytes [built] [code generated]
➤ YN0000: [@joplin/pdf-viewer]: fs (ignored) 15 bytes [built] [code generated]
➤ YN0000: [@joplin/pdf-viewer]: canvas (ignored) 15 bytes [built] [code generated]
➤ YN0000: [@joplin/pdf-viewer]: zlib (ignored) 15 bytes [optional] [built] [code generated]
➤ YN0000: [@joplin/pdf-viewer]: http (ignored) 15 bytes [built] [code generated]
➤ YN0000: [@joplin/pdf-viewer]: https (ignored) 15 bytes [built] [code generated]
➤ YN0000: [@joplin/pdf-viewer]: url (ignored) 15 bytes [built] [code generated]
➤ YN0000: [@joplin/pdf-viewer]: 
➤ YN0000: [@joplin/pdf-viewer]: WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
➤ YN0000: [@joplin/pdf-viewer]: This can impact web performance.
➤ YN0000: [@joplin/pdf-viewer]: Assets: 
➤ YN0000: [@joplin/pdf-viewer]:   main.js (1.62 MiB)
➤ YN0000: [@joplin/pdf-viewer]:   pdf.worker.js (994 KiB)
➤ YN0000: [@joplin/pdf-viewer]: 
➤ YN0000: [@joplin/pdf-viewer]: WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
➤ YN0000: [@joplin/pdf-viewer]: Entrypoints:
➤ YN0000: [@joplin/pdf-viewer]:   main (1.62 MiB)
➤ YN0000: [@joplin/pdf-viewer]:       main.js
➤ YN0000: [@joplin/pdf-viewer]:   pdf.worker (994 KiB)
➤ YN0000: [@joplin/pdf-viewer]:       pdf.worker.js
➤ YN0000: [@joplin/pdf-viewer]: 
➤ YN0000: [@joplin/pdf-viewer]: WARNING in webpack performance recommendations: 
➤ YN0000: [@joplin/pdf-viewer]: You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
➤ YN0000: [@joplin/pdf-viewer]: For more info visit https://webpack.js.org/guides/code-splitting/
➤ YN0000: [@joplin/pdf-viewer]: 
➤ YN0000: [@joplin/pdf-viewer]: webpack 5.74.0 compiled with 3 warnings in 42313 ms
➤ YN0000: [@joplin/pdf-viewer]: Process exited (exit code 0), completed in 45s 28ms
➤ YN0000: The command failed for workspaces that are depended upon by other workspaces; can't satisfy the dependency graph
➤ YN0000: Failed with errors in 1m 2s
[23:18:03] 'build' errored after 1.07 min
[23:18:03] Error: Command failed with exit code 1: yarn run buildParallel
➤ YN0000: [joplin]: Process started
➤ YN0000: [@joplin/app-mobile]: Process started
➤ YN0000: [@joplin/app-mobile]: [23:17:04] Requiring external module ts-node/register
➤ YN0000: [joplin]: [23:17:04] Using gulpfile ~/Sites/personal/joplin/packages/app-cli/gulpfile.js
➤ YN0000: [joplin]: [23:17:04] Starting 'build'...
➤ YN0000: [joplin]: [23:17:04] Starting 'prepareBuild'...
➤ YN0000: [joplin]: [23:17:04] Finished 'prepareBuild' after 56 ms
➤ YN0000: [joplin]: [23:17:04] Finished 'build' after 59 ms
➤ YN0000: [joplin]: Process exited (exit code 0), completed in 2s 500ms
➤ YN0000: [@joplin/fork-htmlparser2]: Process started
➤ YN0000: [@joplin/app-mobile]: [23:17:07] Using gulpfile ~/Sites/personal/joplin/packages/app-mobile/gulpfile.ts
➤ YN0000: [@joplin/app-mobile]: [23:17:07] Starting 'build'...
➤ YN0000: [@joplin/app-mobile]: [23:17:07] Starting 'buildInjectedJs'...
➤ YN0000: [@joplin/app-mobile]: Building bundle: codeMirrorBundle...
➤ YN0000: [@joplin/fork-htmlparser2]: Process exited (exit code 0), completed in 13s 791ms
➤ YN0000: [@joplin/pdf-viewer]: Process started
➤ YN0000: [@joplin/app-mobile]: Minifying bundle: codeMirrorBundle...
➤ YN0000: [@joplin/app-mobile]: Creating: ~/Sites/personal/joplin/packages/app-mobile/lib/rnInjectedJs/CodeMirror.bundle.js
➤ YN0000: [@joplin/app-mobile]: Creating: ~/Sites/personal/joplin/packages/app-mobile/lib/rnInjectedJs/webviewLib.js
➤ YN0000: [@joplin/app-mobile]: [23:17:52] Finished 'buildInjectedJs' after 45 s
➤ YN0000: [@joplin/app-mobile]: [23:17:52] Starting 'encodeAssets'...
➤ YN0000: [@joplin/app-mobile]: [23:17:52] 'encodeAssets' errored after 85 ms
➤ YN0000: [@joplin/app-mobile]: [23:17:52] Error: EEXIST: file already exists, mkdir '~/Sites/personal/joplin/packages/app-mobile/pluginAssets/katex/fonts'
➤ YN0000: [@joplin/app-mobile]: [23:17:52] 'build' errored after 45 s
➤ YN0000: [@joplin/app-mobile]: Process exited (exit code 1), completed in 50s 636ms
➤ YN0000: [@joplin/server]: Process started
➤ YN0000: [@joplin/server]: [23:17:55] Using gulpfile ~/Sites/personal/joplin/packages/server/gulpfile.js
➤ YN0000: [@joplin/server]: [23:17:55] Starting 'build'...
➤ YN0000: [@joplin/server]: [23:17:55] Starting 'compilePackageInfo'...
➤ YN0000: [@joplin/server]: Generated ~/Sites/personal/joplin/packages/server/dist/packageInfo.js
➤ YN0000: [@joplin/server]: [23:17:55] Finished 'compilePackageInfo' after 69 ms
➤ YN0000: [@joplin/server]: [23:17:55] Finished 'build' after 72 ms
➤ YN0000: [@joplin/server]: Process exited (exit code 0), completed in 2s 802ms
➤ YN0000: [@joplin/turndown]: Process started
➤ YN0000: [@joplin/turndown]: 
➤ YN0000: [@joplin/turndown]: src/turndown.js → lib/turndown.cjs.js...
➤ YN0000: [@joplin/turndown]: created lib/turndown.cjs.js in 660ms
➤ YN0000: [@joplin/turndown]: Process exited (exit code 0), completed in 2s 329ms
➤ YN0000: [@joplin/turndown-plugin-gfm]: Process started
➤ YN0000: [@joplin/turndown-plugin-gfm]: 
➤ YN0000: [@joplin/turndown-plugin-gfm]: src/gfm.js → lib/turndown-plugin-gfm.cjs.js...
➤ YN0000: [@joplin/turndown-plugin-gfm]: created lib/turndown-plugin-gfm.cjs.js in 67ms
➤ YN0000: [@joplin/turndown-plugin-gfm]: Process exited (exit code 0), completed in 1s 527ms
➤ YN0000: [@joplin/pdf-viewer]: asset main.js 1.62 MiB [compared for emit] [minimized] [big] (name: main) 1 related asset
➤ YN0000: [@joplin/pdf-viewer]: asset pdf.worker.js 994 KiB [compared for emit] [minimized] [big] (name: pdf.worker) 1 related asset
➤ YN0000: [@joplin/pdf-viewer]: orphan modules 129 KiB [orphan] 5 modules
➤ YN0000: [@joplin/pdf-viewer]: runtime modules 972 bytes 5 modules
➤ YN0000: [@joplin/pdf-viewer]: modules by path ./ 3.93 MiB 59 modules
➤ YN0000: [@joplin/pdf-viewer]: modules by path ../lib/ 14.3 KiB
➤ YN0000: [@joplin/pdf-viewer]:   ../lib/shim.ts 13.7 KiB [built] [code generated]
➤ YN0000: [@joplin/pdf-viewer]:   ../lib/hooks/useAsyncEffect.ts 682 bytes [built] [code generated]
➤ YN0000: [@joplin/pdf-viewer]: fs (ignored) 15 bytes [built] [code generated]
➤ YN0000: [@joplin/pdf-viewer]: canvas (ignored) 15 bytes [built] [code generated]
➤ YN0000: [@joplin/pdf-viewer]: zlib (ignored) 15 bytes [optional] [built] [code generated]
➤ YN0000: [@joplin/pdf-viewer]: http (ignored) 15 bytes [built] [code generated]
➤ YN0000: [@joplin/pdf-viewer]: https (ignored) 15 bytes [built] [code generated]
➤ YN0000: [@joplin/pdf-viewer]: url (ignored) 15 bytes [built] [code generated]
➤ YN0000: [@joplin/pdf-viewer]: 
➤ YN0000: [@joplin/pdf-viewer]: WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
➤ YN0000: [@joplin/pdf-viewer]: This can impact web performance.
➤ YN0000: [@joplin/pdf-viewer]: Assets: 
➤ YN0000: [@joplin/pdf-viewer]:   main.js (1.62 MiB)
➤ YN0000: [@joplin/pdf-viewer]:   pdf.worker.js (994 KiB)
➤ YN0000: [@joplin/pdf-viewer]: 
➤ YN0000: [@joplin/pdf-viewer]: WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
➤ YN0000: [@joplin/pdf-viewer]: Entrypoints:
➤ YN0000: [@joplin/pdf-viewer]:   main (1.62 MiB)
➤ YN0000: [@joplin/pdf-viewer]:       main.js
➤ YN0000: [@joplin/pdf-viewer]:   pdf.worker (994 KiB)
➤ YN0000: [@joplin/pdf-viewer]:       pdf.worker.js
➤ YN0000: [@joplin/pdf-viewer]: 
➤ YN0000: [@joplin/pdf-viewer]: WARNING in webpack performance recommendations: 
➤ YN0000: [@joplin/pdf-viewer]: You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
➤ YN0000: [@joplin/pdf-viewer]: For more info visit https://webpack.js.org/guides/code-splitting/
➤ YN0000: [@joplin/pdf-viewer]: 
➤ YN0000: [@joplin/pdf-viewer]: webpack 5.74.0 compiled with 3 warnings in 42313 ms
➤ YN0000: [@joplin/pdf-viewer]: Process exited (exit code 0), completed in 45s 28ms
➤ YN0000: The command failed for workspaces that are depended upon by other workspaces; can't satisfy the dependency graph
➤ YN0000: Failed with errors in 1m 2s
    at makeError (~/Sites/personal/joplin/packages/tools/node_modules/execa/lib/error.js:59:11)
    at handlePromise (~/Sites/personal/joplin/packages/tools/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async fn (~/Sites/personal/joplin/gulpfile.js:35:5)
```

**Comment by roman-r-m** [comment]
I think it might be this:
```
/bin/sh: python: command not found
```

**Comment by laurent22** [comment]
There's also something wrong with this:

    ➤ YN0000: [@joplin/app-mobile]: [23:17:52] 'encodeAssets' errored after 85 ms
    ➤ YN0000: [@joplin/app-mobile]: [23:17:52] Error: EEXIST: file already exists, mkdir 
    '~/Sites/personal/joplin/packages/app-mobile/pluginAssets/katex/fonts'

The command we use is essentially "mkdir -p" so it shouldn't complain that the directory already exists. So maybe some problems with the file permissions.

**Comment by laurent22** [comment]
Somehow that same error also randomly happened on CI - https://github.com/laurent22/joplin/actions/runs/3225952024/jobs/5278879753#step:10:4086

Although it makes no sense that mkdirp fails that way, I'm going to add an extra check to avoid this.

**Comment by sanskarfc** [comment]
faced the same issue today after running 
```
yarn install
```

anyone found out, how to resolve this?
