### ISSUE TITLE
Joplin on Android crashes when trying to open any note

### ISSUE THREAD

**Issue by n3wmsy** [laurent22/joplin#6950]
## Environment

Joplin version: 2.8.1
Platform: Android 13
OS specifics: Pixel 4a - Build Number TP1A.221005.002.2022101500

## Steps to reproduce

1. Open Joplin App
2. Attempt to Open a Note
3. App crashes

## Describe what you expected to happen
Note to open to be viewed and/or edited

### Android Crash Report

```
type: crash
osVersion: google/sunfish/sunfish:13/TP1A.221005.002/2022101500:user/release-keys
package: net.cozic.joplin:2097668
process: net.cozic.joplin

android.util.AndroidRuntimeException: java.lang.reflect.InvocationTargetException
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:363)
	at android.webkit.WebView.getFactory(WebView.java:2594)
	at android.webkit.WebView.ensureProviderCreated(WebView.java:2588)
	at android.webkit.WebView.setOverScrollMode(WebView.java:2656)
	at android.view.View.<init>(View.java:5370)
	at android.view.View.<init>(View.java:5511)
	at android.view.ViewGroup.<init>(ViewGroup.java:703)
	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
	at android.webkit.WebView.<init>(WebView.java:421)
	at android.webkit.WebView.<init>(WebView.java:363)
	at android.webkit.WebView.<init>(WebView.java:345)
	at android.webkit.WebView.<init>(WebView.java:332)
	at android.webkit.WebView.<init>(WebView.java:322)
	at com.reactnativecommunity.webview.RNCWebViewManager$RNCWebView.<init>(RNCWebViewManager.java:1225)
	at com.reactnativecommunity.webview.RNCWebViewManager.createRNCWebViewInstance(RNCWebViewManager.java:176)
	at com.reactnativecommunity.webview.RNCWebViewManager.createViewInstance(RNCWebViewManager.java:182)
	at com.reactnativecommunity.webview.RNCWebViewManager.createViewInstance(RNCWebViewManager.java:118)
	at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:139)
	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:76)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281)
	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:194)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1110)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1081)
	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:827)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:355)
	... 40 more
Caused by: TQ: errorCode=2
	at org.chromium.base.library_loader.b.g(chromium-TrichromeWebView64.apk-stable-524912635:870)
	at org.chromium.base.library_loader.b.i(chromium-TrichromeWebView64.apk-stable-524912635:697)
	at org.chromium.android_webview.AwBrowserProcess.i(chromium-TrichromeWebView64.apk-stable-524912635:681)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(chromium-TrichromeWebView64.apk-stable-524912635:445)
	at com.android.webview.chromium.WebViewChromiumFactoryProviderForT.<init>(chromium-TrichromeWebView64.apk-stable-524912635:13)
	at com.android.webview.chromium.WebViewChromiumFactoryProviderForT.create(chromium-TrichromeWebView64.apk-stable-524912635:9)
	... 42 more
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libmonochrome_64.so" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1661)
	at org.chromium.base.library_loader.b.g(chromium-TrichromeWebView64.apk-stable-524912635:819)
	... 47 more
```

### Joplin Logfile

![Screenshot_20221017-100231](https://user-images.githubusercontent.com/26755243/196062703-ac45b46d-4c9f-4def-92a4-b1a66822301a.png)

**Comment by roman-r-m** [comment]
Could be related to this https://stackoverflow.com/questions/66361472/app-crashed-with-base-apklibmonochrome-so (a bug in the system Webview).
Supposedly fixed in 89.0.4389.105 (https://support.google.com/android/thread/103561027)

**Comment by root-io** [comment]
Are you by any chance using GrapheneOS ? If yes, see https://github.com/GrapheneOS/os-issue-tracker/issues/1570

**Comment by n3wmsy** [comment]
I am using GrapheneOS. Looking at the issue you logged with them I am going to assume the fix will need to come from GrapheneOS rather than with Joplin?

**Comment by root-io** [comment]
They already reverted the changes on GrapheneOS, but the update will probably be deployed in the next few days.

You can simply download the 64-bit version of Joplin for Android. Download the file `joplin-v2.8.1.apk` here: 
https://github.com/laurent22/joplin-android/releases/tag/android-v2.8.1

**Comment by n3wmsy** [comment]
Cheers
