### ISSUE TITLE
Building the Terminal application error

### ISSUE THREAD

**Issue by flipjs** [laurent22/joplin#71]
### Operating system

- [ ] Windows
- [x ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [ ] Desktop
- [ ] Mobile
- [ x] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

*If there is an error, please copy and paste the full error message*

---

Im getting this error when running `run.sh`:

```
Error: Cannot find module '../locales/index.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at supportedLocales (/Users/felipeapostol/dev/oss/joplin/CliClient/build/lib/locale.js:190:46)
    at closestSupportedLocale (/Users/felipeapostol/dev/oss/joplin/CliClient/build/lib/locale.js:211:18)
    at localeStrings (/Users/felipeapostol/dev/oss/joplin/CliClient/build/lib/locale.js:274:17)
    at _ (/Users/felipeapostol/dev/oss/joplin/CliClient/build/lib/locale.js:293:16)
    at Function.label (/Users/felipeapostol/dev/oss/joplin/CliClient/build/lib/SyncTargetFilesystem.js:19:10)
    at Function.addClass (/Users/felipeapostol/dev/oss/joplin/CliClient/build/lib/SyncTargetRegistry.js:13:27)
```

**Comment by laurent22** [comment]
Yes, you would need to build the translations but unfortunately that won't currently work on macOS. Instead I suggest you take them from one of the other app, for example there: https://github.com/laurent22/joplin/tree/master/ReactNativeClient/locales
Or run this from the root of the repository: `rsync -aP ReactNativeClient/locales/ CliClient/build/locales/`

**Comment by flipjs** [comment]
Got it to work by running this first `rsync -aP ReactNativeClient/locales/ CliClient/build/locales/` .

Thanks!
