### ISSUE TITLE
Webdav passed Synchronisation configuration check but failed when actual syncing

### ISSUE THREAD

**Issue by fronse** [laurent22/joplin#721]
### Operating system
- Win7

### Application
- Desktop
v1.0.104

I'm using webdav service from jianguoyun.com, when I finished the Synchronisation setting, It said "Synchronisation configuration appears to be correct."
But this error notification below always occurs when I click Synchronise:

> Created remote items: 1.
> Completed: 15/08/2018 20:36
> Last error: Error: PUT 4aa2f5793f7f4a6394a6e945f1aa280b.md: The resource of this location does not exist (Exception ObjectNotFound) (404): <?xml version="1.0" encoding="UTF-8" standalone="no"?><d:error xmlns:d="DAV:" xmlns:s="http://ns.jianguoyun.com"><s:exception>ObjectNotFound</s:exception><s:message>The resource of this location does not exist</s:message></d:error>

Inside the log.txt:
2018-08-15 20:34:34: "First start: detected locale as en_GB"
2018-08-15 20:34:34: "Trying to load 0 master keys..."
2018-08-15 20:34:34: "Loaded master keys: 0"
2018-08-15 20:34:34: "Trying to load 0 master keys..."
2018-08-15 20:34:34: "Loaded master keys: 0"
2018-08-15 20:34:34: "Scheduling sync operation..."
2018-08-15 20:34:34: "Scheduling sync operation..."
2018-08-15 20:34:35: "DecryptionWorker: starting decryption..."
2018-08-15 20:34:35: "DecryptionWorker: completed decryption."
2018-08-15 20:34:44: "Preparing scheduled sync"
2018-08-15 20:34:44: "Saving updated Dropbox auth."
2018-08-15 20:34:44: "Synchroniser is missing credentials - manual sync required to authenticate."
2018-08-15 20:34:44: "Updating all notifications..."
2018-08-15 20:34:44: "Garbage collecting alarms..."
2018-08-15 20:34:45: "DecryptionWorker: starting decryption..."
2018-08-15 20:34:45: "DecryptionWorker: completed decryption."
2018-08-15 20:35:04: "ResourceService::indexNoteResources: Start"
2018-08-15 20:35:04: "ResourceService::indexNoteResources: Completed"
2018-08-15 20:35:04: "ResourceService::deleteOrphanResources:", "[]"
2018-08-15 20:35:39: "Scheduling sync operation..."
2018-08-15 20:35:42: "Scheduling sync operation..."
2018-08-15 20:35:43: "Scheduling sync operation..."
2018-08-15 20:35:43: "Preparing scheduled sync"
2018-08-15 20:35:43: "Starting scheduled sync"
2018-08-15 20:36:14: "Error: PUT 4aa2f5793f7f4a6394a6e945f1aa280b.md: The resource of this location does not exist (Exception ObjectNotFound) (404): <?xml version="1.0" encoding="UTF-8" standalone="no"?><d:error xmlns:d="DAV:" xmlns:s="http://ns.jianguoyun.com"><s:exception>ObjectNotFound</s:exception><s:message>The resource of this location does not exist</s:message></d:error>
Code: 404
Error: PUT 4aa2f5793f7f4a6394a6e945f1aa280b.md: The resource of this location does not exist (Exception ObjectNotFound) (404): <?xml version="1.0" encoding="UTF-8" standalone="no"?><d:error xmlns:d="DAV:" xmlns:s="http://ns.jianguoyun.com"><s:exception>ObjectNotFound</s:exception><s:message>The resource of this location does not exist</s:message></d:error>
    at newError (C:\Users\ch\AppData\Local\Temp\nstB8D8.tmp\app\resources\app.asar\lib\WebDavApi.js:284:11)
    at WebDavApi.exec (C:\Users\ch\AppData\Local\Temp\nstB8D8.tmp\app\resources\app.asar\lib\WebDavApi.js:310:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)"
2018-08-15 20:36:14: "Operations completed: "
2018-08-15 20:36:14: "createRemote: 1"
2018-08-15 20:36:14: "Total folders: 1"
2018-08-15 20:36:14: "Total notes: 1"
2018-08-15 20:36:14: "Total resources: 0"
2018-08-15 20:36:14: "There was some errors:"
2018-08-15 20:36:14: "Error: PUT 4aa2f5793f7f4a6394a6e945f1aa280b.md: The resource of this location does not exist (Exception ObjectNotFound) (404): <?xml version="1.0" encoding="UTF-8" standalone="no"?><d:error xmlns:d="DAV:" xmlns:s="http://ns.jianguoyun.com"><s:exception>ObjectNotFound</s:exception><s:message>The resource of this location does not exist</s:message></d:error>
Code: 404
Error: PUT 4aa2f5793f7f4a6394a6e945f1aa280b.md: The resource of this location does not exist (Exception ObjectNotFound) (404): <?xml version="1.0" encoding="UTF-8" standalone="no"?><d:error xmlns:d="DAV:" xmlns:s="http://ns.jianguoyun.com"><s:exception>ObjectNotFound</s:exception><s:message>The resource of this location does not exist</s:message></d:error>
    at newError (C:\Users\ch\AppData\Local\Temp\nstB8D8.tmp\app\resources\app.asar\lib\WebDavApi.js:284:11)
    at WebDavApi.exec (C:\Users\ch\AppData\Local\Temp\nstB8D8.tmp\app\resources\app.asar\lib\WebDavApi.js:310:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)"

**Comment by fronse** [comment]
Update: the problem disappeared after I disabled the encryption.

**Comment by baixiaoyu2997** [comment]
有没有用到android版本？我都没有通过检测

**Comment by baixiaoyu2997** [comment]
刚才看了一下文档，joplin不支持jianguoyun

**Comment by fronse** [comment]
@baixiaoyu2997 你提醒以后我重新看了一下文档，终于找到办法了。
先在坚果云里新建一个个人同步文件夹，命名为“Joplin"，然后在软件设置的webdav地址里填入https://dav.jianguoyun.com/dav/Joplin，其他照旧就可以了。

**Comment by fronse** [comment]
I've read the manual and found the solution.
One need to create a "Joplin" directory in jianguoyun.com, and input https://dav.jianguoyun.com/dav/Joplin as the WebDav URL.
Thank you laurent, Joplin is a work of art.
