### ISSUE TITLE
Notes connected to Dropbox sync run into `Error in call to API function "files/get_metadata"`

### ISSUE THREAD

**Issue by mcmxcdev** [laurent22/joplin#7342]
## Environment

Joplin version: 2.8.8
Platform: Linux/macOS (happens on both)
OS specifics: Linux Manjaro Gnome, macOS

## Steps to reproduce

This started happening suddenly this morning, and it seems there is some issue with connecting to the Dropbox API (which I am using to store notes)

This should be considered high priority since it completely disables the ability to sync across devices, leading to stale notes.

1. Click "Synchronize"
2. It takes longer than usual
3. Following error pops up above sync button:
```
Completed: 24/11/2022 08:39 (49s)
Last error: Error: POST files/get_metadata: Error (400): Error in call to API function "files/get_metadata": Unknown API function: /2/files/get_metadata
```
4. No note updates come in synced from other devices

## Describe what you expected to happen

Notes sync across devices without sync errors.

## Logfile

<details>
<summary>log.txt (truncated)</summary>

```
2022-11-24 08:44:47: "DecryptionWorker: cannot start because no master key is currently loaded."
2022-11-24 08:44:47: "Preparing scheduled sync"
2022-11-24 08:44:47: "Saving updated Dropbox auth."
2022-11-24 08:44:47: "Starting scheduled sync"
2022-11-24 08:44:47: Synchronizer: "Sync: starting: Starting synchronisation to target 7... supportsAccurateTimestamp = false; supportsMultiPut = false [1669275887231]"
2022-11-24 08:44:47: Synchronizer: "Indexing resources..."
2022-11-24 08:44:47: "ResourceService::indexNoteResources: Start"
2022-11-24 08:44:47: models/Setting: "Saving settings..."
2022-11-24 08:44:47: "ResourceService::indexNoteResources: Completed"
2022-11-24 08:44:47: models/Folder: "updateFolderShareIds:", "{"shareUpdateCount":0,"unshareUpdateCount":0}"
2022-11-24 08:44:47: models/Folder: "updateNoteShareIds: notes to update:", "0"
2022-11-24 08:44:47: FileApi: "get info.json"
2022-11-24 08:44:47: models/Setting: "Settings have been saved."
2022-11-24 08:44:48: models/Setting: "Saving settings..."
2022-11-24 08:44:48: Synchronizer: "Sync target remote info:", "{"version_":3,"masterKeys_":[],"e2ee_":{"value":false,"updatedTime":0},"activeMasterKeyId_":{"value":"","updatedTime":0},"ppk_":{"value":null,"updatedTime":0}}"
2022-11-24 08:44:48: Synchronizer: "Sync target is already setup - checking it..."
2022-11-24 08:44:48: Synchronizer: "Sync target local info:", "{"version_":3,"masterKeys_":[],"e2ee_":{"value":false,"updatedTime":0},"activeMasterKeyId_":{"value":"","updatedTime":0},"ppk_":{"value":null,"updatedTime":0}}"
2022-11-24 08:44:48: FileApi: "list "
2022-11-24 08:44:48: models/Setting: "Settings have been saved."
2022-11-24 08:44:48: FileApi: "put temp/timeCheck771948.txt", "null"
2022-11-24 08:44:49: FileApi: "stat temp/timeCheck771948.txt"
2022-11-24 08:44:50: RevisionService: "maintenance: Starting..."
2022-11-24 08:44:50: RevisionService: "maintenance: Service is enabled"
2022-11-24 08:44:50: RevisionService: "collectRevisions: Created revisions for 0 notes"
2022-11-24 08:44:50: RevisionService: "maintenance: Done in 106ms"
2022-11-24 08:44:56: "SearchEngine: Updating FTS table..."
2022-11-24 08:44:56: "SearchEngine: Updated FTS table in 1ms. Inserted: 0. Deleted: 0"
2022-11-24 08:45:12: FileApi: "Could not retrieve remote date - defaulting to device date:", "Error: POST files/get_metadata: Error (400): Error in call to API function "files/get_metadata": Unknown API function: /2/files/get_metadata
Error: POST files/get_metadata: Error (400): Error in call to API function "files/get_metadata": Unknown API function: /2/files/get_metadata
    at newError (/snap/joplin-desktop/28/opt/joplin-desktop/resources/app/node_modules/@joplin/lib/DropboxApi.js:178:20)
    at DropboxApi.exec (/snap/joplin-desktop/28/opt/joplin-desktop/resources/app/node_modules/@joplin/lib/DropboxApi.js:191:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async FileApiDriverDropbox.stat (/snap/joplin-desktop/28/opt/joplin-desktop/resources/app/node_modules/@joplin/lib/file-api-driver-dropbox.js:30:21)"
2022-11-24 08:45:12: FileApi: "put locks/1_1_d6976273840344c58db725edf3849a2f.json", "null"
2022-11-24 08:45:13: FileApi: "list "
2022-11-24 08:45:13: FileApi: "stat 434abec3f3474ccd98c98d4fa76fa9cd.md"
2022-11-24 08:45:16: "ResourceService::indexNoteResources: Start"
2022-11-24 08:45:16: "ResourceService::indexNoteResources: Completed"
2022-11-24 08:45:16: "ResourceService::deleteOrphanResources:", "[]"
2022-11-24 08:45:35: FileApi: "list "
2022-11-24 08:45:36: Synchronizer: "Error: POST files/get_metadata: Error (400): Error in call to API function "files/get_metadata": Unknown API function: /2/files/get_metadata
Error: POST files/get_metadata: Error (400): Error in call to API function "files/get_metadata": Unknown API function: /2/files/get_metadata
    at newError (/snap/joplin-desktop/28/opt/joplin-desktop/resources/app/node_modules/@joplin/lib/DropboxApi.js:178:20)
    at DropboxApi.exec (/snap/joplin-desktop/28/opt/joplin-desktop/resources/app/node_modules/@joplin/lib/DropboxApi.js:191:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async FileApiDriverDropbox.stat (/snap/joplin-desktop/28/opt/joplin-desktop/resources/app/node_modules/@joplin/lib/file-api-driver-dropbox.js:30:21)"
2022-11-24 08:45:36: FileApi: "delete locks/1_1_d6976273840344c58db725edf3849a2f.json"
2022-11-24 08:45:37: Synchronizer: "Sync: finished: Synchronisation finished [1669275887231]"
2022-11-24 08:45:37: Synchronizer: "Operations completed: "
2022-11-24 08:45:37: Synchronizer: "Total folders: 27"
2022-11-24 08:45:37: Synchronizer: "Total notes: 237"
2022-11-24 08:45:37: Synchronizer: "Total resources: 0"
2022-11-24 08:45:37: Synchronizer: "There was some errors:"
2022-11-24 08:45:37: Synchronizer: "Error: POST files/get_metadata: Error (400): Error in call to API function "files/get_metadata": Unknown API function: /2/files/get_metadata
Error: POST files/get_metadata: Error (400): Error in call to API function "files/get_metadata": Unknown API function: /2/files/get_metadata
    at newError (/snap/joplin-desktop/28/opt/joplin-desktop/resources/app/node_modules/@joplin/lib/DropboxApi.js:178:20)
    at DropboxApi.exec (/snap/joplin-desktop/28/opt/joplin-desktop/resources/app/node_modules/@joplin/lib/DropboxApi.js:191:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async FileApiDriverDropbox.stat (/snap/joplin-desktop/28/opt/joplin-desktop/resources/app/node_modules/@joplin/lib/file-api-driver-dropbox.js:30:21)"
2022-11-24 08:45:37: "Setting up recurrent sync with interval 300"
2022-11-24 08:45:37: "Updating all notifications..."
2022-11-24 08:45:37: "Garbage collecting alarms..."
2022-11-24 08:45:37: "Sync has finished and note has never been changed - reloading it"
2022-11-24 08:45:38: "DecryptionWorker: cannot start because no master key is currently loaded."
2022-11-24 08:45:57: models/Setting: "Saving settings..."
2022-11-24 08:45:57: models/Setting: "Settings have been saved."
```

</details>

**Comment by Eimis-dev** [comment]
Can confirm, experiencing same issue:

![image](https://user-images.githubusercontent.com/10908092/203731033-c0ced496-a1a8-49d3-a02d-e16dc9be08fb.png)

**Comment by mcmxcdev** [comment]
I was able to solve this issue by going to "Settings" > "Synchronization > "Show Advanced Settings" and then clicking "Re-upload local data to sync target" on macOS.

Then I let Linux and iPhone download the up-to-date sync data.

I would consider this a workaround though and not a solution to the issue at hand.

**Comment by wh201906** [comment]
Can you reproduce it now? Since v2.8.8 is a stable release and it have been working fine for months, I don't think it's something wrong in the Joplin code. Maybe it's just a occasional error from the Dropbox server.

**Comment by mcmxcdev** [comment]
Yeah seems like it. Haven't had any issues with it anymore after I re-uploaded local to sync target.

**Comment by JanZeman** [comment]
I just started my search and the same error message brought me here. I am only few minutes on the issue but my first idea is that this problem is not caused by any error in this repository but by [the issue on the Dropbox endpoint](https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/https-api-dropboxapi-com-2-files-get-metadata/m-p/639038) that seems to be fixed by now.

The second hint for my thought is the time. This issue reported 5 days ago - exactly the same day when the same issue got reported for some of my app users...

Can you please confirm the error is not reproducible any more as of today (November 29, 2002)?

**Comment by mcmxcdev** [comment]
I haven't experience this issue anymore and it seems to be on Dropbox's end and not related to Joplin.

**Comment by JanZeman** [comment]
Yes, I got it confirmed directly from Dropbox community. It is safe to close this ticket without any further action in this repository.
