### ISSUE TITLE
Compiling/Running from source on Linux fails.

### ISSUE THREAD

**Issue by tofuhead** [laurent22/joplin#742]
### Operating system

- Linux
(Kubuntu 18.04)

### Application

- Desktop

after compiling (according to instructions) I ran the application with provided run.sh,
all I got was empty application view, with developer tools.  and on the devtool console
I have this error:

Uncaught Error: Cannot find module '/home/basse/src/joplin/ElectronClient/app/node_modules/sqlite3/lib/binding/electron-v1.8-linux-x64/node_sqlite3.node'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (/home/basse/src/joplin/ElectronClient/app/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/basse/src/joplin/ElectronClient/app/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Object.<anonymous> (/home/basse/src/joplin/ElectronClient/app/node_modules/sqlite3/lib/sqlite3.js:190:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)

**Comment by laurent22** [comment]
Did you run `yarn dist` too?

**Comment by tofuhead** [comment]
yes, it just said:
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'dist'

**Comment by laurent22** [comment]
Could you follow the build instructions step by step and show the output of each command?

**Comment by tofuhead** [comment]
hi,
I started fresh, so here are all the info.
[joplin.txt](https://github.com/laurent22/joplin/files/2446353/joplin.txt)

it's a long one ,but you wanted the output of each command :) 
some warnings, but errors that I see are:

basse@roboduck:  ~/src/joplin/ElectronClient/app [master]
 ♥ yarn dist                                                                                                                                                       
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'dist'

and while running the app (run.sh) I get empty window with developer tools saying:

module.js:487 Uncaught Error: Cannot find module '/home/basse/src/joplin/ElectronClient/app/node_modules/sqlite3/lib/binding/electron-v1.8-linux-x64/node_sqlite3.node'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (/home/basse/src/joplin/ElectronClient/app/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/basse/src/joplin/ElectronClient/app/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Object.<anonymous> (/home/basse/src/joplin/ElectronClient/app/node_modules/sqlite3/lib/sqlite3.js:190:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)

that definetely is missing, my /home/basse/src/joplin/ElectronClient/app/node_modules/sqlite3/lib/binding/ looks like this:
basse@roboduck:  ~/src/joplin/ElectronClient/app/node_modules/sqlite3/lib/binding [master]
 ♥ l
total 12K
drwxrwxr-x 3 basse basse 4,0K loka   4 15:41 ./
drwxrwxr-x 3 basse basse 4,0K loka   4 15:41 ../
drwxrwxr-x 2 basse basse 4,0K loka   4 15:41 node-v57-linux-x64/

.b

**Comment by laurent22** [comment]
`ERROR: [Errno 2] No such file or directory: 'dist'` might be the issue since it's `yarn dist` that should compile the modules for use with Electron. Could you try to manually create this directory in `ElectronClient/app/dist` and run `yarn dist` again and all the commands after that?

**Comment by tofuhead** [comment]
♥ yarn dist                                                                                                                                                       1
00h00m00s 0/0: : ERROR: [Errno 21] Is a directory: 'dist'

.b

**Comment by laurent22** [comment]
What "yarn" was it then? Was it just an old version, or a completely different program?
