### ISSUE TITLE
Server upgrade to latest version does not start

### ISSUE THREAD

**Issue by nzlov** [laurent22/joplin#7446]
-- | -- | -- | --
-- | -- | -- | --
sha256:d90853d279bd1e806e38fedad76038... Unused | joplin/server:<none> | 1.2 GB | 2022-10-11 19:05:31
sha256:f9f69a3c0e9604ab5ed016b63b1b3c... | joplin/server:latest | 2.6 GB | 2021-11-13 21:06:50

The mirror image is a bit large...
Update server from `d90853d2` to `latest`.

## log:
```
> @joplin/server@2.6.10 start

> node dist/app.js


2022-12-13 07:08:51: App: Starting server v2.6.10 (prod) on port 22300 and PID 19...

2022-12-13 07:08:51: App: Running in Docker: true

2022-12-13 07:08:51: App: Public base URL: https://xxx.com

2022-12-13 07:08:51: App: API base URL: https://xxx.com

2022-12-13 07:08:51: App: User content base URL: https://xxx.com

2022-12-13 07:08:51: App: Log dir: /home/joplin/packages/server/logs

2022-12-13 07:08:51: App: DB Config: {

  client: 'pg',

  name: 'joplin',

  slowQueryLogEnabled: false,

  slowQueryLogMinDuration: 1000,

  autoMigration: true,

  user: '',

  password: '*******',

  port: ,

  host: '172.17.0.1'

}

2022-12-13 07:08:51: App: Mailer Config: {

  enabled: false,

  host: '',

  port: 587,

  secure: true,

  authUser: '',

  authPassword: '********',

  noReplyName: '',

  noReplyEmail: ''

}

2022-12-13 07:08:51: App: Content driver: { type: 2, path: '/data' }

2022-12-13 07:08:51: App: Content driver (fallback): null

2022-12-13 07:08:51: App: Trying to connect to database...

2022-12-13 07:08:51: App: Connection check: {

  latestMigration: { name: '20220403172253_published_note_links.js', done: true },

  isCreated: true,

  error: null

}

2022-12-13 07:08:51: App: Auto-migrating database...

Error: The migration directory is corrupt, the following files are missing: 20211204191051_user_deletion.js, 20220121172409_email_recipient_default.js, 20220131185922_account_disabled_timestamp.js, 20220201151223_backup_items.js, 20220403172253_published_note_links.js

    at validateMigrationList (/home/joplin/packages/server/node_modules/knex/lib/migrations/migrate/Migrator.js:575:11)

    at Migrator.latest (/home/joplin/packages/server/node_modules/knex/lib/migrations/migrate/Migrator.js:70:7)

    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

## docker-compose.yaml

```
version: '3.1'
services:
    app:
        image: joplin/server:latest
        ports:
            - "22300:22300"
        restart: unless-stopped
        volumes:
         - /etc/localtime:/etc/localtime
         - /docs/lib/joplin:/data
        environment:
            - APP_PORT=22300
            - APP_BASE_URL=https://xxx.com
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=
            - POSTGRES_DATABASE=
            - POSTGRES_USER=
            - POSTGRES_PORT=
            - POSTGRES_HOST=
            - STORAGE_DRIVER=Type=Filesystem; Path=/data
            - STORAGE_DRIVER_FALLBACK=Type=Database; Mode=ReadAndWrite
```

**Comment by nzlov** [comment]
My problem, the image that docker pulls is actually much older. It's a docker repository mirror issue.
