### ISSUE TITLE
Desktop/Plugin API: `insertText` with an image in the rich text editor changes inserted content

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#7547]
# Details

## Environment

Joplin version: 2.9.17 and cf300bc842a76ab42dc91bbdc9c22f56a203dbdd, 2.13.4
Platform: Linux
OS specifics: Ubuntu 23.10

## Steps to reproduce

Minimal example: https://github.com/personalizedrefrigerator/bug-report/tree/joplin-image-inserttext-plugin-bug

1. Open the rich text editor
2. Call `await joplin.commands.execute('insertText', '![](:/some-svg-image-resource-id)');` from a plugin where `:/some-svg-image-resource-id` is the ID of some SVG image resource.
3. Switch back to the markdown editor.

## Observed behavior

The text
```html
<img src="data:;base64,
		<svg width=" 1700"="" height="1536" xmlns="http://www.w3.org/2000/svg">  " />
```
is inserted if the command is run in the rich text editor.

The text `![](:/some-svg-image-resource-id)` is inserted if the command is run in the markdown editor.

## Expected behavior

The SVG image should be visible in the rich text editor and have markdown `![](:/some-svg-image-resource-id)` in the markdown editor.

## Logfile

<details><summary>Log</summary>

```
Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtoolsYou might need to use a local HTTP server (instead of file://): https://reactjs.org/link/react-devtools-faq
main-html.js:49 Environment: dev
main-html.js:49 appId: net.cozic.joplindev-desktop
main-html.js:49 appType: desktop
main-html.js:45 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
  Policy set or a policy with "unsafe-eval" enabled. This exposes users of
  this app to unnecessary security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
output.warn @ main-html.js:45
main-html.js:49 05:02:28: App: Profile directory: /home/builder/.config/joplindev-desktop
main-html.js:49 05:02:28: App: Root profile directory: /home/builder/.config/joplindev-desktop
main-html.js:49 05:02:28: Database was open successfully
main-html.js:49 05:02:28: Checking for database schema update...
main-html.js:49 05:02:28: Current database version Object
main-html.js:49 05:02:28: Upgrading database from version 41
main-html.js:49 05:02:28: New version: 41. Previously recorded version: 41
main-html.js:49 05:02:28: KeychainService: checking if keychain supported
main-html.js:49 05:02:28: KeychainService: check was already done - skipping. Supported: 0
main-html.js:49 05:02:28: e2ee/utils: Master password is not set - trying to get it from the active master key...
main-html.js:49 05:02:28: handleSyncStartupOperation: Processing operation: 0
main-html.js:49 05:02:28: App: Client ID: f35f0d4e8e8845f3a8f002450337bfed
main-html.js:49 05:02:28: models/Setting: Applying default migrations...
main-html.js:49 05:02:28: e2ee/utils: Trying to load 0 master keys...
main-html.js:49 05:02:28: e2ee/utils: Loaded master keys: 0
main-html.js:49 05:02:28: ResourceFetcher: Auto-add resources: Mode: always
main-html.js:49 05:02:28: ResourceFetcher: Auto-added resources: 0
main-html.js:49 05:02:28: App: "syncInfoCache" was changed - setting up encryption related code
main-html.js:49 05:02:28: e2ee/utils: Trying to load 0 master keys...
main-html.js:49 05:02:28: e2ee/utils: Loaded master keys: 0
main-html.js:49 05:02:28: Scheduling sync operation... 10000
main-html.js:49 05:02:28: Setting up recurrent sync with interval 3600
main-html.js:49 05:02:28: Recurrent sync operation DISABLED!!!
main-html.js:49 05:02:28: App: "syncInfoCache" was changed - setting up encryption related code
main-html.js:49 05:02:28: e2ee/utils: Trying to load 0 master keys...
main-html.js:49 05:02:28: e2ee/utils: Loaded master keys: 0
main-html.js:49 05:02:28: Scheduling sync operation... 10000
main-html.js:49 05:02:28: App: "syncInfoCache" was changed - setting up encryption related code
main-html.js:49 05:02:28: e2ee/utils: Trying to load 0 master keys...
main-html.js:49 05:02:28: e2ee/utils: Loaded master keys: 0
main-html.js:49 05:02:28: Scheduling sync operation... 10000
main-html.js:49 05:02:28: app.start: doing regular boot
main-html.js:49 05:02:28: App: Refreshing notes: null null
main-html.js:49 05:02:28: App: "syncInfoCache" was changed - setting up encryption related code
main-html.js:49 05:02:28: e2ee/utils: Trying to load 0 master keys...
main-html.js:49 05:02:28: e2ee/utils: Loaded master keys: 0
main-html.js:49 05:02:28: Scheduling sync operation... 10000
main-html.js:49 05:02:28: Setting up recurrent sync with interval 3600
main-html.js:49 05:02:28: Recurrent sync operation DISABLED!!!
main-html.js:49 05:02:28: App: "syncInfoCache" was changed - setting up encryption related code
main-html.js:49 05:02:28: e2ee/utils: Trying to load 0 master keys...
main-html.js:49 05:02:28: e2ee/utils: Loaded master keys: 0
main-html.js:49 05:02:28: Scheduling sync operation... 10000
main-html.js:49 05:02:28: App: "syncInfoCache" was changed - setting up encryption related code
main-html.js:49 05:02:28: e2ee/utils: Trying to load 0 master keys...
main-html.js:49 05:02:28: e2ee/utils: Loaded master keys: 0
main-html.js:49 05:02:28: Scheduling sync operation... 10000
main-html.js:49 05:02:28: Updating all notifications...
main-html.js:49 05:02:28: Garbage collecting alarms...
main-html.js:49 05:02:28: RevisionService: runInBackground: Starting background service with revision collection interval 600000
main-html.js:49 05:02:28: App: Refreshing notes: 2 446fb3a0731b4f32a2777700f15d681a
main-html.js:49 05:02:28: defaultPluginsUtils: Could not find default plugins' directory: /home/builder/Documents/Build/joplin/packages/app-desktop/build/defaultPlugins - skipping installation.
main-html.js:49 05:02:28: PluginService: Loading plugin from /home/builder/.config/joplindev-desktop/cache/com.github.marc0l92.joplin-plugin-drawio
main-html.js:49 05:02:28: PluginService: Loading plugin from /home/builder/Documents/Build/joplin-plugin-freehand-drawing
main-html.js:49 05:02:28: PluginService: Loading plugin from /home/builder/Documents/Build/bug-reports
main-html.js:49 05:02:28: SpellCheckerServiceDriverNative: Set effective languages to "en-US"
MainScreen.tsx:318 Uncaught TypeError: Cannot set properties of null (setting 'width')
    at MainScreen.tsx:318:15
    at Immer.produce (immerClass.ts:119:13)
    at MainScreenComponent.updateRootLayoutSize (MainScreen.tsx:316:32)
    at MainScreenComponent.window_resize (MainScreen.tsx:254:8)
(anonymous) @ MainScreen.tsx:318
produce @ immerClass.ts:119
updateRootLayoutSize @ MainScreen.tsx:316
window_resize @ MainScreen.tsx:254
main-html.js:49 05:02:29: Loading existing note 8833a9b6bc764528a02671bf5ca83eb3
main-html.js:49 05:02:29: PluginRunner: Got message (3): joplin.plugins.register {onStart: ƒ}
main-html.js:49 05:02:29: joplin.plugins: Starting plugin: io.github.personalizedrefrigerator.js-draw
main-html.js:49 05:02:29: PluginRunner: Got message (3): joplin.plugins.register {onStart: ƒ}
main-html.js:49 05:02:29: joplin.plugins: Starting plugin: com.github.marc0l92.joplin-plugin-drawio
main-html.js:49 05:02:29: PluginRunner: Got message (3): joplin.plugins.register {onStart: ƒ}
main-html.js:49 05:02:29: joplin.plugins: Starting plugin: com.github.personalizedrefrigerator.inserttext-bug
main-html.js:49 05:02:29: Loaded note: {id: '8833a9b6bc764528a02671bf5ca83eb3', parent_id: '446fb3a0731b4f32a2777700f15d681a', title: 'Test', body: '![Test image](:/eba9c4999f4849df8d78b975a70df3a0)', created_time: 1669182810116, …}
main-html.js:49 05:02:29: PluginRunner: Got message (3): joplin.views.dialogs.create jop-freehand-drawing-jsdraw-plugin-jsDrawDialog
main-html.js:49 Loading script /home/builder/Documents/Build/joplin/packages/app-desktop/vendor/lib/tinymce/tinymce.min.js
main-html.js:49 Loading script: {src: '/home/builder/Documents/Build/joplin/packages/app-desktop/vendor/lib/tinymce/tinymce.min.js', id: 'tinyMceScript', loaded: false}
main-html.js:49 05:02:29: PluginRunner: Got message (3): joplin.commands.register {name: 'minimal-bug-example-insertText', label: 'insertText with an SVG image resource', iconName: 'fas fa-floppy-disk', execute: ƒ}
main-html.js:49 05:02:29: joplin.plugins: Uncaught exception in plugin "com.github.marc0l92.joplin-plugin-drawio": Error: ENOENT: no such file or directory, stat '/tmp/joplin-drawio-plugin/'
    at statSync (node:fs:1538:3)
    at e.statSync (node:electron/js2c/asar_bundle:5:4539)
    at __node_internal_ (node:internal/fs/utils:793:8)
    at Object.rmdirSync (node:fs:1156:15)
    at t.clearDiskCache (/home/builder/.config/joplindev-desktop/tmp/plugin_com.github.marc0l92.joplin-plugin-drawio.js:1:4250)
    at /home/builder/.config/joplindev-desktop/tmp/plugin_com.github.marc0l92.joplin-plugin-drawio.js:1:9886
    at Generator.next (<anonymous>)
    at /home/builder/.config/joplindev-desktop/tmp/plugin_com.github.marc0l92.joplin-plugin-drawio.js:1:9465
    at new Promise (<anonymous>)
    at n (/home/builder/.config/joplindev-desktop/tmp/plugin_com.github.marc0l92.joplin-plugin-drawio.js:1:9210)
output.<computed> @ main-html.js:49
log @ Logger.ts:219
error @ Logger.ts:93
(anonymous) @ JoplinPlugins.ts:46
Promise.catch (async)
(anonymous) @ JoplinPlugins.ts:40
(anonymous) @ /home/builder/Documents/Build/joplin/packages/lib/services/plugins/api/JoplinPlugins.js:8
__awaiter @ /home/builder/Documents/Build/joplin/packages/lib/services/plugins/api/JoplinPlugins.js:4
register @ JoplinPlugins.ts:30
(anonymous) @ executeSandboxCall.ts:44
(anonymous) @ /home/builder/Documents/Build/joplin/packages/lib/services/plugins/utils/executeSandboxCall.js:8
__awaiter @ /home/builder/Documents/Build/joplin/packages/lib/services/plugins/utils/executeSandboxCall.js:4
executeSandboxCall @ executeSandboxCall.ts:28
(anonymous) @ PluginRunner.ts:173
(anonymous) @ /home/builder/Documents/Build/joplin/packages/app-desktop/services/plugins/PluginRunner.js:8
__awaiter @ /home/builder/Documents/Build/joplin/packages/app-desktop/services/plugins/PluginRunner.js:4
(anonymous) @ PluginRunner.ts:136
emit @ node:events:538
onMessage @ node:electron/js2c/renderer_init:69
main-html.js:49 05:02:29: joplin.plugins: Finished running onStart handler: com.github.marc0l92.joplin-plugin-drawio (Took 174ms)
main-html.js:49 05:02:29: DecryptionWorker: cannot start because no master key is currently loaded.
main-html.js:49 Loading script gui/NoteEditor/NoteBody/TinyMCE/plugins/lists.js
main-html.js:49 Loading script: {src: 'gui/NoteEditor/NoteBody/TinyMCE/plugins/lists.js', id: 'tinyMceListsPluginScript', loaded: false}
main-html.js:49 05:02:29: PluginRunner: Got message (3): joplin.commands.register {name: 'jop-freehand-drawing-jsdraw-plugin-insertDrawing', label: 'Insert Drawing', iconName: 'fas fa-pen-alt', execute: ƒ}
main-html.js:49 05:02:29: joplin.plugins: Finished running onStart handler: com.github.personalizedrefrigerator.inserttext-bug (Took 285ms)
main-html.js:49 05:02:29: PluginRunner: Got message (3): joplin.views.toolbarButtons.create jop-freehand-drawing-jsdraw-plugin-insertDrawing jop-freehand-drawing-jsdraw-plugin-insertDrawing editorToolbar
main-html.js:49 05:02:29: PluginRunner: Got message (3): joplin.commands.register {name: 'jop-freehand-drawing-jsdraw-plugin-restoreAutosave', label: 'Restore from autosaved drawing', iconName: 'fas fa-floppy-disk', execute: ƒ}
main-html.js:49 05:02:29: models/Setting: Saving settings...
main-html.js:49 05:02:29: PluginRunner: Got message (3): joplin.commands.register {name: 'jop-freehand-drawing-jsdraw-plugin-deleteAutosave', label: 'Delete all autosaved drawings', iconName: 'fas fa-trash-can', execute: ƒ}
main-html.js:49 05:02:29: PluginRunner: Got message (3): joplin.contentScripts.register markdownItPlugin jsdraw__markdownIt_editDrawingButton ./contentScripts/markdownIt.js
main-html.js:49 05:02:29: Plugin: "io.github.personalizedrefrigerator.js-draw": Registered content script: markdownItPlugin: jsdraw__markdownIt_editDrawingButton: /home/builder/Documents/Build/joplin-plugin-freehand-drawing/dist/contentScripts/markdownIt.js
main-html.js:49 05:02:29: PluginRunner: Got message (3): joplin.contentScripts.onMessage jsdraw__markdownIt_editDrawingButton (...args) => __awaiter(this, void 0, void 0, function* () {
            const callbackId = `cb_${pluginId}_${Date.now()}_${callbackIndex++}`;
            const promise = new Promise((resolve, reject)…
main-html.js:49 05:02:29: joplin.plugins: Finished running onStart handler: io.github.personalizedrefrigerator.js-draw (Took 421ms)
main-html.js:49 Got ipc-message: noteRenderComplete null
main-html.js:49 Got ipc-message: noteRenderComplete null
index.html:1 ReferenceError: webviewApi is not defined
    at index.html:1:587
    at HTMLImageElement.onload (index.html:1:811)
(anonymous) @ index.html:1
onload @ index.html:1
load (async)
html @ tinymce.min.js:9
b @ tinymce.min.js:9
Ag @ tinymce.min.js:9
(anonymous) @ tinymce.min.js:9
fold @ tinymce.min.js:9
Rg @ tinymce.min.js:9
setContent @ tinymce.min.js:9
Qh @ tinymce.min.js:9
Tx.setContent @ tinymce.min.js:9
(anonymous) @ TinyMCE.tsx:798
fulfilled @ /home/builder/Documents/Build/joplin/packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.js:5
processTicksAndRejections @ node:internal/process/task_queues:96
Promise.then (async)
step @ /home/builder/Documents/Build/joplin/packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.js:7
(anonymous) @ /home/builder/Documents/Build/joplin/packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.js:8
__awaiter @ /home/builder/Documents/Build/joplin/packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.js:4
loadContent @ TinyMCE.tsx:791
(anonymous) @ TinyMCE.tsx:830
commitHookEffectListMount @ /home/builder/Documents/Build/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:23150
commitPassiveMountOnFiber @ /home/builder/Documents/Build/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:24926
commitPassiveMountEffects_complete @ /home/builder/Documents/Build/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:24891
commitPassiveMountEffects_begin @ /home/builder/Documents/Build/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:24878
commitPassiveMountEffects @ /home/builder/Documents/Build/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:24866
flushPassiveEffectsImpl @ /home/builder/Documents/Build/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:27039
flushPassiveEffects @ /home/builder/Documents/Build/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:26984
(anonymous) @ /home/builder/Documents/Build/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:26769
workLoop @ /home/builder/Documents/Build/joplin/packages/app-desktop/node_modules/scheduler/cjs/scheduler.development.js:266
flushWork @ /home/builder/Documents/Build/joplin/packages/app-desktop/node_modules/scheduler/cjs/scheduler.development.js:239
performWorkUntilDeadline @ /home/builder/Documents/Build/joplin/packages/app-desktop/node_modules/scheduler/cjs/scheduler.development.js:533
processImmediate @ node:internal/timers:466
index.html:1 The webview library either doesn't exist or lacks a postMessage function. Unable to display an edit button.
main-html.js:49 05:02:29: models/Setting: Settings have been saved.
DevTools failed to load source map: Could not parse content for file:///home/builder/Documents/Build/joplin/packages/app-desktop/pluginAssets/mermaid/mermaid.min.js.map: Unexpected end of JSON input
main-html.js:49 05:02:30: models/Setting: Saving settings...
main-html.js:49 05:02:30: models/Setting: Settings have been saved.
main-html.js:49 05:02:32: RevisionService: maintenance: Starting...
main-html.js:49 05:02:32: RevisionService: maintenance: Service is enabled
main-html.js:49 05:02:32: models/Setting: Saving settings...
main-html.js:49 05:02:32: models/Setting: Settings have been saved.
main-html.js:49 05:02:32: RevisionService: collectRevisions: Created revisions for 1 notes
main-html.js:49 05:02:32: RevisionService: maintenance: Done in 143ms
main-html.js:49 05:02:34: models/Setting: Saving settings...
main-html.js:49 05:02:34: models/Setting: Settings have been saved.
main-html.js:49 Got ipc-message: noteRenderComplete null
main-html.js:49 05:02:36: Saving note... {id: '8833a9b6bc764528a02671bf5ca83eb3', parent_id: '446fb3a0731b4f32a2777700f15d681a', title: 'Test', body: ''}
main-html.js:49 05:02:36: Scheduling sync operation... 30000
main-html.js:49 05:02:37: CommandService::execute: commandPalette
main-html.js:49 05:02:37: CommandService::execute: gotoAnything commandPalette
main-html.js:49 05:02:38: SearchEngine: Updating FTS table...
main-html.js:49 05:02:38: models/Setting: Saving settings...
main-html.js:49 05:02:38: models/Setting: Settings have been saved.
main-html.js:49 05:02:38: SearchEngine: Updated FTS table in 48ms. Inserted: 1. Deleted: 0
main-html.js:49 05:02:39: Saving note... {id: '8833a9b6bc764528a02671bf5ca83eb3', parent_id: '446fb3a0731b4f32a2777700f15d681a', title: 'Test', body: ''}
main-html.js:49 05:02:39: Scheduling sync operation... 30000
main-html.js:49 05:02:40: GotoAnything: gotoItem: execute command {id: 'minimal-bug-example-insertText', parent_id: null, type: 16, commandArgs: Array(0)}
main-html.js:49 05:02:40: CommandService::execute: minimal-bug-example-insertText
main-html.js:49 05:02:40: PluginRunner: Got message (3): joplin.data.post ['resources'] null {title: 'Test'} [{…}]
main-html.js:49 05:02:40: PluginRunner: Got message (3): joplin.commands.execute insertText ![Test image](:/c5220a05c23a4b2c950ffc6fee85c467)
main-html.js:49 05:02:40: CommandService::execute: insertText ![Test image](:/c5220a05c23a4b2c950ffc6fee85c467)
main-html.js:49 05:02:40: TinyMce: execCommand {name: 'insertText', value: '![Test image](:/c5220a05c23a4b2c950ffc6fee85c467)'}
main-html.js:49 Got ipc-message: noteRenderComplete null
main-html.js:49 Got ipc-message: noteRenderComplete null
main-html.js:49 05:02:41: Saving note... {id: '8833a9b6bc764528a02671bf5ca83eb3', parent_id: '446fb3a0731b4f32a2777700f15d681a', title: 'Test', body: '<img src="data:;base64,\n\t\t<svg width=" 1700"="" he…="1536" xmlns="http://www.w3.org/2000/svg">  " />'}
main-html.js:49 05:02:41: Scheduling sync operation... 30000
main-html.js:49 05:02:46: CommandService::execute: toggleEditors
data:;base64,%0A%09%09<svg width=:1          GET data:;base64,%0A%09%09<svg width= net::ERR_INVALID_URL
Image (async)
Tx.save @ tinymce.min.js:9
Tx.remove @ tinymce.min.js:9
(anonymous) @ TinyMCE.tsx:1115
safelyCallDestroy @ /home/builder/Documents/Build/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:22932
commitHookEffectListUnmount @ /home/builder/Documents/Build/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:23100
commitPassiveUnmountInsideDeletedTreeOnFiber @ /home/builder/Documents/Build/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:25098
commitPassiveUnmountEffectsInsideOfDeletedTree_begin @ /home/builder/Documents/Build/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:25048
commitPassiveUnmountEffects_begin @ /home/builder/Documents/Build/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:24956
commitPassiveUnmountEffects @ /home/builder/Documents/Build/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:24941
flushPassiveEffectsImpl @ /home/builder/Documents/Build/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:27038
flushPassiveEffects @ /home/builder/Documents/Build/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:26984
commitRootImpl @ /home/builder/Documents/Build/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:26935
commitRoot @ /home/builder/Documents/Build/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:26682
performSyncWorkOnRoot @ /home/builder/Documents/Build/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:26117
flushSyncCallbacks @ /home/builder/Documents/Build/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:12042
(anonymous) @ /home/builder/Documents/Build/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:25651
main-html.js:49 Got ipc-message: noteRenderComplete undefined
DevTools failed to load source map: Could not parse content for file:///home/builder/Documents/Build/joplin/packages/app-desktop/gui/note-viewer/pluginAssets/mermaid/mermaid.min.js.map: Unexpected end of JSON input
main-html.js:49 05:02:47: models/Setting: Saving settings...
main-html.js:49 05:02:47: models/Setting: Settings have been saved.
main-html.js:49 05:02:49: SearchEngine: Updating FTS table...
main-html.js:49 05:02:49: models/Setting: Saving settings...
main-html.js:49 05:02:49: models/Setting: Settings have been saved.
main-html.js:49 05:02:49: SearchEngine: Updated FTS table in 57ms. Inserted: 1. Deleted: 0
main-html.js:49 05:02:58: ResourceService::indexNoteResources: Start
main-html.js:49 05:02:58: models/Setting: Saving settings...
main-html.js:49 05:02:58: models/Setting: Settings have been saved.
main-html.js:49 05:02:58: ResourceService::indexNoteResources: Completed
main-html.js:49 05:02:58: ResourceService::deleteOrphanResources:
```

</details>

**Comment by vanshdeepsingh-coder** [comment]
Hi if anyone is not working on this please assign it to me

**Comment by JackGruber** [comment]
We don't assign issues, feel free to work on it.

**Comment by vanshdeepsingh-coder** [comment]
@JackGruber ok thanks

**Comment by personalizedrefrigerator** [comment]
Still an issue.

**Comment by personalizedrefrigerator** [comment]
Still an issue.
