### ISSUE TITLE
Onedrive synchronization fails since January 2023

### ISSUE THREAD

**Issue by eugenwintersberger** [laurent22/joplin#7568]
Since January 2023 it seems that synchronization with onedrive fails (on Linux and Android). 
I get the following error message in the log

```
2023-01-02 09:20:24: "Running background sync on timer..."
2023-01-02 09:20:24: "Preparing scheduled sync"
2023-01-02 09:20:24: "Could not run background sync:"
2023-01-02 09:20:24: "Error
Code: UnknownError
Header: {"_headers":{"transfer-encoding":["chunked"],"content-type":["application/json"],"content-encoding":["gzip"],"vary":["Accept-Encoding"],"strict-transport-security":["max-age=31536000"],"request-id":["66c8ae7c-caf3-4f81-9819-e1f9967f5f3d"],"client-request-id":["66c8ae7c-caf3-4f81-9819-e1f9967f5f3d"],"x-ms-ags-diagnostic":["{\"ServerInfo\":{\"DataCenter\":\"Germany West Central\",\"Slice\":\"E\",\"Ring\":\"5\",\"ScaleUnit\":\"000\",\"RoleInstance\":\"FR1PEPF000007A3\"}}"],"date":["Mon, 02 Jan 2023 08:20:24 GMT"],"connection":["close"]}}
Request: GET https://graph.microsoft.com/v1.0/me/drives/899b2a3d7e2ec28e/special/approot null null {"headers":{"Authorization":"bearer Ew ... DELIBERATELY OMITTED ... X1a/+V
Error
    at OneDriveApi.oneDriveErrorResponseToError (/tmp/.mount_JoplinBHOUiQ/resources/app.asar/node_modules/@joplin/lib/onedrive-api.js:125:28)
    at OneDriveApi.<anonymous> (/tmp/.mount_JoplinBHOUiQ/resources/app.asar/node_modules/@joplin/lib/onedrive-api.js:307:40)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_JoplinBHOUiQ/resources/app.asar/node_modules/@joplin/lib/onedrive-api.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
2023-01-02 09:25:22: RevisionService: "maintenance: Starting..."
2023-01-02 09:25:22: RevisionService: "maintenance: Service is enabled"
2023-01-02 09:25:22: RevisionService: "collectRevisions: Created revisions for 0 notes"
2023-01-02 09:25:22: RevisionService: "maintenance: Done in 104ms"
```
This error shows up since today. I checked my logs and everything was working fine until today. The last log entry where synchronization seemed to work was on December 28th, 2022. I did not use Joplin since then and when starting it up today morning this error shows up.
 
Any ideas what went wrong here?

**Comment by GabrielOlivaw** [comment]
Hi, I'm using OneDrive too and it was working the last night. A Twitter search shows lots of people complaining about it not working so it's a problem from Microsoft's side.

**Comment by eugenwintersberger** [comment]
I was expecting this to be an MS problem. I hope this will be fixed soon ...

**Comment by newbieh4cker** [comment]
Fails on macOS (m1) too using Joplin 2.9.17

```2023-01-02 19:09:17: "Preparing scheduled sync"
2023-01-02 19:09:17: "Starting scheduled sync"
2023-01-02 19:09:17: Synchronizer: "Sync: starting: Starting synchronisation to target 3... supportsAccurateTimestamp = false; supportsMultiPut = false [1672654157826]"
2023-01-02 19:09:17: Synchronizer: "Indexing resources..."
2023-01-02 19:09:17: "ResourceService::indexNoteResources: Start"
2023-01-02 19:09:17: "ResourceService::indexNoteResources: Completed"
2023-01-02 19:09:17: OneDriveApi: "Got unhandled error:", "ERR_UNESCAPED_CHARACTERS", "Request path contains unescaped characters", "TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
Code: ERR_UNESCAPED_CHARACTERS
TypeError: Request path contains unescaped characters
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at new NodeError (node:internal/errors:371:5)
    at new ClientRequest (node:_http_client:154:13)
    at request (node:https:353:10)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/node-fetch/index.js:119:13
    at new Promise (<anonymous>)
    at new Fetch (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/node-fetch/index.js:49:9)
    at Fetch (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/node-fetch/index.js:37:10)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/shim-init-node.js:456:11
    at Object.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/shim.js:164:44)
    at Generator.next (<anonymous>)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/shim.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/shim.js:4:12)
    at Object.fetchWithRetry (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/shim.js:154:16)
    at shim.fetch (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/shim-init-node.js:455:15)
    at OneDriveApi.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/onedrive-api.js:279:57)
    at Generator.next (<anonymous>)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/onedrive-api.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/onedrive-api.js:4:12)
    at OneDriveApi.exec (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/onedrive-api.js:228:16)
    at OneDriveApi.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/onedrive-api.js:397:41)
    at Generator.next (<anonymous>)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/onedrive-api.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/onedrive-api.js:4:12)
    at OneDriveApi.execText (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/onedrive-api.js:396:16)
    at FileApiDriverOneDrive.get (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api-driver-onedrive.js:114:37)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api.js:282:48
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api.js:51:38
    at Generator.next (<anonymous>)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api.js:4:12)
    at tryAndRepeat (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api.js:41:12)
    at FileApi.get (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api.js:282:16)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/syncInfoUtils.js:55:46
    at Generator.next (<anonymous>)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/syncInfoUtils.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/syncInfoUtils.js:4:12)
    at fetchSyncInfo (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/syncInfoUtils.js:54:12)
    at Synchronizer.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:412:78)
    at Generator.next (<anonymous>)
    at fulfilled (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"
2023-01-02 19:09:17: Synchronizer: "TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
Code: ERR_UNESCAPED_CHARACTERS
TypeError: Request path contains unescaped characters
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at new NodeError (node:internal/errors:371:5)
    at new ClientRequest (node:_http_client:154:13)
    at request (node:https:353:10)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/node-fetch/index.js:119:13
    at new Promise (<anonymous>)
    at new Fetch (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/node-fetch/index.js:49:9)
    at Fetch (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/node-fetch/index.js:37:10)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/shim-init-node.js:456:11
    at Object.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/shim.js:164:44)
    at Generator.next (<anonymous>)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/shim.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/shim.js:4:12)
    at Object.fetchWithRetry (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/shim.js:154:16)
    at shim.fetch (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/shim-init-node.js:455:15)
    at OneDriveApi.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/onedrive-api.js:279:57)
    at Generator.next (<anonymous>)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/onedrive-api.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/onedrive-api.js:4:12)
    at OneDriveApi.exec (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/onedrive-api.js:228:16)
    at OneDriveApi.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/onedrive-api.js:397:41)
    at Generator.next (<anonymous>)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/onedrive-api.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/onedrive-api.js:4:12)
    at OneDriveApi.execText (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/onedrive-api.js:396:16)
    at FileApiDriverOneDrive.get (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api-driver-onedrive.js:114:37)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api.js:282:48
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api.js:51:38
    at Generator.next (<anonymous>)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api.js:4:12)
    at tryAndRepeat (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api.js:41:12)
    at FileApi.get (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api.js:282:16)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/syncInfoUtils.js:55:46
    at Generator.next (<anonymous>)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/syncInfoUtils.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/syncInfoUtils.js:4:12)
    at fetchSyncInfo (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/syncInfoUtils.js:54:12)
    at Synchronizer.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:412:78)
    at Generator.next (<anonymous>)
    at fulfilled (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"
2023-01-02 19:09:17: Synchronizer: "Sync: finished: Synchronisation finished [1672654157826]"
2023-01-02 19:09:17: Synchronizer: "Operations completed: "
2023-01-02 19:09:17: Synchronizer: "Total folders: 3"
2023-01-02 19:09:17: Synchronizer: "Total notes: 3"
2023-01-02 19:09:17: Synchronizer: "Total resources: 3"
2023-01-02 19:09:17: Synchronizer: "There was some errors:"
2023-01-02 19:09:17: Synchronizer: "TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
Code: ERR_UNESCAPED_CHARACTERS
TypeError: Request path contains unescaped characters
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at new NodeError (node:internal/errors:371:5)
    at new ClientRequest (node:_http_client:154:13)
    at request (node:https:353:10)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/node-fetch/index.js:119:13
    at new Promise (<anonymous>)
    at new Fetch (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/node-fetch/index.js:49:9)
    at Fetch (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/node_modules/node-fetch/index.js:37:10)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/shim-init-node.js:456:11
    at Object.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/shim.js:164:44)
    at Generator.next (<anonymous>)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/shim.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/shim.js:4:12)
    at Object.fetchWithRetry (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/shim.js:154:16)
    at shim.fetch (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/shim-init-node.js:455:15)
    at OneDriveApi.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/onedrive-api.js:279:57)
    at Generator.next (<anonymous>)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/onedrive-api.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/onedrive-api.js:4:12)
    at OneDriveApi.exec (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/onedrive-api.js:228:16)
    at OneDriveApi.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/onedrive-api.js:397:41)
    at Generator.next (<anonymous>)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/onedrive-api.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/onedrive-api.js:4:12)
    at OneDriveApi.execText (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/onedrive-api.js:396:16)
    at FileApiDriverOneDrive.get (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api-driver-onedrive.js:114:37)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api.js:282:48
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api.js:51:38
    at Generator.next (<anonymous>)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api.js:4:12)
    at tryAndRepeat (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api.js:41:12)
    at FileApi.get (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/file-api.js:282:16)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/syncInfoUtils.js:55:46
    at Generator.next (<anonymous>)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/syncInfoUtils.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/syncInfoUtils.js:4:12)
    at fetchSyncInfo (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/synchronizer/syncInfoUtils.js:54:12)
    at Synchronizer.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:412:78)
    at Generator.next (<anonymous>)
    at fulfilled (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"
2023-01-02 19:09:17: "Sync has finished and note has never been changed - reloading it"```

**Comment by seriousfreezing** [comment]
I have a similar error, using Android + Linux, but I use Dropbox! And I can't access my notes from LInux on Android!

**Comment by laurent22** [comment]
> I have a similar error

And the error is?

**Comment by laurent22** [comment]
I'm tagging this upstream for now since it's not the first time that Microsoft breaks OneDrive

**Comment by seriousfreezing** [comment]
Hmmm... I don't know what the name of the error is, if you want I can send you the log

**Comment by laurent22** [comment]
> Hmmm... I don't know what the name of the error is, if you want I can send you the log

Yes we need the full error because for sure it's not the same as the OneDrive error, and there's a chance it's an unrelated problem

**Comment by seriousfreezing** [comment]
![image](https://user-images.githubusercontent.com/66693072/210232172-ea2931a8-c37b-410b-86b4-9720bf97c449.png)
![image](https://user-images.githubusercontent.com/66693072/210232231-66c2cdc0-684a-42d7-8b49-49d3cb7fc7d2.png)
To understand better, I put the same dropbox account and both don't show the same things!

**Comment by laurent22** [comment]
Since there's no new comments I'm going to assume they fixed the issue. If not, please post here again

**Comment by yanchou3** [comment]
i cant't link with onedrive too in my win11,having trouble in logging in onedrive.mc Edge keeps blank at https://[login.microsoftonline.com](https://login.microsoftonline.com/)/

**Comment by laurent22** [comment]
Please open another issue, and provide the log
