### ISSUE TITLE
Joplin desktop crashed when date of note edit

### ISSUE THREAD

**Issue by dmagister** [laurent22/joplin#7608]
When trying to change date of the note in the note propertes app is crashed.

## Environment

Joplin version: 2.10.4
Platform: Windows, Linux
## Steps to reproduce

1. Open the note properties 
2. Click on the pencil icon with note date.

`Error
Joplin encountered a fatal error and could not continue.

To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

If the error persists you may try to [restart in safe mode](https://github.com/laurent22/joplin/issues/new?assignees=&labels=bug&template=bug_report.md&title=#), which will temporarily disable all plugins.

Message
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `NotePropertiesDialog`.

Version info
Joplin for Desktop

Copyright © 2016-2023 Laurent Cozic
Joplin 2.10.4 (prod, win32)

Идентификатор клиента: ee4bc048b76d4fcd9935ca1cced2ee9f
Синхронизированная версия: 3
Версия профиля: 41
Поддерживаемая связка ключей: Да

Изменения: 9866e59
Plugins
[
    {
        "id": "ylc395.joplinOcr",
        "name": "OCR",
        "enabled": true,
        "version": "0.3.2"
    },
    {
        "id": "plugin.calebjohn.MathMode",
        "name": "Math Mode",
        "enabled": true,
        "version": "0.5.3"
    },
    {
        "id": "io.treymo.LinkGraph",
        "name": "Link Graph UI",
        "enabled": false,
        "version": "1.5.0"
    },
    {
        "id": "com.hieuthi.joplin.life-calendar",
        "name": "Life Calendar",
        "enabled": false,
        "version": "1.4.0"
    },
    {
        "id": "io.github.makaanneo.apollo",
        "name": "Joplin Note Attachement rename",
        "enabled": true,
        "version": "1.2.2"
    },
    {
        "id": "joplin-plugin-knowledge-graph",
        "name": "Graph",
        "enabled": false,
        "version": "1.1.0"
    },
    {
        "id": "joplin.plugin.benji.favorites",
        "name": "Favorites",
        "enabled": false,
        "version": "1.3.0"
    },
    {
        "id": "joplin-plugin-conflict-resolution",
        "name": "Conflict Resolution",
        "enabled": false,
        "version": "1.2.3"
    },
    {
        "id": "aa.asrient.backstage",
        "name": "Backstage",
        "enabled": true,
        "version": "1.0.0"
    },
    {
        "id": "org.joplinapp.plugins.AutoShowActiveNoteInSideBar",
        "name": "Auto show active note in sidebar",
        "enabled": false,
        "version": "1.0.1"
    },
    {
        "id": "com.gitlab.BeatLink.joplin-plugin-agenda",
        "name": "Agenda",
        "enabled": false,
        "version": "3.7.1"
    },
    {
        "id": "com.septemberhx.Joplin.Enhancement",
        "name": "Enhancement",
        "enabled": true,
        "version": "1.1.2"
    },
    {
        "id": "ylc395.noteLinkSystem",
        "name": "Note Link System",
        "enabled": false,
        "version": "0.8.0"
    },
    {
        "id": "io.github.jackgruber.note-overview",
        "name": "Note overview",
        "enabled": true,
        "version": "1.6.0"
    },
    {
        "id": "plugin.azamahJunior.note-statistics",
        "name": "Note Statistics",
        "enabled": true,
        "version": "1.0.4"
    },
    {
        "id": "joplin.plugin.note.tabs",
        "name": "Note Tabs",
        "enabled": false,
        "version": "1.4.0"
    },
    {
        "id": "com.remove.images.from.note",
        "name": "Remove Images",
        "enabled": true,
        "version": "0.0.2"
    },
    {
        "id": "joplin.plugin.ambrt.sendSnippet",
        "name": "Send snippet to different note",
        "enabled": true,
        "version": "1.0.0"
    },
    {
        "id": "joplin.plugin.templates",
        "name": "Templates",
        "enabled": false,
        "version": "2.3.0"
    },
    {
        "id": "sadmice.TextColorize",
        "name": "Text Colorize",
        "enabled": true,
        "version": "1.2.3"
    },
    {
        "id": "org.joplinapp.plugins.Victor",
        "name": "Victor",
        "enabled": false,
        "version": "1.0.0"
    },
    {
        "id": "com.eliasvsimon.email-note",
        "name": "Email Note",
        "enabled": true,
        "version": "1.2.2"
    },
    {
        "id": "io.github.jackgruber.backup",
        "name": "Simple Backup",
        "enabled": true,
        "version": "1.2.2"
    },
    {
        "id": "io.github.jackgruber.combine-notes",
        "name": "Combine notes",
        "enabled": true,
        "version": "1.0.1"
    },
    {
        "id": "joplin.plugin.ambrt.backlinksToNote",
        "name": "Automatic Backlinks to note",
        "enabled": false,
        "version": "3.0.3"
    },
    {
        "id": "com.whatever.quick-links",
        "name": "Quick Links",
        "enabled": false,
        "version": "1.2.3"
    },
    {
        "id": "albert.joplin.plugin.jl14",
        "name": "Delete unlinked resources",
        "enabled": true,
        "version": "1.0.0"
    },
    {
        "id": "joplin-plugin-note-encryption",
        "name": "Note encryption",
        "enabled": true,
        "version": "1.0.5"
    }
]
Stack trace
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `NotePropertiesDialog`.
    at createFiberFromTypeAndProps (C:\Users\feliks\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:28439:17)
    at createFiberFromElement (C:\Users\feliks\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:28465:15)
    at updateElement (C:\Users\feliks\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:15061:19)
    at updateSlot (C:\Users\feliks\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:15171:22)
    at reconcileChildrenArray (C:\Users\feliks\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:15349:22)
    at reconcileChildFibers (C:\Users\feliks\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:15821:16)
    at reconcileChildren (C:\Users\feliks\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:19174:28)
    at updateHostComponent (C:\Users\feliks\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:19924:3)
    at beginWork (C:\Users\feliks\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:21618:14)
    at beginWork$1 (C:\Users\feliks\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:27426:14)
Component stack

    at div
    at div
    at div
    at div
    at NotePropertiesDialog (C:\Users\feliks\AppData\Local\Programs\Joplin\resources\app.asar\gui\NotePropertiesDialog.min.js:15:3)
    at div
    at MainScreenComponent (C:\Users\feliks\AppData\Local\Programs\Joplin\resources\app.asar\gui\MainScreen\MainScreen.js:74:9)
    at ConnectFunction (C:\Users\feliks\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-redux\lib\components\connect.js:246:87)
    at div
    at NavigatorComponent (C:\Users\feliks\AppData\Local\Programs\Joplin\resources\app.asar\gui\Navigator.min.js:9:1)
    at ConnectFunction (C:\Users\feliks\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-redux\lib\components\connect.js:246:87)
    at exports.ThemeProvider (C:\Users\feliks\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:25041)
    at ae (C:\Users\feliks\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:13420)
    at RootComponent (C:\Users\feliks\AppData\Local\Programs\Joplin\resources\app.asar\gui\Root.js:103:1)
    at ConnectFunction (C:\Users\feliks\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-redux\lib\components\connect.js:246:87)
    at ErrorBoundary (C:\Users\feliks\AppData\Local\Programs\Joplin\resources\app.asar\gui\ErrorBoundary.js:21:9)
    at Provider (C:\Users\feliks\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-redux\lib\components\Provider.js:19:3)`

**Comment by laurent22** [comment]
This is fixed in 6b9a2702259dc1e5c9ff13aef50ab9d54bd251f2 It will be in 2.10.5
