### ISSUE TITLE
NotePropertiesDialog crashes Joplin

### ISSUE THREAD

**Issue by schwaschwa** [laurent22/joplin#7619]
## Environment

Joplin version: 2.10.4
Platform: macOS
OS specifics:  macOS Big Sur 11.6.1

## Steps to reproduce

1. Open Joplin
2. Click "i"-button (properties) inside a note
3. Click pen-button, to change date created or click pen-button to change date of last change

## Describe what you expected to happen

opens dialogue to change the date

## Logfile

Error
Joplin encountered a fatal error and could not continue.

To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

If the error persists you may try to [restart in safe mode](https://github.com/laurent22/joplin/issues/new?assignees=&labels=bug&template=bug_report.md&title=#), which will temporarily disable all plugins.

Message
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `NotePropertiesDialog`.

Version info
Joplin for Desktop

Copyright © 2016-2023 Laurent Cozic
Joplin 2.10.4 (prod, darwin)

Client-ID: -
Sync-Version: 3
Profil-Version: 41
Unterstützter Schlüsselbund: Ja

Revision: 9866e59
Plugins
[
    {
        "id": "ylc395.noteLinkSystem",
        "name": "Note Link System",
        "enabled": true,
        "version": "0.8.0"
    },
    {
        "id": "joplin.plugin.ambrt.convertToNewNote",
        "name": "Convert Text To New Note",
        "enabled": true,
        "version": "1.5.1"
    },
    {
        "id": "io.github.jackgruber.note-overview",
        "name": "Note overview",
        "enabled": true,
        "version": "1.6.0"
    },
    {
        "id": "com.plugin.randomNotePlugin",
        "name": "Random note",
        "enabled": true,
        "version": "1.0.3"
    },
    {
        "id": "outline",
        "name": "Outline",
        "enabled": false,
        "version": "1.5.4"
    },
    {
        "id": "io.github.jackgruber.copytags",
        "name": "Tagging",
        "enabled": true,
        "version": "1.0.1"
    },
    {
        "id": "com.whatever.inline-tags",
        "name": "Inline tags",
        "enabled": true,
        "version": "1.2.1"
    },
    {
        "id": "com.andrejilderda.macOSTheme",
        "name": "macOS theme",
        "enabled": false,
        "version": "1.3.5"
    },
    {
        "id": "joplin.plugin.ambrt.copyNoteLink",
        "name": "Copy link to active note",
        "enabled": true,
        "version": "1.0.1"
    },
    {
        "id": "io.github.jackgruber.combine-notes",
        "name": "Combine notes",
        "enabled": true,
        "version": "1.0.1"
    },
    {
        "id": "com.hieuthi.joplin.life-calendar",
        "name": "Life Calendar",
        "enabled": true,
        "version": "1.4.0"
    },
    {
        "id": "ylc395.betterMarkdownViewer",
        "name": "Cursor Sync",
        "enabled": false,
        "version": "2.0.5"
    },
    {
        "id": "joplin.plugin.note.tabs",
        "name": "Note Tabs",
        "enabled": true,
        "version": "1.4.0"
    },
    {
        "id": "plugin.calebjohn.rich-markdown",
        "name": "Rich Markdown",
        "enabled": false,
        "version": "0.13.2"
    },
    {
        "id": "joplin.plugin.alondmnt.history-panel",
        "name": "History Panel",
        "enabled": true,
        "version": "1.0.1"
    },
    {
        "id": "com.lki.homenote",
        "name": "Home Note",
        "enabled": true,
        "version": "1.0.4"
    },
    {
        "id": "com.hieuthi.joplin.slash-commands",
        "name": "Slash Commands: Datetime & More",
        "enabled": true,
        "version": "1.3.2"
    },
    {
        "id": "joplin.plugin.ambrt.backlinksToNote",
        "name": "Automatic Backlinks to note",
        "enabled": false,
        "version": "3.0.3"
    },
    {
        "id": "joplin-plugin-knowledge-graph",
        "name": "Graph",
        "enabled": false,
        "version": "1.1.0"
    }
]
Stack trace
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `NotePropertiesDialog`.
    at createFiberFromTypeAndProps (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:28439:17)
    at createFiberFromElement (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:28465:15)
    at updateElement (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:15061:19)
    at updateSlot (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:15171:22)
    at reconcileChildrenArray (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:15349:22)
    at reconcileChildFibers (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:15821:16)
    at reconcileChildren (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:19174:28)
    at updateHostComponent (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:19924:3)
    at beginWork (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:21618:14)
    at beginWork$1 (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:27426:14)
Component stack

    at div
    at div
    at div
    at div
    at NotePropertiesDialog (/Applications/Joplin.app/Contents/Resources/app.asar/gui/NotePropertiesDialog.min.js:15:3)
    at div
    at MainScreenComponent (/Applications/Joplin.app/Contents/Resources/app.asar/gui/MainScreen/MainScreen.js:74:9)
    at ConnectFunction (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-redux/lib/components/connect.js:246:87)
    at div
    at NavigatorComponent (/Applications/Joplin.app/Contents/Resources/app.asar/gui/Navigator.min.js:9:1)
    at ConnectFunction (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-redux/lib/components/connect.js:246:87)
    at exports.ThemeProvider (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/styled-components/dist/styled-components.cjs.js:1:25041)
    at ae (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/styled-components/dist/styled-components.cjs.js:1:13420)
    at RootComponent (/Applications/Joplin.app/Contents/Resources/app.asar/gui/Root.js:103:1)
    at ConnectFunction (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-redux/lib/components/connect.js:246:87)
    at ErrorBoundary (/Applications/Joplin.app/Contents/Resources/app.asar/gui/ErrorBoundary.js:21:9)
    at Provider (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-redux/lib/components/Provider.js:19:3)

***

Thanks in advance for any kind of help

**Comment by laurent22** [comment]
It will be fixed in next pre-release
