### ISSUE TITLE
Starting terminal application gives this error. 

### ISSUE THREAD

**Issue by kumit12** [laurent22/joplin#77]
### Operating system
- [ ] macOS

### Application
- [ ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

*If there is an error, please copy and paste the full error message*

Fatal error:
{ Error: Error: SQLITE_ERROR: table folders already exists: CREATE TABLE folders (id TEXT PRIMARY KEY, title TEXT NOT NULL DEFAULT "", created_time INT NOT NULL, updated_time INT NOT NULL);
    at DatabaseDriverNode.sqliteErrorToJsError (/usr/local/Cellar/joplin/0.10.65/libexec/lib/node_modules/app/lib/database-driver-node.js:22:16)
    at JoplinDatabase.sqliteErrorToJsError (/usr/local/Cellar/joplin/0.10.65/libexec/lib/node_modules/app/lib/database.js:26:24)
    at JoplinDatabase._callee2$ (/usr/local/Cellar/joplin/0.10.65/libexec/lib/node_modules/app/lib/database.js:87:17)
    at tryCatch (/usr/local/Cellar/joplin/0.10.65/libexec/lib/node_modules/joplin/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/local/Cellar/joplin/0.10.65/libexec/lib/node_modules/joplin/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as throw] (/usr/local/Cellar/joplin/0.10.65/libexec/lib/node_modules/joplin/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/local/Cellar/joplin/0.10.65/libexec/lib/node_modules/joplin/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/Cellar/joplin/0.10.65/libexec/lib/node_modules/joplin/node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) code: 'SQLITE_ERROR' }

I think I installed it twice. What's the way to completely uninstall it?

**Comment by laurent22** [comment]
Yes this was an issue in old versions but it has been fixed now. Did you have any important data? If not, you can simply delete the file at `~/joplin/database.sqlite` and restart the app. It will rebuild the database properly and it should work again. If you had some data in there let me know as there's a manual fix too.

**Comment by kumit12** [comment]
It worked; although the db file was in `~/.config/joplin`
