### ISSUE TITLE
POSTGRES_CONNECTION_STRING not working

### ISSUE THREAD

**Issue by loganmarchione** [laurent22/joplin#7703]
## Environment

Joplin version: 2.10.5
Platform: K3s (mini distribution of Kubernetes)
OS specifics: `Linux kube01 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux` 

## Steps to reproduce

1. Setup Joplin using the variable `POSTGRES_CONNECTION_STRING`
2. Joplin produces errors with the incorrect Postgres settings

## Describe what you expected to happen

Joplin should have parsed the variable `POSTGRES_CONNECTION_STRING` and started successfully.

## Logfile

I'm trying to install Joplin on [K3s](https://k3s.io/). I'm not using a Helm chart, just a plain K8s manifest YAML file ([here](https://github.com/loganmarchione/k8s_homelab/blob/master/cluster/apps/joplin/joplin.yaml)). I was reading [this](https://github.com/laurent22/joplin/tree/dev/packages/server) document to install the server and wanted to use the `POSTGRES_CONNECTION_STRING` variable (like other apps that I run in K3s). However, Joplin is throwing database connection errors...

Below is the output from the container showing the environment variables...

```
$ env | grep DB
DB_CLIENT=pg
$ env | grep -i post
POSTGRES_CONNECTION_STRING=postgresql://joplin:password_goes_here@db05.internal.mydomain.com:5432/dbjoplin
```

Below is the output from the container log. Notice how the `host` is `localhost`? That's not what it should be set at. Is the variable `POSTGRES_CONNECTION_STRING` being parsed correctly?

```
2023-01-31 22:26:07: App: Starting server v2.10.5 (prod) on port 22300 and PID 7...
2023-01-31 22:26:07: App: NTP time offset: -22ms
2023-01-31 22:26:07: App: Running in Docker: true
2023-01-31 22:26:07: App: Public base URL: https://joplin.internal.mydomain.com
2023-01-31 22:26:07: App: API base URL: https://joplin.internal.mydomain.com
2023-01-31 22:26:07: App: User content base URL: https://joplin.internal.mydomain.com
2023-01-31 22:26:07: App: Log dir: /home/joplin/packages/server/logs
2023-01-31 22:26:07: App: DB Config: {
  client: 'pg',
  name: 'joplin',
  slowQueryLogEnabled: false,
  slowQueryLogMinDuration: 1000,
  autoMigration: true,
  user: 'joplin',
  password: '********',
  port: 5432,
  host: 'localhost'
}
2023-01-31 22:26:07: App: Mailer Config: {
  enabled: false,
  host: '',
  port: 465,
  security: 'tls',
  authUser: '',
  authPassword: '********',
  noReplyName: '',
  noReplyEmail: ''
}
2023-01-31 22:26:07: App: Content driver: { type: 1 }
2023-01-31 22:26:07: App: Content driver (fallback): null
2023-01-31 22:26:07: App: Trying to connect to database...
2023-01-31 22:26:07: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:08: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:09: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:10: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:11: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:12: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:13: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:14: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:15: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:16: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:17: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:18: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:19: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:20: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:21: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:22: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:23: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:24: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:25: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:26: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:27: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:28: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:29: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:30: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:31: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:32: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:33: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:34: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:35: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:36: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:37: db: Could not connect. Will try again. connect ECONNREFUSED ::1:5432
2023-01-31 22:26:37: [error] db: Timeout trying to connect to database: Error: connect ECONNREFUSED ::1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 5432
}
Error: Timeout trying to connect to database. Last error was: connect ECONNREFUSED ::1:5432
    at /home/joplin/packages/server/src/db.ts:113:10
    at Generator.next (<anonymous>)
    at fulfilled (/home/joplin/packages/server/dist/db.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)5432
```

**Comment by Aadijindal07** [comment]
kindly assign me
It appears that the Joplin server is not correctly parsing the POSTGRES_CONNECTION_STRING environment variable and is instead using the default value of localhost as the database host. This is why you are seeing connect ECONNREFUSED ::1:5432 in the logs, as the server is trying to connect to the database on localhost instead of the specified host db05.internal.mydomain.com.

To resolve this issue, i will try to modify the Joplin server code to correctly parse the POSTGRES_CONNECTION_STRING environment variable and use the information contained within it to configure the database connection.

**Comment by roman-r-m** [comment]
@Aadijindal07 
we do not assign issues but feel free to work on it if you like

**Comment by monotok** [comment]
I was about to raise this issue myself. @Aadijindal07 thanks for looking at this! I want to use the connection string so I can add ?sslmode=no-verify to end otherwise it refuses to connect to the crunchy postgres operator unless I disable TLS on the DB.

Like @loganmarchione I am using a k8s yaml file. Eg:

```
            - name: DB_CLIENT
              value: pg
            - name: BASE_DB_URL
              valueFrom:
                secretKeyRef:
                  key: uri
                  name: db-pguser-joplin-user
            - name: POSTGRES_CONNECTION_STRING
              value: $(BASE_DB_URL)?sslmode=no-verify
```

**Comment by loganmarchione** [comment]
@monotok  Same thing here, wanted to use SSL on Postgres. I self-host Postgres, so I disabled SSL on that database and used the individual variables for now.

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: joplin-deployment
  namespace: joplin
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: joplin
  template:
    metadata:
      labels:
        app: joplin
    spec:
      containers:
        - name: joplin
          image: joplin/server:2.10.5-beta
          ports:
            - containerPort: 22300
          env:
            - name: DB_CLIENT
              value: "pg"
            - name: APP_PORT
              value: "22300"
            - name: APP_BASE_URL
              value: "https://joplin.${SECRET_INTERNAL_DOMAIN_NAME}"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: joplin-secret-vars
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: joplin-secret-vars
                  key: POSTGRES_DATABASE
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: joplin-secret-vars
                  key: POSTGRES_USER
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: joplin-secret-vars
                  key: POSTGRES_PORT
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: joplin-secret-vars
                  key: POSTGRES_HOST
```

**Comment by laurent22** [comment]
It's in 2.10.6, not 2.10.5

**Comment by loganmarchione** [comment]
Thanks! Confirmed working!
