### ISSUE TITLE
error during updating

### ISSUE THREAD

**Issue by ledzep974** [laurent22/joplin#7738]
## Environment

Joplin version: 
Platform: linux 
OS specifics: linux PARROT

## Steps to reproduce

1. accept an updating request
2. 
3. 

## Logfile
[
The full error was:

GET info.json: Unknown error 2 (403): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>403 Forbidden</title> </head><body> <h1>Forbidden</h1> <p>You don't have permission to access this resource.</p> <hr> <address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address> </body></html>

Error: GET info.json: Unknown error 2 (403): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at ewebdav.pcloud.com Port 443</address>
</body></html>

    at newError (/tmp/.mount_JoplinVTor9K/resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:414:11)
    at WebDavApi.exec (/tmp/.mount_JoplinVTor9K/resources/app.asar/node_modules/@joplin/lib/WebDavApi.js:444:10)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async FileApiDriverWebDav.get (/tmp/.mount_JoplinVTor9K/resources/app.asar/node_modules/@joplin/lib/file-api-driver-webdav.js:164:21)

**Comment by Daeraxa** [comment]
pCloud is not supported as a WebDAV target because of a problematic implementation of WebDAV.
https://joplinapp.org/faq/#the-following-webdav-hosts-are-not-supported
