### ISSUE TITLE
Error when upgrading sync target 

### ISSUE THREAD

**Issue by kachapman** [laurent22/joplin#7742]
The error:

> Joplin upgrade in progress...
Please wait while the sync target is being upgraded. It may take a few seconds or a few minutes depending on the upgrade. The application will automatically restart once it is completed.
>Error
The sync target could not be upgraded due to an error. For support, please copy the complete content of this page and paste it in the forum: https://discourse.joplinapp.org/
>The full error was:
>MKCOL locks/: Unknown error 2 (400): ����c
>Error: MKCOL locks/: Unknown error 2 (400): ����c
    at newError (/app/joplin-desktop/resources/app/node_modules/@joplin/lib/WebDavApi.js:414:11)
    at WebDavApi.exec (/app/joplin-desktop/resources/app/node_modules/@joplin/lib/WebDavApi.js:444:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async FileApiDriverWebDav.mkdir (/app/joplin-desktop/resources/app/node_modules/@joplin/lib/file-api-driver-webdav.js:184:4)

## Environment

Joplin version: 2.9.17
Platform: Linux
OS specifics: Pop!_OS 22.04 LTS

## Steps to reproduce

1.  Try to Sync
2. Error

**Comment by laohuzhigege** [comment]
thankyou
