### ISSUE TITLE
TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by Gabscap** [laurent22/joplin#7770]
I installed the joplin AUR package and get the following errors:

```
$ joplin help
Class extends value undefined is not a constructor or null
```

Running joplin works, but if I close it again with `:q`, I get the following error:
```
$ joplin
Unhandled promise rejection Promise {
  <rejected> TypeError: Class extends value undefined is not a constructor or null
      at Object.<anonymous> (/usr/share/joplin/node_modules/joplin/app/command-done.js:8:23)
      at Module._compile (node:internal/modules/cjs/loader:1246:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
      at Module.load (node:internal/modules/cjs/loader:1103:32)
      at Module._load (node:internal/modules/cjs/loader:942:12)
      at Module.require (node:internal/modules/cjs/loader:1127:19)
      at require (node:internal/modules/helpers:112:18)
      at /usr/share/joplin/node_modules/joplin/app/app.js:154:26
      at Array.forEach (<anonymous>)
      at Application.commands (/usr/share/joplin/node_modules/joplin/app/app.js:148:30)
} reason: TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/usr/share/joplin/node_modules/joplin/app/command-done.js:8:23)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at Module.require (node:internal/modules/cjs/loader:1127:19)
    at require (node:internal/modules/helpers:112:18)
    at /usr/share/joplin/node_modules/joplin/app/app.js:154:26
    at Array.forEach (<anonymous>)
    at Application.commands (/usr/share/joplin/node_modules/joplin/app/app.js:148:30)
```

## Environment

Joplin version: [AUR 2.9.17-2](https://aur.archlinux.org/packages/joplin)
Platform: Arch Linux
OS specifics: Node Version v19.6.0

## Steps to reproduce

1. Install joplin AUR package
2. Run `joplin` or `joplin help`

## Logfile

Same output with `--debug --log-level debug` as shown above.

**Comment by Gabscap** [comment]
The version on the master branch seems to work without this error. I'll try to track down the problem.

**Comment by cuihaoleo** [comment]
I'm debugging the same issue. Change this very first line in `command-done.js`:
```js
const { BaseCommand } = require('./base-command.js');
```
to
```js
const BaseCommand = require('./base-command').default;
```
seems to fix the issue.

**Comment by Sadra-jl** [comment]
Exactly same log and issue here, changing "command-done.js" is no help.

**Comment by fabiandrinksmilk** [comment]
I am experiencing the same. It happens when I try to type any command. Just pressing colon(:) and typing any letter immediately crashed.

**Comment by piperfw** [comment]
> Hey there, it looks like there has been no activity on this issue recently. Has the issue been fixed, or does it still require the community's attention? If you require support or are requesting an enhancement or feature then please create a topic on the [Joplin forum](https://discourse.joplinapp.org/). This issue may be closed if no further activity occurs. You may comment on the issue and I will leave it open. Thank you for your contributions.

I've just done a clean build of 2.9.17-2 on Arch to check: the issue is still there (joplin is not usable).

**Comment by piperfw** [comment]
Comment on the issue to keep it open.

**Comment by piperfw** [comment]
Comment on the issue to keep it open.

**Comment by piperfw** [comment]
Comment on the issue to keep it open.

**Comment by Sadra-jl** [comment]
Comment on the issue to keep it open.
