### ISSUE TITLE
shared notebooks not update

### ISSUE THREAD

**Issue by hotcoin-walle** [laurent22/joplin#7836]
When I was using the shared notes feature, I encountered two problems:

After successfully sharing the note, if I make modifications, others are unable to see the latest version of the note (even though it shows that the synchronization has been completed).

If others make changes to the notes within the shared notebook, I am also unable to see the changes.

## Environment

Joplin version: 67b6d267f0c0 (the latest version in docker hub)
Platform:  docker 
OS specifics:  my pc Ubuntu 20.04.5 LTS (Focal Fossa)

## Steps to reproduce

1. Create notebooks and notes.
2. Share the notes.
3. Modify or create a notes.(one of the user)
4. Others synchronize the notes.
At this point, the person who received the shared notes cannot see the latest notes.
 

## Describe what you expected to happen
I hope that anyone can view the shared notes in the shared notebook regardless of who made the modifications.

## Logfile

2023-02-24 10:34:20: ShareService: Starting maintenance...
2023-02-24 10:34:21: [error] ShareService: Could not update share items: TypeError: Cannot read properties of undefined (reading 'jop_share_id')
    at /home/joplin/packages/server/src/models/ShareModel.ts:304:56
    at Array.find (<anonymous>)
    at ShareModel.<anonymous> (/home/joplin/packages/server/src/models/ShareModel.ts:304:32)
    at Generator.next (<anonymous>)
    at /home/joplin/packages/server/dist/models/ShareModel.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/joplin/packages/server/dist/models/ShareModel.js:4:12)
    at /home/joplin/packages/server/src/models/ShareModel.ts:289:43
    at ShareModel.<anonymous> (/home/joplin/packages/server/src/models/BaseModel.ts:228:19)
    at Generator.next (<anonymous>)

[error] App: 404: GET /api/items/root:/e2541c7840bf44e6a26c8adccbf7728b.md:/content: bf3SZ3j3yBXN1w7yhaSss0: Not found: root:/e2541c7840bf44e6a26c8adccbf7728b.md:
2023-02-24 10:35:58: App: GET /api/items/root:/e2541c7840bf44e6a26c8adccbf7728b.md:/content (404) (2ms)

**Comment by laurent22** [comment]
version?

**Comment by hotcoin-walle** [comment]
> version?

client 2.9.17(windows)

**Comment by laurent22** [comment]
Of the server

**Comment by hotcoin-walle** [comment]
> Of the server

{
  "name": "@joplin/server",
  "version": "2.10.6",

**Comment by hotcoin-walle** [comment]
I switched the service version to 2.10.9 and it worked fine.

[2.10.9-beta ](https://hub.docker.com/layers/joplin/server/2.10.9-beta/images/sha256-d1536bbc071f617b5bcddcf3b05beeea95d36223624fdd62ce58c381ffd2874d)
