### ISSUE TITLE
Syncing problem. Infinitely spinning circle with no feedback on what's wrong and how to fix it

### ISSUE THREAD

**Issue by RZarifov** [laurent22/joplin#7911]
Joplin couldn't sync. The icon indicating that the app tries to sync is spinning, and that's it. Cancelling it also gives no effect, since it just starts "cancelling" also infinitely.  
The same on mobile devices. It starts spinning, and that's it.  

So I pulled the laptop I used at the weekend, launched it, and immediately upon it completing synchronization in joplin, all other devices have started syncing.  
So I guess the problem is that when I finishing using my windows laptop yesterday, joplin decided to sink, and the device was turned off in the middle of this process.  
But other devices never tell you that the other device didn't finish the syncing process. It leaves absolutely zero feedback regarding this. It just spins the circle, and that's it.  

## Environment

Joplin version: 2.9.17
Platform: All of them. Literally. Linux, Mac, Windows, Android. I launched multiple devices.

## Steps to reproduce

1. I suppose first step is to ask one of the clients to sync, and immediately kill the power.  
2. Try to sync on other devices, and observe infinitely spinning circle.  
3. Launch the device with killed power again so it would lift the lock or whatever preventing other devices to sync.  

## Describe what you expected to happen
If the lock is n hours/minutes/days/whatever long, we can just ignore it.  
And app gives you a feedback that something is wrong. That one of the devices haven't finished the syncing process.  
And it would be great if it would give you an option to bypass it.

**Comment by laurent22** [comment]
The app can cancel in between requests, but if a request gets stuck forever it will now work. You can check the log to see what's wrong joplinapp.org/debugging

**Comment by RZarifov** [comment]
Well, next time I stumble upon this I will try to use the debug.   
But still it'd be great if you see to this problem on your side.  
If you need something from me (logs, whatever), tell me how to acq it and where to send it.

**Comment by steel-steven-87** [comment]
This issue has happened on my Android device many times before. The sync just stops working after some time and it is unclear why. It could be days, weeks, months before it breaks. The solution I found was to delete all application data and synchronize the notes from scratch.

This is unfortunate because I can never trust Joplin to sync notes from the desktop app.

I have checked the log file and found this error message.

```
04-15T00:20:22,20,"Synchronizer: ""There was some errors:""
04-15T00:20:22,20,"Synchronizer: ""Error: Cannot acquire exclusive lock because the following clients have a sync lock on the target: (1 #757f4ccce11f4a72aa25429a00c45aeb)
Code: hasSyncLock
Error: Cannot acquire exclusive lock because the following clients have a sync lock on the target: (1 #757f4ccce11f4a72aa25429a00c45aeb)
    at construct (native)
    at apply (native)
    at _construct (address at index.android.bundle:1:1861030)
    at Wrapper (address at index.android.bundle:1:1860696)
    at construct (native)
    at _createSuperInternal (address at index.android.bundle:1:1859789)
    at call (native)
    at JoplinError (address at index.android.bundle:1:1860150)
    at ?anon_0_ (address at index.android.bundle:1:2055451)
    at next (native)
    at fulfilled (address at index.android.bundle:1:2052345)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/164673tg/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/164673tg/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (address at index.android.bundle:1:213962)
    at _callTimer (address at index.android.bundle:1:212911)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:213075)
    at callReactNativeMicrotasks (address at index.android.bundle:1:215050)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:115434)
    at anonymous (address at index.android.bundle:1:114527)
    at __guard (address at index.android.bundle:1:115275)
    at flushedQueue (address at index.android.bundle:1:114438)
    at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:114381)""
```

@laurent22 Does this give any hint of what could be the issue? Please let me know if I can help.

**Comment by Daniel-GabrielN** [comment]
I have the same issue

**Comment by laurent22** [comment]
It means something else is synchronising at the same time, for example if you have the desktop app open somewhere simultaneously

**Comment by NeitherSound** [comment]
This is still an issue on the Desktop app running current version

**Comment by arkanoid87** [comment]
same issue here on windows 2.12.17
