### ISSUE TITLE
keep on syncing, while no files are synced

### ISSUE THREAD

**Issue by andrewchenshx** [laurent22/joplin#8034]
## Environment

Joplin version: 2.9.17
Platform: Windows
OS specifics: win10 64bit

## Steps to reproduce

1. install joplin
2. setup sync configuration: webdav, 
click "check synchronisation configuration" , returns "Success! Synchronisation configuration appears to be correct."
3. click sync

## Describe what you expected to happen
notes synced from the webdav

## Logfile

C:\Users\Administrator\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\Logger.js:190 18:12:27: FileApi: Could not retrieve remote date - defaulting to device date: Error: PUT temp/timeCheck2028.txt: Unknown error 2 (403): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /joplin/temp/timeCheck2028.txt
on this server.<br />
</p>
</body></html>

    at newError (C:\Users\Administrator\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\WebDavApi.js:414:11)
    at WebDavApi.exec (C:\Users\Administrator\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\WebDavApi.js:444:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async FileApiDriverWebDav.put (C:\Users\Administrator\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\file-api-driver-webdav.js:201:10)

**Comment by andrewchenshx** [comment]
android version(2.4.3) syncs well

**Comment by andrewchenshx** [comment]
manually creating the temp folder solved this problem
