### ISSUE TITLE
Joplin crashed on Android

### ISSUE THREAD

**Issue by simonla** [laurent22/joplin#8047]
## Environment

Joplin version: 2.11.2
Platform: Android
OS specifics: Android 13

## Steps to reproduce

1. Attach a ~50MB file
2. Sync to S3

## Logfile

```
04-13 02:55:08.106 31284 31344 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
04-13 02:55:08.106 31284 31344 E AndroidRuntime: Process: net.cozic.joplin, PID: 31284
04-13 02:55:08.106 31284 31344 E AndroidRuntime: java.lang.RuntimeException: Could not invoke RNFSManager.readFile
04-13 02:55:08.106 31284 31344 E AndroidRuntime:        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
04-13 02:55:08.106 31284 31344 E AndroidRuntime:        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
04-13 02:55:08.106 31284 31344 E AndroidRuntime:        at com.facebook.jni.NativeRunnable.run(Native Method)
04-13 02:55:08.106 31284 31344 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:942)
04-13 02:55:08.106 31284 31344 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
04-13 02:55:08.106 31284 31344 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
04-13 02:55:08.106 31284 31344 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:210)
04-13 02:55:08.106 31284 31344 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:299)
04-13 02:55:08.106 31284 31344 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
04-13 02:55:08.106 31284 31344 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:1012)
04-13 02:55:08.106 31284 31344 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
04-13 02:55:08.106 31284 31344 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-13 02:55:08.106 31284 31344 E AndroidRuntime:        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
04-13 02:55:08.106 31284 31344 E AndroidRuntime:        ... 9 more
04-13 02:55:08.106 31284 31344 E AndroidRuntime: Caused by: java.lang.OutOfMemoryError: Failed to allocate a 67339208 byte allocation with 9747504 free bytes and 9519KB until OOM, target footprint 268435456, growth limit 268435456
04-13 02:55:08.106 31284 31344 E AndroidRuntime:        at java.lang.StringFactory.newStringFromChars(StringFactory.java:112)
04-13 02:55:08.106 31284 31344 E AndroidRuntime:        at java.lang.StringFactory.newStringFromBytes(StringFactory.java:97)
04-13 02:55:08.106 31284 31344 E AndroidRuntime:        at java.lang.StringFactory.newStringFromBytes(StringFactory.java:65)
04-13 02:55:08.106 31284 31344 E AndroidRuntime:        at android.util.Base64.encodeToString(Base64.java:458)
04-13 02:55:08.106 31284 31344 E AndroidRuntime:        at com.rnfs.RNFSManager.readFile(RNFSManager.java:227)
04-13 02:55:08.106 31284 31344 E AndroidRuntime:        ... 11 more
```

OutOfMemory On `Base64.encodeToString`

```java

  @ReactMethod
  public void readFile(String filepath, Promise promise) {
    try {
      InputStream inputStream = getInputStream(filepath);
      byte[] inputData = getInputStreamBytes(inputStream);
      String base64Content = Base64.encodeToString(inputData, Base64.NO_WRAP);

      promise.resolve(base64Content);
    } catch (Exception ex) {
      ex.printStackTrace();
      reject(promise, filepath, ex);
    }
  }
```

Does anyone know where will invoke `readFile` on JS side? @laurent22 

 I'm interested in fixing this

**Comment by laurent22** [comment]
Not sure where exactly so you'll need to trace the code. Ideally we'd move away from that rnblob library but not sure if there's a good alternative

**Comment by simonla** [comment]
#4127 would read the entire file into memory

**Comment by simonla** [comment]
Current situation:

In the implementation of S3 file synchronization, We use RNFS to read file into JavaScript at once, which causing Java OOM.

Possible solutions:

1. Read and upload file in chunks. The advantage is that it requires minimal changes and is less likely to cause problems, but the disadvantage is the cost of memory copying and Base64 serialization.
2. Use uploadBlob to upload file. The advantage is that it does not copy the original file data, so the speed will be faster.
