### ISSUE TITLE
There is a bug when I click the "backtrace"

### ISSUE THREAD

**Issue by fangtaoysu** [laurent22/joplin#8121]
When I open a url in Joplin rather than browser, at same time, I click a backtrace(
![image](https://user-images.githubusercontent.com/78029226/235903366-aa4bd52d-01ef-4118-8faa-4a218f650810.png)), it appear a fatal error

## Logfile

Error
Joplin encountered a fatal error and could not continue.

To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

If the error persists you may try to [restart in safe mode](https://github.com/laurent22/joplin/issues/new?assignees=&labels=bug&template=bug_report.md&title=#), which will temporarily disable all plugins.

Message
Blocked a frame with origin "file://" from accessing a cross-origin frame.

Version info
Joplin for Desktop

Copyright © 2016-2023 Laurent Cozic
Joplin 2.9.17 (prod, win32)

客户端 ID: 1580698d162e49fd893e98cd3a88263d
同步版本：3
配置文件版本：41
支持的密钥链：是

修订：a84a8e7
Plugins
[
    {
        "id": "outline",
        "name": "Outline",
        "enabled": true,
        "version": "1.5.8"
    },
    {
        "id": "com.sctmes.kity-minder",
        "name": "Kity Minder",
        "enabled": true,
        "version": "1.0.12"
    }
]
Stack trace
Error: Blocked a frame with origin "file://" from accessing a cross-origin frame.
    at C:\Users\MrFeng\AppData\Local\Programs\Joplin\resources\app.asar\services\plugins\hooks\useWebviewToPluginMessages.js:34:25
    at HTMLUnknownElement.callCallback (C:\Users\MrFeng\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:347:14)
    at Object.invokeGuardedCallbackDev (C:\Users\MrFeng\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:397:16)
    at invokeGuardedCallback (C:\Users\MrFeng\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:454:31)
    at safelyCallDestroy (C:\Users\MrFeng\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:19900:5)
    at C:\Users\MrFeng\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:20279:19
    at unstable_runWithPriority (C:\Users\MrFeng\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\scheduler\cjs\scheduler.development.js:643:12)
    at runWithPriority$2 (C:\Users\MrFeng\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11305:10)
    at commitUnmount (C:\Users\MrFeng\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:20274:13)
    at commitNestedUnmounts (C:\Users\MrFeng\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:20349:5)
Component stack

    in ForwardRef(UserWebview) (created by ResizableLayout)
    in div (created by styled.div)
    in styled.div (created by ResizableLayout)
    in div (created by ResizableLayout)
    in div (created by ResizableLayout)
    in ResizableLayout (created by MainScreenComponent)
    in div (created by MainScreenComponent)
    in MainScreenComponent (created by Connect(MainScreenComponent))
    in Connect(MainScreenComponent) (created by NavigatorComponent)
    in div (created by NavigatorComponent)
    in NavigatorComponent (created by Connect(NavigatorComponent))
    in Connect(NavigatorComponent) (created by RootComponent)
    in ThemeProvider (created by RootComponent)
    in StyleSheetManager (created by RootComponent)
    in RootComponent (created by Connect(RootComponent))
    in Connect(RootComponent)
    in ErrorBoundary
    in Provider

**Comment by laurent22** [comment]
Could you provide the exact steps to replicate this issue?

**Comment by fangtaoysu** [comment]
> Could you provide the exact steps to replicate this issue?

first, I will define a link:
![image](https://user-images.githubusercontent.com/78029226/236676473-f49543af-12e2-46a4-b3f6-c9d052e5504b.png)
then, I open the url in joplin:
![image](https://user-images.githubusercontent.com/78029226/236676621-1fe2f87a-22c7-4836-ba8d-3e789b1150f0.png)
last, I click '<':
![image](https://user-images.githubusercontent.com/78029226/236676722-753d2b96-76ae-4b56-9dad-ba242f0a1cb3.png)
I get a error:
![image](https://user-images.githubusercontent.com/78029226/236676746-e7de8395-d258-41ee-84b1-807c0ec3aa82.png)

I think this error is concerned with "Outline", it is a plugins

**Comment by laurent22** [comment]
Please can you check if it still happens in 2.10? I cannot replicate this
