### ISSUE TITLE
Can't install CLI after 2.10.16 upgrade

### ISSUE THREAD

**Issue by richardsprague** [laurent22/joplin#8145]
When I try to install joplin terminal

```sh
npm install -g joplin
npm WARN deprecated @types/nanoid@3.0.0: This is a stub types definition. nanoid provides its own type definitions, so you do not need this installed.
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated highlight.js@9.12.0: Version no longer supported. Upgrade to @latest
npm WARN deprecated highlight.js@9.12.0: Version no longer supported. Upgrade to @latest
```

```
node --version
v20.1.0
npm --version
9.6.4
```

## Environment

Joplin version: 2.10.16
Platform: MacOS 
OS specifics: 13.3.1 ARM 64

## Steps to reproduce

1. Nuke all old copies of joplin (npm uninstall -g joplin  or `rm -r ~/.joplin-bin`)
2. run `NPM_CONFIG_PREFIX=~/.joplin-bin npm install -g joplin
sudo ln -s ~/.joplin-bin/bin/joplin /usr/bin/joplin`
3. see above error

## Describe what you expected to happen

should install correctly. Not sure why all those "deprecated" and other error messages appear.

**Comment by laurent22** [comment]
> and other error messages appear

Warnings don't matter, it's the errors we need to see

**Comment by richardsprague** [comment]
Here's the error:

```
~/.joplin-bin/lib/node_modules/joplin/node_modules/sharp/lib/sharp.js:34
  throw new Error(help.join('\n'));
  ^

Error:
Something went wrong installing the "sharp" module

dlopen(~/.joplin-bin/lib/node_modules/joplin/node_modules/sharp/build/Release/sharp-darwin-arm64v8.node, 0x0001): symbol not found in flat namespace '__ZTVN4vips7VOptionE'

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current darwin-arm64v8 runtime: "npm install --platform=darwin --arch=arm64v8 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (~/.joplin-bin/lib/node_modules/joplin/node_modules/sharp/lib/sharp.js:34:9)
    at Module._compile (node:internal/modules/cjs/loader:1267:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
    at Module.load (node:internal/modules/cjs/loader:1125:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at Module.require (node:internal/modules/cjs/loader:1149:19)
    at require (node:internal/modules/helpers:121:18)
    at Object.<anonymous> (~/.joplin-bin/lib/node_modules/joplin/node_modules/sharp/lib/constructor.js:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1267:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
```

**Comment by laurent22** [comment]
Do you know what was the latest working version for you? Maybe we just need to rollback sharp to an earlier version

**Comment by laurent22** [comment]
According to this thread, it happens on M1: https://stackoverflow.com/questions/68814180/darwin-arm64v8-binaries-cannot-be-used-on-the-darwin-x64-platform

Is that what you have?

If so, maybe you can try the same workaround:

    NPM_CONFIG_PREFIX=~/.joplin-bin npm install --arch=x64 --platform=darwin -g joplin

**Comment by richardsprague** [comment]
hmmm, I tried that but still get this error 
```
/Users/sprague/.joplin-bin/lib/node_modules/joplin/node_modules/sharp/lib/sharp.js:34
  throw new Error(help.join('\n'));
  ^

Error:
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-darwin-arm64v8.node'
Require stack:
- /Users/sprague/.joplin-bin/lib/node_modules/joplin/node_modules/sharp/lib/sharp.js
- /Users/sprague/.joplin-bin/lib/node_modules/joplin/node_modules/sharp/lib/constructor.js
- /Users/sprague/.joplin-bin/lib/node_modules/joplin/node_modules/sharp/lib/index.js
- /Users/sprague/.joplin-bin/lib/node_modules/joplin/main.js

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current darwin-arm64v8 runtime: "npm install --platform=darwin --arch=arm64v8 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/Users/sprague/.joplin-bin/lib/node_modules/joplin/node_modules/sharp/lib/sharp.js:34:9)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/sprague/.joplin-bin/lib/node_modules/joplin/node_modules/sharp/lib/constructor.js:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)

Node.js v18.16.0
```

Unfortunately I don't know the version number for my last working version.  Everything was fine until (1) I updated to Node 18 (from 16 or 17, I think) and (2) I upgraded to desktop 2.10.19.   I needed the Node upgrade for another app, but didn't run Joplin CLI until after the desktop upgrade, so I'm unsure if it was the Node upgrade or the Joplin upgrade.  Either way, I'm unable to get Joplin CLI to work even after nuking Node entirely and trying the various sharp installs you suggested.
