### ISSUE TITLE
Joplin folder sync stalls on "Cancelling": EBUSY: resource busy or locked

### ISSUE THREAD

**Issue by mgrandi** [laurent22/joplin#8146]
Joplin when running for a long time sometimes gets in a state where the sync is "Cancelling..." and makes no progress

I have a folder sync set up to a one drive folder, as i am not allowed to use API sync to one drive

I set up debug logging in Joplin and let it run for a week, until i got to this error:

```plaintext
2023-05-05 08:06:57: PluginRunner: "Got message (3): joplin.data.get", "[["tags"],{"fields":"title, id, updated_time","order_by":"updated_time","order_dir":"DESC","limit":10,"page":1}]"
2023-05-05 08:06:58: Synchronizer: "BasicDelta: Report: {"timestamp":1683169807038,"older":4266,"newer":0,"equal":1}"
2023-05-05 08:06:58: Synchronizer: "Sync: fetchingTotal: Fetching delta items from sync target"
2023-05-05 08:06:58: FileApi: "delete C:\Users\mgrandi\OneDrive - Microsoft\JoplinSync/locks/1_1_339fa57187c64b44a9fa462e73aca41c.json"
2023-05-05 08:06:58: "Could not run background sync:"
2023-05-05 08:06:58: "Error: Error: EBUSY: resource busy or locked, unlink 'C:\Users\mgrandi\OneDrive - Microsoft\JoplinSync\locks\1_1_339fa57187c64b44a9fa462e73aca41c.json'. Path: C:\Users\mgrandi\OneDrive - Microsoft\JoplinSync/locks/1_1_339fa57187c64b44a9fa462e73aca41c.json
Code: EBUSY
Error: Error: EBUSY: resource busy or locked, unlink 'C:\Users\mgrandi\OneDrive - Microsoft\JoplinSync\locks\1_1_339fa57187c64b44a9fa462e73aca41c.json'. Path: C:\Users\mgrandi\OneDrive - Microsoft\JoplinSync/locks/1_1_339fa57187c64b44a9fa462e73aca41c.json
    at FileApiDriverLocal.fsErrorToJsError_ (C:\Users\mgrandi\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\file-api-driver-local.js:20:18)
    at FileApiDriverLocal.delete (C:\Users\mgrandi\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\file-api-driver-local.js:174:15)"
2023-05-05 08:06:58: "Setting up recurrent sync with interval 300"
2023-05-05 08:06:58: models/Setting: "Saving settings..."
2023-05-05 08:06:58: models/Setting: "Settings have been saved."
2023-05-05 08:10:26: RevisionService: "maintenance: Starting..."
2023-05-05 08:10:26: RevisionService: "maintenance: Service is enabled"
2023-05-05 08:10:26: RevisionService: "collectRevisions: Created revisions for 0 notes"
2023-05-05 08:10:26: RevisionService: "maintenance: Done in 111ms"
```

after that, the log just has this in the log when it tries to sync

```plaintext
2023-05-08 10:12:12: "Running background sync on timer..."
2023-05-08 10:12:12: "Scheduling sync operation...", "0"
2023-05-08 10:12:12: "Preparing scheduled sync"
2023-05-08 10:12:12: "Starting scheduled sync"
2023-05-08 10:12:12: "Synchronisation is already in progress. State: in_progress"
2023-05-08 10:12:12: "Setting up recurrent sync with interval 300"
```

## Environment

Joplin version:  2.9.17 
Platform: windows
OS specifics:  windows 10

```plaintext
Joplin 2.9.17 (prod, win32)

Client ID: 339fa57187c64b44a9fa462e73aca41c
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: a84a8e7
```

## Steps to reproduce

1. Leave joplin running for a while
2.  Sync fails and it just shows "Cancelling..."
3.  have to restart joplin for syncs to resume

## Describe what you expected to happen

Syncs to resume normally even after a 1 time error

## Logfile

I have a log file however it seems to contain the contents of my notes, let me know if you are looking for something specific and I can attach it

**Comment by vaz-ar** [comment]
@mgrandi are you also seeing the following error in the side bar ?

~~~
Completed: 09/05/2023 10:32 (205s)
Last error: Error: Error: SQLITE_BUSY: database is locked: DELETE FROM sync_items WHERE item_location = 1 AND item_type = 1 AND item_id NOT IN (SELECT id FROM notes WHERE is_conflict = 0)
~~~

Just to know if we have the same problem.

EDIT: Just saw that your problem is on 2.9, mine is after upgrading to 2.10 so I will file my own issue

**Comment by mgrandi** [comment]
yeah, this takes so long for it to trigger (like a week) that I didn't upgrade yet, i have upgraded to 2.10.17 to see if the same issue occurs

and i searched my log file and didn't find SQLITE_BUSY, just a bunch of the "Error: EBUSY: resource busy or locked" errors

**Comment by mgrandi** [comment]
This is still happening

**Comment by mgrandi** [comment]
This is still happening

**Comment by mgrandi** [comment]
Wow that is incredibly frustrating that two days and I've missed email is enough to close an issue
