### ISSUE TITLE
Mac OS, upgrade version 2.10.17 failed

### ISSUE THREAD

**Issue by gEndelf** [laurent22/joplin#8158]
Error raised during upgrade Joplin on Mac OS with brew env. error.

## Environment

Joplin version:
- current version: 2.9.17
- new version: 2.10.17

Platform: Mac OS Ventura, 13.2.1 (22D68)
OS specifics: brew

## Steps to reproduce

1.  ```brew update && brew upgrade && brew upgrade --cask && brew cleanup --prune=1```
2. 
```
==> Upgrading 1 outdated package:
joplin 2.9.17 -> 2.10.17
==> Upgrading joplin
==> Downloading https://github.com/laurent22/joplin/releases/download/v2.10.17/Joplin-2.10.17.dmg
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/79162682/923ee405-1350-4e21-a4a8-a9de61366fd4?X-
########################################################################################################################################### 100.0%
==> Backing App 'Joplin.app' up to '/opt/homebrew/Caskroom/joplin/2.9.17/Joplin.app'
==> Removing App '/Applications/Joplin.app'
==> Moving App 'Joplin.app' to '/Applications/Joplin.app'
==> Purging files for version 2.10.17 of Cask joplin
==> Purging files for version 2.10.17 of Cask joplin
Warning: Reverting upgrade for Cask joplin
==> Purging files for version 2.9.17 of Cask joplin
Error: joplin: undefined method `artifacts' for #<Hash:0x0000000108f01a00>
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:127:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:253:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:137:in `upgrade'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

## Describe what you expected to happen

Joplin has to be successfully upgraded.

## Logfile

```
brew update && brew upgrade && brew upgrade --cask && brew cleanup --prune=1'''

==> Upgrading 1 outdated package:
joplin 2.9.17 -> 2.10.17
==> Upgrading joplin
==> Downloading https://github.com/laurent22/joplin/releases/download/v2.10.17/Joplin-2.10.17.dmg
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/79162682/923ee405-1350-4e21-a4a8-a9de61366fd4?X-
########################################################################################################################################### 100.0%
==> Backing App 'Joplin.app' up to '/opt/homebrew/Caskroom/joplin/2.9.17/Joplin.app'
==> Removing App '/Applications/Joplin.app'
==> Moving App 'Joplin.app' to '/Applications/Joplin.app'
==> Purging files for version 2.10.17 of Cask joplin
==> Purging files for version 2.10.17 of Cask joplin
Warning: Reverting upgrade for Cask joplin
==> Purging files for version 2.9.17 of Cask joplin
Error: joplin: undefined method `artifacts' for #<Hash:0x0000000108f01a00>
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:127:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:253:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:137:in `upgrade'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

**Comment by laurent22** [comment]
We don't maintain the Homebrew package, please report it on the Homebrew repo
