### ISSUE TITLE
Issues syncing with mac from (from win, android, ios)

### ISSUE THREAD

**Issue by GJPvWesten** [laurent22/joplin#8170]
## Environment Mac

Joplin version: 2.10.17
Platform: OS X
OS specifics: 12.6.3

Since about a week or two I have issues syncing to my Mac (Montery 12.6.3 and Joplin version 2.10.17). Shortly said, notes created or edited under android (boox tab ultra) often do not sync properly to the mac. When a new note is made typically only the title and the first line sync and subsequently nothing more. When an existing note is modified, these changes are not propagated. 

Notes do however sync correctly to my iPhone (iOS 16.5) , windows 11 machine, and the boox on Android.

Notes are synced to a webdav location. 

Sometimes, but not always, I get the error: "Error: Got metadata for path but could not fetch content: 5fe81d4266304923afc73b2377a2613a.md".  

Extremely annoying workaround is to copy the note text, email to self, and create the note on mac. When the offending note(snippet)  is deleted on the mac client and recreated with the text from the email the problem is solved on the mac and the other devices follow the mac correctly. 

However, with syn issues there is always the fear that you lose stuff..

## Logfile

2023-05-12 12:32:37: "Starting scheduled sync"
2023-05-12 12:32:37: Synchronizer: "Sync: starting: Starting synchronisation to target 6... supportsAccurateTimestamp = false; supportsMultiPut = false [1683887557179]"
2023-05-12 12:32:37: Synchronizer: "Indexing resources..."
2023-05-12 12:32:37: "ResourceService::indexNoteResources: Start"
2023-05-12 12:32:37: "ResourceService::indexNoteResources: Completed"
2023-05-12 12:32:37: Synchronizer: "Sync target remote info:", "{"version_":3,"masterKeys_":[],"e2ee_":{"value":false,"updatedTime":0},"activeMasterKeyId_":{"value":"","updatedTime":0},"ppk_":{"value":null,"updatedTime":0}}"
2023-05-12 12:32:37: Synchronizer: "Sync target is already setup - checking it..."
2023-05-12 12:32:37: Synchronizer: "Sync target local info:", "{"version_":3,"masterKeys_":[],"e2ee_":{"value":false,"updatedTime":0},"activeMasterKeyId_":{"value":"","updatedTime":0},"ppk_":{"value":null,"updatedTime":0}}"
2023-05-12 12:32:38: Synchronizer: "Error: Got metadata for path but could not fetch content: 5fe81d4266304923afc73b2377a2613a.md
Error: Got metadata for path but could not fetch content: 5fe81d4266304923afc73b2377a2613a.md
    at Synchronizer.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:576:43)
    at Generator.next (<anonymous>)
    at fulfilled (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"
2023-05-12 12:32:38: Synchronizer: "Req 12:32:33: DELETE https://surfdrive.surf.nl/files/remote.php/nonshib-webdav/Work-private/notes/Joplin/b29f2eb6c5744f7a811cd563aff9a1ce.md {"headers":{"Authorization":"********","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-90470","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}"
2023-05-12 12:32:38: Synchronizer: "Res 12:32:33: <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File with name Work-private/notes/Joplin/b29f2eb6c5744f7a811cd563aff9a1ce.md could not be located</s:message>
</d:error>
"
2023-05-12 12:32:38: Synchronizer: "Req 12:32:33: PUT https://surfdrive.surf.nl/files/remote.php/nonshib-webdav/Work-private/notes/Joplin/609c797f9dae4af9b2cd3c0154d6c093.md {"headers":{"Authorization":"********","Content-Type":"text/plain","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-76014","User-Agent":"Joplin/1.0","Content-Length":"943"},"body":"Roeland Merks\n\n- NU DIRECTEUR LORENTZ\n\nRESEARCH\n\n- MATHEMATICAL BIOLOGISTS\n- MECHANISTIC\n- DON'T MATCH WELL WITH AI & ML INITIATIVES\n- PLACE THEM UNDER CCLS?\n- WILLEM & A COMP. Biol.?\n- MIKE PREUSS , SANDER HILLEN, SILKE HENKES?\n- JUNE 9TH KICK OFF?\n- MARK ALBER APRIL 2024, SABBATICAL@LEIDEN., CCLS TALK.\n- EMAIL CURRENT.\n\nid: 609c797f9dae4af9b2cd3c0154d6c093\nparent_id: 6d0b56bebc714e6482b5fa7afb420798\ncreated_time: 2023-05-12T10:32:22.217Z\nupdated_time: 2023-05-12T10:32:27.176Z\nis_conflict: 0\nlatitude: 52.16011440\nlongitude: 4.49700970\naltitude: 0.0000\nauthor: \nsource_url: \nis_todo: 0\ntodo_due: 0\ntodo_completed: 0\nsource: joplin-desktop\nsource_application: net.cozic.joplin-desktop\napplication_data: \norder: 0\nuser_created_time: 2023-05-12T10:32:22.217Z\nuser_updated_time: 2023-05-12T10:32:27.176Z\nencryption_cipher_text: \nencryption_applied: 0\nmarkup_language: 1\nis_shared: 0\nshare_id: \nconflict_original_id: \nmaster_key_id: \ntype_: 1","ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}"
2023-05-12 12:32:38: Synchronizer: "Res 12:32:33: "
2023-05-12 12:32:38: Synchronizer: "Req 12:32:33: PROPFIND https://surfdrive.surf.nl/files/remote.php/nonshib-webdav/Work-private/notes/Joplin/5fe81d4266304923afc73b2377a2613a.md {"headers":{"Depth":0,"Authorization":"********","Content-Type":"text/xml","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-89828","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}"
2023-05-12 12:32:38: Synchronizer: "Res 12:32:33: <?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns"><d:response><d:href>/files/remote.php/nonshib-webdav/Work-private/notes/Joplin/5fe81d4266304923afc73b2377a2613a.md</d:href><d:propstat><d:prop><d:getlastmodified>Fri, 12 May 2023 09:41:24 GMT</d:getlastmodified><d:resourcetype/></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>
"
2023-05-12 12:32:38: Synchronizer: "Req 12:32:34: GET https://surfdrive.surf.nl/files/remote.php/nonshib-webdav/Work-private/notes/Joplin/5fe81d4266304923afc73b2377a2613a.md {"headers":{"Authorization":"********","Cache-Control":"no-store","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}"
2023-05-12 12:32:38: Synchronizer: "Res 12:32:34: <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message/>
</d:error>
"
2023-05-12 12:32:38: Synchronizer: "Req 12:32:35: DELETE https://surfdrive.surf.nl/files/remote.php/nonshib-webdav/Work-private/notes/Joplin/locks/1_1_5a16962935df484ea3bdc14aae259644.json {"headers":{"Authorization":"********","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-84825","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}"
2023-05-12 12:32:38: Synchronizer: "Res 12:32:35: "
2023-05-12 12:32:38: Synchronizer: "Req 12:32:37: GET https://surfdrive.surf.nl/files/remote.php/nonshib-webdav/Work-private/notes/Joplin/info.json {"headers":{"Authorization":"********","Cache-Control":"no-store","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}"
2023-05-12 12:32:38: Synchronizer: "Res 12:32:37: {
	"version": 3,
	"e2ee": {
		"value": false,
		"updatedTime": 0
	},
	"activeMasterKeyId": {
		"value": "",
		"updatedTime": 0
	},
	"masterKeys": []
}"
2023-05-12 12:32:38: Synchronizer: "Req 12:32:37: PROPFIND https://surfdrive.surf.nl/files/remote.php/nonshib-webdav/Work-private/notes/Joplin/locks/ {"headers":{"Depth":1,"Authorization":"********","Content-Type":"text/xml","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-87164","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}"
2023-05-12 12:32:38: Synchronizer: "Res 12:32:37: <?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns"><d:response><d:href>/files/remote.php/nonshib-webdav/Work-private/notes/Joplin/locks/</d:href><d:propstat><d:prop><d:getlastmodified>Fri, 12 May 2023 10:32:34 GMT</d:getlastmodified><d:resourcetype><d:collection/></d:resourcetype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>
"
2023-05-12 12:32:38: Synchronizer: "Req 12:32:38: PUT https://surfdrive.surf.nl/files/remote.php/nonshib-webdav/Work-private/notes/Joplin/locks/1_1_5a16962935df484ea3bdc14aae259644.json {"headers":{"Authorization":"********","Content-Type":"text/plain","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-1977","User-Agent":"Joplin/1.0","Content-Length":"71"},"body":"{\"type\":1,\"clientType\":1,\"clientId\":\"5a16962935df484ea3bdc14aae259644\"}","ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}"
2023-05-12 12:32:38: Synchronizer: "Res 12:32:38: "
2023-05-12 12:32:38: Synchronizer: "Req 12:32:38: PROPFIND https://surfdrive.surf.nl/files/remote.php/nonshib-webdav/Work-private/notes/Joplin/locks/ {"headers":{"Depth":1,"Authorization":"********","Content-Type":"text/xml","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-11901","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}"
2023-05-12 12:32:38: Synchronizer: "Res 12:32:38: <?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns"><d:response><d:href>/files/remote.php/nonshib-webdav/Work-private/notes/Joplin/locks/</d:href><d:propstat><d:prop><d:getlastmodified>Fri, 12 May 2023 10:32:37 GMT</d:getlastmodified><d:resourcetype><d:collection/></d:resourcetype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/files/remote.php/nonshib-webdav/Work-private/notes/Joplin/locks/1_1_5a16962935df484ea3bdc14aae259644.json</d:href><d:propstat><d:prop><d:getlastmodified>Fri, 12 May 2023 10:32:37 GMT</d:getlastmodified><d:resourcetype/></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>
"
2023-05-12 12:32:38: Synchronizer: "Req 12:32:38: PROPFIND https://surfdrive.surf.nl/files/remote.php/nonshib-webdav/Work-private/notes/Joplin/5fe81d4266304923afc73b2377a2613a.md {"headers":{"Depth":0,"Authorization":"********","Content-Type":"text/xml","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-62596","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}"
2023-05-12 12:32:38: Synchronizer: "Res 12:32:38: <?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns"><d:response><d:href>/files/remote.php/nonshib-webdav/Work-private/notes/Joplin/5fe81d4266304923afc73b2377a2613a.md</d:href><d:propstat><d:prop><d:getlastmodified>Fri, 12 May 2023 09:41:24 GMT</d:getlastmodified><d:resourcetype/></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>
"
2023-05-12 12:32:38: Synchronizer: "Req 12:32:38: GET https://surfdrive.surf.nl/files/remote.php/nonshib-webdav/Work-private/notes/Joplin/5fe81d4266304923afc73b2377a2613a.md {"headers":{"Authorization":"********","Cache-Control":"no-store","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}"
2023-05-12 12:32:38: Synchronizer: "Res 12:32:38: <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message/>
</d:error>
"
2023-05-12 12:32:39: Synchronizer: "Sync: finished: Synchronisation finished [1683887557179]"
2023-05-12 12:32:39: Synchronizer: "Operations completed: "
2023-05-12 12:32:39: Synchronizer: "Total folders: 3"
2023-05-12 12:32:39: Synchronizer: "Total notes: 924"
2023-05-12 12:32:39: Synchronizer: "Total resources: 27"
2023-05-12 12:32:39: Synchronizer: "There was some errors:"
2023-05-12 12:32:39: Synchronizer: "Error: Got metadata for path but could not fetch content: 5fe81d4266304923afc73b2377a2613a.md
Error: Got metadata for path but could not fetch content: 5fe81d4266304923afc73b2377a2613a.md
    at Synchronizer.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:576:43)
    at Generator.next (<anonymous>)
    at fulfilled (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/Synchronizer.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"
2023-05-12 12:32:39: "Sync has finished and note has never been changed - reloading it"
2023-05-12 12:32:40: "DecryptionWorker: cannot start because no master key is currently loaded."
2023-05-12 12:32:45: "Updating lat/long of note 116a5d76edba44a6a31227e8771de8bf"
2023-05-12 12:32:48: "Provisional was not modified - deleting it"
2023-05-12 12:32:51: "Updating lat/long of note dbd1d53bedce4577ac4ede14ccf731a8"
2023-05-12 12:32:53: "Provisional was not modified - deleting it"
2023-05-12 12:32:55: "Updating lat/long of note 6be2756b666c4993871bbd74bb7d6d4f"
2023-05-12 12:32:55: "SearchEngine: Updating FTS table..."
2023-05-12 12:32:56: "SearchEngine: Updated FTS table in 31ms. Inserted: 1. Deleted: 2"
2023-05-12 12:33:08: "Preparing scheduled sync"
2023-05-12 12:33:08: "Starting scheduled sync"
2023-05-12 12:33:08: Synchronizer: "Sync: starting: Starting synchronisation to target 6... supportsAccurateTimestamp = false; supportsMultiPut = false [1683887588642]"
2023-05-12 12:33:08: Synchronizer: "Indexing resources..."
2023-05-12 12:33:08: "ResourceService::indexNoteResources: Start"
2023-05-12 12:33:08: "ResourceService::indexNoteResources: Completed"
2023-05-12 12:33:09: Synchronizer: "Sync target remote info:", "{"version_":3,"masterKeys_":[],"e2ee_":{"value":false,"updatedTime":0},"activeMasterKeyId_":{"value":"","updatedTime":0},"ppk_":{"value":null,"updatedTime":0}}"
2023-05-12 12:33:09: Synchronizer: "Sync target is already setup - checking it..."
2023-05-12 12:33:09: Synchronizer: "Sync target local info:", "{"version_":3,"masterKeys_":[],"e2ee_":{"value":false,"updatedTime":0},"activeMasterKeyId_":{"value":"","updatedTime":0},"ppk_":{"value":null,"updatedTime":0}}"
2023-05-12 12:33:10: Synchronizer: "Sync: deleteRemote: local has been deleted: (Remote 116a5d76edba44a6a31227e8771de8bf)"
2023-05-12 12:33:10: Synchronizer: "Sync: deleteRemote: local has been deleted: (Remote dbd1d53bedce4577ac4ede14ccf731a8)"
2023-05-12 12:33:10: Synchronizer: "Sync: deleteRemote: local has been deleted: (Remote 5fe81d4266304923afc73b2377a2613a)"
2023-05-12 12:33:10: "SearchEngine: Updating FTS table..."
2023-05-12 12:33:11: "SearchEngine: Updated FTS table in 39ms. Inserted: 1. Deleted: 1"
2023-05-12 12:33:11: Synchronizer: "Sync: createRemote: remote does not exist, and local is new and has never been synced: Note: (Local 6be2756b666c4993871bbd74bb7d6d4f)"
2023-05-12 12:33:11: Synchronizer: "Sync: createRemote: remote does not exist, and local is new and has never been synced: Revision: (Local 28cbd454d0c24d518021cddf6eebb525)"
2023-05-12 12:33:12: Synchronizer: "TaskQueue.stop: syncDownload: waiting for tasks to complete: 0"
2023-05-12 12:33:12: Synchronizer: "TaskQueue.stop: syncDownload: Done, waited for 0"
2023-05-12 12:33:16: Synchronizer: "BasicDelta: Report: {"timestamp":1683884252000,"older":4188,"newer":4,"equal":1}"
2023-05-12 12:33:16: Synchronizer: "Sync: fetchingTotal: Fetching delta items from sync target"
2023-05-12 12:33:16: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2023-05-12 12:33:16: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2023-05-12 12:33:16: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2023-05-12 12:33:16: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2023-05-12 12:33:17: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2023-05-12 12:33:17: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2023-05-12 12:33:17: Synchronizer: "Sync: finished: Synchronisation finished [1683887588642]"
2023-05-12 12:33:17: Synchronizer: "Operations completed: "
2023-05-12 12:33:17: Synchronizer: "deleteRemote: 3"
2023-05-12 12:33:17: Synchronizer: "createRemote: 2"
2023-05-12 12:33:17: Synchronizer: "fetchingTotal: 6"
2023-05-12 12:33:17: Synchronizer: "fetchingProcessed: 6"
2023-05-12 12:33:17: Synchronizer: "Total folders: 3"
2023-05-12 12:33:17: Synchronizer: "Total notes: 924"
2023-05-12 12:33:17: Synchronizer: "Total resources: 27"
2023-05-12 12:33:17: "Sync has finished and note has never been changed - reloading it"
2023-05-12 12:33:18: "DecryptionWorker: cannot start because no master key is currently loaded."

**Comment by laurent22** [comment]
When it says this:

> "Error: Got metadata for path but could not fetch content: 5fe81d4266304923afc73b2377a2613a.md".

It means your server listed that the file 5fe81d4266304923afc73b2377a2613a.md but when the app tries to fetch it, it doesn't. First thing to check is whether this file exists - if you go to server directly, do you see a file "5fe81d4266304923afc73b2377a2613a.md"?

**Comment by GJPvWesten** [comment]
So, I had some further investigation. The problem is that the mac client simply ignores updated notitions made on android. The other clients (ios , windows) do pick ithe changes up correctly. It looks like this. Left is the MacOS version which is not updated, whereas the other two are correctly updated. 

Note that the item Prague visit only contains the first line on MacOS whereas bullets are corectly updated on the other two. 

This only happens when notes are made / ammened on the android client and is not correctly processed by MacOS.

When then on the android / iOS client a change is is made to one of these incorrectly syncing notes, then the error about metadata etc is appearing. The file IS present and in the shared folder and the errors appear on the android and iOS clients. The mac clients claims to succesfully sync (missing notes) and the others fail.

problem is the resolved by deleting the note on all devices (actually all notes edited with android) and recreating them on MacOS. Changes are then subsequently correcly shared. 


![Screenshot 2023-06-02 at 12 27 39](https://github.com/laurent22/joplin/assets/3306167/6d2a1bb4-81aa-4ef7-931f-677ac7afab0a)

**Comment by GJPvWesten** [comment]
This is now also starting to happen when syncing from mac to iphone. Notes made and modified on mac are not updated on iphone (have not been able to check android).

**Comment by GJPvWesten** [comment]
This is now also starting to happen when syncing from mac to iphone. Notes made and modified on mac are not updated on iphone (have not been able to check android).

**Comment by GJPvWesten** [comment]
Starting to get a bit desperate. May have to move away from Joplin but would hate to do so..!

I did notice a 'body dif' file that was not processed by mac. Is this underlying the issue? can you help please @laurent22 ?
<img width="852" alt="Screenshot 2023-06-27 at 14 55 26" src="https://github.com/laurent22/joplin/assets/3306167/edad2718-c873-4551-a041-7f596e5f3abd">

**Comment by GJPvWesten** [comment]
Update: Modifying a note on mac is not picked up by iPhone and modyfying on ihone is not picked up with mac. Android picks both up without a problem. 

Making a new note with the same contents does sync in both cases.

**Comment by laurent22** [comment]
You need to narrow it down: Make a change on desktop, sync, open the mobile app, sync. Does the change show up? If not, provide the log
