### ISSUE TITLE
External Editor Saves arn't loaded

### ISSUE THREAD

**Issue by Stolas** [laurent22/joplin#8202]
The same bug as https://github.com/laurent22/joplin/issues/4065 appears in latest.
When an external editor is set; and triggered.
The file is shown in the external editor, when saving, closing and, triggering "stop external editing". The data is lost.

## Environment

Joplin 2.10.18 (prod, win32)

Sync Version: 3
Profile Version: 42
Keychain Supported: Yes

Revision: c67f5fa

Enhancement: 1.2.1
Inline TODO: 1.6.0
Note Tabs: 1.4.0
Outline: 1.5.9

## Steps to reproduce

1. Set an External Editor
2. Edit in external edtior
3. Load edits back in Joplin
4. The work done at 2 is lost.

## Describe what you expected to happen

No data loss :)

## Logfile

```
2023-05-17 14:20:34: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:20:34: "ExternalEditWatcher: Watched note has been deleted: undefined"
```

**Comment by laurent22** [comment]
We need the editor name, and we need the full log

**Comment by Stolas** [comment]
Tried with gvim first.
Then I went googling and noticed this was fixed before for notepad. Tested that same behaviour.

While collecting the full log I tried it again and twice more and now it works.
No way we can figure out what the issue/bug was now. 

Sorry for the disruption thanks for the fast reply.

**Comment by Stolas** [comment]
And it broke again without changing the settings here is the log

```
2023-05-17 14:31:55: "Preparing scheduled sync"
2023-05-17 14:31:55: "Could not run background sync:"
2023-05-17 14:31:55: "Error: Error: ENOENT: no such file or directory, mkdir ''. Path: 
Code: ENOENT
Error: Error: ENOENT: no such file or directory, mkdir ''. Path: 
    at FileApiDriverLocal.fsErrorToJsError_ (C:\Users\Stolas\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\file-api-driver-local.js:20:18)
    at FileApiDriverLocal.mkdir (C:\Users\Stolas\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\file-api-driver-local.js:121:15)
    at async SyncTargetFilesystem.initFileApi (C:\Users\Stolas\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\SyncTargetFilesystem.js:35:3)"
2023-05-17 14:31:55: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:31:55: "ExternalEditWatcher: Stopped watching C:/Users/Stolas/.config/joplin-desktop/edit-8bf479a1ed2f4beaa7f10b13158a8d27.md"
2023-05-17 14:31:55: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:31:58: "ExternalEditWatcher: Started watching C:/Users/Stolas/.config/joplin-desktop/edit-8bf479a1ed2f4beaa7f10b13158a8d27.md"
2023-05-17 14:31:58: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:32:05: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:32:05: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:32:05: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:32:09: "ExternalEditWatcher: Stopped watching C:/Users/Stolas/.config/joplin-desktop/edit-8bf479a1ed2f4beaa7f10b13158a8d27.md"
2023-05-17 14:32:09: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:32:15: "SearchEngine: Updating FTS table..."
2023-05-17 14:32:15: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:32:15: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:32:15: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:32:15: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:32:15: "SearchEngine: Updated FTS table in 52ms. Inserted: 1. Deleted: 0"
2023-05-17 14:32:35: "Preparing scheduled sync"
2023-05-17 14:32:35: "Could not run background sync:"
2023-05-17 14:32:35: "Error: Error: ENOENT: no such file or directory, mkdir ''. Path: 
Code: ENOENT
Error: Error: ENOENT: no such file or directory, mkdir ''. Path: 
    at FileApiDriverLocal.fsErrorToJsError_ (C:\Users\Stolas\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\file-api-driver-local.js:20:18)
    at FileApiDriverLocal.mkdir (C:\Users\Stolas\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\file-api-driver-local.js:121:15)
    at async SyncTargetFilesystem.initFileApi (C:\Users\Stolas\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\SyncTargetFilesystem.js:35:3)"
2023-05-17 14:32:35: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:33:38: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:33:38: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:33:38: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:33:41: RepositoryApi: "findWorkingMirror: Using: https://raw.githubusercontent.com/joplin/plugins/master"
2023-05-17 14:33:41: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:33:43: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:33:43: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:33:43: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:33:46: "ExternalEditWatcher: Started watching C:/Users/Stolas/.config/joplin-desktop/edit-8bf479a1ed2f4beaa7f10b13158a8d27.md"
2023-05-17 14:33:46: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:33:48: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:33:48: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:33:48: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:33:58: "SearchEngine: Updating FTS table..."
2023-05-17 14:33:58: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:33:58: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:33:58: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:33:58: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:33:58: "SearchEngine: Updated FTS table in 43ms. Inserted: 1. Deleted: 0"
2023-05-17 14:34:09: "ExternalEditWatcher: Stopped watching C:/Users/Stolas/.config/joplin-desktop/edit-8bf479a1ed2f4beaa7f10b13158a8d27.md"
2023-05-17 14:34:09: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:34:11: "ExternalEditWatcher: Started watching C:/Users/Stolas/.config/joplin-desktop/edit-8bf479a1ed2f4beaa7f10b13158a8d27.md"
2023-05-17 14:34:11: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:34:18: "Preparing scheduled sync"
2023-05-17 14:34:18: "Could not run background sync:"
2023-05-17 14:34:18: "Error: Error: ENOENT: no such file or directory, mkdir ''. Path: 
Code: ENOENT
Error: Error: ENOENT: no such file or directory, mkdir ''. Path: 
    at FileApiDriverLocal.fsErrorToJsError_ (C:\Users\Stolas\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\file-api-driver-local.js:20:18)
    at FileApiDriverLocal.mkdir (C:\Users\Stolas\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\file-api-driver-local.js:121:15)
    at async SyncTargetFilesystem.initFileApi (C:\Users\Stolas\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\SyncTargetFilesystem.js:35:3)"
2023-05-17 14:34:18: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:34:28: "ExternalEditWatcher: Stopped watching C:/Users/Stolas/.config/joplin-desktop/edit-8bf479a1ed2f4beaa7f10b13158a8d27.md"
2023-05-17 14:34:28: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:34:30: "ExternalEditWatcher: Started watching C:/Users/Stolas/.config/joplin-desktop/edit-8bf479a1ed2f4beaa7f10b13158a8d27.md"
2023-05-17 14:34:30: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:34:34: "ExternalEditWatcher: Stopped watching C:/Users/Stolas/.config/joplin-desktop/edit-8bf479a1ed2f4beaa7f10b13158a8d27.md"
2023-05-17 14:34:34: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:34:36: "ExternalEditWatcher: Started watching C:/Users/Stolas/.config/joplin-desktop/edit-8bf479a1ed2f4beaa7f10b13158a8d27.md"
2023-05-17 14:34:36: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:34:42: "ExternalEditWatcher: Stopped watching C:/Users/Stolas/.config/joplin-desktop/edit-8bf479a1ed2f4beaa7f10b13158a8d27.md"
2023-05-17 14:34:42: "ExternalEditWatcher: Watched note has been deleted: undefined"
2023-05-17 14:34:44: "ExternalEditWatcher: Started watching C:/Users/Stolas/.config/joplin-desktop/edit-8bf479a1ed2f4beaa7f10b13158a8d27.md"
2023-05-17 14:34:44: "ExternalEditWatcher: Watched note has been deleted: undefined"

```

**Comment by personalizedrefrigerator** [comment]
> Tried with gvim first.

When I use `vim` on Linux as an external editor for Joplin, I occasionally need to run `:! touch %` after saving. While `touch` updates the last-modified timestamp, I'm not sure why this is necessary, as saving should also do this.

**Comment by Stolas** [comment]
Not on Linux. no touch :)

**Comment by Stolas** [comment]
Bug still exist, yet I moved to Obsidian.
Feel free to close.
