### ISSUE TITLE
Joplin server: Timeout trying to connect to database: Error: self-signed certificate in certificate chain

### ISSUE THREAD

**Issue by PaoloC68** [laurent22/joplin#8212]
## Environment

Joplin version: joplin/server:2.11.1-beta
Platform: Kuberentes
OS specifics: 1.25.4-do.0

## Steps to reproduce

1. Deploy on K8s with the following manifest:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: joplin
  namespace: joplin
  labels:
    app: joplin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joplin
  template:
    metadata:
      name: joplin
      labels:
        app: joplin
    spec:
      containers:
        - name: joplin
          image: joplin/server:2.11.1-beta
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 22300
          env:
          - name: APP_BASE_URL
            value: "https;//joplin.example.com"
          - name: APP_PORT
            value: "22300"
          - name: DB_CLIENT
            value: "pg"
          - name: POSTGRES_CONNECTION_STRING
            value: "postgresql://joplin:passw@private-db-postgresql.db.ondigitalocean.com:25061/joplin_pool?sslmode=require"
          - name: MAILER_ENABLED
            value: "0"
          livenessProbe:
            tcpSocket:
              port: 22300
            initialDelaySeconds: 190
          readinessProbe:
            tcpSocket:
              port: 22300
      restartPolicy: Always
```

## Describe what you expected to happen

The application should start and connect to the existing database using ssl encryption as required. 

## Logfile
```
2023-05-18 23:20:12: App: Content driver: { type: 1 }
2023-05-18 23:20:12: App: Content driver (fallback): null
2023-05-18 23:20:12: App: Trying to connect to database...
2023-05-18 23:20:12: db: Could not connect. Will try again. self-signed certificate in certificate chain
2023-05-18 23:20:13: db: Could not connect. Will try again. self-signed certificate in certificate chain
2023-05-18 23:20:43: [error] db: Timeout trying to connect to database: Error: self-signed certificate in certificate chain
    at TLSSocket.onConnectSecure (node:_tls_wrap:1540:34)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket._finishInit (node:_tls_wrap:959:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:743:12) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}
Error: Timeout trying to connect to database. Last error was: self-signed certificate in certificate chain
    at /home/joplin/packages/server/src/db.ts:118:10
    at Generator.next (<anonymous>)
    at fulfilled (/home/joplin/packages/server/dist/db.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by PaoloC68** [comment]
Temporarily I was able to connect the db by setting the following environment variable:
```
          - name: NODE_TLS_REJECT_UNAUTHORIZED
            value: "0"
 ```
