### ISSUE TITLE
Fatal Error on 2.11.4 Win10 desktop 

### ISSUE THREAD

**Issue by IkaSumi33** [laurent22/joplin#8235]
Joplin version 2.11.4 WIN10 Desktop sync using DropBox - no plugins
( this has been transferred from Joplin support forum as per laurents request)

Also using Joplin Desktop 2.11.4 Ubuntu 22.04.2 LTS ( my main version of joplin) and Android v 2.11.22 syncing using Dropbox

I have not used Joplin on Win10 for a few days and got this fatal error after Joplin seemed to struggle with syncing via dropbox approx 40 notes were due to be deleted in sync

I appreciate I am using pre-release versions, so am posting this here to see if it is useful info. Restarting Joplin on windows 10 seems to have reset and sync appeared to complete successfully and no other issues so far.

Error
Joplin encountered a fatal error and could not continue.
To report the error, please copy the entire content of this page and post it on Joplin forum or GitHub.
If the error persists you may try to restart in safe mode, which will temporarily disable all plugins.
Message
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
Version info
Joplin for Desktop

Copyright © 2016-2023 Laurent Cozic
Joplin 2.11.4 (prod, win32)

Client ID: f02259b47a604fb58a45d04962747a80
Sync Version: 3
Profile Version: 42
Keychain Supported: No

Revision: 201c7d8
Stack trace
Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
at checkForNestedUpdates (C:\Users\andre\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:27292:11)
at scheduleUpdateOnFiber (C:\Users\andre\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:25475:3)
at Object.enqueueSetState (C:\Users\andre\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:14067:7)
at Component.setState (C:\Users\andre\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react\cjs\react.development.js:354:16)
at ItemList.updateStateItemIndexes (C:\Users\andre\AppData\Local\Programs\Joplin\resources\app.asar\gui\ItemList.js:36:14)
at ItemList.onScroll (C:\Users\andre\AppData\Local\Programs\Joplin\resources\app.asar\gui\ItemList.js:70:14)
at ItemList.componentDidUpdate (C:\Users\andre\AppData\Local\Programs\Joplin\resources\app.asar\gui\ItemList.js:61:18)
at commitLayoutEffectOnFiber (C:\Users\andre\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:23333:30)
at commitLayoutMountEffects_complete (C:\Users\andre\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:24688:9)
at commitLayoutEffects_begin (C:\Users\andre\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:24674:7)
Component stack
at ItemList (C:\Users\andre\AppData\Local\Programs\Joplin\resources\app.asar\gui\ItemList.js:8:9)
at div
at I (C:\Users\andre\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19385)
at NoteListComponent (C:\Users\andre\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteList\NoteList.js:51:88)
at ConnectFunction (C:\Users\andre\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-redux\lib\components\connect.js:246:87)
at div
at I (C:\Users\andre\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19385)
at NoteListWrapper (C:\Users\andre\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteListWrapper\NoteListWrapper.js:16:49)
at div
at I (C:\Users\andre\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19385)
at div
at Resizable (C:\Users\andre\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\re-resizable\lib\index.es5.js:211:28)
at div
at ResizableLayout (C:\Users\andre\AppData\Local\Programs\Joplin\resources\app.asar\gui\ResizableLayout\ResizableLayout.js:46:45)
at div
at MainScreenComponent (C:\Users\andre\AppData\Local\Programs\Joplin\resources\app.asar\gui\MainScreen\MainScreen.js:74:9)
at ConnectFunction (C:\Users\andre\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-redux\lib\components\connect.js:246:87)
at div
at NavigatorComponent (C:\Users\andre\AppData\Local\Programs\Joplin\resources\app.asar\gui\Navigator.js:7:1)
at ConnectFunction (C:\Users\andre\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-redux\lib\components\connect.js:246:87)
at exports.ThemeProvider (C:\Users\andre\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:25117)
at ae (C:\Users\andre\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:13440)
at RootComponent (C:\Users\andre\AppData\Local\Programs\Joplin\resources\app.asar\gui\Root.js:103:1)
at ConnectFunction (C:\Users\andre\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-redux\lib\components\connect.js:246:87)
at ErrorBoundary (C:\Users\andre\AppData\Local\Programs\Joplin\resources\app.asar\gui\ErrorBoundary.js:21:9)
at Provider (C:\Users\andre\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-redux\lib\components\Provider.js:19:3)

**Comment by laurent22** [comment]
This issue should be fixed in 659f602a125d91ff97388f82c6300dbecc89376c
