### ISSUE TITLE
[CLI] `joplin use` throws error

### ISSUE THREAD

**Issue by amcooper** [laurent22/joplin#8303]
## Environment

Joplin version: \[CLI\] v2.10.3
Platform: terminal
OS specifics: Arch Linux

## Steps to reproduce

1. Execute `joplin use $NOTEBOOK`. The error message below appears in stdout. The active notebook doesn’t change.
```
$ joplin use Miscellany
Fatal error:
Error: Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: settings.key: INSERT INTO `settings` (`key`, `value`) VALUES (?, ?): sync.5.password,not-my-password
    at DatabaseDriverNode.sqliteErrorToJsError (/home/adam/.config/nvm/versions/node/v16.17.0/lib/node_modules/joplin/node_modules/@joplin/lib/database-driver-node.js:23:18)
    at JoplinDatabase.sqliteErrorToJsError (/home/adam/.config/nvm/versions/node/v16.17.0/lib/node_modules/joplin/node_modules/@joplin/lib/database.js:34:30)
    at JoplinDatabase.<anonymous> (/home/adam/.config/nvm/versions/node/v16.17.0/lib/node_modules/joplin/node_modules/@joplin/lib/database.js:135:36)
    at Generator.throw (<anonymous>)
    at rejected (/home/adam/.config/nvm/versions/node/v16.17.0/lib/node_modules/joplin/node_modules/@joplin/lib/database.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'SQLITE_CONSTRAINT'
}
```

## Describe what you expected to happen

I expected no output to stdout and the active notebook to change to `$NOTEBOOK`.

## Logfile

```
2023-06-09 18:49:33: models/Setting: "Could not save settings", "Error: Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: settings.key: INSERT INTO `settings` (`key`, `value`) VALUES (?, ?): sync.5.password,not-my-password
Code: SQLITE_CONSTRAINT
Error: Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: settings.key: INSERT INTO `settings` (`key`, `value`) VALUES (?, ?): sync.5.password,not-my-password
    at DatabaseDriverNode.sqliteErrorToJsError (/home/adam/.config/nvm/versions/node/v16.17.0/lib/node_modules/joplin/node_modules/@joplin/lib/database-driver-node.js:23:18)
    at JoplinDatabase.sqliteErrorToJsError (/home/adam/.config/nvm/versions/node/v16.17.0/lib/node_modules/joplin/node_modules/@joplin/lib/database.js:34:30)
    at JoplinDatabase.<anonymous> (/home/adam/.config/nvm/versions/node/v16.17.0/lib/node_modules/joplin/node_modules/@joplin/lib/database.js:135:36)
    at Generator.throw (<anonymous>)
    at rejected (/home/adam/.config/nvm/versions/node/v16.17.0/lib/node_modules/joplin/node_modules/@joplin/lib/database.js:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
2023-06-09 18:49:34: models/Setting: "Could not save settings", "Error: Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: settings.key: INSERT INTO `settings` (`key`, `value`) VALUES (?, ?): sync.5.password,not-my-password
Code: SQLITE_CONSTRAINT
Error: Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: settings.key: INSERT INTO `settings` (`key`, `value`) VALUES (?, ?): sync.5.password,not-my-password
    at DatabaseDriverNode.sqliteErrorToJsError (/home/adam/.config/nvm/versions/node/v16.17.0/lib/node_modules/joplin/node_modules/@joplin/lib/database-driver-node.js:23:18)
    at JoplinDatabase.sqliteErrorToJsError (/home/adam/.config/nvm/versions/node/v16.17.0/lib/node_modules/joplin/node_modules/@joplin/lib/database.js:34:30)
    at JoplinDatabase.<anonymous> (/home/adam/.config/nvm/versions/node/v16.17.0/lib/node_modules/joplin/node_modules/@joplin/lib/database.js:135:36)
    at Generator.throw (<anonymous>)
    at rejected (/home/adam/.config/nvm/versions/node/v16.17.0/lib/node_modules/joplin/node_modules/@joplin/lib/database.js:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
2023-06-09 18:50:15: App: "Profile directory: /home/adam/.config/joplin"
2023-06-09 18:50:15: App: "Root profile directory: /home/adam/.config/joplin"
2023-06-09 18:50:15: "Database was open successfully"
2023-06-09 18:50:15: "Checking for database schema update..."
2023-06-09 18:50:15: "Current database version", "{"version":42,"table_fields_version":42}"
2023-06-09 18:50:15: "Upgrading database from version 42"
2023-06-09 18:50:15: "New version: 42. Previously recorded version: 42"
2023-06-09 18:50:15: "KeychainService: checking if keychain supported"
2023-06-09 18:50:15: "KeychainService: check was already done - skipping. Supported:", "0"
2023-06-09 18:50:15: handleSyncStartupOperation: "Processing operation:", "0"
2023-06-09 18:50:15: App: "Client ID: 8f6d25172c314eb3a1ad95f97df9aa53"
2023-06-09 18:50:15: models/Setting: "Applying default migrations..."
2023-06-09 18:50:15: e2ee/utils: "Trying to load 1 master keys..."
2023-06-09 18:50:15: e2ee/utils: "findMasterKeyPassword: No master password is defined - trying to get master key specific password"
2023-06-09 18:50:15: EncryptionService: "Loading master key: 5972b5f717b942f4a424987efe52c017. Make active:", "true"
2023-06-09 18:50:15: e2ee/utils: "Loaded master keys: 1"
2023-06-09 18:50:15: "ResourceFetcher: Auto-add resources: Mode: always"
2023-06-09 18:50:15: "ResourceFetcher: Auto-added resources: 0"
```

**Comment by laurent22** [comment]
It's not clear how it can happens. Only issue I could think of is maybe some conflict with multiple profile. Do you use multiple profiles by any chance?

**Comment by amcooper** [comment]
Not intentionally. Is there a simple way of knowing if I've done that accidentally? (I will look into it myself, of course, when I have a moment.)
UPDATE: I don't think I'm using multiple profiles, as I just use the CLI, TUI, and iOS app, and I don't think multiple profile functionality is available outside of desktop.

**Comment by amcooper** [comment]
I deleted the offending row in the database, and that seems to have fixed it.

To be specific:
`$ sqlite3 ~/.config/joplin/database.sqlite`
`sqlite> DELETE FROM settings WHERE key = 'sync.5.password';`

The row was re-created in the database (!) & now `joplin use $NOTEBOOK` works as expected.
