### ISSUE TITLE
Error on opening app: Cannot read properties of null (reading 'setBaseAndExtent')

### ISSUE THREAD

**Issue by juliux-arg** [laurent22/joplin#8313]
Error
Joplin encountered a fatal error and could not continue.

To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

If the error persists you may try to [restart in safe mode](https://github.com/laurent22/joplin/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=#), which will temporarily disable all plugins.

Message
Cannot read properties of null (reading 'setBaseAndExtent')

Version info
Joplin for Desktop

Copyright © 2016-2023 Laurent Cozic
Joplin 2.10.19 (prod, win32)

ID del Cliente: f6b581cce8a34d148ceb2ba0f7e79081
Versión de la Sincronización: 3
Versión del Perfil: 42
Llavero Soportado: No

Revisión: 1100ab0

Conflict Resolution: 1.2.3
Favorites: 1.3.0
Journal: 1.0.11
Note Tabs: 1.4.0
Plugins
[
    {
        "id": "joplin.plugin.note.tabs",
        "name": "Note Tabs",
        "enabled": false,
        "version": "1.4.0"
    },
    {
        "id": "joplin.plugin.benji.favorites",
        "name": "Favorites",
        "enabled": true,
        "version": "1.3.0"
    },
    {
        "id": "joplin-plugin-conflict-resolution",
        "name": "Conflict Resolution",
        "enabled": true,
        "version": "1.2.3"
    },
    {
        "id": "com.leenzhu.journal",
        "name": "Journal",
        "enabled": true,
        "version": "1.0.11"
    }
]
Stack trace
TypeError: Cannot read properties of null (reading 'setBaseAndExtent')
    at Object.h [as setRng] (file:///C:/Users/Sumar/AppData/Local/Temp/2Pv6oUdEnIGnQlLaprk5j29WGgt/resources/app.asar/vendor/lib/tinymce/tinymce.min.js:9:228027)
    at he (file:///C:/Users/Sumar/AppData/Local/Temp/2Pv6oUdEnIGnQlLaprk5j29WGgt/resources/app.asar/vendor/lib/tinymce/plugins/searchreplace/plugin.min.js:9:13636)
    at Object.onClose (file:///C:/Users/Sumar/AppData/Local/Temp/2Pv6oUdEnIGnQlLaprk5j29WGgt/resources/app.asar/vendor/lib/tinymce/plugins/searchreplace/plugin.min.js:9:12082)
    at file:///C:/Users/Sumar/AppData/Local/Temp/2Pv6oUdEnIGnQlLaprk5j29WGgt/resources/app.asar/vendor/lib/tinymce/themes/silver/theme.min.js:9:379317
    at r (file:///C:/Users/Sumar/AppData/Local/Temp/2Pv6oUdEnIGnQlLaprk5j29WGgt/resources/app.asar/vendor/lib/tinymce/themes/silver/theme.min.js:9:399999)
    at file:///C:/Users/Sumar/AppData/Local/Temp/2Pv6oUdEnIGnQlLaprk5j29WGgt/resources/app.asar/vendor/lib/tinymce/themes/silver/theme.min.js:9:400057
    at Object.each (file:///C:/Users/Sumar/AppData/Local/Temp/2Pv6oUdEnIGnQlLaprk5j29WGgt/resources/app.asar/vendor/lib/tinymce/themes/silver/theme.min.js:9:5398)
    at file:///C:/Users/Sumar/AppData/Local/Temp/2Pv6oUdEnIGnQlLaprk5j29WGgt/resources/app.asar/vendor/lib/tinymce/themes/silver/theme.min.js:9:400040
    at e (file:///C:/Users/Sumar/AppData/Local/Temp/2Pv6oUdEnIGnQlLaprk5j29WGgt/resources/app.asar/vendor/lib/tinymce/themes/silver/theme.min.js:9:38628)
    at file:///C:/Users/Sumar/AppData/Local/Temp/2Pv6oUdEnIGnQlLaprk5j29WGgt/resources/app.asar/vendor/lib/tinymce/themes/silver/theme.min.js:9:1078
Component stack

    at TinyMCE (C:\Users\Sumar\AppData\Local\Temp\2Pv6oUdEnIGnQlLaprk5j29WGgt\resources\app.asar\gui\NoteEditor\NoteBody\TinyMCE\TinyMCE.js:93:54)
    at div
    at div

**Comment by juliux-arg** [comment]
The issue was solved when I disabled **Note Tabs** plugin. Apparently it conflicted with **Favorites** plugin.
