### ISSUE TITLE
Sync with Nextcloud fails. Server Error "Request Containing Content, but Missing Content-Type header"

### ISSUE THREAD

**Issue by mtballday** [laurent22/joplin#837]
### Operating system

- Linux

### Application

- Desktop

I am syncing Joplin with Nextcloud. Sync is working from Android, but not from Linux, and I can't figure it out. I've pasted the error that shows up on the server and the client, but I admit I don't really know what they mean.

Any ideas?

Thanks

*Server error:*
```
[Tue Oct 02 10:50:01 2018] [error] [client xx.xx.xx.xx] ModSecurity: Access denied with code 406 (phase 2). Match of "rx ^0$" against "REQUEST_HEADERS:Content-Length" required. [file "/etc/httpd/modsecurity.d/10_asl_rules.conf"] [line "102"] [id "392301"] [rev "5"] [msg "Request Containing Content, but Missing Content-Type header"] [severity "NOTICE"] [hostname "anonymized.com"] [uri "/nextcloud/remote.php/webdav/Notes/"] [unique_id "anonymized@anonymized"]
```

*Joplin log:*
```
2018-10-02 11:00:46: "Error: PROPFIND : Unknown error 2 (406): <head><title>Not Acceptable!</title></head><body><h1>Not Acceptable!</h1><p>An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.</p></body></html>
Code: 406
Error: PROPFIND : Unknown error 2 (406): <head><title>Not Acceptable!</title></head><body><h1>Not Acceptable!</h1><p>An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.</p></body></html>
    at newError (/home/rich/.joplin-bin/lib/node_modules/joplin/lib/WebDavApi.js:284:11)
    at WebDavApi.exec (/home/rich/.joplin-bin/lib/node_modules/joplin/lib/WebDavApi.js:313:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)"
```

**Comment by laurent22** [comment]
Please use the forum for support requests.
