### ISSUE TITLE
Sync timeout with WebDAV and E2EE activated

### ISSUE THREAD

**Issue by francoisbruneau** [laurent22/joplin#869]
### Operating system

- macOS

### Application

- Desktop

### Description

Initial sync seems to have worked fine, uploading many .md files and resources, until it attempted to process a 8.8MB resource file. As shown in the logs, a network timeout occured. Further syncs resume the process starting from this file, with the same issue occuring over and over.

**First sync**

```
2018-10-08 02:39:24: "FetchError: network timeout at: https://<serverName>/francois/joplin/.resource/037e7c266ba013fbbeb19b99d3cc2ead
FetchError: network timeout at: https://<serverName>/francois/joplin/.resource/037e7c266ba013fbbeb19b99d3cc2ead
    at /Applications/Joplin.app/Contents/Resources/app/node_modules/node-fetch/index.js:126:13"
2018-10-08 02:39:24: "Operations completed: "
2018-10-08 02:39:24: "createRemote: 6745"
2018-10-08 02:39:24: "Total folders: 26"
2018-10-08 02:39:24: "Total notes: 6057"
2018-10-08 02:39:24: "Total resources: 3170"
```

**Subsequent syncs**

```
2018-10-08 03:36:34: "FetchError: network timeout at: https://<serverName>/francois/joplin/.resource/037e7c266ba013fbbeb19b99d3cc2ead
FetchError: network timeout at: https://<serverName>/francois/joplin/.resource/037e7c266ba013fbbeb19b99d3cc2ead
    at /Applications/Joplin.app/Contents/Resources/app/node_modules/node-fetch/index.js:126:13"
2018-10-08 03:36:34: "Operations completed: "
2018-10-08 03:36:34: "createRemote: 1"
2018-10-08 03:36:34: "Total folders: 26"
2018-10-08 03:36:34: "Total notes: 6057"
2018-10-08 03:36:34: "Total resources: 3170"
```

Why the process fails on a 8.8MB resource remains obscure, as server-side logs show it managed to upload a slightly smaller 6.4MB resource during the first sync.

For all syncs after the initial one, all I see server-side is .sync/ and .resource/ subdirectories re-creation and then nothing till the next sync attempt.

The timeout takes roughly 1 hour to happen. During this time, the UI status is stuck on:

```
Created remote items: 1
State: In progress.
```

Any idea what could be happening?

**Comment by laurent22** [comment]
Could there be something on your computer or server preventing the 8MB to be uploaded?

**Comment by francoisbruneau** [comment]
Not that I know. Would it be possible to add more debug output to help troubleshoot such cases?
