### ISSUE TITLE
Importing note with image from ENEX causes hang

### ISSUE THREAD

**Issue by bgoodmansf** [laurent22/joplin#8699]
## Environment

Joplin version: 2.11.11 (portable version)
Platform:  Windows
OS specifics: Windows 10 Pro, 22H2, build 19045.3271

## Steps to reproduce

1. Import attached file "ImportFail.enex" using File > Import > ENEX - Evernote export file (as Markdown)
   [ImportFail.zip](https://github.com/laurent22/joplin/files/12389042/ImportFail.zip)
2. Displays:
   Importing from "Z:\ImportFail.enex" as "enex" format. Please wait...
3. Hangs forever
 
## Describe what you expected to happen

Expect import to complete.

## Logfile

C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\gui\MenuBar.js:221 Error: Line 14:182: "DSCN0716.JPG": Unexpected close tag
Line: 14
Column: 182
Char: >
    at error (C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:651:10)
    at strictFail (C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:677:7)
    at closeTag (C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:871:9)
    at SAXParser.write (C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:1443:13)
    at SAXStream.write (C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:239:18)
    at ReadStream.ondata (node:internal/streams/readable:754:22)
    at ReadStream.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
onError @ C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\gui\MenuBar.js:221
(anonymous) @ C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\import-enex.js:420
emit @ node:events:538
SAXStream._parser.onerror @ C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:194
emit @ C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:624
error @ C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:653
strictFail @ C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:677
closeTag @ C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:871
write @ C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:1443
SAXStream.write @ C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:239
ondata @ node:internal/streams/readable:754
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
(anonymous) @ node:internal/fs/streams:275
wrapper @ node:fs:660
2C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\gui\MenuBar.js:221 Error: Line 14:182: "DSCN0716.JPG": Unexpected close tag
Line: 14
Column: 182
Char: >
    at error (C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:651:10)
    at strictFail (C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:677:7)
    at closeTag (C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:871:9)
    at SAXParser.write (C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:1443:13)
    at SAXStream.write (C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:239:18)
    at ReadStream.ondata (node:internal/streams/readable:754:22)
    at ReadStream.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
onError @ C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\gui\MenuBar.js:221
(anonymous) @ C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\import-enex.js:420
emit @ node:events:526
SAXStream._parser.onerror @ C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:194
emit @ C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:624
error @ C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:653
strictFail @ C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:677
closeTag @ C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:871
write @ C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:1443
SAXStream.write @ C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:239
ondata @ node:internal/streams/readable:754
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
(anonymous) @ node:internal/fs/streams:275
wrapper @ node:fs:660
C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\gui\MenuBar.js:221 Error: Line 14:182: "DSCN0716.JPG": Unmatched closing tag: en-note
Line: 14
Column: 182
Char: >
    at error (C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:651:10)
    at strictFail (C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:677:7)
    at closeTag (C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:879:7)
    at SAXParser.write (C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:1443:13)
    at SAXStream.write (C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:239:18)
    at ReadStream.ondata (node:internal/streams/readable:754:22)
    at ReadStream.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
onError @ C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\gui\MenuBar.js:221
(anonymous) @ C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\import-enex.js:420
emit @ node:events:526
SAXStream._parser.onerror @ C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:194
emit @ C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:624
error @ C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:653
strictFail @ C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:677
closeTag @ C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:879
write @ C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:1443
SAXStream.write @ C:\Temp\2RbtnbFslSHogNBtWbWpBWULstO\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\fork-sax\lib\sax.js:239
ondata @ node:internal/streams/readable:754
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
(anonymous) @ node:internal/fs/streams:275
wrapper @ node:fs:660
DevTools failed to load source map: Could not parse content for file:///C:/Temp/2RbtnbFslSHogNBtWbWpBWULstO/resources/app.asar/InteropService_Importer_EnexToMd.js.map: Unexpected end of JSON input

**Comment by laurent22** [comment]
Was this file generated by Evernote? Because it's corrupted and even Evernote cannot import it. I've added some extra check so that the application simply skips the note in this case, and doesn't get stuck

**Comment by bgoodmansf** [comment]
This note was in an ENEX file with about 700 other notes. I edited the file to reduce it to the single failing note.

Today, I used Evernote to export this single note in an ENEX:
[DSCN0716.JPG..enex.zip](https://github.com/laurent22/joplin/files/12412748/DSCN0716.JPG.enex.zip)

However, Evernote has had an update so this is from version 10.60.4 while the previous file was from 10.58.8.

As you can see the content of the en-note item has changed and no longer includes the "CDATA" text.

The current Evernote is able to import this file correctly.

I don't think my editing would have generated this type of change. It would be interesting to repeat this export on the older version of Evernote, but that is difficult to do since Evernote forces automatic updates now.

In any case, it will be great if Joplin can ignore this type of corrupted data.
