### ISSUE TITLE
npm problem with fs-extra

### ISSUE THREAD

**Issue by ebayer** [laurent22/joplin#871]
Hello

When building, npm gives the following error on npm install:

```
$ npm install                                        

> Joplin@1.0.111 postinstall /home/ebayer/workspace/dev/repos/git/ebayer/joplin/ElectronClient/app
> node compile-jsx.js && node compile-package-info.js && node ../../Tools/copycss.js --copy-fonts

module.js:549
    throw err;
    ^

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ebayer/workspace/dev/repos/git/ebayer/joplin/Tools/copycss.js:1:74)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Joplin@1.0.111 postinstall: `node compile-jsx.js && node compile-package-info.js && node ../../Tools/copycss.js --copy-fonts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Joplin@1.0.111 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

Even installing fs-extra manual or global does not help:

```
$ sudo npm -g install fs-extra@5.0.0
+ fs-extra@5.0.0
added 4 packages in 1.076s

$ npm install fs-extra@5.0.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.1.1 (node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.1.1: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@1.0.1 (node_modules/7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ fs-extra@5.0.0
updated 1 package in 7.546s
```

I also tried cleaning the npm cache and all modules and re-install everything from scratch, to no avail. Npm debug log shows the following:

```
707 silly lifecycle   'node compile-jsx.js && node compile-package-info.js && node ../../Tools/copycss.js --copy-fonts' ]
708 silly lifecycle Joplin@1.0.111~postinstall: Returned: code: 1  signal: null
709 info lifecycle Joplin@1.0.111~postinstall: Failed to exec postinstall script
710 verbose stack Error: Joplin@1.0.111 postinstall: `node compile-jsx.js && node compile-package-info.js && node ../../Tools/copycss.js --copy-fonts`
710 verbose stack Exit status 1
710 verbose stack     at EventEmitter.<anonymous> (/usr/lib64/node_modules/npm8/node_modules/npm-lifecycle/index.js:285:16)
710 verbose stack     at emitTwo (events.js:126:13)
710 verbose stack     at EventEmitter.emit (events.js:214:7)
710 verbose stack     at ChildProcess.<anonymous> (/usr/lib64/node_modules/npm8/node_modules/npm-lifecycle/lib/spawn.js:55:14)
710 verbose stack     at emitTwo (events.js:126:13)
710 verbose stack     at ChildProcess.emit (events.js:214:7)
710 verbose stack     at maybeClose (internal/child_process.js:925:16)
710 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
711 verbose pkgid Joplin@1.0.111
712 verbose cwd /home/ebayer/workspace/dev/repos/git/ebayer/joplin/ElectronClient/app
713 verbose Linux 4.18.8-1-default
714 verbose argv "/usr/bin/node8" "/usr/bin/npm-default" "install"
715 verbose node v8.11.4
716 verbose npm  v5.6.0
717 error code ELIFECYCLE
718 error errno 1
719 error Joplin@1.0.111 postinstall: `node compile-jsx.js && node compile-package-info.js && node ../../Tools/copycss.js --copy-fonts`
719 error Exit status 1
720 error Failed at the Joplin@1.0.111 postinstall script.
720 error This is probably not a problem with npm. There is likely additional logging output above.
721 verbose exit [ 1, true ]
```

I do not know npm and node very much, any help is appreciated.

### Operating system

- Linux

### Application

- Desktop

**Comment by laurent22** [comment]
Please have a look at BUILD.md as it explains how to build the desktop app.
