### ISSUE TITLE
when i develop a plugin,i met an error that i cannot open the software

### ISSUE THREAD

**Issue by wuyz-harder** [laurent22/joplin#8961]
### hi sir, i use react to develop the plugin,but i think it is not work
but sometimes i start it successful, I don`t know what happen

### here is the  errror report : 

Error
Joplin encountered a fatal error and could not continue.

To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

If the error persists you may try to [restart in safe mode](https://github.com/laurent22/joplin/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=#), which will temporarily disable all plugins.

Message
frameWindow.removeEventListener is not a function

Version info
Joplin for Desktop

Copyright © 2016-2023 Laurent Cozic
Joplin 2.13.1 (dev, darwin)

client ID: c8fc727c0b30469286a7a7631d98892e
syn version：3
config file version：43

fix：d22abe69b (dev)

Calendar: 1.0.0-pre-release-6
comake-plugin: 1.0.0
Plugins
[
    {
        "id": "org.joplinapp.plugins.joplin-calendar",
        "name": "Calendar",
        "enabled": false,
        "version": "1.0.0-pre-release-6"
    }
]
Stack trace
TypeError: frameWindow.removeEventListener is not a function
    at /Users/wuyongzhen/Downloads/project/joplin/packages/app-desktop/services/plugins/hooks/useHtmlLoader.js:30:25
    at safelyCallDestroy (/Users/wuyongzhen/Downloads/project/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:22932:5)
    at commitHookEffectListUnmount (/Users/wuyongzhen/Downloads/project/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:23100:11)
    at commitPassiveUnmountInsideDeletedTreeOnFiber (/Users/wuyongzhen/Downloads/project/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:25098:11)
    at commitPassiveUnmountEffectsInsideOfDeletedTree_begin (/Users/wuyongzhen/Downloads/project/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:25048:5)
    at commitPassiveUnmountEffects_begin (/Users/wuyongzhen/Downloads/project/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:24956:11)
    at commitPassiveUnmountEffects (/Users/wuyongzhen/Downloads/project/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:24941:3)
    at flushPassiveEffectsImpl (/Users/wuyongzhen/Downloads/project/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:27038:3)
    at flushPassiveEffects (/Users/wuyongzhen/Downloads/project/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:26984:14)
    at commitRootImpl (/Users/wuyongzhen/Downloads/project/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:26935:5)
Component stack

    at UserWebview (/Users/wuyongzhen/Downloads/project/joplin/packages/app-desktop/services/plugins/UserWebview.js:42:28)
    at div
    at I (/Users/wuyongzhen/Downloads/project/joplin/packages/app-desktop/node_modules/styled-components/dist/styled-components.cjs.js:1:19269)
    at div

**Comment by wuyz-harder** [comment]
hi sir,i tested for an hour,it has 50 percent to panic,this is my react and webpack info:
```
 "react": "^18.2.0",
 "react-dom": "^18.2.0",
 "webpack": "^5.74.0",
 "webpack-cli": "^4.10.0"
```

**Comment by wuyz-harder** [comment]
in the file  useHtmlLoader.js  , i  Added a layer of judgment to the code to solve this error：
```
if(frameWindow.removeEventListener != undefined){
                frameWindow.removeEventListener('message', onMessage);
            }
```
But I don't know how the error was caused, and whether using this method would cause a memory leak @laurent22

**Comment by laurent22** [comment]
Yes your fix is fine, we just need to apply to the codebase

**Comment by wuyz-harder** [comment]
> Yes your fix is fine, we just need to apply to the codebase

aha,thanks.(expecting)

**Comment by wuyz-harder** [comment]
May I inquire whether you've had the chance to address the issue and if there are any plans to release a new patch version? @laurent22

**Comment by laurent22** [comment]
No, the issue is still open as you can see
