### ISSUE TITLE
Joplin Desktop fails on Windows with "ECONNREFUSED" when syncing with Joplin Server

### ISSUE THREAD

**Issue by mu88** [laurent22/joplin#8987]
Dear @laurent22 ,

Syncing changes from my Win11 device using the Joplin Desktop app to my Joplin Server running on a Raspberry Pi 4 does no longer work - it fails with `ECONNREFUSED`.  
However, when using the Joplin app for Android, the sync works without any issues (even on different Android devices.)

My setting was working without any issues for several months until today. As a first try, I updated both Joplin Server and the Joplin Windows app to the latest version - unfortunately, without luck.

When opening Joplin Server in the web browser (https://myraspi/joplinServer), there are no issues: I can log in, view and edit settings.

Here's the output of `curl --ssl-no-revoke -v -X POST -H "X-API-MIN-VERSION: 2.6.0" -H "Content-Type: application/json" --data '{"email":"myJoplinUser@myraspi","password":"TopSecret"}' https://myraspi/joplinServer/api/sessions` on my Win11 device:
```
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying [<<IPv6 address>>]:443...
*   Trying <<IPv4 address>>:443...
* Connected to myraspi (<<IPv4 address>>) port 443 (#0)
* schannel: disabled automatic use of client certificate
* ALPN: offers http/1.1
* ALPN: server accepted http/1.1
* using HTTP/1.1
> POST /joplinServer/api/sessions HTTP/1.1
> Host: myraspi
> User-Agent: curl/8.0.1
> Accept: */*
> X-API-MIN-VERSION: 2.6.0
> Content-Type: application/json
> Content-Length: 56
>
* schannel: remote party requests renegotiation
* schannel: renegotiating SSL/TLS connection
* schannel: SSL/TLS connection renegotiated
* schannel: remote party requests renegotiation
* schannel: renegotiating SSL/TLS connection
* schannel: SSL/TLS connection renegotiated
< HTTP/1.1 500 Internal Server Error
< Server: nginx/1.18.0
< Date: Sat, 30 Sep 2023 14:36:07 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 52
< Connection: keep-alive
< Vary: Origin
< Content-Security-Policy: frame-ancestors 'none'
< X-Frame-Options: DENY
<
{"error":"Unexpected token ' in JSON at position 0"}* Connection #0 to host myraspi left intact
```

Here's the output of `curl --ssl-no-revoke -v -X POST -H "X-API-MIN-VERSION: 2.6.0" -H "Content-Type: application/json" -H "Content-Length: 62" --data '{"email":"myJoplinUser@myraspi","password":"TopSecret"}' https://myraspi/joplinServer/api/sessions` on my Win11 device:
```
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying [<<IPv6 address>>]:443...
*   Trying <<IPv4 address>>:443...
* Connected to myraspi (<<IPv4 address>>) port 443 (#0)
* schannel: disabled automatic use of client certificate
* ALPN: offers http/1.1
* ALPN: server accepted http/1.1
* using HTTP/1.1
> POST /joplinServer/api/sessions HTTP/1.1
> Host: myraspi
> User-Agent: curl/8.0.1
> Accept: */*
> X-API-MIN-VERSION: 2.6.0
> Content-Type: application/json
> Content-Length: 62
>
* schannel: remote party requests renegotiation
* schannel: renegotiating SSL/TLS connection
* schannel: SSL/TLS connection renegotiated
* schannel: remote party requests renegotiation
* schannel: renegotiating SSL/TLS connection
* schannel: SSL/TLS connection renegotiated
* schannel: server closed abruptly (missing close_notify)
* Closing connection 0
* schannel: shutting down SSL/TLS connection with myraspi port 443
curl: (56) Failure when receiving data from the peer
```

## Environment

Joplin version: `2.13.1` (Joplin Server), `2.12.18` (Joplin Windows app), `2.12.3` (Joplin Android app)
Platform: Linux (Joplin Server), Windows (Joplin Windows app), Android (Joplin Android app)
OS specifics: `Debian GNU/Linux 11 (bullseye)` (Raspberry Pi 4 / Linux Server), `Windows 11 22H2 (OS build 22621.2283)` (Joplin Windows app), `Android 12` (Joplin Android app)

## Steps to reproduce

1. Open Joplin → Tools → Options → Synchronization → Check synchronization configuration

## Describe what you expected to happen
The synchronization check does not fail and Joplin can sync successfully.

## Logfile

```
2023-09-30 16:15:20: JoplinServerApi: "curl -v -X POST -H "X-API-MIN-VERSION: 2.6.0" -H "Content-Type: application/json" -H "Content-Length: 62" --data '{"email":"myJoplinUser@myraspi","password":"******"}' 'https://myraspi/joplinServer/api/sessions'"
2023-09-30 16:15:20: JoplinServerApi: "Code:", "ECONNREFUSED"
2023-09-30 16:15:20: JoplinServerApi: "FetchError: request to https://myraspi/joplinServer/api/sessions failed, reason: connect ECONNREFUSED <<IPv6 address>>:443
Code: ECONNREFUSED
FetchError: request to https://myraspi/joplinServer/api/sessions failed, reason: connect ECONNREFUSED <<IPv6 address>>:443
    at ClientRequest.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\node_modules\node-fetch\lib\index.js:1491:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"
2023-09-30 16:15:20: JoplinServerApi: "Could not acquire session:", "undefined", "
", "FetchError: request to https://myraspi/joplinServer/api/sessions failed, reason: connect ECONNREFUSED <<IPv6 address>>:443
Code: ECONNREFUSED
FetchError: request to https://myraspi/joplinServer/api/sessions failed, reason: connect ECONNREFUSED <<IPv6 address>>:443
    at ClientRequest.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\node_modules\node-fetch\lib\index.js:1491:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"
2023-09-30 16:15:20: SyncTargetJoplinServer: "Could not fetch or parse info.json:", "FetchError: request to https://myraspi/joplinServer/api/sessions failed, reason: connect ECONNREFUSED <<IPv6 address>>:443
Code: ECONNREFUSED
FetchError: request to https://myraspi/joplinServer/api/sessions failed, reason: connect ECONNREFUSED <<IPv6 address>>:443
    at ClientRequest.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\node_modules\node-fetch\lib\index.js:1491:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"
2023-09-30 16:15:22: JoplinServerApi: "curl -v -X POST -H "X-API-MIN-VERSION: 2.6.0" -H "Content-Type: application/json" -H "Content-Length: 62" --data '{"email":"myJoplinUser@myraspi","password":"******"}' 'https://myraspi/joplinServer/api/sessions'"
2023-09-30 16:15:22: JoplinServerApi: "Code:", "ECONNREFUSED"
2023-09-30 16:15:22: JoplinServerApi: "FetchError: request to https://myraspi/joplinServer/api/sessions failed, reason: connect ECONNREFUSED <<IPv6 address>>:443
Code: ECONNREFUSED
FetchError: request to https://myraspi/joplinServer/api/sessions failed, reason: connect ECONNREFUSED <<IPv6 address>>:443
    at ClientRequest.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\node_modules\node-fetch\lib\index.js:1491:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"
2023-09-30 16:15:22: JoplinServerApi: "Could not acquire session:", "undefined", "
", "FetchError: request to https://myraspi/joplinServer/api/sessions failed, reason: connect ECONNREFUSED <<IPv6 address>>:443
Code: ECONNREFUSED
FetchError: request to https://myraspi/joplinServer/api/sessions failed, reason: connect ECONNREFUSED <<IPv6 address>>:443
    at ClientRequest.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\node_modules\node-fetch\lib\index.js:1491:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"
```

**Comment by mu88** [comment]
Update: it seems to be a specific Win11 issue as I don't have the problem on a Win10 device

**Comment by mu88** [comment]
Another update:
- Device 1 (Windows 11)
  - `2.11.11` ✅
  - `2.12.15` ❌
  - `2.12.16` ❌
  - `2.12.17` ❌
  - `2.12.18` ❌
- Device 2 (Windows 10)
  - `2.11.11` ✅
  - `2.12.17` ✅
  - `2.12.18` ❌
- Device 3 (Windows 10)
  - `2.11.11` ✅
  - `2.12.17` ✅
  - `2.12.18` not yet checked

The error message on device 2 (Windows 10) for `2.12.18` is also a bit different:
```
2023-10-03 18:54:40: JoplinServerApi: "curl -v -X POST -H "X-API-MIN-VERSION: 2.6.0" -H "Content-Type: application/json" -H "Content-Length: 55" --data '{"email":"myJoplinUser@myraspi","password":"******"}' 'https://myraspi/joplinServer/api/sessions'"
2023-10-03 18:54:40: JoplinServerApi: "Code:", "undefined"
2023-10-03 18:54:40: JoplinServerApi: "FetchError: network timeout at: https://myraspi/joplinServer/api/sessions
FetchError: network timeout at: https://myraspi/joplinServer/api/sessions
    at C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\node_modules\node-fetch\lib\index.js:1484:13"
2023-10-03 18:54:40: JoplinServerApi: "Could not acquire session:", "undefined", "
", "FetchError: network timeout at: https://myraspi/joplinServer/api/sessions
FetchError: network timeout at: https://myraspi/joplinServer/api/sessions
    at C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\node_modules\node-fetch\lib\index.js:1484:13"
2023-10-03 18:54:40: SyncTargetJoplinServer: "Could not fetch or parse info.json:", "FetchError: network timeout at: https://myraspi/joplinServer/api/sessions
FetchError: network timeout at: https://myraspi/joplinServer/api/sessions
    at C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\node_modules\node-fetch\lib\index.js:1484:13"
```

**Comment by romu70** [comment]
It may be the same issue as this one: https://github.com/laurent22/joplin/issues/8788

Because I also get ECONNREFUSED. Happens only for the macOS version for me.

**Comment by mu88** [comment]
Ouh yes, that looks pretty similar 🙈

**Comment by V1ck3s** [comment]
We continue on #8788
