### ISSUE TITLE
joplin server: "Task is already running" error

### ISSUE THREAD

**Issue by ctr49** [laurent22/joplin#9028]
After running joplin server for a couple of days (3 users, 6 devices, 10 notes) it suddenly crashed with the following log messages (taken from supervisord which is maintaining the node process in my setup - so don't worry about the extra data):

```
2023-10-08 00:00:11,905 DEBG 'joplin' stdout output:
2023-10-08 00:00:11: TaskService: Running #11 (Process shared items) (scheduled)...

2023-10-08 00:00:13,680 DEBG 'joplin' stderr output:

/home/ctr01/joplin_install/packages/server/src/models/TaskStateModel.ts:35
                if (state.running) throw new Error(`Task is already running: ${taskId}`);
                           ^

2023-10-08 00:00:13,680 DEBG 'joplin' stderr output:
Error: Task is already running: 11
    at TaskStateModel.<anonymous> (<install_path>/packages/server/src/models/TaskStateModel.ts:35:28)
    at Generator.next (<anonymous>)
    at fulfilled (<install_path>/packages/server/dist/models/TaskStateModel.js:5:58)

2023-10-08 00:00:13,833 DEBG fd 8 closed, stopped monitoring <POutputDispatcher at 140063883250144 for <Subprocess at 140063883250000 with name joplin in state RUNNING> (stdout)>
2023-10-08 00:00:13,834 DEBG fd 10 closed, stopped monitoring <POutputDispatcher at 140063883248704 for <Subprocess at 140063883250000 with name joplin in state RUNNING> (stderr)>
2023-10-08 00:00:13,835 INFO exited: joplin (exit status 1; not expected)
```

I can't tell what the original problem was, but this resulted in joplin being unable to restart. When trying to do so it also complained about task 11 already running.

Indeed the `task_state` table in the database contained a `running` flag for task 11 (and task 2?):

| id | task_id | running | enabled | updated_time | created_time |
| --- | --- | --- | --- | --- | --- |
1|1|0|1|1696716003011|1696529842014
2|2|1|1|1696716000463|1696529842051
3|7|0|1|1696716003028|1696529842075
4|8|0|1|1696713000210|1696529842102
5|3|0|1|1696710600307|1696529842125
6|6|0|1|1696716003022|1696529842146
7|10|0|1|1696713300644|1696529842171
8|11|1|1|1696716004361|1696529842198
9|12|0|1|1696759260696|1696529842218

After manually clearing the `running` flag I could start joplin server again.

## Environment

Joplin version: 2.12.18 with sqlite backend
Platform: Linux (amd64)
OS specifics: CentOS 7, node.js v18.18.0

## Steps to reproduce

1. Crash in task processing stage (not really reproducible - an offline update of task_state, may make this reproducible)
2. Restart joplin server after the crash (or DB task_state modification)
3. Observe "Task is already running" error

## Describe what you expected to happen

I would expect Joplin to clean-up the task_state when starts from scratch (and it can be ensured that no concurrent task is running).

## Logfile

see above description

**Comment by laurent22** [comment]
The latest version 2.13 has a fix for this
