### ISSUE TITLE
Plugins do not run when PROFILE switch is used

### ISSUE THREAD

**Issue by hp6393** [laurent22/joplin#9090]
When using the "--profile" switch in Windows 11 to store the profile in a different location, everything works fine, but all plugins do not run.

## Environment

Joplin version: 2.12.18 (Win 32) 
Platform: PC/Windows
OS specifics: Windows 11 

## Steps to reproduce

1.  Run joplin.exe --profile \path\to\folder
2.  Joplin loads and functions normally. All notes are there.
3.  My 10 plugins appear under Tools | Options and are turned on, but none of the plugins are running (i.e., Simple Backup plug-in does not appear on the Tools menu; Whitespacer plug-in does not add white space marks to the notes, etc.).

## Describe what you expected to happen

Plugins run and work normally.

## Logfile

2023-10-17 23:07:56: PluginService: "Loading plugin from C:\Users\xxxxxxx\Thumb Drive Mount\Joplin\plugins"
2023-10-17 23:07:56: PluginService: "Could not load plugin: C:\Users\xxxxxxx\Thumb Drive Mount\Joplin\plugins", "Error: Error: ENOENT: no such file or directory, open 'C:\Users\xxxxxxx\Thumb Drive Mount\Joplin\plugins\dist\index.js'. Path: C:\Users\xxxxxxx\Thumb Drive Mount\Joplin\plugins/dist/index.js  [This path and file *did* exist. Note the slash differences.]
Code: ENOENT
Error: Error: ENOENT: no such file or directory, open 'C:\Users\xxxxxxx\Thumb Drive Mount\Joplin\plugins\dist\index.js'. Path: C:\Users\xxxxxxx\Thumb Drive Mount\Joplin\plugins/dist/index.js  [This path and file *did* exist. Note the slash differences.]
    at FsDriverNode.fsErrorToJsError_ (C:\Users\xxxxxxx\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\fs-driver-node.js:22:24)
    at FsDriverNode.<anonymous> (C:\Users\xxxxxxx\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\fs-driver-node.js:182:28)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\xxxxxxx\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\fs-driver-node.js:6:65)"
2023-10-17 23:07:56: joplin.plugins: "Starting plugin: net.gagnepain.turnToChart"
2023-10-17 23:07:56: SpellCheckerServiceDriverNative: "Set effective languages to "en-US""
2023-10-17 23:07:58: joplin.plugins: "Starting plugin: joplin.plugin.templates"
2023-10-17 23:07:58: joplin.plugins: "Starting plugin: org.joplinapp.plugins.ToggleSidebars"
2023-10-17 23:07:58: joplin.plugins: "Starting plugin: org.joplinapp.plugins.whitespacer"
2023-10-17 23:07:58: joplin.plugins: "Starting plugin: net.rmusin.resource-search"
2023-10-17 23:07:58: joplin.plugins: "Finished running onStart handler: net.gagnepain.turnToChart (Took 1613ms)"
2023-10-17 23:07:58: joplin.plugins: "Finished running onStart handler: org.joplinapp.plugins.whitespacer (Took 546ms)"
2023-10-17 23:07:58: RevisionService: "maintenance: Starting..."
2023-10-17 23:07:58: RevisionService: "maintenance: Service is enabled"
2023-10-17 23:07:58: joplin.plugins: "Finished running onStart handler: org.joplinapp.plugins.ToggleSidebars (Took 654ms)"
2023-10-17 23:07:58: RevisionService: "collectRevisions: Created revisions for 0 notes"
2023-10-17 23:07:59: checkForUpdates: "Starting..."
2023-10-17 23:07:59: checkForUpdates: "Checking with options {"includePreReleases":false}"
2023-10-17 23:08:00: joplin.plugins: "Finished running onStart handler: net.rmusin.resource-search (Took 2424ms)"
2023-10-17 23:08:01: joplin.plugins: "Finished running onStart handler: joplin.plugin.templates (Took 3086ms)"
2023-10-17 23:08:01: checkForUpdates: "Current version: 2.12.18"
2023-10-17 23:08:01: checkForUpdates: "Latest version: 2.12.18"
2023-10-17 23:08:01: checkForUpdates: "Is Pre-release:", "false"
2023-10-17 23:08:01: checkForUpdates: "Done."
2023-10-17 23:08:01: RevisionService: "maintenance: Done in 2968ms"
2023-10-17 23:08:03: Synchronizer: "Sync: fetchingTotal: Fetching delta items from sync target"
2023-10-17 23:08:04: "SearchEngine: Updating FTS table..."
2023-10-17 23:08:04: "SearchEngine: Updated FTS table in 4ms. Inserted: 0. Deleted: 0"
2023-10-17 23:08:04: Synchronizer: "Sync: finished: Synchronisation finished [1697598475394]"
2023-10-17 23:08:04: Synchronizer: "Operations completed: "
2023-10-17 23:08:04: Synchronizer: "fetchingTotal: -"
2023-10-17 23:08:04: Synchronizer: "Total folders: 76"
2023-10-17 23:08:04: Synchronizer: "Total notes: 6086"
2023-10-17 23:08:04: Synchronizer: "Total resources: 5686"
2023-10-17 23:08:04: "Updating all notifications..."
2023-10-17 23:08:04: "Garbage collecting alarms..."
2023-10-17 23:08:04: "Sync has finished and note has never been changed - reloading it"

**Comment by laurent22** [comment]
The profile switch is not supported
