### ISSUE TITLE
CodeMirrorBundle is not defined after building Android app

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9213]
After building the Android app, in dev mode:

- Create a new note
- Open it

Getting the error `CodeMirrorBundle is not defined`.

I guess it's the same error that someone got in the prerelease app, where they couldn't see the editor?

<img width="381" alt="image" src="https://github.com/laurent22/joplin/assets/1285584/5a9fb2ea-463d-4b71-89cb-8eddcbfcdcd4">

Also another error, probably related:

<img width="381" alt="image" src="https://github.com/laurent22/joplin/assets/1285584/8eff8e61-94c7-449a-9cb0-c256486b6c7f">

**Comment by personalizedrefrigerator** [comment]
So far (on my Ubuntu 23.10 computer), I haven't been able to reproduce this. However, I have encountered a `react-native-vosk`-related build issue. Here's what I've tried.

1. Start an Android emulator
2. Uninstall Joplin (a development version)
```
zsh$ adb shell                    
emulator64_x86_64_arm64:/ $ pm uninstall net.cozic.joplin
Success
emulator64_x86_64_arm64:/ $ ^D
zsh$
```

3. Clean all `.gitignore`d files and reinstall
```
zsh$ pwd
/home/builder/Documents/joplin
zsh$ git clean -dXi
...
zsh$ yarn
...
```

4. Switch to the `app-mobile` directory and run `yarn start`, then press <kbd>a</kbd> to launch on Android.
```
zsh$ cd packages/app-mobile
zsh$ yarn start
warn Package react-native-fingerprint-scanner contains invalid configuration: "dependency.assets" is not allowed,"dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Package react-native-sqlite-storage contains invalid configuration: "dependency.platforms.ios.project" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Package rn-fetch-blob contains invalid configuration: "dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.

                        ▒▒▓▓▓▓▒▒
                     ▒▓▓▓▒▒░░▒▒▓▓▓▒
                  ▒▓▓▓▓░░░▒▒▒▒░░░▓▓▓▓▒
                 ▓▓▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▓▓
                 ▓▓░░░░░▒▓▓▓▓▓▓▒░░░░░▓▓
                 ▓▓░░▓▓▒░░░▒▒░░░▒▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▒▒▒▒▓▓▓▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▓▓▓▓▓▓▓▓▒░░▓▓
                 ▓▓▒░░▒▒▓▓▓▓▓▓▓▓▒░░░▒▓▓
                  ▒▓▓▓▒░░░▒▓▓▒░░░▒▓▓▓▒
                     ▒▓▓▓▒░░░░▒▓▓▓▒
                        ▒▒▓▓▓▓▒▒


warning: the transform cache was reset.
                Welcome to Metro v0.73.9
              Fast - Scalable - Integrated

r - reload the app
d - open developer menu
i - run on iOS
a - run on Android

a
info Opening the app on Android...

node:internal/fs/watchers:252
    throw error;
    ^

Error: ENOENT: no such file or directory, watch '/home/builder/Documents/joplin/packages/app-mobile/node_modules/react-native-vosk/android/build/kotlin/compileDebugKotlin/cacheable/caches-jvm'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2315:34)
    at NodeWatcher._watchdir (/home/builder/Documents/joplin/packages/app-mobile/node_modules/metro-file-map/src/watchers/NodeWatcher.js:145:24)
    at /home/builder/Documents/joplin/packages/app-mobile/node_modules/metro-file-map/src/watchers/NodeWatcher.js:264:22
    at Walker.<anonymous> (/home/builder/Documents/joplin/packages/app-mobile/node_modules/metro-file-map/src/watchers/common.js:135:31)
    at Walker.emit (node:events:513:28)
    at /home/builder/Documents/joplin/packages/app-mobile/node_modules/walker/lib/walker.js:69:16
    at FSReqCallback.oncomplete (node:fs:197:23) {
  errno: -2,
  syscall: 'watch',
  code: 'ENOENT',
  path: '/home/builder/Documents/joplin/packages/app-mobile/node_modules/react-native-vosk/android/build/kotlin/compileDebugKotlin/cacheable/caches-jvm',
  filename: '/home/builder/Documents/joplin/packages/app-mobile/node_modules/react-native-vosk/android/build/kotlin/compileDebugKotlin/cacheable/caches-jvm'
}

Node.js v18.13.0
```

4. After it fails, run `yarn start` again:
```
zsh$ yarn start
warn Package react-native-fingerprint-scanner contains invalid configuration: "dependency.assets" is not allowed,"dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Package react-native-sqlite-storage contains invalid configuration: "dependency.platforms.ios.project" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Package rn-fetch-blob contains invalid configuration: "dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.

                        ▒▒▓▓▓▓▒▒
                     ▒▓▓▓▒▒░░▒▒▓▓▓▒
                  ▒▓▓▓▓░░░▒▒▒▒░░░▓▓▓▓▒
                 ▓▓▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▓▓
                 ▓▓░░░░░▒▓▓▓▓▓▓▒░░░░░▓▓
                 ▓▓░░▓▓▒░░░▒▒░░░▒▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▒▒▒▒▓▓▓▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▓▓▓▓▓▓▓▓▒░░▓▓
                 ▓▓▒░░▒▒▓▓▓▓▓▓▓▓▒░░░▒▓▓
                  ▒▓▓▓▒░░░▒▓▓▒░░░▒▓▓▓▒
                     ▒▓▓▓▒░░░░▒▓▓▓▒
                        ▒▒▓▓▓▓▒▒


warning: the transform cache was reset.
                Welcome to Metro v0.73.9
              Fast - Scalable - Integrated

r - reload the app
d - open developer menu
i - run on iOS
a - run on Android

a
info Opening the app on Android...
 BUNDLE  ./index.js ▓▓▓▓░░░░░░░░░░░░ 29.3% (872/1625)
```
5. Create a new notebook and note
6. Edit the note

After step 5, for me, the note editor is visible without errors.

I plan to try the above steps on MacOS next.

**Comment by personalizedrefrigerator** [comment]
I wasn't able to reproduce this on MacOS either. Does running `yarn start` again fix the issue? What if `yarn build` is re-run?

(I do think that this is probably a build issue &mdash; I was able to reproduce this very consistently on an older version of the TestFlight release and a prerelease on Android).

**Comment by personalizedrefrigerator** [comment]
If this is related to the custom minification logic, https://github.com/laurent22/joplin/pull/9221 may fix this issue.

**Comment by laurent22** [comment]
With the recent improvements to the Gulp tasks I think it should be fine now. And hopefully if something still fails it will be clearer what it is
