### ISSUE TITLE
Database savepoint error

### ISSUE THREAD

**Issue by viharm** [laurent22/joplin#9223]
Similar to #6605

When I start to sync on Linux client I encounter several errors on the Joplin server :

On the client:
```
Created remote items: 1.
Completed: 2023-11-06 19:29 (5s)
Last error: Error: SAVEPOINT sp_EFwfaB8v6GkEHaOFCHs2O3 - current transaction is aborted, commands ignored until end of transaction block

```

On the server (last line of the several error lines:
```
19:29:12 0|app  | 2023-11-06 19:29:12: [error] db: SAVEPOINT sp_EFwfaB8v6GkEHaOFCHs2O3 - current transaction is aborted, commands ignored until end of transaction block
```

## Environment

Joplin 2.12.18 (prod, linux)
Sync Version: 3
Profile Version: 43
Keychain Supported: No
Linux Kubuntu Desktop 20.04

## Steps to reproduce

1. Added lots of new notes inside a nested notebook
2. Waited for auto-sync
4. encountered this error (then checked the server logs)

## Describe what you expected to happen

Message showing successful sync with no errors.

## Logfile

Client console debug output
```
Logger.ts:247 19:29:10: Starting scheduled sync
Logger.ts:247 19:29:10: Synchronizer: Sync: starting: Starting synchronisation to target 9... supportsAccurateTimestamp = true; supportsMultiPut = true [1699298950893]
Logger.ts:247 19:29:10: Synchronizer: Indexing resources...
Logger.ts:247 19:29:10: ResourceService::indexNoteResources: Start
Logger.ts:247 19:29:11: ResourceService::indexNoteResources: Completed
Logger.ts:247 19:29:11: Synchronizer: Sync target remote info: 
SyncInfo
Logger.ts:247 19:29:11: Synchronizer: Sync target is already setup - checking it...
Logger.ts:247 19:29:11: Synchronizer: Sync target local info: 
SyncInfo
Logger.ts:247 19:29:13: Synchronizer: Sync: createRemote: remote does not exist, and local is new and has never been synced: Revision: (Local 832083edcc5e42bc9d33dcc189387863)
Logger.ts:247 19:29:14: Synchronizer: Error: SAVEPOINT sp_EFwfaB8v6GkEHaOFCHs2O3 - current transaction is aborted, commands ignored until end of transaction block
    at ItemUploader.<anonymous> (ItemUploader.ts:49:22)
    at Generator.next (<anonymous>)
    at /app/joplin-desktop/…temUploader.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/joplin-desktop/…temUploader.js:4:12)
    at ItemUploader.serializeAndUploadItem (ItemUploader.ts:36:89)
    at Synchronizer.<anonymous> (Synchronizer.ts:725:28)
    at Generator.next (<anonymous>)
    at fulfilled (/app/joplin-desktop/…ynchronizer.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Logger.ts:247 19:29:14: ShareService: Refresh share invitations:
Logger.ts:247 19:29:15: ShareService: Refreshed shares: 
{items: Array(1), has_more: false}
Logger.ts:247 19:29:15: Synchronizer: Sync: finished: Synchronisation finished [1699298950893]
Logger.ts:247 19:29:16: Synchronizer: Operations completed: 
Logger.ts:247 19:29:16: Synchronizer: createRemote: 1
Logger.ts:247 19:29:16: Synchronizer: Total folders: 88
Logger.ts:247 19:29:16: Synchronizer: Total notes: 868
Logger.ts:247 19:29:16: Synchronizer: Total resources: 51
Logger.ts:247 19:29:16: Synchronizer: There was some errors:
Logger.ts:247 19:29:16: Synchronizer: Error: SAVEPOINT sp_EFwfaB8v6GkEHaOFCHs2O3 - current transaction is aborted, commands ignored until end of transaction block
    at ItemUploader.<anonymous> (ItemUploader.ts:49:22)
    at Generator.next (<anonymous>)
    at /app/joplin-desktop/…temUploader.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/joplin-desktop/…temUploader.js:4:12)
    at ItemUploader.serializeAndUploadItem (ItemUploader.ts:36:89)
    at Synchronizer.<anonymous> (Synchronizer.ts:725:28)
    at Generator.next (<anonymous>)
    at fulfilled (/app/joplin-desktop/…ynchronizer.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
DevTools failed to load source map: Could not load content for file:///app/joplin-desktop/resources/app/gui/note-viewer/pluginAssets/mermaid/mermaid.min.js.map: Unexpected end of JSON input
Logger.ts:247 19:29:17: Sync has finished and note has never been changed - reloading it
Logger.ts:247 19:29:17: DecryptionWorker: cannot start because no master key is currently loaded.
Logger.ts:247 19:29:19: Request: GET /folders?as_tree=1&token=527a095a0047ed05dc472262e54c5515a4f2defc7bdac53da89663b98d7f4206f942108f9507b9fc41cbec5ca837c5576523293827ee741e28ac98a1b61c3635
Logger.ts:247 19:29:29: Request: GET /folders?as_tree=1&token=527a095a0047ed05dc472262e54c5515a4f2defc7bdac53da89663b98d7f4206f942108f9507b9fc41cbec5ca837c5576523293827ee741e28ac98a1b61c3635
Logger.ts:247 19:29:39: Request: GET /folders?as_tree=1&token=527a095a0047ed05dc472262e54c5515a4f2defc7bdac53da89663b98d7f4206f942108f9507b9fc41cbec5ca837c5576523293827ee741e28ac98a1b61c3635
Logger.ts:247 19:29:49: Request: GET /folders?as_tree=1&token=527a095a0047ed05dc472262e54c5515a4f2defc7bdac53da89663b98d7f4206f942108f9507b9fc41cbec5ca837c5576523293827ee741e28ac98a1b61c3635
Logger.ts:247 19:29:59: Request: GET /folders?as_tree=1&token=527a095a0047ed05dc472262e54c5515a4f2defc7bdac53da89663b98d7f4206f942108f9507b9fc41cbec5ca837c5576523293827ee741e28ac98a1b61c3635
```

**Comment by viharm** [comment]
Bumping, since the issue isn’t really fixed. I’ve had to reset the database and create a new client profile.

**Comment by ygol** [comment]
> reset the database

@viharm I have the same problem. How do you reset the database?

**Comment by viharm** [comment]
> > reset the database
> 
> @viharm I have the same problem. How do you reset the database?

Hi, unfortunately it is far less elegant as it sounds. Since I’m running this on _Docker_, I installed a fresh database container and started fresh. However since I had the latest local copy of the notes in my client, I could sync “up” and had all the latest versions of my notes with no loss of data (but lost some of the history of changes that were only in the DB).

Whatever you do, please ensure that you create a backup from the local client in case something goes wrong.
