### ISSUE TITLE
Linux Joplin does not longer sync Dropbox (timed out)

### ISSUE THREAD

**Issue by gerritleman** [laurent22/joplin#9257]
Joplin does not sync with Dropbox
  A fresh install on Fedora 39 does get not passed the Joplin Dropbox-login
I have attached a screenshot of Dropin Joplin folder
![Screenshot_20231110_locks](https://github.com/laurent22/joplin/assets/110778181/980df5db-deee-4f6a-86d4-6522fbfb57ac)

## Environment

Joplin version: 
Joplin 2.12.19 (prod, linux)  
Sync Version: 3  
Profile Version: 43  
Keychain Supported: No
Platform: Linux
OS specifics: Fedora 38, MX Linux 23, Fedora 39
Sync target is Dropbox
I am able to access the Joplin folder on Dropbox via Firefox

## Steps to reproduce

1. Start op Joplin as usual with Dropbox as sync target 
2. Install fresh Joplin and use the Sync Wizard and try got get pas the Joplin Dropbox-login 

## Describe what you expected to happen
I just wanted to see the notes created and deleted as I work on different machines and  different linux distributions

## Logfile
2023-11-10 08:38:40: "Running background sync on timer..."
2023-11-10 08:38:40: "Preparing scheduled sync"
2023-11-10 08:38:40: "Starting scheduled sync"
2023-11-10 08:38:40: Synchronizer: "Sync: starting: Starting synchronisation to target 7... supportsAccurateTimestamp = false; supportsMultiPut = false [1699601920886]"
2023-11-10 08:38:40: Synchronizer: "Indexing resources..."
2023-11-10 08:38:40: "ResourceService::indexNoteResources: Start"
2023-11-10 08:38:40: "ResourceService::indexNoteResources: Completed"
2023-11-10 08:39:53: RevisionService: "maintenance: Starting..."
2023-11-10 08:39:53: RevisionService: "maintenance: Service is enabled"
2023-11-10 08:39:54: RevisionService: "collectRevisions: Created revisions for 0 notes"
2023-11-10 08:39:54: RevisionService: "maintenance: Done in 181ms"
2023-11-10 08:43:40: "Running background sync on timer..."
2023-11-10 08:43:40: "Preparing scheduled sync"
2023-11-10 08:43:40: "Starting scheduled sync"
2023-11-10 08:43:40: "Synchronisation is already in progress. State: in_progress"
2023-11-10 08:47:02: Synchronizer: "FetchError: network timeout at: https://content.dropboxapi.com/2/files/download
FetchError: network timeout at: https://content.dropboxapi.com/2/files/download
    at /app/joplin-desktop/resources/app/node_modules/@joplin/lib/node_modules/node-fetch/lib/index.js:1484:13"
2023-11-10 08:47:02: Synchronizer: "Sync: finished: Synchronisation finished [1699601920886]"
2023-11-10 08:47:02: Synchronizer: "Operations completed: "
2023-11-10 08:47:02: Synchronizer: "Total folders: 32"
2023-11-10 08:47:02: Synchronizer: "Total notes: 74"
2023-11-10 08:47:02: Synchronizer: "Total resources: 59"
2023-11-10 08:47:02: "Sync has finished and note has never been changed - reloading it"
2023-11-10 08:47:03: "DecryptionWorker: cannot start because no master key is currently loaded."
2023-11-10 08:49:53: RevisionService: "maintenance: Starting..."
2023-11-10 08:49:53: RevisionService: "maintenance: Service is enabled"
2023-11-10 08:49:54: RevisionService: "collectRevisions: Created revisions for 0 notes"
2023-11-10 08:49:54: RevisionService: "maintenance: Done in 104ms"
2023-11-10 08:52:02: "Running background sync on timer..."
2023-11-10 08:52:02: "Preparing scheduled sync"
2023-11-10 08:52:02: "Starting scheduled sync"
2023-11-10 08:52:02: Synchronizer: "Sync: starting: Starting synchronisation to target 7... supportsAccurateTimestamp = false; supportsMultiPut = false [1699602722188]"
2023-11-10 08:52:02: Synchronizer: "Indexing resources..."
2023-11-10 08:52:02: "ResourceService::indexNoteResources: Start"
2023-11-10 08:52:02: "ResourceService::indexNoteResources: Completed"
2023-11-10 08:57:02: "Running background sync on timer..."
2023-11-10 08:57:02: "Preparing scheduled sync"
2023-11-10 08:57:02: "Starting scheduled sync"
2023-11-10 08:57:02: "Synchronisation is already in progress. State: in_progress"
2023-11-10 10:25:24: App: "Profile directory: /home/gla/.config/joplin-desktop"
2023-11-10 10:25:24: App: "Root profile directory: /home/gla/.config/joplin-desktop"
2023-11-10 10:25:24: "Database was open successfully"
2023-11-10 10:25:24: "Checking for database schema update..."
2023-11-10 10:25:24: "Current database version", "{"version":43,"table_fields_version":43}"
2023-11-10 10:25:24: "Upgrading database from version 43"
2023-11-10 10:25:24: "New version: 43. Previously recorded version: 43"
2023-11-10 10:25:24: "KeychainService: checking if keychain supported"
2023-11-10 10:25:24: "KeychainService: check was already done - skipping. Supported:", "0"
2023-11-10 10:25:24: e2ee/utils: "Master password is not set - trying to get it from the active master key..."
2023-11-10 10:25:24: handleSyncStartupOperation: "Processing operation:", "0"
2023-11-10 10:25:24: App: "Client ID: 9a12dfb748de419cb1a2d15fa2f1c693"
2023-11-10 10:25:24: models/Setting: "Applying default migrations..."
2023-11-10 10:25:24: e2ee/utils: "Trying to load 0 master keys..."
2023-11-10 10:25:24: e2ee/utils: "Loaded master keys: 0"
2023-11-10 10:25:24: "ResourceFetcher: Auto-add resources: Mode: always"
2023-11-10 10:25:24: "ResourceFetcher: Auto-added resources: 0"
2023-11-10 10:25:24: App: ""syncInfoCache" was changed - setting up encryption related code"
2023-11-10 10:25:24: e2ee/utils: "Trying to load 0 master keys..."
2023-11-10 10:25:24: e2ee/utils: "Loaded master keys: 0"
2023-11-10 10:25:24: App: ""syncInfoCache" was changed - setting up encryption related code"
2023-11-10 10:25:24: e2ee/utils: "Trying to load 0 master keys..."
2023-11-10 10:25:24: e2ee/utils: "Loaded master keys: 0"
2023-11-10 10:25:24: App: ""syncInfoCache" was changed - setting up encryption related code"
2023-11-10 10:25:24: e2ee/utils: "Trying to load 0 master keys..."
2023-11-10 10:25:24: e2ee/utils: "Loaded master keys: 0"
2023-11-10 10:25:24: "app.start: doing regular boot"
2023-11-10 10:25:24: App: ""syncInfoCache" was changed - setting up encryption related code"
2023-11-10 10:25:24: e2ee/utils: "Trying to load 0 master keys..."
2023-11-10 10:25:24: e2ee/utils: "Loaded master keys: 0"
2023-11-10 10:25:24: App: ""syncInfoCache" was changed - setting up encryption related code"
2023-11-10 10:25:24: e2ee/utils: "Trying to load 0 master keys..."
2023-11-10 10:25:24: e2ee/utils: "Loaded master keys: 0"
2023-11-10 10:25:24: App: ""syncInfoCache" was changed - setting up encryption related code"
2023-11-10 10:25:24: e2ee/utils: "Trying to load 0 master keys..."
2023-11-10 10:25:24: e2ee/utils: "Loaded master keys: 0"
2023-11-10 10:25:24: RevisionService: "runInBackground: Starting background service with revision collection interval 600000"
2023-11-10 10:25:24: defaultPluginsUtils: "Could not find default plugins' directory: /app/joplin-desktop/resources/build/defaultPlugins - skipping installation."
2023-11-10 10:25:24: SpellCheckerServiceDriverNative: "Set effective languages to "en-US""
2023-11-10 10:25:25: "DecryptionWorker: cannot start because no master key is currently loaded."
2023-11-10 10:25:25: "Preparing scheduled sync"
2023-11-10 10:25:25: "Saving updated Dropbox auth."
2023-11-10 10:25:25: "Starting scheduled sync"
2023-11-10 10:25:25: Synchronizer: "Sync: starting: Starting synchronisation to target 7... supportsAccurateTimestamp = false; supportsMultiPut = false [1699608325623]"
2023-11-10 10:25:25: Synchronizer: "Indexing resources..."
2023-11-10 10:25:25: "ResourceService::indexNoteResources: Start"
2023-11-10 10:25:26: "ResourceService::indexNoteResources: Completed"
2023-11-10 10:25:28: RevisionService: "maintenance: Starting..."
2023-11-10 10:25:28: RevisionService: "maintenance: Service is enabled"
2023-11-10 10:25:28: RevisionService: "collectRevisions: Created revisions for 0 notes"
2023-11-10 10:25:28: RevisionService: "maintenance: Done in 107ms"
2023-11-10 10:25:34: "SearchEngine: Updating FTS table..."
2023-11-10 10:25:34: "SearchEngine: Updated FTS table in 2ms. Inserted: 0. Deleted: 0"
2023-11-10 10:25:54: "ResourceService::indexNoteResources: Start"
2023-11-10 10:25:54: "ResourceService::indexNoteResources: Completed"
2023-11-10 10:25:54: "ResourceService::deleteOrphanResources:", "[]"
2023-11-10 10:33:34: "Running background sync on timer..."
2023-11-10 10:33:34: "Preparing scheduled sync"
2023-11-10 10:33:34: "Starting scheduled sync"
2023-11-10 10:33:34: "Synchronisation is already in progress. State: in_progress"
2023-11-10 10:33:37: "Fetching geolocation..."
2023-11-10 10:33:37: "Got lat/long"
2023-11-10 10:33:37: "Updating lat/long of note 16a2bb1389354ece972d977db9da5f8b"
2023-11-10 10:33:47: "SearchEngine: Updating FTS table..."
2023-11-10 10:33:47: "SearchEngine: Updated FTS table in 50ms. Inserted: 1. Deleted: 0"
2023-11-10 10:34:02: "SearchEngine: Updating FTS table..."
2023-11-10 10:34:02: "SearchEngine: Updated FTS table in 36ms. Inserted: 1. Deleted: 0"
2023-11-10 10:34:14: "SearchEngine: Updating FTS table..."
2023-11-10 10:34:14: "SearchEngine: Updated FTS table in 51ms. Inserted: 1. Deleted: 0"
2023-11-10 10:34:33: "SearchEngine: Updating FTS table..."
2023-11-10 10:34:33: "SearchEngine: Updated FTS table in 38ms. Inserted: 1. Deleted: 0"
2023-11-10 10:34:45: "SearchEngine: Updating FTS table..."
2023-11-10 10:34:45: "SearchEngine: Updated FTS table in 41ms. Inserted: 1. Deleted: 0"
2023-11-10 10:35:01: "SearchEngine: Updating FTS table..."
2023-11-10 10:35:01: "SearchEngine: Updated FTS table in 36ms. Inserted: 1. Deleted: 0"
2023-11-10 10:35:13: "SearchEngine: Updating FTS table..."
2023-11-10 10:35:13: "SearchEngine: Updated FTS table in 40ms. Inserted: 1. Deleted: 0"
2023-11-10 10:35:24: RevisionService: "maintenance: Starting..."
2023-11-10 10:35:24: RevisionService: "maintenance: Service is enabled"
2023-11-10 10:35:24: RevisionService: "collectRevisions: Created revisions for 1 notes"
2023-11-10 10:35:24: RevisionService: "maintenance: Done in 148ms"
2023-11-10 10:35:27: "SearchEngine: Updating FTS table..."
2023-11-10 10:35:27: "SearchEngine: Updated FTS table in 43ms. Inserted: 1. Deleted: 0"
2023-11-10 10:35:40: "SearchEngine: Updating FTS table..."
2023-11-10 10:35:40: "SearchEngine: Updated FTS table in 38ms. Inserted: 1. Deleted: 0"
2023-11-10 10:35:52: "SearchEngine: Updating FTS table..."
2023-11-10 10:35:52: "SearchEngine: Updated FTS table in 45ms. Inserted: 1. Deleted: 0"
2023-11-10 10:37:50: "SearchEngine: Updating FTS table..."
2023-11-10 10:37:50: "SearchEngine: Updated FTS table in 41ms. Inserted: 1. Deleted: 0"
2023-11-10 10:37:51: Synchronizer: "FetchError: network timeout at: https://content.dropboxapi.com/2/files/download
FetchError: network timeout at: https://content.dropboxapi.com/2/files/download
    at /app/joplin-desktop/resources/app/node_modules/@joplin/lib/node_modules/node-fetch/lib/index.js:1484:13"
2023-11-10 10:37:51: Synchronizer: "Sync: finished: Synchronisation finished [1699608325623]"
2023-11-10 10:37:51: Synchronizer: "Operations completed: "
2023-11-10 10:37:51: Synchronizer: "Total folders: 32"
2023-11-10 10:37:51: Synchronizer: "Total notes: 75"
2023-11-10 10:37:51: Synchronizer: "Total resources: 59"
2023-11-10 10:37:51: "Updating all notifications..."
2023-11-10 10:37:51: "Garbage collecting alarms..."
2023-11-10 10:37:51: "Sync has finished and note has never been changed - reloading it"
2023-11-10 10:37:52: "DecryptionWorker: cannot start because no master key is currently loaded."
2023-11-10 10:37:56: RepositoryApi: "findWorkingMirror: Could not connect to https://raw.githubusercontent.com/joplin/plugins/master:", "FetchError: network timeout at: https://raw.githubusercontent.com/joplin/plugins/master/.gitignore
FetchError: network timeout at: https://raw.githubusercontent.com/joplin/plugins/master/.gitignore
    at /app/joplin-desktop/resources/app/node_modules/@joplin/lib/node_modules/node-fetch/lib/index.js:1484:13"
2023-11-10 10:37:57: RepositoryApi: "findWorkingMirror: Could not connect to https://cdn.staticaly.com/gh/joplin/plugins/master:", "FetchError: request to https://cdn.staticaly.com/gh/joplin/plugins/master/.gitignore failed, reason: write EPROTO 44770748191296:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:231:

Code: EPROTO
FetchError: request to https://cdn.staticaly.com/gh/joplin/plugins/master/.gitignore failed, reason: write EPROTO 44770748191296:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:231:

    at ClientRequest.<anonymous> (/app/joplin-desktop/resources/app/node_modules/@joplin/lib/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"
2023-11-10 10:37:59: RepositoryApi: "findWorkingMirror: Using: https://ghproxy.com/https://raw.githubusercontent.com/joplin/plugins/master"
2023-11-10 10:38:09: "SearchEngine: Updating FTS table..."
2023-11-10 10:38:09: "SearchEngine: Updated FTS table in 31ms. Inserted: 1. Deleted: 0"
2023-11-10 10:38:22: "SearchEngine: Updating FTS table..."
2023-11-10 10:38:22: "SearchEngine: Updated FTS table in 32ms. Inserted: 1. Deleted: 0"
2023-11-10 10:38:27: "Preparing scheduled sync"
2023-11-10 10:38:27: "Starting scheduled sync"
2023-11-10 10:38:27: Synchronizer: "Sync: starting: Starting synchronisation to target 7... supportsAccurateTimestamp = false; supportsMultiPut = false [1699609107130]"
2023-11-10 10:38:27: Synchronizer: "Indexing resources..."
2023-11-10 10:38:27: "ResourceService::indexNoteResources: Start"
2023-11-10 10:38:27: "ResourceService::indexNoteResources: Completed"
2023-11-10 10:38:41: "SearchEngine: Updating FTS table..."
2023-11-10 10:38:41: "SearchEngine: Updated FTS table in 48ms. Inserted: 1. Deleted: 0"
2023-11-10 10:38:53: "SearchEngine: Updating FTS table..."
2023-11-10 10:38:53: "SearchEngine: Updated FTS table in 36ms. Inserted: 1. Deleted: 0"
2023-11-10 10:39:39: "SearchEngine: Updating FTS table..."
2023-11-10 10:39:39: "SearchEngine: Updated FTS table in 41ms. Inserted: 1. Deleted: 0"
2023-11-10 10:39:54: "SearchEngine: Updating FTS table..."
2023-11-10 10:39:54: "SearchEngine: Updated FTS table in 40ms. Inserted: 1. Deleted: 0"
2023-11-10 10:40:06: "SearchEngine: Updating FTS table..."
2023-11-10 10:40:07: "SearchEngine: Updated FTS table in 45ms. Inserted: 1. Deleted: 0"
2023-11-10 10:40:19: "SearchEngine: Updating FTS table..."
2023-11-10 10:40:19: "SearchEngine: Updated FTS table in 32ms. Inserted: 1. Deleted: 0"
2023-11-10 10:40:30: "SearchEngine: Updating FTS table..."
2023-11-10 10:40:30: "SearchEngine: Updated FTS table in 41ms. Inserted: 1. Deleted: 0"
2023-11-10 10:40:46: "SearchEngine: Updating FTS table..."
2023-11-10 10:40:46: "SearchEngine: Updated FTS table in 38ms. Inserted: 1. Deleted: 0"
2023-11-10 10:41:31: "SearchEngine: Updating FTS table..."
2023-11-10 10:41:31: "SearchEngine: Updated FTS table in 39ms. Inserted: 1. Deleted: 0"
2023-11-10 10:41:43: "SearchEngine: Updating FTS table..."
2023-11-10 10:41:44: "SearchEngine: Updated FTS table in 36ms. Inserted: 1. Deleted: 0"
2023-11-10 10:42:07: "SearchEngine: Updating FTS table..."
2023-11-10 10:42:08: "SearchEngine: Updated FTS table in 40ms. Inserted: 1. Deleted: 0"
2023-11-10 10:42:24: "SearchEngine: Updating FTS table..."
2023-11-10 10:42:24: "SearchEngine: Updated FTS table in 39ms. Inserted: 1. Deleted: 0"
2023-11-10 10:42:38: "SearchEngine: Updating FTS table..."
2023-11-10 10:42:38: "SearchEngine: Updated FTS table in 34ms. Inserted: 1. Deleted: 0"
2023-11-10 10:42:51: "Running background sync on timer..."
2023-11-10 10:42:51: "Preparing scheduled sync"
2023-11-10 10:42:51: "Starting scheduled sync"
2023-11-10 10:42:51: "Synchronisation is already in progress. State: in_progress"
2023-11-10 10:42:52: "SearchEngine: Updating FTS table..."
2023-11-10 10:42:52: "SearchEngine: Updated FTS table in 37ms. Inserted: 1. Deleted: 0"
2023-11-10 10:43:20: "SearchEngine: Updating FTS table..."
2023-11-10 10:43:20: "SearchEngine: Updated FTS table in 40ms. Inserted: 1. Deleted: 0"
2023-11-10 10:43:30: "SearchEngine: Updating FTS table..."
2023-11-10 10:43:31: "SearchEngine: Updated FTS table in 40ms. Inserted: 1. Deleted: 0"
2023-11-10 10:43:42: "SearchEngine: Updating FTS table..."
2023-11-10 10:43:42: "SearchEngine: Updated FTS table in 32ms. Inserted: 1. Deleted: 0"
2023-11-10 10:43:54: "SearchEngine: Updating FTS table..."
2023-11-10 10:43:55: "SearchEngine: Updated FTS table in 41ms. Inserted: 1. Deleted: 0"
2023-11-10 10:44:05: "SearchEngine: Updating FTS table..."
2023-11-10 10:44:06: "SearchEngine: Updated FTS table in 42ms. Inserted: 1. Deleted: 0"
2023-11-10 10:45:24: RevisionService: "maintenance: Starting..."
2023-11-10 10:45:24: RevisionService: "maintenance: Service is enabled"
2023-11-10 10:45:24: RevisionService: "collectRevisions: Created revisions for 1 notes"
2023-11-10 10:45:24: RevisionService: "maintenance: Done in 178ms"
2023-11-10 10:46:48: Synchronizer: "FetchError: network timeout at: https://content.dropboxapi.com/2/files/download
FetchError: network timeout at: https://content.dropboxapi.com/2/files/download
    at /app/joplin-desktop/resources/app/node_modules/@joplin/lib/node_modules/node-fetch/lib/index.js:1484:13"
2023-11-10 10:46:48: Synchronizer: "Sync: finished: Synchronisation finished [1699609107130]"
2023-11-10 10:46:48: Synchronizer: "Operations completed: "
2023-11-10 10:46:48: Synchronizer: "Total folders: 32"
2023-11-10 10:46:48: Synchronizer: "Total notes: 75"
2023-11-10 10:46:48: Synchronizer: "Total resources: 59"
2023-11-10 10:46:48: "Sync has finished and note has never been changed - reloading it"
2023-11-10 10:51:48: "Running background sync on timer..."
2023-11-10 10:51:48: "Preparing scheduled sync"
2023-11-10 10:51:48: "Starting scheduled sync"
2023-11-10 10:51:48: Synchronizer: "Sync: starting: Starting synchronisation to target 7... supportsAccurateTimestamp = false; supportsMultiPut = false [1699609908455]"
2023-11-10 10:51:48: Synchronizer: "Indexing resources..."
2023-11-10 10:51:48: "ResourceService::indexNoteResources: Start"
2023-11-10 10:51:48: "ResourceService::indexNoteResources: Completed"
2023-11-10 10:55:24: RevisionService: "maintenance: Starting..."
2023-11-10 10:55:24: RevisionService: "maintenance: Service is enabled"
2023-11-10 10:55:24: RevisionService: "collectRevisions: Created revisions for 0 notes"
2023-11-10 10:55:24: RevisionService: "maintenance: Done in 104ms"
2023-11-10 10:56:48: "Running background sync on timer..."
2023-11-10 10:56:48: "Preparing scheduled sync"
2023-11-10 10:56:48: "Starting scheduled sync"
2023-11-10 10:56:48: "Synchronisation is already in progress. State: in_progress"
2023-11-10 11:00:09: Synchronizer: "FetchError: network timeout at: https://content.dropboxapi.com/2/files/download
FetchError: network timeout at: https://content.dropboxapi.com/2/files/download
    at /app/joplin-desktop/resources/app/node_modules/@joplin/lib/node_modules/node-fetch/lib/index.js:1484:13"
2023-11-10 11:00:09: Synchronizer: "Sync: finished: Synchronisation finished [1699609908455]"
2023-11-10 11:00:09: Synchronizer: "Operations completed: "
2023-11-10 11:00:09: Synchronizer: "Total folders: 32"
2023-11-10 11:00:09: Synchronizer: "Total notes: 75"
2023-11-10 11:00:09: Synchronizer: "Total resources: 59"
2023-11-10 11:00:09: "Sync has finished and note has never been changed - reloading it"
2023-11-10 11:00:10: "DecryptionWorker: cannot start because no master key is currently loaded."
2023-11-10 11:05:09: "Running background sync on timer..."
2023-11-10 11:05:09: "Preparing scheduled sync"
2023-11-10 11:05:09: "Starting scheduled sync"
2023-11-10 11:05:09: Synchronizer: "Sync: starting: Starting synchronisation to target 7... supportsAccurateTimestamp = false; supportsMultiPut = false [1699610709818]"
2023-11-10 11:05:09: Synchronizer: "Indexing resources..."
2023-11-10 11:05:09: "ResourceService::indexNoteResources: Start"
2023-11-10 11:05:09: "ResourceService::indexNoteResources: Completed"
2023-11-10 11:05:24: RevisionService: "maintenance: Starting..."
2023-11-10 11:05:24: RevisionService: "maintenance: Service is enabled"
2023-11-10 11:05:24: RevisionService: "collectRevisions: Created revisions for 0 notes"
2023-11-10 11:05:24: RevisionService: "maintenance: Done in 105ms"
2023-11-10 11:10:09: "Running background sync on timer..."
2023-11-10 11:10:09: "Preparing scheduled sync"
2023-11-10 11:10:09: "Starting scheduled sync"
2023-11-10 11:10:09: "Synchronisation is already in progress. State: in_progress"
2023-11-10 11:13:30: Synchronizer: "FetchError: network timeout at: https://content.dropboxapi.com/2/files/download
FetchError: network timeout at: https://content.dropboxapi.com/2/files/download
    at /app/joplin-desktop/resources/app/node_modules/@joplin/lib/node_modules/node-fetch/lib/index.js:1484:13"
2023-11-10 11:13:30: Synchronizer: "Sync: finished: Synchronisation finished [1699610709818]"
2023-11-10 11:13:30: Synchronizer: "Operations completed: "
2023-11-10 11:13:30: Synchronizer: "Total folders: 32"
2023-11-10 11:13:30: Synchronizer: "Total notes: 75"
2023-11-10 11:13:30: Synchronizer: "Total resources: 59"
2023-11-10 11:13:31: "Sync has finished and note has never been changed - reloading it"
2023-11-10 11:13:32: "DecryptionWorker: cannot start because no master key is currently loaded."
2023-11-10 11:15:24: RevisionService: "maintenance: Starting..."
2023-11-10 11:15:24: RevisionService: "maintenance: Service is enabled"
2023-11-10 11:15:24: RevisionService: "collectRevisions: Created revisions for 0 notes"
2023-11-10 11:15:24: RevisionService: "maintenance: Done in 105ms"
2023-11-10 11:18:31: "Running background sync on timer..."
2023-11-10 11:18:31: "Preparing scheduled sync"
2023-11-10 11:18:31: "Starting scheduled sync"
2023-11-10 11:18:31: Synchronizer: "Sync: starting: Starting synchronisation to target 7... supportsAccurateTimestamp = false; supportsMultiPut = false [1699611511117]"
2023-11-10 11:18:31: Synchronizer: "Indexing resources..."
2023-11-10 11:18:31: "ResourceService::indexNoteResources: Start"
2023-11-10 11:18:31: "ResourceService::indexNoteResources: Completed"
2023-11-10 11:23:31: "Running background sync on timer..."
2023-11-10 11:23:31: "Preparing scheduled sync"
2023-11-10 11:23:31: "Starting scheduled sync"
2023-11-10 11:23:31: "Synchronisation is already in progress. State: in_progress"
2023-11-10 11:25:24: "Garbage collecting alarms..."
2023-11-10 11:25:24: RevisionService: "maintenance: Starting..."
2023-11-10 11:25:24: RevisionService: "maintenance: Service is enabled"
2023-11-10 11:25:24: RevisionService: "collectRevisions: Created revisions for 0 notes"
2023-11-10 11:25:24: RevisionService: "maintenance: Done in 104ms"
2023-11-10 11:26:23: RepositoryApi: "findWorkingMirror: Could not connect to https://raw.githubusercontent.com/joplin/plugins/master:", "FetchError: network timeout at: https://raw.githubusercontent.com/joplin/plugins/master/.gitignore
FetchError: network timeout at: https://raw.githubusercontent.com/joplin/plugins/master/.gitignore
    at /app/joplin-desktop/resources/app/node_modules/@joplin/lib/node_modules/node-fetch/lib/index.js:1484:13"
2023-11-10 11:26:24: RepositoryApi: "findWorkingMirror: Could not connect to https://cdn.staticaly.com/gh/joplin/plugins/master:", "FetchError: request to https://cdn.staticaly.com/gh/joplin/plugins/master/.gitignore failed, reason: write EPROTO 44770748191296:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:231:

Code: EPROTO
FetchError: request to https://cdn.staticaly.com/gh/joplin/plugins/master/.gitignore failed, reason: write EPROTO 44770748191296:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:231:

    at ClientRequest.<anonymous> (/app/joplin-desktop/resources/app/node_modules/@joplin/lib/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"
2023-11-10 11:26:25: RepositoryApi: "findWorkingMirror: Using: https://ghproxy.com/https://raw.githubusercontent.com/joplin/plugins/master"
2023-11-10 11:26:52: Synchronizer: "FetchError: network timeout at: https://content.dropboxapi.com/2/files/download
FetchError: network timeout at: https://content.dropboxapi.com/2/files/download
    at /app/joplin-desktop/resources/app/node_modules/@joplin/lib/node_modules/node-fetch/lib/index.js:1484:13"
2023-11-10 11:26:52: Synchronizer: "Sync: finished: Synchronisation finished [1699611511117]"
2023-11-10 11:26:52: Synchronizer: "Operations completed: "
2023-11-10 11:26:52: Synchronizer: "Total folders: 32"
2023-11-10 11:26:52: Synchronizer: "Total notes: 75"
2023-11-10 11:26:52: Synchronizer: "Total resources: 59"
2023-11-10 11:26:53: "DecryptionWorker: cannot start because no master key is currently loaded."
2023-11-10 11:31:52: "Running background sync on timer..."
2023-11-10 11:31:52: "Preparing scheduled sync"
2023-11-10 11:31:52: "Starting scheduled sync"
2023-11-10 11:31:52: Synchronizer: "Sync: starting: Starting synchronisation to target 7... supportsAccurateTimestamp = false; supportsMultiPut = false [1699612312343]"
2023-11-10 11:31:52: Synchronizer: "Indexing resources..."
2023-11-10 11:31:52: "ResourceService::indexNoteResources: Start"
2023-11-10 11:31:52: "ResourceService::indexNoteResources: Completed"

**Comment by gerritleman** [comment]
Anybody?
