### ISSUE TITLE
"aria" prop prints a warning

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9284]
### Operating system

Windows

### Application version

2.13.5

### Current behaviour

It should be named "ariaRole"? It happens as soon as opening the settings screen.

```
Warning: Invalid aria prop `aria-role` on <a> tag. For details, see https://reactjs.org/link/invalid-aria-props
    at a
    at I (/Users/laurent/src/joplin/packages/app-desktop/node_modules/styled-components/dist/styled-components.cjs.js:1:19269)
    at div
    at I (/Users/laurent/src/joplin/packages/app-desktop/node_modules/styled-components/dist/styled-components.cjs.js:1:19269)
    at Sidebar (/Users/laurent/src/joplin/packages/app-desktop/gui/ConfigScreen/Sidebar.js:82:15)
    at div
    at ConfigScreenComponent (/Users/laurent/src/joplin/packages/app-desktop/gui/ConfigScreen/ConfigScreen.js:42:9)
    at ConnectFunction (/Users/laurent/src/joplin/packages/app-desktop/node_modules/react-redux/lib/components/connect.js:246:74)
    at div
    at NavigatorComponent (/Users/laurent/src/joplin/packages/app-desktop/gui/Navigator.js:7:1)
    at ConnectFunction (/Users/laurent/src/joplin/packages/app-desktop/node_modules/react-redux/lib/components/connect.js:246:74)
    at exports.ThemeProvider (/Users/laurent/src/joplin/packages/app-desktop/node_modules/styled-components/dist/styled-components.cjs.js:1:25001)
    at ae (/Users/laurent/src/joplin/packages/app-desktop/node_modules/styled-components/dist/styled-components.cjs.js:1:13440)
    at RootComponent (/Users/laurent/src/joplin/packages/app-desktop/gui/Root.js:103:1)
    at ConnectFunction (/Users/laurent/src/joplin/packages/app-desktop/node_modules/react-redux/lib/components/connect.js:246:74)
    at ErrorBoundary (/Users/laurent/src/joplin/packages/app-desktop/gui/ErrorBoundary.js:21:9)
    at Provider (/Users/laurent/src/joplin/packages/app-desktop/node_modules/react-redux/lib/components/Provider.js:19:3)
```

**Comment by personalizedrefrigerator** [comment]
`aria-` properties [don't use camel case](https://react.dev/learn/writing-markup-with-jsx#3-camelcase-salls-most-of-the-things) in React. However, I think that should be [`role`](https://react.dev/warnings/invalid-aria-prop) and not `aria-role`.

Thank you for noticing this!
