### ISSUE TITLE
my joplin crashed

### ISSUE THREAD

**Issue by stephen-a2z** [laurent22/joplin#9303]
### Operating system

macOS

### Joplin version

2.12.19

### Desktop version info

Joplin for Desktop

Copyright © 2016-2023 Laurent Cozic
Joplin 2.12.19 (prod, darwin)

Client ID: 838e081837fb4e2eb340af350c38a0b6
Sync Version: 3
Profile Version: 43
Keychain Supported: Yes

Revision: 7081046

Athena: 2.2.3
Attaché: 1.1.1
BibTeX: 0.5.0
Bulk Note Creator: 1.0.0
Code Section: 1.0.6
Code-Clipboard: 1.0.0
Draw.io: 2.2.0
Embed Search: 2.0.0
Emoji: 1.0.4
Jarvis: 0.4.4
JSheets: 1.1.3
Kity Minder: 1.0.16
Rich Markdown: 0.13.2
Templates: 2.4.0
Text Colorize: 1.2.3

### Current behaviour

open the app, 3 secend later, crashed and displayed the error logs

### Expected behaviour

working normally

### Logs

Error
Joplin encountered a fatal error and could not continue.

To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

If the error persists you may try to [restart in safe mode](https://github.com/laurent22/joplin/issues/new?assignees=&labels=bug&projects=&template=BUG_REPORT.yml#), which will temporarily disable all plugins.

Message
frameWindow.removeEventListener is not a function

Version info
Joplin for Desktop

Copyright © 2016-2023 Laurent Cozic
Joplin 2.12.19 (prod, darwin)

Client ID: 838e081837fb4e2eb340af350c38a0b6
Sync Version: 3
Profile Version: 43
Keychain Supported: Yes

Revision: 7081046

Athena: 2.2.3
Attaché: 1.1.1
BibTeX: 0.5.0
Bulk Note Creator: 1.0.0
Code Section: 1.0.6
Code-Clipboard: 1.0.0
Draw.io: 2.2.0
Embed Search: 2.0.0
Emoji: 1.0.4
Jarvis: 0.4.4
JSheets: 1.1.3
Kity Minder: 1.0.16
Rich Markdown: 0.13.2
Templates: 2.4.0
Text Colorize: 1.2.3
Plugins
[
    {
        "id": "io.github.manuerwin.attache",
        "name": "Attaché",
        "enabled": true,
        "version": "1.1.1"
    },
    {
        "id": "com.xUser5000.bibtex",
        "name": "BibTeX",
        "enabled": false,
        "version": "0.5.0"
    },
    {
        "id": "com.ahaltindis.joplin.BulkNoteCreator",
        "name": "Bulk Note Creator",
        "enabled": true,
        "version": "1.0.0"
    },
    {
        "id": "bluulo.JoplinCodeClipboardPlugin",
        "name": "Code-Clipboard",
        "enabled": true,
        "version": "1.0.0"
    },
    {
        "id": "de.habelt.CodeSection",
        "name": "Code Section",
        "enabled": false,
        "version": "1.0.6"
    },
    {
        "id": "com.github.marc0l92.joplin-plugin-drawio",
        "name": "Draw.io",
        "enabled": true,
        "version": "2.2.0"
    },
    {
        "id": "retr0ve.EmojiPlugin",
        "name": "Emoji",
        "enabled": true,
        "version": "1.0.4"
    },
    {
        "id": "joplin.plugin.ambrt.embedSearch",
        "name": "Embed Search",
        "enabled": true,
        "version": "2.0.0"
    },
    {
        "id": "joplin.plugin.alondmnt.jarvis",
        "name": "Jarvis",
        "enabled": true,
        "version": "0.4.4"
    },
    {
        "id": "plugin.calebjohn.rich-markdown",
        "name": "Rich Markdown",
        "enabled": false,
        "version": "0.13.2"
    },
    {
        "id": "joplin.plugin.templates",
        "name": "Templates",
        "enabled": true,
        "version": "2.4.0"
    },
    {
        "id": "sadmice.TextColorize",
        "name": "Text Colorize",
        "enabled": false,
        "version": "1.2.3"
    },
    {
        "id": "com.sctmes.kity-minder",
        "name": "Kity Minder",
        "enabled": true,
        "version": "1.0.16"
    },
    {
        "id": "io.github.makaanneo.Athena",
        "name": "Athena",
        "enabled": true,
        "version": "2.2.3"
    },
    {
        "id": "com.joplin.JSheets",
        "name": "JSheets",
        "enabled": true,
        "version": "1.1.3"
    }
]
Stack trace
TypeError: frameWindow.removeEventListener is not a function
    at /Applications/Joplin.app/Contents/Resources/app.asar/services/plugins/hooks/useHtmlLoader.js:30:25
    at safelyCallDestroy (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22932:5)
    at commitHookEffectListUnmount (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23100:11)
    at commitPassiveUnmountInsideDeletedTreeOnFiber (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:25098:11)
    at commitPassiveUnmountEffectsInsideOfDeletedTree_begin (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:25048:5)
    at commitPassiveUnmountEffects_begin (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24956:11)
    at commitPassiveUnmountEffects (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24941:3)
    at flushPassiveEffectsImpl (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:27038:3)
    at flushPassiveEffects (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:26984:14)
    at commitRootImpl (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:26935:5)
Component stack

    at UserWebview (/Applications/Joplin.app/Contents/Resources/app.asar/services/plugins/UserWebview.js:42:28)
    at div
    at I (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/styled-components/dist/styled-components.cjs.js:1:19269)
    at div
    at Resizable (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/re-resizable/lib/index.es5.js:211:28)

**Comment by laurent22** [comment]
It's been fixed in v2.13
