### ISSUE TITLE
`\begin{align}`/`\end{align}` breaks KaTeX rendering

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#9455]
### Operating system

Linux, Android, iOS

### Joplin version

2.13.8

### Desktop version info

Joplin 2.13.8 (prod, linux)

Client ID: 8e9dffaf041d4d34929b525a8c87104a
Sync Version: 3
Profile Version: 44
Keychain Supported: No

Revision: 604dcbc

Freehand Drawing: 2.5.0

### Current behaviour

To reproduce, create a note with the following content:
```md
$$
\begin{align}
    \text{Block}
\end{align}
$$

$\text{Inline}$.
```

### Expected behaviour

Joplin should render the inline KaTeX.

### Logs

Exception and stack trace:

```
/tmp/.mount_Joplinm45GpJ/resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/renderer/MdToHtml/rules/katex.js:243 Katex error for: test TypeError: Cannot read properties of undefined (reading 'map')
    at stringifyKatexOptions (/tmp/.mount_Joplinm45GpJ/resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/renderer/MdToHtml/rules/katex.js:45:56)
    at renderToStringWithCache (/tmp/.mount_Joplinm45GpJ/resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/renderer/MdToHtml/rules/katex.js:227:49)
    at katexInline (/tmp/.mount_Joplinm45GpJ/resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/renderer/MdToHtml/rules/katex.js:261:30)
    at Object.inlineRenderer [as math_inline] (/tmp/.mount_Joplinm45GpJ/resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/renderer/MdToHtml/rules/katex.js:269:20)
    at Renderer.renderInline (/tmp/.mount_Joplinm45GpJ/resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/renderer/node_modules/markdown-it/lib/renderer.js:275:28)
    at Renderer.render (/tmp/.mount_Joplinm45GpJ/resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/renderer/node_modules/markdown-it/lib/renderer.js:330:22)
    at MarkdownIt.render (/tmp/.mount_Joplinm45GpJ/resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/renderer/node_modules/markdown-it/lib/index.js:544:24)
    at MdToHtml.<anonymous> (/tmp/.mount_Joplinm45GpJ/resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/renderer/MdToHtml.js:395:45)
    at Generator.next (<anonymous>)
    at /tmp/.mount_Joplinm45GpJ/resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/renderer/MdToHtml.js:8:71
```

**Comment by personalizedrefrigerator** [comment]
Originally reported on the forum: https://discourse.joplinapp.org/t/inline-math-mode-does-not-work-in-latest-update-2-13-8/34119/6
