### ISSUE TITLE
Link inactive in WYSIWYG panel but work if two panels are deployed

### ISSUE THREAD

**Issue by Emmanuel-L** [laurent22/joplin#9569]
### Operating system

Windows

### Joplin version

2.13.9

### Desktop version info

Joplin 2.13.9 (prod, win32)

ID client : 11e6791b15264684ace7a281865bd347
Version de Synchro : 3
Version du profil : 44
Trousseau supporté : Oui

Révision : 1bbec44

Joplin Evernote Links Replacer: 1.0.0

### Current behaviour

1. Create a "Parent note"
2. Copy markdown link of this parent note
3. Create a "Child note 1"
4. write "parent note - " and paste the link
5. Then the link is inactive by left-click but is active by right-click and "open" of context menu.
6. The link is active (with a Joplin icon) in WYSIWYG panel when the 2 panels are open

### Expected behaviour

The link is active by left-click (and a better user experience ;-), thanks)

**Comment by personalizedrefrigerator** [comment]
Try <kbd>ctrl</kbd>+<kbd>click</kbd>.


If this works, would it make sense to include this information in the welcome notes?

**Comment by Emmanuel-L** [comment]
Does not work.

**Comment by laurent22** [comment]
Yes it seems ctrl+click is broken on Windows. It works for me in macOs

**Comment by laurent22** [comment]
This is the error in the console when doing a ctrl+click:

```
Uncaught (in promise) Error: No item with ID index
    at \AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteEditor\utils\contextMenu.js:53:19
    at Generator.next (<anonymous>)
    at fulfilled (\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteEditor\utils\contextMenu.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by Emmanuel-L** [comment]
Thank you for your quick analysis. 
I think it would be better to use left-click instead of ctrl+click. Less click/typing is better for user experience.

**Comment by tomasz1986** [comment]
> I think it would be better to use left-click instead of ctrl+click. Less click/typing is better for user experience.

If it was triggered by left-click, then you wouldn't be able to easily modify the link text (and many would likely trigger them accidentally). However, I've seen other programs use either double-click or middle-click to open such links, which does make it easier, as you only need to use the mouse to do it. It would also be nice to be able to open links via the right-click menu, but this doesn't work currently, unfortunately.

**Comment by Emmanuel-L** [comment]
Thanks for the idea.
Just for your information I am also an evernote user. The way to do it in evernote is left-click directly (main usage), and when you need to change the name of the link (rare case) you just click on the side of the link and with keyboard arrow or backspace you change it.
I hope it will help in this functional choice.

**Comment by pedr** [comment]
I tested Ctrl+Click on Windows in version 2.13.15 and 2.14.11 (latest dev) and it is working as intended.

The error reported by Laurent seems to happen when you delete the parent note:

```
C:\Projeto\joplin-pu…s\contextMenu.js:53 Uncaught (in promise) Error: No item with ID bf9df92f35ff4e45949f84b94e32d055
    at C:\Projeto\joplin-pu…ontextMenu.js:53:19
    at Generator.next (<anonymous>)
    at fulfilled (C:\Projeto\joplin-pu…contextMenu.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
``` 

Maybe an improvement would be to add a css rule `course: pointer;` for these links.
