### ISSUE TITLE
Error: 405 Method Not Allowed

### ISSUE THREAD

**Issue by 1026742642** [laurent22/joplin#9614]
### Operating system

Windows 10 Education version 22H2 (19045.3448)

### version info

windows desktop: 
Joplin 2.13.11 (prod, win32)
Client ID: 0679726020f74e0da98a05c11697c677
Sync Version: 3
Profile Version: 44
Keychain Supported: yes

docker-server:Joplin Server v2.13.2

### Current behaviour

I have two Windows machines: one is running Windows 10 Education version 22H2 (19045.3448), and the other is running Windows 11 Professional (22621.2861). Both machines have Joplin 2.13.11 (prod, win32) installed. However, when synchronizing on Windows 10, it shows an error with status code 405.
![image](https://github.com/laurent22/joplin/assets/16112685/46a821db-c518-433a-b3dc-090b2c6f91df)

### Logs
```
2023-12-28 15:02:32: Synchronizer: "Sync: finished: Synchronisation finished [1703746930747]"
2023-12-28 15:02:32: Synchronizer: "Operations completed: "
2023-12-28 15:02:32: Synchronizer: "Total folders: 318"
2023-12-28 15:02:32: Synchronizer: "Total notes: 1053"
2023-12-28 15:02:32: Synchronizer: "Total resources: 52"
2023-12-28 15:02:32: Synchronizer: "There was some errors:"
2023-12-28 15:02:32: Synchronizer: "Error: Error 405 Method Not Allowed: <html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>openresty</center>
</body>
</html>

Code: 405
Error: Error 405 Method Not Allowed: <html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>openresty</center>
</body>
</html>

    at newError (C:\Users\Administrator\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\JoplinServerApi.js:193:28)
    at JoplinServerApi.<anonymous> (C:\Users\Administrator\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\JoplinServerApi.js:233:27)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\Administrator\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\JoplinServerApi.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
2023-12-28 15:02:32: "Sync has finished and note has never been changed - reloading it"
2023-12-28 15:02:33: "DecryptionWorker: cannot start because no master key is currently loaded."
```

**Comment by 1026742642** [comment]
Resolved: It was a proxy issue caused by the inability to access [github.com](http://github.com/). Opening Clash resolved the problem.
