### ISSUE TITLE
Unable to clear "Some items cannot be synchronized." warning on Android

### ISSUE THREAD

**Issue by kit299** [laurent22/joplin#9669]
### Operating system

Android

### Joplin version

2.13.10

### Current behaviour

Joplin displays an orange "Some items cannot be synchronized." warning banner at the top of every page - I would like a way to get rid of this banner.

### Expected behaviour

I would like a way to either resolve the synchronization problem, or temporarily dismiss the banner.
One approach would be to provide a button to dismiss the warning, so that it only reappears if a new synchronization issue occurs (i.e. a different note/revision is impacted).

Ideally, it would be possible for Joplin to fix the underlying synchronization issue, rather than merely hiding it by dismissing the warning.

Some background:

I created a note via the desktop Joplin webclipper, that ended up fairly large - about 5MB of HTML. This synchronized to other devices (including the Android device just fine). Some time later (and I think it was several months) this note reported synchronization issues on Android. I remember reading about a Joplin encryption change around this time that was reverted for performance reasons - perhaps this is related. I believe the logs did mention decryption timeouts, but I don't recall and didn't save them.

I noticed that a substantial amount of the note was actually indentation - removing consecutive tabs reduced the note size to around 250KB. So I created a new note, containing this smaller version of the content and deleted the original version of the note.

The new smaller note displays correctly in the Android app - but I am left with some old revisions (which I believe to be from versions of the 5MB note) that Joplin is struggling to delete.

In the logs I see this:
```
"Aborted deletion of old revisions for item "" (rev "e1c69af17a7c490a965825c3927e688d") because one of the revisions is still encrypted", "Error: One of the revision to be deleted is encrypted
Code: revision_encrypted
Error: One of the revision to be deleted is encrypted
```

However, I also see this:

```
"DecryptionWorker: error for: e1c69af17a7c490a965825c3927e688d (revisions)", "Error: Item is not encrypted: e1c69af17a7c490a965825c3927e688d
Error: Item is not encrypted: e1c69af17a7c490a965825c3927e688d
```

So it can't be deleted because it is encrypted - but it can't be decrypted because it is not encrypted....

### Logs

```
01-04T17:39:46: root: "root.biometrics: biometricsDone", "true"
01-04T17:39:46: root: "root.biometrics: biometricsEnabled", "false"
01-04T17:39:46: root: "root.biometrics: shouldShowMainContent", "true"
01-04T17:39:46: root: "root.biometrics: this.state.sensorInfo", "{"enabled":false,"sensorsHaveChanged":false,"supportedSensors":""}"
01-04T17:39:41: "Aborted deletion of old revisions for item "" (rev "e1c69af17a7c490a965825c3927e688d") because one of the revisions is still encrypted", "Error: One of the revision to be deleted is encrypted
Code: revision_encrypted
Error: One of the revision to be deleted is encrypted
    at construct (native)
    at Wrapper (address at index.android.bundle:1:2584138)
    at construct (native)
    at _createSuperInternal (address at index.android.bundle:1:2583214)
    at call (native)
    at JoplinError (address at index.android.bundle:1:2583592)
    at ?anon_0_ (address at index.android.bundle:1:4516607)
    at next (native)
    at fulfilled (address at index.android.bundle:1:4511761)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (address at index.android.bundle:1:218984)
    at _callTimer (address at index.android.bundle:1:217933)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:218097)
    at callReactNativeMicrotasks (address at index.android.bundle:1:220072)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:121378)
    at anonymous (address at index.android.bundle:1:120471)
    at __guard (address at index.android.bundle:1:121219)
    at flushedQueue (address at index.android.bundle:1:120382)
    at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:120325)"
01-04T17:39:41: RevisionService: "maintenance: Done in 513ms"
01-04T17:39:41: RevisionService: "collectRevisions: Created revisions for 0 notes"
01-04T17:39:41: root: "root.biometrics: biometricsDone", "true"
01-04T17:39:41: root: "root.biometrics: biometricsEnabled", "false"
01-04T17:39:41: root: "root.biometrics: shouldShowMainContent", "true"
01-04T17:39:41: root: "root.biometrics: this.state.sensorInfo", "{"enabled":false,"sensorsHaveChanged":false,"supportedSensors":""}"
01-04T17:39:41: RevisionService: "maintenance: Starting..."
01-04T17:39:41: RevisionService: "maintenance: Service is enabled"
01-04T17:39:24: "ResourceFetcher: Auto-added resources: 0"
01-04T17:39:24: "ResourceFetcher: Auto-add resources: Mode: always"
01-04T17:39:24: "DecryptionWorker: completed decryption."
01-04T17:39:21: "ResourceFetcher: Auto-added resources: 0"
01-04T17:39:21: "ResourceFetcher: Auto-add resources: Mode: always"
01-04T17:39:21: "SearchEngine: Updated FTS table in 4017ms. Inserted: 14. Deleted: 0"
01-04T17:39:20: root: "root.biometrics: this.state.sensorInfo", "{"enabled":false,"sensorsHaveChanged":false,"supportedSensors":""}"
01-04T17:39:20: root: "root.biometrics: biometricsDone", "true"
01-04T17:39:20: root: "root.biometrics: biometricsEnabled", "false"
01-04T17:39:20: root: "root.biometrics: shouldShowMainContent", "true"
01-04T17:39:20: Synchronizer: "Total folders: 84"
01-04T17:39:20: Synchronizer: "Total notes: 2578"
01-04T17:39:20: Synchronizer: "Total resources: 7624"
01-04T17:39:20: Synchronizer: "Operations completed: "
01-04T17:39:20: Synchronizer: "Sync: finished: Synchronisation finished [1704418756570]"
01-04T17:39:20: Synchronizer: "TaskQueue.stop: syncDownload: waiting for tasks to complete: 0"
01-04T17:39:20: Synchronizer: "TaskQueue.stop: syncDownload: Done, waited for 0"
01-04T17:39:20: "ResourceFetcher: Auto-added resources: 0"
01-04T17:39:20: "ResourceFetcher: Auto-add resources: Mode: always"
01-04T17:39:20: Synchronizer: "Sync target remote info:", ---cut---
01-04T17:39:20: Synchronizer: "Sync target is already setup - checking it..."
01-04T17:39:20: Synchronizer: "Sync target local info:", ---cut---
01-04T17:39:20: "ResourceFetcher: Auto-added resources: 0"
01-04T17:39:20: "ResourceFetcher: Auto-add resources: Mode: always"
01-04T17:39:19: "ResourceService::indexNoteResources: Completed"
01-04T17:39:19: root: "root.biometrics: biometricsDone", "true"
01-04T17:39:19: root: "root.biometrics: biometricsEnabled", "false"
01-04T17:39:19: root: "root.biometrics: shouldShowMainContent", "true"
01-04T17:39:19: root: "root.biometrics: this.state.sensorInfo", "{"enabled":false,"sensorsHaveChanged":false,"supportedSensors":""}"
01-04T17:39:17: "DecryptionWorker: error for: e1c69af17a7c490a965825c3927e688d (revisions)", "Error: Item is not encrypted: e1c69af17a7c490a965825c3927e688d
Error: Item is not encrypted: e1c69af17a7c490a965825c3927e688d
    at ?anon_0_ (address at index.android.bundle:1:2576779)
    at next (native)
    at anonymous (address at index.android.bundle:1:2568049)
    at tryCallTwo (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (address at index.android.bundle:1:2567876)
    at decrypt (address at index.android.bundle:1:2576696)
    at ?anon_0__loop (address at index.android.bundle:1:3664033)
    at next (native)
    at ?anon_0_ (address at index.android.bundle:1:3663069)
    at next (native)
    at fulfilled (address at index.android.bundle:1:3660623)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (address at index.android.bundle:1:218984)
    at _callTimer (address at index.android.bundle:1:217933)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:218097)
    at callReactNativeMicrotasks (address at index.android.bundle:1:220072)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:121378)
    at anonymous (address at index.android.bundle:1:120471)
    at __guard (address at index.android.bundle:1:121219)
    at flushedQueue (address at index.android.bundle:1:120382)
    at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:120325)", "{"created_time":1704418731199,"updated_time":1704335074524,"item_updated_time":0,"encryption_applied":1,"metadata_diff":"","encryption_cipher_text":null,"body_diff":"","item_id":"","title_diff":"","item_type":0,"parent_id":"","id":"e1c69af17a7c490a965825c3927e688d","type_":13}"
01-04T17:39:17: "ResourceFetcher: Auto-added resources: 4"
01-04T17:39:17: "ResourceFetcher: Auto-add resources: Mode: always"
01-04T17:39:17: "SearchEngine: Updating FTS table..."
01-04T17:39:16: Synchronizer: "Indexing resources..."
01-04T17:39:16: "ResourceService::indexNoteResources: Start"
01-04T17:39:16: Synchronizer: "Sync: starting: Starting synchronisation to target 8... supportsAccurateTimestamp = false; supportsMultiPut = false [1704418756570]"
01-04T17:39:16: root: "root.biometrics: biometricsDone", "true"
01-04T17:39:16: root: "root.biometrics: biometricsEnabled", "false"
01-04T17:39:16: root: "root.biometrics: shouldShowMainContent", "true"
01-04T17:39:16: root: "root.biometrics: this.state.sensorInfo", "{"enabled":false,"sensorsHaveChanged":false,"supportedSensors":""}"
01-04T17:39:16: "Preparing scheduled sync"
01-04T17:39:16: "Starting scheduled sync"
```

**Comment by kit299** [comment]
Yes, this is still an issue.
