### ISSUE TITLE
Mobile: Fails to start with error "cannot set property dispatch of undefined"

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#9678]
### Operating system

Android

### Joplin version

2bf2395f1b9e4910e5a00d8f9cadfee48a6c796d

### Current behaviour

Currently, when running the mobile app, an error is logged to the console and the screen remains white.

To reproduce:
1. Run the mobile app

### Expected behaviour

Joplin should launch without an error.

### Logs

```
 WARN  Possible Unhandled Promise Rejection (id: 3):
TypeError: Cannot set property 'dispatch' of undefined
TypeError: Cannot set property 'dispatch' of undefined
    at ?anon_0_ (http://localhost:8081/root.bundle?platform=android&app=net.cozic.joplin&modulesOnly=true&dev=true&minify=false&runModule=true&shallow=true:357:106)
    at next (native)
    at fulfilled (http://localhost:8081/root.bundle?platform=android&app=net.cozic.joplin&modulesOnly=true&dev=true&minify=false&runModule=true&shallow=true:15:30)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/5815x2p5/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/5815x2p5/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:27987:26)
    at _callTimer (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:27906:17)
    at _callReactNativeMicrotasksPass (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:27936:17)
    at callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:28099:44)
    at __callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:4267:46)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:4079:45)
    at __guard (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:4251:15)
    at flushedQueue (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:4078:21)
    at invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:4072:33)
```

The error seems to come from this line:

https://github.com/laurent22/joplin/blob/2bf2395f1b9e4910e5a00d8f9cadfee48a6c796d/packages/app-mobile/root.tsx#L519

### Notes

There may be a similar issue with the Joplin API:

https://github.com/laurent22/joplin/blob/2bf2395f1b9e4910e5a00d8f9cadfee48a6c796d/packages/lib/services/rest/routes/folders.ts#L8

**Comment by personalizedrefrigerator** [comment]
Possibly related to https://github.com/laurent22/joplin/commit/763716397b0ece953e69c17af9f7bc361bc6c001
