### ISSUE TITLE
OneDrive sync target can no longer synchronize: ObjectHandle is invalid

### ISSUE THREAD

**Issue by flo-ri-an** [laurent22/joplin#9703]
### Operating system

Android

### Joplin version

2.13.10

### Current behaviour

When trying to sync manually, Joplin fails for one of two profiles. Both profiles sync to OneDrive.

After triggering the sync, I get the error message "Error: ObjectHandle is invalid"

### Expected behaviour

I would expect that both profiles can sync successfully

### Logs

01-12T09:18:23: "Could not initialise synchroniser: "
01-12T09:18:23: "Error: ObjectHandle is Invalid
Code: invalidRequest
Header: {"map":{"client-request-id":"34e9e240-40e4-4806-9b30-0b60acb2e831","content-type":"application/json","date":"Fri, 12 Jan 2024 08:18:22 GMT","request-id":"34e9e240-40e4-4806-9b30-0b60acb2e831","strict-transport-security":"max-age=31536000","transfer-encoding":"chunked","vary":"Accept-Encoding","x-ms-ags-diagnostic":"{\"ServerInfo\":{\"DataCenter\":\"Switzerland North\",\"Slice\":\"E\",\"Ring\":\"5\",\"ScaleUnit\":\"002\",\"RoleInstance\":\"ZR2PEPF000000F8\"}}"}}
Request: GET https://graph.microsoft.com/v1.0/me/drives/b!Aud4OtrO-UKDYHz6DiRQ9KqSgBwuc2FAu3OqGfoxlpbTg9BlV3L8TqK01RvZeivY/special/approot null null {"headers":{"Authorization":"bearer EwB4A8l6BAAUs5+HQn0N+h2FxWzLS31ZgQVuHsYAASJuQimH/fboXLEQ96pUUQYbc3ScddfuIdxMKmGyKRF+2f0HZb+m7LV4MQYIl2T4w7PV1qFRq4avghCvDucYqnmIa87ei2fPZyOD1FUv3ePOD5f4cjrEkJa57B8gTvd6IZzQGxFzOXh6DZKrSXYCeFuwiuwLjquqjfhqJYIAOu5ViuboFclqQv1AsZvenaDT34pldhzE2AnUffqB1TetG5DJdJEF1go72gbfAaGsmf2DTS0IhERptrHru9t8QQN0L7YgxyKkA82hHuIeS+u0Yf1pRYjENk0vHOx3firvOM+Cur/F5QV4DuPgTpHUG48f+7IpN/yXmKaeR+wcSzLgb9UDZgAACGpQm0mQZK+9SAJIwcVNbS4eZLlh+ukULLLJMWP/pguEKGLa8RndT90B1NlTs/H/gadX2vi1StvVattejzaP0LKW+vjUZvYYT6w59/hf6JzcCpoVRlEUuObbc6zvxYVGdPS/9ve7wwY40J1kPAq7uRufKJJBQpSsY6jq4wtaL/8chK2xtJAqV57WHs82kkHy9w5fGelabPVGG/FLp+RT3vKnXijYeAGVqa5wpenI6tYDj4N+k76hrLb2b9Cdd1Dqtkz5lIBAK9vSqep/+u8N1mvwCrXoqEtVkUKo0PicMTjzlKOCnJrlGYgJjlJk4gPSflPHTY2MiNNaAIeXTyZVZWWnI/wtLXsoIFrlLwq8RCte165IRNLvca0afNbcrKHu5W8T+kBqz7p44xI1etKa7gLCjS92tO3phyT73IXbjjbJXwVfRra0pVAMRsu4mR6dE/TMchiUmKaD
Error: ObjectHandle is Invalid
    at oneDriveErrorResponseToError (address at index.android.bundle:1:2800555)
    at ?anon_0__loop (address at index.android.bundle:1:2803973)
    at next (native)
    at ?anon_0_ (address at index.android.bundle:1:2803098)
    at next (native)
    at fulfilled (address at index.android.bundle:1:2798637)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (address at index.android.bundle:1:218984)
    at _callTimer (address at index.android.bundle:1:217933)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:218097)
    at callReactNativeMicrotasks (address at index.android.bundle:1:220072)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:121378)
    at anonymous (address at index.android.bundle:1:120471)
    at __guard (address at index.android.bundle:1:121219)
    at flushedQueue (address at index.android.bundle:1:120382)
    at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:120325)"
01-12T09:18:20: "Error: ObjectHandle is Invalid
Code: invalidRequest
Header: {"map":{"client-request-id":"dbc9de0d-d5c5-4f5d-a6f7-1fa3a66dec05","content-type":"application/json","date":"Fri, 12 Jan 2024 08:18:19 GMT","request-id":"dbc9de0d-d5c5-4f5d-a6f7-1fa3a66dec05","strict-transport-security":"max-age=31536000","transfer-encoding":"chunked","vary":"Accept-Encoding","x-ms-ags-diagnostic":"{\"ServerInfo\":{\"DataCenter\":\"Switzerland North\",\"Slice\":\"E\",\"Ring\":\"5\",\"ScaleUnit\":\"002\",\"RoleInstance\":\"ZR2PEPF000000F8\"}}"}}
Request: GET https://graph.microsoft.com/v1.0/me/drives/b!Aud4OtrO-UKDYHz6DiRQ9KqSgBwuc2FAu3OqGfoxlpbTg9BlV3L8TqK01RvZeivY/special/approot null null {"headers":{"Authorization":"bearer EwB4A8l6BAAUs5+HQn0N+h2FxWzLS31ZgQVuHsYAASJuQimH/fboXLEQ96pUUQYbc3ScddfuIdxMKmGyKRF+2f0HZb+m7LV4MQYIl2T4w7PV1qFRq4avghCvDucYqnmIa87ei2fPZyOD1FUv3ePOD5f4cjrEkJa57B8gTvd6IZzQGxFzOXh6DZKrSXYCeFuwiuwLjquqjfhqJYIAOu5ViuboFclqQv1AsZvenaDT34pldhzE2AnUffqB1TetG5DJdJEF1go72gbfAaGsmf2DTS0IhERptrHru9t8QQN0L7YgxyKkA82hHuIeS+u0Yf1pRYjENk0vHOx3firvOM+Cur/F5QV4DuPgTpHUG48f+7IpN/yXmKaeR+wcSzLgb9UDZgAACGpQm0mQZK+9SAJIwcVNbS4eZLlh+ukULLLJMWP/pguEKGLa8RndT90B1NlTs/H/gadX2vi1StvVattejzaP0LKW+vjUZvYYT6w59/hf6JzcCpoVRlEUuObbc6zvxYVGdPS/9ve7wwY40J1kPAq7uRufKJJBQpSsY6jq4wtaL/8chK2xtJAqV57WHs82kkHy9w5fGelabPVGG/FLp+RT3vKnXijYeAGVqa5wpenI6tYDj4N+k76hrLb2b9Cdd1Dqtkz5lIBAK9vSqep/+u8N1mvwCrXoqEtVkUKo0PicMTjzlKOCnJrlGYgJjlJk4gPSflPHTY2MiNNaAIeXTyZVZWWnI/wtLXsoIFrlLwq8RCte165IRNLvca0afNbcrKHu5W8T+kBqz7p44xI1etKa7gLCjS92tO3phyT73IXbjjbJXwVfRra0pVAMRsu4mR6dE/TMchiUmKaD
Error: ObjectHandle is Invalid
    at oneDriveErrorResponseToError (address at index.android.bundle:1:2800555)
    at ?anon_0__loop (address at index.android.bundle:1:2803973)
    at next (native)
    at ?anon_0_ (address at index.android.bundle:1:2803098)
    at next (native)
    at fulfilled (address at index.android.bundle:1:2798637)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (address at index.android.bundle:1:218984)
    at _callTimer (address at index.android.bundle:1:217933)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:218097)
    at callReactNativeMicrotasks (address at index.android.bundle:1:220072)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:121378)
    at anonymous (address at index.android.bundle:1:120471)
    at __guard (address at index.android.bundle:1:121219)
    at flushedQueue (address at index.android.bundle:1:120382)
    at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:120325)"

**Comment by laurent22** [comment]
Unfortunately that seems to be a problem with OneDrive not with us, and part of the reason we'd like to discontinue OneDrive support since it's too slow and unreliable and they provide no support: https://github.com/OneDrive/onedrive-api-docs/issues/657
