### ISSUE TITLE
Remove auth info from the log

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9705]
### Operating system

Windows

### Joplin version

2.13

### Current behaviour

We should remove API auth info from the log. For example in OneDrive, the "DELETE" part should be removed.

```
01-12T09:18:23: "Could not initialise synchroniser: "
01-12T09:18:23: "Error: ObjectHandle is Invalid
Code: invalidRequest
Header: {"map":{"client-request-id":"","content-type":"application/json","date":"Fri, 12 Jan 2024 08:18:22 GMT","request-id":"","strict-transport-security":"max-age=31536000","transfer-encoding":"chunked","vary":"Accept-Encoding","x-ms-ags-diagnostic":"{"ServerInfo":{"DataCenter":"Switzerland North","Slice":"E","Ring":"5","ScaleUnit":"002","RoleInstance":""}}"}}
Request: GET https://graph.microsoft.com/v1.0/me/drives/b!/special/approot null null {"headers":{"Authorization":"__DELETE__DELETE__DELETE__DELETE__DELETE__DELETE__DELETE__DELETE__DELETE__DELETE__DELETE__DELETE__DELETE__DELETE
Error: ObjectHandle is Invalid
at oneDriveErrorResponseToError (address at index.android.bundle:1:2800555)
at ?anon_0__loop (address at index.android.bundle:1:2803973)
at next (native)
at ?anon_0_ (address at index.android.bundle:1:2803098)
at next (native)
at fulfilled (address at index.android.bundle:1:2798637)
at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
at apply (native)
at anonymous (address at index.android.bundle:1:218984)
at _callTimer (address at index.android.bundle:1:217933)
at _callReactNativeMicrotasksPass (address at index.android.bundle:1:218097)
at callReactNativeMicrotasks (address at index.android.bundle:1:220072)
at __callReactNativeMicrotasks (address at index.android.bundle:1:121378)
at anonymous (address at index.android.bundle:1:120471)
at _guard (address at index.android.bundle:1:121219)
at flushedQueue (address at index.android.bundle:1:120382)
at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:120325)"
01-12T09:18:20: "Error: ObjectHandle is Invalid
Code: invalidRequest
Header: {"map":{"client-request-id":"dbc9de0d-d5c5-4f5d-a6f7-","content-type":"application/json","date":"Fri, 12 Jan 2024 08:18:19 GMT","request-id":"dbc9de0-1fa3a66dec05","strict-transport-security":"max-age=31536000","transfer-encoding":"chunked","vary":"Accept-Encoding","x-ms-ags-diagnostic":"{"ServerInfo":{"DataCenter":"Switzerland North","Slice":"E","Ring":"5","ScaleUnit":"002","RoleInstance":""}}"}}
Request: GET https://graph.microsoft.com/v1.0/me/drives/b!Aud4OtrO-UKDYHz6DiRQ9KqSgBwuc2FAu3OqGfoxlpbTg9BlV3L8TqK01RvZeivY/special/approot null null {"headers":{"Authorization":""__DELETE__DELETE__DELETE__DELETE__DELETE__DELETE__DELETE__DELETE__DELETE__DELETE__DELETE__DELETE__DELETE__DELETE
Error: ObjectHandle is Invalid
at oneDriveErrorResponseToError (address at index.android.bundle:1:2800555)
at ?anon_0__loop (address at index.android.bundle:1:2803973)
at next (native)
at ?anon_0 (address at index.android.bundle:1:2803098)
at next (native)
at fulfilled (address at index.android.bundle:1:2798637)
at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5p1x2e66/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
at apply (native)
at anonymous (address at index.android.bundle:1:218984)
at _callTimer (address at index.android.bundle:1:217933)
at _callReactNativeMicrotasksPass (address at index.android.bundle:1:218097)
at callReactNativeMicrotasks (address at index.android.bundle:1:220072)
at __callReactNativeMicrotasks (address at index.android.bundle:1:121378)
at anonymous (address at index.android.bundle:1:120471)
at __guard (address at index.android.bundle:1:121219)
at flushedQueue (address at index.android.bundle:1:120382)
at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:120325)"
```

Also check that it's done for the other sync targets. See JoplinServerApi for an example (hidePassword method)

**Comment by laurent22** [comment]
Checked WebDAV which is fine (we hide the authorization header). OneDrive and Joplin Server are fine too.
