### ISSUE TITLE
`yarn install` fails when running `buildDefaultPlugins`

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9710]
### Operating system

Windows

### Joplin version

2.14

### Current behaviour

```
➤ YN0000: [@joplin/app-desktop]: [18:29:20] Starting 'buildDefaultPlugins'...
➤ YN0000: [@joplin/app-desktop]: [96m Building plugin io.github.jackgruber.backup at /var/folders/sz/gwmjm6v50tz_w6m131179bxw0000gn/T/default-plugin-buildSfAn23 [0m
➤ YN0000: [@joplin/app-desktop]: > git rev-parse HEAD~
➤ YN0000: [@joplin/app-desktop]: 07fafb31fe7643b5b821a5befd68be28131e0079
➤ YN0000: [@joplin/app-desktop]: [96m Switching to commit bd49c665bf60c1e0dd9b9862b2ba69cad3d4c9ae [0m
➤ YN0000: [@joplin/app-desktop]: > git switch master
➤ YN0000: [@joplin/app-mobile]: Creating: /Users/laurent/src/joplin/packages/app-mobile/lib/rnInjectedJs/CodeMirror.bundle.js
➤ YN0000: [@joplin/app-desktop]: Déjà sur 'master'
➤ YN0000: [@joplin/app-desktop]: Votre branche est à jour avec 'origin/master'.
➤ YN0000: [@joplin/app-desktop]: > git checkout bd49c665bf60c1e0dd9b9862b2ba69cad3d4c9ae
➤ YN0000: [@joplin/app-desktop]: fatal : la référence n'est pas un arbre : bd49c665bf60c1e0dd9b9862b2ba69cad3d4c9ae
➤ YN0000: [@joplin/app-mobile]: [18:29:20] Finished 'buildCodeMirrorEditor' after 1.65 s
➤ YN0000: [@joplin/app-mobile]: [18:29:20] Starting 'buildJsDrawEditor'...
➤ YN0000: [@joplin/app-desktop]: Error: Command failed with exit code 128: git checkout bd49c665bf60c1e0dd9b9862b2ba69cad3d4c9ae
➤ YN0000: [@joplin/app-desktop]: fatal : la référence n'est pas un arbre : bd49c665bf60c1e0dd9b9862b2ba69cad3d4c9ae
➤ YN0000: [@joplin/app-desktop]:     at makeError (/Users/laurent/src/joplin/packages/utils/node_modules/execa/lib/error.js:60:11)
➤ YN0000: [@joplin/app-desktop]:     at handlePromise (/Users/laurent/src/joplin/packages/utils/node_modules/execa/index.js:118:26)
➤ YN0000: [@joplin/app-desktop]:     at processTicksAndRejections (node:internal/process/task_queues:95:5) {
➤ YN0000: [@joplin/app-desktop]:   shortMessage: 'Command failed with exit code 128: git checkout bd49c665bf60c1e0dd9b9862b2ba69cad3d4c9ae',
➤ YN0000: [@joplin/app-desktop]:   command: 'git checkout bd49c665bf60c1e0dd9b9862b2ba69cad3d4c9ae',
➤ YN0000: [@joplin/app-desktop]:   escapedCommand: 'git checkout bd49c665bf60c1e0dd9b9862b2ba69cad3d4c9ae',
➤ YN0000: [@joplin/app-desktop]:   exitCode: 128,
➤ YN0000: [@joplin/app-desktop]:   signal: undefined,
➤ YN0000: [@joplin/app-desktop]:   signalDescription: undefined,
➤ YN0000: [@joplin/app-desktop]:   stdout: '',
➤ YN0000: [@joplin/app-desktop]:   stderr: "fatal : la référence n'est pas un arbre : bd49c665bf60c1e0dd9b9862b2ba69cad3d4c9ae",
➤ YN0000: [@joplin/app-desktop]:   failed: true,
➤ YN0000: [@joplin/app-desktop]:   timedOut: false,
➤ YN0000: [@joplin/app-desktop]:   isCanceled: false,
➤ YN0000: [@joplin/app-desktop]:   killed: false
➤ YN0000: [@joplin/app-desktop]: }
➤ YN0000: [@joplin/app-desktop]: Input is not from a TTY -- not waiting for input.
➤ YN0000: [@joplin/app-desktop]: Build directory /var/folders/sz/gwmjm6v50tz_w6m131179bxw0000gn/T/default-plugin-buildSfAn23
➤ YN0000: [@joplin/app-mobile]: Building bundle: svgEditorBundle...
➤ YN0000: [@joplin/app-desktop]: [96m Removed build directory [0m
➤ YN0000: [@joplin/app-desktop]: [18:29:20] 'buildDefaultPlugins' errored after 149 ms
➤ YN0000: [@joplin/app-desktop]: [18:29:20] Error: Command failed with exit code 128: git checkout bd49c665bf60c1e0dd9b9862b2ba69cad3d4c9ae
➤ YN0000: [@joplin/app-desktop]: fatal : la référence n'est pas un arbre : bd49c665bf60c1e0dd9b9862b2ba69cad3d4c9ae
➤ YN0000: [@joplin/app-desktop]:     at makeError (/Users/laurent/src/joplin/packages/utils/node_modules/execa/lib/error.js:60:11)
➤ YN0000: [@joplin/app-desktop]:     at handlePromise (/Users/laurent/src/joplin/packages/utils/node_modules/execa/index.js:118:26)
➤ YN0000: [@joplin/app-desktop]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
➤ YN0000: [@joplin/app-desktop]: [18:29:20] 'build' errored after 2.5 s
➤ YN0000: [@joplin/app-desktop]: Process exited (exit code 1), completed in 6s 373ms

```

**Comment by personalizedrefrigerator** [comment]
Thank you for letting me know!

Try deleting everything in `packages/default-plugins/plugin-sources/` &mdash; it's possible that the `default-plugins` package needs to fetch the `io.github.jackgruber.backup` from GitHub again (to find the new commit). Removing the `packages/default-plugins/plugin-sources/io.github.jackgruber.backup` should force it to clone from GitHub again.

(edit) If that's the issue, this should be fixed by 72190260b9a4a54e9b7123f6f72e35dff045b394.

**Comment by laurent22** [comment]
> Try deleting everything in `packages/default-plugins/plugin-sources/` — it's possible that the `default-plugins` package needs to fetch the `io.github.jackgruber.backup` from GitHub again (to find the new commit). Removing the `packages/default-plugins/plugin-sources/io.github.jackgruber.backup` should force it to clone from GitHub again.

Hmm, yes but shouldn't the script somehow handle this? Isn't it possible to check what commit we have and if it's outdated, the script fetches the repo again? I don't fully understand how it works but as a general rule `yarn install` should just work without having to understand what's happening in the log

**Comment by laurent22** [comment]
> If that's the issue, this should be fixed by [7219026](https://github.com/laurent22/joplin/commit/72190260b9a4a54e9b7123f6f72e35dff045b394).

Sure, I'm going to try and confirm

**Comment by personalizedrefrigerator** [comment]
>  I don't fully understand how it works but as a general rule yarn install should just work without having to understand what's happening in the log

Yes. It's a bug. (See 72190260b9a4a54e9b7123f6f72e35dff045b394 &mdash; I plan to create a pull request with it after doing some manual testing).

**Comment by laurent22** [comment]
Perfect it's building now with this change, thanks!
