### ISSUE TITLE
Rich text editor: Toggling code logs an error to the console

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#9787]
### Operating system

Linux

### Joplin version

2.14.10

### Desktop version info

Joplin 2.14.10 (dev, linux)

Client ID: a477b8fe5e4f47c886afa74c9f21afd2
Sync Version: 3
Profile Version: 45
Keychain Supported: No

Revision: 521c93d34 (pr/fix-default-plugins-build)

Simple Backup: 1.3.5

### Current behaviour

1. Select text
2. Toggle inline code with <kbd>ctrl</kbd>-<kbd>`</kbd>

Currently, the following error is logged to the console:

```error
tinymce.min.js:9 Uncaught TypeError: e.replace is not a function
    at il (tinymce.min.js:9:126975)
    at Lg (tinymce.min.js:9:192516)
    at yp (tinymce.min.js:9:197666)
    at Object.matchNode (tinymce.min.js:9:213415)
    at Object.matchNode (tinymce.min.js:9:269274)
    at tinymce.min.js:9:204508
    at I (tinymce.min.js:9:3286)
    at jp (tinymce.min.js:9:204474)
    at t (tinymce.min.js:9:225527)
    at Y (tinymce.min.js:9:2837)
```

### Expected behaviour

No error should be logged.

### Logs

<details><summary>Console</summary>

```
...

main-html.js:54 Got ipc-message: noteRenderComplete null
main-html.js:54 10:37:51: SearchEngine: Updating FTS table...
main-html.js:54 10:37:51: models/Setting: Saving settings...
main-html.js:54 10:37:51: models/Setting: Settings have been saved.
main-html.js:54 10:37:51: Updating items_normalized from {updated_time: 0, id: ''}
main-html.js:54 10:37:51: SearchEngine: Updated FTS table in 78ms. Inserted: 1. Deleted: 0
main-html.js:54 10:37:52: Saving note... {id: '625156623c8941988d00bbde365eedcb', parent_id: '03cd34b5aacc4608bf79c3a4d88e9a88', title: 'test', body: 'test\n\ntest\n\ntest\n\ntest\n\ntest'}
main-html.js:54 10:37:52: Scheduling sync operation... 15000
main-html.js:54 10:38:02: SearchEngine: Updating FTS table...
main-html.js:54 10:38:02: models/Setting: Saving settings...
main-html.js:54 10:38:02: models/Setting: Settings have been saved.
main-html.js:54 10:38:02: Updating items_normalized from {updated_time: 0, id: ''}
main-html.js:54 10:38:02: SearchEngine: Updated FTS table in 69ms. Inserted: 1. Deleted: 0
main-html.js:54 10:38:07: Preparing scheduled sync
main-html.js:54 10:38:07: Sync cancelled - no sync target is selected.
main-html.js:54 10:40:22: models/Setting: Saving settings...
main-html.js:54 10:40:22: models/Setting: Settings have been saved.
main-html.js:54 10:40:24: CommandService::execute: textCode
main-html.js:54 10:40:24: TinyMce: execCommand {name: 'textCode', value: undefined}
tinymce.min.js:9 Uncaught TypeError: e.replace is not a function
    at il (tinymce.min.js:9:126975)
    at Lg (tinymce.min.js:9:192516)
    at yp (tinymce.min.js:9:197666)
    at Object.matchNode (tinymce.min.js:9:213415)
    at Object.matchNode (tinymce.min.js:9:269274)
    at tinymce.min.js:9:204508
    at I (tinymce.min.js:9:3286)
    at jp (tinymce.min.js:9:204474)
    at t (tinymce.min.js:9:225527)
    at Y (tinymce.min.js:9:2837)
il @ tinymce.min.js:9
Lg @ tinymce.min.js:9
yp @ tinymce.min.js:9
matchNode @ tinymce.min.js:9
matchNode @ tinymce.min.js:9
(anonymous) @ tinymce.min.js:9
I @ tinymce.min.js:9
jp @ tinymce.min.js:9
t @ tinymce.min.js:9
Y @ tinymce.min.js:9
(anonymous) @ tinymce.min.js:9
ne @ tinymce.min.js:9
Ph @ tinymce.min.js:9
(anonymous) @ tinymce.min.js:9
ux.fire @ tinymce.min.js:9
fire @ tinymce.min.js:9
o1.nodeChanged @ tinymce.min.js:9
Tx.nodeChanged @ tinymce.min.js:9
(anonymous) @ tinymce.min.js:9
ux.fire @ tinymce.min.js:9
fire @ tinymce.min.js:9
lx @ tinymce.min.js:9
e @ tinymce.min.js:9
ci.executeHandlers @ tinymce.min.js:9
o @ tinymce.min.js:9
selectionchange (async)
h @ tinymce.min.js:9
Oh @ tinymce.min.js:9
toggle @ tinymce.min.js:9
toggle @ tinymce.min.js:9
J1.toggleFormat @ tinymce.min.js:9
mceToggleFormat @ tinymce.min.js:9
J1.execCommand @ tinymce.min.js:9
Tx.execCommand @ tinymce.min.js:9
(anonymous) @ TinyMCE.tsx:272
(anonymous) @ /home/builder/Documents/joplin/packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.js:8
__awaiter @ /home/builder/Documents/joplin/packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.js:4
execCommand @ TinyMCE.tsx:200
(anonymous) @ useWindowCommandHandler.ts:63
(anonymous) @ /home/builder/Documents/joplin/packages/app-desktop/gui/NoteEditor/utils/useWindowCommandHandler.js:8
__awaiter @ /home/builder/Documents/joplin/packages/app-desktop/gui/NoteEditor/utils/useWindowCommandHandler.js:4
execute @ useWindowCommandHandler.ts:37
(anonymous) @ CommandService.ts:248
(anonymous) @ /home/builder/Documents/joplin/packages/lib/services/CommandService.js:8
__awaiter @ /home/builder/Documents/joplin/packages/lib/services/CommandService.js:4
execute @ CommandService.ts:241
(anonymous) @ MenuBar.tsx:268
(anonymous) @ MenuBar.tsx:357
click @ MenuUtils.ts:85
apply @ /home/builder/Documents/joplin/packages/app-desktop/node_modules/@electron/remote/dist/src/renderer/callbacks-registry.js:54
(anonymous) @ /home/builder/Documents/joplin/packages/app-desktop/node_modules/@electron/remote/dist/src/renderer/remote.js:348
(anonymous) @ /home/builder/Documents/joplin/packages/app-desktop/node_modules/@electron/remote/dist/src/renderer/remote.js:330
emit @ node:events:513
onMessage @ node:electron/js2c/renderer_init:2
tinymce.min.js:9 Uncaught (in promise) TypeError: e.replace is not a function
    at il (tinymce.min.js:9:126975)
    at Lg (tinymce.min.js:9:192516)
    at yp (tinymce.min.js:9:197666)
    at Object.matchNode (tinymce.min.js:9:213415)
    at Object.matchNode (tinymce.min.js:9:269274)
    at tinymce.min.js:9:204508
    at I (tinymce.min.js:9:3286)
    at jp (tinymce.min.js:9:204474)
    at t (tinymce.min.js:9:225527)
    at Y (tinymce.min.js:9:2837)
il @ tinymce.min.js:9
Lg @ tinymce.min.js:9
yp @ tinymce.min.js:9
matchNode @ tinymce.min.js:9
matchNode @ tinymce.min.js:9
(anonymous) @ tinymce.min.js:9
I @ tinymce.min.js:9
jp @ tinymce.min.js:9
t @ tinymce.min.js:9
Y @ tinymce.min.js:9
(anonymous) @ tinymce.min.js:9
ne @ tinymce.min.js:9
Ph @ tinymce.min.js:9
(anonymous) @ tinymce.min.js:9
ux.fire @ tinymce.min.js:9
fire @ tinymce.min.js:9
o1.nodeChanged @ tinymce.min.js:9
Tx.nodeChanged @ tinymce.min.js:9
Oh @ tinymce.min.js:9
toggle @ tinymce.min.js:9
toggle @ tinymce.min.js:9
J1.toggleFormat @ tinymce.min.js:9
mceToggleFormat @ tinymce.min.js:9
J1.execCommand @ tinymce.min.js:9
Tx.execCommand @ tinymce.min.js:9
(anonymous) @ TinyMCE.tsx:272
(anonymous) @ /home/builder/Documents/joplin/packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.js:8
__awaiter @ /home/builder/Documents/joplin/packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.js:4
execCommand @ TinyMCE.tsx:200
(anonymous) @ useWindowCommandHandler.ts:63
(anonymous) @ /home/builder/Documents/joplin/packages/app-desktop/gui/NoteEditor/utils/useWindowCommandHandler.js:8
__awaiter @ /home/builder/Documents/joplin/packages/app-desktop/gui/NoteEditor/utils/useWindowCommandHandler.js:4
execute @ useWindowCommandHandler.ts:37
(anonymous) @ CommandService.ts:248
(anonymous) @ /home/builder/Documents/joplin/packages/lib/services/CommandService.js:8
__awaiter @ /home/builder/Documents/joplin/packages/lib/services/CommandService.js:4
execute @ CommandService.ts:241
(anonymous) @ MenuBar.tsx:268
(anonymous) @ MenuBar.tsx:357
click @ MenuUtils.ts:85
apply @ /home/builder/Documents/joplin/packages/app-desktop/node_modules/@electron/remote/dist/src/renderer/callbacks-registry.js:54
(anonymous) @ /home/builder/Documents/joplin/packages/app-desktop/node_modules/@electron/remote/dist/src/renderer/remote.js:348
(anonymous) @ /home/builder/Documents/joplin/packages/app-desktop/node_modules/@electron/remote/dist/src/renderer/remote.js:330
emit @ node:events:513
onMessage @ node:electron/js2c/renderer_init:2
tinymce.min.js:9 Uncaught TypeError: e.replace is not a function
    at il (tinymce.min.js:9:126975)
    at Lg (tinymce.min.js:9:192516)
    at yp (tinymce.min.js:9:197666)
    at Object.matchNode (tinymce.min.js:9:213415)
    at Object.matchNode (tinymce.min.js:9:269274)
    at tinymce.min.js:9:204508
    at I (tinymce.min.js:9:3286)
    at jp (tinymce.min.js:9:204474)
    at t (tinymce.min.js:9:225527)
    at Y (tinymce.min.js:9:2837)
il @ tinymce.min.js:9
Lg @ tinymce.min.js:9
yp @ tinymce.min.js:9
matchNode @ tinymce.min.js:9
matchNode @ tinymce.min.js:9
(anonymous) @ tinymce.min.js:9
I @ tinymce.min.js:9
jp @ tinymce.min.js:9
t @ tinymce.min.js:9
Y @ tinymce.min.js:9
(anonymous) @ tinymce.min.js:9
ne @ tinymce.min.js:9
Ph @ tinymce.min.js:9
(anonymous) @ tinymce.min.js:9
ux.fire @ tinymce.min.js:9
fire @ tinymce.min.js:9
o1.nodeChanged @ tinymce.min.js:9
Tx.nodeChanged @ tinymce.min.js:9
(anonymous) @ tinymce.min.js:9
ux.fire @ tinymce.min.js:9
fire @ tinymce.min.js:9
(anonymous) @ tinymce.min.js:9
add @ tinymce.min.js:9
add @ tinymce.min.js:9
a @ tinymce.min.js:9
(anonymous) @ tinymce.min.js:9
ux.fire @ tinymce.min.js:9
fire @ tinymce.min.js:9
lx @ tinymce.min.js:9
e @ tinymce.min.js:9
ci.executeHandlers @ tinymce.min.js:9
o @ tinymce.min.js:9
main-html.js:54 10:40:25: Saving note... {id: '625156623c8941988d00bbde365eedcb', parent_id: '03cd34b5aacc4608bf79c3a4d88e9a88', title: 'test', body: 'test\n\ntest\n\ntest\n\ntest\n\n`test`'}
main-html.js:54 10:40:25: Scheduling sync operation... 15000
main-html.js:54 10:40:35: SearchEngine: Updating FTS table...
main-html.js:54 10:40:36: models/Setting: Saving settings...
main-html.js:54 10:40:36: models/Setting: Settings have been saved.
main-html.js:54 10:40:36: Updating items_normalized from {updated_time: 0, id: ''}
main-html.js:54 10:40:36: SearchEngine: Updated FTS table in 70ms. Inserted: 1. Deleted: 0
main-html.js:54 10:40:40: Preparing scheduled sync
main-html.js:54 10:40:40: Sync cancelled - no sync target is selected.
```
</details>

**Comment by personalizedrefrigerator** [comment]
This should now be fixed (by https://github.com/laurent22/joplin/pull/9816).
