### ISSUE TITLE
Joplin 1.0.115 is not showing full content of the note

### ISSUE THREAD

**Issue by alexdevero** [laurent22/joplin#979]
### Operating system

- Windows

### Application

- Desktop

Version: 1.0.115

Part of the note editor, the bottom, is not visible. This is caused by newly introduced tag bar. This bug occurs on notes with tags and without tags. When note contains tags, note editor allows to scroll beyond visible area.

Screen - note without tags:
![joplin](https://user-images.githubusercontent.com/4237724/48659391-7b32a500-ea50-11e8-9d83-fbca33e9c76a.PNG)

Screen - note with tags:
![joplin-with-tags](https://user-images.githubusercontent.com/4237724/48659422-175cac00-ea51-11e8-9a21-8f1b6e1116e7.PNG)

**Comment by alexdevero** [comment]
I wanted to fix this, but build is failing:

```
C:\joplin\ElectronClient\app\node_modules\sqlite3
# if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --module=C:\joplin\ElectronClient\app\node_modules\sqlite3\lib\binding\node-v67-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\joplin\ElectronClient\app\node_modules\sqlite3\lib\binding\node-v67-win32-x64 )  else (node "" build --fallback-to-build --module=C:\joplin\ElectronClient\app\node_modules\sqlite3\lib\binding\node-v67-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\joplin\ElectronClient\app\node_modules\sqlite3\lib\binding\node-v67-win32-x64 )
gyp info it worked if it ends with ok
gypgyp info using node-gyp@3.8.0
gyp info using node@11.2.0 | win32 | x64
 info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.2.0 | win32 | x64
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  unpack_sqlite_dep
  unpack_sqlite_dep
  ImportError: No module named site
  ImportError: No module named site
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\joplin\ElectronClient\app\node_modules\sqlite3\build\deps\action_before_build.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\joplin\ElectronClient\app\node_modules\sqlite3\build\deps\action_before_build.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12) gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=E:\\Devero-Laboratories\\WEB\\clones-and-forks\\joplin\\ElectronClient\\app\\node_modules\\sqlite3\\lib\\binding\\node-v67-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=E:\\Devero-Laboratories\\WEB\\clones-and-forks\\joplin\\ElectronClient\\app\\node_modules\\sqlite3\\lib\\binding\\node-v67-win32-x64"
gyp ERR! cwd C:\joplin\ElectronClient\app\node_modules\sqlite3
gyp ERR! node -v v11.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12) gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=E:\\Devero-Laboratories\\WEB\\clones-and-forks\\joplin\\ElectronClient\\app\\node_modules\\sqlite3\\lib\\binding\\node-v67-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=E:\\Devero-Laboratories\\WEB\\clones-and-forks\\joplin\\ElectronClient\\app\\node_modules\\sqlite3\\lib\\binding\\node-v67-win32-x64"
gyp ERR! cwd C:\joplin\ElectronClient\app\node_modules\sqlite3
gyp ERR! node -v v11.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\joplin\ElectronClient\app\node_modules\sqlite3\lib\binding\node-v67-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\joplin\ElectronClient\app\node_modules\sqlite3\lib\binding\node-v67-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\joplin\ElectronClient\app\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\Devero-Laboratories\\WEB\\clones-and-forks\\joplin\\ElectronClient\\app\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\joplin\ElectronClient\app\node_modules\sqlite3
node-pre-gyp ERR! node -v v11.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\joplin\ElectronClient\app\node_modules\sqlite3\lib\binding\node-v67-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\joplin\ElectronClient\app\node_modules\sqlite3\lib\binding\node-v67-win32-x64' (1)
```
